---
title: "Homeostase"
author: "Vegard Lysne"
date: "2013.11.07"
categories: 
  - Fysiologi
---

[Tilbake til artikkelserien om menneskets fysiologi](../../fysiologi.html)

Kroppen vår består av trillioner av celler, som alle sammen bader i det samme indre miljøet. Disse cellene er stort sett bygget opp av de samme bestanddelene, og stiller de samme kravene til miljøet rundt for å overleve, og derfor har vi drøssevis med kontrollmekanismer for å holde dette mljøet så stabilt som mulig.. Overordnet omtales dette som homeostase, og det ser jeg nærmere på i dette innlegget.

Homeostase er et begrep som i humanfysiologien brukes om opprettholdelse av det indre miljøet. Selv om de ulike cellene har forskjellige funksjoner, har de også mye felles. For eksempel bruker alle cellene oksygen for å hente ut energi fra de energigivende næringsstoffene, stort sett ved nøyaktig de samme reaksjonsrekkene. Disse er beskrevet nærmere i artikkelserien om [metabolismen](http://www.friskogfunksjonell.no/metabolismen/ "Metabolismen"). Alle celler er avhengig av tilførsel av næringsstoffer og en riktig balanse av elektrolytter. Riktig surhetsgrad er også helt avgjørende for cellenes overlevelse. Alle bestanddelene i blodet og ekstracellulærvæsken holdes derfor innenfor snevre fysiologiske grenser, og de fleste organene våre bidrar til dette på ulike måter. Under følger en liten oversikt over ulike aspekter ved denne reguleringen.

## Respirasjon

Lungene har en veldig viktig funksjon når det kommer til å opprettholde nivåene av ulike gasser i blodet. Alle cellene trenger oksygen, og dette tilføres som alle vet når vi trekker pusten. Da fraktes oksygenet ned i lungene, der det lett diffunderer over i blodet hvor det binder til proteinet hemoglobin i de røde blodcellene. Når næringsstoffene brytes ned produseres karbondioksid som et biprodukt. Dette transporteres i blodet til lungene, hvor det forlater kroppen når vi puster ut. Hemoglobin har en unik evne til å endre struktur som følge av lokale endringer i oksygen- og karbondioksidnivåer. Som følge av dette bindes oksygenet enten sterkere eller svakere, noe som gjør at hemoglobinet kan frigi akkurat nok oksygen til å holde blodkonsentrasjonen på ønsket nivå.

Konsentrasjonen av karbondioksid i blodet er viktig å kontrollere for å opprettholde riktig syre/base-balanse. Når karbondioksidmengden økes, synker pH, noe som gir et surt miljø. Vi har viktige kontrollsystemer som påvirker dette, og det viktigste er at karbondioksid i blodet stimulerer respirasjonssenteret i hjernen og dermed får oss til å puste. Dette er den enkle forklaringen på hvorfor vi puster fortere når vi er fysisk aktive og derfor produserer mer karbondioksid. Det forklarer også hvorfor det er en grense for hvor lenge vi klarer å holde pusten, da dette fører til en opphopning av karbondioksid.

## Opptak, metabolisme og utskillelse

Når vi spiser så absorberer vi næringsstoffer i [tarmen](http://www.friskogfunksjonell.no/fordoyelsessystemet/ "Fordøyelsessystemet"). Da øker konsentrasjonen av de ulike næringsstoffene i blodet midlertidig, men på grunn av våre mange kontrollmekanismer så normaliseres disse raskt. For det første så reguleres selve opptaket av de ulike næringsstoffene i tarmen, noe du kan lese mer om i artikkelserien om [næringsstoffene](http://www.friskogfunksjonell.no/naeringsstoffene/ "Artikkelserie om Næringsstoffene"). For det andre har vi hormonelle responser, deriblant utskillelse av insulin, som sørger for at næringsstoffene blir tatt opp i celler og vev for å lagres. Deretter frigis de sakte og kontrollert i ettertid, slik at nivåene i blodet holdes innenfor normale grenser.

De fleste næringsstoffene fraktes til [leveren](http://www.friskogfunksjonell.no/leveren/ "Leveren – metabolismens dirigent") etter at de kommer ut i blodet, og her bearbeides de før de sendes ut igjen i blodet for å fraktes til målcellene. Leveren kontrollerer de fleste aspekter ved metabolismen, og et godt eksempel er regulering av blodsukkeret. Ved å lagre glukose som glykogen, kan leveren sørge for å frigi glukose til blodet i kontrollert tempo, slik at blodsukkeret holdes stabilt. Etter et måltid øker innlagringen (her er også muskelvevet viktig, som har stor lagringskapasitet), før frigjøringen til blodet deretter økes i fasteperioden. Leveren er også sentral i fettmetabolismen, og regulerer nivåene av frie fettsyrer i blodet ved å absorbere disse og enten bryte de ned til ketoner eller inkorporere dem i lipoproteiner. Leveren produserer de fleste blodproteinene, som er viktig for transport av mange substanser i blodet og for å opprettholde det osmotiske trykket. En funksjon som er like viktig som de foregående er modifisering av molekyler som gjør at de kan skilles ut fra kroppen, og noe skilles også ut direkte fra leveren via gallen.

Utskillelse av væske metabolitter i urinen skjer via [nyrene](http://www.friskogfunksjonell.no/nyre-2/ "Nyrene del 2 – Væskebalanse og urinproduksjon"), og dette er det viktigste reguleringspunktet for å opprettholde væskebalansen og nivåene av elektrolytter i blodet. Endepunkter fra metabolismen som kreatinin og urea, samt andre nedbrytningsprodukter skilles også ut denne veien. [Nyrene filtrerer daglig hele blodvolumet 30-40 ganger](http://www.friskogfunksjonell.no/nyre-1/ "Nyrene del 1 – Oppbygging og glomerulær filtrasjonsrate"), noe som gir gode forhold til å [kontrollere blodnivåene av metabolitter nøye](http://www.friskogfunksjonell.no/nyre-3/ "Nyrene del 3 – Elektrolyttstatus og andre funksjoner"). Ved hjelp av filtrasjon, reabsorbsjon og ekskresjon reguleres utskillelsen etter behov. Det er derfor ikke overraskende at det kan gå hardt utover den homeostatiske reguleringen om [nyrene skades](http://www.friskogfunksjonell.no/nyre-4/ "Nyrene del 4 – nyresykdom").

## Hormoner og nervesystemet

Produksjon og utskillelse av hormoner, samt nerveimpulser fra de utallige nervecellene våre er også viktig for å opprettholde homeostasen. Nerveimpulser stimuleres av reseptorer som oppfatter miljøet rundt cellene, og ved å påvirke de ulike vevene vil disse nervesignalene bidra til å gjenopprette homeostasen. Et godt eksempel på dette er blodtrykket, som styres av hvor mye blod som pumpes ut av hjertet kombinert med utvidelse/innstramming av blodårer (i tillegg til det totale blodvolumet). Disse faktorene reguleres i stor grad av nerveimpulser.

Hormoner er signalstoffer som fraktes i blodet og regulerer cellulære prosesser ved å binde til reseptorer i cellemembranen eller inne i cellen. Vi har åtte store endokrine kjertler som produserer hormoner, og produksjonen styres etter behov. Insulin er et sentralt hormon som produseres i [bukspyttkjertelen](http://www.friskogfunksjonell.no/bukspyttkjertelen/ "Bukspyttkjertelen") som følge av endringer i blodsukkeret, paratyroideahormon produseres i biskjoldbruskkjertelen som følge av lave blodnivåer av kalsium og aldosteron produseres i binyrene som følge av reduserte natriumnivåer i blodet.

Nervesystemet og hormonene styrer altså gjennom ulike mekanismer det meste som skjer i kroppen vår, og sørger for at homeostasen opprettholdes.

## Negativ og positiv feedback

De fleste reguleringsmekanismene fungerer ved det som kalles negativ feedback. Dette fungerer kort fortalt slik at en viss stimuli aktiverer prosesser som motvirker den opprinnelige stimulien. Når blodtrykket øker, aktiverer dette flere prosesser som gjør at blodtrykket synker igjen. Det samme gjelder motsatt vei. Når blodtrykket faller, eksempelvis som følge av blødning, vil det aktiveres prosesser som fører til at blodtrykket normaliseres. Øker blodsukkeret produserer vi insulin som fører til at blodsukkeret faller igjen. Når nivåene av et hormon i blodet øker, vil dette som oftest redusere produksjonen av det samme hormonet for å unngå for høy aktivitet. Alle disse er eksempler på negativ feedback siden responsen motvirker den opprinnelige endringen.

I motsatt ende har vi positiv feedback, og som navnet tilsier så handler dette om prosesser som øker effekten av den opprinnelige stimulien. Et eksempel på dette er redusert hjertefunksjon som følge av blødninger. Når blodmengden reduseres tilstrekkelig vil ikke hjertet få nok tilførsel av blod til å pumpe optimalt. Da synker blodtrykket, noe som ytterligere reduserer hjertets tilførsel av blod. I de fleste tilfeller vil altså positiv feedback føre til en stadig forverring av en tilstand, så heldigvis styres det meste med negativ feedback. Et spesifikt tilfelle der positiv feedback bidrar på gunstig måte er i sårtilheling, der aktivering av blodplater fører til at flere blodplater aktiveres. Det finnes noen andre slike eksempler, men stort sett kan disse sees på som en bestanddel av en overordnet negativ feedback, og i eksempelet med sårtilheling er dette en del av den negative feedback-mekanismen for å motvirke blodtapet.

## Avvik fra homeostase

Et friskt menneske vil klare å opprettholde homeostasen i de fleste tilfeller. I noen tilfeller kan imidlertid stimulien være så kraftig at kapasiteten for regulering overskrides, noe som fører til avvik. Et godt eksempel på en slik situasjon er kraftige blødninger. Normalt vil vi tåle å tape en del blod, ettersom vi til en viss grad kan regulere blodtrykk og hjertets funksjon til å tilpasses en lavere blodmengde. Etter hvert som vi produserer nytt blod reverseres dette, og vi fungerer igjen som normalt. Ved større blødninger kan blodtapet bli så stort at vi ikke klarer å kompensere, noe som da kan føre til større problemer og eventuelt død. Et annet eksempel er forgiftninger, der tilførselen av et stoff blir så stor at vi ikke klarer å kvitte oss med det raskt nok.

Vanligvis skyldes avvik fra homeostasen sykdom. Ved diabetes har vi for eksempel problemer med å regulere blodsukkeret, noe som også påvirker metabolismen av de øvrige næringsstoffene. Ved nyresvikt har vi problemer med utskillelsen av stoffer fra blodet, noe som påvirker konsentrasjonen av blant annet elektrolytter. Lungesykdommer kan påvirke evnen til å regulere konsentrasjonen av gasser i blodet, og leversykdom vil blant annet påvirke produksjonen av proteiner som er viktig for transport av ulike substanser i blodet. Dette er bare eksempler, og listen kunne vart i evigheter. Poenget er at sykdom påvirker evnen til å opprettholde homeostasen, noe som kan føre til store problemer eller død.

## Konklusjon

Alle kroppens celler er avhengig av et stabilt indre miljø for å fungere, og dette kalles i fysiologien for homeostase. I denne innføringen i homeostase og ulike mekanismer som sørger for denne har du sett hvordan de ulike organene og signalmåtene bidrar til å opprettholde et stabilt miljø, og dette gjør at vi er rustet til å tåle store variasjoner i det ytre miljøet.
