project:
  type: website
  render:
    - "*.qmd"
    - "!upublisert/"

website:
  title: "Frisk og Funksjonell (arkiv)"
  description: "Arkivert versjon av bloggen Frisk og Funksjonell"
  navbar:
    right:
      - text: Alle poster
        href: poster.qmd
      - text: Næringsstoffene
        href: naeringsstoffer.qmd
      - text: Metabolismen
        href: metabolismen.qmd
      - text: Fysiologi
        href: fysiologi.qmd
      - text: Hormoner
        href: hormonsystemet.qmd
      - text: Kildekritikk
        href: kildekritikk.qmd
      - text: Kosthold i helseinstitusjoner
        href: kosthold-institusjoner.qmd
      - text: Om bloggen
        href: om.qmd
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

