---
title: "Artikkelserie om menneskets fysiologi"
date: 2013.11.28
listing:
  contents: artikler/fysiologi/*.qmd
  sort: "date desc"
  type: table
  fields: [date, title, author, reading-time]
  field-display-names: 
    date: Publiseringsdato
    title: Tittel
    author: Forfatter
    reading-time: Lesetid
  categories: true
  sort-ui: false
  filter-ui: [title, description, author]
page-layout: full
title-block-banner: false
---

Fysiologi er læren om hvordan kroppen fungerer, og i denne artikkelserien vil du finne artikler som tar for seg ulike deler av menneskets fysiologi. Disse kunnskapene kan være veldig sentrale for å forstå hvordan alt henger sammen. I denne artikkelserien tar vi for oss ulike aspekter ved menneskets fysiologi som er knyttet opp mot kosthold og helse.

## Cellen og det indre miljøet

Menneskekroppen består av celler. Selv om de ulike cellene har forskjellige funksjoner er de i stor grad bygget opp av de samme elementene, og det å vite litt om hva som befinner seg inne i cellen er sentralt for forståelsen av hvordan kroppen fungerer. At cellene i stor grad er like betyr også at de er avhengig av de samme faktorene for å kunne fungere og overleve, og derfor er det også viktig at det indre miljøet holdes konstant, noe som omtales som homeostase. Les mer om disse tingene i følgende artikler:

-   [Cellen](artikler/fysiologi/cellen.qmd) (*November 2013)*

-   [Homeostase](artikler/fysiologi/homeostase.qmd) (*November 2013*)

## Lungene

Lungene er pusteorganet vårt som sørger for at vi kan tilføre kroppens celler sårt tiltrengt oksygen. I tillegg gjør lungene at vi også kan kvitte oss med gasser, noe som er svært viktig for funksjonen til alle kroppens celler.

-   [Lungene del 1 – ventilasjon og gassutveksling](artikler/fysiologi/lunge1.qmd) (*Januar 2015*)

-   [Lungene del 2 – transport av gasser og regulering av ventilasjon](artikler/fysiologi/lunge2.qmd")

## Hjertet

Hjertet er muskelen som sørger for å pumpe blodet rundt i kroppen vår. Dette er viktig for at cellene skal få tilført nødvendige ting som oksygen og næringsstoffer, og for å bli kvitt metabolitter som skal skilles ut. I følgende artikler vil du finne informasjon om hjertet.

-   [Hjertet del 1 – Anatomi og fysiologi](artikler/fysiologi/hjerte1.qmd) (*November 2013)*

-   [Hjertet del 2 – Energisubstrat, oksygenforbruk, ytelse og aktivitetsnivå](artikler/fysiologi/hjerte2.qmd) (*Desember 2013*)

-   [Hjertet del 3 – Hjertets ledningssystem](artikler/fysiologi/hjerte3.qmd) (*mars 2014)*

-   [Den aterosklerotiske prosessen](artikler/fysiologi/hjerte4.qmd) (*mars 2014*)

## Fordøyelsessystemet

Fordøyelsesprosessen starter i det vi putter maten i munnen og avsluttes nede i tarmene der vi absorberer de ulike næringsstoffene. På veien passerer maten gjennom spiserøret, magesekken, de ulike delene av tynntarmen og til slutt tykktarmen. Alle disse har viktige funksjoner som til sammen gjør at vi kan gjøre nytte av energien i maten vi spiser.

-   [Fordøyelsessystemet](artikler/fysiologi/fordoyelse.qmd) (*Desember 2011*)

## Bukspyttkjertelen

Bukspyttkjertelen er en kjertel som kan deles inn i to deler. Den endokrine delen produserer hormoner som insulin og glukagon, mens den eksokrine delen produserer fordøyelsesenzymer som hjelper oss å fordøye og absorbere maten vi spiser. Sykdom eller skade på bukspyttkjertelen har et bredt spekter av konsekvenser, som i stor grad handler om fordøyelsen.

-   [Bukspyttkjertelen](artikler/fysiologi/bukspyttkjertel.qmd) (*Oktober 2013*)

## Leveren

Leveren er den store dirigenten i metabolismen vår. Nesten alt som absorberes i tarmen vil fraktes til leveren, og hva som sendes ut i blodet herfra er avgjørende både for hva som befinner seg i blodet og ikke minst hva som kommer frem til cellene. Sykdom eller skade på leveren kan ha mange konsekvenser.

-   [Leveren – metabolismens dirigent](artikler/fysiologi/lever.qmd) (*Juli 2013*)

## Nyrene

Nyrene er et svært nyttig organ som har som hovedoppgave å filtrere blodet vårt og produsere urin. På denne måten regulerer nyrene væskebalansen i kroppen og blodkonsentrasjonen av de ulike stoffene.  I tillegg har de også en rekke andre oppgaver. Alle de viktige funksjonene gjør at skade eller sykdom kan være svært skummelt. Informasjon om nyrene finner du i følgende artikler:

-   [Nyrene del 1 – Oppbygging og glomerulær filtrasjonsrate](artikler/fysiologi/nyre1.qmd) (*Juli 2013)*

-   [Nyrene del 2 – Væskebalanse og urinproduksjon](artikler/fysiologi/nyre2.qmd) (*Juli 2013)*

-   [Nyrene del 3 – Elektrolyttstatus og andre funksjoner](artikler/fysiologi/nyre3.qmd) (*August 2013*)

-   [Nyrene del 4 – Nyresykdom](artikler/fysiologi/nyre4.qmd) (*September 2013*)

Sammen med lungene er nyrene helt sentrale for å regulere syre/base-status i kroppen, noe du kan lese mer om i følgende artikkel:

-   Regulering av syre/base-balansen (kommer)

I arbeidet med denne artikkelserien har vi først og fremst tatt utgangspunkt i lærebøker i både fysiologi (1), biokjemi (2) og ernæring (3).

**Referanser**

1.  Guyton A, Hall J: Textbook of Medical Physiology, 12 edn: Saunders/Elsevier; 2011.

2.  Berg JM, Tymoczko JL, Stryer L (eds.): Biochemistry, 6 edn: Freeman; 2007.

3.  Erdman JW, Macdonald IA, Zeisel SH (eds.): Present Knowledge in Nutrition, 10 edn: Wiley-Blackwell; 2012.
