---
title: "Artikkelserie om metabolismen"
date: 2012.01.16
listing:
  contents: artikler/metabolismen/*.qmd
  sort: "date desc"
  type: table
  fields: [date, title, author, reading-time]
  field-display-names: 
    date: Publiseringsdato
    title: Tittel
    author: Forfatter
    reading-time: Lesetid
  categories: false
  sort-ui: false
  filter-ui: [title, description, author]
page-layout: full
title-block-banner: false
---

Metabolismen er en fellesbenevnelse for de prosessene som foregår i kroppen som omhandler næringsstoffene. I denne artikkelserien får du et overblikk over hvilke prosesser som inngår i metabolismen, hvordan disse fungerer og hva som stimulerer de. Dette inkluderer metabolismen av de energigivende næringsstoffene og relaterte prosesser, artikler om sykdommer tilknyttet disse prosessene og metabolske endringer i ulike situasjoner som ved sykdom eller fysisk aktivitet.

## ATP og energilagre

Kroppens primære energimolekyl heter adenosintrifosfat, forkortet ATP. Trifosfat (TP) betyr at det er bundet tre fosfatgrupper til adenosinmolekylet. Ved å spalte av en fosfatgruppe frigjøres det energi, og ATP blir da redusert til adenosindifosfat, ADP. For å redanne ATP henter vi energi fra de energigivende næringsstoffene, som avgir energi når de brytes ned. Adenosinmonofosfat, AMP, produseres når det spaltes av en fosfatgruppe fra ADP.

Vi har også egne lagre av de energigivende næringsstoffene [karbohydrater](artikler/naeringsstoffer/karbohydrater.qmd) og [fett](artikler/naeringsstoffer/fett.qmd). Karbohydrater lagres i form av glykogen, noe som skjer både i muskelvev og i leveren. Fett lagres først og fremst i fettvevet, som er vårt desidert største energilager.

For å danne ATP fra nedbrytningsproduktene av næringsstoffene, har vi noen viktige prosesser, nemlig sitronsyresyklusen og elektrontransportkjeden. Det er ved hjelp av disse at energien i næringsstoffene blir overført til ATP-molekylet. Disse er utdypet i følgende artikler (sist oppdatert):

-   [Sitronsyresyklusen](artikler/metabolismen/sitronsyresyklusen.qmd) *(januar 2012)*

-   [Elektrontransportkjeden](artikler/metabolismen/elektrontransportkjeden.qmd) *(februar 2012)*

## Energimetabolismen

I [artikkelserien om næringsstoffene](naeringsstoffer.qmd) fikk du en innføring i hvordan de ulike næringsstoffene ble tatt opp i tarmen og fraktet til målcellen, så her tar vi det et steg videre og ser på hva som skjer inne i cellene når de energigivende næringsstoffene skal frigi energi som cellene kan bruke.

#### Karbohydrater

Karbohydratmetabolismen omhandler kroppens bearbeiding av de ulike karbohydratene. Det mest sentrale molekylet er glukose, som er en viktig energikilde. De andre monosakkaridene, fruktose og galaktose, metaboliseres gjennom egne metabolske veier. Glykogenmetabolismen inkluderer lagring av glukosemolekyler som glykogen og den påfølgende frigjøringen. Metabolismen av karbohydrater er videre beskrevet i følgende artikler (sist oppdatert):

-   [Glukosemetabolismen](artikler/metabolismen/glukosemetabolismen.qmd) *(august 2013)*

-   [Fruktose- og galaktosemetabolismen](artikler/metabolismen/fruktose-galaktose.qmd) *(august 2013)*

-   [Glykogenmetabolismen](artikler/metabolismen/glykogenmetabolismen.qmd) (*august 2013)*

#### Protein

Protein består av aminosyrer. Vi har både essensielle aminosyrer, som vi må få i oss gjennom maten vi spiser, og ikke-essensielle aminosyrer som vi i utgangspunktet kan produsere selv. Proteinmetabolismen er kompleks, men i de følgende artiklene finner du mer informasjon om henholdsvis syntese og nedbrytning av proteiner og aminosyrer (sist oppdatert):

-   [Aminosyre- og proteinsyntese](artikler/metabolismen/aminosyrer.qmd)

-   [Proteinmetabolismen](artikler/metabolismen/proteinmetabolismen.qmd)

#### Fett

Fettmetabolismen er omfattende. Vi kan selv produsere fettsyrer i leveren (fettsyresyntese), og β-oksidasjon er prosessen der vi bryter ned fettsyrer for å produsere ATP. I tillegg til dette har vi en rekke enzymer som er involvert i metabolismen av flerumettede fettsyrer (omega-3 og omega-6). Disse gir også opphav til hormonlignende signalstoffer som heter eikosanoider. Ketonlegemer er et vannløselig biprodukt av fettsyrenedbrytning, som kan sendes ut i blodet og benyttes som et energimolekyl rundt i kroppen. Fettløselige stoffer i blodet fraktes hovedsakelig bundet til lipoproteiner. De ulike aspektene av fettmetabolismen er utdypet i følgende artikler (sist oppdatert):

-   [Fettsyrenedbrytning – β-oksidasjon](artikler/metabolismen/fettsyrenedbrytning.qmd) (*august 2013)*

-   [Fettsyresyntese](artikler/metabolismen/fettsyresyntese.qmd) *(august 2013)*

-   [Langkjedede og flerumettede fettsyrer](artikler/metabolismen/langkjedede-flerumettede.qmd) (*august 2013)*

-   [Eikosanoider](artikler/metabolismen/eikosanoider.qmd) (*mars 2015*)

-   [Ketonmetabolismen](artikler/metabolismen/ketonmetabolismen.qmd) (*september 2013)*

-   [Kolesterolmetabolismen](artikler/metabolismen/kolesterolmetabolismen.qmd) (*Oktober 2013)*

-   [Lipoproteinmetabolismen](artikler/metabolismen/lipoproteinmetabolismen.qmd) (*November 2013*)

## Metabolske sykdommer

Metabolske sykdommer skyldes medfødte genetiske abnormaliteter. Disse rammer som oftest viktige enzymer som er viktige for å metabolisere en forbindelse, og mangel på enzym fører til at denne forbindelsen hoper seg opp. Det kliniske bildet av disse sykdommene kan variere mye, spesielt som følge av hvorvidt det er fullstendig mangel på enzym eller om produksjonen bare er kraftig redusert. I de følgende artiklene får du en innføring i genetikk og deretter mer spesifikt om ulike klasser av metabolske sykdommer.

-   [Genetikk og epigenetikk](artikler/metabolismen/genetikk.qmd) (*Januar 2013*)

-   [Prinsippene bak metabolske sykdommer](artikler/metabolismen/metabolskesykdommer.qmd) (*Januar 2013*)

-   [Medfødte sykdommer i karbohydratmetabolismen](artikler/metabolismen/sykdommer-karbohydrat.qmd) (*August 2013)*

-   Sykdommer i proteinmetabolismen

-   Sykdommer i fettmetabolismen

-   Sykdommer i lipoproteinmetabolismen

## Sult- og stressmetabolisme

Dersom vi over tid spiser lite eller ingenting, skjer det tilpasninger i kroppen. Dette er helt nødvendig for at vi skal kunne overleve og fungere i en slik situasjon. Ved skader og sykdom kan det også forekomme tilpasninger, kalt stressmetabolisme. I de følgende artiklene er dette utdypet.

-   Sult/fastemetabolisme

-   Stressmetabolisme

## Metabolisme under fysisk aktivitet

Ernæring, idrett og prestasjon går hånd i hånd, men generelt sett er det lite fokus på hvordan de ulike næringsstoffene metaboliseres under aktivitet. Her kan vi skille mellom det som kalles aerob forbrenning, der vi har nok oksygen tilgjengelig til å forbrenne karbohydrater og fett fullstendig, og anaerob forbrenning, der energiproduksjonen går så fort at vi ikke rekker å tilføre nok oksygen. Det skjer også en tilpasning i forbruket av de ulike næringsstoffene. Dette vil bli utdypet i følgende artikler (sist oppdatert):

-   Aerob og anaerob metabolisme

-   [Karbohydrater under fysisk aktivitet](artikler/metabolismen/fysak-karbohydrat.qmd) (*oktober 2013*)

-   [Protein under fysisk aktivitet](artikler/metabolismen/fysak-protein.qmd) (*April 2014*)

-   Fett under fysisk aktivitet

-   Regulering av energisubstrat under fysisk aktivitet

I arbeidet med denne artikkelserien er det benyttet fagbøker i biokjemi (1,2), metabolisme (3), fysiologi (4) og ernæring (5,6,7,8). Artiklene er skrevet av Vegard Lysne og Thomas Olsen.

**Referanser**

1.  Champe PC, Harvey RA, Ferrier DR (eds.): **Biochemistry**, 4 edn: Lippincott Williams&Wilkins; 2008.

2.  Berg JM, Tymoczko JL, Stryer L (eds.): **Biochemistry**, 6 edn: Freeman; 2007.

3.  Frayn KN: **Metabolic Regulation**, 3 edn: Wiley-Blackwell; 2010.

4.  Guyton A, Hall J: **Textbook of Medical Physiology**, 12 edn: Saunders/Elsevier; 2011.

5.  Erdman JW, Macdonald IA, Zeisel SH (eds.): **Present Knowledge in Nutrition**, 10 edn: Wiley-Blackwell; 2012.

6.  Shils M, Shike M, Ross A, Caballero B, Cousins R: **Modern Nutrition, In Health And Disease**, 10 edn: Lippincott Williams&Wilkins; 2005.

7.  Shaw V, Lawson M: **Clinical Paedriatric Dietetics**: Blackwell Publishing; 2007.

8.  Kang J: Nutrition and Metabolism in Sports, Exercise and Health, 1st end: Routledge; 2012
