---
title: "Om Frisk og Funksjonell"
date: "2011.10.14"
author: "Vegard"
---

Frisk og funksjonell er en blogg som omhandler temaene kosthold, trening og helse. Våre skribenter er hovedsakelig studenter innen ulike helsefag, noe som gir et bredt kompetansefelt. I tillegg til informative artikler vil vi også i egne innlegg omtale nyere studier og kommentere ting som dukker opp i media.

**Frisk og Funksjonell er et 100% ikke-kommersielt nettsted, og verken skribenter eller bloggeier har noen form for inntekt/utbytte fra siden.**

Vi er ikke en fasit, og oppfordrer til å lese all informasjon med kritiske øyne. Temaene vi skriver om tilhører et levende fagfelt, og etterhvert som det kommer ny informasjon til er vi helt åpne for at ting vi har skrevet tidligere kan være utdatert eller til og med vise seg å være feil. Det er en del av prosessen, og vi ønsker å hele tiden strebe etter å holde oss oppdaterte.

### Redaksjonen:

Vegard Lysne (grunnlegger), Thomas Olsen, Andreas Wahl Blomkvist, Andrea Rørvik Marti.

### Andre bidragsytere:

Torbjørn Lysne, Mari Kalland Knapstad, Asle Bøe, Martin Hole Hanstveit, Eivind Eliasson, Erik Arnesen, Ingvild Thun, Stine Malvik, Monica Linnea Ones, Hanne Storhaug, Martin Norum, Kristian Fagerland
