---
title: "Proteinmetabolismen under trening"
author: "Thomas Olsen"
date: "2014.04.07"
categories: 
  - Metabolismen
---

[Tilbake til artikkelserien om metabolismen](../../metabolismen.html)

Proteiner er et hovednæringsstoffene som blir mest diskutert både før og etter trening og tilskrives allskens effekter, deriblant prestasjonsfremming. Generelt har protein en rekke funksjoner i kroppen, og i tillegg til å være en sentral byggestein fungerer proteiner som enzymer (katalyserer kjemiske reaksjoner) og bidrar til transport og lagring (eksempelvis oksygen og jern, henholdsvis). I tillegg er det en viktig bestanddel av hormoner som utøver signalisering og setter i gang ulike cellulære funksjoner. Under aktivitet vil visse typer proteiner (aktin og myosin) få musklene våre til å trekke seg sammen. I denne artikkelen ser jeg nærmere på hva den metabolske rollen til proteiner er i forbindelse med ulike typer fysisk aktivitet.

## Protein turnover

Proteinene i kroppen vår er en kontinuerlig del av et kretsløp som består av syntese, forbruk og påfølgende nedbrytning. Dette krever energi og man estimerer at rundt 20% av energiforbruket vårt i hvile går med til protein turnover. Syntese følger degradering, og halveringstiden varierer fra protein til protein (fra minutter til uker). I musklene som arbeider under fysisk aktivitet, er det et økt behov. Den økte syntesen av mitokondrielle proteiner som gjør at kroppens celler i større grad kan syntetisere ATP via oksidativ fosforylering vil blant annet gi oss bedre utholdenhet. På den andre siden er det en økt syntese av myofibrillære muskelfibre som følge av styrketrening som resulterer i såkalt hypertrofi, altså muskelvekst. Disse prosessene er begge et resultat av at proteinsyntesen overgår nedbrytningen. Skulle nedbrytningen overgå syntese, kalles dette atrofi.

Helkropps-turnover av protein skjer hurtig og avhenger ikke bare av fysisk aktivitet men også en rekke andre prosesser. Det er med andre ord svært viktig at man tilfører essensielle aminosyrer gjennom kostholdet slik at man i noenlunde grad sørger for at ligningen går i favør syntese kontra nedbrytning. Både idrettsutøvere og mosjonister med høyt aktivitetsnivå øker derfor proteininntaket sitt slik at nedbrytningen av proteiner ikke overgår syntesen. Når proteiner nedbrytes frigis det aminosyrer som kan brukes som energi. Når det er sagt, er ikke proteiner og aminosyrer primære energisubstrat og brukes først når tilgjengeligheten på glukose er for lav eller metaboliseringen av fettvev går for tregt.

## Aminosyrelageret

Etter proteiner konsumeres og brytes ned i tarmene før absorpsjon, transporteres disse med blodet rundt til ulike vev (hovedsakelig skjelettmuskulatur og lever). Skjelettmuskulatur inneholder den største andelen proteinbundne og frie aminosyrer, mens leveren er det mest aktive organet vi har når det gjelder metabolismen av aminosyrene. De frie aminosyrene man finner i blodet (via syntese, mat eller nedbrytning) og i ekstracellulærvæsker kalles aminosyrelageret. Aminosyrene som ikke brukes til syntese av proteiner vil avhengig av energistatus, forbrukes som energi via [sitronsyresyklusen](sitronsyresyklusen.qmd "Sitronsyresyklusen"), eller brukes til å danne glukose (glukogene aminosyrer)

## Proteinmetabolisme under trening

Som nevnt over vil ikke proteiner eller aminosyrer forbrukes i spesielt stor grad under trening og kun 5-15% går med til energiproduksjon. Skjelettmuskulaturen inneholder to typer proteiner, nemlig kontraktile og ikke-kontraktile proteiner. Disse subgruppene er henholdsvis ansvarlig for muskelkontraksjon og en rekke andre cellulære funksjoner i muskelcellene. Metabolismen av intramuskulære proteiner er mer kompleks enn man skulle tro. Det er bred enighet om at ikke-kontraktile proteiner kan brytes ned ved intens trening, og dette ser man blant annet ved å måle frigjøring av aminosyrene tyrosin, fenylalanin, samt oksidasjon av den forgrenede aminosyren leucin.

Når det gjelder kontraktile proteiner derimot, er det 3-metylhistidine (3-MH) som i størst grad blir brukt som markør på nedbrytning av kontraktilt protein under aktivitet, men det har senere vært vist at produksjonen 3-MH faktisk er nedregulert under trening og *øker* ved restitusjon. Det er uklart hvorfor akkurat dette skjer. Denne modifiserte aminosyren dannes utelukkende i muskelvev, og mål av denne i blodet er derfor et godt mål på nedbrytning av kontraktile proteiner.

## Nitrogenbalanse

Vurdering av proteinnedbrytning vs syntese (se avsnittet om protein turnover) vil være av interesse for å bestemme om de av oss som er fysisk aktive behøver et høyere proteininntak for å forhindre muskelnedbrytning. Proteiner inneholder grunnstoffet nitrogen som ikke kan brytes ned av kroppen, og skilles derfor ut som urea (nitrogen + hydrogen) i urin. Nitrogenbalanse vil oppstå når inntak matcher utskillelse, og en positiv nitrogenbalanse oppstår følgelig når inntak overgår utskillelse. Ved positiv nitrogenbalanse vil overskuddsprotein blant annet brukes til å reparere skadet ved. I negativ nitrogenbalanse overgår proteintapet inntaket, og dette kan man se ved vektnedgang såvel som ved underernæring og spiseforstyrrelser.

Trening med høy intensitet over tid kan også føre til negativ nitrogenbalanse og overtrening som igjen legger til rette for råd om økt inntak hos dem det gjelder (1.2-1.4 g/kg kroppsvekt for utholdenhetsutøvere og 1.6-1.8 g/kg kroppsvekt hos styrketrenende).

## Energimetabolisme fra aminosyrer

Protein fra kosten, aminosyrelageret og endogent vevsprotein er tre viktige kilder til energi fra protein. For at aminosyrer skal kunne metaboliseres til energi må de igjennom prosesser som kalles *transaminering* og *oksidativ deanimering.* Et vanlig eksempel på dette er overføringen av et nitrogenholdig molekyl (amin) fra glutamat til pyruvat. Dette produserer aminosyren alanin som igjen kan gå inn i nydannelsen av glukose via en reaksjon som kalles alanin-syklusen. Nitrogenresten vil omdannes til urea ved hjelp av deanimering i leveren og skilles ut. Det resterende karbonskjelettet kan videre benyttes i sitronsyresyklusen.

Alt i alt kan aminosyrer gi opphav til pyruvat (glukolyse), acetyl-CoA (energimetabolisme), oxaloacetat, fumarat, succinyl-CoA og a-ketoglutarate (sitronsyresyklusen). En annen måte aminosyrer kan bidra er ved å inngå i [glukoneogenesen](glukosemetabolismen.qmd "Glukosemetabolismen").

## Rollen til de forgrenede aminosyrene

Leucin, isoleucin og valin utgjør de forgrenede aminosyrene (BCAA). Disse er essensielle og må altså konsumeres via kosten. De forgrenede aminosyrene brytes hovedsakelig ned i skjelettmuskulatur og kan via glutamat produsere alanin. Tilskudd av BCAA er omdiskutert, og blir blant annet påstått å forhindre proteintap samt redusere utmattelse. Sistnevnte ser ut til å komme av at det inhiberer opptak av tryptofan via blod-hjerne barrieren og dermed hindre produksjon av serotonin som man tror spiller en rolle i utmattelse. Således vil tilskudd av BCAA kunne utsette utmattelse, noe som også er vist i studier. Det åpner også for at inntak av aminosyren før trening vil kunne forhindre prestasjon ved å øke serotoninproduksjon. Det er det derimot ikke håndfaste bevis for enda, og det er viktig å huske på at både forgrenede aminosyrer og tryptofan har andre funksjoner, andre steder enn i hjernen. En annen faktor som kan være av betydning er at BCAA er en foretrukket energikilde under aktivitet, og det er antatt at omtrent 6% av energien hentes fra nedbrytning av disse aminosyrene.
