---
title: "Karbohydratforbruk under trening"
author: "Thomas Olsen"
date: "2013.10.28"
categories: 
  - Metabolismen
---

[Tilbake til artikkelserien om metabolismen](../../metabolismen.html)

Omsetningen av næringsstoffer under fysisk aktivitet og trening avhenger av hvilken type aktivitet man bedriver, intensitet og varighet. Energiomsetningen vil øke som følge av økt energibehov og forbruk. Ved tung/intens trening vil energiforbruket kunne øke hele 15-20 ganger hvileforbruket for å øke ATP-produksjon i arbeidende muskler. ATP er kroppens primære energimolekyl og produseres via nedbrytning av energilagrene i kroppen og via proteiner, karbohydrater og fett som konsumeres daglig gjennom mat. Med andre ord er det ikke så vanskelig å tenke seg til at maten vi spiser og prestasjoner både på trening og i konkurranse henger sammen. I denne artikkelen ser jeg nærmere på hvordan karbohydratmetabolismen oppfører seg under fysisk aktivitet.

Relevante artikler

-   [Karbohydrater](http://www.friskogfunksjonell.no/karbohydrater/ "Karbohydrater")
-   [Glukosemetabolismen](http://www.friskogfunksjonell.no/glukosemetabolismen/ "Glukosemetabolismen")
-   [Glykogenmetabolismen](http://www.friskogfunksjonell.no/glykogenmetabolismen/ "Glykogenmetabolismen")

## Karbohydrater - Vårt primære energisubstrat

Til tross for en del debatt om hva kroppen forbruker av energi under aktivitet, vil karbohydrater være foretrukket ved høy intensitet på generell basis (Før dere spør; fettadaptasjon vil diskuteres i artikkelen om fett). Hovedgrunnen til det er at man kan hente ut energi hurtig fra karbohydrater under både aerobe (med oksygen) og anaerobe (uten oksygen) forhold.

Glykogen, lagringsformen for glukose, mobiliseres raskt og effektivt under aktivitet. Da frigjøres glukosemolekyler, som deretter gjennom glykolysen bidrar til ATP-produksjon. Viktigheten av kroppens glykogenlagre kan demonstreres ved at utmattelse ofte kommer som en konsekvens av tomme glykogenlagre og hypoglykemi (lavt blodsukker).

Under oppstart av trening vil forbruket av muskelglykogen være høyt, da dette er lett tilgjengelig energi. Vi har imidlertid en energikilde som er enda raskere, nemlig kreatinfosfat. Kreatinfosfat kan donere en fosfatgruppe til ADP, og dermed bidra til hurtig regenerering av ATP under aktivitet med høy intensitet. Lagrene i muskelvevet er små, og brukes opp på kort tid ved denne typen aktivitet. Tidligere trodde man at glykogen ikke ble brutt ned før etter denne innledningsfasen, mens det kan se ut som at en viss prosentandél glykogen (15-25%) brytes ned parallellt med forbruk av kreatinfosfat.

## Effekt av intensitet og varighet

Under trening med høy intensitet, og når oksygenopptaket etter hvert ikke strekker til, vil lever- og muskelglykogen brytes ned i enda større grad. Dette er fordi glykolysen ikke er avhengig av oksygen i motsetning til sitronsyresyklusen og elektrontransportkjeden. Dersom det ikke er nok oksygen tilgjengelig til at pyruvat, endepunktet i glykolysen, kan metaboliseres videre i sitronsyresyklusen, kan det fermenteres videre og danne melkesyre. Dette gir mindre energi enn en fullstendig oksidativ forbrenning, men går til gjengjeld raskere.

Glykogennedbrytning er som sagt høyest tidlig under treningsøkten. Etterhvert som kroppen kommer i gang vil forbruket av glykogen flate ut, men når intensiteten øker, vil glykogennedbrytningen øke proporsjonalt. Ved økende varighet synker nedbrytningen av muskelglykogen samtidig som at økt blodsukker via glykogenolyse i lever kompenserer for dette og øker sitt bidraget til de arbeidende musklene. Det har tidligere blitt estimert at trening over to timer tømmer glykogenlagre i både muskler og lever.

Ved fysisk aktivitet av moderat natur er tapet av kreatinfosfat mindre, og muskelglykogen bidrar med en mye høyere prosentandèl innledningsvis. Når «steady-state»-intensitet er oppnådd deler både lever- og muskelglykogen samt oksidasjon av fettsyrer hovedansvaret for energiproduksjon, fordelingen er dog helt avhengig av intensitet og treningsbakgrunn. Etter hvert som muskelglykogenet tømmes, og blodsukker via glykogenolyse i lever tar over som energikilde, vil også oksidasjonen av fettsyrer øke. Her vil flere kanskje oppleve at intensiteten svekkes, noe som er fordi fett vanligvis omsettes tregere enn glukose og glukoseopptaket i muskler fra blodet ikke er tilstrekkelig til å dekke behovene.

## Glykogenolyse i lever

Frigjøring av glukose fra lever vil øke etterhvert som glykogenlagrene i lever tømmes for å opprettholde blodsukker og for å kompensere for tømming av glykogenlagre i muskler (muskler kan ikke produsere glukose). Denne frigjøringen øker 3-6 ganger sammenlignet med hvile.

Ved moderat intensitet holdes blodsukkeret relativt konstant til tross for økt forbruk av arbeidende muskler, og hypoglykemi vil ikke intreffe før etter flere timer med trening (med forutsetningen om at glykogenlagrene er fulle før trening). Blodsukkernivået vil med andre ord reflektere en balanse mellom hepatisk glukosefrigjøring og forbruk i muskler, og ved moderat intensitet vil denne balansen være stabil. Ved økt intensitet vil balansen øke i favør blodsukker, ettersom glykogenolysen i lever vil øke som følge av feedback fra det sentrale nervesystemet. Over lengre perioder med høy intensitet vil denne balansen derimot svekkes når produksjonen av glukose i lever ikke lenger kan matche forbruket i muskler.

## Glukoneogenese i lever

Glukoneogenesen (nydannelse av glukose) i lever vil også øke under aktivitet, og innebærer nydannelse av glukose fra aminosyrer, glyserol (bestanddel av triglyserider) og melkesyre (laktat). Sistnevnte er en mekanisme som lar oss utnytte energien i melkesyren som dannes under anaerob forbrenning av glukose i musklene. Denne melkesyren fraktes i blodet til leveren, der det produseres ny glukose, og denne prosessen kalles Cori syklus. Den nydannede glukosen kan frigjøres til blodet og transporteres til muskler for energiproduksjon. Generelt sett er dette sett på som et mer effektivt bidrag til leverens glukosefrigjøring under trening kontra hepatisk glykogenolyse. Glukoneogenese spiller dog først en rolle etter at treningen har pågått en stund.

På generell basis, dersom trening foregår under anaerob terskel (over denne vil melkesyreproduksjonen øke drastisk), er glyserol foretrukket molekyl for glukoneogenese. Dette gir mening ettersom nedbrytningen av fett er mer effektiv ved moderat intensitet, mens produksjonen av melkesyre vil øke når man kommer over anaerob terskel og være primært substrat for glukoneogenese. Økt bidrag fra glukogene aminosyrer som alanin ser man først under harde, lange økter.

De neste artiklene i serien vil fokusere på proteiner, fett og regulering av hvilke næringsstoffer som brukes som substrat.

Takk til Vegard Lysne for innspill til denne saken, som først og fremst er basert på informasjon fra boken *Nutrition and Metabolism in Sports, Exercise and Health*.
