---
title: "Energi- og næringstett kost"
date: 2012.10.14
---

Tilbake til [kosthold i helseinstitusjoner](../../kosthold-institusjoner.qmd "Kosthold i helseinstitusjoner").

De som av ulike grunner ikke klarer å dekke energibehovene sine gjennom [nøkkelrådskost](brokenlink/nokkelradskost/ "Nøkkelrådskost") kan prøve å komme i mål med energi- og næringstett kost (EN-kost). Kort fortalt er målet å dekke energibehovene på en mindre mengde mat. EN-kost er den andre standardkosten som brukes i helseinstitusjoner i dag.

Energi- og næringsrik kost inngår i serien [kosthold i helseinstitusjoner](brokenlink/kosthold-i-helseinstitusjoner/ "Kosthold i helseinstitusjoner").

Sammenlignet med nøkkelrådskosten inneholder EN-kost litt mindre karbohydrater (40-50 E%), litt mer fett (35-40 E%) og omtrent samme mengde protein (15-20 E%). Det legges også opp til flere måltider, normalt sett 4 hovedmåltider og 2 mellommåltider. Dette er nyttig for å gjøre det enklere å få i seg tilstrekkelig energi. Mengden grønnsaker og frukt reduseres kraftig når man følger EN-kost. Dette er fordi disse matvarene gir lite energi og stort volum, og i så måte virker mot sin hensikt når målet er å begrense volumet av maten.

## Hvem skal bruke EN-kost?

Som nevnt er dette et kosthold for de som av ulike grunner ikke får i seg nok mat med nøkkelrådskost. Alle som er i risiko for underernæring bør anbefales denne kosten, eksempelvis eldre, funksjonshemmede eller kronisk syke. Under sykdom kan energibehovet være økt, og det kan være nyttig å endre kosten i denne retningen.

Friske som har et høyt energibehov, deriblant idrettsutøvere, kan med fordel velge et mer energitett kosthold for å dekke behovene sine, men ikke på bekostning av frukt og grønnsaker.

Husk at EN-kost i utgangspunktet er beregnet på folk som sliter med å få i seg nok mat, og anbefalingene tar utgangspunkt i dette. Det er ikke meningen at friske skal følge de konkrete anbefalingene bokstavelig, men de kan være veldig nyttig i en pasientsituasjon.

## Matvarevalg

-   Det anbefales å velge mindre grove kornprodukter enn ved nøkkelrådskost, siden disse metter mindre og dermed er lettere å spise mer av. Bruk godt med brødfett og gjerne energirikt pålegg som ost og makrell-i-tomat.

-   Helfete meieriprodukter er anbefalt. Disse kan også brukes for å øke energiinnholdet i andre retter. Bytt gjerne ut vann som drikke med energiholdige alternativer som jus og saft.

-   Egg er en næringsrik matvare som fint kan inngå daglig. Egg kan også brukes for å berike andre matretter.

-   Velg fetere kjøttprodukter enn det som er tilfelle for nøkkelrådskost, og fet fisk er selvfølgelig også anbefalt.

-   Frukt og grønnsaker bør begrenses, men ikke kuttes ut. Lag gjerne smoothier eller pureer som kan berikes med fløte, smør eller olje for å øke energitettheten.

-   Nøtter er energirike og passer fint som mellommåltid på EN-kost.

## Utfordringer

Det kan være vanskelig å dekke behovene for enkelte næringsstoffer, spesielt om det totale energiinntaket er lavt. Dette gjelder spesielt næringsstoffene der frukt og grønnsaker er hovedkilden, som kalium, folat, magnesium og c-vitamin. På et høyere energiinntak burde ikke dette være et problem, men ved lavt inntak bør det vurderes om det er nødvendig med kosttilskudd.

Det kan være lett å komme høyt på fettinntaket. For å komme innenfor anbefalingene er det nyttig å bruke sukker/honning til å berike mat, samt å benytte seg av karbohydratholdige drikkevarer for å få i seg mer karbohydrater.

## Måltidseksempler

Frokost: Havregrøt beriket med fløte, honning og smør eller egg og bacon.

Lunsj: Brødmat med makrell-i-tomat og majones. Helmelk som drikke

Middag: Fisk eller kjøtt med beriket potetmos og løk

Kveldsmat: Smoothie

Mellommåltid: Vaniljekesam eller yoghurt med nøtteblanding, yoghurt beriket med fløte eller olje, nøtter.

Tilbake til [kosthold i helseinstitusjoner](brokenlink/kosthold-i-helseinstitusjoner/ "Kosthold i helseinstitusjoner")
