---
title: "Konsistenstilpasset kost"
author: "Ingvild Thun"
date: 2012.10.18
---

Tilbake til [kosthold i helseinstitusjoner](../../kosthold-institusjoner.qmd "Kosthold i helseinstitusjoner").

Ikke alle har mulighet til å spise vanlig mat. Ulike problemstillinger kan påvirke vår evne til å spise, og av og til er det nødvendig å gjøre tiltak for å i det hele tatt klare å få i seg tilstrekkelig med energi og næringsstoffer. I denne artikkelen ser vi på det som kalles konsistenstilpasset kost, som er en måte å tilpasse kosten til de som sliter med å spise maten i sin opprinnelige form.

## Hva er konsistenstilpasset kost?

Konsistenstilpasset kost er mat og drikke tilpasset tygge- og svelgefunksjon, og skal samtidig dekke en persons behov for energi, næringsstoffer og væske. Kosten varierer i konsistens fra lett tyggelig til mer eller mindre flytende kost:

-   Lett-tyggelig kost

-   Findelt/purékost

-   Geléringskost

-   Flytende kost – grad 1, 2 og 3

## Hvem skal bruke konsistenstilpasset kost?

Lett -tyggelig kost passer til personer med noe tyggevansker og redusert munnmotorikk, mens findelt/puré kost passer for de med dårlig/ingen tyggefunksjon og dårlig munnmotorikk. Geléringskost er beregnet på personer med ingen tyggefunksjon og som har svelgeproblemer, redusert tungebevegelighet og dårlig leppefunksjon. Flytende kost inndeles i tre ulike konsistensgrader avhengig av svelgefunksjon:

-   Tyntflytende (grad 1): normal svelgefunksjon eller kjevelås

-   Tyktflytende (grad 2): personer med tendens til feilsvelging

-   Kremkonsistens (grad 3): personer med tendens til feilsvelging av tynnere konsistenser

Mange som spiser konsistenstilpasset kost har en sykdomstilstand der konsekvensene er redusert funksjon, smerte eller lammelser i munnhule og svelg eller fortrengninger i spiserør. Eksempler er hjerneslag, hodeskade, multippel sklerose (MS) og cerebral parese (CP). Svelge- og tyggevansker kan også oppstå som følge av dårlig tannstatus, kreft i munn/svelg eller ved dysfagi (svelgebesvær). Mulige tegn på tygge­ og svelgevansker kan være at måltidene tar lang tid, man opplever hosting og sikling, eller over lengre tid konsekvenser som vekttap og dehydrering.

## Matvarevalg

Matvarevalget kommer an på hvilken konsistens man tolerer, jo fastere konsistens jo mer er det generelt å velge i. Så lenge man ikke er kritisk syk, betinger ikke konsistenstilpasset mat og drikke en bestemt fordeling av næringsstoffer; man kan ofte spise den samme maten som ellers uavhengig av hvilken type kosthold man ønsker å følge, så langt dette er mulig.

Ved lett-tyggelig kost og purékost kan man følge et hvilket som helst kosthold ut i fra egne preferanser, da de fleste matretter kan mykgjøres og moses ved å bruke stavmikser, blender og liknende utstyr. Slike retter ser ofte mer fristende ut hvis man moser de ulike ingrediensene, for eksempel grønnsaker og kjøtt, hver for seg.

Geleringskost skal være glatt, geleaktig og ha en fast, sammenhengende form (krem, fromasj, mousse). Ingen tyggefunksjon og redusert tungebevegelighet medfører behov for retter som endres fra fast til lettsvelget konsistens uten bearbeiding i munnen. Man kan ta utgangspunkt i purékost eller flytende kost, for deretter å justere konsistensen under tillaging. Dette oppnår man ved å bruke bindemiddel som gelatin, potet- eller maisstivelse.

Når det gjelder flytende kost, avhenger dette av hvilken konsistensgrad man må følge. Det viktigste er at all flytende kost skal ha en jevn og glatt konsistens uten biter. Nedenfor presenteres ulike forslag til flytende kost for de ulike konsistensgradene.

-   **Tyntflytende (grad 1)**: vann, kaffe, te, melk, juice, saft, supper kokt på vann/kraft, velling, avkok, utblandet buljong

-   **Tyktflytende (grad 2)**: smoothies, yoghurt, drikkeyoghurt, milkshake, kremete supper og kulturmelk. Denne konsistensgraden kan man drikke fra glass, men den skal flyte langsommere enn tyntflytende drikker.

-   **Kremkonsistens (grad 3)**: alle mer eller mindre flytende matvarer uten biter – konsistensen kan tilpasses ved bruk av fortykningsmiddel, som ofte er nødvendig ved denne graden. Konsistensen kan drikkes av glass, men flyter veldig langsomt og passer best å spise med skje (et sugerør skal kunne stå av seg selv).

## Utfordringer

Man kan støte på flere utfordringer ved konsistenstilpasset kost, men dette avhenger ofte av konsistensgrad. Det vil være større utfordringer jo mer tyntflytende kosten er, dette fordi man øker mengden mat uten å øke energitettheten. Å få dekket en persons behov for energi og næringsstoffer på flytende kost kan være utfordrende, spesielt for småspiste, og ofte er det behov for supplering med kosttilskudd og næringsdrikker. Personer med ulike tygge- og svelgevansker har økt risiko for å utvikle ernæringsvansker, og ernæringsstatus bør følge opp av fastlege.

En del matvarer egner seg ikke til mosing, dette gjelder spesielt fisk, kjøtt og diverse grønnsaker som stangselleri. Dette kan gå ut over proteinkvalitet samt kostens innhold av omega 3 fettsyrer og vitaminer, spesielt vitamin D og jern (fertile kvinner).

I tillegg kan denne kosten bli ensformig hvis man ikke eksperimenterer med ulike smaker, da konsistensen vil være den statiske faktoren. I startfasen kan det være lurt å konsentrere seg om å tilvennes konsistensen og bruke kjente matvarer man liker, så kan eksperimentering komme etter hvert. Det anbefales også å veksle mellom varme og kalde retter.

Ved behov for konsistenstilpasset kost over lange perioder tenker man ofte på den høye andelen fett, og da spesielt mettet fett, som vil være en konsekvens av beriking med naturlige råvarer. Over kortere perioder på konsistenstilpasset kost er ikke dette en bekymring. Man kan med fordel bruke oljer (da helst raps- og olivenolje) for mer gunstig fettfordeling eller benytte seg av spesialprodukter som energi- og proteinpulver og/eller næringsdrikker. Fortykningsmiddel er ofte nødvendig for personer på flytende kost, spesielt ved feilsvelging (grad 3). Slike spesialprodukter kan kjøpes på apotek, og for personer med sykdommer i munn og svelg gis dette på blå resept. Konsistenstilpasset mat krever i tillegg utstyr i form av stavmikser, blendere og ofte ulike beholdere.
