---
title: "Lettfordøyelig kost"
author: "Ingvild Thun"
date: 2014.03.10
---

Tilbake til [kosthold i helseinstitusjoner](../../kosthold-institusjoner.qmd).

Enkelte pasientgrupper kan ha problemer med å fordøye maten, og oppleve en del symptomer i forbindelse med dette. Lettfordøyelig kost er. Målsettingen for kosten vil være å minske pasientens symptomer og plager, samtidig som den smaker godt og er ernæringsmessig tilstrekkelig.

## Målgruppe

Hvem kan dra nytte av lettfordøyelig kost? Dette kan for eksempel gjelde pasienter i tiden etter en operasjon i magetarmkanalen. Også pasienter med refluksproblematikk, da de har en svak lukkemuskel mellom magesekk og spiserør, som gjør at surt mageinnhold irriterer spiserøret. [Mer om refluks finner du her](../refluks-funksjonell-dyspepsi.qmd). Andre pasientgrupper som kan ha nytte av lettfordøyelig kost, er de med uspesifikke fordøyelsesplager eller [irritabel tarm](../irritabel-tarm.qmd), da disse ofte er sensitive for matvarer man typisk unngår i et lettfordøyelig kosthold.

## Matvarevalg

Matvarevalget er mye som [standardkost](nokkelkost.qmd), men inneholder færre matvarer som potensielt kan skape problemer i fordøyelsen. Dette vil i praksis bety å unngå store mengder søte melkeprodukter med laktose, sterkt saltet/krydret/røkt mat, fete matvarer, harde/brente skorper, gassdannende grønnsaker, syrlige grønnsaker, kaffe, peppermynte, alkohol og søtstoffer.

## Utfordringer

Denne kosten er som regel uproblematisk, men kan være tam på smak og heller ensidig. Ved uspesifikke fordøyelsesplager vil det alltid være behov for individuelle tilpasninger.

## Råd

-   Begrens mengden laktoserike matvarer – benytt laktosefrie varianter
-   Bruk mørt kjøtt
-   Egg og fisk tåles fint, men helst ikke stekt eller saltet
-   Kokte, hermetiske, frosne grønnsaker og grønne salater
-   Poteter og ris
-   Unngå gassdannende grønnsaker som bønner, kål, erter, løk, hvitløk osv
-   Drikke: vann, is-te, rett i koppen, urtete, saft
-   Unngå sterkt krydret mat
-   Vær varsom med alkohol
