---
title: "Melkeproteinfri kost"
author: "Ingvild Thun"
date: 2013.12.19
---

Tilbake til [kosthold i helseinstitusjoner](../../kosthold-institusjoner.qmd).

Melkeprotein er en av de vanligste proteinene å være allergisk mot. De fleste som rammes vokser fra seg denne allergien i ung alder, men noen fortsetter å være allergiske også i voksen alder. I denne artikkelen får du en innføring i hva melkeproteinfri kost er.

## Hva er melkeprotein?

Melkeprotein er rett og slett proteinet i melka, men det finnes over 25 ulike typer proteiner og alle kan gi reaksjon hos allergikere. De fleste har allergi mot flere av proteinene. Hovedtypen proteiner i melk og meieriprodukter er *myse* og *kasein*, men begge inneholder flere undergrupper av proteiner.

Ved melkeproteinallergi reagerer immunforsvaret på en eller flere av proteinene i melken, med det resultat at det blir satt i gang en reaksjon hvor antistoffer skal angripe og forsvare kroppen mot det «fremmede» proteinet. Etter å ha inntatt noe man reagerer på, kan det gå veldig raskt før symptomene melder seg, og de kan vise seg fra flere organer. Det vanligste er å få en hud-, magetarm- og/eller en luftveisreaksjon i form av kløe, utslett, elveblest, magesmerter, diare, oppkast og pusteproblemer. Den mest alvorlige formen for allergisk reaksjon er *anafylaktisk sjokk* med pustevansker, kvelningsfornemmelse og blodtrykksfall, men dette er heller sjelden ved melkeproteinallergi.

## Målgruppe

Personer som har melkeproteinallergi må ha et kosthold helt uten kumelk og produkter som inneholder dette. Det er først og fremst et problem i tidlig barneår, 2-3 % av barn, og de fleste vokser det av seg før skolegang. Melkeproteinfri kost gjelder ikke for de med *laktoseintoleranse,* hvor man ofte ikke tåler søtmelk, men kan tåle ost, yoghurt og fløte. Kosten er restriktiv og anbefales kun til personer med melkeprotein*allergi*.

## Matvarevalg

Kostholdet må være fritt for meieriprodukter, supplert med eventuelle erstatningsprodukter basert på soya, havre eller ris. Råvarer av korn, kjøtt, fisk, egg, frukt og grønnsaker er grunnlaget for næringsrike måltider uten melkeprotein. Erstatningsproduktene kan brukes som drikke og i matlaging for voksne og barn over 3 år. Ofte er disse produktene beriket med kalsium og B-vitaminer. Risdrikker har derimot liten ernæringsmessig verdi og bør kun brukes til matlaging og ikke som måltidsdrikke. Barn under 3 år anbefales å bruke melkeerstatning basert på spaltet (hydrolysert) melkeprotein i kostholdet, peptidløsninger. Noen få vil også reagere på dette, og da kan man prøve løsninger basert på aminosyrer.

## Utfordringer

I motsetning til de som er *laktoseintolerante,* finnes ingen erstatningsprodukter der komponenten man reagerer på, er tatt ut. Det er ikke mulig å fjerne melkeproteinet på samme måte som man fjerner melkesukkeret. En kost uten melk og meieriprodukter vil inneholde mindre energi, protein, fett, kalsium, jod, enkelte B-vitaminer og sink, noe som kan gjøre det utfordrende å få dekket behovet på en melkeproteinfri kost. Kalsiumtilskudd er ofte nødvendig.

For barn under 3 år kreves det god motivasjon og tålmodighet hos foreldrene når barnet skal venne seg til å bruke melkeerstatning, som smaker annerledes enn morsmelk/erstatninger. Erfaring viser at det går lettest når barnet er under 1 år.

Mange typer hel- og halvfabrikata inneholder melk, derfor må man oftere lage maten fra bunnen av og planlegge godt. Det finnes flere erstatningsprodukter på markedet nå enn for noen år siden, og blir man vant til disse er det mindre utfordrende med et godt og variert kosthold.
