---
title: "Natriumredusert kost"
author: "Ingvild Thun"
date: 2013.11.21
---

Tilbake til [kosthold i helseinstitusjoner](../../kosthold-institusjoner.qmd).

Maten vi spiser inneholder makronæringsstoffene karbohydrat, protein og fett, men også viktige mikronæringsstoffer i form av vitaminer, mineraler og sporstoffer. [Natrium](../naeringsstoffer/natrium-klor.qmd), regulerer væskebalansen i kroppen. Kaliumioner er dominerende inne i cellene, mens natriumionene hovedsakelig befinner seg ekstracellulært. Mangel på natrium er heller sjelden nå til dags, og myndighetene anbefaler å kutte ned på bruken av salt. Noen har ekstra problemer med å regulere saltbalansen, og kan ha behov for kosttiltak som hjelper til med dette.

## Målgruppe

Så hvem trenger et kosthold med begrensede mengder natrium? Kosten er hensiktsmessig for personer med hjertesvikt, ødemer (væskeopphopning) og kronisk nyresykdom. Personer med nyresykdom har ikke evne til å skille ut overflødig natrium – dette fører til at væske holdes tilbake, urinproduksjonen blir nedsatt og blodtrykket stiger.

## Matvarevalg

Matvarer med høyt innhold av natrium er først og fremst salt, NaCl. Kosten innebærer å unngå salting av mat ved bordet, begrense i matlaging og utelate salte matvarer, saltet/røkt kjøtt og fisk, salte krydderblandinger, samt hel/halvfabrikata som ofte inneholder mye salt. Dette inkluderer hermetikk, ferdigmiddager, supper, sauser, buljonger og noen desserter. I stedet for salt kan man bruke pepper, sitron, eddik, balsamico, løk, hvitløk, friske urter eller urtekrydder. Salterstatninger inneholder mye kalium og anbefales ikke til personer med kronisk nyresykdom. Natrium inngår i natriumklorid, NaCl, sodium, MSG (monosodiumglutamat), koksalt, havsalt, urtesalt m. f.

## Utfordringer

Hva er så utfordringene med et natriumredusert kosthold? Mange som går på natriumredusert kost har liten matlyst, og lite salt i maten hjelper ikke på. Man må bruke gode råvarer, fremheve smaken i maten på andre måter og bruke andre tilsetninger. Hvor utfordrende kosten er, avhenger også av hvor mye salt mat man er vant til å spise - etter noen dager til uker på natriumredusert kost vil smaksløkene tilvennes.

## Råd for saltrestriksjon

-   Salt ikke ved bordet
-   Unngå spekemat, røkt kjøtt og fisk
-   Obs på buljong, pulversupper/sauser, samt sylteagurker, pickles osv
-   Kutt ned salt snacks som potetgull, saltet popcorn osv
-   Les varedeklarasjoner og velg produkter med salt lengre bak i ingredienslista

1 gram salt (NaCl) tilsvarer 0,4 gram natrium à det er 1 gram natrium i 2,5 gram salt. Myndighetene sine råd om å begrense saltinntaket til 5g/dag tilsvarer altså 2g natrium.
