---
title: "Nøkkelrådskost"
date: 2012.10.13
---

Tilbake til [kosthold i helseinstitusjoner](../../kosthold-institusjoner.qmd "Kosthold i helseinstitusjoner").

Nøkkelrådskost bygger på nøkkelrådene for kosthold fra Helsedirektoratet, og er det kostholdet som også anbefales for den friske befolkningen. Målet med nøkkelrådskosten er å legge til rette for god helse og å redusere risikoen for å utvikle sykdommer. 

Energifordelingen i nøkkelrådskosten er 50-60E% karbohydrat, 10-20E% protein og 25-35E% fett. Proteinbehovet er beregnet til ca 1g protein av god kvalitet per kg kroppsvekt. Det er også fokus på fettkvaliteten, og det anbefales at flerumettet fett utgjør opp til 10E% (minst 1E% omega-3) og mettet fett begrenses til maksimalt 10E%.

Normalt legges det opp til 4 hovedmåltider og 1 mellommåltid, og det er anbefalt å legge opp til regelmessige måltider.

## **Hvem skal bruke nøkkelrådskost?**

Målgruppen for nøkkelrådskost er alle friske og syke med god ernæringsstatus. De aller fleste helseinstitusjoner bruker dette kostholdet som utgangspunkt, og gjør deretter individuelle tilpasninger der det skulle være behov for det.

## Matvarevalg

Når man setter opp nøkkelrådskost fokuseres det på å velge matvarer som er naturlig fiberrike, som fullkornsprodukter, frukt og grønnsaker. Noen av de viktigste rådene kan oppsummeres i følgende punkter.

-   Velg fortrinnsvis grove kornprodukter.

-   Frukt og grønnsaker bør inngå i alle måltider, mens nøtter bør unngås i standardoppsettet for å unngå problemer for de med allergier.

-   Det er anbefalt å velge magre meieriprodukter.

-   Ren fisk og magert kjøtt er anbefalt, og det etterstrebes å begrense mengden rødt og bearbeidet kjøtt.

-   Reduser bruk av sukker, sukkerrike matvarer og salt.

## Utfordringer

Det er ingen utpregede utfordringer med nøkkelhullskost. Det er mange som har en oppfatning av at et slikt kosthold vil være ugunstig, men med et fornuftig valg av matvarer er det lite som tilsier at et slikt kosthold skal være et problem for majoriteten av befolkningen.

Det kan være vanskelig å komme opp i de anbefalte mengdene karbohydrater, og det er for gjort å komme for høyt på fettet, siden det er mange matvarer som er naturlig rike på fett. Tenk derfor på anbefalingene som veiledende, og ikke at de må følges bokstavelig hver eneste dag.

## Måltidseksempler

**Frokost:** Havregrøt, kornblanding, omelett

**Lunsj:** Brødmat med variert pålegg

**Middag:** Kjøtt, fisk, fugl med potet/ris/pasta og grønnsaker

**Kveldsmat:** Brødmat med variert pålegg

**Mellommåltid:** Frukt, bær, yoghurt, nøtter
