---
title: "Proteinkontrollert kost"
author: "Ingvild Thun"
date: 2014.01.27
---

Tilbake til [kosthold i helseinstitusjoner](../../kosthold-institusjoner.qmd "Kosthold i helseinstitusjoner").

En kost med et moderat proteininnhold kan redusere eller forhindre proteinutskillelse i urin, og uremisymptomer som hudkløe, kvalme og oppkast hos personer med nyresykdom. Derfor brukes proteinkontrollert kost til disse pasientene. I denne artikkelen får duet innblikk i hvordan et slikt kosthold ser ut.

## Målgruppe

Personer med begynnende eller etablert nyresykdom er målgruppen for proteinkontrollert kost. Dietten er vanligvis ikke langvarig, og jo større restriksjon jo færre dager på dietten. Dette er også en kost som gjennomføres på sykehus under kontrollerte omgivelser og hyppig oppfølging av kvalifisert helsepersonell.

## Matvarevalg

Kostholdet må tilrettelegges individuelt ut i fra blodprøver, symptomer og aktuelt kosthold, samt ernæringsmessig risiko. Det vanlige er å begrense proteininntaket til 0,8-1,0 g/kg/dag. Det er mulig å redusere til 0,6g, men det krever tett oppfølging. Den lave mengden protein setter krav til at det som spises, bør være av høy biologisk kvalitet i form av kjøtt, fisk, egg og meieriprodukter. Et annet viktig element er at proteinene fordeles utover måltidene og ikke spises på en gang. Reduserer man proteininntaket, må man øke på noe annet – karbohydrater og/eller fett.

## Utfordringer

Hva er så **utfordringene** med en proteinkontrollert kost? Dette kommer an på mengden man spiser fra før, men generelt vil det ofte bety en halvering i mengden protein, noe som kan by på store utfordringer – både ernæringsmessig, smaksmessig og tilberedning. Det er viktig å vurdere kosten opprinnelige proteininnhold for å avgjøre behovet for reduksjon, og kosten krever hyppig oppfølging og veiledning av lege og/eller klinisk ernæringsfysiolog.

## Praktiske råd

-   Høykvalitet proteinkilder – litt til hvert måltid
-   Frukt, bær og grønnsaker er ok, men unngå belgfrukter, kål, mai, avokado, tørket frukt og nøtter
-   Unngå for grove kornprodukter – skjær tynne skiver
-   Bruk margarin/smør og sauser
-   Proteinfattige pålegg: honning, sunda, syltetøy, banan, agurk, salat, tomat, marmelade, sjokoladepålegg
-   Dessert: bær med fløte
