---
title: "C-vitamin"
date: "2011.10.22"
categories: 
  - næringsstoffene
  - vannløselige vitaminer
---

[Tilbake til artikkelserien om næringsstoffene](../../naeringsstoffer.html)

C-vitamin er et vannløselig vitamin som har mange viktige funksjoner i kroppen, deriblant som en antioksidant. Vi har ingen lagre av dette vitaminet (selv om konsentrasjonen i enkelte vev er ganske høy), og er dermed avhengig av jevnlig tilførsel for å dekke kroppens behov. Vitaminet ble oppdaget ved at sjøfolk som spiste sitrusfrukter under seiling ikke utviklet skjørbuk, som er en mangelsykdom som oppstår ved mangel på C-vitamin.

De fleste dyr produserer C-vitamin selv, men vi mennesker mangler et avgjørende enzym i denne prosessen, og er dermed avhengig av å få i oss vitaminet fra kosten. Vitaminet syntetiseres fra karbohydrater, men hos dyr som mangler det avgjørende enzymet så vil endeproduktet bare omdannes tilbake til glukose.

## Opptak og metabolisme

C-vitamin tas opp i tynntarmen. For å krysse cellemembraner er vitaminet avhengig av hjelp fra et transportprotein som heter SVCT, som står for sodium-dependent vitamin-C transporter, eller på norsk: Natrium-avhengig vitamin-C transporter. Disse transportproteinene er energikrevende. Det finnes to kjente slike transportproteiner: SVCT1 som finnes i tarmen, leveren og nyrene, og SVCT2 som finnes i alt annet vev. Det førstnevnte er ansvarlig for opptak i tarmen og reopptak i nyrene, som er de to hovedveiene der kroppen kan få tilførsel av C-vitamin. SVCT2 er avhengig av kalsium og magnesium, og har som oppgave å transportere C-vitamin inn i metabolsk aktivt vev. Vi kan si at SVCT1 regulerer hele kroppens c-vitaminbalanse, mens SVCT2 regulerer C-vitaminmetabolismen i de ulike cellene.

C-vitamin opptrer i ulike former. Det vi kaller C-vitamin og som vi finner i mat er askorbinsyre. I blod og vev omdannes askorbinsyre til den oksiderte formen monodehydroaskorbinsyre. Denne formen har i seg selv ingen antioksidantfunksjon, men i områder med høyt oksidativt stress kan denne oksideres en gang til og danne dehydroaksorbinsyre som kan tas opp i celler via glukosetransporterne GLUT1, GLUT3 og GLUT4. Inne i cellene kan dehydroaskorbinsyre raskt reduseres tilbake til askorbinsyre, og dette er den molekylære mekanismen bak vitaminets antioksidanteffekt. Dette indikerer også at vi effektivt resirkulerer C-vitamin i områder med høyt oksidativt stress, altså når behovet er høyt. Under normale omstendigheter vil imidlertid konsentrasjonene av dehydroaskorbinsyre være lave, og sirkulerende blodsukker vil dominere i konkurransen om GLUT-transporterne, noe som minimerer denne resirkuleringen.

Genetiske variasjoner i de sentrale transportproteinene har vist seg å påvirke C-vitaminstatus. Ulike mutasjoner i SVCT1 påvirker sirkulerende nivåer, mens mutasjoner i SVCT2 er satt i sammenheng med blant annet kreft og prematur fødsel, noe som indikerer at denne transporteren er svært sentral i C-vitaminets funksjon.

Dersom dehydroaskorbinsyre ikke reduseres til askorbinsyre vil det hovedsakelig degraderes til oksalat og forlate kroppen via urinen sammen med umetabolisert askorbinsyre.

## Funksjoner

C-vitamin har flere funksjoner i kroppen. For det første er vitaminet som nevnt en antioksidant, og in vitro (utenfor kroppen) studier har vist at C-vitamin også kan være med å regenerere [E-vitamin](evitamin.qmd). Den biologiske funksjonen til askorbinsyre er som kofaktor for en rekke oksidaser, der C-vitamin stimulerer enzymaktiviteten ved å holde jern i sin reduserte form. Askorbinsyre er kofaktor for 8 enzymer i menneskekroppen, som er med å regulere syntesen av noradrenalin fra dopamin (*dopamin β-hydroksylase*), stabilisering av kollagen (*prolyl 4-hydroksylase, prolyl 3-hydroksylase og lysyl hydroksylase*), syntese av karnitin (*6-N-trimetyl-L-lysine hydroksylase og γ-butyrobetain hydroksylase),* aktivering av en rekke nevrotransmittere (*peptidylglycin α-amiderende monooksygenase*) og i tyrosinmetabolismen (*4-hydroksyfenylpyruvat dioksygenase).*

Mange av symptomene på c-vitaminmangel er antatt å skyldes redusert kollagenstyrke og karnitinsyntese. Allerede på 80-tallet ble det foreslått at utmattethet assosiert med skjørbuk skyldtes reduserte intramuskulære nivåer av karnitin, som er viktig for fettforbrenningen. Per i dag er ikke dette dokumentert, men i cellekulturer har man sett en økt karnitinsyntese og økt fettsyreoksidasjon ved å tilføre c-vitamin.

I binyrene og i hypofysen har vi store konsentrasjoner av C-vitamin, noe som antagelig skyldes at vitaminet er en viktig kofaktor for to viktige kobberavhengige enzymer involvert i syntesen av noradrenalin og aktivering av en rekke nevrotransmittere. Ettersom peptidylglycin α-amiderende monooksygenase kontrollerer produksjonen av over halvparten av alle nevropeptider er dette et stort og mindre kartlagt felt når det kommer til C-vitamins rolle i nevroendokrin biologi.

I studier på cellekulturer har det blitt oppdaget at C-vitamin er med å regulere gentranskripsjon og stabiliserer mRNA for en rekke gener, men mekanismen her er ikke kjent. Dette er en ny molekylær mekanisme for vitaminet, og kan indikere at det er sentralt for intracellulær signaloverføring.

C-vitamin kan også øke opptaket av [jern](jern.qmd), noe som er grunnen til at jerntilskudd anbefales å tas sammen med C-vitamin, f.eks. appelsinjuice. Mekanismen er antatt å være at C-vitamin reduserer jernet, noe som gjør at det i mindre grad binder til antinæringsstoffer som fytat.

## Behov og anbefalinger

Anbefalt daglig inntak av C-vitamin er 75mg, med litt variasjon etter kjønn og alder. Dette tilsvarer innholdet i ca 50g paprika, 150g brokkoli, 150g appelsin eller 120g jordbær. Med andre ord er det ikke noe problem å få i seg anbefalt mengde.

Noen mener at de anbefalte dosene av C-vitamin er alt for lave. Spesielt ved sykdomstilstander bør inntaket være mye høyere. Dette begrunnes med at de pattedyrene som produserer eget C-vitamin produserer vitaminet i doser som er langt høyere enn de anbefalte mengdene. Små pattedyr produserer vitaminet i mengder som varierer fra 150-275 mg/kg kroppsvekt. Kroppslagrene av vitaminet hos disse dyrene varierer fra 30-100 mg/kg, og konsentrasjonene i blodet ligger rundt 0,5-1 mg/dL. Til tross for at vi mennesker bare inntar rundt 1 mg/kg så opprettholder vi kroppslagre på 20 mg/kg og en blodkonsentrasjon på 0,5-0,7 mg/dL. Halvveringstiden for C-vitamin hos mennesker er mye høyere enn hos disse dyrene med egenproduksjon, så vi kan si at vi er svært gode til å opprettholde nivåene og har et lavere behov per kg kroppsvekt.

## Mangeltilstander

Symptomer på C-vitaminmangel er først og fremst knyttet til skjørbuk  , som er en tilstand som oppstår når et eller flere av enzymene (nevnt under funksjoner) ikke fungerer. Mangelsykdommen karakteriseres av intramuskulære og cerebrale blødninger, ødemer og nevropati. De vanligste symptomene er utslett, vannansamlinger i beina, beinsmerter, svakhet og generell sykdomsfølelse.

Skjørbuk kan være dødelig dersom det ikke behandles (tilførsel av C-vitamin), og de som først og fremst er utsatt for denne mangeltilstanden er alkoholikere, eldre, enslige og folk med svært restriktive dietter uten frukt og grønnsaker.

## Kan vi få for mye?

I og med at C-vitamin er vannløselig, kan kroppen skille ut et overskudd. Alvorlige konsekvenser av et inntak som overskrider behovet er derfor ikke noe å være redd for. Et høyt inntak kan likevel føre til diaré, oppblåsthet og magekramper, og høyt inntak over lengre perioder kan medføre risiko for jernoverbelastning hos folk med hemokromatose, sigdcelleanemi eller liknende. Disse effektene er ikke observert hos friske individer.

Høyt inntak av C-vitamin vil øke utskillelsen av oksalat og urinsyre, og dermed kunne øke risikoen for nyrestein. Epidemiologiske studier har funnet blandede resultater vedrørende hvorvidt det er er en direkte sammenheng her.

En øvre grense for inntak er satt til 2g/dag, og denne grensen er først og fremst knyttet til mageproblemer. Merker du ikke noe til dette, er det ingen fare å innta større mengder.

## Gode kilder

Frukt og grønnsaker er gode kilder til C-vitamin. De største mengdene finner vi i grønnsaker som paprika/rosenkål/brokkoli, i bær som solbær/molter/jordbær og i frukt, i hovedsak sitrusfrukter som appelsin/sitron/lime. Av animalske kilder er det bare lever som bidrar til inntaket av C-vitamin.

C-vitamin er et veldig ustabilt vitamin, og betydelige mengder går tapt under behandling av matvarer. Vitaminet tapes først og fremst gjennom kokevann, lyseksponering, oksygen og ved lagring. For å beholde mest mulig vitamin bør frukt og grønnsaker lagres kaldt og mørkt (i kjøleskap), koketiden bør være så kort som mulig, og mengden kokevann begrenses.

## Aktuelt om C-vitamin

-   Ved koronar hjertesykdom vil oksidativt stress redusere produksjonen av nitrogenoksid (vasodilator) og øke produksjonen av proinflammatoriske molekyler. Det finnes indikasjoner på at C-vitamin kan spille en terapeutisk rolle her ved å stimulere produksjonen av nitrogenoksid. Tilskudd av C-vitamin har vist seg å kunne reversere endotelial dysfunksjon hos folk med høyt blodtrykk, diabetes eller stabil angina og hos røykere. Det er her snakk om tilskudd av 500 mg C-vitamin, og litteraturen er langt fra entydig. Her må man blant annet holde muligheten åpen for at effekten kan komme som følge av at C-vitaminstatus i utgangspunktet var lav.

-   Det forskes nå på en mulig effekt av høydose intravenøs C-vitamin i behandlingen av kreft. Ettersom det er beviser for at vitaminet reduserer oksidative skader på DNA og proteiner in vivo, er det plausible mekanismer for en kreftforebyggende effekt av C-vitamin, men per i dag er interessen først og fremst fokusert rundt behandling av kreft. I høye doser virker nemlig vitaminet pro-oksiderende og det dannes hydrogenperoksid som dreper kreftcellene. Foreløpig er ikke resultatene oppløftende for denne typen behandling.

-   Det er mange meninger om C-vitamins funksjoner for immunsystemet. I enkelte pasientgrupper har tilskudd av vitaminet vist seg å kunne forbedre immunstatus, men i majoriteten av studier på dette finner man ingen effekt. Det er en vanlig oppfatning at C-vitamin kan forebygge forkjølelse, men heller ikke her finner man en effekt under normale omstendigheter. Det er en metaanalyse som har funnet en beskyttende effekt hos stressede mennesker som følge av høyt aktivitetsnivå eller ved å oppholde seg i kalde omgivelser. Hos astmatikere har tilskudd av C-vitamin vist seg å kunne beskytte mot kontraksjoner av luftveiene som følge av fysisk aktivitet, sannsynligvis grunnet redusert produksjon av proinflammatoriske eikosanoider.

-   Høyt inntak av C-vitamin er satt i sammenheng med høyere beinmineraltetthet hos eldre. Nyere studier har identifisert en mulig effekt som kofaktor for enzymatiske reaksjoner i regulering av osteoblastdifferensiering.

-   [Er C-vitamin-tilskudd verdt pengene?](../vitamin-c-tilskudd.qmd "Vitamin C-tilskudd og immunsystemet ditt – Noe å bruke penger på?")

Artikkelen er oppdatert juli 2013
