---
title: "Fiber"
date: "2013.08.12"
categories: 
  - næringsstoffene
  - makronæringsstoffer
---

[Tilbake til artikkelserien om næringsstoffene](../../naeringsstoffer.html)

Fiber er en fellesbetegnelse på karbohydratforbindelser som ikke fordøyes av menneskelige fordøyelsesenzymer og derfor fraktes ufordøyd ned i tykktarmen. Selv om fiber ikke absorberes i tarmen har det flere viktige funksjoner, blant annet for tarmfunksjon. I tykktarmen kan bakteriene fermentere noe av fiberet slik at det dannes korte fettsyrer. Disse kan absorberes, og på denne måten kan vi utnytte noe av energien fra dette makronæringsstoffet.

## Definisjoner

Definisjonen på fiber har opp gjennom variert litt, og hvilke forbindelser som inkluderes under begrepet kan variere litt etter hvem du spør. Fiber består av ufordøyelige polysakkarider, og stivelse faller naturligvis utenfor denne definisjonen. Nå vet vi imidlertid at også en del stivelse unnslipper fordøyelse i tynntarmen. Dette kalles resistent stivelse, og det har vært diskutert hvorvidt resistent stivelse skal regnes som fiber eller ikke. Også andre ufordøyelige karbohydrater, som inulin, galaktooligosakkarider (GOS) og fruktooligosakkarider (FOS) har vært diskutert ettersom molekylene er mindre enn det som tradisjonelt har vært regnet som fiber.

FAO/WHO laget i 2010 en formell definisjon på fiberbegrepet:

> Fiber er karbohydratpolymerer med minst ti monosakkaridenheter som ikke hydrolyseres av fordøyelsesenzymer i menneskets tynntarm, og som tilhører følgende kategorier.
> -   Spiselige karbohydratpolymerer som finnes naturlig I maten vi spiser.
> -   Karbohydratpolymerer som på fysisk, kjemisk eller enzymatisk vis er hentet fra matvarer, som er vist å ha helsemessig gunstige effekter demonstrert ved tilfredsstillende vitenskapelig dokumentasjon og godkjent av kompetente autoriteter.
> -   Syntetiske karbohydratpolymerer som er vist å ha helsemessig gunstige effekter demonstrert ved tilfredsstillende vitenskapelig dokumentasjon og godkjent av kompetente autoriteter.

Denne definisjonen inkluderer ikke ufordøyelige karbohydrater med mindre enn 10 monosakkarider i kjeden, som inulin og GOS/FOS. Det er imidlertid nevnt å være opp til de nasjonale autoritetene å vurdere hvorvidt disse skal inngå under fiberdefinisjonen.

Det er populært å dele fiber inn i løselig og uløselig fiber, men hvorvidt denne kategoriseringen er nyttig kan det stilles spørsmål ved. Hvorvidt et fibermolekyl er løselig i vann utenfor kroppen er ingen god prediktor for den fysiologiske funksjonen, og det er heller ingen garanti for at fiberet løser seg opp når det befinner seg i tarmen. Allerede i 1998 foreslo FAO/WHO at man burde slutte å bruke disse, men likevel er det fremdeles vanlig å bruke disse begrepene.

## Funksjoner

Fiber har en rekke fysiologiske funksjoner i fordøyelseskanalen, og påvirker opptaket av næringsstoffer og generell tarmfunksjon.

-   Fordøyelsen av karbohydrater starter i munnen ved fordøyelsesenzymer i spyttet og mekanisk knusing ved tygging. Fiberrike matvarer er mer motstandsdyktig mot denne nedbrytningen, og fordøyelsen forsinkes derfor noe.
-   I magesekken vil fiber gjøre at maten blir værende lenger før den tømmes ut i tynntarmen. Dette bidrar til at den glykemiske responsen fra et måltid reduseres.
-   I tynntarmen hemmer fiber opptaket av glukose ved å gjøre karbohydratene mindre tilgjengelig for fordøyelsesenzymene. Ulike fibertyper kan påvirke dette på forskjellige måter. Uløselige fibre fra eksempelvis fullkorn beskytter stivelsen som ligger innenfor, men har liten beskyttende effekt på andre karbohydrater i tarmen. Andre, mer løselige fibre bidrar til å binde tarminnholdet sammen i en mer seigtflytende masse som er mindre tilgjenglig for fordøyelsesenzymene, som dermed bruker lenger tid på å fordøye maten.
-   Fiber kan også binde til ioniserte substanser som mineraler og tungmetaller, og hindre opptak av disse. Også andre organiske stoffer kan bindes til fiber og dermed unngå absorbsjon. Det er lite som tyder på at fiber har en negativ effekt på mineralmetabolismen i hos mennesker, men store mengder fytat som finnes i fullkornsprodukter og belgfrukter binder til toverdige mineraler som sink, magnesium og kalsium og hemmer opptaket av disse.
-   Alle fibertyper bidrar til å øke vekten på avføringen, både ved å holde på væske og ved å øke bakteriemassen. Uløselige fibre fra f.eks. fullkorn bidrar først og fremst ved å holde på væske, mens fermenterbare fibre først og fremst bidrar til å øke mengden bakterier.

Fiber har også en rekke metabolske funksjoner, ved å påvirke opptaket av næringsstoffer og ved at de kan fermenteres i tykktarmen og gi opphav til korte fettsyrer.

-   Fiber er positivt for blodsukkerkontroll. Dette er på grunn av effektene fiber har på opptaket av karbohydrater. Det er også holdepunkter for at fiber påvirker utskillelsen av hormoner som bidrar til å regulere blodsukkeret.
-   Nederst i tarmen har vi endokrine celler som produserer hormoner som respons på kontakt med næringsstoffer. Ved å redusere hastigheten på opptaket av karbohydrater og fett lenger oppe i tarmen kan fiber sørge for at disse kommer i kontakt med disse cellene og dermed påvirke produksjonen av disse. Det er blant annet vist at nivåene av peptid YY, som er et av hormonene som regulerer appetitten kan påvirkes på denne måten. Glukagonliknende peptid (GLP) produseres også av disse cellene, og det er foreslått at dette kan bidra til å øke insulinsensitiviteten.
-   Fettmetabolismen påvirkes av fiberinntaket, men mekanismene er ikke fullstendig kartlagt eller forstått. Ulike fibre bidrar til å senke kolesterolet, sannsynligvis ved å redusere reabsorbsjonen av gallesalter nederst i tarmen. Da må leveren produsere nye gallesalter, og da brukes kolesterol som substrat. Det er hovedsakelig de løselige fibrene som gjør dette, ved at gallesalter bindes til den seigtflytende massen som dannes.
-   I tykktarmen har vi masse bakterier, som i motsetning til oss har enzymer som kan bryte ned fiber. Da produseres det korte fettsyrer (acetat, propionat og butyrat), som kan absorberes og brukes som energi. Acetat brukes i ulike vev, propionat metaboliseres i leveren, mens butyrat er tarmcellenes primære energikilde.
-   Disse korte fettsyrene har også mange andre egenskaper, noe som åpner opp for at fiber kan spille en viktig rolle ved å være en kilde til disse. De kan eksempelvis fungere som signalmolekyler, og butyrat har vist seg å kunne påvirke genuttrykket i tarmcellene og å stimulere til celledød i kreftceller.
-   Fermenterbare fibre øker bakteriemassen, men normalt sett vil forholdet mellom de ulike fibertypene være uendret. Enkelte ufordøyelige fibre, som GOS/FOS har derimot vist seg å kunne spesifikt stimulere til vekst av enkelte bakterietyper som er antatt å være gunstige, og disse brukes derfor som kosttilskudd og kalles prebiotika.

## Fiber og sykdomsrisiko

Fiber har fått mye oppmerksomhet for å være linket til redusert risiko for en rekke sykdommer.

Et fiberrikt kosthold er antatt å være beskyttende mot overvekt. Store epidemiologiske studier viser at fiberinntaket blant overvektige er signifikant lavere enn gjennomsnittlig fiberinntak hos normalvektige. Dette tilsier ikke at fiber har en direkte effekt på kroppsvekten, men med tanke på fibers effekter på næringsopptaket og metthet så er det en plausibel sammenheng. I studier der energiinntaket er kontrollert er høyere fiberinntak vist å gi høyere metthetsfølelse, og i studier der energiinntaket ikke er kontrollert er høyere fiberinntak assosiert med lavere energiinntak og større vekttap. Fiberrik mat er i gjennomsnitt mindre energitett enn mat med mindre fiber, noe som kan spille inn i stor grad på denne sammenhengen.

Det er foreslått at fiber er involvert i utviklingen av diabetes type 2 og metabolsk syndrom, men dette er også først og fremst basert på epidemiologiske data. Dette er først og fremst forankret i fiberets påvirkning på karbohydratopptaket, men også effektene på blodlipidene spiller en rolle. Det er også etablert en sammenheng mellom fiberinntak og inflammasjon, noe som også er bekreftet i intervensjonsstudier, men mekanismene for dette er ikke kjent. Overvekt er også en risikofaktor for disse sykdommene, så koblingen mellom fiber og overvekt må tas med i betraktningen. Høyt inntak av fiber er også assosiert med en reduksjon i blodtrykk, som er en viktig risikofaktor for en rekke sykdommer.

Fiber er satt i sammenheng med redusert risiko for hjertesykdom, og det er antatt at et fiberrikt kosthold er beskyttende. Dette begrunnes med at fiber er linket til positive effekter på en rekke av risikofaktorene som eksempelvis overvekt, hypertensjon og metabolsk syndrom.

Et høyt inntak av fiber er antatt å beskytte mot tykktarmskreft. Dette kan skyldes at fiber er beskyttende mot dannelsen av utposninger (divertikulitter) i tykktarmen, i tillegg til de nevnte effektene av korte fettsyrer. Epidemiologiske studier har avdekket en signifikant risikoreduksjon ved høyere inntak av fiber.

## Behov, anbefalinger og kilder

Vi har ikke et spesifikt behov for fiber, men det er etablert en verdi for tilstrekkelig inntak. Denne er beregnet til 14g/1000kcal, og dette er basert på kunnskapen om at fiberinntaket er forbundet med redusert risiko for hjertesykdom. De norske anbefalingene er satt til 25-35g fiber daglig.

Gode kilder til fiber er fullkornsprodukter, frukt, grønnsaker og belgfrukter.

## Kan vi få for lite eller for mye?

Det er ikke etablert noen konsekvenser av fibermangel i seg selv, bortsett fra sammenhengene med risiko for ulike sykdommer som er nevnt over.

Et høyt inntak av fiber kan gi ubehag i form av økt gassproduksjon, men for de fleste vil disse plagene være milde og forbigående. Høyt inntak av fiber er linket til redusert mineralstatus, men dette er antatt å skyldes inntaket av fytat, og ikke fiber i seg selv. Det er ikke dokumentert noen farlige konsekvenser av høyt fiberinnntak, men det er rapportert tilfeller av blokkering i spiserør som følge av høyt inntak av fiberrike slankeprodukter, som virker ved å trekke til seg væske og dermed fylle magesekken.

## Aktuelt om fiber

Thomas har skrevet en sak med gode argumenter for [hvorfor du bør få i deg tilstrekkelig med fiber](../fiber-awesome.qmd).

*Artikkelen er sist oppdatert august 2013*
