---
title: "Jod"
date: "2011.11.09"
categories: 
  - næringsstoffene
  - mineraler
---

[Tilbake til artikkelserien om næringsstoffene](../../naeringsstoffer.html)

Jod har atomnummer 53, og regnes som et sporelement. Mineralet er svært ujevnt utbredt i jorden på grunn av blant annet isbreer oversvømmelser, og derfor finner vi mest av det i sjøen. I naturen foreligger jod vanligvis som jodid (I-) eller jodat (IO3-), og finnes hovedsakelig som bestanddel i uorganiske salter. Globalt er det antatt at nesten to milliarder individer får i seg for lite jod, først og fremst i fattige land men også i den vestlige verden. I kroppen er jod viktig som bestanddel i stoffskiftehormonene våre som produseres i skjoldbruskkjertelen (tyroidea), og det er i tillegg svært viktig for mental utvikling.

## Opptak og metabolisme

Jod fra maten brytes hovedsakelig ned til jodid i magen før det absorberes til blodet. Mesteparten av jodet absorberes helt øverst i tynntarmen via en kotransporter som transporterer jod sammen med [natrium](natrium-klor.qmd) (Na/I-symport) inn i tarmcellene. Jod transporteres så over i blodet, og herfra vil det enten tas opp i skjoldbruskkjertelen via en tilsvarende Na/I-symport som vi fant i tarmene, eller skilles ut over nyrene. Urinutskillelsen er ganske stabil, men hvor stor andel som tas opp i skjoldbruskkjertelen vil variere med inntaket. Jo mer vi spiser jo mindre andel tas opp her, og ved tilstrekkelig inntak vil under 10% gå denne veien. Ved utilstrekkelig inntak vil imidlertid mesteparten kunne havne her. I blodet er halvveringstiden for jod omtrent 10 timer, noe som betyr at vi trenger tilførsel med jevne mellomrom for å unngå mangel.

En gjennomsnittlig voksen person har omtrent 20mg jod lagret i kroppen, hvorav mesteparten befinner seg i skjoldbruskkjertelen. Hver dag absorberer skjoldbruskkjertelen 60-80µg jod for å gjøre opp for det som tapes og kunne opprettholde syntesen av stoffskiftehormoner.

Inne i skjoldbruskkjertelen  binder jod til et stort glykoprotein som heter tyroglobulin (Tg). I cellemembranen til kjertelcellene (tyrocyttene) har vi et enzym som heter tyroperoksidase (TPO), som sammen med hydrogenproksid oksiderer jodet slik at det kan binde til tyrosinresiduer på Tg. Da dannes det monojodotyrosin (MIT) og dijodotyrosin (DIT). MIT og DIT er forløperne for tyroideahormonene.

Tyroideahormonene trijodotyronin (T3) og tyroksin (T4) dannes ved at enzymet TPO katalyserer bindingen av hhv MIT+DIT (T3) eller DIT+DIT (T4). T3 og T4 er strukturelt like, men inneholder hhv 3 og 4 jodmolekyler. Alt dette skjer inne i selve skjoldbruskkjertelen, og de ferdige joderte forbindelsene lagres bundet til Tg. Når Tg så fraktes inn i tyrocyttene så vil proteaser (enzymer som fordøyer proteiner, her Tg) frigjøre de joderte forbindelsene og T3 og T4 fraktes ut i blodet. MIT og DIT vil dejodineres av en selenavhengig dejodinase, slik at jodet kan brukes på nytt. Produksjonen av T3 og T4 styres hormonelt. Mengden fritt T4 i sirkulasjonen styrer produksjonen av hormonet [TSH](../hormoner/hypofysehormonene.qmd), tyroideastimulerende hormon, som produseres i hypofysen og stimulerer skjoldbruskkjertelen til å produsere hormoner.

Når T3 og T4 kommer ut i blodet binder de hovedsakelig til tyroksinbindende protein, men også til andre proteiner som albumin og transtyretin. Etter at hormonene er brukt så vil de brytes ned, og jodet blir igjen tilgjengelig for å enten absorberes av skjoldbruskkjertelen eller skilles ut over nyrene.

## Funksjoner

Når T3 og T4 tas opp i målvevene, som hovedsakelig er lever, nyrer, hjerte, muskelvev, hypofysen og hjernen, dejodineres T4 slik at det dannes T3. Det er nemlig T3 som er det mest aktive hormonet. Tyroideahormonene regulerer et bredt spekter av fysiologiske funksjoner. På cellenivå virker de ved å binde til reseptorer i cellekjernen, og styrer hvilke gener som uttrykkes. Generelt sett promoterer T3 produksjon av enzymer og proteiner som øker den metabolske aktiviteten i den aktuelle cellen.

Den mest kjente funksjonen er at disse hormonene øker energimetabolismen, ved å øke varmeproduksjon og oksygenforbruket i cellene. I tillegg de med å opprettholde kjønnskjertlenes funksjon og dermed regulere reproduksjonsevnen. Ved å regulere produksjonen av veksthormoner er tyroideahormonene også sentrale for å regulere vekst og modning, både av vev og skjelett. Nervesystemet er også avhengig av disse hormonene, spesielt i de første levemånedene, og de er derfor også knyttet til utvikling.

## Behov og anbefalinger

Behovet for jod er beregnet utifra risikoen for å utvikle struma. De norske anbefalingene for jod er i området 150µg/dag. Barn trenger mer jod per kg kroppsvekt enn voksne, pga et høyere stoffskifte.

## Mangeltilstander

Globat sett er det beregnet av omtrent 2 milliarder mennesker får i seg utilstrekkelig med jod. Spesielt i områder der jorden av ulike årsaker inneholder lite jod er mangel utbredt. Dette inkluderer områder i sentral-Asia, Afrika, Nordvest-Amerika og sentral- og øst-Europa. I områder der jodmangel er utbredt vil det fortsette å være slik helt til jod innføres i kosten, enten ved beriking eller introduksjon av nye matvarer som er produsert i andre områder. Det er mange konsekvenser av jodmangel, og med en fellesbetegnelse kalles disse IDD (Iodine deficiency disorders).

Det tydeligste symptomet på jodmangel er struma, som er en samlebetegnelse på tilstander som gir forstørret skjoldbruskkjertel. Ved mangel på jod, vil mengden T4 i sirkulasjonen reduseres. Dette øker utskillelsen av TSH fra hypofysen, som deretter stimulerer skjoldbruskkjertelen til å lage mer hormon. Pga utlistrekkelige mengder jod, kan ikke kjertelen produsere hormonet. I stedet stimuleres cellene til økt celledeling, og kjertelen vokser. Hovedproblemet med en forstørret skjoldbruskkjertel er at den kan legge press på andre strukturer i halsområdet, som luft- og spiserøret, samt at den kan skade nerver i området. Når tyroideafolliklene etterhvert slår seg sammen kalles det for nodulær struma.

Tyroideahormonene er nødvendig for normal utvikling av sentralnervesystemet. Tilstrekkelige mengder hormon er viktig for myeliniseringen av nervecellene,  og en mangel tidlig i livet kan gi alvorlige, mentale skader. Kretinisme er en alvorlig mental lidelse som skyldes jodmangel i denne perioden, og kjennetegnes ved tap av hørsel og tale, kortvoksthet, kramper/spasmer og kraftig mental retardasjon.

Graviditet fører til et økt stress på morens skjoldbruskkjertel, da hun må produsere tyroideahormoner både til seg selv og til fosteret. Mangel på jod kan derfor skape problemer både på mor og foster. Alvorlig mangel under graviditet kan gi økt forekomst av dødfødsler, aborter eller barn med medfødte misdannelser. Spermieproduksjonen og normal menstruasjonssyklus er også avhengig av normal produksjon av tyroideahormoner, og både redusert og økt produksjon av disse hormonene kan forstyrre disse systemene.

Hypotyreose, eller lavt stoffskifte som det ofte betegnes som, kjennetegnes ved for lav produksjon av tyroideahormoner og har mange konsekvenser. Symptomer som at man føler seg trøtt og tiltaksløs, fryser lett, er deprimert og ukonsentrert, og opplever hukommelsessvikt er vanlig. Kroppsvekten vil vanligvis øke, samtidig som man får smerter i ledd, humørsvingninger og søvnproblemer.

Mangel på andre næringsstoffer kan forverre en jodmangel. Mangel på [selen](selen.qmd) kan øke aktiviteten til TSH dersom man har jodmangel, noe som øker risikoen for å utvikle struma.

## Kan vi få for mye?

For stort inntak av jod kan gi hypertyreose, men høyt inntak gir langt mindre skade enn et utilstrekkelig inntak vil gjøre, og vi tåler ganske store mengder før det gir betydelige skader. Hypertyreose kjennetegnes ved et økt stoffskifte, og symptomer på dette kan blant annet være hjertebank og hurtig puls, økt kroppsvarme, svetting, irritabilitet, vekttap til tross for økt appetitt, søvnforstyrrelser og muskelsvakhet.

Hos folk med tilstrekkelig jodstatus kan høyt inntak føre til det som kalles subklinisk hypotyreose. Dette skyldes at stort overskudd av jod hindrer produksjonen av tyroideahormoner, ved å blokkere koblingen av MIT til Tg. Frigjøringen av hormon fra skjoldbruskkjertelen kan også blokkeres. Som et resultat får vi en redusert produksjon av tyroideahormoner, noe som gir økt TSH, som igjen stimulerer til cellevekst i skjoldbruskkjertelen. Dette kan også ramme nyfødte dersom mor har hatt et veldig høyt inntak.

Høyt jodinntak kan også føre til hypertyroidisme. Ved struma, og da spesielt nodulær struma, kan tyrocyttene bli mindre sensitive for TSH sine signaler. Dersom man da over tid tilfører mye jod, så kan produksjonen av tyroideahormoner øke så mye at vi utvikler hypertyroidisme. Dette kan være spesielt farlig dersom man har underliggende hjertesykdom, da det i verste fall kan være dødelig.

Akkutt jodforgiftning gir magesmerter, diaré, kvalme, oppkast og hodepine, samt i alvorlige tilfeller kardiovaskulære symptomer og koma. De fleste tåler imidlertid ganske store doser godt.

## Gode kilder

Gode kilder til jod er sjømat, meieriprodukter og salt som er beriket med jod, f.eks. JOZO salt. Sjpmat inneholder jevnt over mer jod ettersom sjøen er spesielt rik på mineralet.

*Artikkelen er sist oppdatert juli 2013*
