---
title: "Kalium"
date: "2013.06.06"
categories: 
  - næringsstoffene
  - mineraler
---

[Tilbake til artikkelserien om næringsstoffene](../../naeringsstoffer.html)

Kalium er vår viktigste intracellulære kation, og har mange viktige funksjoner i kroppen. Regulering væskebalansen i kroppen, samt opprettholdelse av membranpotensialer og dermed funksjonen til alle cellene i kroppen er de viktigste. Gjennomsnittlig vil en mann på 70kg inneholde ca 120g kalium. I denne artikkelen får du en kort innføring i hvordan kalium metaboliseres i kroppen.

## Opptak og metabolisme

Rundt 90% av alt kalium i maten vi spiser vil aktivt absorberes i tynntarmen. Etter et måltid vil kaliumkonsentrasjonene i blodet øke, men dette er svært forbigående ettersom opptaket til cellene skjer raskt. Inne i kroppen finner vi derfor mesteparten av kaliumet (omtrent 98%) inne i cellene, og det er derfor vår viktigste intracellulære elektrolytt.

Konsentrasjonen av kalium inne i cellene (140-150mmol/L) og i blodet (3,5-5mmol/L) er nøye regulert. På grunn av konsentrasjonsgradienten så vil kalium diffundere fra cellene og ut i blodet. Det motsatte gjelder for natrium, som hovedsakelig befinner seg utenfor cellene, og vil diffundere inn. I cellemembranen har vi en pumpe som heter natrium/kalium-pumpen (Na/K-pumpen), som aktivt pumper disse elektrolyttene motsatt vei, og på denne måten opprettholder konsentrasjonene slik de skal være. Reguleringen av disse konsentrasjonene er viktig for å opprettholde membranpotensialet som er viktig for signaliseringen mellom cellene og deres funksjon. Denne pumpen krever energi, og aktiviteten stimuleres blant annet av insulin.

Sirkulerende kalium tas opp i alle vev. Blodkonsentrasjonene av kalium er under normale omstendigheter relativt stabile, som følge av at mesteparten fraktes inn i cellene. Opptaket til cellene reguleres blant annet av hormonene insulin, aldosteron og katekolaminene adrenalin og noradrenalin.

Også nyrene er sentrale i reguleringen av kaliumbalansen, og overskuddet skilles effektivt ut. Selv om nyrene kan tilpasse utskillelsen til både høyt og lavt inntak, vil minimum 5 mmol (0,2g) skilles ut daglig, og ved inntak under 0,4-0,8g vil vi ikke klare å opprettholde kaliumbalansen.

## Funksjoner

Kaliums viktigste funksjon er i dannelsen av cellenes membranpotensialer. Disse potensialene avhenger av konsentrasjonen av kalium på inn- og utsiden av cellen, og reguleres via Na/K-pumpen som beskrevet over.

Membranpotensialene er viktig for signalisering mellom cellene, blant annet i ledning av nerveimpulser. Spesielt hjertet er avhengig av en godt regulert kaliumkonsentrasjon, og store forstyrrelser kan være svært kritiske for hjertets funksjon. Musklene og nyrenes funksjon er også i stor grad avhengig av kaliumbalansen.

I tillegg påvirker kalium nyrenes utskillelse av blant annet natrium, og som dere vil se noen avsnitt lenger ned så har dette en innvirkning på blodtrykket!

## Behov og anbefalinger

Det er antatt at menneskene tidligere har inntatt mer kalium enn det vi gjør i dag. Dette er først og fremst på grunn av et økt inntak av prosessert industrimat, men også på grunn av et redusert inntak av frukt og grønnsaker.

De norske anbefalingene for kaliuminntak ligger på 3,5g for menn og 3,1g for kvinner. Litt lavere for barn. Det er ikke oppgitt noen økte behov ved graviditet/amming, så de generelle anbefalingene ligger her også. Per 100g inneholder poteter ca 0,5g, bananer ca 0,4g, og tomater ca 0,3g.

De som spiser et noenlunde fornuftig og variert kosthold har ikke noe problem med å dekke behovene, så lenge det totale matinntaket er tilstrekkelig. Forstyrrelser i kaliumbalansen skyldes svært sjelden for lavt eller høyt inntak.

## Kalium og blodtrykk

Normalt sett tenker vi først og fremst på salt når det er snakk om blodtrykk, og viktigheten av å redusere saltinntaket understrekes ofte i denne sammenhengen. Det er imidlertid mange studier som har demonstrert at et høyt kaliuminntak også bidrar til å redusere blodtrykket. Mekanismene her henger sammen med at høyt inntak av kalium vil øke utskillelsen av natrium over nyrene, og på den måten reduseres blodvolumet og blodtrykket.

Å øke inntaket av kalium gjennom å spise mer frukt og grønnsaker kan derfor være en viktig intervensjon for å redusere problemer relatert til økt blodtrykk, og ikke minst vil dette være enklere enn å redusere inntaket av salt. Lavt inntak av kalium kan forverre problemene hos de som allerede har et forhøyet blodtrykk, ettersom det kan bidra til redusert natriumutskillelse.

DASH-dietten (Dietary Approaches to Stop Hypertension) inneholder rikelig med kaliumrike matvarer, og det er antatt at det økte kaliuminntaket er den viktigste faktoren for hvorfor denne dietten har vist seg svært effektiv for å redusere høyt blodtrykk. Dette underbygges av at studiedeltakerne som hadde økt inntaket av frukt og grønnsaker (kalium) vedlikeholdt reduksjonen i blodtrykket på tross av at de hadde økt saltinntaket igjen.

## Mangel

Hypokalemi, lave kaliumkonsentrasjoner i blodet, er sjelden forårsaket av for lavt inntak av kalium. Dette er fordi dette stort sett alltid skjer i kombinasjon med lavt energiinntak, noe som gir nedbrytning av kroppsvev og frigjøring av intracellulært kalium. Hypokalemi kan oppstå når kroppens totale kaliumlagre reduseres, eller det kan også oppstå som følge av økt opptak fra blodet til cellene.

Årsaker til hypokalemi kan være diaré og oppkast, ettersom dette vil øke tapet av kalium både via urin og avføring via kompliserte mekanismer. Merk at det her er snakk om vedvarende oppkast/diaré, ofte grunnet underliggende sykdom, ikke enkelttilfeller. Forstyrrelser i hormoner som regulerer kaliumkonsentrasjonen kan også være årsaker til hypokalemi, deriblant overproduksjon av aldosteron eller renin. Vanndrivende medikamenter kan påvirke nyrenes utskillelse av kalium og derfor være en årsak. Metabolsk alkalose er også en årsak til hypokalemi, ettersom dette vil øke utskillelsen av kalium over nyrene. Lavt inntak kan i ytterste konsekvens føre til hypokalemi, men dette er først og fremst knyttet til kronisk alkoholisme eller anoreksi og da som følge av at lagrene tappes over tid. Hormonelle forstyrrelser som hyperaldosteronisme kan også medføre hypokalemi som følge av at for mye føres inn i cellene.

Mild hypokalemi trenger ikke å gi symptomer, men det første man merker kan være muskelsvakhet, forstoppelse eller slapphet. Mer alvorlig hypokalemi kan føre til forstyrrelser i hjerterytmen og i verste fall hjertestans. Pusteproblemer kan også oppstå som følge av svekkelse av pustemusklene.

Dersom hypokalemien oppstår raskt er det større risiko for å utvikle hjerterelaterte symptomer. Dette kan forekomme som en del av det som er kjent som reernæringssyndrom, som er en konsekvens av reernæring etter langvarig underernæring. Det som skjer da er at vi får en plutselig økning i transporten av kalium fra blodet og inn i cellene som følge av aktivering av Na/K-pumpen, og kaliumkonsentrasjonene i blodet synker raskt. Av denne grunn følger man i slike situasjoner med på elektrolyttstatus under reernæring, slik at dette kan korrigeres underveis.

Hypokalemi behandles ved å tilføre mer kalium eller ved å gjøre noe med nyrenes utskillelse.

## Kan vi få for mye?

Hyperkalemi vil på samme måte som hypokalemi påvirke cellenes membranpotensiale. I verste fall kan dette føre til hjertestans, men som ved hypokalemi så spiller hastigheten på utviklingen inn i stor grad på risikoen her. Muskulære symptomer på kaliumoverbelastning er kribling, svakhet og lammelser. Mental forvirring er også et symptom.

Det er viktig å skille mellom sann hyperkalemi og pseudohyperkalemi. Sistnevnte kan oppstå som følge av ødeleggelse av røde blodceller, som gir frigjøring av kalium som befant seg inne i disse. Dette har ingen fysiologiske konsekvenser.

Sann hyperkalemi kan oppstå som følge av redusert nyrefunksjon eller ved transport av kalium fra cellene og ut i blodet. Ved acidose vil kaliumfrigjøringen fra celler øke, og det samme skjer ved langvarig underernæring og påfølgende nedbrytning av kroppsvev. Normalt sett vil nyrene ta seg av dette, men ved nedsatt nyrefunksjon kan hyperkalemi oppstå. Hormonelle forstyrrelser i de hormonene som regulerer kaliumbalansen er også en årsak, spesielt mangel på aldosteron eller insulin (som ved diabetes). For høyt inntak av kalium er svært sjelden en årsak til hyperkalemi.

Hard trening kan gi en økning i kaliumkonsentrasjonene i blodet som følge av frigjøring fra muskelcellene. Normalt er denne hyperkalemien mild og hurtig forbigående, men i ytterste konsekvens kan dette medføre hjertestans, men dette er svært sjeldent. Dette gjelder spesielt personer med diabetes (insulinmangel) eller folk som får medikamenter som hemmer katekolaminenes effekt (β-adrenerge blokkere).

Hyperkalemi behandles ved kostrestriksjoner og ved å gjøre noe med den underliggende årsaken.

## Gode kilder

Kalium finnes i de fleste matvarer, men hovedkildene til denne elektrolytten er frukt og grønnsaker. Spesielt dersom vi ser kaliuminnholdet i forhold til energimengden kommer disse matvarene spesielt godt ut. Bananer, poteter, sitrusfrukter og tomater er eksempler på gode kilder.

## Aktuelt om kalium

-   Det er holdepunkter for at [en høy ratio mellom natrium:kalium er forbundet med økt risiko for hjerteinfarkt](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2629129/), og det er derfor antatt at en reduksjon av saltinntaket kombinert med å øke inntaket av kalium kan være med å forebygge hjertesykdom.
-   [En helt fersk metaanalyse](http://www.bmj.com/content/346/bmj.f1378) på sammenhengene mellom kalium og blodtrykk (takk til [Erik Arnesen](http://www.sunnskepsis.wordpress.com) for tips)
-   [Kaliumredusert kost](http://www.friskogfunksjonell.no/kaliumredusert-kost/ "Kaliumredusert kost") benyttes hos pasienter med nyresykdom

Informasjonen i artikkelen er hentet fra bøkene Modern Nutrition (Shils et al), Present Knowledge in Nutrition (Erdman et al) og Textbook of Medical Physiology (Guyton&Hall)

*Artikkelen er sist oppdatert juni 2013*
