---
title: "Sink"
date: "2011.11.05"
categories: 
  - næringsstoffene
  - mineraler
---

[Tilbake til artikkelserien om næringsstoffene](../../naeringsstoffer.html)

Sink har atomnummer 30, og regnes som et sporelement. Omtrent 10% av proteinene i kroppen vår er avhengig av sink for å formes som de skal og dermed fungere. Sink inngår i over 100 enzymer som blant annet påvirker omsetningen av næringsstoffer, cellevekst, reproduksjon, immunforsvar, sårheling og hormonproduksjon, og er derfor essensielt i alle dyre- og planteceller. Globalt har WHO estimert at rundt halvparten av verdens befolkning har suboptimal sinkstatus, og dette sporstoffet er et av de fire store satsingsområdene når det gjelder spesifikk feilernæring.

Sink foreligger vanligvis som et divalent kation, Zn2+, og er det mest utbredte sporelementet intracellulært. I kroppen finner vi sink i størst grad i skjelettmusklene og beinvevet, og det totale innholdet er omtrent 1,5g hos kvinner og 2,5g hos menn.

## Opptak

Opptak av sink skjer i hele tynntarmen. Aktivt opptak av sink til tarmcellene skjer gjennom transportproteinet Zip4, og mengden Zip4 er høyest lengst oppe i tarmen noe som gjør at opptaket er høyest her. Sink kan også absorberes passivt ved paracellulær transport (mellom tarmcellene). Konsentrasjonen av sink i tarmene etter et måltid er høyere enn den er inne i tarmcellene, noe som gjør at mineralet passivt diffunderer inn i cellene og ikke motsatt vei. Det passive opptaket er av naturlige årsaker også høyest i begynnelsen av tynntarmen, siden konsentrasjonene av sink vil være høyest her. Ved lavt inntak vil de aktive transportmekanismene dominere, mens de passive vil ha mer å si når inntaket øker. Nøyaktig hvordan absorbsjonen av sink reguleres er det forsket mye på, men foreløpig er dette ikke godt forstått. Det er identifisert en rekke sinktransportere, og disse er klassifisert i to familier; ZnT (10 kjente) og Zip (14 kjente). Disse befinner seg i ulike vev, både i cellemembraner og inne i selve cellene, og er involvert i hvordan sink transporteres og fordeler seg i kroppen. Generelt er Zip-proteinene involvert i opptak av sink til celler og ulike deler inne i cellene, mens ZnT-proteinene transporterer mineralet motsatt vei.

Inni tarmcellene bindes sink til molekylet metallothionein, som regulerer hvor mye som fraktes videre til blodet. Fra tarmcellene fraktes sink over i portåren, og transporteres til leveren. I blodet finner vi sink hovedsakelig bundet til albumin, og noe er også bundet til α2-makroglobulin. Konsentrasjonen av sink i blodets plasma er lav, og innholdet i de røde blodcellene er mye høyere. Hemolyse av disse kan derfor være et kraftig forstyrrende element ved analyser av sinkinnholdet i blod.  Spesifikke sinktransportere fører sink inn i målcellene. Inne i cellene kan sink enten bindes til metallothionein, som sørger for at mineralet fanges inne i cellen, det kan brukes til sinkavhengige prosesser eller det kan passere ut i blodet igjen.

Per i dag kjenner vi ikke til noen spesifikke sinklagre som skal bidra til å opprettholde likevekt over lenger tid. Spiser vi for lite sink så vil symptomene på sinkmangel oppstå ganske raskt. Hovedsakelig reguleres sinkhomeostasen ved å øke eller redusere opptaket. Spiser vi lite sink vil vi absorbere en større andel enn dersom vi spiser mye sink, og utskillelsen i avføringen vil dermed også følge inntaket. Dette reguleres muligens ved å endre uttrykket av sinktransporterne, og det er blant annet observert at høyt inntak av sink vil nedregulere uttrykket av Zip4 i tarmcellene, slik at den aktive absorbsjonen reduseres. Når intracellulært sink øker så vil transportproteiner som transporterer sink ut fra cellene (sånn som ZnT-1) oppreguleres, noe som bidrar til å øke utskillelsen.

Når vi spiser et måltid vil vi skille en del endogent sink ut i tarmen, både i bukspyttet og gallen. Dette sinket er tilgjengelig for å absorberes igjen, eller det kan skilles ut i avføringen. Sink som er bundet til metallothionein i tarmcellene vil skilles ut fra kroppen i avføringen når tarmcellene dør. Kroppens opptak av sink er sterkt, homeostatisk regulert, og et økt inntak vil føre til økt konsentrasjon i avføringen og motsatt. Normalt skiller vi ut svært lite gjennom urinen, men under katabole forhold kan dette øke.

## Funksjoner

Sink utfører sin funksjon via ulike proteiner, og det er identifisert over 3000 mulige sinkproteiner i mennesket. Sink inngår i mange enzymer, og er essensielt i prosesser som genregulering, hormonfunksjon, metabolisme av næringsstoffer, vekst og vedlikehold, reproduksjon og immunfunksjon. Sink har en strukturell funksjon i små proteiner, og sørger for at de folder seg korrekt ved å danne såkalte sink-fingre.

Vi kan dele sinks funksjoner inn i følgende kategorier: katalytiske, strukturelle og regulatoriske.

**Katalytiske funksjoner**

Vi kjenner til over 50 unike, sinkholdige enzymer, og da regner man bare med enzymer som mister sin funksjon dersom sink fjernes. Dette inkluderer enzymer innenfor alle de internasjonalt bestemte enzymklassene, noe som sier at disse er involvert i et bredt spekter av reaksjoner. Eksempler på slike enzymer er RNA polymerase, som er sentral i RNA-syntesen og karbonisk anhydrase, som er sentral i syre-base-reguleringen.

**Strukturelle funksjoner**

Proteiner må foldes riktig for å kunne utføre sine oppgaver. Sink bidrar til denne foldingen, ved å være med å danne strukturer kalt sink-fingre. Det er funnet over 2500 kodinger for sink-fingre i menneskets DNA.

**Regulatoriske funksjoner**

Sinkfingrene er med å mediere et proteins interaksjoner med andre proteiner, DNA, RNA eller lipider. Sink inngår i mange reseptorer, som er involvert i reseptor-mediert signaloverføring. Blant annet immunsystemets T-celler har reseptorer som inneholder sink. Transkripsjonsfaktorer er faktorer som binder til DNA og er med å regulere hvilke gener som uttrykkes, og disse inneholder ofte en eller flere sinkfingre som bidrar til at de binder til spesifikke steder på DNA. Dette gjelder blant annet kjernereseptorene til [A-](avitamin.qmd). Også enzymer involvert i reparasjon av DNA og regulering av cellesyklus og celledød er i mange tilfeller sinkavhengige.

Nervesystemet inneholder mye sink, spesielt i presynaptiske vesikler, og man tror at sink er sentralt i reguleringen av nervesignaler.

## Behov og anbefalinger

Behovet for sink beregnes utifra hvor mye som skilles ut hver dag. Det finnes ingen pålitelige målinger som kan si noe om sinkstatus hos enkeltindividet, noe som gjør det vanskelig å sette korrekte anbefalinger.

De norske anbefalingene bygger på WHO sine anbefalinger, og er ca 10mg/dag, noe som tilsvarer mengden du får i deg ved å spise ca 150g storfekjøtt, 200g cashewnøtter eller 500g bønner.

## Mangeltilstander

Nivåene av sink i blodet er sterkt homeostatisk regulert, men langvarig lavt inntak vil etterhvert føre til at nivåene synker slik at vi utvikler hyposinkemi. Sinkmangel har flere kjente symptomer, deriblant hemming av vekst, nedsatt immunforsvar, dårlig sårheling og nedsatt apetitt. Funksjonen til steroidehormonene vil nedjusteres, og glukosetoleransen og fettmetabolismen vil også svekkes. Den foreløpige forståelsen for sinkmangel er basert på hvordan folk reagerer på tilskudd av sporelementet.

Sink har direkte effekter på hormoner som styrer celledeling og matinntak, f.eks. Insulinlignende vekstfaktor (IGF) og [leptin](../leptin-tykt-tynt.qmd), og dette kan være med å forklare hvorfor en mangel kan hemme vekst. IGF stimulerer til celledeling og hemmer apoptosen (programmert celledød). Det er diskutert hvorvidt redusert vekst skyldes sinkmangelen i seg selv eller om det er en konsekvens av nedsatt matinntak. En forklaring er at vekst nedreguleres for å spare sink til viktige metabolske prosesser, og dette støttes ved at forsøksdyr som får tilstrekkelig tilførsel av sink vokser mer enn de som ikke gjør det til tross for at matinntaket ellers er likt. Nedsatt matinntak spiller selvfølgelig en rolle, men det forklarer ikke veksthemmingen alene.

Immunforsvaret inneholder mange sinkavhengige strukturer, og mangel på sink kan føre til at parasittiske eller mikrobielle infeksjonsagenter ikke blir drept, men heller kan utvikle seg. Sinkmangel stimulerer til programmert celledød i prosessen med å produsere nye immunceller. Det er blant annet observert redusert størrelse av tymus ved sinkmangel, som følge av atrofi av tymuscellene. Aktiviteten til immunceller er også avhengig av sink.

Generelt sett er det fem ulike årsaker til at man utvikler sinkmangel: Utilstrekkelig inntak, økt behov, malabsorbsjon, økte tap eller forstyrrelser i sinkmetabolismen. Disse kan oppstå alene eller i kombinasjoner. Malabsorbsjon som ved eksempelvis cøliaki, inflammatoriske tarmsykdommer, kort tarm eller infeksjoner i tarmsystemet (diaré) er sammen med økte tap i urinen den viktigste årsaken til mangel. I tillegg kan et kosthold som inneholder mye fytat redusere biotilgjengeligheten slik at vi ikke tar opp nok. Kronisk alkoholisme bidrar også. En sjelden genetisk sykdom, Acrodermatitis Enterohepatica, gir et defekt Zip4-protein, noe som hindrer opptak fra tarmen. Det er også indikasjoner på at enkelte fedmeoperasjoner kan bidra til sinkmangel.

Sinkmangel som følge av utilstrekkelig inntak er sjelden i Europa. Likevel kan mangel oppstå, spesielt hos unge (som har høyere behov), dersom inntaket av sink er lavt og dietten inneholder mye fytat. Ved hyppig diaré, kan opptaket reduseres betraktelig, og mangel kan oppstå. Marginal sinkmangel kan være vanskelig å oppdage, og grunnet mangelen på gode markører for sinkstatus er dette et ganske kontroversielt felt. Det er stor enighet om at plasmanivåene av sink er en dårlig markør for sinkstatus, ettersom denne ikke synker nevneverdig før sinkinntaket er så lavt at homeostasen ikke lenger kan opprettholdes. Derfor er dette en markør som kan avdekke alvorlig mangel, men ikke en mer marginal sinkstatus. Det er mulig at marginal mangel kan oppstå i perioder der sinkforbruket er høyt, som ved graviditet eller ved vekst.

## Kan vi få for mye?

Sinkforgiftning som følge av inntak fra mat er svært sjelden. Symptomer på forgiftning er magesmerter, kvalme, oppkast og diaré. Kronisk forgiftning, som følge av bruk av kosttilskudd over lengre tid, kan gi nedsatt immunfunksjon og redusert HDL. Sink påvirker opptaket av kobber, og kobbermangel er den vanligste rapporterte bivirkningen av kronisk høyt sinkinntak. Den øvre grensen for inntak er satt til 40mg/dag for voksne.

For høye mengder sink er i praksis bare mulig ved stort inntak av syreholdig mat som har vært oppbevart i en galvanisert beholder (syren frigir sink fra beholderen), eller ved inntak av tilskudd. ZMA er et populært kosttilskudd som inneholder sink.

## Gode kilder

Biotilgjengeligheten til sink påvirkes i stor grad av andre bestanddeler i maten vi spiser. Komponenter som reduserer biotilgjengeligheten kan gjøre dette enten ved å binde seg til sink og danne komplekser som ikke absorberes, eller ved å konkurrere om absorbsjonsmekanismene. Fytat fra korn og belgfrukter er et eksempel på en forbindelse som kan binde til sink og hindre opptak. Oksalat (hvete, kaffe/te, soya, sjokolade, nøtter m.m.) er en annen forbindelse som reduserer opptaket av sink. Det er også kostholdsfaktorer som øker opptaket av sink, deriblant enkelte aminosyrer som kan binde seg til sink gjøre at det tas lettere opp.

Sink finnes i alle plante- og dyreceller, og dermed i all mat. Spesielt gode kilder til sink er skalldyr, kjøtt og fisk. Disse er regnet som spesielt gode kilder ettersom de ikke inneholder faktorer som reduserer opptaket samtidig som de er rike på aminosyrer som øker opptaket. I kornprodukter finner vi sink først og fremst i skallet, noe som gjør at fullkorn er en god kilde mens fint mel inneholder lite.

## Aktuelt om sink

-   Tilskudd av sink har vist seg å være effektivt mot akutt diaré, spesielt hos barn. En av mekanismene som ligger til grunn for diaré er at kloridioner skilles ut i tarmen, og disse trekker med seg væske som gir løs avføring. Cellestudier har vist at sink kan hemme tre av fire signalveier involvert i denne kloridutskillelsen, noe som gir en mekanistisk forklaring på hvorfor tilskudd hjelper.

-   Sinktransporterne kan også transportere andre stoffer, deriblant tungmetallet kadmium. Derfor er det plausibelt at sinkmangel kan øke risikoen for kadmiumtoksisitet. Kadmium får vi blant annet i oss gjennom sigarettrøyking, noe som tilsier at sinkstatus kan påvirke risikoen for sykdom hos røykere.

-   Ettersom fødselsdefektene som kommer som følge av sinkmangel er veldig like de som er antatt å skyldes alkoholbruk under svangerskapet, er det foreslått at alkoholindusert sinkmangel kan være mekanismen som ligger til grunn for dette.

-   Diabetes kan øke urinutskillelsen av sink, og hyposinkemi er et vanlig funn hos diabetikere. Det er imidlertid ikke funnet noen fordelaktige effekter ved sinktilskudd hos denne populasjonen.

-   Enkelte proinflammatoriske cytokiner har vist seg å øke sinkopptaket i leveren. Økt sinkinnhold induserer metallothionein inne i leveren, noe som bidrar til stress- og inflammasjonsindusert hyposinkemi. Dette kan være et potensielt behandlingsmål for en rekke kroniske, inflammatoriske sykdommer.

*Artikkelen er sist oppdatert juli 2013*
