---
title: "Svakheter i ernæringsepidemiologi"
date: 2014.04.24
---

[Tilbake til kildekritikk, vitenskap og tankefeil](../../kildekritikk.qmd "Kildekritikk, vitenskap og tankefeil")

I artikkelen «[er forskning til å stole på](forskning-troverdig.qmd "Er forskning til å stole på?")» kunne du lese om hvorfor det er viktig å se på effektstørrelser og hvorfor det er viktig at studier replikeres av andre. I denne artikkelen vil jeg se nærmere på ernæringsforskning og svakheter med denne. Advances in Nutrition publiserte i januar en reviewartikkel som drøfter svakheter med observasjonsstudier innen ernæring og hvilke implikasjoner dette har for hvordan vi leser disse artiklene og hvilke råd vi skal gi \[1\].

## Studietyper

Selv om randomiserte kliniske studier troner øverst i evidenshierarkiet, er det store utfordringer med å gjennomføre slike studier innen ernæring. For det første er det vanskelig å kontrollere alle variabler ettersom maten vi spiser er en ekstremt kompleks suppe med kjemikalier, og et bytte fra en matvare til en annen fører til endring i mange av disse. I tillegg vil kostholdsrelaterte sykdommer utvikles over lang tid, og det å gjennomføre en kontrollert studie over flere år er så godt som umulig.

Derfor gjennomfører man heller studier av kortere varighet, og baserer seg på myke endepunkter som endringer i biomarkører som for eksempel kan måles i blod. Eksempler på slike kan være blodsukker eller kolesterolverdier, og selv om disse kan være informative i seg selv, vil de aldri være et fullgodt alternativ til å undersøke sykdom og død direkte.

På grunn av dette er de fleste kostrådene bygget på det beste vi har tilgjengelig, nemlig prospektive observasjonsstudier. Ved å følge store grupper over lengre tid, og registrere hva de spiser (som oftest ved å spørre dem om hva de vanligvis spiser), kan man finne sammenhenger mellom kosthold og utvikling av sykdommer. Da er det viktig å også være klar over alle svakhetene denne typen studier er beheftet med, slik at man kan gjøre bedre vurderinger og tolkninger av resultatene og konklusjonene.

## Innsamling av kostholdsdata

Det å registrere matinntaket har mange innebygde feilkilder, og er kanskje den største svakheten med all ernæringsforskning. For det første er en detaljert innsamling av kostdata en omfattende prosess, og man er avhengig av en enorm nøyaktighet blant studiedeltakerne. Dette kan la seg gjøre i korte studieperioder med få deltakere, men med en gang studiene blir større og lengre blir man nødt til å ta i bruk enda mindre nøyaktige metoder. Det vanligste i store studier er såkalte matvarefrekvensskjema, der deltakerne fyller ut spørreskjema der de svarer på hvor ofte og hvor mye de spiser av ulike matvarer, og forskerne deretter estimerer inntaket basert på dette. Selve estimeringen av matinntaket basert på kostregistrering er heller ikke helt nøyaktig, da innholdet i to like matvarer kan være forskjellig fra hverandre, så her opererer man med gjennomsnittsverdier.

Disse spørreskjemaene går ofte bakover i tid, noe som introduserer enda en feilkilde, nemlig det at svarene baseres på hva deltakerne mener at de har spist. Hvor mye fet fisk har du spist det siste året? I tillegg vet vi også at det er en kraftig tendens til under- og overrapportering av hva man selv har spist, der typisk overvektige underrapporterer mens undervektige overrapporterer. Dette påvirker selvfølgelig også estimatene av mikronæringsstoffene.

Matvarefrekvensskjema gir også flere feilkilder. Det er lite praktisk å spørre om hver enkelt matvare, slik at det tas utgangspunkt i hvor mye man har spist av ulike matvaregrupper. Dette inkluderer også ulike tilberedningsmetoder, som vi vet vil kunne påvirke innholdet av næringsstoffer. I tillegg til dette har de aller fleste et kosthold som endres over tid, så det å generalisere ut fra enkeltregistreringer er også problematisk, spesielt om man ønsker å finne sanne sammenhenger. I de groveste tilfellene er kostholdet bare registrert på ett enkelt tidspunkt, før man prøver å finne sammenhenger mellom kosthold og helse over lang tid.

## Sammensetning og valg av matvarer

En matvare er satt sammen av mange næringsstoffer, og faktisk over 25 000 ulike bioaktive komponenter identifisert. Matvaregrupper som er spesielt rik på et spesifikt næringsstoff er ofte også veldig rik på andre stoffer, noe som gjør at det er en sammenheng mellom mengden av de ulike næringsstoffene i kostholdet. Et godt eksempel er kornvarer, som er hovedkilden vår til kostfiber. Samtidig er kornvarer en viktig kilde til B-vitaminer. Rødt kjøtt er en god kilde til jern, men bidrar samtidig med mye protein og mettet fett. På grunn av dette er det vanskelig å identifisere selvstendige effekter av et næringsstoff, da matvarevalg påvirker mange stoffer på en gang.

Dette bringer oss over på det som kan kalles substitusjonseffekter. Ettersom vi har et visst energibehov så vil en økning eller reduksjon i inntaket av en matvare som oftest føre til en motsatt effekt på andre matvarer. Spiser vi mer av noe, spiser vi sannsynligvis mindre av noe annet. Dersom dette byttet har en eller annen effekt, er dette da en effekt av å spise mer av A eller mindre av B? Dette vil være svært vanskelig å si noe om ut fra observasjonsdata.

En annen viktig faktor som kan påvirke resultatene er [helsebevisste individer](helsebevissthet.qmd "Helsebevisste individer – en forstyrrende faktor i forskningen?"). Enkelte matvaregrupper er i stor grad assosiert med en generelt sunn livsstil, som inkluderer mye fysisk aktivitet osv. Andre matvaregrupper er i større grad assosiert med det motsatte, der helse gjerne ikke står som første prioritet. I observasjonsstudier er det vanskelig å se om effektene man observerer er en konsekvens av matvaren man undersøker eller om det er andre egenskaper med disse menneskene som gir en effekt. Menneskene som undersøkes bestemmer jo selv hva de spiser, og disse valgene vil naturligvis påvirkes av både livsstil og andre faktorer. Gode eksempler på dette kan være det å spise mye frukt og grønnsaker, et høyt inntak av sukker eller rett og slett det å følge spesifikke dietter/kosthold. Et annet godt eksempel kan være assosiasjoner mellom sukkerfri drikke og overvekt, der den mest plausible årsaksretningen er at overvektige velger disse drikkene for å slanke seg, ikke at disse drikkene på noen måte forårsaket overvekten.

## Små effektstørrelser i ernæringsforskning

En annen viktig ting å ha i bakhodet når man leser epidemiologiske ernæringsstudier er at effektstørrelsene som rapporteres ofte er små. Som du kanskje husker fra [forrige artikkel](forskning-troverdig.qmd "Er forskning til å stole på?") så vil en oddsratio under 1.5 i denne typen studier tilsvare en liten og svak assosiasjon, og at vi må opp mot en oddsratio over 5 for å kunne snakke om en stor effekt \[2\]. De fleste assosiasjoner som kommer frem i ernæringsepidemiologi har en oddsratio under 2, og konfidensintervallene er ofte ganske brede. Samtidig er disse studiene ofte gjort på enorme populasjoner, og med så store grupper kan selv små og praktisk irrelevante resultater bli statistisk signifikante. Dette understreker nok en gang betydningen av også å vurdere effektstørrelsen.

Jo nærmere en effekt er null (oddsratio=1), jo større er sjansen for at observasjonen er tilfeldig og påvirket av andre faktorer. Når vi vet hvor store feilkildene i datainnsamlingen kan være når det kommer til forskning på ernæring, er dette noe som er veldig viktig å ha i bakhodet. Med andre ord vil små effektstørrelser tilsi at muligheten for at funnet er en falsk positiv er ganske stor. Spesielt gjelder dette for utforskende analyser der man undersøker mange forskjellige faktorer uten å ha noen spesifikk hypotese på forhånd.

## Korrelasjon er ikke det samme som kausalitet

Du har kanskje hørt det før, at det er en korrelasjon betyr ikke at det er snakk om et årsaksforhold hvor det ene forårsaker det andre. Et vanlig, men flåsete, eksempel er sammenhengen mellom issalg og drukningsulykker. Forårsaker issalget at flere drukner, eller er det mer sannsynlig at i den perioden av året flest spiser is, altså om sommeren, er det også flere som bader og dermed flere som drukner. En annen ting som kan være verdt å tenke på er en eventuell årsaksretning. Vil det at brannmenn samles rundt huset ditt gjøre at det begynner å brenne, eller er den motsatte retningen et mer sannsynlig scenario?

Selv om man observerer at to ting skjer samtidig er det ikke sikkert at de har noe med hverandre å gjøre. Dette gjelder også når det kommer til sammenhenger som observeres mellom maten vi spiser og helseutfall. I epidemiologiske studier kan man finne mange sammenhenger mellom atferd og utfall, men til og med når man observerer det samme gang på gang er det ikke sikkert at det er en reell sammenheng. Det beste eksempelet på dette er effekten kvinner får av å ta østrogentilskudd etter overgangsalderen. I observasjonsstudier viste dette seg konsekvent å være forbundet med lavere hjertedød, men når man testet det i en eksperimentell studie viste det seg at dette tilskuddet faktisk økte dødeligheten. Dette viste seg å være et godt eksempel på effekten av helsebevissthet, da de som brukte østrogentilskudd viste seg å være de som var mest opptatt av å ta vare på helsen sin generelt, og at dette slo ut i en konsekvent korrelasjon mellom østrogentilskudd og bedre helse. Innen ernæring er det flere eksempler på sammenhenger som konsekvent viser seg i observasjonsstudier som ikke lar seg finne igjen når man tester det i eksperimentelle studier, noe som gjør at man bør være forsiktig med å basere seg på observasjonsstudier alene.

Egentlig blir det mer riktig å si at korrelasjon ikke nødvendigvis betyr kausalitet, for det finnes noen eksempler hvor det kan være mulig å utlede kausalitet fra disse dataene. Allerede i 1965 foreslo Sir Austin Bradford Hill, en kjent epidemiolog, 9 kriterier som måtte være oppfylt for at man skulle kunne gjøre dette \[3\]. Blant disse finner vi først kriteriet styrke, som i praksis betyr at effektstørrelsen må kunne betraktes som stor. Deretter må observasjonen være konsekvent. Varierende resultater vil gjøre det vanskelig å fastslå kausalitet, men som vi har vært gjennom er det heller ikke sikkert at konsekvente assosiasjoner trenger å være kausale. Assosiasjonen bør også ha et tydelig dose-respons forhold, noe som betyr at økende eksponering også bør reflekteres i økende mengde utfall. At observasjonen er biologisk plausibel er et annet viktig kriterie. Sammenhengen må altså kunne gi mening rent teoretisk. Utfallet må selvfølgelig også skje etter årsaken, og sammenhengen bør også være i noenlunde overensstemmelse med allerede kjent kunnskap. Helt nye sammenhenger kan altså ikke sies å være kausale ut fra observasjonsdata alene.

## Konklusjoner

Sitter du nå igjen med et inntrykk av at ernæringsforskning er mer eller mindre verdiløst så har jeg bommet. Poenget med denne artikkelen er å sette fokus på svakhetene med ernæringsepidemiologi, og hvorfor det er så viktig å holde tungen beint i munnen når du leser resultater fra slike studier. Å komme med bastante uttalelser på bakgrunn av observasjonsstudier alene er sjelden en god ide. Samtidig er kosthold så komplekst, og kostholdsrelaterte sykdommer bruker lang tid på å utvikle seg, så observasjonsstudier er ofte det beste vi kan få til. Derfor vil nødvendigvis kunnskapen vi har om kosthold og helse i stor grad basere på denne typen data, noe som gjør det enda viktigere å være klar over begrensningene disse studiene bærer med seg.

Referanser:

1.  Maki KC, Slavin JL, Rains TM, Kris-Etherton PM: Limitations of observational evidence: implications for evidence-based dietary recommendations. Adv Nutr 2014, 5(1):7-15.

2.  Chen HN, Cohen P, Chen S: How Big is a Big Odds Ratio? Interpreting the Magnitudes of Odds Ratios in Epidemiological Studies. Commun Stat-Simul C 2010, 39(4):860-864.

3.  Hill AB: The Environment and Disease: Association or Causation? Proceedings of the Royal Society of Medicine 1965, 58:295-300.
