---
title: "Full kontroll?"
author: "Andrea Rørvik Marti"
date: 2013.06.13
---

[Tilbake til kildekritikk, vitenskap og tankefeil](../../kildekritikk.qmd)

Det å ha en kontrollgruppe er noe av det viktigste innen vitenskapen. Per definisjon innebærer faktisk et vitenskapelig eksperiment en inklusjon av kontroll. I denne artikkelen vil jeg først forklare det helt grunnleggende prinsippet bak bruken av kontroller i eksperimenter. Jeg vil så gå igjennom noen av de menneskelige biasene som kan elimineres ved bruk av godt designede studier. Helt til slutt vil jeg ta opp noen problemer som kan oppstå både i utførselen og gjennomgangen av kontrollerte studier. Det er ikke alltid like lett å ha full kontroll!

## Hvorfor må man ha en kontroll?

Vi starter enkelt. La oss si at du vil undersøke om vitamin C hjelper mot forkjølelse. Du tar 100 personer og gir dem vitamin C-tilskudd, og følger dem opp en måned senere. Du oppdager så at 95 av de 100 forkjølede individene er blitt friske. Fantastiske resultater! Vitamin C kurerer forkjølelse i 95% av alle tilfeller!

Nei, det er nok ikke så enkelt. Forkjølelse er noe alle får fra tid til annen, og noe de aller fleste blir friske fra på kort tid. Det kan altså være at disse 95 som ble friske hadde blitt det uten vitamin C-tilskuddet du distribuerte også. Dette kan man enkelt utelukke ved å bruke en kontrollgruppe.

La oss si at du i stedet for å gi samtlige 100 forsøkspersoner vitamin C, så deler du gruppen tilfeldig i to, og gir 50 stykker vitamin C og 50 stykker en pille uten noe virkestoff (placebo). Når du så en måned senere følger opp, kan du simpelthen sammenlikne hvor mange i vitamingruppen som ble friske fra forkjølelsen, og hvor mange i kontrollgruppen som ble friske. Da har du isolert vitamin C-tilskudd som den enkelte variabelen som skiller gruppene. Altså kan du være sikker på at andre faktorer som påvirker forkjølelse vil være utelukket. Dette er helt grunnleggende og ekstremt viktig i ethvert eksperiment. Kontrollgruppen representerer de endringene som ville skjedd uansett, og ved å sammenligne intervensjonsgruppen mot kontrollgruppen unngår man å tillegge intervensjonen effekter den ikke hadde.

## Kontroll reduserer bias

Det er en hel del faktorer som kan påvirke utfallet av et eksperiment. I studier med mennesker er dette uunngåelig, fordi vi blir påvirket av verden rundt oss. Det er mange omstendigheter rundt en studie som vil påvirke både deltakere og forskere, og effekten av disse kan reduseres ved hjelp av kontroller.

I intervensjonsstudier, som eksempelet brukt over, brukes som regel en placebokontroll. Dette vil si at både kontrollgruppen og gruppen man forsker på mottar en intervensjon (for eksempel en pille eller en injeksjon). Ingen av deltakerne i studien får vite om intervensjonen de mottar faktisk inneholder et virkestoff eller ikke. Dette gjøres for å eliminere placeboeffekten.

Placeboeffekten er noe som alle mennesker påvirkes av i ulik grad, og innebærer en bedring av symptomer etter en intervensjon som ikke direkte kan knyttes til den fysiske effekten av intervensjonen. Med andre ord; du blir bedre fordi du forventer at intervensjonen skal fungere, uten at den i realiteten har en effekt.  Det er fortsatt uvisst nøyaktig hvordan placeboeffekten fungerer, eller hvorfor den eksisterer, men den er like fullt reell, og kan påvirke forskningsresultater. Blant annet kan man bli påvirket av hvilken farge en placebopille (helt uten noe virkestoff) har; røde piller er mest effektivt mot smerte (1) og blå piller har best beroligende effekt (2). På samme måte har injeksjon av placebo en sterkere effekt enn piller, kapsler fungerer bedre enn tabletter, og placebo merket med navnet på et kjent legemiddelfirma fungerer bedre enn generisk placebo (3). Placebo fungerer til og med selv om personen som mottar den er fullt klar over at behandlingen de mottar ikke vil ha en effekt (4). Ved å gi alle deltakere i en studie tilsynelatende samme intervensjon kan man dermed utelukke at placebo har spilt inn på forskjeller mellom gruppene. Placebokontroll eliminerer placeboeffekten.

På samme måte som at deltakerne i en studie kan bli påvirket av at de tror de mottar behandling, kan også den som utfører behandlingen bli påvirket. Selv om resultatene måles objektivt kan det for eksempel hende at personen som deler ut pillene kan komme til å virke mer positiv når de administrerer behandling de vet inneholder et virkestoff. Kanskje vil de bruke litt andre ord, eller på andre måter uttrykke sine egne forventninger til virkningen av stoffet. På denne måten kan administratoren med sin væremåte øke deltakerens tro på behandlingen, og dermed fungere som en ekstra placebo. Dette kalles for observatør-forventingsbias (observer-expectancy bias). Et klassisk eksempel er «[Clever Hans](http://en.wikipedia.org/wiki/Clever_Hans)», en hest som man på begynnelsen av 1900-tallet var overbevist om at kunne løse enkle mattestykker. I realiteten viste det seg at Clever Hans sin trener hadde påvirket hestens adferd uten å være klar over det selv. Hesten var altså ikke noe matematisk geni, men derimot en kløpper på å plukke opp ikke-verbale tegn fra sin trener og publikum.

I kontrollerte placebostudier kan man kontrollere for observatør-forventningsbias ved å dobbel-blinde eksperimentet. Dette vil si at personene som administrerer behandlingen, og som foretar målinger av fremgang, ikke vet hvilke deltakere som har mottatt hvilken type behandling. Dermed kan ikke forskernes forventninger påvirke deltakernes resultater.

Dobbeltblindede placebokontrollerte studier anses som gullstandarden når det kommer til eksperimenter som ser på effekten av en spesifikk behandling. En studie som utføres slik vil kunne eliminere så godt som alle andre faktorer som kan spille inn på et forskningsresultat. Til slutt vil man sitte igjen med den isolerte effekten av en spesifikk intervensjon, og man vil kunne si noe om hvor effektiv denne er i behandling av en bestemt tilstand.

## Kontrollproblemer

Selv om en studie er kontrollert, kan det oppstå problemer. Det første problemet kommer når man ikke lenger ønsker å kun studere effekten av en pille eller en injeksjon, men mer komplekst sammensatte faktorer. Ett eksempel på dette er knyttet til ernæring; hvis man i en gruppe bytter ut kjøtt med fisk for å få mer umettet fett, så bytter man samtidig ut kjøttprotein med fiskeprotein og forskyver balansen mellom en del mikronæringsstoffer. Altså er det veldig mange variabler som skiller de to gruppene. Maten vi spiser antas å inneholde over 25,000 ulike bioaktive stoffer (5). Det å skulle endre kun én av disse i en gruppe mennesker, og samtidig holde alle andre faktorer konstante, vil være tilnærmet umulig.

En annen vanskelig faktor å kontrollere for i vitenskapelige eksperimenter er trening. Tenk deg for eksempel at du vil studere [effekten trening har på mental helse](brokenlink/smartere-av-trening/ "Gjør trening deg smartere?"). For det første er det umulig å placebokontrollere en slik studie; en person vil alltid være klar over om de trener eller ikke, og de vil ha forventninger knyttet til denne kunnskapen. I tillegg vil det være vanskelig å isolere den fysiske effekten av trening fra andre nærliggende faktorer. Mens intervensjonsgruppen trener, hva skal kontrollgruppen gjøre? Ingenting? Se på TV? Sitte på kafé? Her finnes ingen fasit, og avgjørelsen forskerne tar om hvordan studien skal designes vil påvirke studiens utfall, og også dens kvalitet. Det er rett og slett ikke mulig å utføre en dobbeltblindet placebokontrollert studie i veldig mange tilfeller, og dette vil alltid være et punkt som er verdt å kritisere. Selv om mangel på dobbeltblindet placebokontroll ikke ugyldiggjør en studie, er det viktig å merke seg nøyaktig hvordan en studie har blitt utført slik at man kan vurdere hvilke andre faktorer som kan ha spilt inn, og hvor generaliserbare resultatene vil være.

Til og med placebokontrollerte dobbeltblindede studier kan ha sine svakheter. I de tilfellene hvor man ønsker å studere effekten av en intervensjon, vil også kvaliteten på kontrollen spille inn. Det er nemlig ikke gitt at placebokontroll er det beste i alle tilfeller. Hvis du for eksempel ønsker å teste om effekten av en ny type smertestillende er det liten vits i å sammenlikne denne med placebo. Med alle de typene smertestillende som allerede finnes på markedet er det ikke så relevant å finne ut at medikamentet fungerer bedre enn ingenting – vi vil jo vite om det fungerer bedre enn de smertestillende medisinene vi har tilgjengelig for øyeblikket! Derfor vil det i dette tilfellet være bedre å sammenlikne den nye typen smertestillende med eksisterende typer (6).

Også hvis man sammenlikner en ny type medikament med et eksisterende medikament kan man gjøre feil. Man kan for eksempel rigge studier ved å dele ut den eksisterende medisinen i for høye eller for lave doser, hvilket kan resultere i dårligere prestasjon og/eller mer bivirkninger for kontrollgruppen, og det nye medikamentet vil komme bedre ut fra testene. Har man økonomisk interesse i å få et medikament ut på markedet kan dette være en ganske «lur» måte å ordne det på. En slik skjevhet i dosering er også noe som kan være vanskelig å spotte for et utrent øye. Derfor er det viktig å ha relevant bakgrunnskunnskap når man evaluerer vitenskapelige studier.

## Har du kontroll nå?

Kontroll er alfa og omega i vitenskapelige studier. Uten kontroll har man ikke noe eksperiment. Allikevel skal man ikke rope hurra for hver eneste kontrollerte studie man kommer over. Svakheter kan fortsatt være til stede, og i visse tilfeller kan de være ekstremt vanskelig å få øye på med mindre man sitter på ekspertkunnskaper. Derfor er det viktig å huske å alltid lese med et kritisk øye. Full kontroll er ikke alltid mulig å oppnå, og dette må man ha i bakhodet når man tolker vitenskapelige artikler.

Referanser:

2.  Huskisson, E. C. (1974). Simple analgesics for arthritis. *British Medical Journal*, 26, 196-200.
4.  Lucchelli, P. E., Cattaneo, A. D., & Zattoni, J. (1978). Effect of capsule colour and order of administration of hypnotic treatments. *European Journal of Clinical Pharmacology*, 13, 153-155.
6.  Rajagopal, S. (2006). The placebo effect. *The Psychiatrist*, 30, 185-188.
8.  Kaptchuk, T. J., Friedlander, E., Kelley, J. M. et al. (2010). Placebos without deception: a randomized controlled trial in irritable bowel syndrome. *PLoS One*, 5, e15591.
10. Nicastro, H. & Milner, J. A. (2012). Cancer. In *Present Knowledge in Nutrition 10^th^ ed.,* J. K. W. Erdman, I. Macdonald and S. H. Zeisel (eds.). New York: Wiley-Blackwell.
12. Goldacre, B. (2008). *Bad Science*. London: Fourth Estate
