---
title: "Kildekritikk – hva er en god kilde?"
date: 2013.08.01
---

[Tilbake til kildekritikk, vitenskap og tankefeil](../../kildekritikk.qmd)

Du ønsker å tilegne deg kunnskaper om et gitt tema, men hvor begynner du? Du står foran en skog av informasjon, men aner ikke hvilke trær som er enklest eller mest fornuftig å klatre opp i. I dette innlegget håper jeg å kunne gi deg en pekepinn på hvordan du kan gå frem for å finne informasjon og ikke minst noen tips til hvordan du kan vurdere den informasjonen du leser.

## Vi ønsker å forstå

Det å være nysgjerrig og ønske å forstå ting er menneskelig. Vi søker stadig etter forklaringer på det vi opplever, og ofte ender vi opp med uheldige konklusjoner. Dette kan skyldes at vi ikke er i stand til å se eller tolke hele bildet, og kombinert med et sterkt ønske om å forstå så er det fort gjort å ta snarveier.  Vi er spesielt farget av våre egne overbevisninger, og ofte er [ønsket om å bekrefte disse](tankefeil1.qmd) den største drivkraften til å undersøke nærmere. I denne sammenhengen kan det være fristende å være noe selektiv i valget av kilder. Kanskje er vi ikke så interessert i å lese på informasjon som ikke samsvarer med det vi trodde fra før, og foretrekker å lese ting som bekrefter våre overbevisninger, uavhengig av kvaliteten på kildene.

Vitenskapen er et verktøy vi bruker for å finne forklaringer på det vi observerer på en objektiv måte, og for å få et innblikk i hvordan ting henger sammen er vi nødt til å se på hva forskningen som helhet har kommet frem til. Det å skaffe seg oversikt over all forskningen som er gjort er en enorm oppgave, spesielt om det er snakk om et tema som ligger utenfor ditt kompetansefelt. Her kan internett være et nyttig verktøy, og til tross for hva mange vil hevde så er [Wikipedia](http://en.wikipedia.org/wiki/Main_Page), spesielt den engelske utgaven, ofte et veldig fint sted å starte om man vil tilegne seg kunnskaper om et gitt tema. Men selv om wikipedia i mange tilfeller kan være tilstrekkelig for mannen i gaten, så er det noen som ønsker å sette seg bedre inn i ting. Dette bringer oss inn på det første jeg ønsker å ta opp, nemlig lærebøker.

## Lærebøker

Lærebøker vil gi deg en oversikt over et tema, gjerne helt fra det grunnleggende. Fordelen med disse er at du slipper tolkningsarbeidet som ligger i å lese primærkildene, altså studiene som ligger til grunn. Disse bøkene er som oftest skrevet av anerkjente autoriteter innen de respektive feltene, og disse har et helt annet utgangspunkt for å gjøre fornuftige tolkninger av litteraturen enn det du har som ufaglært.

En lærebok vil i de fleste tilfeller gi deg et mer enn godt nok overblikk, men det er også noen ulemper med disse bøkene. Den første ulempen er at lærebøker raskt kan bli utdatert. Forskningen er stadig i utvikling, og hele tiden dukker det opp ny informasjon. Dette betyr ikke at bøkene er dårlige kilder til informasjon, for det er de absolutt ikke, men det kan være greit å ta hensyn til når boken du holder i hånden sist var oppdatert. Det vil også være forskjell fra fagfelt til fagfelt hvor raskt utviklingen går, slik at en ti år gammel bok kan være helt topp i ett fag mens en like gammel bok er for en antikvitet å regne innenfor et annet fagfelt. En siste ulempe med lærebøker er at de ofte kan være veldig tungleste, ettersom de benytter seg av fagspråk som ikke alltid faller like lett for forståelsen. Her vil du imidlertid kunne finne forklaringer på ord og uttrykk ved å gjøre enkle søk på internett, for eksempel ved hjelp av wikipedia.

Nasjonale rapporter og anbefalinger bør også nevnes i denne sammenhengen. Disse er utarbeidet av fagpersoner som jobber i direktoratene, og bygger på internasjonal konsensus. Arbeidet med å utarbeide disse rapportene er svært omfattende, og de kan regnes som vitenskapelig svært solide.

## Studier

Forskningen har aldri vært mer tilgjengelig enn den er i dag, og ved å søke på [Pubmed](http://www.pubmed.org) kan alle finne studier relatert til det man ønsker å lese om. Uten å betale for det vil man som oftest bare ha tilgang til sammendragene (abstract). Dette er ikke tilstrekkelig til å tolke en studie kritisk. I dag publiseres imidlertid også mye forskning i åpne tidsskrift (open access) som f.eks. [BMJ](http://www.bmj.com/), [The Lancet](http://www.thelancet.com/), [PLOSone](http://www.plosone.org/), [Nutrition and Metabolism](http://www.nutritionandmetabolism.com/) og [The New England Journal of Medicine](http://www.nejm.org/), slik at allmennheten også får tilgang på fulltekstene. Er du student eller akademisk ansatt har du gjerne tilgang til mange tidsskrift gjennom studiested/arbeidsplass.

Når grunnkunnskapen er på plass kan det være både interessant og viktig å holde seg oppdatert ved å lese studier. Men det å lese studier er ikke for alle, og det å tilegne seg kunnskaper om [studiedesign, metode og statistikk](signifikans.qmd "Signifikans og alt det der") kan være fryktelig nyttig, selvfølgelig i tillegg til grunnkunnskaper om det aktuelle fagområdet. Som jeg skrev i artikkelen om [å tolke studier i kontekst](tolke-studier-kontekst.qmd "Å tolke en studie i kontekst") så er denne grunnleggende kunnskapen ofte nødvendig for å forstå det du leser, så lærebøker er alltid et fint sted å begynne.

De mest relevante studiene er metaanalyser og reviewartikler. Metaanalyser oppsummerer resultater fra mange andre studier på samme område, og vil derfor kunne si noe om totalbildet av forskningen. Her vil forfatterne også ta seg av prosessen med å vurdere metodene i de enkelte studiene og dermed la studier av høy kvalitet veie tyngre enn de svakere studiene i den totale analysen. Blant reviewartikler har vi to typer. Systematiske review følger en gitt oppskrift for innsamling og vurdering/tolkning av studier, og er derfor ansett som solide. [Cochrane collaboration](http://www.cochrane.org/) er en gruppe forskere som er ansett for å produsere systematiske review av god kvalitet, og er derfor en veldig god kilde å støtte seg på. Den andre typen reviewartikkel heter narrativ review, og disse kan du se på som en forskers personlige tolkning av forskningen på et område. Om det er mulig så vil det være fornuftig å lese gjennom et systematisk review før du leser et narrativ review, ettersom førstnevnte i mye mindre grad vil være farget av forfatterens egne meninger.

Enkeltstudier kan også være veldig interessant, men i den store sammenhengen bør disse vektlegges mindre enn metaanalysene og reviewene. En enkeltstudie vil sjelden være sterk nok til å konkludere alene, og må derfor tolkes i kontekst av hva annen forskning har kommet frem til. En fordel med å lese originalartiklene er imidlertid at du får muligheten til selv å vurdere hva som er gjort og se resultatene direkte. Da kan du for eksempel selv se hvordan studien er [kontrollert](full-kontroll.qmd "Full kontroll?"), om resultatene har noen [uteliggere](uteliggere.qmd "Soyaprotein, østrogen og uteliggere – Hvorfor du skal være obs på feilkilder") eller om det foreligger [andre feilkilder](helsebevissthet.qmd "Helsebevisste individer – en forstyrrende faktor i forskningen?"). Dette får du ikke gjort ved å lese i en lærebok, men samtidig så krever dette som sagt en viss bakgrunnskunnskap.

Hvordan studier er finansiert kan også være av betydning, men dette poenget trekkes ofte utover alle proporsjoner. Det er riktig at industrisponsede studier er mer tilbøyelig til å komme med positivt resultat enn studier med uavhengig finansiering. Når finansieringskilden har interesser i å fremme et gitt resultat så kan dette påvirke hvordan forfatterne ordlegger seg i sin konklusjon, og i noen tilfeller har dette også en innvirkning på valg av metode i selve studien. Skrivebordsskuffeffekten beskriver problematikken med at sannsynligheten for at negative studier publiseres er liten (de blir liggende i skrivebordsskuffen). Dersom bare de positive resultatene publiseres så gir dette en svært skjev fremstilling av den totale forskningen. Problematikken rundt finansiering er viktig å være klar over når man leser en studie, spesielt når det gjelder å tolke forfatternes konklusjon. Industrisponsede studier er jevnt over av høyere metodisk kvalitet enn uavhengig finansierte studier, noe som også er viktig å ta med seg.

## Bøker, blogger, youtube og media

Populærvitenskapelige bøker og fagblogger kan være fine kilder til kunnskap, men her er det viktig å holde tungen rett i munnen. Disse mangler nemlig [kvalitetssikringen](publikasjonsprosessen.qmd "Publikasjonsprosessen") du finner i fagfellevurderte studier og fagbøker. Her må du derfor være ekstra kildekritisk, og det første som kan være greit å legge merke til er hvem som har skrevet det du leser. Seriøse aktører vil alltid være åpen om hvilken formell kompetanse de sitter på (er denne relevant for temaet det skrives om?). Ofte vil det være enkelt å hente inn videre opplysninger ved å søke på internett, og interessante opplysninger kan være hva annet denne personen driver med. Er dette en person som for eksempel selger et produkt og derfor har økonomiske motiver bak det som skrives? Hva personen jobber med til daglig kan også være relevant, og en akademisk ansatt vil være å anse for en bedre kilde enn en privat aktør, ettersom en som er ansatt ved en vitenskapelig institusjon har et visst press på seg til å ha dekning for det som skrives. Ikke minst kan du også være trygg på at en person med akademisk bakgrunn har brukt mye tid på å sette seg inn i det grunnleggende i sitt fagfelt.

I alle tilfeller er det viktig å huske på at du ved å lese bøker og blogger får informasjon som er tolket gjennom øynene til en annen person, en såkalt sekundærkilde. Denne personen har som oss alle sine biaser, og det er derfor viktig å være ekstra kritisk. Det er ikke alltid den som skriker høyest har mest rett. [Dunning-Kruger-effekten](dunning-kruger.qmd "Inkompetent uten å vite det – Dunning-Kruger-effekten") er en bias som forklarer hvorfor personer uten kompetanse har problemer med å innse dette selv, og dermed kan fremstå svært selvsikker i sine uttalelser. I tillegg er det mange som ikke [kjenner sine egne begrensninger](radgiver-begrensninger.qmd "Rådgiver – kjenn dine begrensninger!") og velger å gi råd utover sitt eget kompetansefelt. Å være klar over disse tingene kan hjelpe deg til å unngå å stole for mye på folk du ikke bør stole for mye på, og en kjapp bakgrunnssjekk vil alltid være nyttig.

En annen ting som kan være verdt å ofre en tanke er kildebruk, og dette kan være vanskelig å vurdere dersom man ikke er trent i nettopp dette. Hvilken type referanser som oppgis er av stor betydning. Dersom det refereres til fagfellevurderte studier eller lærebøker så er det et godt tegn, og referanser til metaanalyser og systematiske reviewartikler står normalt sterkere enn referanser til enkeltstudier. Om forfatteren baserer seg på enkeltstudier må du være obs på hvorvidt du presenteres for hele bildet eller om kildebruken er selektiv for å underbygge forfatterens syn. Sistnevnte er kjent som cherrypicking, der man velger de kildene man liker og overser de som sier noe annet. Gjennom å sjekke ut hvem forfatteren er kan du ofte danne deg en oppfatning av hva som er sannsynlig her. Dersom det er referert til masse tilfeldige nettsider, filmer på youtube eller lignende er dette normalt et dårlig tegn. Dette er sjeldent gode kilder, så i dette tilfellet er det lurt å skru det kritiske blikket opp et par hakk.

Lange referanselister kan se veldig imponerende og overbevisende ut, men dette er samtidig noe som for min del kan få en del alarmer til å ringe. Med tanke på hvor lang tid man bruker på å lese gjennom studier skikkelig og tolke dem grundig så vil jeg når jeg ser en lang referanseliste alltid holde muligheten åpen for at forfatteren: 1) ikke har lest disse studiene skikkelig selv eller 2) har kopiert referanselisten fra noen andre. I begge tilfeller faller troverdigheten ettersom du ikke har noen garanti for at studiene faktisk underbygger påstandene de er ment å underbygge. Selvfølgelig er det også tilfeller der forfatteren faktisk har gjort et solid arbeid og derfor har mange kilder, og dette gjelder kanskje spesielt dersom forfatteren er akademiker og gjerne har et stort bibliotek med referanser han/hun har lest opp gjennom. Hvordan referansene er oppgitt i teksten kan gi et bilde av dette. Dersom forfatteren går litt inn i referansene sine og beskriver disse er det mer sannsynlig at han/hun også har brukt tid på å tolke disse på forhånd. Dette er selvfølgelig ingen automatikk i at dette er tilfelle.

Det er veldig populært å vise til videoer på [Youtube](http://www.youtube.com) når man diskuterer, og som med alt annet så finner du også svært varierende kvalitet her. Det skal sies at du kan finne veldig mye god informasjon på Youtube, deriblant opptak fra foredrag (kan spesielt anbefale [TED-talks](http://www.ted.com)), debatter og [konferanser](../lhl-konferanse-2013.qmd). Mange godt skolerte mennesker bruker Youtube for å nå ut til flest mulig med budskapet sitt, for eksempel professor [Andy Field](http://www.youtube.com/user/ProfAndyField/videos) som foreleser i statistikk og har lagt ut hele forelesningsrekken sin. Leter du etter oppskriften på hvordan noe gjøres, kan du med stor sannsynlighet finne noe fornuftig med et søk på Youtube. Dette var eksempler på hvordan Youtube kan være en god kilde til kunnskap, men vær klar over at veldig mye av det som ligger ute ikke kan anses som en spesielt troverdig kilde. Husk at hvem som helst kan legge ut videoer, og med god retorikk så kan det meste høres veldig troverdig ut og det er lett å bli overbevist. Du har ofte ingen garanti for at den som har lagt opp videoen har god kompetanse på det aktuelle temaet, og i videoer kan mangelen på gode kilder være vanskelig å avdekke. Husk at de uten kompetanse ofte kan høres veldig selvsikker og overbevisende ut. Det er derfor en god forhåndsregel å alltid være spesielt kritisk når folk underbygger argumentene sine med videoer.

Ting du leser i avisen eller i ukeblader kan du alltid ta med en enorm klype salt. Husk at disse først og fremst skriver for å selge aviser, og derfor har interesser i å overdramatisere og polarisere. Denne problematikken har Andrea skrevet utfyllende om tidligere, der hun oppfordrer deg til [ikke å tro alt du leser](ikke-tro-alt-du-leser.qmd "Ikke tro alt du leser!"). Dette gjelder selvfølgelig i like stor grad internettutgavene av disse mediene.

## Så, hva er fornuftig?

Vi lever i et informasjonssamfunn og kunnskapen er mer tilgjengelig enn noen gang tidligere. Dette øker mulighetene til å gjøre informerte valg, men det gjelder å være kritisk til det du leser. Kvaliteten på informasjonen kan være svært varierende, og ved å ha dette i bakhodet kan du gjøre gode prioriteringer når det gjelder å velge hva du vil forholde deg til.

Når det gjelder vår egen helse er vi kanskje spesielt opptatt av å kunne ta informerte valg. Da er det viktig å reflektere litt over den informasjonen vi eksponeres for. Du er selv ansvarlig for hvilke kunnskapskilder du ønsker å benytte deg av, og det eneste jeg kan råde deg til er å slå på den kritiske sansen og spørre deg selv hvor troverdig det du sitter og leser er. Ikke la deg lure av glansbilder og god retorikk, tenk litt lenger!
