---
title: "Konfunderende faktorer"
author: "Thomas Olsen"
date: 2014.04.28
---

[Tilbake til kildekritikk, vitenskap og tankefeil](../../kildekritikk.qmd "Kildekritikk, vitenskap og tankefeil")

I [forrige artikkel](ernaeringsepidemiologi.qmd "Svakheter i ernæringsepidemiologi") vi publiserte gikk Vegard igjennom vanlige faktorer som kan skape problemer innenfor ernæringsepidemiologisk forskning, og hvordan det er praktisk nærmest umulig å kontrollere og justere for alle bakenforliggende faktorer som kan påvirke resultater og utfall av studien. Et enkelt eksempel er innsamling av kostdata som blant annet kan avhenge av deltakers hukommelse som naturlig nok påvirker hva forskerne får registrert og ikke.  I denne artikkelen ser jeg nærmere på konfunderende faktorer, som i en studie kan defineres som faktorer som påvirker resultatet av studien men som ikke nødvendigvis måles.

## Viktige å være klar over

I ernæringsforskning hvor man studerer effekten av matvare A på sykdom B kan en variabel kan ansés som en konfunderene faktor dersom den 1) er en kjent risikofaktor for sykdom B eller den 2) er assosiert med matvare A men er ikke et resultat av inntaket av matvaren. For å konkretisere eksempelet kan man tenke seg en studie der man ser på effekten av frukt på lungekreft. Her er røyking en potensiell konfunderende faktor fordi den 1) er en kjent risikofaktor for lungekreft. Med andre ord, finner man er assosiasjon mellom fruktinntak og risiko for lungekreft, kan det være at man har oversett en konfunderende faktor som at den ene gruppen røykte mer enn den andre. Man må derfor alltid være klar over at resultatet av en studie kan forårsakes av en underliggende faktor som ikke er tatt med i beregningen.

## Hvordan løse problemet?

Så, når man vet at det kan være både kjente og ukjente faktorer i en studie som kan påvirke utfallet, hvordan løser man dette problemet? Først og fremst vil dette komme an på studiedesignet. Dersom man skal studere det ovenfornevnte scenarioet (frukt og lungekreft), er den enkleste utveien kanskje å ekskludere røykere/passiv-røykere fra studien. Man kan i tillegg velge et studiedesign som tar utgangspunkt i flere grupper hvor man sammenligner en gruppe mennesker som spiste mye frukt mens en annen spiste lite eller ingenting. Da kan man matche disse gruppene etter eksempelvis alder, som også er en risikofaktor for sykdom, for å eliminere den eventuelle effekten av alder på forskjellene man observerer mellom gruppene. Deretter sammenligner man forekomsten av lungekreft hos dem som spiste mye frukt, og hos dem som spiste lite eller ingenting. Det beste alternativet er selvfølgelig randomiserte kliniske studier, der man deler inn gruppene tilfeldig slik at disse konfunderende faktorene fordeles mer eller mindre likt i gruppene. Et alternativ er det som kalles propensity-score matching, hvor man konstruerer en tilnærming til en randomisert klinisk studie fra observasjonsdata, ved å matche forsøkspersonene basert på baseline-karakteristika.

Alternativt kan man løse problemet når man gjør de statistiske analysene ved å enten stratifisere eller justere. Stratifisering er i praksis et veldig enkelt prinsipp. Med utgangspunkt i eksempelet over kan man ikke bare dele inn i de som spiste/ikke spiste frukt, men også grad av fruktinntak. Eksempelvis: Gruppe 1) 0-1 frukt om dagen, gruppe 2) 2-4 frukt om dagen og gruppe 3) 5+ frukt om dagen. Her kan man da studere i hvilken gruppe sammenhengen er sterkest mellom fruktinntak og lungekreft. Dersom man tar utgangspunkt i at fruktinntak er sett i sammenheng med lavere risiko for lungekreft, vil resultatene idéelt sett gjenspeile dette, og skal man kunne si noe om kausalitet bør det også være en form for dose-respons slik at jo mer eksponering jo mer ufall.

Når det gjelder justering er tanken her at man enkelt sagt "justerer bort" effekten av røyking på utfallet (lungkreft). Epidemiolog George Davey Smith [melder derimot](https://www.youtube.com/watch?v=3v1-kNLfhvg#t=315) i et foredrag på [LHLs kostholdskonferanse 2013](../lhl-konferanse-2013.qmd "Kosthold og hjertesykdom – hvor står vi i 2013?") at statistisk justering ikke fungerer så godt som man skulle ønske når man prøver å kontrollere for effektene av konfunderende faktorer. I ernæringsepidemilogiske studier hvor man utforsker assosiasjoner er det gjerne flere titalls konfunderende faktorer, og Smith mener at jo flere konfunderende faktorer det er, jo dårligere effekt har statistisk justering på utfallet. Smith er i samme foredrag inne på prinsippet om Mendelsk randomisering, der deltakere i en studie grupperes etter varianter av bestemte gener og deres varierende effekt på for eksempel metabolismen av spesifikke antioksidanter i frukten, og ser deretter på forekomsten av lungekreft.

## Oppsummering

Konfunderende faktorer i epidemiologisk forskning er altså faktorer som er assosiert med sykdommen eller variabelen man studerer, og som dermed kan påvirke utfallet av studien. Populært sett kan man justere for disse faktorene via ekskludering, stratifisering og justering, og i tiden fremover forhåpentligvis ved hjelp av Mendelisk randomisering. Til sist vil jeg også nevne at konfunderende faktorer i seg selv ikke bør ansés som feil, men et faktisk fenomen som må forstås i sammenheng med sykdomsbildet fordi den er med på å beskrive det observerte forholdets natur. Verden består nemlig av ekstremt mange variabler som virker på en gang, og det må vi forholde oss til enten vi ønsker det eller ikke. Feil er det derimot dersom man unnlater å ta hensyn til disse faktorene fordi det kan gi skjevhet i resultater og konklusjonene som trekkes.

Takk til Vegard for diskusjon og innspill.
