---
title: "Publikasjonsprosessen"
author: "Andrea Rørvik Marti"
date: 2013.07.08
---

[Tilbake til kildekritikk, vitenskap og tankefeil](../../kildekritikk.qmd)

Når man tenker på hva forskning er ser man gjerne for seg laboratoriearbeid. Men sannheten er at vitenskapen er en prosess hvor selve laboratoriearbeidet (datainnsamlingen) spiller en av mange viktige roller. Vitenskap består av hypoteseformulering, dataanalyse, logiske inferenser og konklusjoner. Minst like viktig innebærer vitenskap det å formidle funnene til andre mennesker, hovedsakelig andre fagfolk og forskere som kan dra nytte av denne nye kunnskapen. For å kunne kommunisere sine funn med omverdenen må forskeren skrive en fagartikkel og få denne publisert i et vitenskapelig tidsskrift. Veien fra manuskript til publisert artikkel kan være lang og kronglete, og er ikke uten baksider. I denne artikkelen vil jeg gi en oversikt over hvordan publikasjonsprosessen av vitenskapelige artikler foregår. Jeg vil også gå inn på de positive og negative sidene ved dette systemet, samt diskutere noen nylige endringer en del tidsskrifter har tatt i bruk, som kanskje kan forbedre prosessen ytterligere.

## Fra idé til publikasjon

Det aller første man må gjøre når man ønsker å publisere funnene sine er å skrive et manuskript som redegjør for hva som er blitt gjort, hva som er blitt funnet, og hvilken betydning dette har. Vitenskapelige artikler kalles manuskripter så lenge de ikke er publisert; kun etter publikasjon kaller man dem for artikler. Ulike tidsskrifter har ulike krav til hvilket format de ønsker manuskripter innsendt i. Dette kan gjelde faktorer som for eksempel lengde, seksjoner, organisering av materiale og skrive- og referansestil. Altså er det ikke særlig mye rom for kreativitet og spenning i fagartikler, noe som gjør dem ekstremt kjedelige å lese, men like fullt svært konkrete og sammenfattede.

Manuskriptet sendes så avgårde til det tidsskriftet man ønsker å publisere i. Her blir manuskriptet først lest av tidsskriftets redaktør. Redaktøren avgjør om manuskriptet skal forkastes med en gang, eller om det skal sendes til det som kalles for fagfellevurdering. Siden redaktøren av et tidsskrift ikke kan være ekspert på alle mulige temaer, benytter redaktøren seg av ekspertise fra andre forskere innen spesifikke felt som har sagt seg villig til å motta og vurdere vitenskapelige manuskripter. Som regel sendes et manuskript ut til 4-5 fagfeller, hvorav 2-4 sender en vurdering tilbake (det er alltid noen unnasluntrere).

Fagfellevurdering er en svært viktig del av vitenskapen, og det å delta anses på mange måter som en plikt for forskere. Arbeidet er ikke lønnet, og kan være tidkrevende, men er allikevel svært viktig. Når man mottar et upublisert manuskript skal dette leses igjennom og vurderes nøye og i dybden. Denne jobben bør ikke undervurderes; du sitter med informasjon som skal ut til det vitenskapelige samfunnet, og skal vurdere hvorvidt arbeidet er bra nok eller ikke. Som regel vurderes manuskriptene anonymt slik at de som mottar dem vet hvem forfatteren er, mens forfatteren aldri får vite hvem som har vurdert hans/hennes manuskript. Som regel vil et manuskript returneres til redaktøren av tidsskriftet enten med en beskjed om at manuskriptet er akseptert, akseptert med forbehold om små endringer, akseptert med forbehold om store endringer eller forkastet. Dette kan variere noe fra tidsskrift til tidsskrift.

Flere runder kan gå mellom redaktør, forfatter og fagfeller før en artikkel anses som klar til publisering. Hvis forfatteren må gjøre store endringer i manuskriptet, for eksempel ved å samle inn mer data eller kjøre flere eksperimenter, kan det gå flere år fra første innsending til endelig publikasjon. Hvor lang tid dette tar kan variere mye, men om man må vente et år eller lenger så er man i hvert fall ikke alene om det. Hvis et manuskript er i en klasse for seg og beskriver banebrytende ny forskning kan publikasjonstiden være kortet ned til dager.

## Fungerer fagfellevurdering?

Et åpenbart problem med fagfellevurdering, og publikasjonsprosessen generelt, er at den er subjektiv. Selv om manuskripter sendes ut til mennesker som anses som eksperter innen et gitt felt, betyr ikke dette at de nødvendigvis er i stand til å vurdere manuskriptet på en god og objektiv måte. Det finnes mange grunner til at de som blir valgt ut til å vurdere et manuskript kan begå feil, kanskje også uten at de selv er klar over det.

En fagfelle kan velge å avstå fra å vurdere en artikkel hvis de har en nær tilknytning til forfatteren av manuskriptet. Men innen svært små fagfelt vil det være tilnærmet umulig å finne fagfeller som sitter på tilstrekkelig ekspertkunnskap uten å ha nær kjennskap til forfatteren. Da må man enten velge en fagfelle som har kunnskap innen et nærliggende felt, eller en fagfelle med nær relasjon til forfatter. Begge scenarioer kan by på problemer. Om man kun har grunnleggende kunnskap innen et spesifikt felt vil man kanskje slite med å forstå bakgrunnen og viktigheten av et manuskript; kanskje har man utdatert eller mangelfull kunnskap som gjør at man stiller spørsmål til aspekter som i utgangspunktet er uproblematiske. Har man derimot ekspertkunnskap, men også en nær tilknytning til manuskriptforfatter kan dette svekke ens egen dømmekraft. Kanskje vil du være litt snillere med et manuskript som en nær kollega har skrevet, og kanskje vil du være negativ til et manuskript skrevet av en fagfelle som du ikke deler synspunkt med. Fagfellevurdering er og blir problematisk på grunn av denne uunngåelige subjektiviteten. Selv om mange forbehold tas for å unngå det, kommer man ikke bort ifra at fagfeller er mennesker, og de vil aldri kunne være helt og holdent objektive.

## Fungerer publikasjonsprosessen?

Fagfellevurdering er en viktig del av den vitenskapelige publikasjonsprosessen, men denne prosessen er som sagt subjektivt. Det er likevel viktig å presisere at selv om fagfellevurdering kan være problematisk, er mangel på fagfellevurdering langt mer kritikkverdig. Det finnes tidsskrifter som ikke praktiserer fagfellevurdering, og dette vil jeg nesten si er grunn til å totalt ignorere innholdet i artikler publisert i slike tidsskrifter. Når et manuskript har blitt publisert uten å ha gått igjennom noen som helst form for kvalifisert kvalitetskontroll er det grunn til å reagere. Ethvert tidsskrift med respekt for seg selv praktiserer fagfellevurdering. Til tross for de potensielle problemene er det tross alt det beste alternativet vi har for å kunne kvalitetskontrollere vitenskapelige artikler før de blir publisert. Det går også prestisje i å bidra til denne prosessen i store tidsskrift, noe som gjør at de fremste forskerne innen det enkelte feltet ofte være blant de som blir plukket ut.

Man skal derimot være forsiktig med å stole blindt på alt som publiseres i anerkjente tidsskrifter, for også disse kan inneholde feil. For eksempel ble en [oppsiktsvekkende artikkel](http://www.nature.com/news/fallout-from-hailed-cloning-paper-1.13078) nylig publisert i det prestisjetunge tidsskriftet Cell, som rapporterte om et nytt gjennombrudd innen forskning på kloning. Denne studien ble ansett som så banebrytende og viktig at fagfellevurderingsprosessen ble utført så hurtig så mulig, og artikkelen lå tilgjengelig på internett bare dager etter første innsendelse. Det var ikke før senere at en kommentar til artikkelen påpekte at tre av bildene i artikkelen var helt like, men med ulike anmerkninger. Dette viste seg i etterkant å ha vært en glipp som følge av at vurderingen ikke hadde blitt gjennomført nøye nok før publikasjon (veldig flaut for Cell). Feil og mangler kan forekomme i alle tidsskrifter, så man bør alltid lese med et kritisk øye.

## Publikasjonsprosessens fremtid

Publikasjonsprosessen er langt ifra perfekt, og nye utbedringer foreslås og gjennomføres med jevne mellomrom. Det er opp til hvert enkelt tidsskrift å vurdere hvordan deres egen publikasjonsprosess skal se ut, og noen ligger lenger frem enn andre. For eksempel har flere tidsskrifter begynt å publisere en oversikt over prosessen et manuskript har gått igjennom før den har blitt publisert; her kan man se hvor mange runder manuskriptet har gått mellom forfatter, fagfelle og redaktør, og også hvor store endringer som er blitt anbefalt å gjøre. Dette kan være nyttig å vite om man bekymrer seg for at fagfellevurderingen har vært noe slurvete. Flere tidsskrifter har også begynt å tillate kommentarfelt under artikler publisert på nettet, noe som åpner for at hvem som helst kan bidra med tilbakemeldinger og synspunkter. Kommentarene er som regel moderert før publikasjon, og har en viss grad av formalitet, men er likevel et ledd som gjør kommunikasjon mellom forfatter og leser mer direkte, og som kan tillate mer effektiv kvalitetssikring også etter publikasjon.

Poenget med publikasjonsprosessen er å kunne vurdere og kvalitetssikre vitenskapelige manuskripter på en objektiv måte. Selv om prosessen aldri kan bli helt objektiv, og negative aspekter finnes, har vi i dag ikke noe godt alternativ. Dette er noe som skiller den vitenskapelige litteraturen fra alt det andre du leser på internett, i aviser eller hører fra naboen, og som gjør dette til en [langt bedre kilde til informasjon enn de nevnte](ikke-tro-alt-du-leser.qmd).
