---
title: "Rådgiver - kjenn dine begrensninger!"
date: 2013.04.11
---

Som personlig trener, ernæringsfysiolog eller på andre måter involvert i arbeid med atferdsendring, ønsker du selvfølgelig å hjelpe folk til en bedre livsstil. Det burde hvertfall være den primære drivkraften bak å jobbe i en slik bransje. Det å se at rådene du gir blir fulgt og gir resultater gir motivasjon til å fortsette, og fornøyde kunder er god reklame! Men samtidig burde vi alle være klar over egne begrensninger, og vite når vi skal oppsøke andre med annen kompetanse for klientens beste.

Helsebransjen er tverrfaglig, og mange bruker flere år på å utdanne seg innen de ulike feltene. Selv om det er mye overlapp, og man ofte har overfladiske kunnskaper på feltene som ikke er ens eget, så er det ingen som sitter med solid kompetanse på alle felt. Dette handler like mye om egeninteresse som faglig bakgrunn.

## Hvor langt skal vi strekke oss?

Som ernæringsfysiolog med stor interesse for trening så hjelper jeg gjerne til med enkle [treningstips](../bedre-helse-2013-trening.qmd). Å f.eks. fortelle om fordelene med styrketrening kontra det å bare trene utholdenhet, eller å hjelpe til med å sette opp enkle treningsprogram er ting jeg føler meg komfortabel med. Kommer det derimot en person med muskulære ubalanser eller annen skadeproblematikk, må jeg melde pass og sende vedkommende videre til en med bedre kompetanse på feltet, eksempelvis en fysioterapeut eller personlig trener. Det samme gjelder selvfølgelig om jeg snakker med noen med helt spesifikke idrettslige mål. Der kommer min kompetanse til kort, og det er i personens beste interesse at noen med bedre kompetanse involveres.

Innen kostveiledning gjelder mye av det samme. Med litt egeninteresse er det lett å sette seg inn i hvordan et generelt sunt kosthold ser ut. Hva som skal til for å gå opp eller ned i vekt er heller ikke en statshemmelighet. Forebyggende [kostveiledning](../bedre-helse-2013-kosthold.qmd) er noe de fleste kan si noe om, og offentlige retningslinjer legger gode rammer for en god livsstil.

Skillet går i mine øyne ved frisk/syk. En frisk person tåler det aller meste, og det er veldig begrenset hvilke skade man kan gjøre. Spise en eller ti ganger om dagen? En frisk person vil kunne tilpasse seg dette og tåle det utmerket. Lavkarbo eller lavfett? Samme historien gjelder her. Snakker vi derimot om en person som ikke er frisk, så kan hele bildet være snudd på hodet, da sykdom kan endre mye med tanke på behov/toleranse for næringsstoffer, måltidsfrekvens osv.

Plutselig kan ting som en frisk ville tålt helt fint gjøre mer skade enn godt, og uten kunnskaper om den aktuelle sykdomstilstanden befinner man seg i et minefelt om man skulle bestemme seg for å likevel gi kostråd. På samme måte som at jeg vil risikere å fremprovosere eller forverre en skade ved å gi treningstips til en som fra før sliter med ubalanser, kan man uten ernæringskompetanse risikere å gjøre en syk person dårligere ved å gi kostråd som ikke passer med den aktuelle tilstanden.

## Hva er poenget her?

Vi går alle ut over vår kompetanse i arbeidet med atferdsendring, og det er i mange tilfeller helt greit. Men tenk gjennom og bli bevisst på hvor din kompetanse stopper, og hvor kunden din vil være i tryggere hender ved å oppsøke annen kompetanse. Vi kan alle utrette svært mye på egenhånd, men vi kommer ikke bort fra at vi sammen står mye sterkere, og dermed kan utgjøre en enda større forskjell!

Denne saken er først og fremst rettet mot de som gir råd eller på andre måter jobber med mennesker og livsstil. Men dere som står på andre siden av saken, dere som søker råd hos fagfolk, har også noe å ta med dere herfra. Ha i bakhodet at det ikke finnes noen som kan alt, og still gjerne spørsmål om det du blir fortalt høres rart ut. Samtidig er det også greit å ikke stille for høye krav til hva denne personen skal kunne bidra med når det gjelder ting han/hun ikke egentlig har noen kompetanse på. Spør du meg om treningstips, så kan jeg nok i de fleste tilfeller tipse om nyttige ting, men skal du bli virkelig god på noe så ville jeg spurt noen andre!

[Tilbake til kildekritikk, vitenskap og tankefeil](../../kildekritikk.qmd)
