---
title: "Tankefeil del 1 -  Bekreftelse og tilgjengelighet"
author: "Andrea Rørvik Marti"
date: 2013.07.22
---

[Tilbake til kildekritikk, vitenskap og tankefeil](../../kildekritikk.qmd)

Kognitiv bias er et begrep som beskriver visse systematiske «tankefeil» som rammer oss alle. Selv om vi liker å tro at vi alltid tenker logisk og rasjonelt, så viser det seg at vi i mange situasjoner har en tendens til å gjøre nesten det motsatte. Disse tankefeilene kan gi oss en rask og enkel løsning på et innviklet problem, men de representerer også et problem. I denne artikkelen vil jeg presentere to av de mest vanlige tankefeilene vi alle rammes av, og jeg kan garantere at du vil føle deg truffet! Uten at vi tenker over det begår vi alle slike feil fra tid til annen, men ved å ha kunnskap om dem vil du kanskje være bedre rustet til å unngå bias og dermed kunne tenke klarere.

## Bekreftelsesbias (confirmation bias)

Bekreftelsesbias handler om den tendensen vi mennesker har til å oppsøke og fokusere på informasjon som støtter vår egen oppfatning. Dette vil enkelt og greit si at vi hele tiden ønsker bekreftelse på at det vi tror er korrekt. Bekreftelsesbias innebærer også det å ha mer tiltro til informasjon som stemmer overens med vår nåværende oppfatning. Dette ble demonstrert allerede i 1979, i et eksperiment på Stanford-studenter (1).

I dette eksperimentet tok man to grupper studenter; halvparten var for dødsstraff, og halvparten var imot. Deltakerne fikk så lese to studier, hvorav én studie indikerte at dødsstraff var en bra ting fordi det virket avskrekkende for potensielle kriminelle, og den andre studien hevdet det motsatte. Deltakerne skulle så evaluere hvor god kvalitet de to ulike studiene hadde. Studiene var skrevet slik at de begge skulle ha både styrker og svakheter, men være av lik kvalitet når man ser på helheten. Resultatene av eksperimentet viste at de som i utgangspunktet støttet dødsstraff vurderte at artikkelen som samsvarte med deres syn var av langt høyere kvalitet enn den som ikke støttet deres meninger. Man fant det samme mønsteret for de som var imot dødsstraff. Det man ser her er altså at to ulike grupper mennesker har lest og vurdert nøyaktig samme artikler, men kommet til totalt ulike konklusjoner.

Konsekvensene av bekreftelsesbias er potensielt svært store. Det som kan skje er at om du har gjort deg opp en mening om en sak mister du all evne til å kunne se ting fra andre perspektiv senere. Dette er en kvalitet man helst vil være foruten, da det er slik tankegang som fører til sneversyn og ignoranse. Du vil alltid trekkes mot det du er enig i. Det er mer spennende å lese en avisartikkel som fremmer samme syn som det du allerede har, men husk alltid at du blir kun servert én side av saken. Skal du gjøre deg opp en mening om for eksempel en politisk sak, forsøk å finne argumenter som både støtter *og* motsetter seg saken. På denne måten kan du ta en informert beslutning om hvilken side du ønsker å ta. Husk også at det ikke er noen skam i å endre mening etter å ha fått ytterligere bevis. Det er slik vitenskapen fungerer, og det er slik det bør være, selv om hodet vårt ikke alltid får det til. En sak har alltid to sider, og selv om det ikke alltid er så lett vil det alltid lønne seg å bli kjent med dem begge.

## Tigjengelighetsbias (Availability heuristic)

Våre tanker påvirkes av hvor lett noe kommer til minnet når vi forsøker å huske noe. Dette vil si at ting som er lette å komme på, eller vekker de mest livaktige minnene, vil antas å være mer vanlige enn ting som ikke vekker like livlige minner. Dette påvirker vår evne til å bedømme sannsynlighet. Noe som er lett å huske vil skape en illusjon av at det også skjer oftere enn ting som er vanskelige å huske. Men det kan derimot ofte være slik at ting som er vanskelige å huske slett ikke er uvanlige - de kan bare være så vanlige at du ikke legger merke til dem.

Kahneman og Tversky var de første til å beskrive tilgjengelighetsbias, allerede i 1973 (2). De gjorde et eksperiment hvor de ganske enkelt ba folk anslå hvorvidt de trodde det fantes flere ord i det Engelske språket som startet med bokstaven K, eller som hadde K som tredje bokstav. Majoriteten av deltakerne mente at det fantes flest ord som begynte med bokstaven K. Dette viser seg derimot å være helt feil, og det er i realiteten langt flere engelske ord med K som tredje bokstav. Men siden det er enklere å søke etter ord i hukommelsen når man bruker første bokstav som referanse skaper dette en illusjon av at flere ord starter med K. Du kan jo prøve selv og se hvor enkelt det er å finne ord som begynner med en viss bokstav, og hvor vanskelig det er å finne ord som har samme bokstaven som tredje bokstav. Dette faktum forteller oss derimot ingenting om hvor vanlige disse ordene er, selv om det virker logisk å anta det.

Tilgjengelighetsbias er høyst relevant fordi det handler om hvordan vi tror at virkeligheten er, og om at vi kan oppfatte virkeligheten feil. Nyhetsmediene er kanskje det mest åpenbare eksempelet; det vi ofte omtales i nyhetene er det vi antar at skjer ofte, noe som ikke nødvendigvis stemmer. Nylig kom en undersøkelse fra den Britiske versjonen av Statistisk Sentralbyrå som blandt annet viste at [de fleste Briter tror at kriminaliteten øker](http://www.ipsos-mori.com/researchpublications/researcharchive/3188/Perceptions-are-not-reality-the-top-10-we-get-wrong.aspx), mens den i realiteten synker. Det er nærliggende å tro at dette handler om tilgjengelighetsbias. Når du hører om kriminalitet på nyhetene hver eneste dag vil du automatisk tro at kriminalitet er ekstremt vanlig, og kanskje vanligere enn det faktisk er. Her ser man altså en måte som mediene direkte kan påvirke vår oppfatning av virkeligheten i fullstendig feil retning. Her er det viktig å huske at mediene skriver om det uvanlige, ikke det vanlige. En nyhetssak om at ingen kriminalitet fant sted er ingen sak i det hele tatt. Derfor gir ikke nyhetene oss noen som helst informasjon om hvor vanlig kriminalitet er, selv om det kanskje kan virke slik. Nyheter handler om anekdoter, og anekdoter handler som regel ikke om hverdagslige eller statistisk sannsynlige ting - snarere vert imot.

## Avslutning

Bekreftelsesbias og tilgjengelighetsbias er bare to av veldig mange tankefeil vi mennesker utsetter oss selv for hele tiden. Det vil nok aldri være mulig for oss å unngå dem fullstendig, men med kunnskap og bevissthet vil man kanskje være bedre rustet for å unngå dem. Jeg kommer til å presentere flere typer bias i senere artikler. Foreløpig håper jeg i hvert fall du har fått med deg at en sak alltid har to sider, og anekdoter ikke nødvendigvis gjenspeiler virkeligheten. Med bevissthet rundt disse to faktum har du nok bedre selvinnsikt enn de fleste, og kan forhåpentligvis unngå to av de aller vanligste tenkefellene vi alle går i fra tid til annen. Lykke til!

Referanser

1. Lord, C. G., Ross, L. & Lepper, M. R. (1979). Biased assimilation and attitude polarization: the effects of prior theories on subsequently considered evidence. *Journal of Personality and Social Psychology*, 37, 2098-2109.
2.  Tversky, A. & Kahneman, D. (1973). Availability: a heuristic for judging frequency and probability. *Cognitive Psychology*, 5, 207–233.
