---
title: "Sosiale bias - Fundamental attribusjonsfeil"
author: "Andrea Rørvik Marti"
date: 2013.09.02
---

[Tilbake til kildekritikk, vitenskap og tankefeil](../../kildekritikk.qmd "Kildekritikk, vitenskap og tankefeil")

Denne artikkelen vil være litt ulik de to tidligere artiklene om bias. Grunnen til det er at jeg nå vil bevege meg inn i sosialpsykologiens verden, hvor målet er å forklare og forutse sosiale handlinger hos enkeltpersoner og grupper. Dette er langt mer komplisert enn enkle tankefeil, fordi de involverer sosial kognisjon. Det handler ganske enkelt om hvordan folk oppfører seg når de samhandler med eller tenker på andre folk. Her finnes utallige variabler, og derfor er det notorisk vanskelig å finne universelle mønstre i menneskers oppførsel.Det som er spesielt med disse biasene er altså at de ikke er like generelle som de jeg tidligere har gått igjennom. De er derimot noe av det nærmeste man kommer kognitiv bias på det sosiale plan. Om vi for øyeblikket fokuserer på tilfellene heller enn unntakene kan disse fortelle oss mye om hvordan og hvorfor vi mennesker tenker og gjør som vi gjør i samhandling med andre mennesker. Jeg skal nå i første omgang ta for meg fundamental attribusjonsfeil (FAF). Dette kan kanskje virke en smule komplisert og irrelevant ved første øyekast, men jeg kan love deg at det i realiteten er veldig enkelt, og veldig veldig vanlig. Du rammes helt sikkert av FAF hele tiden, men hvis du er bevisst på det kan du kanskje lære å gjenkjenne det i deg selv, og som følge roe ned hyklerskheten litt.

## Hva er fundamental attribusjonsfeil?

FAF er en av de best etablerte, mest universielle (men unntak finnes også her) sosiale biasene vi mennesker har (1). Attribusjon handler om hvordan vi årsaksforklarer ulike fenomener, og akkurat her snakker vi om andre menneskers handlinger. FAF begås når vi årsaksforklarer hva andre mennesker har gjort ved å overfokusere på interne kvailteter ved personen og underfokusere på situasjonen. Jeg vil først ta et eksempel fra den første demonstrasjonen av dette fenomenet, også gi et eksempel som kanskje er litt mer nærliggende.

Tenk deg at du blir bedt om å lese en artikkel som omtaler Fidel Castro i et positivt lys. Du får beskjed om at personen som har skrevet artikkelen ikke har hatt noe valg – det ble foretatt en loddtrekning blant en gruppe mennesker hvorav halvparten måtte skrive pro-Castro-artikler, og den andre halvparten måtte skrive anti-Castro-artikler. Du har altså lest en artikkel skrevet av en av dem som ble trukket ut til å skrive en pro-Castro-artikkel. Deretter får du spørsmålet – hvor sannsynlig er det at denne personen støtter Castros politikk?

Dette er scenarioet som møtte en fjerdedel av deltakerne i eksperimentet til Jones og Harris i 1967 (2). Én gruppe deltakere leste også pro-Castro-artikler, men de ble fortalt at forfatteren selv hadde valgt å skrive det. De to andre gruppene var delt inn på samme måte, bare at artiklene var anti-Castro i stedet for pro-Castro. Forskerne hadde forventet at deltakerne skulle si at det var høy sannsynlighet for at de som selv hadde valgt hva de ville skrive om var enige i det de selv hadde skrevet. Det var også det resultatene viste. Men det som derimot overrasket forskerne var at det samme skjedde til tross for at deltakerne var fullt klar over at forfatterne ikke hadde hatt noen makt over avgjørelsen om hva de skulle skrive om – allikevel ble det oppgitt høy sannsynlighet for at forfatterne var enige i det de selv hadde skrevet (ikke like høy som hos dem som hadde valgt det selv, men allikevel overraskende høy). Det var slik FAF ble oppdaget.

Det som altså hadde skjedd var at deltakerne ikke hadde klart å ta situasjonen forfatterne var i nok inn i betraktning, og heller antatt at de var enige i det de selv hadde skrevet. Personlige egenskaper ble fokusert for mye på. Det er kanskje litt vanskelig å se hvordan dette egentlig fungerer, men se for deg at du står i butikken og ser en tykk person kjøpe inn enorme mengder godterier en fredags ettermiddag. Det er lett å anta at vedkommende er lat og med lav viljestyrke. Men kanskje er vedkommende i realiteten ute og handler til et stort selskap som han/hun skal arrangere neste dag? Eller hvis du ser en person råkjøre nedover gaten er det lett å anta at vedkommende er en idiot som skulle ha blitt fratatt førerkortet på stedet. Men kanskje har han/hun en akuttsyk person i bilen som trenger umiddelbar legehjelp? Situasjonen ignoreres og permanente personlige egenskaper vektlegges.

## Hvorfor?

Hvorfor gjør vi dette? Hvorfor gir vi ikke folk «benefit of the doubt» som det kalles, og holder dem uskyldig inntil det motsatte er bevist? Grunnen handler sannsynligvis om at hjernen vår liker regler og løsninger, ikke usikkerhet. Hvis vi vet lite om situasjonen en person er i er det enklere å anta at situasjonen er knyttet til hvordan vedkommende er som person. Når det kommer til oss selv derimot, er det langt enklere å bortforklare ting som en følge av situasjonen. Hvis en annen person får dårlig karakter på en prøve må det være fordi vedkommende er dum. Får du selv dårlig karakter er det fordi du hadde en dårlig dag eller fordi læreren er streng med rettingen. FAF gjør en vanskelig og komplisert sosial verden enkel og oversiktlig. Det må allikevel nevnes at FAF er noe som påvirker mennesker i ulik grad, og man ser også klare kulturforskjeller (vi i Vesten rammes hardest). Men det er fortsatt slik at vi alle sammen rammes av FAF fra tid til annen og forhåndsdømmer en person på bakgrunn av det. Dette kan igjen gi opphav til stereotyper som igjen bidrar til fordommer og rasisme. Dette skal jeg komme tilbake til i neste artikkel.

1.  Hogg, M. A. & Vaughan, G. (2008). *Social Psychology*, 5th ed. Pearson: New Jersey.

2.  Jones, E.E. & Harris, V. A. (1967). The attribution of attitudes. *Journal of Experimental Social Psychology*, 3, 1-24.
