---
title: "Å tolke en studie i kontekst"
date: 2013.06.27
---

[Tilbake til kildekritikk, vitenskap og tankefeil](../../kildekritikk.qmd)

Forskningen er i større og større grad åpent tilgjengelig for hvem som helst. Med fremmarsjen av «open access»-tidsskrifter der man slipper å betale for tilgang til fulltekstversjoner er det også mulig å lese disse. Men, som vi har vært inne på i flere saker tidligere, så er det ikke bare-bare å lese denne typen artikler. I dette innlegget vil jeg gå litt inn på viktige aspekter ved det å tolke forskningsartikler og sette de inn i kontekst.

De fleste får med seg forskningsresultater gjennom oppslag i media som selektivt er valgt ut basert på nyhetsverdi og sensasjonalisering. Andrea har i [denne artikkelen](ikke-tro-alt-du-leser.qmd) (ekstreme verdier) kan påvirke sluttresultatet, og dette er bare en av tingene som kan være viktig å ha i bakhodet når man tolker resultatene fra en studie.

## Relevant fagkunnskap

En ting som kan være svært viktig for å gjøre gode tolkninger av en studie, er å ha relevante bakgrunnskunnskaper om det aktuelle feltet. Kjennskap til fagterminologi og ikke minst vanlig praksis kan være helt essensielt for å forstå både metoder og resultater, og den beste måten å skaffe seg slike kunnskaper på er gjennom høyere utdanning. Da vil man i tillegg til å skaffe seg relevante kunnskaper også bli kjent med viktige tidsskrifter og andre relevante institusjoner til det fagfeltet du tilhører. Man kan selvfølgelig også tilegne seg masse kunnskap gjennom egenstudier, men mange har dessverre en tendens til å ta snarveier som å hoppe over det grunnleggende. Ikke minst er det vanlig å [overvurdere egen kompetanse](dunning-kruger.qmd), noe Andrea har skrevet en fantastisk sak om.

Gjennom hele utdanningsløpet har jeg opplevd å være ganske god på å lese og forstå forskningsartikler. Samtidig har jeg kontinuerlig lært nye ting, og oppdaget at ting jeg tidligere ikke har lagt mye vekt på, gjerne fordi jeg ikke har forstått det så godt, viste seg å være svært viktig for å gjøre gode tolkninger. Her må jeg ærlig innrømme at jeg føler meg massivt truffet av Dunning-Kruger-effekten. Jeg har i stor grad overvurdert min egen kompetanse underveis, og jeg tror ikke jeg er et unntak. Grunnen til at jeg trekker frem dette er at jeg tror det er viktig å være ydmyk overfor egen kunnskap og innse at det er mye mer du ikke vet enn det du faktisk vet. Dette var grunnen til at jeg skrev en sak om hvor viktig det er å [identifisere sine egne begrensninger](radgiver-begrensninger.qmd), spesielt i situasjoner der man gir råd til andre mennesker.

Uten relevant bakgrunnskunnskap er det fort gjort å trekke uheldige konklusjoner fra en forskningsartikkel. Mye av forskningen er også bare tilgjengelig som abstrakt, altså korte sammendrag, som ikke forteller hele historien. Å bare basere seg på abstrakt er aldri en god idé, og du risikerer å gå glipp av mange viktige poenger som nyanserer artikkelen. Tilgang til fulltekstversjoner er noe man ofte må betale for, med mindre du er heldig å tilhøre en utdanningsinstitusjon som gir deg tilgang til relevante tidsskrifter. Men da er vi tilbake til dette med å tilhøre et fagmiljø.

## Viktige deler av en artikkel

Når du så sitter med en artikkel i fanget og skal til å lese, kan det med første øyekast være vanskelig å få oversikt over hva du finner i de ulike seksjonene. De fleste artiklene er bygget opp etter IMRAD-modellen, som er en forkortelse for innledning, metoder, resultater og diskusjon. Ulike tidsskrift har imidlertid ulike regler for hvordan artiklene skal bygges opp og hvor lange de kan være, og av og til vil du f.eks. finne metodedelen helt til slutt. Men hva kan du forvente å finne i de ulike delene av en artikkel?

Kort fortalt vil du i metodedelen finne ut hva forskerne har gjort. Dette bør inkludere en beskrivelse av populasjonen man har undersøkt (hvem, hvor, hvor gamle, helsestatus osv), hvordan man har rekruttert deltakerne, hvordan studien er bygget opp (generelt design), hva man har målt (og hvordan man har målt det), hvilke analyser man ha gjennomført, hva man har justert for samt inklusjons- og eksklusjonskriterier og etiske problemstillinger. I resultatdelen vil du finne en presentasjon av hvilke resultater forskerne har funnet etter å ha gjennomført studien. Her skal det ikke presenteres noen tolkninger av resultatene, ettersom dette skal være en objektiv fremstilling. I resten av dette innlegget vil jeg fokusere på viktigheten av de øvrige delene av en artikkel, nemlig introduksjonen og diskusjonen.

Introduksjonen er en svært viktig del av en forskningsartikkel. Hvor omfattende introduksjonen er kan variere en del fra tidsskrift til tidsskrift. Noen ganger vil du få en omfattende innføring i det aktuelle temaet, mens andre ganger vil bakgrunnsinformasjonen begrenses til det mest essensielle. I en innledning skal du få presentert en oversikt over det aktuelle temaet, hva som er gjort av forskning og hva som eventuelt mangler. Denne delen kan ofte være svært lærerik, og kan bidra med å fylle en del hull i bakgrunnskunnskapen du har om temaet fra tidligere. Vi vet sjelden alt om et emne, og i introduksjonen skal du også få en beskrivelse av hva vi eventuelt ikke vet. Dette bør munne ut i en del forskningsspørsmål og en forklaring på hva denne studien er tiltenkt å bidra med til det totale kunnskapsbildet.

Diskusjonsdelen er den siste seksjonen av en forskningsartikkel, og for å sette ting i perspektiv er denne veldig viktig. Her vil forskerne først oppsummere hva de har funnet og hva studien har bidratt med opp mot det som stod i introduksjonen. Her vil ofte resultatene sammenlignes og settes i sammenheng med tidligere studier og den daværende kunnskapen. Deretter vil de diskutere svakheter og styrker ved studien, noe som kan sette ting i et annet lys. Kanskje har studien en del begrensninger som gjør at resultatene må tolkes med forsiktighet. Dette kan for eksempel være at de ikke har klart å justere for alle mulige konfunderende faktorer, det kan ha oppstått problemer med utvalget av deltagere, det kan ha manglet ressurser til å gjøre det man ønsket eller det kan ha oppstått uventede ting som har påvirket resultatene. I kostholdsstudier er ofte måten man har samlet inn informasjon om hva deltakerne har spist et tema som kan diskuteres.

Avslutningsvis vil man ofte komme med en konklusjon. Dette kan være en konkret anbefaling eller nye hypoteser/faktorer som bør undersøkes videre. Har man ikke funnet noe, så er dette også et viktig funn å rapportere. Diskusjonsdelen av en artikkel er den seksjonen som kan være mest farget av forfatterens eget subjektive syn. Det er derfor viktig å huske på at de tolkningene av resultater som fremmes i en diskusjon ikke nødvendigvis er korrekte. Det kan være alternative tolkninger som ikke kommer opp i diskusjonen, enten fordi forfatteren ikke har tenkt på det, eller har begrenset med plass i artikkelen. Her kan også problematikk rundt hvem som har finansiert studien spille en stor rolle, da det ofte kan stå mye penger på spill for å produsere et visst resultat. Vi vet at industrifinansierte studier er langt mer tilbøyelige til å produsere resultater som er gunstige for produsentene, men samtidig vet vi også at disse studiene jevnt over er av høyere kvalitet enn uavhengig finaniserte studier. Diskusjoner og konklusjoner bør derfor alltid leses med et ekstra kritisk blikk.

## Konklusjon

Å lese en forskningsartikkel er både tidkrevende og vanskelig. Den lettvinte løsningen er å basere seg på konklusjonene, men husk at dette er forfatternes egne konklusjoner og representerer ikke nødvendigvis en fasit. I alle tilfeller er det viktig å sette dette inn i en relevant kontekst for å kunne sitte igjen med noe fornuftig. Forkunnskaper vil fungere som en lommelykt når man skal trekke ut essensen av forskningsresultater, evaluere, konstruktivt kritisere dem og eventuelt fremme sitt syn på en sak. Uten dem blir man famlende i mørket.
