---
title: "Hypotalamus, hypofysen og binyrene"
date: "2011.12.14"
---

Tilbake til [innføringen i hormonsystemet](../../hormonsystemet.qmd "En innføring i hormonsystemet").

Hypotalamus, hypofysen og binyrene er veldig sentrale kjertler i hormonsystemet. Hypotalamus er det overordnede senteret både for det autonome nervesystemet og for hormonsystemet, mens hypofysen med sine hormoner styrer resten av det endokrine systemet. Binyrene produserer mange viktige hormoner, blant annet adrenalin og kortisol.

## Hypotalamus

Hypotalamus er som nevnt det overordnede senteret for hormonsystemet, og er hovedstedet for regulering av kroppens indre miljø. Hypotalamus inneholder mange reseptorer som registrerer endringer i det indre miljøet, noe som stimulerer til hormonproduksjon. Hormonene fra hypotalamus kan enten gå til hypofysens forlapp eller baklapp. De hormonene som går til forlappen, kalles med et fellesnavn hypotalamushormonene, og kan enten hemme eller stimulere de ulike hormonene som produseres i hypofysen.

Andre hormoner som produseres i hypotalamus kan lagres i hypofysens baklapp, og slippes ut i blodet derfra. Det er her snakk om følgende peptidhormoner:

-   **ADH – antidiuretisk hormon**. Dette hormonet virker på nyrene, og gjør at vi skiller ut mindre vann. Utskillelsen av ADH styres av væske- og elektrolyttbalansen i kroppen, og sørger for at dette er mest mulig stabilt.

-   **Oxytocin** – stimulerer fødselsrier og melkeproduksjon.

## Hypofysen

Hypofysen *(pituitary gland)* kan deles i to deler, forlappen og baklappen. Baklappen produserer ingen hormoner, men fungerer som en lagerplass for noen av hypotalamus sine hormoner, som frisettes herfra. Forlappen består av ulike endokrine celler, og her produseres seks ulike peptidhormoner. Disse hormonene styrer hormonproduksjonen i andre kjertler, samt er sentrale i vekstreguleringen av ulike vev. De seks hormonene er:

-   **ACTH – adrenokortikotropt hormon**. Dette hormonet stimulerer produksjonen av hormoner i binyrebarken. Stimulerer også til vekst av binyrene.

-   **TSH – tyroideastimulerende hormon**. TSH stimulerer hormonproduksjonen i skjoldbruskkjertelen. TSH stimulerer også til vekst av skjoldbruskkjertelen.

-   **FSH og LH – folikkelstimulerende og luteniserende hormon**. Disse styrer produksjon av kjønnshormoner, og regulerer vekst og modning av kjønnscellene.

-   **GH – veksthormon**. Stimulerer celler til å produsere vekstfaktorer.

-   **PL – prolaktin**. Stimulerer vekst og melkeproduksjon i brystkjertlene.

Disse hormonene er presentert i en egen artikkel [her](hypofysehormonene.qmd "Hypofysehormonene").

Produksjonen av disse hormonene stimuleres av signaler fra hypotalamus. I tillegg til å virke på sine respektive målorganer, har disse hormonene en hemmende effekt på hypotalamus. Dette kalles negativ tilbakekobling, og hindrer overproduksjon av hormoner. Hormonene som produseres i de øvrige endokrine kjertlene har negativ tilbakekobling både på hypofysen og hypotalamus, slik at hele systemet er veldig nøye regulert.

## Binyrene

Binyrene *(adrenal gland)* er noen små kjertler som sitter på toppen av nyrene. Disse kjertlene er bygget opp med en marg (medulla) og en bark som ligger rundt (cortex). Barken er delt inn i tre soner: reticularis, fasciculata og glomerulosa (fra margen og utover). Hormoner produseres i alle de ulike delene av binyrene, og de viktigste av disse vil presenteres i en egen artikkel.

Her er de viktigste hormonene fra binyrene:

-   **Kortisol**. Dette er et stresshormon, som blant annet fører til økt glukosekonsentrasjon i blodet. Kortisol er et katabolt (nedbrytende) hormon. Kortisol er et livsviktig hormon med mange viktige effekter. Produksjonen av kortisol styres i stor grad av ACTH fra hypofysen.

-   **Aldosteron**. Dette hormonet er hovedregulator av nyrenes utskillelse av natrium. Produksjonen av aldosteron styres blant annet via ACTH fra hypofysens forlapp.

-   **Androgener**. Dette er hormoner med samme effekter som det mannlige kjønnshormonet testosteron, men effektene er avhengige av at de omdannes til testosteron i målorganene. De kan også omdannes til det kvinnelige kjønnshormonet østrogen.

-   **Adrenalin**. Dette er kroppens primære kjemp-eller-flykthormon. Hovedeffektene av adrenalin er at det setter kroppen i en skjerpet tilstand. Mer blod går til musklene, og tilgjengeligheten til de energigivende stoffene øker. Produksjonen av adrenalin styres av sympatiske nervefibre fra hypotalamus, og øker ved stress, fysisk aktivitet eller lavt blodsukker.
