---
title: "Blod-hjerne-barrieren"
author: "Kristian Fagerland"
date: 2013.11.14
---

# **(Uvisst hvorfor denne lå som kladd)**

**Blod-hjerne-barrieren**

\- et levende filter

Menneskehjernen er den mest avanserte strukturen verden kjenner til. Den veier ca 1.5 kg og består av drøye 100 milliarder nerveceller som kommuniserer sammen på ulike måter. Per dags dato finnes det ingen datamaskin som kan sammenliknes med dette utrolige organet som styrer alt i fra menneskets tanker til andre funksjoner som for eksempel hjerterytme, fordøyelse og motorikk.

For å utføre sine daglige funksjoner er hjernen avhengig av stimuli og næring. Stimuli får den hver gang vi har en tanke, utfører en motorisk aktivitet, eller hver gang vi blir stimulert fra miljøet rundt oss. Næring får den fra blodårene og kapillærene som fører "mat" og oksygen til hjernen fra fordøyelsessystemet og lungene.

Dersom vi strekker ut alle hjernens blodårer, utgjør disse utrolige 600 kilometer! Det som kanskje er enda mer fascinerende er at rundt blodårene ligger blod-hjerne-barrieren, et tynt lag av beskyttende celler som aktivt regulerer hvilke elementer som trenger inn og ut av hjernen. Denne barrieren er en vesentlig del av vårt immunforsvar. Den beskytter blant annet hjernen fra uønskede bakterier, virus, tungmetaller, gluten, osv. I tillegg til å fungere som et filter er barrieren også delaktig med å regulere blodtilstrømning og næring til aktive områder i hjernen. Der hvor nevrologisk aktivitet pågår, åpner barrieren seg. På denne måten får aktive nerveceller mer næring og kvitter seg raskere med avfallstoffer.

Blod-hjerne-barrieren fungerer i høyeste grad som et aktivt filter som stadig er i bevegelse. Ulike livsstilsfaktorer som for eksempel diett, stress og alderdom påvirker barrierens funksjonalitet. Når vi blir eldre svekkes barrieren. Dette medfører nevrologisk degenerasjon, og sannsynligheten for aldringssykdommer som Alzheimer og demens øker. Stress, alkohol og blodsukkerubalanser fører også til nedsatt funksjon og ytterligere degenerasjon.

Sykdommer som MS og epilepsi linkes til episodiske "brudd" i blod-hjerne-barrieren. MS er en "semi-autoimmun" sykdom som periodevis bryter ned lokale områder av blod-hjerne-barrieren. Disse bruddene gjør at hvite blodlegemer kan trenge inn i hjernen, for så å gå til angrep på myelinet. Dette kan forklare hvorfor MS pasienter stadig får tilbakefall. Nyere forskning indikerer også at liknende "hull" i barrieren kan igangsette akutte epileptiske anfall.

En vesentlig del av helsa vår bør være å ivareta blod-hjerne-barrieren. En sunn livsstil bestående av naturlig mat, stressmestring og fysisk aktivitet er grunnleggende. Det finnes også kosttilskudd som kan bidra til en bedre blod-hjerne-barriere. Alfa liponsyre (ALA), Q10, kreatin, hvitløk, omega 3 og B vitaminer ser ut til å ha en positiv effekt på barrieren. Alkohol og stress virker skadende. Spesielt nevneverdig er det at stress ser ut til å ha en særs negativ effekt på barn, tenåringer og eldre. Derfor er det essensielt at vi som foreldre til en hver tid passer på stressnivået til barna våre. Trygge omgivelser, masse kjærlighet og god planlegging fra foreldrenes side er med å redusere stressnivået til barn i vekst.

Den farmasøytiske industrien er også interessert i blod-hjerne-barrieren. De fleste medisiner krysser nemlig ikke barrieren, og har liten effekt på nevrologiske sykdommer. I den senere tid har det vært et kappløp i utviklingen av metoder som leverer medisiner på tvers av barrieren. Per dags dato eksisterer det 3 metoder, men de er fortsatt under utprøving. Den mest vellykkede er kanskje lokal innsprøyting av mannitol som i en kort periode åpner opp barrieren slik at medisiner som for eksempel cellegift kan komme inn i hjernen og bekjempe kreftsvulster. Andre metoder benytter såkalte "trojanermolekyler" som transporterer medisiner over barrieren. Den siste metoden anvender ultralyd som tvinger medisinene igjennom blod-hjerne-barrieren.

Mye er fortsatt uklart når det gjelder blod-hjerne-barrieren, og vi forstår enda ikke dens fulle funksjon. Det forskes stadig på dette området, og forhåpentligvis vil forskningen bidra til bedre viten slik at vi som jobber med helse kan hjelpe pasientene våre på best måte.

**Referanser:**

Scientific American June 2013 Volume 308, Number 6

50 ideas you really ned to know-the human brain Moheb Costandi

Why do I still have thyroid symptoms when my lab tests are normal Datis Kharrazian
