---
title: "Må du spise ren mat?"
---

Mange som driver med kostveiledning vil fokusere på at maten du spiser bør være mest mulig ren. Hva som ligger i dette begrepet vil variere litt etter hvem som bruker det, men stort sett handler det om hvor mye maten er bearbeidet. Dette har lenge vært et ledende kostholdsparadigme innen sporter som kroppsbygging og fitness, og som motsvar til dette har det vokst frem en alternativ strategi der det er matens innhold som får all oppmerksomheten. Midt mellom disse polariserte leirene står du, men hva er riktige råd for deg?

## Kosthold og kroppssammensetning

Kostholdsbaserte endringer i kroppssammensetningen styres først og fremst om hvor mye vi får i oss av energi og protein. Hvis vi nå ser bort fra helseaspektet, og bare fokuserer på det visuelle, så vil makronæringsstoffene ha en langt større innvirkning og betydning enn mikronæringsstoffene. Selvfølgelig vil også vitaminer og mineraler være essensielle, ettersom de er viktige kofaktorer i omsetningen av makronæringsstoffene, samt at de er viktig for generell funksjon som vil ha betydning for alt fra treningsprestasjon til søvnkvalitet.

Tradisjonelt sett har det vært populært å basere kostplaner på såkalt ren mat, men kriteriene for hva som er ren mat vil variere ut fra hvem du spør. Gjennomgangsmelodien er at maten skal være minst mulig prosessert. Tanken bak er at denne maten er mest næringsrik, og vil være det beste valget både for prestasjon og helse. Ulempen med en slik tilnærming er at det ofte innebærer en del begrensninger på hva du kan spise, ettersom du må styre unna mat som per definisjon ikke regnes som ren.

Begrepet ren mat har fått mye kritikk. Først og fremst kommer dette fra typiske kroppsbygger- og fitnessmiljøer, der hovedfokuset ligger på det visuelle heller enn god helse. Her er det som nevnt kostholdets innhold av næringsstoffer som har mest betydning, og ikke hvilken matvare vi finner dem i. Det hevdes at sukker er en like god kilde til karbohydrat som potet, ettersom dette uansett brytes ned til glukose inne i kroppen. Det at matvarene inneholder mindre mikronæringsstoffer betyr ikke så mye, ettersom det er totalen som betyr noe, så disse kan man få fra andre matvarer. Hovedbudskapet med denne tilnærmingen, som har fått navnet [IIFYM](http://www.myrevolution.no/s/iifym-fleksibelt-kosthold/) (If It Fits Your Macros) eller fleksibelt kosthold, er at du kan spise nøyaktig de matvarene du ønsker, men du har en viss mengde energi, protein, karbohydrater og fett å gå på. Her går begrensningene altså på matens innhold av næringsstoffer, og da først og fremst makronæringsstoffene, ikke på hvilken type mat det er snakk om. Hvorvidt du kan spise noe avhenger av om den passer inn med mengden du skal ha i deg av de ulike næringsstoffene den aktuelle dagen.

## Kostråd i praksis

Vi lever i en verden med tilnærmet fri tilgang på akkurat den maten vi måtte ha lyst på. Dette har bidratt til [overvektsbølgen](..artikler/hvorfor-er-vi-feite.qmd), og råd om hva vi bør spise er absolutt noe jeg anser som nødvendig. De generelle kostrådene fra myndighetene til hele befolkningen er godt kjent, men hvilke type råd vil være mest fornuftig for enkeltmennesket?

Det er ganske åpenbart at begge disse tilnærmingene har sine fordeler og ulemper. Der en "ren mat"-tilnærming gjerne kan bli kjedelig og restriktiv, så kan IIFYM-tilnærmingen potensielt brukes som en unnskyldning for å spise mye næringsfattig mat. Dette er selvfølgelig ekstremtilfeller, og trenger ikke å være realiteten ved noen av disse. Ren mat trenger ikke å være ensidig, det er store muligheter for variasjon.

Ren mat som utgangspunkt er bare bra, men når det også inkluderer at mat som ikke er ren blir forbudt, har det gått for langt!
