---
title: "2012 - året som gikk"
date: 2012.12.28
---

Da er 2013 like om hjørnet, og det er på tide med et tilbakeblikk på hva som har skjedd i 2012.

## Artikler og innlegg

2012 har bydd på 76 artikler og innlegg. Målet for året var å produsere artikler og innlegg med jevne mellomrom, og selv om det har vært noen tørkeperioder, så må vi si oss fornøyd med nettstedets første fulle kalenderår. Vi skal selvfølgelig jobbe hardt for å forbedre oss i året som kommer!

Her følger en liste over flere av årets beste og mest populære artikler etter kategori:

#### Helse:

-   [Minikurs i lipoproteiner](http://www.friskogfunksjonell.no/minikurs-i-lipoproteiner/ "Minikurs i lipoproteiner")

-   [Hjerteinfarkt, hva er det egentlig?](http://www.friskogfunksjonell.no/hjerteinfarkt-hva-er-det-egentlig/ "Hjerteinfarkt, hva er det egentlig?")

-   [Stump røyken](http://www.friskogfunksjonell.no/stump-royken/ "Stump røyken")

-   [Ketose eller ketoacidose?](http://www.friskogfunksjonell.no/ketose-eller-ketoacidose/ "Ketose eller ketoacidose?")

-   [Fedmeoperasjon av unge, en akseptabel løsning?](http://www.friskogfunksjonell.no/fedmeoperasjon-av-unge/ "Fedmeoperasjon av unge, en akseptabel løsning?")

-   [Midlertidige løsninger - midlertidige resultater](http://www.friskogfunksjonell.no/midlertidige-losninger/ "Midlertidige løsninger – midlertidige resultater")

-   [Energibalansen - hva sier den egentlig?](http://www.friskogfunksjonell.no/energibalansen/ "Energibalansen – hva sier den egentlig?")

-   [Insulinindeks - hva og hvorfor?](http://www.friskogfunksjonell.no/insulinindeks/ "Insulinindeks – hva og hvorfor?")

-   [Sunt kosthold på studentbudsjett](http://www.friskogfunksjonell.no/sunt-kosthold-pa-studentbudsjett/ "Sunt kosthold på studentbudsjett")

-   [Underholdningsslavens redning](http://www.friskogfunksjonell.no/underholdningsslavens-redning/ "Underholdningsslavens redning")

#### Kosthold:

-   [Alt du trenger å vite om proteinkvalitet](http://www.friskogfunksjonell.no/proteinkvalitet/ "Alt du trenger å vite om proteinkvalitet")

-   [De offentlige anbefalingene for fett, godt begrunnet?](http://www.friskogfunksjonell.no/de-offentlige-anbefalingene-for-fett-godt-begrunnet/ "De offentlige anbefalingene for fett, godt begrunnet?")

-   [Irritabel tarm og hva du kan gjøre med det](http://www.friskogfunksjonell.no/irritabel-tarm-og-hva-du-kan-gjore-med-det/ "Irritabel tarm og hva du kan gjøre med det!")

-   [Søtstoffer](http://www.friskogfunksjonell.no/sotstoffer/ "Søtstoffer")

-   [Nøkkelhull, bare tull?](http://www.friskogfunksjonell.no/nokkelhull-bare-tull/ "Nøkkelhull, bare tull?")

-   [Sunt eller usunt, betydningen av kontekst](http://www.friskogfunksjonell.no/betydningen-av-kontekst/ "Sunt eller usunt – betydningen av kontekst")

-   [Metthetsfølelsen, viktig når du skal velge kosthold](http://www.friskogfunksjonell.no/metthetsfolelsen/ "Metthetsfølelsen – viktig når du skal velge kosthold")

-   [Hvilken diett skal jeg velge?](http://www.friskogfunksjonell.no/hvilken-diett-skal-jeg-velge/ "Hvilken diett skal jeg velge?")

-   [Heldigvis bestemmer vi selv hva vi skal spise](http://www.friskogfunksjonell.no/heldigvis-bestemmer-vi-selv-hva-vi-skal-spise/ "Heldigvis bestemmer vi selv hva vi skal spise")

-   [Kan barn spise lavkarbo?](http://www.friskogfunksjonell.no/kan-barn-spise-lavkarbo/ "Kan barn spise lavkarbo?")

-   [Hvorfor bør du spise variert?](http://www.friskogfunksjonell.no/hvorfor-bor-du-spise-variert/ "Hvorfor bør du spise variert?")

-   Enkle tiltak som kan forbedre kostholdet ditt - [del 1](http://www.friskogfunksjonell.no/3-enkle-tiltak/ "Enkle tiltak som kan forbedre kostholdet ditt – del 1"), [del 2](http://www.friskogfunksjonell.no/3-tiltak-del-2/ "Enkle tiltak som kan forbedre kostholdet ditt – del 2"), [del 3](http://www.friskogfunksjonell.no/3-tiltak-del-3/ "Enkle tiltak som kan forbedre kostholdet ditt – del 3")

-   [Enkle prinsipper for kosthold og styrkeøkning](http://www.friskogfunksjonell.no/enkle-prinsipper-for-kosthold-og-styrkeokning/ "Enkle prinsipper for kosthold og styrkeøkning")

-   [Enkle tiltak for å få i seg nok mat](http://www.friskogfunksjonell.no/enkle-tiltak-for-a-fa-i-seg-nok-mat/ "Enkle tiltak for å få i seg nok mat")

-   [Enkle tiltak for å få i seg lite nok mat](http://www.friskogfunksjonell.no/enkle-tiltak-for-a-fa-i-seg-lite-nok-mat/ "Enkle tiltak for å få i seg lite nok mat")

#### Trening:

-   [Planlegg treningen din](http://www.friskogfunksjonell.no/planlegg-treningen-din/ "Planlegg treningen din")

-   [Basistrening - bli trent for å trene](http://www.friskogfunksjonell.no/basistrening/ "Basistrening – bli trent for å trene")

-   [Har du god mobilitet i hoften?](http://www.friskogfunksjonell.no/har-du-god-mobilitet-i-hoften/ "Har du god mobilitet i hoften?")

-   [Hvordan bli raskere](http://www.friskogfunksjonell.no/hvordan-bli-raskere/ "Hvordan bli raskere")

-   [Guide til å mestre pullups](http://www.friskogfunksjonell.no/guide-til-a-mestre-pullups/ "Guide til å mestre pullups")

-   Egenbehandling ved belastningsskader - [del 1](http://www.friskogfunksjonell.no/egenbehandling-ved-belastningsskader-del-1/ "Egenbehandling ved belastningsskader – del 1"), [del 2](http://www.friskogfunksjonell.no/egenbehandling-ved-belastningsskader-del-2/ "Egenbehandling ved belastningsskader – del 2")

Vi avsluttet året med en [spørrerunde](http://www.friskogfunksjonell.no/sporrerunde/ "Spørrerunde") som til slutt fikk over 90 kommentarer med spørsmål og svar. Vi kommer helt klart til å ha flere spørrerunder!

## Nye skribenter

I løpet av året har vi knyttet til oss flere skribenter. Thomas Olsen, Ingvild Thun og Asle Bøe har debutert med artikler i år, og vi ønsker alle hjertelig velkommen på laget. Vi har også fått gjesteinnlegg fra Martin Norum, noe vi håper det kommer flere av i fremtiden!

Vi har alle blitt ett år eldre, og økt kompetansenivået vårt. Vegard, Thomas, Ingvild og Hanne har alle fullført bachelorgrad i ernæring. Hanne har nå tatt fatt på medisinstudiet, Thomas har påbegynt en master i Human Ernæring, mens Vegard og Ingvild har startet på mastergraden i Klinisk Ernæring. Torbjørn fullførte sin bachelorgrad i fysioterapi, og har det siste halvåret vært utplassert i turnus. Eivind er fremdeles i full jobb som fysioterapeut.

Mot slutten av året fikk Hanne publisert en [artikkel i Tidsskriftet](tidsskriftet.no/article/2940375) på bakgrunn av bacheloroppgaven sin om de offentlige anbefalingene for fett. Vegard ble [intervjuet i magasinet VOF](http://www.friskogfunksjonell.no/intervju-i-vof/ "Intervju i VOF"), der han uttalte seg om de offentlige kostrådene, samt at han ble representert i TV2 Sporty i en sak om [kosthold på begrenset budsjett](http://www.tv2.no/sporty/kosthold/spis-sunnere-og-spar-tusenlapper-hver-maaned-3944871.html).

## 2013 - Veien videre

Selv om vi sier oss godt fornøyd med 2012, må vi se fremover, for det er et stort forbedringspotensiale! Et soleklart mål er å poste gode artikler regelmessig, og unngå tørkeperioder slik vi har hatt noen av i år. For å oppnå målsetningen om mer regelmessig publisering av artikler, ønsker vi å utvide skribentstallen i 2013!

Et annet mål for 2013 er å videreutvikle kunnskapsbasen. Den langsiktige planen er at denne skal fungere som et solid arkiv med lettfattelig informasjon om temaene vi skriver om, slik at alle skal kunne sette seg inn i hvordan ting fungerer uten å måtte studere i mange år.

Vi ønsker å jobbe videre for at siden skal vokse ytterligere, da vi ønsker å nå ut til flest mulig! I den sammenheng er vi veldig takknemlige for alle som deler artiklene på facebook og andre sosiale plattformer, og på den måten hjelper oss med å realisere akkurat dette.

Vi ønsker dere alle et godt nyttår, og håper dere vil fortsette å følge oss i året som kommer. Dere vil ikke bli skuffet!

##### Hva er din favorittartikkel fra 2012, og hvorfor? Del din mening i kommentarfeltet!
