---
title: "Aktivitetsnivå og helse"
author: "Vegard Lysne"
date: "2011.11.18"
categories:
  - trening
  - aktivitet
---

Vi trener mer enn noen gang, men likevel har vi aldri vært så overvektige som vi er i dag. Helseundersøkelsen i Nord-Trøndelag, [HUNT](http://www.ntnu.no/documents/10304/1130562/folkehelse-i-endring-huntrapport-2011.pdf), viser at 75 % av alle menn og 61% av alle kvinner over 20 år er overvektige (BMI \> 25). Nesten hver fjerde nordmann lider av fedme (BMI \> 30). Hvordan henger dette sammen?

**Mange tror at løsningen på denne overvektsproblematikken er å trene mer og spise mindre.** Dette har i lang tid vært den anbefalte fremgangsmåten, men problemet har likevel ikke blitt mindre. Av ulike årsaker er det svært få som klarer å oppnå målene sine på denne måten, og da må vi finne andre løsninger.

**En ting som er åpenbart, er at vi beveger oss mye mindre enn vi gjorde før, og da snakker vi ikke om trening,** men om det daglige aktivitetsnivået. I dag kjører vi til og fra jobb, og på jobben sitter vi stort sett i en stol. Når vi kommer hjem, blir vi sittende foran en skjerm til vi går og legger oss, kanskje avbrutt av en treningsøkt et par ganger i uken.

Det er ingen tvil om at aktivitetsnivået til gjennomsnittsnordmannen bør økes. Menneskekroppen er ikke laget for å sitte stille, og det er også vist at stillesitting øker dødeligheten uavhengig av treningsmengde. Men, hvordan skal vi få dette til? Og ikke minst, hvilken type aktivitet bør vi først og fremst øke mengden av?

## Trening

Trening, både styrketrening og utholdenhetstrening, har mange positive effekter på helsen vår. Blant annet vil større og sterkere muskler gjøre hverdagens oppgaver lettere, forbedret insulinfølsomhet gjør at vi bedre tåler maten vi putter i oss og et økt oksygenopptak vil forbedre vår evne til å forbrenne fett.

Samtidig kan for mye trening ha negative effekter. Et økt stress på kroppen under trening kan over tid føre til uheldige slitasjer, samtidig som vi kan bli mer utsatt for sykdom. På grunn av dette, kan vi ikke ukritisk øke mengden av denne typen aktivitet. Ved store treningsmengder risikerer du også å bli utbrent, noe som ytterligere forværrer de nevnte problemene. Disse problemene er blant annet knyttet til en økt utskillelse av kortisol, som er kroppens stresshormon.

Alle har godt av å trene noen ganger i uken, men før vi øker mengdene er det en god ide å tenke over kvaliteten på det vi gjør på trening, slik at vi får med oss de gode effektene uten å stresse kroppen unødvendig!

## Hva bør vi gjøre i stedet?

All aktivitet er bra, ikke bare den som er forbundet med trening. Aktiviteter med lav intensitet som gåturer (rolige joggeturer om du er godt trent), sykling til og fra jobb, gå i trapper og alt mulig annet som får deg opp av godstolen har flere gunstige effekter på helsen, blant annet at:

-   Fettforbrenningen blir mer effektiv. Under aktivitet med lav intensitet vil hovedenergikilden være fett. Å effektivt hente energi fra fettvevet er noe de fleste vil ha gunstige helseeffekter av.

-   For det kardiovaskulære systemet vil denne typen aktivitet bidra med å utvikle det kapillære nettverket, samt øke mengden mitokondrier i muskelcellene.

-   Sammenliknet med å være inaktiv, vil denne typen aktivitet bidra til å styrke skjelett og bindevev, slik at du blir bedre rustet til å tåle hverdagens påkjenninger.

-   Økt blodgjennomstrømming fører til at du lettere blir kvitt slaggstoffer som bygger seg opp under trening, noe som fører til bedre restitusjon før neste treningsøkt.

## Hvordan skal vi øke det daglige aktivitetsnivået?

Generelt bør du benytte enhver anledning til å bevege deg, men store deler av døgnet har vi begrensede muligheter til å gjøre nettopp dette. Enten du går på skole eller jobber på kontor, blir det nødvendigvis mange timer daglig i sittende stilling. Likevel kan du gjøre et par enkle grep som vil bidra til et økt aktivitetsnivå:

-   Velg trapper i stedet for heisen

-   Benytt alle muligheter til å reise deg fra stolen i løpet av dagen, f.eks. for å hente kaffe/vann, noe som ikke nødvendigvis trenger å hentes på det nærmeste stedet! Kanskje du til og med får inkludert trapper i dette prosjektet?

-   Du trenger ikke alltid å ta bussen helt fram. Du kan f.eks. gå av et par stopp tidligere og gå resten. Om du har muligheten til det, kan du kanskje gå eller sykle hele veien, og få en enda bedre effekt av det?

-   Gå til butikken, eller parker et stykke fra inngangen. Dersom du handler en del, får du også bært de tunge posene et stykke!

-   I stedet for å sette seg ned i sofaen etter middag, kan du et par kvelder i uken gå en kveldstur i nabolaget. I tillegg til at du får beveget deg, kan dette bidra til å bedre søvnkvaliteten den påfølgende natten!

## Er vi i mål?

Å øke aktivitetsnivået vil ikke alene løse overvektsproblematikken, men det er helt klart en del av løsningen. Størstedelen av problemet må løses gjennom de valgene vi tar i butikken, på kjøkkenet og ved spisebordet.

Et mer bevisst forhold til fysisk aktivitet vil likevel gjøre at vi bedre benytter oss av energien vi får i oss. Samtidig vil vi kanskje øke motivasjonen til å gjøre de riktige valgene i matveien, og da er vi på vei i riktig retning!

Dette blogginnlegget har tidligere vært publisert hos [Sunt Hjem](http://www.sunthjem.wordpress.com/).
