---
title: "De offentlige anbefalingene for fett, godt begrunnet?"
author: "Hanne Storhaug"
date: 2012.09.04
---

Gjennom denne høsten (2011) har vi hørt flere uttalelser fra myndigheter og fagpersoner om mettet fett og hjerte- og karsykdommer. Den siste som uttalte seg var helsedirektøren. Det har vært vanskelig å få konkrete svar på hva uttalelsene og rådene er baserte på, men det vi i allefall har hørt mange ganger er at [kostrådene](http://www.helsedirektoratet.no/publikasjoner/kostrad-for-a-fremme-folkehelsen-og-forebygge-kroniske-sykdommer/Publikasjoner/kostrad-for-a-fremme-folkehelsen-2011.pdf) støtter seg på store systematiske kunnskapsoppsummeringer, og at disse bruker samme metodologi som World Cancer Research Fund ([WRCF](http://www.wcrf.org)) gjør i sin store rapport om kreft og miljøpåvirkninger. Med slike argumenter stopper diskusjonen opp. Noen har valgt å stole på at dokumentasjonen som foreligger er så sterk som det som er blitt forespeilet oss, mens andre, meg selv inkludert, har vært svært interesserte i å finne ut mer. Som en del av bacheloroppgaven min i ernæring har jeg gått gjennom den dokumentasjonen helsedirektoratet legger hovedvekten sin for å gi oss anbefalinger om fett.

## Anbefales det fortsatt en reduksjon i mettet fett?

Det kan se ut som om helsedirektoratet fortsatt anbefaler en reduksjon i mettet fett for å redusere risikoen for [hjerte- og karsykdommer](brokenlink/hjerteinfarkt-hva-er-det-egentlig/ "Hjerteinfarkt, hva er det egentlig?"); både fordi det ser slik ut fra matrisene som oppsummerer helseeffekter (matrise 19.1) og fordi det står at

> *de norske næringsstoffanbefalingene konkluderer at mettede fettsyrer og transfettyrer bør begrenses til 10E%*

Mettet fett nevnes også flere steder i kostrådene, der det blant annet anbefales magre meieri- og kjøttprodukter. Dette samsvarer ikke med nyere oversiktsartikler og metaanalyser (1-4) som har konkludert med at mettet fett ikke er signifikant assosiert med hjerte- og karsykdommer.

Rune Blomhoff har ledet arbeidsgruppen som har oppsummert forskningen gjort på fett og fettsyrer, og som er presentert i kostrapporten (5). Jeg skrev til han for å høre hvorfor det fortsatt anbefales å redusere mettet fett når resultatene fra de studiene som er gjort til nå viser så motstridende resultater at det samlet sett ikke er signifikante assosiasjoner mellom mettet fett og hjerte- og karsykdommer. Blomhoff svarte følgende:

> I kostrådene anbefaler vi ikke isolert sett reduksjon av mettet fett for å redusere HKS. Vi skriver flere steder at det er viktig at man ikke ser på rådene isolert, men at de må settes i sammenheng. Rådet om mettet fett må settes i sammenheng med råd om fisk og vegetabilske oljer, og energitetthet. I WHO/FAO rapporten som er en systematisk kunnskapsoppsummering konkluderer man at fettkvalitet er viktigere enn mettet fett isolert sett.  Dette er i tråd med de siste metaanalyser og reviews på feltet.

**Det kan altså se ut som om at kostrådene har gått bort fra å anbefale folk å redusere mettet fett alene, men at det nå heller fokuseres på å få folk til å spise mer flerumettet fett på bekostning av det mettede.**

## Bør vi heller velge myk margarin enn meierismør?

I matrise 19.1 står det at det er overbevisende evidens for at en utskifting av mettede fettsyrer med flerumettede vil gi redusert risiko for koronar hjertesykdom og død av koronar hjertesykdom.Det vises til rapporten fra WHO/FAO (6).

**Kostrådene (5), som er gitt ut av helsedirektoratet og rettet mot friske mennesker, har som hovedformål å forebygge kroniske sykdommer i befolkningen**. I disse anbefales det at en heller velger matoljer, flytende og myk margarin enn for eksempel meierismør. I rådene om meieriprodukter og kjøttvarer nevnes også dette byttet av mettet fett med umettet. Det skrives at:

> *For å sikre at det samlede kostholdet får en gunstig fettsyrekvalitet, bør inntaket av meieriprodukter med mye mettet fett begrenses og erstattes av matvarer som har lite mettet fett eller mye umettet fett*

Alle disse anbefalingene om å bytte ut mettet fett med flerumettet støtter seg hovedsaklig på konklusjoner fra WHO/FAO rapporten. Rune Blomhoff skriver at:

> Angående fett legger vi stor vekt på den systematiske kunnskapsoppsummeringen fra FAO/WHO fra 2009. Denne bør du lese.

Det har jeg gjort, og videre vil jeg presentere hovedtrekkene i det som handler om kostens sammensetning av fettsyrer for å unngå hjertesykdom.

##### Fat and fatty acids in human nutrition - Report of an expert consultation

Rapporten (6) er en oppsummering av det ekspertrådet fra FAO/WHO ble enige om under konferansen som ble holdt i Geneve i november 2008. Hensikten med møtet var at FAO og WHO, i deres roller som tekniske byråer for FN, skal gi vitenskapsbaserte råd om mat og ernæring til nasjonale myndigheter og til det internasjonale samfunn.

I rapporten kan det leses at “basert på data om morbiditet og mortalitet fra koronar hjertesykdom fra epidemiologiske studier og kontrollerte kliniske forsøk (som bruker koronar hjertesykdom og død som endepunkter), var det enighet om at \[...\] det er **overbevisende evidens for at det å erstatte mettet fett med flerumettet fett** senker risikoen for hjertesykdom."

I kapittel 14 skrives det hva som er grunnlaget for denne konklusjonen:

-   På bakgrunn av denne \[Jakobsen et al (7)\], sammen med støttende evidens fra kliniske forsøk med lavere risiko for koronar hjertesykdom på dietter med høy P/S ratio (høy ratio av flerumettet:mettet) \[Skeaff og Miller (8)\], og effekten av flerumettet fett på å senke LDL kolesterol og total/HDL ratio, **konkluderte rådet med at det er overbevisende evidens for lavere risiko for koronar hjertesykdom og død av koronar hjertesykdom når flerumettet fett erstatter mettet fett.**

Konklusjonen om overbevisende evidens er altså tatt på bakgrunn av metaanalyser av prospektive kohortstudier publisert av Jakobsen et al.(7), en metaanalyse av kliniske forsøk publisert i artikkelen av Skeaff og Miller (8) og det at flerumettet fett senker LDL kolesterolet og total:HDL ratio.

-   Selv om flerumettet fett senker LDL kolesterolet og total:HDL ratio er det ikke dermed sagt at risikoen for hjerte- og karsykdommer går ned. **Kostfaktorer kan påvirke mange andre parametre som er forbundet med økt sykdomsrisiko**, eksempelvis triglyserider i blodet, insulinsensitivitet og [LDL-partikkelstørrelse](brokenlink/minikurs-i-lipoproteiner/ "Minikurs i lipoproteiner"), og det er bred enighet om at studier gjort på biomarkører som kan si noe om sykdomsrisiko aldri kan erstatte studier som er gjort direkte på sykdom og død.

-   Artikkelen av Jakobsen et al. (7) viser en signifikant effekt på hjerterelatert død for kvinner under 60, men ikke for kvinner over 60. På menn er det ingen signifikant effekt  på sykdom eller død ved å bytte ut mettet fett med flerumettet. Les resultatene fra denne artikkelen [her](http://www.nutritionevidencelibrary.com/worksheet.cfm?worksheet_id=250651&highlight=Jakobsen%20MU&home=1). **Konklusjonen stemmer ikke med funnene**; dette er en overtolkning av resultater som i beste fall er relevante for kvinner under 60, ikke for hele befolkningen.

-   **Metaanalysen av randomiserte kontrollerte forsøk (8) fant ingen effekt på total dødelighet eller hjerterelatert dødelighet ved å bytte ut mettet fett med flerumettet.** Derimot fant de en såvidt signifikant effekt på hjertesykdom (men ikke død!) dersom flerumettet fett erstattet mettet. Skeaff og Miller har inkludert The Finnish Mental Hospital Study i sin metaanalyse; en studie som i flere andre metaanalyser (2, 9) er blitt ekskludert, fordi pasientene ikke ble randomiserte (det ble brukt cluster randomization) og fordi det var andre store forskjeller mellom gruppene, utenom fettinntaket, som kan ha påvirket utfallet.

## Er det virkelig tatt hensyn til alle resultater når vi anbefales å velge omega-6-rike oljer og margariner?

En oppsummering av resultatene fra WHO/FAO rapporten finnes igjen på side 333 og 334 i kostrapporten fra helsedirektoratet. Der finner vi flere interessante tall:

-   Mettet fett er ikke assosiert med hjertesykdom eller død fra hjertesykdom

-   Flerumettet fett er sterkt assosiert med død fra koronar hjertesykdom

    -   Resultatene på linolsyre speiler dette resultatet, og gir den samme RR på 1,25 (95% CI 1,02-1,52)

Likevel viser tabellen at får en svært god effekt på både koronar hjertesykdom og hjerterelatert død ved å bytte ut mettet fett med flerumettet. Dette ser ut til å være en selvmotsigelse, og for å finne ut hvor resultatene er tatt fra må vi gå tilbake til artikkelen fra Skeaff og Miller.

1.  Figur 12 i artikkelen (se under) viser resultatene fra en metaanalyse av prospektive kohortstudier og flerumettet fett. **Flerumettet fett er sterkt assosiert med dødelighet fra koronar hjertesykdom**. Den relative risikoen er 1,25 (95%CI, 1,06-1,47). Det betyr at risikoen for å dø av hjertesykdom for de som hadde høyt inntak av flerumettet fett, sammenliknet med de som hadde lavt inntak var 25% høyere. Denne risikoen kan være både over- og underestimert, men den ligger med 95% sannsynlighet mellom 1,06 og 1,47. Altså, i beste fall hadde de som spiste mer flerumettet fett 6% større sjanse for å dø enn de som spiste minst og i verste fall 47%. Disse tallene er å finne igjen i kostrapporten vår på side 333 (5).

2.  Tallene presentert i tabell A på side 333 i kostrapporten  viser også at den relative risikoen for å få hjertesykdom og for å dø av hjertesykdom var mye mindre for de som byttet ut mettede fettsyrer med flerumettede. **Risikoen for å dø av hjertesykdom er nesten halvert for de som gjorde dette byttet!**Resultatene presentert i kostrapporten er også tatt fra artikkelen av Skeaff og Miller, og her er det, etter min mening, gjort en alvorlig metodisk feil av de som har plukket ut resultatene til tabellen i kostrapporten vår. De har valgt å presentere resultater fra en metaanalyse gjort på bare tre utvalgte studier!

Skeaff og Miller har, i tillegg til de analysene presentert tidligere (som ikke viser effekt på dødelighet), gjort en metaanalyse der de **plukket ut kun de studiene som viste en signifikant forskjell i kolesterolet mellom gruppene og gjort en egen analyse på disse.** Resultater som før ikke var signifikante på hjerterelatert død er nå høyst signifikante. I denne analysen er det bare tre randomiserte kontrollerte forsøk som er tatt med: Oslo Diet Heart, STARS og The Finnish Mental Hospital Study. Det skrives også i artikkelen at:

> *The meta-analysis of trials in which serum cholesterol concentrations in the high P/S diet group were significantly lower than in the control group, revealed that a diet higher in PUFA and lower in SFA decreased the risk of fatal CHD; however, this was significant only after inclusion of results from the Oslo study which included smoking cessation as part of the treatment.*

## WHO/FAO er ydmyke i sin rapport

Skeaff og Miller skriver blant annet i FAO/WHO-rapporten at:

> *The available evidence from cohort and randomized controlled trials is unsatisfactory and unreliable to make judgment about and substantiate the effects of dietary fat on risk of CHD.*

og:

> *The observational evidence for an association between dietary PUFA and CHD risk is inconsistent and is unreliable.*

Evidensen som foreligger er langt fra konsistent eller homogen, noe som også påpekes i rapporten fra WHO/FAO. Det er ikke tatt hensyn til den signifikante assosiasjonen fra prospektive kohortstudier mellom flerumettet fett og økt dødelighet, mens analysen fra tre utvalgte RCTer som viser effekt på å bytte ut mettet fett med flerumettet er betydelig vektlagt.

**På bakgrunn av den dokumentasjonen som foreligger ser jeg meg derfor nødt til å konkludere med at evidensen presentert av WHO/FAO, og som er vektlagt av helsedirektoratet i utarbeidelse av sine kostråd, langt fra er entydig nok til å gjøre anbefalinger til et bredt spekter av befolkningen!**

## Etterord

Arbeidet med å finne fram i kildene brukt i kostrapporten har vært stort. Det er lite originallitteratur som er brukt, og en må lete seg gjennom hundrevis av sider for å finne ut hva kostrådene baserer seg på. De færreste har tid til dette. **Mange helsearbeidere i Norge bruker kostrapporten som en fasit, og har ikke tid til å sette seg inn i all dokumentasjonen bak konklusjonene som er oppsummert**. Når det konkluderes med at det er overbevisende evidens for noe blir dette godtatt og brukt som om det skulle være det. Jeg har selv lært på skolen gjennom disse årene på ernæring at dersom vi har en pasient med litt høyt LDL-kolesterol som spiser både ost og meierismør, er det viktig å anbefale vedkommende et bytte til f.eks. Vita hjertego\` og plantemargarin; et bytte som jeg, etter gjennomgang av litteraturen, ikke kan finne konsistent dokumentasjon for hvorfor en skal gjøre.

Avslutningsvis vil jeg oppfordre de som er interesserte til å lese artikkelen av Jakobsen et al. (7) og artikkelen av Skeaff og Miller (8). I tillegg er det høyst interessant å studere kvaliteten på de randomiserte kontrollerte forsøk som bytter ut mettet fett med flerumettet. En cochrane review fra 2011 (10) kan være til god hjelp.

#### Referanser:

1.  Siri-Tarino PW, Sun Q, Hu FB, Krauss RM: **Meta-analysis of prospective cohort studies evaluating the association of saturated fat with cardiovascular disease**. Am J Clin Nutr 2010, 91(3):535-546.

2.  Hooper L, Summerbell CD, Higgins JP, Thompson RL, Capps NE, Smith GD, Riemersma RA, Ebrahim S: **Dietary fat intake and prevention of cardiovascular disease: systematic review**. BMJ 2001, 322(7289):757-763.

3.  Siri-Tarino PW, Sun Q, Hu FB, Krauss RM: **Saturated fat, carbohydrate, and cardiovascular disease**. Am J Clin Nutr 2010, 91(3):502-509.

4.  Mente A, de Koning L, Shannon HS, Anand SS: **A systematic review of the evidence supporting a causal link between dietary factors and coronary heart disease**. Arch Intern Med 2009, 169(7):659-669.

5.  Nasjonalt råd for ernæring 2011**. Kostråd for å fremme folkehelsen og forebygge kroniske sykdommer, metodologi og vitenskapelig kunnskapsgrunnlag**.

6.  **Fats and fatty acids in human nutrition. Proceedings of the Joint FAO/WHO Expert Consultation**. November 10-14, 2008. Geneva, Switzerland. Ann Nutr Metab 2009, 55(1-3):5-300.

7.  Jakobsen MU, O'Reilly EJ, Heitmann BL, Pereira MA, Balter K, Fraser GE, Goldbourt U, Hallmans G, Knekt P, Liu S et al: **Major types of dietary fat and risk of coronary heart disease: a pooled analysis of 11 cohort studies**. Am J Clin Nutr 2009, 89(5):1425-1432.

8.  Skeaff CM, Miller J: **Dietary fat and coronary heart disease: summary of evidence from prospective cohort and randomised controlled trials**. Ann Nutr Metab 2009, 55(1-3):173-201.

9.  Ramsden CE, Hibbeln JR, Majchrzak SF, Davis JM: **n-6 fatty acid-specific and mixed polyunsaturate dietary interventions have different effects on CHD risk: a meta-analysis of randomised controlled trials**. Br J Nutr 2010, 104(11):1586-1600.

10. Hooper L, Summerbell CD, Thompson R, Sills D, Roberts FG, Moore H, Davey Smith G: **Reduced or modified dietary fat for preventing cardiovascular disease**. Cochrane Database Syst Rev 2011(7):CD002137.
