---
title: "Atferdsproblematikk og behandling"
author: "Kristian Fagerland"
date: 2013.01.10
---

Forekomsten av diagnoser som ADHD og autisme er økende. Et av de store spørsmålene innen dagens atferdsproblematikk er; hvorfor ser vi slik økning av disse uheldige problemene? Klarer vi å svare på dette spørsmålet, klarer vi kanskje også å hjelpe noen barn til en bedre hverdag?

## Er disse lidelsene uhelbredelige?

Forskning indikerer at ca. 4-6% av alle dagens barn har ADHD eller Autisme (1,2,3). I følge [Legeforeningen](http:// www.legeforeningen.no) defineres atferdsforstyrrelser av denne typen som uhelbredelige kjemiske forstyrrelser i hjernen, hvor genetiske faktorer spiller en vesentlig og forklarende rolle. Statped, som er et statlig spesialpedagogisk støttesystem, ser også ut til å støtte legeforeningens definisjon; at genetiske faktorer er hovedgrunnen til at disse lidelsene forekommer (4).

Andre skoler tenker heldigvis noe annerledes. Francis S. Collins er forsker, ph.D og lege. Han var leder av ”The Human Genome Project” som kartla alle menneskets gener. Tanken bak prosjektet var at når alle genene våre ble kartlagt, så hadde vi oppskriften til å medisinere alle sykdommer. Denne hypotesen viste seg å være feil. Riktignok klarte forskerne å kartlegge menneskets gener, men vi oppleder ingen endringer i verdens sykdomsbilde. Francis S. Collins uttaler seg i etterpåklokskap som følgende:

> ”Genene våre forteller ikke hele sannheten. Nyere økning av kroniske sykdommer som diabetes, barneastma, fedme og autisme kan IKKE skyldes forandringer i genene våre, da disse krever mye lenger tid til å forandre seg. Det MÅ skyldes miljømessige forandringer som for eksempel diett og fysisk aktivitet.” (5)

## Morgendagens atferdsbehandling?

Hvis Francis S. Collins har rett, så åpner dette dører for en helt ny vri innen atferdsbehandling. Hvis miljømessige faktorer som kosthold, trening og stressmestring er like viktige som gener, burde vi kanskje være mer skeptisk til hyppig bruk av sentralstimulerende medisiner som Ritalin, Stratera, Concerta og lignende? Disse lindrer bare symptomene, men kurerer ikke atferdsproblemene. Medisinene har for øvrig en del alvorlige bivirkninger (6). Hva med å starte behandlingen av disse barna med en mindre invaderende metode, som å se på livsstilsfaktorer og funksjonalitet av nervesystemet?

Først og fremst bør vi utelukke matintoleranser, og deretter utføre en funksjonell analyse av nervesystemet. Når vi forstår hvilke mattyper barna reagerer på og hvilke områder av hjernen som ikke ”fungerer”, kan vi gi spesifikke og rehabiliterende sansemotoriske øvelser. En screening av psykososiale faktorer bør også utføres. Dersom det eksisterer psykososialt stress så må dette håndteres av en profesjonell behandler som for eksempel psykolog eller NLP Coach osv.

Kandell beviste i 2000 at dersom tilstrekkelig næring er tilstede, blir nerveceller sterkere og mer funksjonelle når de blir stimulert (7). Forskningen gav ham en Nobelpris. Kandells arbeid støtter en sansemotorisk tilnærming i behandlingen av disse barna. Denne gruppen kan tilsynelatende ha særs godt av å styrke visse områder i hjernen.

## Hvordan bør vi behandle "primitiv atferd"?

ADHD og autistisk atferd kan argumenteres som å tilhøre en mer primitiv atferd enn den vi ønsker å se hos barn (eller voksne for den saks skyld). Mange enklere dyr demonstrerer atferd lik disse barna. Enklere dyr har dårligere sosiale antenner, tenker ofte kortsiktig istedenfor langsiktig, er mye mer utålmodige, mer aggressive, har dårligere evne til å se helheten i situasjoner, dårligere evne til å kommunisere og er dårligere til å multitaske enn oss mennesker.

Hovedforskjellen på menneskehjernen og dyrehjernen er at vi har utviklet store og komplekse frontale pannelapper. Dermed kan man si at primitiv atferd skyldes et problem i frontale mekanismer. Dette ser vi som daglig jobber med slike barn klinisk. Barna demonstrerer ofte aktive primitive reflekser (noe som er unormalt blant ”friske” barn). Barna tester dårlig i frontale tester som for eksempel multitasking og impulskontroll. I tillegg er de stadig dårlig i motorisk og kognitiv koordinasjon.

I min kliniske hverdag ser jeg at trening/stimulering av hjernens frontale områder samt en eliminering av matintoleranser og psykososialt stress kan forandre disse barnas hverdag. Skulle det vise seg at noen barn ikke responderer til denne type behandling, noe som er svært sjeldent, så er det indikert med en mer invaderende metode. Først da bør det være aktuelt med medisiner!

Referanser:

1 http://www.ncbi.nlm.nih.gov/pubmedhealth/PMH0002518/ (Pubmed Health)

2 http://www.ncbi.nlm.nih.gov/pubmedhealth/PMH0002494/ (Pubmed Health)

3 Welcome to your child´s brain by Aamodt & Wang

4 http://www.statped.no/adhd (Statped)

5 Disconnected Kids by Robert Melillo

6 http://en.wikipedia.org/wiki/Methylphenidate

7 Principles of Neuroscience by Kandell & Schwartz
