---
title: "Kan barn spise lavkarbo?"
date: "2012.01.07"
---

Denne uken har dette spørsmålet dukket opp i media. Først ut var Sunt Hjem AS, med sitt [blogginnlegg](http://www.sunthjem.no/2012/01/05/kan-barn-spise-lavkarbomat/) om temaet, og påfølgende [artikkel](http://sprek.bt.no/sprek/Fikk-kjokkenet-endevendt-i-jakten-pa-usunn-mat-13386.html) i blant annet BT, der blant annet ernæringsfysiolog Janne Walle er hjemme hos en familie for å hjelpe dem med kostholdet. Spreks kostholdsekspert, Mette Helvik Morken, som har doktorgrad i ernæring, var raskt ute med å [kritisere](http://sprek.bt.no/sprek/-Lavkarbodiett-er-ikke-bra-for-barna-13390.html) det hun mener tenderer til barnemishandling. Jeg syns denne debatten vitner om to parter som ikke forstår hverandre og derfor snakker forbi hverandre. Her kommer mine innspill.

## Siv Hauge og Sunt Hjem AS

Utgangspunktet for dette innlegget er et [blogginnlegg](http://www.sunthjem.no/2012/01/05/kan-barn-spise-lavkarbomat/) skrevet av Siv Hauge, ernæringsterapeut og daglig leder i [Sunt Hjem AS](http://www.sunthjem.no). Hauge står for et kosthold basert på rene, hele matvarer, og et redusert inntak av karbohydrater. I dette innlegget argumenterer hun for at også barn kan (og bør) ha et kosthold basert på disse retningslinjene. Hun skriver blant annet at:

> *Det vil si at friske, aktive og normalvektige barn kan spise oppimot 45 E% karbohydrater. Kilden til karbohydratene (sukkerarter) er svært viktig, og bør være grønnsaker, bær, frukt, belgfrukter, nøtter, frø og kjerner. Sukker, hvitt mel og hvit ris er ingen god karbohydratkilde da det kun inneholder sukker og ingen vitaminer eller mineraler.*

Med andre ord er ikke dette snakk om noe ekstremt lavkarbokosthold. En uttalelse mange nok vil kritisere er at inntaket av frukt bør reduseres, men i blogginnlegget begrunner Hauge hvorfor hun mener dette, og skriver:

> *Jeg sier ikke at barn IKKE skal spise frukt, men at inntaket ikke skal gå på bekostning av grønnsaker eller mat med viktige proteiner og fett. Det er mye bedre la barna spise hel frukt enn å drikke juice, for juice er som brus å regne.*

Fra et faglig synspunkt er dette noe det er vanskelig å være uenig i. Alle er enige om at vi spiser for lite grønnsaker, og at frukt ikke er en fullgod erstatter for dette. Når det gjelder karbohydrater i flytende form, er det mye som tilsier at dette ikke er det beste valget, noe jeg har [skrevet om tidligere](flytende-karbohydrater.qmd).

Til slutt i innlegget sitt stiller Hauge spørsmålet om det er farlig for barn å spise mye fett. Her flytter hun fokuset over på kvaliteten på det fettet barna får i seg, og advarer mot transfett fra kjeks og kaker, margarin, raffinerte og varmpressede planteoljer og herdet vegetabilsk fett.

## Mette Helvik Morken, klinisk ernæringsfysiolog

Dagen etter dukket det opp et svar fra spreks kostholdsekspert, Mette Helvik Morken. Morken har doktorgrad i ernæring, og lang erfaring som klinisk ernæringsfysiolog ved Haukeland Universitetssykehus. I innledningen på artikkelen ser vi at Morken er positiv til konseptet med å dra på hjemmebesøk til folk for å hjelpe dem med kostholdet, men her er det slutt på enigheten, og det er tydelig at hun ikke deler Sunt Hjems oppfatning om hvordan et kosthold bør se ut.

> *- Voksne får gjøre som de vil, men det tenderer til barnemishandling å gamble med maten til barna på denne måten. Å skulle hindre barn å spise brød, poteter, pasta og ris er feil, jeg har ikke problemer med å si det. Karbohydratene i disse matvarene inneholder næringsstoffer som vi vet er viktige for barns utvikling.*

I utgangspunktet er jeg veldig enig med Morken i hovedpoenget. Å sette barn på en streng diett, der enkelte matvarer fremstår som ulovlige, vil i det lange løp kunne føre til et lite avslappet forhold til mat. Vi vet at det som er ulovlig også er det som er mest spennende, og dersom man nekter barna å spise noe hjemme, vil de med stor sannsynlighet spise ekstra av dette i andre anledninger.

En del av utviklingen til et barn i matveien er å smake på mest mulig ulik mat, da dette blant annet bidrar til å utvikle smaksløkene og gir et avslappet forhold til mat. Vi må huske at mat er mer enn næringsstoffer, og også skal være en del av kulturen barnet vokser opp i!\
Når dette er sagt, så er det riktig at brød, poteter, pasta og ris inneholder viktige næringsstoffer, men de inneholder ingenting man ikke kan få fra andre matvarer. Så å fremstille det som at disse matvarene er nødvendige for et barns utvikling blir litt feil, selv om det også blir feil å nekte barna å spise dette.

Videre kan vi lese at:

> *Alle er enige om at vi bør spise mer grønnsaker og mindre sukkerholdige matvarer, men uenigheten handler om synet på karbohydratene som finnes i for eksempel korn og poteter – og ikke minst er synet på hva fett gjør med oss ulikt. Lavkarbofolket mener fett, også den mettede typen, er en helt OK energikilde, mens Helsedirektoratet anbefaler mindre mettet fett.*

Her ser vi at uenighetene når det kommer til karbohydrater ikke er så fryktelig stor når alt kommer til alt. At sukkerholdige matvarer er det som først og fremst bør kuttes ned på er noe stort sett alle fagfolk er enige om. Når det gjelder mettet fett, så er kunnskapsgrunnlaget bak de offentlige retningslinjene utrolig mangelfulle, og flere nye studier konkluderer med at det ikke er noen sammenheng mellom mettet fett i kostholdet og sykdomsrisiko, f.eks. [her](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2824152/pdf/ajcn9130535.pdf). Her ser jeg ikke noen grunn til å være særlig bombastisk verken den ene eller andre veien.

> *- Å ta bort brød og poteter fra kostholdet og å bytte ut margarin med smør, gjør at du får en helt feil sammensetning i kosten i forhold til det vi vet i dag. Å bruke fullfett meieriprodukter som H-melk og seterrømme anbefales ikke. Og hvor de har det fra at margarin er skadelig? Det skjønner jeg ikke.*

Med tanke på hvor dårlig kunnskapsgrunnlaget bak rådene om f.eks. fettinntak er, syns jeg det bør være rom for mer åpenhet rundt at det vi tror i dag ikke nødvendigvis trenger å være riktig. Margarin i seg selv er nok ikke farlig å spise, hvertfall ikke nå som det ikke lenger er transfett i norsk margarin. Jeg kjøper likevel ikke argumentene for hvorfor margarin skal være bedre enn smør. Margarin er umettede fettsyrer som er mettet gjennom industrielle prosesser, og hvorfor disse menneskeskapte mettede fettsyrene skal være bedre enn de naturlig mettede fettsyrene er for meg et mysterium. I tillegg bidrar margarin med mye omega-6, som vi allerede får i oss alt for mye av sammenlignet med omega-3.

**Les mer om [omega-3 og omega-6 her](omega-3-6.qmd).**

## Mine kommentarer til saken

Jeg vil først og fremst si at jeg er enig med poenger fra begge sider i denne debatten. Jeg ser heller ikke noen motsetninger som er så drastiske som de har blitt fremstilt i media. Når vi leser kritikken fra Morken, kan det se ut som om hun diskuterer mot noen som står for et ekstremt kosthold der alt av karbohydrater er bannlyst, noe som ikke er tilfelle. Hauge nevner 45E% fra karbohydrater i sitt blogginnlegg, noe som ikke kan sies å være særlig ekstremt i noen retning.

Barn med epilepsi behandles med et ketogent kosthold, som er en ekstremvariant av lavkarbo. Her er det ikke snakk om verken brød, pasta, potet eller ris, og heller ikke frukt passer inn i en slik diett. Andre barn har ulike allergier, og må kutte ut enkelte matvarer. Disse barna vokser også opp, så at disse matvarene er nødvendige for et barns utvikling er nok ikke helt riktig.

Et [moderat og variert lavkarbokosthold](lavkarbo-livsstil.qmd) inneholder gode matvarer som kjøtt, fisk, egg, grønnsaker, frukt, nøtter og bær. I tillegg er det plass til både potet, pasta, brød og ris, men ikke nødvendigvis hver dag. **Jeg ser ingen motsetninger mellom dette og et variert kosthold, og vil heller stille spørsmålet om hvor variert dagens barnekosthold er**. Brødmat til frokost, lunsj og kvelds og pasta til middag er ikke særlig variert i mine øyne. Ved siden av maten drikkes det gjerne juice, som bidrar med lite annet enn lettopptagelige karbohydrater. Middagen er ofte den eneste skikkelige proteintilførselen i løpet av dagen, og med tanke på hvor viktig proteiner er for et barns vekst så er ikke dette godt nok. Forhåpentligvis inkluderes det nok frukt og grønnsaker til å dekke de fem om dagen, som i mine øyne er et minimum med tanke på hva disse matvarene faktisk bidrar med av vitaminer, mineraler, fiber og fytokjemikalier.

**Les [våre råd for kosthold og fysisk aktivitet](helserad.qmd).**

Det jeg beskriver over her er ikke et urealistisk kosthold for et barn i dag, og hvis vi ser for oss at frokosten byttes ut med en sukkerrik frokostblanding så har vi en god beskrivelse av hva et barn faktisk spiser. Vi kan heller ikke neglisjere effektene av fysisk aktivitet, som må sies å ha falt drastisk de siste tiårene. En redusert fysisk aktivitet, vil gjøre at vi i mindre grad tåler et kosthold basert på mye karbohydrater. Her er det stor forskjell fra person til person!

**Hovedmålet med denne debatten må være å komme fram til et godt kosthold for barn, som bidrar til å forebygge overvekt og følgesykdommer som diabetes, som dessverre er sterkt økende blant barn.** Jeg syns likevel fokuset på å "ha rett" overdøver det målet, som forhåpentligvis er det samme hos alle debattantene. Jeg vil også understreke viktigheten av å tenke på kosthold som en livsstil, og droppe fokuset på midlertidige dietter.

**Les [diett eller livsstilsendring](diett-livsstilsendring.qmd).**

Jeg syns vi skal gå bort fra behovet for å kalle kostholdet lavkarbo eller hva det måtte være, og heller fokusere på hvilke matvarer vi bruker. Så lenge matvarene er av god kvalitet, så burde sammensetningen av næringsstoffene være underordnet. Media fokuserer for mye på detaljer, i stedet for å se på kostholdet som en helhet.

#### Hva syns du? Hvordan bør et barn spise?
