---
title: "Basistrening - bli trent for å trene"
author: "Torbjørn Lysne"
date: "2012.09.10"
---

På 90-tallet kom begrepet basistrening til verden. Det er ikke snakk om en ny og spesiell treningsmetode, men begrepet setter fokus på en viktig del av treningen. Basistrening gir deg en bedre fysisk kapasitet til å utøve den idretten/treningen du driver med.

## Hva er basistrening?

På folkemunne har betegnelsen basistrening blitt relatert til trening av dyptliggende stabiliseringsmuskulatur, hovedsakelig korsettmuskulaturen. Basistrening er mye mer enn dette. All trening som gjøres utenom den spesifikke idretten/treningen du ønsker å bli bedre på, kan kalles for basistrening. Det er en viktig del av treningen, og det er ikke uten grunn at ikke-spesifikk trening blir gjort i alle idretter og treningsmetoder. Basistrening kan defineres som **generell og/eller spesifikk utvikling av utholdenhet, styrke, hurtighet, bevegelighet, spenst, koordinasjon og psykiske egenskaper som ligger til grunn for ferdighetsutviklingen i ulike idretter.** Denne typen trening gjøres dermed for å skape et helhetlig treningsgrunnlag for å utøve en idrett. Et godt generelt treningsgrunnlag vil skape forutsetningene for et godt idrettslig nivå.

Vi kan også skille mellom generell og spesifikk basistrening. Den generelle delen tar sikte på å bedre de ulike faktorene som er sentral for en bedre ferdighetsutvikling i idretten. Den spesifikke basistreningen er ulike måter å imitere det man skal gjøre i idretten. Et eksempel på spesifikk basistrening er løpere som løper i vann. På denne måten får de trent på løpeteknikken på en annen måte enn deres egentlige treningsunderlag.

## Hvorfor drive basistrening?

Mange spør seg selv hvorfor det er viktig å trene på øvelser som ikke har noe med den egentlige treningen de driver. Basistrening er jo så kjedelig. Som et svar på dette er det lurt å tenke på hva du trenger for å bli bedre i den idretten du driver (eller for å nå målene for treningen din).

For å ta et eksempel: Hva trengs for å kunne løfte et maksløft i knebøy? Svaret er ikke bare en sterk lår- og setemuskulatur. I bunnen må du ha en god teknikk (spesifikk trening), men du trenger også å trene bevegelighet for å kunne å utføre øvelsen med en trygg og god teknikk. Du må også trene hurtighet for å klare å aktivere flest mulig av de raskeste og sterkeste muskelfibrene, og du må ha en god koordineringsevne for å ta til deg den riktige teknikken. Det er også viktig å være sterk nok i andre muskelgrupper for at teknikken skal opprettholdes. For eksempel er kjernemuskulaturen i mage/rygg viktige for at ryggen skal holdes i god posisjon under hele løftet. Oppsummert ser vi at et maksløft i knebøy er avhengig av styrke i hele kroppen, bevegelighet og koordinasjon nok til å gjennomføre teknikken riktig og hurtighet.

## Oppsummering

For å skape et godt treningsgrunnlag er basistrening viktig. Det vil gi deg en allsidighet som virker skadeforebyggende, det kan hjelpe deg til å bedre prestasjonen i en idrett, og sist, men ikke minst gjøre at du tåler mer trening. Du blir med andre ord "trent for å trene". Ved å trene mye basistrening vil du tåle mer av den spesifikke treningen, og dette vil igjen kunne bedre prestasjonsevnen din. Vi vil komme tilbake til hvordan du kan trene basistrening i en senere artikkel.

Så mitt tips til deg er å fokusere mer på basistreningen for å prestere bedre i den spesifikke treningen.
