---
title: "Møt 2013 med forbedret helse – kosthold"
date: 2013.01.02
---

Januar, første måned i det nye året, kjennetegnes av fulle treningssentre og utsolgt fruktdisk. Nå tar man tak i nyttårsforsettene, og det med brask og bram! Mange går hardt ut, i god tro om at denne gangen skal det gå, men de fleste faller raskt tilbake i gamle vaner. Vi har flere ganger understreket betydningen av å gjøre endringer som du kan leve med over lengre tid, og i år hjelper vi deg i gang med nettopp dette!

I denne saken vil jeg presentere 10 enkle kostholdstips som kan hjelpe deg i søket etter bedre helse. Du trenger ikke å gjøre alle sammen med en gang, eller i det hele tatt. Husk at alle små steg i riktig retning vil gjøre noe for totalresultatet! Begynn med det som er lett å gjennomføre, så vil motivasjonen til å gjøre flere endringer sannsynligvis øke etter hvert som resultatene kommer.

### 1. Spis mer grønnsaker

Dette vil alltid være det første rådet jeg gir til folk som ønsker å forbedre kostholdet sitt. Med mindre du fra før spiser masse grønnsaker, er dette et punkt det er lett å forbedre. Fordelene med grønnsaker er beskrevet mange andre steder her på siden, men kort fortalt bidrar de med masse vitaminer og mineraler, er basedannende, bidrar med lite energi per mengde og gir stort potensiale for variasjon i kostholdet.

### 2. Reduser inntaket av tilsatt sukker

En reduksjon i inntaket av sukker vil gi en positiv helsegevinst hos de aller fleste. Tilsatt sukker er tomme kalorier i den forstand at de bare bidrar med energi, uten å samtidig tilføre andre nødvendige næringsstoffer. Dersom sukker står blant de første ingrediensene i en matvare er dette i de fleste tilfeller en matvare du ikke bør spise for ofte eller for mye av.

### 3. Velg gode proteinkilder

Protein er et viktig næringsstoff, som fungerer som byggesteiner i alle kroppens celler. Fra maten vi spiser er protein det næringsstoffet som metter best, og proteinrik mat gjør det lettere å begrense totalinntaket. Ønsker du å begrense deg kan det derfor være effektivt å forsyne seg litt ekstra av kjøtt/fisk og heller ta litt mindre tilbehør.

### 4. Spis kaloriene i stedet for å drikke dem

Mat i [flytende form](http://www.friskogfunksjonell.no/bor-du-begrense-inntaket-av-flytende-karbohydrater/ "Bør du begrense inntaket av flytende karbohydrater?") metter generelt dårligere enn det vi finner i fast form. Å redusere på den flytende føden og heller prioritere å spise maten vår er et effektivt grep for å begrense energiinntaket. Samtidig kan flytende mat være et supert tiltak for de som sliter med å få i seg nok, men generelt i samfunnet er ikke dette vårt største problem!

### 5. Reduser inntaket av ferdigmat

Det meste vi finner av ferdigmat inneholder mye lettopptakelige karbohydrater i form av sukker og fint mel. Ved å redusere bruken av halv- og helfabrikata, og heller lager maten fra bunnen av med skikkelige råvarer, er du allerede langt på vei til å oppfylle de tre første tipsene på denne listen. Ved å lage større porsjoner når du først lager mat, har du også kvalitetsmat klar til neste måltid, eventuelt til lunsj neste dag.

### 6. Frukt og bær til dessert

Du tror kanskje at dessert er blant det første som må vike når du skal gjøre forbedringer i kostholdet ditt. Husk at du kan komme veldig langt med å velge andre alternativer til dessert, fremfor å kutte det helt ut. Frukt og bær kan være basisen for en sunn og god dessert som du kan spise med den beste samvittighet, gjerne hver dag!

### 7. Spis når du er sulten

Det verserer flere myter når det kommer til spisemønstre, alt fra viktigheten av frokost til det å spise ofte for å opprettholde forbrenningen. Dette støttes imidlertid ikke av forskningen, som viser at det er den totale mengden du spiser som har noe å si, ikke når du spiser den eller hvor mange måltider du fordeler det på. Finn et spisemønster som passer deg og din hverdag. Spis når du er sulten, ikke når klokken skriker «måltid»!

### 8. Innfør lørdagsgodt

Det å gjøre varige endringer er veldig viktig om du ønsker å forbedre helsen din. Det er begrenset hva korte kurer kan gjøre for deg i det lange løp, så disse er normalt sett ikke veien å gå. Det å kutte ting helt ut av kostholdet kan fungere for mange, mens det for andre kan bidra til å trigge større sprekker med jevne mellomrom. Hører du til den siste kategorien kan en løsning være å gjeninnføre lørdagsgodtet, der du har en dag i uken der du tillater deg det du styrer unna i hverdagen!

### 9. Spis variert

Ved å [spise variert](http://www.friskogfunksjonell.no/hvorfor-bor-du-spise-variert/ "Hvorfor bør du spise variert?") sørger du for å dekke behovet for alle næringsstoffene. Med å spise variert mener jeg at du spiser mat fra flere ulike matvaregrupper, altså kjøtt, fisk, egg, grønnsaker, frukt, nøtter, meieriprodukter og fullkorn. Ved å være innom de fleste matvaregruppene over tid skal det mye til at du ender opp med å få i deg for lite av noe som helst.

### 10. Fokuser på de viktige tingene

Du trenger ikke å detaljstyre kostholdet ned til den minste kalori. Kroppen er god til å tilpasse seg, og om du skulle spise mer enn vanlig en dag, så vil forbruket øke for å kompensere for dette. Husk også at det er inntaket over tid som har noe å si, så om du skeier ut en gang i blant så vil ikke dette nødvendigvis gjøre noe skade i det hele tatt.

Det er lett å la fokuset på sunt kosthold bli så stort at det går utover andre ting i livet. Da kan det være greit å ta med seg at det du gjør mesteparten av tiden også vil diktere mesteparten av resultatene, så om du ikke klarer å følge planen til punkt å prikke så går det som regel bra likevel. Et balansert og fornuftig forhold til kostholdet gir rom for variasjon og utskeielser, og dette er et viktig poeng om man ønsker å få til varige endringer!

## Hvor skal du begynne?

Noen mennesker er i stand til å gjøre store omveltninger i livene sine på kort tid, og det som skal til er enkelt og greit at de bestemmer seg. De fleste vil derimot ha større sjanser for å få til varige endringer dersom endringsprosessen skjer gradvis over tid. Vi har tidligere snakket om viktigheten av individuell tilpasning av kostholdet. Dette betyr i klartekst at du tilpasser kostholdet til deg, ikke omvendt.

Det er umulig å gi en fasit på hvilke råd man skal begynne med. Mange av dere følger nok også flere av disse rådene allerede, og noen har mer å ta tak i enn andre. Mitt beste tips blir å velge seg ut det man synes ser lettest ut å gjøre noe med og starte der. Motivasjonen til å gjøre flere endringer kommer med stor sannsynlighet etterhvert som de første tingene begynner å gli inn i hverdagen, og på denne måten blir det heller ikke snakk om store omveltninger på en gang.

På vegne av meg selv og alle andre som skriver for siden, ønsker jeg dere alle et godt nyttår! Om noen dager kommer en tilsvarende sak med treningstips, og i mellomtiden kan du mer enn gjerne dele dine beste kostholdstips i kommentarfeltet!
