---
title: "Hvordan kan vi bedre folkehelsen?"
author: "Eivind Eliasson"
date: 2013.03.14
---

Antallet overvektige øker gradvis i Norge med påfølgende livstilssykdommer, HUNT-undersøkelsene er entydige på dette, selv om det finnes flere positive ting som færre røykere og lavere dødelighet av hjerte- og karsykdom. Flere positive tiltak som frisklivssentraler, revidering av råd om fysisk aktivitet og ernæring osv hjelper utvilsomt, men likevel er det store deler av befolkningen som ikke treffes av disse. I dette debattinnlegget vil jeg presentere noen tanker om tiltak som kanskje kan gjøre noe med dette!

Det snakkes mye om hvordan man kan få til en større grad av endring fra helsemyndighetenes side, men så langt har man i liten grad lykkes. Undersøkelser viser at folk trener omtrent like mye som før, men hverdagsaktiviteten har droppet mye. Bil og buss har i stor grad tatt over for bena og sykkelen, heisen for trappen osv.

[Nøkkelhullsmerkingen](nokkelhull.qmd) og trening i arbeidstid er eksempeler på tiltak. Nøkkelhullsmerkingen har nok totalt sett bidratt positivt, selv om den er omdiskutert grunnet hvilke matvarer som skal kvalifisere. Mange forstår ikke at noen kategorier som generelt ansees som usunne kan få nøkkelhullsmerket, mens andre ikke. Grandiosaen med nøkkelhull er prakteksemplet som stadig blir dratt frem i media.

Trening i arbeidstiden er et eksempel på gode intensjoner som feiler i praksis. Man har i liten grad fått de inaktive som man ønsker å nå til å bli mer fysisk aktive, da de generelt dropper å delta.

## Hva kan vi så gjøre?

Man kan aldri nå ut til alle, men jeg tror følgende tiltak ville gjort det lettere å nå ut til flere:

-   Fjern alle former for moms på trening. For de fleste er ikke trening et økonomisk spørsmål, men for meg som jobber med grupper som generelt har dårlig råd, kan det å være medlem på et treningssenter, stikke innom svømmehallen osv. være i grenseland til hva de greier økonomisk. De gruppene som har størst utbytte av økt fysisk aktivitet er også de gruppene som har dårligst økonomi.
-   Innfør treningsplikt i arbeidstiden ved alle nyansettelser i det offentlige og hos statlig eide bedrifter. Treningsformen kan være valgfri, og om vedkommende bruker den til å sykle til jobb, spille fotball eller svømme er mindre viktig så lenge arbeidstakeren selv har valgt aktiviteten. Arbeidsgiver kan f.eks. tilrettelegge ved å sette av en time i uka i den lokale idrettshallen for å spille fotball for de som ønsker det. Man må selvfølgelig gjøre unntak for enkelte grupper, men alt i alt tror jeg dette kan bidra positivt når det gjelder sykefravær og en rekke livstilssykdommer.
-   Innfør kjøregodtgjørelse for bruk av sykkel i arbeidstiden. Det å gi samme kjøregodtgjørelse for bruk av sykkel vil nok føre til at flere lar bilen stå!
-   Fjern momsen på rene produkter av fisk, frukt og grønt. Avgiften på f.eks. sukker kan økes for å finansiere dette.
-   Selv om det bare gjelder en mindre del av befolkningen så tror jeg et forbud mot industrielt transfett, ala det man har i Danmark, kan være positivt for den totale folkehelsen.
-   Innfør gratis frukt og grønnsaker på alle skoler. Frukt og grønt bidrar med lite kalorier, men metter bra, og fører ofte til at de fortrenger inntak av mindre sunne og mer energitette matvarer.
-   Reklameforbud for godteri, junkfood etc rettet mot barn og unge.
-   Fjerning av godteri og snacks ved kassa i butikkene. Frukt- og grøntdisken burde ideelt sett ligge i kasseområdet i alle butikker. Dette vil ha en potensiell påvirkning på impulskjøp, der det helt klart er mer gunstig om folk i større grad rasker med seg et eple enn en sjokolade!

Vil disse tiltakene være til hjelp? Vil dette være gjennomførbart? Noen punkter vil definitivt kreve en hel del, f.eks. dette med treningsplikt og tilrettelegging rundt det. Likevell kan man dra paralleller til at mange arbeidsplasser har innført røykeforbud og tilbyr kurs i arbeidstiden for røykeslutt, så hvorfor ikke strekke seg litt lenger?

Hver for seg utgjør nok tiltakene lite, men til sammen kan det hende de utgjør en forskjell som kan bidra positivt til folkehelsen.
