---
title: "Møt 2013 med forbedret helse - Trening"
author: "Torbjørn Lysne"
date: 2013.01.04
---

Nok et år er gått og mange nyttårsforsett er inngått. Et nyttårsforsett har som oftest et mål om å bedre sin egen livssituasjon på en eller annen måte. Veldig mange velger et forsett hvor sin egen helse står i fokus, enten det er snakk om bedret kosthold, slutte å røyke/snuse eller å trene mer. Den store utfordringen for folk flest er å gjennomføre det de har de har satt seg som mål.

Helse er i vinden som aldri før, og 2013 vil nok ikke bli et unntak. Sist så Vegard på [tips som kan forbedre kostholdet ditt](brokenlink/mot-2013-med-forbedret-helse-kosthold/). Her kommer noen tips for hvordan nettopp du kan komme i bedre form i 2013.

### 1. **Sett tydelige og realistiske mål**

For å kunne nå et mål om bedre form bør du skrive ned noen målsetninger som er klare og tydelig for deg selv. Jeg vil anbefale deg å konkretisere målene slik at det er lett å se om du når dem eller ikke utover året. Et eksempel kan være «Jeg skal ta 140kg i knebøy, 150kg i markløft og 100kg i benkpress», i stedet for «Jeg skal bli sterkere i knebøy, markløft og benkpress». «Jeg skal løpe 10km på x minutter», ikke «få bedre utholdenhet». «Jeg skal trene x antall ganger i uken», ikke «jeg skal trene oftere». Spesifiser målene – de vil da bli mer oversiktelig og du vil ha større motivasjon for å klare de. Heng gjerne målene opp på veggen, kjøleskapet eller bruk det som bakgrunn på datamaskinen for å hele tiden minne deg selv på hva du har satt deg som mål i 2013.

Med realistiske mål mener jeg at du bør sette deg et mål som er oppnåelig med tanke på din situasjon. Du må samtidig være ambisiøs og skrive ned noe du mener er verdt å jobbe for å klare. Det kan være lurt også å nevne *hvorfor* du ønsker å oppnå hvert enkelt mål. Urealistiske mål vil ofte drepe motivasjonen, mens realistiske mål er første steg på veien til suksess!

### 2. Planlegg treningen din

Jeg vil anbefale deg å [lage en plan](brokenlink/planlegg-treningen-din/) for hva du skal trene i løpet av uken og hvilke dager du skal trene det på. Det nytter å bruke litt tid på en god planlegging. I fjor høst kom det en liten sak på hvordan du kan planlegge treningen din.

En god plan er lettere å gjennomføre enn ingen plan.

### **3. Øk hverdagsaktiviteten**

Dette er kanskje det viktigste tipset for svært mange som ønsker en generell forbedret fysisk helse. Kaloriforbruk pr. minutt er naturlig nok lavere enn ved trening som løping, styrketrening, svømming eller aerobic, men hverdagsaktiviteten sitt store omfang gjør den kanskje til den viktigste faktoren for fettforbrenningen. Oppsøk hver mulighet til litt bevegelse, det være seg litt mer bevegelse i løpet av arbeidsdagen, bruk av trapper fremfor heis/rulletrapp, hoppe av bussen noen stopp for tidlig eller ta en ekstra sløyfe med hunden på kveldstid. Du kan også la bilen stå om du skal gjøre noen små ærend på nærbutikken. Bruk også helgene på mer tid til aktiviteter med familie og venner. Dette er enkle, men effektive tiltak for en bedre helse.

Og til småbarnsforeldre: Ingenting er gøyere enn foreldre som er med i svømmehallen eller på fotballbanen!

### 4. Sett av tid

Dette punktet er en naturlig del av planleggingsfasen. Hvis du VIRKELIG har et ønske om et bedre treningsår må du også sette av nok tid til trening. Det er selvsagt ingenting i veien for å planlegge aktiviteter som ikke nødvendigvis blir omtalt som trening, noe punktet om økt hverdagsaktivitet understreker. Poenget er å investere nok tid til sin egen helse.

### 5. Gjør noe mens du ser på TV

Den velkjente TV-tiden er obligatorisk i nesten samtlige hjem. Hvorfor ikke bruke litt av tiden på litt aktivitet, eventuelt å gjøre det samtidig? Vi er i dag så heldige at flere tredemøller og ergometersykler er utstyrt med TV-skjermer. Ta med ørepropper og se favorittserien mens du trener! I hjemmet kan du for eksempel tøye eller

Les også [Underholdningsslavens redning](underholdningsslavens-redning.qmd).

### 6. Finn en aktivitet du trives med

Å finne aktiviteter man liker er kanskje den største motivasjonsfaktoren for mer fysisk aktivitet. Det viktigste er ikke hvilke aktiviteter du velger, men at du trives med å gjøre de!

### 7. Tren effektivt

Mange har en travel hverdag og tar seg ikke tid til lange treningsøkter. Hvis du er én av dem kan vi meddele at korte, men intensive treninger ofte gir vel så mye utbytte som lengre treningsøkter. Enkle løsninger på tidsfloken kan være å trene annenhver øvelse på over- og underkropp i styrkerommet, intervalløkter i stedet for langkjøringer på utholdenhetstreningen og lignende. Selv om tiden kanskje ikke alltid strekker til og du ikke rekker all treningen du har planlagt, tenk på ordtaket: "alle monner drar". Litt er alltid bedre enn ingenting!

### 8. Oppsøk kompetanse

For å få best mulig utbytte av den treningen du legger ned kan det være lurt å oppsøke kompetanse. Det finnes mange der ute som har både utdanning og erfaring innen trening og helse. Fordelene med å oppsøke treningshjelp er at du kan få mer igjen for treningen du legger ned. De kan hjelpe deg med å lage en fornuftig plan med tanke på innhold, intensitet og progresjon for at du skal nå målene dine for året. De kan også komme med tekniske tilbakemeldinger som vil hjelpe deg til å prestere bedre og samtidig unngå skader.

### 9. Tren variert

Et godt tips for hvordan du kan få trent mer og få mer nytte av treningen er å trene variert. Godene med stor variasjon er at du får en generelt bedre fysikk, du vil ha mindre risiko for belastningsskader og ikke minst ha lettere for å motivere deg for hver enkelt trening da det er mindre monotont treningsopplegg. Ta med elementer med utholdenhet, hurtighet, styrke og spenst hver uke (noen kan gjerne kombineres i en og samme økt).

### 10. Ikke glem hvile

Dette er et viktig punkt! Å gå rett fra en sofatilværelse til daglig trening er ikke vår sterkeste anbefaling. Å ukritisk sette ut i et voldsomt tempo i januar og februar resulterer fort i motivasjonssvikt, utmattelse og skader. Finn en treningsfrekvens som du tror kan holde hele året og øk heller etter hvert dersom du føler du kan det. God restitusjon i form av nok nattessøvn, mat og hvile er samtidig en av de viktigste faktorene for fremgang på trening.

## Hvor skal du begynne?

Å bli mer fysisk aktiv handler først og fremst om å endre vaner. Skal du klare dette må du gjøre treningen til en naturlig del av hverdagen. Trening må, som så mye annet, tilpasses den enkelte for best mulig resultat. Det som er helt klart er at du må trene på det du vil bli god på!

Tipsene over er ment som en en hjelp til hvordan du kan inplementere trening i en travel hverdag. Hvor aktiv du er i dag er avgjørende for hvilke tips som kan hjelpe deg mest på veien til en bedre helse, men en god blanding av alle punktene vil kunne hjelpe deg på veien. Legg gjerne igjen en kommentar om dine beste treningstips!
