---
title: "Beinhinnebetennelse - er hvile det beste?"
author: "Martin Hole Hanstvedt"
date: 2013.04.04
---

Beinhinnebetennelse er den hyppigst forekommende kroniske belastningslidelsen hos idrettsutøvere, og spesielt løpere er utsatt. Hvile blir ofte anbefalt for å bli kvitt plagene, men er dette det beste? I denne artikkelen vil jeg gå nærmere innpå denne tilstanden og dra inn forskning på hva som kan hjelpe for å forebygge og bli kvitt plagene. Deler av artikkelen kan være faglig tung, men nederst vil du finne en rekke praktiske tips du kan ta med deg!

## Hva er beinhinnebetennelse?

Beinhinnebetennelse er en betegnelse som omhandler aktivitetsrelaterte leggsmerter.  Det er spesielt distale 2/3 av leggen som er utsatt og personen opplever ofte smerter og ømhet under og i etterkant av trening. Smertene kommer ofte igjen etter aktivitet og kan være desto verre neste morgen.Man finner oftepalperbare knuter og klumper på innsiden av tibia (skinnbeinet), og utøveren kan oppleve smerte ved plantarfleksjon (nedoverbøyning) av fot og tær**.** Man kan også finnerødhet over innsiden av tibia.

Symptomer på beinhinnebetennelse kan ha flere årsaker. Intense treningsperioder med påfølgende muskelvekst (hypertrofi) og stølhet regnes å være medvirkende til en betennelsestilstand, fibrosering og fortykkelse av bindevevshinnen (fascien) inn mot benhinnen på innsiden av tibia.

Medial traksjonsperiostitt er den medisinske betegnelsen og innebærer: medial = innsiden, traksjon=drag, periost= del av knokkelen, itt=endelse som betyr at det er en betennelse.

Kisner og Colby (2002) deler tilstanden i anterior og posterior beinhinnebetennelse (1):

-   **Anterior beinhinnebetennelse** – overbelastning av tibialis anterior er vanligst. Hypomobilitet i gastrocnemius og soleus, nedsatt styrke i Tibialis anterior og økt pronasjon av foten er relatert til denne type beinhinnebetennelse. Smertene øker med aktiv dorsalfleksjon og ved strekk av muskulaturen ved plantarfleksjon
-   **Posterior beinhinnebetennelse** – stramhet i gastrocnemius/soleus og svak eller inflammasjon i tibialis posterior, sammen med overpronasjon, er assosiert med posterior medial beinhinnebetennelse. Man opplever da smerter under passiv dorsalfleksjon av ankel sammen med eversjon og ved aktiv supinasjon. Muskelutmattelse ved intensiv aktivitet, som løping eller aerobic, kan fremprovosere problemene.

## Anatomi

Leggen består av to bein: Tibia (skinnbeinet) og Fibula (leggbeinet). Hovedmuskelen som bøyer foten oppover (dorsalfleksjon) fester på fremsiden (anteriort) av tibia og heter Tibialis anterior. Muskelen som drar foten nedover og innover heter Tibialis Posterior, og denne har feste på posteriore (bakre) og mediale del ( innsiden) av Tibia. Tibialismusklene sine fibre har feste på periosteum (peri=rundt, osteum= bein) som omgir Tibia. Flere muskler kan være aktuelle å undersøke ved denne tilstanden, men det er disse to sammen med soleus som ofte antydes å ha en sammenheng med beinhinnebetennelse (2, 3, 4)

## Hvordan stilles diagnosen?

Ytterligere undersøkelser er vanligvis ikke påkrevd, men skjelettscintigrafi kan være nyttig ved mistanke om tretthetsbrudd. Røntgen kan også i typiske og kronifiserte tilfeller vise forandringer.

## Differensialdiagnoser

Det er flere tilstander som kan gi samme symptomer som beinhinnebetennelse. Tilstanden må ikke forveksles med compartmentsyndrom eller losjesyndrom, som er en mer alvorlig tilstand med avklemming av blodforsyningen og ekstrem hevelse inne i muskelfascien. Dette skjer dersom trykket i en av de fire muskellosjene er høyere enn blodtrykket som holder blodårene åpne. Dersom dette trykket fortsetter å øke kan det også klemme av større blodårer og nerver, noe som kan medføre kuldefornemmelse, nummenhet og hevelse i fot og legg.

Det er verdt å nevne at muskelspenninger og triggerpunkter i muskulaturen kan gi lignende symptomer som ved beinhinnebetennelse, og dette bør utelukkes før diagnostisering.

En grundig undersøkelse og samtale med terapeut eller lege vil være viktig for å stille diagnosen, sette opp et behandlingsopplegg og etter hvert ha fokus på å forebygge at skaden kommer tilbake.

## Årsak til beinhinnebetennelse

Årsakene til beinhinnebetennelse er likevel ikke fullstendig kartlagt da det finnes mange faktorer som kan medvirke til utviklingen og opprettholdelsen av plagene. Tidlige teorier inkluderte en inflammatorisk respons i periosteum av tibia (vevet som omgir benet) eller en peristoeal traksjonsreaksjon. Traksjonskrefter fra muskulaturen i leggen fører da til smerter og inflammasjon, som igjen har ført til den medisinske termen medial traksjonperiostitt.  Nyere forskning antyder en smertefull stressreaksjon i selve beinet (5)

Det kan være en rekke årsaker til beinhinnebetennelse og de vanligste er ”for mye, for tidlig”, biomekaniske faktorer (unormale bevegelsesmønster) og feilaktig trening. Her vil jeg gjennomgå noen av de viktigste:

## Mulige medvirkende årsaker

Overpronasjon av fot er et av de best dokumenterte risikofaktorene. At innsiden av fotsålen faller innover under stegavviklingen kan medføre et økt drag i bindevevet langs leggen. Videre ser man at kvinner er mest utsatt, samt at man er mer disponert for plagene dersom man har hatt de tidligere (6, 7).

Det er også mulige sammenhenger mellom et endret løpsmønster og utviklingen av belastningsskader. Man har da funnet at et sentralt hælisett, overpronasjon sammen med medialt fottrykk, og en økt lateral fotavvikling. (8)

Det er viktig å undersøke i forhold til plattfot: om foten har en nedsunken (pes planus), normal eller høy (pes cavus) lengde- og tverrbue, og om dette er beinstrukturen eller om dette er den naturlige posisjoneringen grunnet svak muskulatur. På denne måte kan man få et bedre bilde på hvordan foten belastes.  Endret biomekanikk i foten kan påvirke det meste vi gjør, fra tung vektløftning til hvordan man løper. En ubalanse i belastningen av foten med høyere trykk medialt (innsiden) sammenlignet med lateralt (utsiden) har også vist seg som en risikofaktor sammen med livsstilsfaktorer som røyking og dårlig fysisk form (9).

En studie fra 2012 undersøkte risikofaktorer og prognostiske indikatorer for å pådra seg beinhinnebetennelse. Forfatterne undersøkte en rekke mulige faktorer og kom frem til at nedsatt bevegelsesutslag i innadrotasjon i hofte, økt plantarfleksjon og positiv navicular drop test var assosiert med beinhinnebetennelse, samtidig som en høy kroppsmasseindeks (BMI) var assosiert med et lengre  rehabiliteringsforløp (10). En annen studie fra 2009 fant støtter dette, men fant at økt innad-og utadrotasjon i hofte , samt omkrets av legg også var risikofaktorer (11)

Muskulære ubalanser og nedsatt bevegelse, spesielt stramhet i triceps surae (gastrocnemius og soleus) og plantarmusklene er hyppig assosiert med tilstanden. Utøvere med svake triceps surae vil kunne bli sliten tidligere og dette kan lede til endret løpemønster og stress av tibia. Det anbefales også å undersøke ubalanser med hamstrings og quadriceps (4).

Det er altså en rekke mulige medvirkende faktorer til denne tilstanden og man kan verken utelukke eller bekrefte at det er helt spesielle faktorer som er viktigere enn andre.

## Hva er behandlingen?

Først og fremst vil det være hensiktsmessig med en solid undersøkelse for å kartlegge biomekaniske faktorer, muskelkvalitet og styrke. Dette er noe en bør oppsøke profesjonell hjelp for siden det sjelden er hensiktsmessig med selvdiagnostisering. En god terapeut vil kunne hjelpe deg på riktig vei. Det er videre vanlig å dele skadeforløpet inn i en akutt og en subakutt fase.

Hensikten med behandling vil være å redusere smerte og inflammasjon, kartlegge treningsrelaterte og biomekaniske problemer som har ført til skaden, få muskulaturen i området til å fungere hensiktsmessig, og etter hvert returnere til normal aktivitet (4).  Kanskje vil dette også føre til at du utvikler et bedre og mer effektivt løpssteg og dermed en bedre løpsøkonomi.

Det kan naturligvis også være grunn til  å analysere kostholdet, og kanskje spesielt kalsium og D-vitamin som er viktig for benbygningen, men her kan det være mange mulige medvirkende faktorer (4). Fokuset videre vil være på hva man kan gjøre i forhold til behandling og trening.

#### Akuttfase

Man blir ofte anbefalt hvile og is som akutt behandling. Det vil være viktig å ikke gjøre dette for lenge da dette over tid vil føre skadeproblematikken inn i en stillstand der det ikke blir gjort noe med årsaken.

Litteraturen støtter naturlig nok "hvile" som den viktigste behandlingen i akuttfasen. Dette er likevel langt fra ideelt for spesielt idrettsutøvere som trenger å komme raskt tilbake i trening og konkurranse. Avhengig av alvorlighetsgraden vil mann kunne måtte ha avbrekk fra aktiviteten i 2 til 6 uker.

Konservativ behandling vil i de fleste tilfeller være tilstrekkelig for å midlertidig få bukt med plagene, men de har for vane å komme igjen innen kort tid. Denne konservative behandlingen har tradisjonelt bestått av ro og hvile, tøyninger, ising, alternativ trening og NSAID-preparater (non-steroid anti-inflammatory steroids/smertestillende medikamenter som ibux).  I mine øyne vil det være av stor betydning å finne ut årsaken til at plagene kom i utgangspunktet, og da er det gjerne behov for en grundigere undersøkelse av årsaksforhold.

Dersom man ikke gjør noe med årsaken til plagene vil man ha store sjanser for å pådra seg den samme skaden igjen. Ved å kun være i ro vil det ikke nødvendigvis skje noen bedring av årsaken til plagene og utøveren vil innen kort tid kunne være plaget med smerter igjen ved tilbakevending til aktivitet.

#### Subakutt fase

Etter akuttfasen bør målet med behandlingen være å modifisere treningsregimet og kartlegge biomekaniske abnormaliteter. En grundig gjennomgang av holdning, muskelstyrke, muskelkvalitet, biomekaniske forhold under gange og løp, samt analyse av bevegelsesmåte, vil være et godt utgangspunkt. Dette bør gjennomføres av en fagperson med god innsikt i anatomi, fysiologi, biomekanikk og treningslære. Sjekk forøvrig ut [denne artikkelen](http://martinhanstvedt.com/2012/03/01/velge-behandling-eller-behandler/) for noen tips til å finne rett person til dette.

Å nedjustere ukentlig løpsdistanse, hyppighet og intensitet med 50 % vil kunne bedre symptomene uten at man trenger å kutte all aktivitet. Det vil også være fordelaktig å legge løpingen til moderat hardt underlag for økt trykkabsorpsjon som fører til mindre stress for beina.

Det vil i subakuttfasen kunne være hensiktsmessig å legge om treningen til løping i basseng, svømming, bruk av ellipsemaskin eller sykkel for å minske belastningen på beina. Terapeuter kan legge opp en passende rehabiliteringsplan som fokuserer på korrekt teknikk, muskulære ubalanser, gangtrening, og gradvis tilbakevending til aktivitet. Over flere uker kan utøveren gradvis øke treningsaktiviteten innenfor smertegrensen. Aktiviteter som fremprovoserer smerte bør utelukkes i denne perioden.

Det kan også være aktuelt med andre passive behandlingsmetoder som bløtvevsmobilisering, ultralyd, fonoforese (ultralyd brukes til å levere terapeutika til vevet under huden), boblebad, elektrisk stimulering og vektavlastet aktivitet, men disse har ikke vist seg mer effektive enn andre behandlingsmetoder (4)

Det man ofte starter med etter den akutte fasen, og som ofte gir god symptomlindring, er å jobbe med muskelkvalitet gjennom tverrfriksjoner, dry needling (intramuskulær stimulering med nåler) eller trykkbølgebehandling. Dette kan være smertefullt, men vil kunne skape sirkulasjon i vevet og fremme kroppens eget reparasjonssystem.

Behandling for beinhinnebetennelse bør også inkludere korrigering av dysfunksjoner i den kinetiske kjeden. Dysfunksjon i rygg, iliosakralledd og bekken er eksempler på kroppsdeler som kan medvirke til skader i beina. Det er derfor viktig å undersøke hele den kinetiske kjeden.  Målet med manuellterapi vil være å gjenvinne normal bevegelighet, forbedre muskel- og bindevevskvalitet, samt utbedre muskulære ubalanser.

Å korrigere dysfunksjoner relatert til muskel og skjelett kan bedre smerte og generell funksjon, samt virke forebyggende. Det er likevel manglende RCT (randomisert kontrollerte studier) som tar for seg manuellterapi som eneste spesifikke intervensjon for beinhinnebetennelse (12, 13).

Det er verdt å nevne at en kombinasjon av nevnte tiltak kan være nødvendig, men at man må se an hvert enkelt tilfelle for å tilrettelegge optimalt. En kombinasjon av kartlegging av biomekaniske faktorer,  manuelle teknikker, optimalisering av fottøy, tilrettelegging av trening og gradvis tilbakevending til trening er noe mange ser god effekt av.

## Styrketrening

Fokus på å styrke hoftemuskulaturen og det å utvikle en sterk kjernemuskulatur kan også bidra til bedring av tilstanden, samt virke forebyggende. Muskelstyrke og kontroll i rygg, bekken og hofte er viktig for å kontrollere og optimalisere samspillet mellom ”kjernen” og underekstremitetene (beina).

Å utvikle en kjernestabilitet med sterk mage, rygg og hofte kan bidra til et bedre og mer effektivt løpesett og forebygge skader i beina. Spesifikk styrketrening vil være hensiktsmessig, men man bør tilrettelegge dette slik at man unngår øvelser som provoserer skaden ytterligere (4)

Det anbefales å trene kjernemuskulaturen slik at man får med alle de ulike funksjonene til kjernemuskulaturen: Anti-ekstensjon, anti-fleksjon, anti-rotasjon og anti-sidefleksjon. Øvelser som planke, sideplanke, pallof press, landmines og slyngetrening  kan være gode alternativer her.

Litteraturen støtter et daglig regime med utstrekking av leggmusklene og eksentrisk trening av leggmusklene for å hindre utmattelse av musklene.  Man bør også ha fokus på å styrke tibialis anterior og andre muskler som kontrollerer både inversjon og eversjon av foten. [Video](http://youtu.be/4F0V3HMVEfE)

Det er funnet indikasjoner på at utøvere med beinhinnebetennelse mangler utholdenhet i plantarfleksorene i ankel og at rehabilitering bør inkludere trening av disse. Det er usikkert om manglende utholdenhet i disse er en årsak til utviklingen av tilstanden, men det er naturlig å anta at de vil bli sliten tidligere og at dette kan lede til endret løpemønster og stress av tibia. (14)

Aktivering av setemuskulatur vil være svært hensiktsmessig, siden dette fører til at setet gjør en større del av jobben under løpssteget. Setemuskulaturen er hos mange lite aktiv, og det er synd siden den kan bidra med stor kraft og stabilitet. Den er blant annet ansvarlig for å strekke ut i hoften under løping og er også viktig for å stabilisere hele beinet under landing og fraspark.

Når hofteekstensorene ikke bidrar som de skal, vil andre muskler måtte kompensere for å holde oppe farten. Musklene som ofte lider av dette vil være hamstrings (bakside lår), quadriceps (fremside lår), legger, fotmusklene og/eller tibialis anterior. Nedsatt muskelstyrke i hofteekstensorene kan dermed være en medvirkende faktor til blant hamstringsstrekk/overbelastning, kneplager, plantar fasitt og beinhinnebetennelse.

Gode øvelser for setemuskulaturen er seteløft i slynge, [markløft,](http://martinhanstvedt.com/2012/07/02/markloft-hvorfor-og-hvordan/)og sideplanke.

Det anbefales også å undersøke ubalanser med hamstrings og quadriceps (bakside /forside lår), samt utføre proprioseptiv balansetrening . Dette er viktig for optimal nevromuskulær funksjon og kan utføres ved bruk av trening på ett bein, balansepute og lignende (4).

Det oppfordres også til å utføre styrkeøvelser som kan relateres til løpsbevegelsen fremfor å isolere enkeltmuskler. Øvelser som bare trener ett ledd vil i utgangspunktet bli utført sittende, liggende eller stående i et låst bevegelsesmønster som minimerer krav til stabilitet. Dette vil være lite relevant løpsmessig hvor flere ledd belastes samtidig.

Når du løper vil kroppen din måtte sørge for all stabilitet, aktivt eller passivt, da du belaster ett ben om gangen. Dersom du ikke trener de aktuelle bevegelsene som forekommer under løping, vil du kunne være mer disponert for plager i legg, ankel, knær, hofte og korsrygg.

## Løpesett

Ved å analysere løpesettet ved ulike løpshastigheter, samt ved bruk av video og sakte film kan man plukke opp en rekke faktorer som kan medvirke til utvikling av beinhinnebetennelse.

En rekke belastningsrelaterte skader, som beinhinnebetennelse, kan sannsynligvis unngås eller bedres ved å optimalisere løpesett, på samme måte som en vektløfter endrer på løfteteknikk for å unngå skader. Med tanke på hvor mange steg man tar under en løpetur er det naturlig at stadig feilbelastning og et uhensiktsmessig løpesett på sikt vil kunne medføre problemer.

Ved å analysere og endre noe på løpesettet vil man kunne få et mer energiøkonomisk steg som reduserer stress på legg og ankel, noe som igjen vil medføre mindre smerte og sannsynligvis bedre løpstider

Man må huske at det å se noen i en statisk positur, og det å se noen under bevegelse, er to helt forskjellige ting. Analyse av holdning i stående og gående er en ting, men det er vel så viktig å se personen under løping for å få hele bildet. Mange som løper ville nok hatt nytte av å fått noen til å analysere løpesettet. Ved små korreksjoner kan man minske skaderisikoen samtidig som man får mindre energilekkasje, og dermed et mer energiøkonomisk løpesett.

[Video om løpesett](http://youtu.be/lY0nUBRRd10)

Ikke glem at en god oppvarming vil øke sirkulasjonen og elastisiteten i muskulatur og bindevev. Det anbefales da å jobbe med dynamisk oppvarming der man tar for seg øvelser som øker bevegelsen i problemområder, samt aktiverer muskulatur man anser som underaktivert eller særs viktig for den kommende økten.

Det vil spesielt være viktig å se på mobiliteten i ankel. Stramhet i gastrocnemius, soleus og akillessenen vil være med å hindre dorsalfleksjon i ankel (bøye oppover), og vil promotere plantarfleksjon. Dette er svært vanlig blant folk flest, og spesielt løpere. Dette ledsages ofte av en svak tibialis anterior (antagonist). Forskjellen mellom svak (forside) og sterk/stram bakside legg øker ytterligere etterhvert som dette mønsteret fortsetter.

Ofte vil man kunne se dette under knebøy der vekten blir lagt på forfoten, mens hælene mister kontakten med underlaget.\
Når man løper og treffer underlaget vil tibialis anterior mangle kraft til å eksentrisk kontrollere plantarfleksjonen (bøye nedover). Dermed vil muskelfibrene strekkes utover tåleevnen ettersom de ikke er sterke nok til å holde igjen bevegelsen. Det skapes da små rupturer (rifter) i muskelfibrene som over lang tid og repetetiv bevegelse vil kunne skape irritasjon og smerte i leggen.

## Skotøy

Flere har funnet at riktig fottøy kan være med å redusere forekomsten av beinhinnebetennelse. Såler som korrigerer feilstillinger i fot kan redusere kreftene gjennom beina og dermed virke forebyggende.

Det anbefales også å skifte ut løpesko hver 400-800 km. Det er mulig at individer med biomekaniske problemer i fot med fordel kan benytte ortoser, og det kan være tilstrekkelig med standardsåler for pes planus (plattfot) og overpronasjon.

En samlestudie sammenlignet støtdempende innleggssåler, hælpute av skum, tøyning av akillessenen, fottøy og tilpasset løpeprogram. De fant at støtdempende innleggsåler hadde en lovende effekt, men klarte ikke å påvise noen enkelttiltak som forebyggende mot beinhinnebetennelse (15). En annen studie undersøkte effekten av innleggsåler og tøyning av leggmuskulatur hos personer med beinhinnebetennelse. Det hadde en viss effekt, men forfatterne presiserer at dette bare bør være en del av et sammensatt rehabiliteringsprogram (16).

Innleggssåler eller tilpassede sko kan til en viss grad korrigere overpronasjon og valgusstilling i kne (kalvbent), og gi god demping. Dette kan fungere som en del av totalbehandlingen, men den vil ikke nødvendigvis være løsningen i seg selv. Det vil i de fleste tilfeller være vår belastning av kroppen og hvordan vi bruker den som vil være årsaken, med mindre det er skjedd et direkte traume.

Når det er sagt kan en tilpasset såle som korrigere en eventuell feilstilling under belastning kunne bidra til å minske stressbelastning på leggen. Jeg har selv hatt god erfaring med å benytte tilpasning av såler som en del av en komplett behandling.

## Trykkbølgebehandling

Radial trykkbølgebehandling er en serie av høyenergetiske trykkbølger som brukes på behandlingsområdet. I 2011 fant man at et tilpasset løpsprogram sammen med trykkbølgebehandling fikk personer med beinhinnebetennelse fullstendig rehabilitert etter omtrent 2 måneder, mens de som bare hadde et tilpasset løpsprogram brukte omtrent 3 måneder (17).

En annen studie fra 2010 støtter også trykkbølgebehandling som en effektiv behandlingsmetode for beinhinnebetennelse da de sammenlignet dette med et standardisert hjemmetreningsprogram (18). Svakheter med disse studiene er mangel på blinding av deltagerne, altså at deltagerne visste om de fikk behandling eller ikke, samt andre metodologiske svakheter ved gjennomføringen av studiene.

## Hvordan er prognosen?

De fleste blir bra ved hvile og omlegging av treningen. Tilstanden har likevel en tendens til å komme tilbake, og man må ofte ta hensyn til dette over lang tid. Noen får kroniske plager som forhindrer aktiv idrett. Dette er svært synd og kunne sannsynligvis vært unngått i mange tilfeller med riktig behandling og progresjon.

Prognosen er generelt god dersom pasienten følger et konservativt behandlingsopplegg med nedtrapping av smerteutløsende aktivitet og sko-/såletilpasning. Kirugisk behandling gir bedring av symptomer hos 80-90% av pasientene, men toppidrettsutøvere kan regne med å være borte fra idrett på høyt nivå i inntil et halvt år avhengig av alvorlighetsgrad (19).

## Hva kan du gjøre selv?

Først og fremst bør du naturlig nok unngå de aktivitetene og bevegelsene som gir smerter. Forsøk ulike treningsformer som gir mindre belastning som svømming, løping i vann og sykling. Det er viktig at du ikke begynner igjen med full aktivitet selv om du har hatt noen smertefrie dager.

### Praktiske tips

Dersom du har eller er i fare for å få beinhinnebetennelse:

-   Jobb med vevskvalitet i fot, legg, lår og hofte (hele den kinetiske kjeden)
-   Kartlegg eventuelle biomekaniske risikofaktorer som nevnt tidligere
-   Kartlegg eventuelle risikofaktorer relatert til løpesett og muskulære ubalanser
-   Nedjuster løpsdistanse og øk denne gradvis etter hvert som du er symptomfri
-   Bruk fottøy som er tilpasset din fot
-   Løp minst mulig på hardt underlag, asfalt og lignende
-   Reduser eller legg om treningen dersom plagene melder seg

### Egenmassasje

Det kan være nyttig å jobbe med vevskvaliteten og Dean Somerset viser i denne videoen hvordan man kan jobbe med Tibialis posterior ved hjelp av egenmassasje. [Video](http://youtu.be/Vzm3NtGC-jg)

Lignende teknikker kan benyttes for øvrige leggmuskler og muskulatur i den kinetiske kjeden. Det anbefales likevel å ta kontakt med kvalifisert personell dersom du anser problemet som noe du ikke selv kan utbedre på egenhånd

## Oppsummering

Det er per dags dato begrenset evidens som støtter spesifikk behandling og intervensjoner for beinhinnebetennelse.\

Likevel støtter flere studier hvile, is og smertestillende i akuttfasen. Det blir også anbefalt å modifisere trening, å tøye og styrke muskulatur i beina, benytte passende fottøy og såler, samt manuellterapi for å korrigere biomekaniske dysfunksjoner. Deretter anbefales det å gradvis returnere til aktivitet.

Det er behov for ytterligere forskning på dette området (som alle andre områder) og det blir spennende å se hva fremtidens forskere finner ut. Det vil da være aktuelt å undersøke større populasjoner og da i hovedsak løpsutøvere som er spesielt disponert.

Forhåpentligvis har denne artikkelen gitt et innblikk i hvilke faktorer som kan spille inn, og ikke minst gitt deg noen tips om hva man kan fokusere på som forebyggende og behandlende tiltak

##### Har du spørsmål om beinhinnebetennelse? Fyr løs i kommentarfeltet!

Referanser

1.  Kisner og Colby (2002) ***Therapeutic excercise**.* 5^th^ ed. E. A. Davis Company: Philadelphia.
2.  Beck BR. **Tibial stress injuries. An aetiological review for the purposes of guiding management.** Sports Med. 1998 Oct;26(4):265-79.
3.  Detmer DE. **Chronic shin splints. Classification and management of medial tibial stress syndrome**. Sports Med. 1986 Nov-Dec;3(6):436-46.
4.  GalbraithM.R,  Lavallee M.E . **Medial tibial stress syndrome: conservative treatment options**, Curr Rev Musculoskelet Med. 2009 September; 2(3): 127–133. Published online 2009 October 7. doi:  10.1007/s12178-009-9055-6
5.  Tweed JL, Avil SJ, Campbell JA, Barnes MR. **Etiologic factors in the development of medial tibial stress syndrome: a review of the literature.** J Am Podiatr Med Assoc. 2008 Mar-Apr;98(2):107-11.
6.  Bennett JE, Reinking MF, Pluemer B, Pentel A, Seaton M, Killian C. **Factors contributing to the development of medial tibial stress syndrome in high school runners**. J Orthop Sports Phys Ther. 2001 Sep;31(9):504-10.
7.  Reshef N, Guelich DR. **Medial tibial stress syndrome.** Clin Sports Med. 2012 Apr;31(2):273-90. doi: 10.1016/j.csm.2011.09.008.
8.  Willems T.M., De Clercq D., Delbaere K., Vanderstraeten G., De Cock A., Witvrouw E. **A prospective study of gait related risk factors for exercise-related lower leg pain, Gait & Posture**, Volume 23, Issue 1 , Pages 91-98, January 2006
9.  Sharma J., Golby J., Greeves J., Spears I.R. **Biomechanical and lifestyle risk factors for medial tibia stress syndrome in army recruits: A prospective study, Gait & Posture**, Volume 33, Issue 3 , Pages 361-365, March 2011 
10. Moen MH, Bongers T, Bakker EW, Zimmermann WO, Weir A, Tol JL, Backx FJ. **Risk factors and prognostic indicators for medial tibial stress syndrome.** Scand J Med Sci Sports. 2012 Feb;22(1):34-9. doi: 10.1111/j.1600-0838.2010.01144.x. Epub 2010 Jun 18.
11. Moen MH, Tol JL, Weir A, Steunebrink M, De Winter TC. **Medial tibial stress syndrome: a critical review.** Sports Med. 2009;39(7):523-46. doi: 10.2165/00007256-200939070-00002.
12. Wilder RP, Sethi S. (2004) **Overuse injuries: tendinopathies, stress fractures, compartment syndrome, and shin splints.** Clin Sports Med. 2004 Jan;23(1):55-81, vi.
13. Karageanes S. **Principles of manual sports medicine**. Philadelphia, PA: Lippincott, Williams and Wilkins; 2005. pp. 467–468.
14. Madeley LT, Munteanu SE, Bonanno DR**. Endurance of the ankle joint plantar flexor muscles in athletes with medial tibial stress syndrome: a case-control study**. J Sci Med Sport. 2007 Dec;10(6):356-62. Epub 2007 Mar 1.
15. Thacker SB, Gilchrist J, Stroup DF, Kimsey CD. (2002) **The prevention of shin splints in sports: a systematic review of literature.** Med. Sci. Sports Exerc., Vol. 34, No. 1, 2002, pp. 32– 40.
16. Loudon JK, Dolphino MR. **Use of foot orthoses and calf stretching for individuals with medial tibial stress syndrome**. Foot Ankle Spec. 2010 Feb;3(1):15-20. doi: 10.1177/1938640009355659. Epub 2009 Dec 18.
17. Moen MH, Rayer S, Schipper M, Schmikli S, Weir A, Tol JL, Backx FJ. **Shockwave treatment for medial tibial stress syndrome in athletes; a prospective controlled study.** Br J Sports Med. 2012 Mar;46(4):253-7. doi: 10.1136/bjsm.2010.081992. Epub 2011 Mar 9.
18. Rompe JD, Cacchio A, Furia JP, Maffulli N. **Low-energy extracorporeal shock wave therapy as a treatment for medial tibial stress syndrome**. Am J Sports Med. 2010 Jan;38(1):125-32. doi: 10.1177/0363546509343804. Epub 2009 Sep 23.
19. Grøntvedt T. I: **Idrettsskader.** Bahr R, Mæhlum S (red.). Medial traksjonsperiostitt. Gazette bok, 2002.
