---
title: "Belgfrukter, en undervurdert matvaregruppe?"
author: "Eivind Eliasson"
date: 2014.01.09
---

I Norge spiser vi ikke all verden med belgfrukter foruten peanøtter (som mange feilaktig tror er en nøtt). I sydligere strøk er de derimot en viktig del av kostholdet og brukes mye til middager, i salater og lignende. I denne artikkelen vil jeg slå et slag for belgfruktene og argumentere for hvorfor de bør få en større plass i kostholdet ditt.

## Generelt om belgfrukter

#### Fordeler

-   De er proteinrike
-   De har lav [glykemisk belastning](brokenlink/mat-og-blodsukker-gi-eller-gb/)
-   De inneholder mye [fiber](naeringsstoffer/fiber.qmd)
-   De inneholder mye [vitaminer og mineraler](../naeringsstoffer.qmd)

#### Ulemper?

-   I et tradisjonelt norsk kosthold finner man ikke mange retter hvor de passer bra inn
-   Kan gi mye luft i magen hos enkelte siden de inneholder mye [oligosakkarider](irritabel-tarm.qmd)
-   Noen mineraler kan ha lav biotilgjengelighet grunnet høyt innhold av fytat.
-   [Proteinkvaliteten](brokenlink/proteinkvalitet/) er ikke den høyeste, men dette er for de aller fleste ikke et problem ettersom ingen baserer seg på belgfrukter som eneste proteinkilde.
-   Noen belgfrukter inneholder giftstoffer som kan fjernes med riktig tilberedning.

Felles for nær sagt alle belgfrukter er at de inneholder mye protein. Som et eksempel inneholder ubehandlede peanøtter og tørkede linser over 30gram protein pr 100 gram. Soyabønner inneholder hele 36g protein per 100g, og er dermed en av de aller mest proteinrike matvarene som finnes. Ved siden av et høyt fiberinnhold gir dette en god metthetsfølelse. Fettinnholdet og karbohydratinnholdet varierer mye, der peanøtter er svært fettrike mens nyrebønner svært fettfattige.

## Hvordan tilberede belgfrukter?

Et stort problem med belgfrukter er at mange ikke vet hvordan de bør tilberedes. Om de tilberedes på en god (og dessverre ofte tidkrevende måte) så blir problemene med luft i magen og biotilgjengeligheten på mineraler kraftig forbedret.

Riktig tilberedning innebærer for de fleste typer bønner og linser at man bløtlegger de, gjerne minst et døgn i vann med litt sitronsyre og salt i og siler av laken og skyller de godt etterpå.  De du finner på boks i butikken som røde linser og nyrebønner er ferdigbehandla på denne måten, mens tørkede varianter bør tilberedes slik selv. Etter at de har ligget i lake bør de kokes, gjerne minst 20 minutter, og kokevannet bør siles bort og belgfruktene skylles. Med peanøtter holder det å riste dem (middels temperatur på stekeplate i ovnen). Disse teknikkene medfører at inneholdet av trøblete karbohydrater som kan gi luftplager synker kraftig.

Antinæringsstoffer og enkelte giftstoffer reduseres kraftig eller nøytraliseres med skikkelig tilberedning. Enkelte positive stoffer som fenoler og til en viss grad proteiner reduseres også, men det er verdt det. Lektiner som finnes i belgvekster er omdiskuterte. Noen kan være svært giftige( som ricin fra castorbønner), mens andre kan være ganske giftige ved moderat inntak som fra nyrebønner. Imidlertid vil koking uskadeliggjøre lektinene. Jeg ville nok likevel ikke spist castorbønner uansett.

I en studie (1) som undersøkte hva som skjer med næringsinnholdet når peanøtter varmebehandles fant forskerne flere interessante funn.Uheldige bakterier som varianter av E-coli ble eliminert, muggsopp forsvant, oksalatinnholdet ble halvert, fytinsyre ble redusert til under 1\\3, mens karbohydratnivået og proteinnivået gikk noe ned. Sistnevnte kan med første øyekast se ut som en negativ effekt, men dette kan nok først og fremst tilskrives at vanninnholdet øker.

En annen studie (2) så på endringer ved riktig tilberedning av Jackbønner (bløtlegging etterfulgt av koking). Negative forbindelser som trypsinhemmere og tanniner ble redusert med ca 2\\3,  oligosakkaridene ble redusert med over 2/3 , mens L-dopa og fenoler ble redusert med over 50%.

## Oppsummering

Belgvekster er svært billige og har etter min mening en alt for liten plass i det norske kostholdet. De har fått et dårlig rykte som i stor grad skyldes at folk ikke kan eller tar seg tid til å tilberede dem på riktig måte. De er generelt gode kilder til proteiner og fiber og gir høy metthetsfølelse, noe som er bra både for behandling og forebygging av overvekt. De gir en lav glykemisk belastning, noe som gjør dem egnet for diabetikere og personer med metabolsk syndrom.

Belgfrukter har mange bruksområder om man er villig til å gjøre små endringer i matvanene, om man tilbereder dem riktig. Hva med å slenge i en boks nyrebønner i den meksikanske gryta, eller i salaten? Eller en boks linser i grønnsakssuppa? Dette er dessuten en fin måte å øke inntaket av grønnsaker på. Personlig er jeg svært glad i mange typer belgvekster så hele denne artikkelen er nok preget av litt bekreftelsesbias, men jeg håper jeg kanskje kan åpne øynene for en undervurdert matvaregruppe som i det norske kjøkken per i dag bare består av ihjelkokte grønne erter og polly peanøtter.

1.  <http://www.jmbfs.org/wp-content/uploads/2012/12/jmbfs-0192-Adjou.pdf>

2.  <http://www.ifrj.upm.edu.my/18%20(03)%202011/(15)IFRJ-2010-260.pdf>
