---
title: "Belte til styrketrening: Hva, hvorfor, hvordan, når og hvilket"
author: "Asle Bøe"
date: 2014.04.17
---

Et skikkelig belte kan gi deg noen titalls kg på maksløft i knebøy og markløft.Det kan også gjøre løft med vekter over 80% raskere, mer stabile og effektive. Det er mange myter om hva et belte skal gjøre og hvordan det virker, og jeg håper å avlive noen av dem her uten å skape for mange nye.

## Hva

Det finnes flere typer belter til styrketrening.

-   Varmebelter (kan være bra for lokal smertelindring og varming, men hjelper ikke direkte med å løfte mer)
-   Belter i syntetisk stoff  (styr unna de fleste av disse, de med jevn diameter med skikkelig spenne som er uelastisk kan brukes)
-   Lærbelter med jevn diameter og metallspenne/leverspenne ( ja! )
-   Lærbelter som  er tykke bak, og smalere på siden og foran ( i de fleste tilfeller: styr unna )

## Hvorfor

Belte brukes hovedsakelig av tre grunner i forbindelse med styrketrening.

1:  Løfte mer og mer effektivt, økt stabilitet\
2:  Redusert skaderisiko, "støtte ryggen"\
3: For å gi varme til korsryggen, lindre stølhet og smerte

Det er  den første grunnen jeg skal fokusere på selv om [**de fleste nevner skadeforebygging**](http://www.ncbi.nlm.nih.gov/pubmed/12930176) som årsak til at de bruker belte. og bruker det til submaksimal løfting.

Beltet gjør deg istand til å løfte mer i øvelser der ryggstyrken og stabiliteten i overkroppen er en begrensende faktor. I hovedsak gjelder det frontbøy, knebøy og markløft. Belte kan også brukes til andre løft, som stående og sittende press, benkpress, stangroing og andre frivekstøvelser, men overføringsverdien er ikke like direkte siden det sjelden er svikt i ryggen som begrenser hvor mye vekt du håndterer her. Ved å bruke belte vil du kunne løfte mer enn du kan uten beltet med maksimale vekter, eller du vil kunne holde ryggen bedre ved lengre submaksimale serier.

## Hvordan

Buktrykk oppstår når musklene rundt luften i buken og brystkassen komprimeres av at musklene trekker seg sammen rundt den. Dette kalles intra-abdominalt trykk.. Vev komprimeres også av disse sammentrekningene, og [**resultatet blir en mer stabil midje**](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2949466/) som motstår fleksjon, eller krumming av ryggsøylen bedre sammen med ryggstrekkerne og multifidene. En enkel måte å  se det på er å se på magemusklene som en ballong med luft inni og brystkassen som en eske. Dersom du fyller [**ballongen med luft og komprimerer den**](http://www.ncbi.nlm.nih.gov/pubmed/10619094) står den mot mer trykk enn om det ikke er luft i den.

Magemusklene , bortsett fra transversus abdominis drar ryggen inn i fleksjon eller mot å bli krum, og for å motstå det aktiveres ryggstrekkerne og multifidene blant annet. Nå blir ryggraden dradd i to retninger - resultatet blir at den stabiliseres.[ **Muskelsammentrekningene gjør også at kompresjonskreftene**](Effect of a stiff lifting belt on spine compression during lifting.) øker.

Forskningen på bruk av vektbelte er ikke umiddelbart overførbar til maksimalløft for veltrente personer, siden det er forsket lite på disse. Forsøk som av McGill og kollegaer med [**vekter på 70-90 kg reflekterer**](http://www.ncbi.nlm.nih.gov/pubmed/2141312) dårlig kreftene i løft på flere ganger kroppsvekt. Ideelt sett skulle vi hatt studier på folk som faktisk løfter, med beltene som brukes av dem og med en representativ bevegelsesbane. Det vil si løft til godkjent IPF-dybde i styrkeløft med maksimale vekter, stiv stang og jernskiver og knebøy gjort av vektløftere med vektløfterstang og bumperplates til sin vante dybde.

En studie utført av [**Attila et al**](http://www.ncbi.nlm.nih.gov/pubmed/11710410) er mer relevant. Her ble deltagernes utførelse med 90% av 1 RM målt, og beltet som var brukt var et belte med jevn diameter og en tykkelse på 8 mm. Dybden var imidlertid mer tvilsom - til lårene var parallelle med bakken. Deltagerne løftet raskere med belte enn uten og bevegelsesbanen ble lengre - men kun med 5% og med en økning på rundt 25% i anteriorforskyvning av stangen i bunn. Samme [**anteriorforskyvning har vært sett i andre forsøk.**](http://europepmc.org/abstract/MED/2304406/reload=0;jsessionid=qU85W4ZfTaTr8PEFKWJv.12)En slik stangbane kan være ineffektivt, og det er mulig deltagerne fremprovoserte dette gjennom å kontrollere den eksentriske fasen dårligere på grunn av beltet. I serier på flere [**repetisjoner med submaksimale vekter**](http://www.ncbi.nlm.nih.gov/pubmed/1533266) har raskere eksentrisk og konsentrisk, altså senke- og løftefase vært sett utover i serien.

Det er mange som bruker beltet feil - bare tar det på og løfter. Skal du få god effekt må beltet strammes, og du må bruke det aktivt for å få et heftig buktrykk.

Slik gjør du:

-   Pust dypt inn, hold pusten
-   Trekk sammen magemusklene mens brystet fremdeles er opp, ikke "trekk ned" brystet
-   Spenn dem "ut" mot beltet uten å blåse opp magen, hold på trykket

Et belte kan bidra til buktrykk både gjennom at magemusklene spennes ut mot det og gjennom at selve beltet er så stramt at det komprimerer luft og vev rundt midjen. Dette vil gjøre midjen , ryggraden og brystkassen mer stabil.

#### Kompresjons- og skjæringskrefter

En vanlig feiltolkning av kreftene som påvirker ryggsøylen er å kategorisere alt som "belastning". Ryggraden utsettes i hovedsak for to typer krefter i et knebøy og et markløft: Kompresjon som følge av vertikal belastning og muskeldrag som presser ryggvirvlene sammen og skjæring som følge av krefter som virker horisontalt og fører til et dreiemoment.

Når vekten hviler på ryggen i utlåst posisjon er ryggen i maksimal kompresjon, etterhvert som overkroppens vinkel reduseres økes skjæringskreftene og dreiemomentet. Ryggraden tåler kompresjon svært godt, og det kan argumenteres for at  ryggraden har tilpasset seg kompresjonskrefter i stor grad gjennom sirkulær brusk i mellomvirvelskivene og et klossesystem av knokler som er svært bestandig mot å bli trykket sammen.

Skjæringskrefter er imidlertid mer problematiske, og det blir vanskelig å gjennomføre et løft om bryst- eller korsryggen går inn i ukontrollert fleksjon. Enkelte løfter bevisst med fleksjon i brystryggen, men det balanseres av større ryggmuskler enn de fleste kan bygge uten apotekbesøk.

I styrkeløft er belte tillat utstyr i konkurranse både med og uten utstyr. Vetkløftere bruker aldri tykke lærbelter i konkurranse av åpenbare grunner. Prøv et par rykk og støt med et belte som er 13 mm og har en stor metallspenne og du vil fort finne ut hvorfor. I styrkeløft gir beltet mer umiddelbar overføringsverdi gjennom å føre til bedre kraftoverføring fra ben og hofter til stangen gjennom økt stabilitet og et mer effektivt løft gjennom at fleksjon motvirkes.

Skal beltet brukes til maksløft bør en også trene med belte. Akkurat når beltet skal på er det vanskelig å gi noen fasit på - å gjøre det på 70% av maksen til noen som akkurat har begynt å trene grenser mot meningsløst mens å gjøre det på 70% av maksvekten til noen som råbøyer 300 kg gir mer mening og er mer konkurransespesifikt.

Dersom du kun trener styrketrening vil et belte kunne gjøre at du blir mer stabil og håndterer tyngre vekter i både knebøy og markløft grunnet de tidligere nevnte faktorene. Et belte skal gjøre det lettere å holde gode posisjoner, ikke bli brukt som forsterking mens du løfter så stygt du bare klarer. Et belte vil kunne gjøre at du kan trene bena hardere siden ryggen ikke blir det første som svikter. Et belte vil også kunne tillate at mer vekt brukes med bedre teknikk, noe som i mine øyne veier opp for et eventuelt redusert muskelarbeide av eksempelvis ryggstrekkerne.

Et belte er på ingen måte en nødvendighet for de aller fleste som kun trener styrke, men for de som vil bli virkelig sterk kan et belte være et godt hjelpemiddel for å løfte mer og å styrke et potensielt svakt ledd i kjeden som begrenser hvor mye vekt du kan flytte. Det er ikke uvanlig at bena og hoftene er sterkere enn ryggen.

La beltet sitte der på magen du klarer å få best trykk og stabilitet. Eksperimenter litt med plassering. Enkelte velger å bruke beltet svært langt oppe i markløft , da er det mer for å støtte midt- og brystryggen.

## Når

Et belte er på ingen måte et must ved all styrketrening.

Når vektene begynner å nærme seg 80-85% i markløft, knebøy og frontbøy kan det være fornuftig å få på beltet.

Dersom du legger opp treningen til at du skal gjøre maksløft med belte bør også oppkjøringen mot løftet eller konkurransen gjøres med belte slik at det blir så konkurransespesifikt som mulig.

## Hvilket

Velg et solid lærbelte som er rundt 11-13 mm tykt og har metallspenne. Beltet bør ha jevn diameter rundt hele.

## Personlig erfaringer og vanlige spørsmål

Jeg begynte først å trene med belte fast for rundt et år siden. Jeg prøvde det sporadisk, men likte det aldri og følte ikke jeg trengte det. Først flere år etter jeg bøyde 200 kg for første gang begynte jeg å eksperimentere med beltebruk i knebøy og markløft. I knebøy var det uproblematisk, og kjentes veldig fint og stabilt.

Den lille svikten i brystryggen som hadde en tendens til å komme på maksvekter ble merkbart mindre. I markløft var det ikke fullt så enkelt, beltet kom i veien i bunn og glapp litt opp slik at det ikke støttet i det hele tatt. Med å plassere beltet litt lengre oppe løste det seg, og det tyngste markløftet jeg har tatt på trening, 250 kg gikk veldig greit.

Nå bruker jeg belte innimellom på maksvekter i knebøy og markløft og trives veldig godt med det. Bruk litt tid på å finne en plassering som kjennes stabil og effektiv ut gjennom hele løftet, og du kan nyte veldig godt av et belte. Ikke vær redd for å stramme til skikkelig godt heller, eller la noen andre hjelpe deg å dra det til. Et løst belte har ingenting for seg.

#### Hvor mye mer kan jeg løfte i markløft og knebøy med belte?

Det vil variere. Studiene over indikerer potensiale for raskere og mer effektive løft, og evnen til å øke stabiliteten så ryggens evne til å støtte vekt bedres. Hvor mye dette utgjør, i tillegg til eventuelle psykologiske effekter av å bruke belte vil variere i hvert enkelt tilfelle.

Noen sverger til at beltet gir dem 10% i knebøy og markløft, noen føler de får mer i markløft enn knebøy, noen mer i knebøy enn markløft mens andre synes det føles bra uten at de tilskriver beltet noen ekstra kg. Folk sprer seg over hele skalaen,  og kroppsfasong, løftestil og type belte vil spille inn. En ting er sikkert, potensialet for å løfte mer er der.

#### Er ikke belte juks?

Dette er en veldig vanlig innvending. En vil ikke løfte med belte fordi det hjelper og fordi en kan løfte mer, derfor føler en at en jukser.

I styrkeløft er det veldig enkelt - belte er tillatt, altså er det ikke juks. På trening vil jeg foreslå at du tenker mer på om det du gjør er effektivt for målsetningen din enn om du får gymcredz for det. Lar belte deg løfte tyngre maksvekter mer effektivt og du får bedre treningseffekt er det viktigst. Om du må presisere at "jeg løfter 200 kg i knebøy, men det er ass to grass, uten belte, truse, med forskjellig farge på sokkene og etter en todagers" mangler du litt perspektiv.

Belte hjelper deg til å løfte mer ved å styrke et potensielt svakt ledd, men er ikke juks. Sammenligner du løftene dine med noen for å se hvem som er kongen av racket kan du finne på hvilke regler du vil.

#### Gjør ikke belte at "kjernemusklene" blir svakere?

Nei. Bruker du beltet som anbefalt, på vekter på rundt 85% og oppover gjør du fremdeles størstedelen av treningen din uten belte. Samtidig tyder studier på at aktiviteten til bukmusklene øker ved bruk av belte når du spenner dem ut mot det og får mottrykk.

Gjør du baseløft, planker, sideplanker, utrulling med magehjul, benhev og senking på en fornuftig måte får den stabiliserende muskulaturen rundt og i midjen og overkroppen mer enn nok stimuli til å bli sterk.

Beltet kan også føre til økt aktivering av magemusklene. Det er ikke noe du tar på som overtar alt arbeidet for musklene. Bruk av belte på maksvekter vil neppe gjøre deg svak, heller hjelpe deg med å håndtere tunge vekter mer effektivt. Dersom du av en eller annen grunn alltid skulle brukt belte i baseløft kan det godt være du ville fått problemer i en overgangsperiode om du sluttet med det.

#### Hjelper belte for å unngå ryggskader?

Siden det er en av hovedgrunnene til at folk bruker det må det da være noe i det? Ikke nødvendigvis, og tenker en slik begår en en [**vanlig tankefeil.**](http://asleboe.no/tankefeil-og-logiske-feilslutninger/)Dette er det meg bekjent ikke studert direkte, så jeg må svare på antagelser basert på momentene over.

Et belte kan være med på å unngå unødig fleksjon i ryggraden, øke kompresjonskrefter og det intra-abdominale trykket. Jeg vil imidlertid, utelukkende basert på observasjon si at slik et belte brukes av de fleste som trener på et kommersielt senter brukes det ikke optimalt.

Styrketrening er i utgangspunktet en veldig trygg treningsform. Om et belte gjør den enda tryggere kommer an på bruken av beltet vil jeg tro - samtidig vet vi at når det gjelder bindevevsskader i ryggen har det et sterkt genetisk komponent . Dersom beltet gjør at du blir mer stabil og løfter med bedre teknikk vil jeg tro beltet kan redusere sjansen for slitasjelignende skader. De eneste studiene jeg vet om på bruk av belte for å redusere skaderisiko er på bagasjekastere, og det blir således ikke helt relevant.

#### Hvilket belte bør jeg kjøpe, og hvor?

Ideelt sett prøver du beltet først. Velg ett som er 11-13 mm tykt, er av lær og har metallspenne. Velg et med jevn diameter rundt hele siden disse beltene gir bedre støtte enn belter som smalner inn foran og er bredere bak. De gjør det lettere å få et godt buktrykk. Enkelte foretrekker vektløfterbelter og smalere belter, spesielt om de er vertikalt utfordret.

Ulempen med et lærbelte er at det kan føles veldig stivt og hardt som nytt. Det mykner med bruk. Belter i andre materialer som ikke gir etter, som nylon kan også brukes.

Svenske [**Wahlander**](http://www.wahlanders.se/webbutik/katalog/product_info.php?cPath=22_31&products_id=79) har mange gode belter som er solide og lette å stramme. [**Titan**](http://www.titansupport.com/products/powerlifting-belts/texas-powerlifting-belts) har også mange gode belter.

#### Jeg prøvde belte en gang, og det var vondt! Hva kan jeg gjøre for å unngå det?

Bortsett fra å være mindre pysete: Nye lærbelter vil være stive. De blir bedre etter et par økter. Du kan gjerne bruke beltet på lettere belastninger og bygge opp toleranse og bli vant til det. Det kan også være en fordel at det ikke er maksvekter på når du skal finne ut hvordan beltet ligger best de første gangene. Vi har forskjellige midjemål, avstander fra hoftekam til ribben og preferanser til hvor det kjennes best støtten kommer, og hvor det ikke blir ubehagelig.

Det er alltid en fordel om det går an å prøve forskjellige beltebredder på forhånd, og å kjenne på et belte som er brukt endel for å se hvordan det vil være når det ikke er nytt.

#### Er det noe jeg kan gjøre for å mykne det?

Bortsett fra å gå med det mye i starten kan du godt rulle det opp begge veier - med utsiden/innsiden ut. Enkelte bruker mer brutale måter som også fungerer, men ikke noe jeg vil anbefale.
