---
title: "Hvordan bli raskere"
author: "Torbjørn Lysne"
date: "2012.07.14"
---

Å løpe er en aktivitet nesten alle kan gjøre. Noen er av den raske typen, mens andre er av den mer utholdende typen. Det som avgjør hvilken løpetype du er avgjøres allerede ved de genene du tildeles ved fødselen, men heldigvis kan alle bli raskere. Les videre for å få noen tips til å øke hurtigheten.

## Muskelfibre og trening

Uten å gå nærmere inn på hvordan musklene fungerer vil jeg først nevne at vi har tre forskjellige typer muskelfibre i kroppen. De ulike muskelfibrene har ulike egenskaper, og de vil derfor ha en innvirkning på evnen til hastighet, utholdenhet og muskelstørrelse. Oversikt over muskelfibre og deres virkning:

|             |               |            |           |
|-------------|---------------|------------|-----------|
| Egenskap    | Type I        | Type IIa   | Type IIx  |
| Hurtighet   | Dårlig        | Ganske god | Svært god |
| Styrke      | Ganske dårlig | Ganske god | Svært god |
| Utholdenhet | Svært god     | Ganske god | Dårlig    |

Når det gjelder mengdeforholdet av muskelfibre er dette medfødt. Man kan altså i svært liten grad gjøre om noen typer til andre (Type IIx kan gå over til type IIa). Dette er svært individuelt og for å bli raskere gjelder det å jobbe med de type IIx-fibrene du har fått utdelt av mor og far. Nedenfor kommer noen tips til hva du kan gjøre for å oppnå dette.

## Akselerasjon og toppfart

Akselerasjon kan defineres som en hastighetsforandring pr. tidsenhet, mens hurtighet kan defineres som musklenes evne til å skape størst mulig akselerasjon.

Før du leser videre kan det være greit å vite om det er en bedre akselerasjon eller økt toppfart du ønsker å oppnå? Disse kvalitetene går selvsagt litt hånd i hånd da begge har fokus på typeIIx-fibre, men det er likevel noen vesentlige forskjeller når det kommer til hvilken muskulatur som er mest aktiv. I akselerasjonsfasen av et løp er muskelstyrken på fremsiden av lårene en ledende muskelgruppe, mens i toppfart bruker man mer baksiden (lår- og setemuskulatur) for å opprettholde/oppnå fart. Andre viktige muskelgrupper for økt akselerasjon og/eller toppfart er hoftebøyerne og bakside legg.

## Øvelser

Jeg vil nå nevne en del øvelser som vil kunne hjelpe deg til å bli raskere. Løpsteknikken er selvsagt svært avgjørende for hvor fort du vil klare å løpe, men i denne gjennomgangen vil fokuset være rettet på øvelser som vil kunne bedre de fysiske forutsetningene for å bli raskere.

#### I styrkerommet

Når man skal løpe fort er hovedmålet å utvikle stor kraft på kort tid. For å skape best mulig forutsetninger for å klare dette er viktig å være sterk i forhold til sin egen kroppsvekt – altså ha en god *relativ styrke*. Det er også typisk å trene med relativt høy belastning og få repetisjoner for å bruke mest mulig av de sterke og raske muskelfibrene.

Ved siden av å øke maksimal styrke i tidligere nevnt hovedmuskulatur for løping, vil det også være en stor fordel å trene eksplosive øvelser for å trigge de raske IIb-fibrene. Her har du noen øvelser som kan hjelpe deg på veien til å bli raskere:

For økt maksimal styrke:

-   Knebøy – 3-4 x 1-8 RM

-   Markløft – 3-4 x 8 RM

-   Bulgarsk utfall - 3-4 x 5-8 på hvert bein ([video](http://www.youtube.com/watch?v=1CvEs-TOIKM))

-   Seteløft/Glute bridge m/vekter – 3-4 x 5-10 RM ([video](http://www.youtube.com/watch?v=03rSrFdq9P0))

-   Hip thrust – 3-4 x 5-10 RM ([video](http://www.youtube.com/watch?v=A8nFGuY77CE))

-   Tåhev – 3-4 x 5-10 RM

For økt eksplosivitet

-   Frivending – 3-4 x 1-5 RM ([video](http://www.youtube.com/watch?v=6TlbDQUWs0s))

-   Rykk – 3-4 x 1-5 RM

-   Støt – 3-4 x 1-5 RM

-   90° knebøy – 3-4 x 5-10 RM

-   Oppstigning på benk - 3-4 x 5 på hvert bein

-   Knebøyhopp m/vekter – 3-4 x 3-8 RM

-   Raske tåhev m/vekter – 3-4 x 10-30 RM

-   Vristhopp m/vekter – 3-4 x 10-30 RM

1 RM = 1 repetisjon maksimum, altså hvor tungt du klarer å løfte ett løft. Når det står flere antall RM betyr det at du skal trene på den vektbelastningen som gjør at du maksimalt klarer det antallet som er forklart.

Det er selvfølgelig viktig å ikke bli for muskulært ubalansert i over- og underkropp, så det er ikke noe i veien for å trene overkropp også. Og ikke minst; for å tåle maksløft og eksplosive styrkevarianter er det viktig å ha en god støttemuskulatur (og selvfølgelig tilstrekkelig teknikk!), så tren også ulike plankevarianter og lignende.

#### Utendørs

For å skape et enda bedre grunnlag for å løpe fortere må du komme deg ut av styrkerommet også. Som med all annen trening er det viktig å trene på det man skal bli god på, og i dette tilfellet vil det være å løpe med opp mot maksimal hastighet flere ganger i uken. Nedenfor kommer noen tips til ulike typer drag du kan gjøre for å få litt variasjon:

-   Drag på friidrettsbane/kunstress e.l. - 30-100m, opp mot maksimal intensitet. 2-3 x 3-5 drag

-   Drag i motbakke - 30-80m, opp mot maksimal intensitet. 2-3 x 3-5 drag

-   Drag i lett unnabakke - 60-100m. Skape høyere fart enn du klarer på flatt underlag. 1-2 x 3-4 drag (obs svært høy belastning)

#### Spenst

Man kan si at spenst er et resultat av den relative styrken, altså den kraften du kan utvikle i forhold til kroppsvekten. Det handler rett og slett om å utvikle en stor akselerasjon i en bestemt retning (vertikalt/horisontalt eller en mellomting).  I vektrommet får du trent mye vertikal spenst, men den horisontale spensten er lettere å gjennomføre utendørs. Det er samtidig viktig å huske på at kraften når man løper går i horisontal retning, så dette er viktig å trene på. Her har du noen øvelser som vil kunne hjelpe deg til å bli mer eksplosiv og dermed en raskere løper (også horisontal spenst er bra, så sleger med noen tips der og):

-   Sprunglauf – raske , 10 x 10-15 hopp ([video](http://www.youtube.com/watch?v=FxJOh46-e04))

-   Stille lengde, 10-15 serier

-   Stegserier – så langt som mulig, 10 serier x 3-steg/5-steg/10-steg

-   Trappespenst (1 – maks antall trinn) - Eks. samlede bein/hinkeserier/raske løp

-   Hekkehopp, 10 serier x 5-10 hekker/3 hekker med stigende høyde

Da gjenstår det bare å ønske lykke til! Legg gjerne igjen spørsmål i kommentarfeltet hvis du lurer på noe angående trening for å bli raskere.
