---
title: "Dårlig samvittighet i glasset?"
date: 2015.10.24
---

De som roper høyest er ikke nødvendigvis de som kan mest. Med sin nye bok "Sannheten i glasset -hva er det vi drikker" har Nils Christian Geelmuyden på nytt skapt både irritasjon og forvirring. Til Side2 presenterer Niels Christian Geelmuyden det han mener er [5 tips for en sunnere mathverdag](http://www.side2.no/helse/geelmuyden---begrens-inntaket-av-disse-drikkene/3423146937.html). Men er disse tipsene velfunderte, eller i det hele tatt fornuftige? Her følger noen korte kommentarer til Geelmuydens tips.

Artikkelen er først publisert hos [Bramat.no](http://www.bramat.no)

## 1. Velg økologisk

Det første rådet er å velge økologisk, for å redusere inntaket av sprøytemidler og kunstige tilsetningsstoffer. For å ta det første først, frykten for sprøytemidler i konvensjonelle produkter er i beste fall misvisende. Det er ikke grunnlag for å hevde at de mikroskopiske restene som eventuelt måtte finnes i produktet utgjør noen helserisiko.

Det Geelmuyden beleilig nok lar være å nevne, er at økologiske drikkevarer kan inneholde ulike kobberforbindelser, som ikke er spesielt gunstige, og også kan inneholde mer tungmetaller ettersom de vokser saktere og kan ta opp mer av dette fra jordsmonnet.

Når det gjelder tilsetningsstoffer, så er det ikke noen automatikk i at disse er ugunstige fordi de er kunstige. Alle tilsetningsstoffer som brukes er godkjent etter et strengt regelverk, og på bakgrunn av kunnskapen som foreligger er det lite som tilsier at dette representerer noen risiko.

Alt i alt finnes det ikke noe grunnlag for å skulle velge økologiske drikkevarer for helsen sin del.

## 2. Velg springvann fremfor flaskevann

Drikk gjerne springvann, kvaliteten på norsk springvann er mer enn god nok. Men at det å velge den ene foran den andre har betydning for annet enn lommeboken er særdeles tvilsomt.

## 3. Begrens inntaket av noen typer drikke

Geelmuyden råder oss til å begrense inntaket av drikker som brus, lettbrus, energidrikker og melk. Han argumenterer med at de tre første sier seg selv, og for brus og energidrikker har han nok fagstanden i ryggen. Men, når det gjelder lettbrus (og annen kunstig søtet drikke), er det [god dokumentasjon for at dette er et bedre helsemessig valg enn de sukkersøtede variantene](aspartamsensitivitet.qmd), så et slikt råd må sees i kontekst av hva man drikker det i stedet for.

Alle er enige om at vann er best som tørstedrikk, men som erstatning for brus er lettbrus definitivt et godt valg.

Når det gjelder melk så viser overhode ikke forskningen at melk øker risikoen for sykdommene Geelmuyden lister opp. Korrelasjon er ikke det samme som kausalitet. Melk kommer totalt sett godt ut i den forskningen som foreligger, noe som reflekteres i nyere reviewartikler.

## 4. Velg villfisk

Geelmuyden mener at skal man spise fisk, så er det best å velge villfisk som har fått bestemme selv hva den vil spise, og ikke er vaksinert/medisinert eller foret med «giftsprøytede planter». Dette er appell til det naturlige, et retorisk grep som ikke har noen i en opplyst ernæringsdebatt å gjøre.

Effekten av å spise en matvare avhenger av hva den inneholder, ikke hvordan den ble til. Vi vet at villfisk inneholder vesentlig mer tungmetaller sammenlignet med oppdrettsfisk, ettersom disse metallene akkumuleres oppover i næringskjeden. Vi vet også at oppdrettsfisk inneholder andelsvis mindre omega-3, men fordi den er fetere inneholder totalt sett mer omega-3 sammenlignet med villfisken.

Fra et helseståsted er det ingen gode argumenter for å skulle velge villfisk foran oppdrettsfisk. Faktisk er det noen holdepunkter for det motsatte.

## 5. Reduser inntaket av kjøtt

Det siste rådet er å redusere inntaket av kjøtt, og her vil nok de fleste fagfolk si seg enige med Geelmuyden. Kjøtt i seg selv er en svært næringsrik matvaregruppe, men samtidig vet vi at spesielt bearbeidet kjøtt er assosiert med økt risiko for noen krefttyper, og i tillegg er kjøttproduksjonen en utfordring rent miljømessig. Mange kunne nok med fordel redusert inntaket av kjøtt.

## Konklusjon

Geelmuyden har et budskap, men argumentasjonen er dessverre skrantende og dokumentasjonen mangelfull. I fravær av dokumentasjon er dette å spre ubegrunnet frykt for matvarer som per det vi vet er helt trygge å spise og drikke. Råd om hva vi skal putte i oss må være basert på god og kvalitetssikret kunnskap, ikke på synsing og forhåndsdefinerte synspunkter.
