---
title: "Konferanse: European Atherosclerosis Society 2014 - Dag 2"
author: "Thomas Olsen"
date: 2014.06.03
---

På konferansens andre dag ble det presentert en rekke spennende funn fra ulike forskningsfelt. Mest interessant for min del var nok den potensielt fremtrendende rollen til tarmbakteriene relatert til hjertesykdom, men det var også interessant å overvære diskusjonen om de ulike retningslinjene som sirkulerer når det gjelder hjerte- og karsykdom.

[Les oppsummering av konferansens første dag her](eas2014-1.qmd)

## Immunitet, mikrobiota og vaksinasjon

Ira Tabas startet dagen med grunnleggende informasjon om inflammasjonsprosesser i kroppen og hvordan disse løses opp. Viktig for aterosklerose er såkalt non-resolving inflammation, som kan oversettes til noe sånt som lett, kronisk inflammasjon som ikke lar seg løse. Dette vil siden gi vevsskade og enda mer inflammasjon, slik at man havner i en ond sirkel. Videre snakket han om hvordan anti-inflammatoriske kosttilskudd som DHA-derivert resolvin (signalstoff laget av omega-3-fettsyren DHA) har vist svært god effekt på oksidativt stress og aterosklerotiske lesjoner hos dyr.

Deretter trakk han videre opp et svært viktig poeng i det dagligdagse, nemlig at den lave graden av inflammasjon man vil unngå ved aterosklerose faktisk er ønskelig ved andre tilstander eller skader! Man bør derfor utvise forsiktighet med bruken av anti-inflammatoriske kosttilskudd, og ikke alltid ha ensidig fokus på å redusere inflammasjon. Som et eksempel nevnte han at ved aterosklerose vil man helst unngå inflammasjon, kalsifisering og trombose da dette øker risikoen dramatisk for hjerteinfarkt. I et helt annet scenario vil de samme mekanismene henholdsvis bekjempe infeksjon, regenerere beinvev etter brudd og hindre blødning. Dette er svært viktige poeng å ha i bakhodet i den evige diskusjonen om betennelse!

Les også: [Overvekt, fettsyrer og inflammasjon](fett-inflammasjon.qmd)

Tabas ble etterfulgt av den anerkjente svenske forskeren Fredrik Bäckhed, og tarmbakterier/mikrobiota stor på agendaen. Dette er et svært hett tema, og blir viet stor interesse fra de fleste forskningsmiljø om dagen. 90% av kroppens celler består av bakterier, og 99% av kroppens DNA består av bakterielt DNA. Tarmbakterier blir derfor ansett som et organ, og deres arvestoff omtales som metagenomet.  I en rask introduksjon kunne Bäckhed avsløre at bakteriekulturen i tarmen er assosiert med immunitet, beinmetabolisme, atferd og energimetabolisme. Han fortalte også at bakterier i ateromatøst plakk kommer fra munnhulen og tarmen, samtidig som man også ser et betydelig endret metagenom hos hjertesyke sammenlignet med friske. Bakteriekulturer er derimot vanskelig å studere og overførbarheten er begrenset ettersom disse varierer fra populasjon til populasjon, og han understreket at studier i ulike etniske grupper er vesentlig for forståelsen av metagenomets rolle i ulike sykdommer og tilstander.

Siste forelesning under dette temaet ble avholdt av nederlandske Johan Kupier. Han driver svært spennende forskning på vaksinasjon mot aterosklerose. Siden det her ikke er noen bakterier å vaksinere seg mot, prøver Kupier og hans team seg på ulike andre vaksinasjonsstategier. Blant dem DNA-vaksinasjon, protein-vaksinasjon og tolerogen vaksinasjon. Førstnevnte har vist seg å være både anti-angiogen samtidig som den motvirker aterosklerose i mus. Samtidig har både protein-vaksinasjon som involverer T-celle-systemet og tolerogen vaksinasjon vist positive effekter. Menneskelige forsøk er imidlertid fremdeles noen år unna, men foreløpig virker altså preliminære data svært lovende!

## Utradisjonelle risikofaktorer: Apolipoprotein A-IV

Florian Kronenberg fra Østerrike gav en rask innføring i ApoA-IV og dets sammenheng med hjertesykdom, nyresykdom og diabetes. Dette er en nylig etablert risikomarkør som produseres i tarmen og tar del i fettabsorpsjon som bestanddel av kylomikroner. Videre stimulerer den kolesterol effluks fra perifere celler og er dermed involvert i revers kolesteroltransport. Som risikomarkør er lav ApoA-IV assosiert med hjertesykdom, mens høye sirkulerende nivåer har blitt observert  ved diabetes og nyresykdom. Her ble det også lagt opp til en diskusjon om genetisk og miljøpåvirkning, dette gikk jeg dessverre glipp av da et foredrag som var spesielt relevant for mitt masterarbeid det siste året fant sted i en annen sal.

Les: [Minikurs i lipoproteiner](minikurs-lipoproteiner.qmd)

Les: [Lipoproteinmetabolismen](metabolismen/lipoproteinmetabolismen.qmd)

## **Lever-tarm aksen og lipidmetabolisme**

Tarmbakterier og mikrobiota var nok en gang på agendaen da Max Nieuwdorp la frem ferske resultater om mikrobiell metabolisme av næringsstoffene [kolin](bioblikk-kolin.qmd). Disse næringsstoffene finner man mye av i animalske matvarer som egg, men kanskje spesielt kjøtt. Mikrobiell metabolisme av disse næringsstoffene danner trimetylamin som absorberes, fraktes til lever og videre omdannes til trimetylamin-N-oksid (TMAO). Dette molekylet er sterkt assosiert med hjertesykdom, men mekanismene er så langt ikke kartlagt. Sirkulerende nivåer av karnitin i seg selv har også vist seg å kunne predikere risiko for hjertesykdom.

Videre presenterte han funn som viste at veganere som ble overtalt til å spise karnitin-rik biff (!) IKKE produserte TMAO sammenlignet med omnivorer som produserte mye av dette, noe som indikerer en annen bakteriekultur hos disse. Når mekanismer er klarlagt for om TMAO faktisk er aterogent rent mekanistisk, åpner dette for fekal transplantasjon (transplantasjon av bakteriekulturer) fra veganere til omnivorer med risiko for hjertesykdom, med håp om risikoreduksjon!

## Hyperlipidemi og hypertriglyseridemi

Børge Nordestgaard snakket mer om fremtidens fokus på kolesterol og hvor han mener vi bør sette fokus i forebygging og behandling av hjertesykdom. Han rettet fokus på triglyserider som han mener er en god markør på kolesterolrest og at disse er langt mer aterogene enn LDL. Kolesterolrest består i hovedsak av IDL, kylomikronrest og VLDL og gir seg som nevnt til kjenne ved høye triglyserider. Nordestgaard kunne melde at kvinner med triglsyeridnivåer på \>5 mmol/l har en svimlende hazard ratio for hjerteinfarkt på hele 7.5 sammenlignet med kvinner med normale nivåer. Menn har derimot en langt lavere risiko på rundt 2.5 med de samme kriteriene. I studiene har de brukt mendelsk randomisering (randomisering basert på genvarianter) for å eliminere [konfunderende faktorer](kildekritikk/konfunderende-faktorer.qmd), noe som gir disse resultatene enda mer tyngde. De viste videre at mennesker med ulik genetisk disponering har økt risiko for iskemisk hjertesykdom ved økt kolesterolrest alene, men også i kombinasjon med lavt HDL. Interessant nok viste også lavt HDL en tendens mot redusert risiko for iskemisk hjertesykdom i pasienter med visse genetiske forutsetninger. Avslutningsvis viste han også en sterk sammenheng mellom kolesterolrest og inflammasjonsmarkøren CRP. Sammenhengen mellom den mer kjente risikomarkøren LDL og CRP var derimot ikke signifikant. I følge Nordestgaard kan HDL fremdeles ansés som ”Good” men påpekte at man nå re-evaluerer noen hypoteser. LDL er fremdeles ansett som "Bad", mens kolesterolrest spiller rollen som Ugly.

## Evaluering av retningslinjer utgitt fra ulike institusjoner

Den amerikanske hjerteorganisasjonen (AHA) kom nylig ut med nye retningslinjer som avviker en del fra de europeiske. Blant annet ønsker man i USA å sette en høyere standard for hvilken evidens som vektlegges når man utarbeider retningslinjer, og alt er her nå basert på randomiserte, kliniske studier. Dette har ført til at man er gått bort fra lipidmål som kolesteroler (med unntak av ved familiær hyperkolesterolemi) ettersom det ikke eksisterer gode klinisk kontrollerte studier på LDL som risikomarkør. Derimot ønsker man å bruke statiner hos mennesker med høy risiko for hjertesykdom. I Europa klør de seg i hodet av disse nye retningslinjene, for mens det å utelukkende ta utgangspunkt i RCTer er positivt, neglisjerer man samtidig en hel del observasjonsdata som gir andre indikasjoner. EAS er uenig, og dette ble diskutert av både svenske Olov Wiklund og belgiske Guy de Backer. De argumenterte for at de nye retningslinjene fra USA senker terskelen for medikamentbruk, og mener observasjondata akkurat nå er den beste kilden til livsstilsdata, ettersom dette er vanskelig å studere under klinisk kontrollerte forhold, og at det derfor ikke bør ignoreres.

Behandlingsmålene til de ulike institusjonene er altså ulike. Hvor EAS fremdeles fokuserer på reduksjon av LDL, er AHA fiksert på statinbruk hos diabetikere med høy risiko (kalkulert risiko \>7.5%) og i mennesker med familiær hyperkolesterolemi (LDL \>4,9 mmol/l). Fordelene med EAS sine retningslinjer er at de vurderer klassiske epidemiologiske studier, meta-analyser og studier som ikke går på statinbruk. Her vurderer man altså en bredere mengde evidens. Hos AHA har man på en annen side svært sterkt bevisgrunnlag, samt at retningslinjene er enkle å følge og godt standardiserte. Som nevnt over vil AHA potensielt senke terskelen for medikamentbruk, noe som potensielt kan føre til at vi ser en økning i bivirkninger og statinintoleranse. Ingenting av dette er ønskelig.

Backer avsluttet sitt foredrag med en anmodning om å finne et rammeverk som alle kan være enige om. Vi trenger ikke flere retningslinjer og mer forvirring men mindre variasjon, harmonisering og konsensus mellom de ulike institusjonene, og understreket at man ikke kan ignorere studier kun fordi de ikke er av randomisert, klinisk design. Personlig mener jeg fokuset i begge retningslinjer har et ensidig fokus på medikamentbruk og at kost og livsstil ikke nevnes med ett ord i noen av foredragene synes jeg er litt på kanten, da det er godt dokumentert at begge deler spiller en rolle. Dette blir forhåpentligvis diskutert i større grad i dagene som kommer.
