---
title: "Konferanse: European Atherosclerosis Society 2014 - Dag 1"
author: "Thomas Olsen"
date: 2014.06.02
---

Jeg kommer til å være tilstede på konferansen til European Atherosclerosis Society i Madrid 31. Mai-3. Juni, og skal prøve å oppdatere dere gjennom hele konferansen på hva som blir lagt frem av nye spennende forskningsresultater når det gjelder den ledende dødsårsaken på global basis, nemlig hjertesykom. Jeg får nok ikke med meg alt av foredrag, men blir med på det aller meste som omhandler ernæring, livsstil og hjertesykdom.

Les også Vegard sin oppsummering av [LHL sin kostholdskonferanse fra 2013](lhl-konferanse-2013.qmd "Kosthold og hjertesykdom – hvor står vi i 2013?").

## Oppsummering dag 1: 31. Mai

Av forelesningene jeg fikk med meg i dag var det først og fremst behandling  og forebygging av dyslipidemi som sto i fokus i et sponset foredrag avholdt i forbindelse med lanseringen av Dyslipidaemia Management Tutorial (DIET). Dette skal være et elektronisk verktøy for leger og helsepersonell i forebygging av [aterosklerose](fysiologi/hjerte4.qmd "Aterosklerose – Hva og Hvordan") og hjertesykdom.

Les mer om [kolesterol](metabolismen/kolesterolmetabolismen.qmd "Kolesterolmetabolismen") og [lipoproteiner](metabolismen/lipoproteinmetabolismen.qmd "Lipoproteinmetabolismen").

### Forebygging av dyslipidemier og DIET-verktøyet

Det 1.5 timer lange foredraget ble innledet av David Jenkins fra Canada. Jenkins hadde fokus på spesifikke matvarer som har vist seg å være gunstig i forebygging av kardiovaskulær sykdom og død. Her trakk han først frem nøtter som en matvare som tidligere ble ansett som fetende, men som i senere tid har vist seg å være assosiert med redusert risiko for kardiovaskulær sykdom og død, i tillegg til å være assosiert med [redusert fremtidig vektøkning](overvekt-forebygging.qmd "Kosthold og forebygging av overvekt"). Videre nevnte han også at både nøtter og olivenolje begge var assosiert med redusert tykkelse på intima media (IMT) og lavere forekomst av diabetes. Han rettet også fokus på ulik såkalt funksjonell mat og dets effekt på kolesterol. Mest fokus fikk fytosteroler fra plantekilder og viskøst [fiber](naeringsstoffer/fiber.qmd "Fiber") som beta-glukan fra havre og bygg samt psylliumfrø. Han nevnte at studier hvor det ble lagt vekt på matvarer rik på disse næringsstoffene gav 30% reduksjon i LDL som er like mye som førstegenerasjons statiner.

Etter David Jenkins, tok Louis Masana over. Han rettet fokus på risikoprediksjon, og manglene med dagens metoder for å predikere risiko for hjertesykdom. En 30-åring med økt forekomst av risikofaktorer som høyt kolesterol, høy BMI osv. vil ha en  ganske lav risikoprofil i et tiårs-perspektiv. Dette er fordi alder er den sterkeste risikofaktoren for utvikling av hjerte- og karsykdommer. Derimot vil man om man ser i livstidsperspektiv ha en mye høyere risiko for hjertesykdom. Masana mener følgelig at det er viktig å fange opp dem som tidlig anses som lav-risiko pasienter. Videre fokuserte han på at små endringer kan gjøre stor forskjell, og dro frem en intervensjonsstudie hvor yoghurt tilsatt fytosteroler ble gitt til deltakere. Når forskerne sammenlignet matvaner før og etter intervensjonen så man ikke bare en drastisk forbedring i deltakernes risikoprofil men også i deres matvaner. Han spekulerte videre i at små triggere som en sunn yoghurt som er ment å være gunstig for hjertehelsen, kanskje kan være med på å endre livsstilen til folk.

Til sist presenterte finske Helena Gylling to kasus-studier hvor to pasienter med høy risiko for hjertesykdom fikk oppfølging av ernæringspersonell og fikk endret sin risikoprofil drastisk i positiv retning. Med disse to veldig generelle kasusene argumenterte hun for at oppførsel og livsstil er fullt mulig å endre med riktig fokus og oppfølging.

Avslutningsvis fikk vi en rask presentasjon av DIET-verktøyet som snart er tilgjengelig for helsepersonell i forebygging, oppfølging og behandling av pasienter med risiko for hjertesykdom. Personlig mener jeg dette er en god idé, spesielt dersom det er mangel på muligheter for behandling hos ernæringspersonell. Dermed kan leger, sykepleiere og helsesøstre benytte seg av dette i denne konteksten.

Les mer om DIET-verktøyet [her](www.dietattheheart.com).
