---
title: "Konferanse: European Atherosclerosis Society - Dag 3"
author: "Thomas Olsen"
date: 2014.06.05
---

Konferansens tredje dag hadde et større fokus på ernæring og livsstil enn de andre dagene, og middelhavsdietten sto sentralt!

[Les oppsummering av konferansens første dag her](eas2014-1.qmd)

[Les oppsummering av dag 2 her](eas2014-2.qmd)

# Ernæring - Fokus på Middelhavsdietten

Spanske Emilio Ros som har vært ledende i forskningen på helseeffektene av middelhavsdietten innledet dagens workshop på ernæring. Han begynte først med å gi en skjematisk oversikt over hvordan prevalensen for hjertesykdom er i Europa, hvor Sør-Europa som kjent kommer best ut, og da spesielt Portugal, Spania, Frankrike og Italia. Han mener dette avhenger av livsstilsfaktorer. Den tradisjonelle middelhavsdietten består av hvete, oliven, vin, sesongens frukt og grønnsaker, meieriprodukter som yoghurt og ost, litt rødt kjøtt samt fisk og sjømat. I utgangspunktet er kan den anses som en høy-fett diett med ubegrenset inntak av enumettede (olivenolje) og flerumettede fettsyrer (fisk). Meta-analyser og studier viser en ganske konsistent nedgang i forekomst av hjertesykdom og død, samt en positiv effekt på overvekt hos kvinner, metabolsk syndrom og diabetes. Isolert sett har olivenolje blitt assosiert med en generell redusert risiko for sykdom og død, og da spesielt extra virgin olivenolje sammenlignet med raffinert olivenolje. Videre har mennesker som spiser etter middelhavsdietten en høyere omega-3 indeks (% av EPA og DHA i røde blodceller) som også er assosiert med lavere forekomst av død. Middelhavsdietten virker altså ut fra dette foredraget å dømme som et svært fornuftig alternativ for å bedre helsen og forebygging av sykdom.

Helena Gylling fra Finland tok over podiumet etter Ros for å snakke om funksjonell mat og nutrigenomikk. Hun pekte på at funksjonell mat egentlig ikke har noen klar definisjon men er et svært populært emne, og kan defineres som som at det skal gi effekter utover grunnleggende ernæring. Funksjonell mat kan altså være beriket av ulike komponenter som f.eks probiotika (yoghurt) eller vitamin D (ekstra lett melk) og derfor gjerne har en helsepåstand tilknyttet seg. Videre dro hun dette inn på at ernæringsforskningen de siste 15 årene har skiftet fokus, og nå omgir genetikk og signalisering. Her spiller naturligvis både makro- og mikronæringsstoffer samt fytokjemikalier som gjerne kan være tilsatt mat eller kosttilskudd en potensiell rolle. Nutrogenomikk omhandler effekten av næringsstoffer på genuttrykk. Mer spesifikt transkriptomet (mRNA-produksjon i celler og vev), proteomet (proteinene i celler og vev) og metabolomet (metabolitter målt i vev (karbohydrater, aminosyrer, steroider, lipider etc). Hun understreket at dette er forskning som enda er i en tidlig fase, men at spesielt fettløselige vitaminer og lipider er potente stimulatorer av både transkriptom, proteom og metabolom og er assosiert med en rekke metabolitter tilknyttet disse. Ved å studere effekten av ulike næringsstoffer på disse faktorene kan man utarbeide nye biomarkører for sykdom i ulike populasjoner med ulike matvaner. Hun trakk frem et eksempel fra en studie gjort på middelhavsdietter som har vist seg å nedregulere gener som er assosiert med diabetes type 2, og at dette trolig bare er begynnelsen på et svært spennende forskningsfelt.

Aleix Sala-Vila snakket mer om middelhavsdietten og har vært med på å gjøre en mekanistisk studie som har undersøkt hvordan effekten er på plakkdannelse på karotisarteriene. Han tok opp at man ser like mye plakkdannelse i Sør-Europa som i resten av Europa, men en langt lavere forekomst av plakkruptur. Forskningsgruppen hans ville finne ut hvorfor, og hypotetiserte at middelhavsdiett ville gi en lavere risiko for ruptur i eldre mennesker med høy risikoprofil. MR ble brukt for å evaluere lesjoner i, samt komposisjon og stenose av, arteriene. Middelhavsdiett med mye extra virgin olivenolje bedret situasjonen betraktelig sammenlignet med en kontrolldiett og middelhavsdiett med mye nøtter. Forskerne konkluderte med at tykkelsen på arteriene ble redusert på middelhavsdiett med mye extra virgin olivenolje gjennom 2 år. Personlig syns jeg denne studien var elegant gjennomført. Mekanistiske studier i mennesker er ikke så vanlig, og denne bidro med mye konkret informasjon.

Jordi Merino gjorde en kort opptreden og kunne rapportere at å redusere saltinntak ikke modifiserte risiko noe særlig hos mennesker som allerede gikk på middelhavsdietten som et ledd i forebygging av hjertesykdom.

# **Kort om Vitamin D**

I en finsk studie hvor deltakerne ble fulgt opp i 27 år kunne Markus Juonala rapportere at lave nivåer av vitamin D (\<50 umol/l) i barndommen var assosiert med økt tykkelse på intima media (IMT) i karotisarteriene i voksen alder og dermed økt risiko for hjertesykdom.

# **Mettet fett**

Tidligere i år ble det publisert en meta-analyse som viste at mettet fett ikke var forbundet med økt risiko for hjertesykdom. Denne ble diskutert på podiumet av Frank Hu fra Harvard, som mener at det er store metodologiske svakheter med meta-analysen. Blant annet mener han at det å ikke inkludere studier som viser at å bytte ut mettet fett med flerumettet fett gir et skjevt bilde av litteraturen. Meta-analysen sier heller ingenting om hva mettet fett ble sammenlignet med. Denne tråden tok Hu videre og argumenterte for at sammenlignet med transfett er mettet fett assosiert med lavere risiko. Videre mener han at det har lite eller ingenting for seg å bytte ut mettet fett med karbohydrater av noe slag da risikoen om noe så ut til å øke, spesielt mtp høy-GI matvarer. Hu argumenterte videre for at man heller bør bytte til matvarer bestående av mye flerumettet fett, da dette nokså konsistent viser en reduksjon i risiko, og at sukkerinntaket må ned. Til tross for tordentalen mot meta-analysen innledningsvis, ble altså ikke dette et korstog mot mettet fett, og Hu konkluderte altså med at det ikke er fordelaktig å bytte ut mettet fett med karbohydrater uansett GI, men at fokuset bør ligge på flerumettet fett og matvarer av høy kvalitet. Han trakk i sedvanlig ånd (etter dagen å dømme) frem middelhavsdietten som et eksempel på dette.

Harvard School of Public Health holdt i April en debatt om fett i kostholdet og effekt på helsen, med tungvektere som Walter Willett, Alicia Lichtenstein, Frank Sacks, Dariush Mozaffarian og nevnte Frank Hu i panelet. [Debatten finnes i opptak her](http://www.hsph.harvard.edu/news/features/saturated-or-not-does-type-of-fat-matter/), og kan anbefales for de som ønsker en oppdatering på hvor vi står per i dag.
