---
title: "Egenbehandling ved belastningsskader - del 1"
date: "2012.05.04"
author: "Eivind Eliasson"
---

Mange som trener opplever belastningsskader, og selv om man gjør "alt riktig" er det vanskelig å unngå skader innimellom. Det viktigste man gjør når slike skader oppstår er at man unngår å provosere skadene ytterligere. Dette kan innebære å f.eks sykle istedet for å løpe hvis beinhinnebetennelsen dukker opp, eller droppe markløft og knebøy om korsryggen krangler. I denne artikkelen skal jeg se på 2 vanlige skader/plager og en enkel metode som kan hjelpe som en del av rehabiliteringen; trege negativer.

## Eksentrisk trening

Eksentrisk trening/trege negativer kan være spesielt nyttig ved følgende to skadetyper: Kneplager, ved smerte like under kneskjellet (1), og akillessmerter (2). Opplever du denne typen smerter bør du følge de skisserte behandlingsoppleggene nedenfor i minimum 4 uker, gjerne mer, for å se om det hjelper.

#### Ved kneplager:

[Trege negativer](http://youtu.be/K8XYB5V3Xj0) kan utføres på følgende måte: Finn deg en stol, stå på ett ben, senk deg så rolig du greier ned til stolsetet, reis deg på begge bena. Forslag til treningsopplegg: 3 sett x 10-15 repetisjoner daglig, ca 30 totalt.

#### Ved akillesplager:

[Trege negativer](http://youtu.be/4F0V3HMVEfE) kan utføres på følgende måte: Stå i en trapp eller på en liten kasse på tærne, med hele fotbladet utenfor kanten. Gå opp på tå med begge beina, og senk deg så rolig du greier ned med en fot. Forslag til treningsopplegg: 2-3 sett x 10-15 repetisjoner daglig, ca 30 totalt.

Hvis plagene ikke forbedres eller til og med forverres etter 4 uker, kan det være lurt å oppsøke lege, fysioterapeut eller manuellterapeut. Om du er villig til å bruke mer penger og komme kjappere inn til behandling, er naprapat eller osteopat gode alternativer.

Kilder:

1\. http://www.ncbi.nlm.nih.gov/pubmed/16882889

2\. http://www.ncbi.nlm.nih.gov/pubmed/22097158
