---
title: "Egenbehandling ved belastningsskader - del 2"
author: "Eivind Eliasson"
date: "2012.07.21"
---

En grei og litt glemt teknikk som kan brukes ved belastningsskader er lett trening med høyt repetisjonsantall. Det er desverre ikke gjort så mye forskning på dette, men det er flere ting som indikerer at en slik tilnærming kan være verdt å teste ut.

Les også: [Egenbehandling ved belastningsskader - del 1](egenbehandling-belastningsskader.qmd "Egenbehandling ved belastningsskader – del 1")

Fordeler:

-   Lav mekanisk belastning gjør at man ofte kan utføre øvelser som er vonde når man løfter tyngre vekter, det er også lettere å løfte med god teknikk

-   Om man trener til teknisk failure kan man allikevel oppnå nesten like gode muskel- og styrkeøkninger som på langt tyngre vekter. (1)

-   Blodsirkulasjonen øker, noe som potensielt kan øke tilhelning.

Når det gjelder valg av øvelser bør man styre unna de største baseøvelsene som knebøy, frontbøy, markløft, olympiske løft osv. Mindre belastende baseøvelser som benkpress, armhevinger, sittende roing, utfall og lignende kan passe bra.

## Eksempler på tilnærminger

Ut ifra hvilke smerter du opplever, kan øvelsesvalget tilpasses din situasjon. Her er noen eksempler på hvordan det kan se ut.

**Skulderskade**: smerter ved utførelse av dips, benkpress med bredt grep og sidehev.

-   3xTF (teknisk failure) facepulls med litt under halve av 1 RM.

-   3xTF armhevinger smalt grep evt på knær om du greier under 20 vanlige på tærne.

-   3xTF sett sittende roing i kabeltrekk med vekt litt under halve av 1 RM

**Kneskade**: Kneet faller innover og er smertefullt under utførelse av knebøy.

-   3xTF step-up med manualer som du greier minst 30 ganger på hvert bein i første sett

-   3xF (vanlig failure) nordic hamstrings

-   3xTF seteløft på ett bein eller med vektstang like nedenfor midja.

Teknisk failure er en betegnelse som betyr at du ikke klarer å utføre flere repetisjoner med god teknikk, og derfor stopper settet. Ved vanlig failure gir du deg når du ikke klarer flere repetisjoner i det hele tatt.

## Er dette i seg selv nok?

Denne behandlingen bør selvfølgelig også kombineres med andre tiltak, som tøying og egenmassasje (tennisball, skumrulle, av kjæresten osv). I tillegg kan man gjøre enkle grep i kostholdet som kan dempe betennelser, som f.eks. å tenke på [balansen mellom omega-3 og omega-6.](brokenlink/omega-3-og-omega-6-i-kostholdet/ "Omega-3 og Omega-6 i kostholdet")

Kilder:

1\. http://www.sciencedaily.com/releases/2012/04/120430105358.htm

###### Har du smerter og lurer på om dette kan være noe for deg, eventuelt hvilke øvelser du bør velge? Still spørsmålet i kommentarfeltet, så svarer Eivind etter beste evne!
