---
title: "En sko til alle?"
author: "Eivind Eliasson"
date: 2013.05.02
---

De siste årene har informasjon om helse, trening og kosthold eksplodert. Ingen av temaene er nye, og selv om kunnskapsgrunnlaget hele tiden blir bredere, så finnes det flere tiår med solid forskning. Likevel virker det som temaene til stadighet blir mer populære og “alle” skal ha en mening. I dette innlegget vil jeg drøfte det jeg anser som et problem med akkurat dette.

Det er flott at disse temaene er i vinden. Mange kan med fordel øke kunnskapen sin, og med tanke på helse og velvære er dette nyttig viten. Imidlertid dukker det stadig opp nye “eksperter” som har funnet noe som fungerer for dem og opptrer som autoriteter som skal belære andre om den unisone fasiten. Forklaringsmodellene er ofte enkle, men glimrer med sitt fravær av anatomi og fysiologi. De går i strupen på flere tiår med forskning, de rakker ned på sine motstandere, og baserer mye av det de skriver på stråmenn og anekdoter. Jeg tenkte å ta for meg noen tema som ser ut til å være temmelig dagsaktuelle.

### "Alle burde spise lavkarbo"

Ok, jeg skal medgi for at en del personer kan en BALANSERT lavkarbodiett være meget fornuftig. Metabolsk syndrom og diabetes type 2 er blant de beste eksemplene. Mange svært overvektige med insulinresistens lykkes svært godt med vektnedgang på lavkarbo. for de som liker typisk lavkarbomat kan et slikt kosthold være perfekt. Jeg har selv prøvd lavkarbo og trivdes godt med det (anekdoter!), men det betyr ikke at jeg da sier at lavkarbo er best for alle.

Noe det ser ut til at en del som fronter lavkarbo ikke forstår, er at mange faktisk både kan ha og har en god helse selv om de spiser litt sukker, hiver innpå med frukt, potet, brød osv. Kostholdet du trives med og kan følge over tid er faktisk det viktigste, såfremt det ikke er åpenbare helseplager som gjør at du bør velge bort noe etc. Mange har faktisk utmerket helse og koser seg med maten selv om de spiser mye brød. Mange har prøvd lavkarbo uten å trives med det. Det finnes flere eksempler på urbefolkninger med svært god helse som f.eks. folket på Kitava som på tross av et høyere karboinntak enn hva de fleste anbefaler (opptil 70%) lever svært godt, men kildene til karbohydrater er riktignok svært annerledes enn våre.

### "Vegan raw-food er fasiten”

En slik påstand er verre enn de mest ekstreme lavkarbofanatikerne, da det er fysisk umulig å overleve på en slik diett over tid bl.a grunnet mangel på vitamin B12. Mange typer mat blir faktisk mer næringsrik av å varmebehandle den (f.eks vil oppvarming øke opptaket av mineraler fra nøtter og belgfrukter), og et sånt kosthold vil også oppleves svært kjipt for mange av oss. Mennesket har et fordøyelsessystem som både ligner dyr som lever vegetarisk og dyr som spiser kjøtt, dvs vi er laget for å være altetere/omnivore. Jeg har ingenting mot veganere så lenge de ikke hevder at dette er en overlegen diett som alle burde følge og som dekker alle næringsstoffene vi trenger.

### “Alle bør trene styrketrening med vekter”


Det er liten tvil om styrketrening med vekter har mange positive helseeffekter, men en god del trives ikke på helsestudio og de liker ikke å løfte vekter. Det viktigste når det gjelder fysisk aktivitet er at du finner en aktivitet som DU liker og dermed greier å gjennomføre over tid. Det er irrelevant om du går tur, sykler, svømmer, spiller badminton eller noe helt annet, så lenge du liker det og får brukt kroppen din slik den er ment for å brukes. Her og vil helsen ha litt å si for valg av aktivitet. Ved store kneplager er kanskje ikke fotball noe godt valg selv om du liker det, men kanskje er lange gåturer i fjellet noe som er like spennende og som knærne attpåtil liker?

### "(putt inn hva som helst) kan behandle/helbrede nær sagt alle typer helseplager”.

Når noe høres for godt ut til å være sant, så er det som regel det. Noen eksempler her er natron, LDN (lavdose naltrexone), nonijuice, pH-diett osv. De fleste av disse  “vidunderkurene” har det til felles at de er rimelig ufarlige. Noen av dem har enkelte positive helseeffekter (muligens LDN og enkelte andre), men de er temmelig marginale sammenlignet med gullet og grønne skoger som loves. Noen er potensielt farlige. Natron er et sånt eksempel hvor man fort kan få i seg alt for store mengder natrium.

Helseplagene det loves effekt mot er ofte diffuse (men ofte alvorlige), med mange årsaksmekanismer og forklaringer. ME (kronisk utmattelsessyndrom) er et godt eksempel hvor noen små studier antyder at en kreftmedisin KAN ha effekt hos NOEN av dem med ME, men mer forskning trengs før dette kan bekreftes. En annen behandling, lightning prosess, er en rent psykologisk behandling som hos andre kan ha en kjempeeffekt. Dette sier noe om at ME ikke er *en* ting og dermed umulig kan ha *en* kur. pH-diettene/kurene er bare et tragisk eksempel på hvor lite folk kan om fysiologi og hvor lett de lures.

## Konklusjon

Det finnes nesten aldri *en* kur, *en* fasit, *en* måte. Ting er mer komplekst enn hva mange liker å tro. Jeg skulle oppriktig ønske at f.eks LDN kurrerte MS, men mange som har prøvd LDN ved MS ble dessverre ikke friske. Mange som brukte nonijuice følte ikke energistrømmene i kroppen, mange opplevde ingen effekt overhodet. Med tanke på økonomi, personlige tragedier ved sykdom osv hadde ingenting vært bedre om det fantes unisone kurer, men dessverre er det ikke slik. Det betyr ikke at vi dermed kan avfeie alle slike påstander og tull og tøys, da en del av dem har  en kjerne av sannhet. Men denne sannheten blåses ut av proposjoner, gjerne av folk som selger aktuelle produkt som “hjelper”. Placeboeffekten undervurderes også, og det er nesten litt rart at mange “alternative” ser ut til å mislike den så sterkt…

Folk er forskjellige og ting har ulike årsaker. Det viktigste både ufaglærte og faglærte bør ta med seg i ryggsekken er respekten for valgene folk gjør, selv om man kan være uenig i dem. Helsepersonell kan f.eks. fraråde en med KOLS å røyke, og nekte han/henne å få oksygen i hjemmet, men de må likevel respektere brukeren for valget han/hun tar. Akkurat som at ingen sko passer alle så finnes det heller ikke løsninger som passer alle. Så flott at skoen passet din fot, men du bruker størrelse 41 og jeg bruker 44…

Relevant lesestoff:

[Opinion Stew](http://www.huffingtonpost.com/david-katz-md/nutrition-advice_b_3061646.html) (David Katz)

[Kjenn dine begrensninger](radgiver-begrensninger.qmd) (Vegard Lysne)

[Hvorfor pH-dietter og natronkurer ikke virker](http://tjomlid.com/2013/04/12/hvorfor-ph-dietter-og-natronkurer-ikke-virker/) (Gunnar Tjomlid)

[En pekefinger i flere retninger](pekefinger.qmd) (Thomas Olsen)
