---
title: "Evidensbasert politikk: Utfordringer og løsninger"
author: "Andrea Rørvik Marti"
date: 2014.05.05
---

Politiske tiltak er en viktig faktor i samfunnsendring og utvikling, og disse kan komme som resultat av en rekke grunner. Politiske tiltak handler om fire ting: (1) Tiltak gjøres på vegne av befolkningen, (2) de gjøres eller iverksettes av staten, (3) de tolkes av offentlige eller private aktører, og (4) de handler om hva staten ønsker å gjøre, og hva den ikke ønsker å gjøre \[1\]. Evidensbasert politikk anses av mange som gullstandarden for politiske tiltak. Dette vil si at tiltak iverksettes basert på grundig og systematisk undersøkelse av problemstillingen, i stedet for gjennom diffuse og ideologisk rettede meninger. Likevel er det ikke alltid slik at politiske tiltak er basert på det forskningen forteller oss. Hvorfor ikke? Hvilke utfordringer møter man på veien fra forskning til politiske tiltak? I denne artikkelen vil jeg beskrive og drøfte noen av problemene man møter på veien, og vil bruke noen eksempler fra psykologisk forskning, fordi det er dette feltet jeg kjenner best. Likevel tror jeg disse utfordringene i like stor grad preger andre fagområder som har potensiale til politisk påvirkning. Jeg ønsker å holde et bredt fokus, og begrenser derfor ikke temaet til Norge eller norsk politikk, men ser på møtet mellom forskning og politikk generelt.

## Kan forskning føre til politisk endring?

Det aller første vi må etablere er dette: Forskningsspørsmål er per definisjon forskjellige fra politiske spørsmål. Ta for eksempel spørsmålet «fører kontakt mellom sosiale grupper til reduserte fordommer disse gruppene imellom?», og sammenlikn så med spørsmålet «kan dette foreslåtte integreringstiltaket resultere i reduserte fordommer mellom disse to sosiale gruppene?». Det første spørsmålet er generelt, og forskningsrettet, mens det andre spørsmålet er spesifikt og krever utprøving i den gitte situasjonen for at man skal kunne finne svaret. Selv om såkalt translasjons- og evalueringsforskning eksisterer (mer om dette senere), er det aller meste av forskning som gjøres såkalt vitenskapelig forskning. Forskningsspørsmål og politiske spørsmål er ikke det samme, og dette gjør iverksetting av evidensbaserte tiltak problematisk. \[2\]

En av hovedgrunnene til at forskningsspørsmål ofte er forskjellige fra politiske spørsmål, handler om det fokuset forskerne velger å ha. The Economic and Social Research Council (ESRC) i Storbritannia utførte i 2007 en stor undersøkelse hvor de blant annet forsøkte å finne ut i hvor stor grad forskere tenker på hvordan deres forskning kan påvirke politikken \[2\]. Rapporten viste at majoriteten av forskerne ikke i det hele tatt tenker på hvorvidt deres forskning kan påvirke politiske avgjørelser. En av hovedgrunnene til dette ble rapportert å være fordi forskerne ikke ser verdien i å prøve å påvirke politiske tiltak, spesielt siden de oppfattet at slike handlinger ikke anerkjennes eller verdsettes innad i forskningsmiljøet, eller av samfunnet utad. ESRC foreslår derfor at forskning som generer innvirkning på politiske tiltak bør verdsettes og anerkjennes i større grad, og at man muligens også kan tilby økonomiske eller andre ønskelige insentiver til forskere som kan å bidra konstruktivt på en slik måte.

En rapport fra Management of Social Transformations (MOST) Programme \[3\] beskriver problematikken godt når de sier at “…politiske spørsmål er ikke forskningsspørsmål, og forskningsspørsmål er som regel kun relatert til politiske spørsmål på veldig indirekte måter” (s.52). Denne forskjellen er viktig å ha med seg, men samtidig utelukker den ikke forskning fra å påvirke politiske tiltak. Flere forfattere, deriblant McKnight og kolleger \[1\], argumenterer for at forskning fint kan brukes i politiske tiltak, så lenge man passer på å implementere disse på en så god og passende måte som mulig.

## Forskningsformidling

I rapporten fra ESRC kommer det frem nok et problem som forskere peker på når det kommer til det de kaller for «impact generation», eller generering av innvirkning. Forskerne i undersøkelsen rapporterte at de er bekymret for at forskningen deres skal bli misforstått av de menneskene de prøver å formidle den til \[2\]. Forskere er veldig fordypet i feltet sitt, og dette fører ofte til at de presenterer stoffet på en måte som kan være vanskelig å forstå for en utenforstående. Ofte blir forklaringene lange og kompliserte, nettopp fordi forskning ofte er veldig vanskelig og komplisert. ESRC foreslår derfor at forskere bør fokusere på det store bildet, og gi en klar og enkel historie som ikke-akademikere kan forstå. Forskere må akseptere at nyanser og detaljer ikke alltid er nødvendig når forskning skal formidles i for eksempel offentlige medier. Ved å arbeide med hvordan man presenterer forskning, kan man på lang sikt gjøre at forskning blir oppfattet som mer tilgjengelig og forståelig for dem med en ikke-akademisk bakgrunn. Dette er vesentlig for at mennesker utenfor forskningsmiljøet skal forstå viktigheten av den forskningen som gjennomføres.

Det finnes også et annet problem når det kommer til hvordan forskere formidler sine funn, og dette er noe som Campbell \[4\] beskriver som «the overadvocacy problem», eller «overformidlingsproblemet». Uttrykket refererer til en tendens som visse forskere har til å fremme sin egen forskning på en alt for entusiastisk måte, uten evne til å se eller påpeke mulige svakheter. Campbell hevder at dette problemet er så stort at forskere bør holde seg så langt unna politikk som overhodet mulig. Andre forfattere påpeker også viktigheten av at forskere må holde seg nøytrale \[5\]. Men her møter man da på et problem: Hvordan kan man fremme en enkel og lettforståelig formulering av egen forskning, men samtidig forholde seg nøytral og avbalansert? Noen forfattere mener at løsningen er at forskere alltid bør påpeke at mer forskning trengs før man trekker endelige konklusjoner \[1\]. Dette kan derimot være et problem i seg selv, ettersom det ofte er uventede og raske hendelser som driver politisk endring \[6\].

Løsningen på problemet blir kanskje at forskere alltid må prøve å holde seg ett skritt foran politikken \[7\]. Ved å fokusere på problemer som er i utvikling, og ved å alltid være åpen for å teste ut ny teknologi og metoder, kan man øke sjansen for at forskningen er på plass når et politisk problem kommer på agendaen. Dette skjedde faktisk på slutten av 1980-tallet i USA da DNA-testing ble tatt i bruk i rettssystemet for å bedømme sannsynligheten for om en mistenkt person hadde begått en gitt kriminell handling. Man DNA-testet en rekke fanger som hadde blitt dømt for handlinger som de hele tiden hadde bedyret sin uskyld for, og svært mange ble frikjent når DNA-bevis kunne bekrefte at de ikke hadde tilknytning til handlingen de var dømt for. Det viste seg at mange av de som hadde blitt uskyldig dømt, hadde blitt dømt utelukkende basert på øyevitneforklaringer. Forut for dette hadde hukommelsesforskere Loftus og Palmer \[8\] allerede studert øyevitnepsykologi i over 10 år, og hadde samlet store mengder bevis for at øyevitneforklaringer i svært mange tilfeller er lite pålitelige. Denne forskningen ble kjent, og store omveltninger ble gjort i rettssystemet for å forbedre bruk av avhørsteknikker og endre rettsprosessen i sin helhet \[9\]

## Forskningsforståelse

Det er ikke bare forskere som opplever problemer med kommunikasjonen, det samme gjelder for politikere og deres rådgivere. Demokrati er basert på at majoriteten bestemmer, og derfor er gjenvalg en sentral del av hverdagslivet til en politiker. Når din egen inntektskilde står på spill kan det være at du foretrekker å gjennomføre tiltak som majoriteten av befolkningen ønsker, fremfor å fokusere på den objektive kunnskapen som eksisterer rundt problemstillingen \[6\]. Sechrest og Bootzing \[10\] sier veldig fint at «politikere fokuserer altfor ofte på sunn fornuft, anekdotiske, introspektive, og kulturelt overførte oppfatninger». Politikere kan altså ofte mislykkes i å se verdien av, eller kanskje simpelthen ikke ha tid til å engasjere seg i forskningsresultater. Dette er et veldig stort problem som fortjener en løsning. Vi trenger politikere som fokuserer på evidensbasert politikk, og politikere må vite at dette er noe befolkningen ønsker og verdsetter. I Storbritannia har regjeringen gått offentlig ut og sagt at de ønsker at alle politiske tiltak skal bygges på evidens \[11\]. Dette er et steg i riktig retning, da det i det minste setter temaet på agendaen.

ESRC foreslår også i sin rapport \[2\] at det må gjennomføres mer åpen dialog mellom forskere og politikere. Men likevel er det ofte endringer i offentlighetens og medienes fokus som fører til politisk endring. Derfor bør forskere også engasjere seg mer i offentlige medier generelt. Selv om det faktum at personlige meninger ofte kommer i veien for evidensbaserte løsninger er problematisk, kan forskning ha større påvirkning om disse tendensene brukes som en fordel.

## Misbruk og misforståelser

Selv når politikere ønsker å basere sine politiske avgjørelser på forskning kan det oppstå problemer. Muligheten for at politikere kan komme til å bruke vitenskapelig forskning for å promotere sin egen politiske agenda er svært reell \[2\]. Undersøkelser viser at bare 14% av Storbritannias befolkning stoler på politikere, men derimot er det 71% som rapporterer at de stoler på forskere \[12\]. Dette faktum kan påvirke måten politikere velger, tolker, og presenterer forskningsresultater, og kan føre til at de overfokuserer på [de funnene som passer med deres allerede eksisterende meninger](kildekritikk/tankefeil1.qmd). Dette problemet må forskere være klar over, og også her kommer kommunikasjon mellom forskere og politikere inn.

Et eksempel på hvordan politikere kan misforstå eller misbruke forskningsresultater kan man se i historien om «Mozart-effekten». I 1993 ble det publisert en studie som viste at det å høre på musikk av Mozart kunne midlertidig øke romlig-temporal kognisjon \[13\]. Studien fikk mye oppmerksomhet i media, og fenomenet «Mozart-effekten» ble introdusert. Resultatene ble dratt langt ut av kontekst til det punktet hvor det ble hevdet at det å lytte til Mozart kunne øke intelligensen og bedre barns utvikling \[14\]. Som et resultat ble det innført en lov i Florida i 1998 som krevde at alle offentlige barnehager skulle spille klassisk musikk for barna minst en time daglig \[15\]. I tillegg gikk guvernøren i Georgia ut med et forslag om at alle nyfødte barn skulle få utdelt en gratis CD med klassisk musikk \[16\]. I senere tid har mange studier sett på effekten av klassisk musikk på en lang rekke parametre, og det er nå veletablert i flere meta-analyser at klassisk musikk ikke har noen som helst effekt på intelligens eller generell utvikling \[14\]. Likevel er det fortsatt mange som tror på dette. Man kan selvfølgelig ikke vite om politikerne som drev frem de nevnte lovforslagene handlet i god tro, eller om de bare ville fremstå som handlekraftige, men fortellingen illustrerer likevel godt hvordan forskning kan overfortolkes og brukes i politiske tiltak mot sin hensikt.

## Veien fra forskning til politiske tiltak

Som vi har hørt i historien om Mozart-effekten kan altså forskning i visse tilfeller føre til politiske tiltak. Men spørsmålet som fortsatt gjenstår er hvorvidt det er optimalt at én enkelt studie skal være nok for å påvirke politiske endringer. De aller fleste innvirkningene fra forskning til politikk er det som kalles for «mini-påvirkere». De er veldig små, nesten ubetydelige hvis man ser på innvirkningen av hver enkelt studie, men kan til sammen ha stor innvirkning. Man kan si at forskning som regel styrer politiske endringer på subtile måter ved å foreslå steg i riktig retning \[2\]. Ofte er ikke forskning relatert til politikk i det hele tatt, men kan likevel fungere som en uventet mini-påvirker. For eksempel kan psykologisk forskning bidra med å avdekke såkalte «universale menneskelige trekk» - psykologiske tendenser alle mennesker har til felles, som for eksempel [systematiske tankefeil](../kildekritikk.qmd) \[10\]. Selv om fordommer mot minoritetsgrupper sannsynligvis varierer i ulike populasjoner, er det sannsynlig at de psykologiske faktorene som bidrar til utvikling av disse fordommene er de samme. Forskning kan derfor være opplysende ved å fremme generell kunnskap som kan brukes i en lang rekke politiske forslag, selv om disse ikke direkte førte til endring, eller på noen måte var relatert til det spesifikke politiske problemet \[17\].

## Hvor mye forskning trenger vi?

La oss igjen ta for oss tilfeller der et enkelt forskningsfunn kan påvirke politiske tiltak. Hvis forsøksdesignet støtter en velbegrunnet og statistisk betydelig konklusjon, er det da egentlig noe problem? Det finnes mange eksempler på robust og god forskning som kan ha spesifikke applikasjoner i politiske problemstillinger. Men dessverre er det slik at [den vitenskapelige metode](kildekritikk/vitenskapelig-metode.qmd) i seg selv er problematisk når det kommer til politikk. Mens forskning gjøres i et kontrollert miljø, er offentligheten ukontrollerbar, og presenterer en lang rekke konfunderende variabler og forstyrrende faktorer \[10\]. For eksempel gjøres mesteparten av psykologisk forskning på en veldig spesifikk gruppe av verdens befolkning, den såkalte «WEIRD»-populasjonen, der WEIRD står for Western, Educated, Industrialized, Rich, Democratic. Amerikanske college-studenter brukes mest av alle, og disse vet vi at er signifikant forskjellig fra den generelle Amerikanske befolkningen (Peterson, 2001). Dette faktum gjør at forskningsfunn blir lite generaliserbare. Problemet med generaliserbarhet må overvinnes før man kan gjennomføre vellykkede politiske tiltak basert på slike data.

Forskningsfunn må også i stor grad kvalitetskontrolleres og dobbeltsjekkes før de kan implementeres politisk. Problemet her ligger i å bestemme hvilken forskning som er av høy nok kvalitet for å få en slik godkjenning \[1\]. Et viktig aspekt ved vitenskapelig metode er å sette spørsmål ved, samt kritisere forskningsfunn. Som regel er forskere uenige, og «perfekt» forskning blir så godt som aldri utført. Vitenskapen er dynamisk og i konstant endring. Denne prosessen kan være vanskelig å forene med tiltaksformulering, hvor målet som regel er å oppnå permanent positiv endring. Det som da blir viktig er at både forskere og politikere systematisk går igjennom all tilgjengelig informasjon, og forsøker å trekke konklusjoner der forskningen blir bedømt til å være god nok. Vi må rett og slett akseptere at det sjeldent vil finnes et «korrekt svar», og tiltak vil kanskje ikke ha den ønskede effekten. Men jo mer forskning som gjøres innen et felt, og jo bedre denne forskningen blir forstått og tolket av personer som virkelig kan det aktuelle feltet, jo høyere er sjansen for at politiske tiltak vil være vellykket.

I tillegg til vitenskapelig forskning, trenger vi et økt fokus på translasjonsforskning \[1\]. Translasjon handler om å undersøke hvordan en gitt behandling eller intervensjon (eller tiltak) fungerer utenfor en laboratoriesetting. Ved å se på hvordan grunnleggende forskning kan overføres til ulike settinger og populasjoner, kan man få en bedre forståelse for hvordan et politisk tiltak vil fungere i praksis. Ved å også forsikre at man har en sterk teoretisk basis for et gitt tiltak, blant annet ved å oppnå en forståelse for de medierende og modererende faktorene som spiller inn, kan senere evaluering av et politisk tiltak gjøres enklere. Derfor må man fokusere på å ha et godt teoretisk rammeverk i bunnen, hvorfra translasjonsforskning kan gjennomføres. Vi finner dessverre lite translasjonsforskning i den psykologiske litteraturen i dag \[1\].

## Er tiltakene vellykket?

Translasjonsstudier kan gi verdifull innsikt til den predikerte suksessen til et gitt evidensbasert tiltak, men det er likevel slik at vi aldri kan vite helt sikkert før vi har prøvd det ut i full skala. Et tiltak må derfor evalueres i ettertid. Som jeg håper du har fått med deg om du har orket å lese så langt som dette, er veien fra forskning til politikk lang og kronglete. Tiltaksforslag sendes gjennom et stort antall individer og organisasjoner, og omskrives ofte dusinvis av ganger før de faktisk implementeres. Derfor er sjansen for at det ferdige produktet passer med visjonen til alle de involverte forsvinnende liten. Selv om et «perfekt tiltak» ble formulert og implementert som planlagt, kan man ikke måle den virkelig innvirkningen av tiltaket før det faktisk er iverksatt. Derfor er evalueringsforskning like viktig som vitenskapelig forskning, teoretiske rammeverk og translasjonsforskning for å forsikre om at tiltaket har vært vellykket.

## Konklusjon

Det å basere politiske avgjørelser på vitenskapelig evidens er viktig, men langt i fra enkelt. Ved å anerkjenne problemene som forskere og politikere støter på, kan vi utvikle mer robuste metoder for implementering av evidensbasert politikk. Det er fortsatt en lang vei å gå, og som vi har sett er ikke alltid evidensbaserte tiltak vellykkede. Men samtidig må vi anerkjenne at vel utførte evidensbaserte tiltak har stort potensial, er det beste alternativet vi har, og bør i aller høyeste grad fremmes som en foretrukket metode for å gjennomføre politiske endringer.

Referanser

1.  McKnight, K. M., Sechrest, L. & McKnight, P. E. (2005). Psychology, Psychologists, and Public Policy. Annual Reviews in Clinical Psychology, 1, 557-76.

2.  Economic and Social Research Council (ESRC). (2007). Policy and Practice Impact Case Study of ESRC Grants and Fellowships in Psychology. L. R. Meagher and C. Lyall (Eds.).

3.  Management of Social Transformations (MOST) Programme (2001). Bridging Research & Policy. J. Crowley (Ed.). Paris: UNESCO.

4.  Campbell, D. T. (1969). Reforms as Experiments. American Psychologist, 24, 409-29.

5.  Seymour, B., & Vlaev, I. (2012) Can, and Should, Behavioural Neuroscience Influence Public Policy?. Trends in Cognitive Sciences, 16, 449-51.

6.  Darley, J. (2002). Gaining Traction for Psychology in the Public Arena. Observer, 15(4) \<http:// www.psychologicalscience.org/observer\>.

7.  DeLeon, P. H., & Kazdin, A. E. (2010) Public Policy: Extending Psychology's Contributions to National Priorities. Rehabilitation Psychology, 55, 311-19.

8.  Loftus, E. F., & Palmer, J. C. (1974). Reconstruction of Auto-mobile Destruction: An Example of Interaction between Language and Memory. Journal of Verbal Learning and Verbal Behaviour, 13, 585-89.

9.  The Innocence Project (2013). Facts on Post-Conviction DNA Exonerations. The Innocence Project Fact Sheets. Retrieved on 24 Feb. 2013. \<http://www.innocenceproject.org/Content/Facts_on_PostConviction_DNA_Exonerations.php\>.

10. Sechrest, L. B., & Bootzing, R. R. (1996). Psychology and Inferences about Public Policy. Psychology, Public Policy, and Law, 2, 377-92.

11. Black, N. (2001). Evidence Based Policy: Proceed with Care. British Medical Journal, 323, 275-279.

12. Ipsos MORI (2011). Public Attitudes to Science. Department for Business Innovation and Skills.

13. Rauscher, F. H., Shaw, G. L., & Ky, K. N. (1993). Music and spatial task performance. Nature, 365, 611.

14. Pietschnig, J., Voracek, M., & Formann, A. K. (2010). Mozart Effect-Schmozart Effect: A Meta-analysis. Intelligence, 38, 314-23.

15. Winterman, D. (2005). Does Classical Music Make Babies Smarter?. BBC News. Retrieved on 24 Feb. 2013. \<http://news.bbc.co.uk/1/hi/magazine/4558507.stm\>.

16. Jones, R. (1999) Mozart's Nice but Doesn't Increase IQs. CNN. Retrieved on 24 Feb. 2013. \<http://edition.cnn.com/HEALTH/9908/25/mozart.iq/ \>.

17. Weiss, C. H. (1977). Research for Policy's Sake: The Enlightenment Function of Social Research. Policy Analysis, 3, 531-45.
