---
title: "Fedmeoperasjon av unge, en akseptabel løsning?"
date: "2012.02.25"
---

Torsdag 23.februar var det duket for [debatt](http://www.nrk.no/nett-tv/klipp/829251/) på NRK , og temaet var fedmeoperasjoner. I panelet fant vi blant annet helsedirektør Bjørn Inge Larsen, trimdronningen Kari Jaquesson, helsepolitiske talsmenn og leder for landsforeningen for overvektige, Jørgen Foss, som nå har bestemt seg for å gjennomføre fedmekirurgi. I publikum satt flere personer som hadde gjennomført slike operasjoner, som fortalte om sine erfaringer.

Denne debatten kom opp på grunnlag av at senter for sykelig overvekt nå åpner for å utføre fedmekirurgi på ungdom i alderen 13-18. Er dette virkelig et akseptabelt alternativ? Lege og forfatter Andreas Eenfeldt gikk for en stund siden [ut i avisen](http://sprek.bt.no/sprek/--Lavkarbo-er-svaret-15175.html) og uttrykte sin motstand mot disse operasjonene. Her er mine tanker om hvordan denne problematikken bør angripes!

## Er fedme en sykdom?

Overvekt og fedme er et resultat av en positiv energibalanse over tid, som har ført til at kroppen har lagret overskuddsenergien som fett. **Overvekten øker risikoen for en rekke følgesykdommer som diabetes, hjerte/kar-sykdom og kreft, og vektnedgang alene vil redusere risikoen for disse sykdommene betraktelig.** Ved siden av å [**kutte røyken**](stump-royken.qmd), er det å gå ned i vekt helt klart et av de viktigste tiltakene du kan gjøre for å forbedre din egen helse, såfremt du ikke fra før er normalvektig. Vektnedgang påvirker en del risikofaktorer for sykdom direkte, blant annet blodtrykk, fordelingen av fettstoffer i blodet og insulinresistens, så det er absolutt mange gode grunner til å gjøre tiltak.

Jeg vil ikke si at fedme i seg selv er en sykdom, men det er absolutt et symptom på at noe er galt. **Årsakene til fedme er mange, og alle har sin egen historie. Likevel er mekanismen den samme, nemlig at kroppen er tilført mer energi enn det som er forbrukt, men årsakene til at denne ubalansen har oppstått kan være ulik fra person til person**. Tradisjonelt sett er teorien at vi spiser for mye og beveger oss for lite, men råd om å spise mindre og trene mer har likevel ikke klart å bremse utviklingen av fedmeepidemien. Kanskje er det på tide å tenke annerledes!

## Hvorfor spiser vi mer?

At en som har blitt overvektig har spist mer enn det som har blitt forbrukt er åpenbart, og er bare et eksempel på de termodynamiske lovene i praksis. **Dette sier imidlertid ikke noe som helst om årsakene til hvorfor denne personen har havnet i denne situasjonen, og det er for meg åpenbart at dette kommer som en følge av at noe annet er i ubalanse.** Mennesker flest spiser seg ikke bevisst til en sykelig overvekt, og spesielt gjelder dette for barn. Et ensidig fokus på at man har spist for mye og beveget seg for lite danner et bilde av at overvektige er svake mennesker som mangler viljestyrke, noe som ikke akkurat bidrar konstruktivt til å løse problemet.

**Det kan være mange årsaker til at en person spiser for mye i forhold til forbruket, og det er helt klart individuelle forskjeller ute å går.** En årsak kan være at vi lever i et samfunn som flommer over av god og velsmakende mat, noe som rent evolusjonært er veldig unaturlig for mennesket. Likevel holder de aller fleste en stabil vekt over tid, noe som taler imot at dette er hovedproblemet. At de fleste holder en stabil vekt år etter år (selv om denne er for høy), betyr at det er en balanse mellom inntak og forbruk, og at denne på et eller annet tidspunkt har vært forskjøvet slik at man har gått opp i vekt.

En annen grunn kan være at maten vi spiser påvirker hvor mye vi spiser, og at mange rett og slett spiser helt feil mat i forhold til hva vi er tilpasset. En liten tur i butikken rundt lunsjtider sier meg at dette med stor sannsynlighet er en av hovedårsakene! **På landsbasis får vi i gjennomsnitt i oss like mye energi fra tilsatt sukker som fra protein!** Lettopptakelige, høyglykemiske karbohydrater gir en kraftig insulinrespons, som igjen påvirker de andre hormonene. Et svingende blodsukker kan også bidra til at vi blir mer sultne og dermed spiser mer. **Jeg er ikke i tvil om at den moderne industrimaten med mye raffinerte karbohydrater og dårlig fett er skyld i mange av dagens helseproblemer!**

## Dårlige tendenser i samfunnet

Overvekt og fedme rammer stadig yngre mennesker, og i 2010 var hver 5. tredjeklassing definert som overvektig eller fet. **Denne utviklingen må bremses om vi ikke ønsker å se en nedgang i den stadig økende levealderen.** Det som tidligere het gammelmannsdiabetes heter nå diabetes type 2, siden det ikke lenger bare rammer eldre.

Hvis vi ser på dagens samfunn, så er det mye å gripe fatt i. **Foreldre generelt har veldig mye å gå på når det gjelder barnas kosthold, og små justeringer kan være gull verdt i forebyggingen av overvekt.** Det verste jeg ser er små barn som blir servert brus eller juice på tåteflasken, lenge før de er store nok til å få med seg annet enn at) gjør med helsen vår, så har jeg problemer med å skjønne hvorfor dette i det hele tatt trenger å være en problemstilling! **Det tradisjonelle lørdagsgodtet er for lengst gått av med pensjon og erstattet med hverdagsgodtet, og helgen som tidligere varte i to dager, varer nå halve uken. Hver dag er en fest!**

Hvem har ikke sett små barn som blir servert søte kjeks eller drops når de er med foreldrene i butikken, bare for at de skal være stille og oppføre seg? Når et barn ikke vil spise det som serveres til middag, er mange foreldre snare med å finne frem mindre sunne alternativer, for barnet må jo spise noe! **Denne mentaliteten kan gjøre mer skade enn godt, og jeg er rimelig sikker på at dette er å gjøre barnet en enorm bjørnetjeneste.** Å lære barnet at dersom det ikke spiser det som serveres så kommer godsakene på bordet, er med å innarbeide dårlige vaner, og som kjent er disse vonde å vende! Om et barn ikke vil spise middag, så er det faktisk en mulighet for at det ikke er sulten!  Jeg har enda tilgode å høre om et barn som har sultet seg, og ingen tar skade av å gå sulten innimellom. Sett heller fram maten igjen litt senere, så skal du se at det blir spist. Man skal selvfølgelig være oppmerksom på underernæring og eventuelle sykdommer, men det er ingen grunn til å bli hysteriske før det er grunn til det!

Når det gjelder fysisk aktivitet er det ikke tvil om at denne er redusert sammenlignet med tidligere, både for barn og voksne. **Det er ikke mange år siden det var vanlig å sykle eller gå til skolen, men i dag er dette unntaket heller enn regelen.** Foreldre kjører barna til og fra skole og andre aktiviteter, for det å gå langs veien er jo livsfarlig. I tillegg stjeler tv, tv-spill og pc en stadig større del av hverdagen, noe som ytterligere reduserer den fysiske aktiviteten. På toppen av det hele finnes det også foreldre som holder barna hjemme når klassen skal på gåtur, siden det selvfølgelig ikke er forsvarlig å gå tur i skogen på ujevnt underlag når det i tillegg er vått ute.

## Hva med slankedietter?

En fedmeoperasjon er naturligvis siste utvei. Den tradisjonelle måten å gå ned i vekt på er tross alt å gjøre endringer i kostholdet og/eller aktivitetsnivået, og her finnes det et utall fremgangsmåter. **Staten kaster nemlig ikke fedmeoperasjoner etter folk; det er en forutsetning at man først har gjort noen ærlige forsøk på å gå ned i vekt på gamlemåten.** Om du ikke har gjort dette, vil du heller ikke få innvilget operasjon.

**Alle dietter fungerer bare så lenge man holder seg til dem.** Går man tilbake til gamle synder, kommer med stor sannsynlighet også den gamle overvekten tilbake, og gjerne med renter. Det er derfor helt essensielt å finne en [**livsstil**](diett-livsstilsendring.qmd) som tillater moderasjon i energiinntaket samtidig som risikoen for å gå på en smell reduseres ved at man unngår å gå rundt sulten. Det er heller ikke til å stikke under en stol at fysisk aktivitet er viktig i en helhetlig sunn livsstil, selv om det ikke i seg selv har en stor innvirkning på vekten.

Rent forskningsmessig er fedmeoperasjoner det eneste som har vist seg å gi varig vektnedgang for større grupper, men disse tallene må tas med en hel bøtte salt. **I studier som sammenligner ulike dietter presenteres resultatene som oftest i form av "intention to treat", noe som betyr at alle forsøkspersonene blir med i sluttanalysen uavhengig av om de har fulgt diettene eller ikke.** Det gjennomsnittlige vekttapet i slike studier er langt fra imponerende, men om man ser bak tallene så består resultene av noen som har gått ned mye i vekt og andre som har gått ned minimalt eller eventuelt gått opp. **Disse resultatene viser derfor ikke effektene av å følge de respektive diettene, men effektene av å bli bedt om å følge den aktuelle dietten.** Det kan være mange årsaker til at mange velger å ikke følge dietten, og det kan være så enkelt som at man blir plassert på en diett man ikke er interessert i å gjennomføre.

## Hva er løsningen?

**Det er rimelig naivt å tro at det er en enkelt løsning på fedmeproblematikken, og en individuell tilnærming vil være ytterst nødvendig.** Samtidig er det en del tiltak som garantert vil være med på å bremse utviklingen, og det er her mesteparten av ressursene bør settes inn.

Det er viktig å gripe fatt i problemstillingen på et tidlig tidspunkt, og opplysning om kosthold rettet mot foreldre burde være det første steget. Statlig/kommunal påvirkning av hva som serveres av mat i barnehager vil også være et godt tiltak, da barna tross alt tilbringer store deler av dagene her.

I debatten på tv ble et økt fysisk aktivitetsnivå i skolen nevnt, og politikerne kunne bekrefte at **det jobbes for at man i hele grunnskolen skal ha en times fysisk aktivitet daglig**. Dette vil være et kjempetiltak, forutsatt at det legges opp på en måte som inkluderer alle og motiverer til en fysisk aktiv hverdag.

Noe som også kan settes i gang er prispolitiske tiltak og opplysningskampanjer, som kan bidra til å vri forbruket over på sunnere matvarer. Når vi vet hvor godt [**nøkkelhullsordningen**](nokkelhull.qmd) har fungert for å vri forbruket over på de merkede varene, er dette et bevis for at denne fremgangsmåten fungerer. Her vil det være fornuftig å starte med de tingene alle er enige om, som å prøve å øke forbruket av frukt, grønnsaker og rene, ubehandlede proteinkilder og å redusere inntaket av tilsatt sukker og hurtigmat. **Hvert lille skritt vil være gull verdt i den store sammenhengen, så det er bare å begynne i den ene enden.**

I denne sammenhengen føler jeg også at det må understrekes at det faktisk ikke er så dyrt å spise sunt. Frosne grønnsaker koster nesten ingenting, og gode proteinkilder som sei, torsk, kylling og karbonadedeig har også en hyggelig kilopris. Man sier gjerne at frukt koster så mye, men sammenlignet med kiloprisen på smågodt, sjokolade og chips er det ikke noe å klage på. Vann som tørstedrikk er også mye billigere enn både brus og jus. Selvfølgelig kan prisene bli mer gunstige, men det er ikke her skoen trykker. **Vi nordmenn bruker en rekordliten andel av inntekten vår på mat, så om vi skal spare penger så har vi mange andre poster i budsjettet å ta fra!**

Fedmekirurgi bør fortsatt være den absolutt siste utveien! Fokuset bør helt klart ligge på forebygging heller enn behandling, og jeg mener absolutt at det er her ressursene må settes inn! **Operasjon av unge mennesker er ikke en akseptabel løsning, da det alltid vil være mange metoder de ikke har prøvd og som bør prøves før operasjon blir aktuelt.** I tillegg må man i hvert enkelt tilfelle kartlegge hva som er årsaken til overvekten, og heller gå inn for å gjøre noe med denne. Å klare å overvinne overvekten på egenhånd vil også gi en følelse av mestring, som kan komme godt med senere i livet!

Hva mener du om fedmekirurgi for unge mennesker? Burde det prioriteres annerledes?
