---
title: "Finn formen i sommer"
date: "2012.06.12"
---

For mange er det et mål å komme i form til sommeren, men husk at også sommeren kan brukes til å være fysisk aktiv. Du trenger ikke engang å dra inn på et treningsstudio for å oppnå dette, det er mange muligheter også utendørs! I dette innlegget vil jeg gi deg noen ideer til aktiviteter du kan velge mellom!

Sommeren er gjerne tiden på året der motivasjonen til å trene inne er klart lavest, noe som bekreftes ved at det er mye mindre aktivitet på de fleste treningssentre. Når solen titter frem frister det kanskje mer å sette seg ut og kose seg med en kald øl. Det er likevel ingen hemmelighet at det er mange treningsmuligheter også utendørs, og flere av disse alternativene er minst like effektive som en tur på gymmet! Gjør deg selv en tjeneste og benytt muligheten til å holde deg i aktivitet i sommer.

## Gå eller løp en tur

Å gå tur, gjerne i kupert terreng, er fin trening. Intensiteten kan styres etter formen, og er du i god form velger du kanskje å jogge eller løpe. Har du fjell i nærheten av der du bor er dette ypperlig for turgåing!

Denne formen for trening er fin for restitusjonen og fettforbrenningen, og når intensiteten økes vil den også kunne gi gode utslag på kondisjonen.

## Hopping og løping

Ta turen til nærmeste kunstgressbane og tren spenst og hurtighet. Det myke underlaget er snillere med kroppen din enn asfalt. Du har mange øvelser å velge mellom, og strengt tatt er det bare fantasien som setter grenser. Hopping både fremover, bakover og sidelengs, burpees, hinking og løping av ulike distanser er bare et lite utvalg av øvelser du kan gjøre.  Du kan også benytte pausene til å f.eks. lære deg å stå på hendene!

[Her er noen filmklipp](http://www.youtube.com/watch?v=uy3jsRB21Bc) fra en av mine egne uteøkter:

\[youtube http://www.youtube.com/watch?v=uy3jsRB21Bc\]

## Ballspill

Hvorfor ikke ta med vennegjengen og spille fotball, sandvolleyball, basketball eller noe annet. Det er både gøy, sosialt og god trening på en gang!

## Styrketrening med egen kroppsvekt

Styrketrening trenger ikke å foregå inne på treningsstudio. Nærmeste lekeplass kan gi uante muligheter! Øvelser som pullups, armhevinger, dips, plankevarianter, hengende beinhev og ettbeins knebøy kan by på utfordringer for de fleste. Er du på et høyere nivå kan du også prøve deg på mer avanserte øvelser som muscleups, front lever, back lever og håndstående armhevinger.

[Her er eksempler på hva en lokal lekeplass hadde å by på](http://www.youtube.com/watch?v=a4I07K6siIE)

##### Dette var bare noen eksempler på trening du kan gjennomføre utendørs. Har du flere forslag?
