---
title: "Hva er et fornuftig kosthold?"
author: "Stine Malvik"
date: 2013.01.14
---

Hva bør man egentlig spise? Hvor ofte? Hvor mye? Trenger det være så komplisert som det fremstilles i media? Og ikke minst - trenger du virkelig gjøre så store forandringer som man kan få inntrykk av?

I dette innlegget skal jeg gi en grei fremstilling av det jeg mener er et fornuftig kosthold. Endelig begynner kostholdsdebatten å roe seg i media, og kanskje er det ikke så dumt å "finne seg selv" igjen etter alle inntrykk man har fått den siste tiden. Det er kanskje ikke så mange som har gjort de helt store forandringene basert på alt som har blitt sagt, men litt forvirret tror jeg nok mange har blitt. Derfor håper jeg dette innlegget kan virke beroligende på de fleste - og kanskje er det ikke så vanskelig?

Aller først vil jeg bare si at mat skal være noe positivt - ikke la det bli for komplisert. Tenk tilbake på hvordan du spiste under oppveksten, med et par justeringer der så tror jeg de fleste er nokså nærme en god fasit på et sunt kosthold. Dette innlegget handler ikke om hvordan man skal spise for å gå ned i vekt - det handler rett og slett om å finne en sunn balanse i kosten, slik at man kan holde seg frisk og rask i mange år fremover. Hvis du vil ha kortversjonen så finner du en oppsummering nederst i innlegget. Om du ønsker litt mer detaljer så kan du lese hele innlegget.

## Energifordelingen

Hvor stor prosentandel av energien du spiser i løpet av en dag bør komme fra de ulike næringsstoffene? For mange kan dette virke vanskelig å omsette i praksis, men det er uansett greit å ha i bakhodet, derfor velger jeg å nevne det her. I praksis betyr det at prosentandelen sier noe om hvor mange kalorier du bør få fra de ulike næringsstoffene i løpet av en dag. Personlig mener jeg det er fornuftig å ligge på denne fordelingen:

-   Karbohydrater: 40-50%
-   Proteiner: 15-25%
-   Fett: 30-35%

Hvor høyt du ligger på proteiner avhengig av hvor mye du trener. På dager med harde treningsøkter vil det være fornuftig å ligge på 20-25% proteiner, og 50% karbohydrater, dvs. spise litt mindre fett disse dagene.

På hverdager er det en fordel om mesteparten av fettet du spiser kommer fra følgende kilder: fisk, oljer, avokado, frø og nøtter. Når det er sagt så tar man absolutt ikke skade av å spise litt mettet fett også, dvs. melkeprodukter/ost, kjøtt, smør ect. Men du trenger ikke la dette være hovedkilden din til fett hver dag.

Karbohydratene du spiser bør i størst mulig grad komme fra grove kornprodukter, grønnsaker, frukt og melkeprodukter.

Gode kilder til proteiner er egg, fisk, kjøtt, melkeprodukter (ost, cottage cheese, kesam, melk), bønner, frø og nøtter.

## Sunt = variasjon

I mine øyne er det å spise sunt synonymt med å spise variert. Og variert i den forstand at man velger ulike matvarer både innenfor én matvaregruppe, og at man i løpet av en dag er innom flere matvaregrupper. Å spise variert er virkelig noe av det viktigste du kan gjøre for å sikre deg god helse gjennom kosten. Ulike matvarer inneholder ulike næringsstoffer, ulike vitaminer og mineraler. Ingenting inneholder alt, så for å sikre seg et optimalt inntak så bør man velge ulike matvarer til hvert måltid, og variere gjennom hele uken.

-   Ikke spis laks hver gang du skal ha fisk, prøv også makrell, sei eller torsk fra frysedisken, det er også rimelig. Tar du deg en tur i ferskvarebutikken kan du få kjøpt f.eks kveite og steinbit. Dette er litt dyrere, men absolutt noe å spandere på seg et par ganger i måneden.
-   Bruker du det samme pålegget hver dag? Ved å variere mellom ost, leverpostei, egg, kaviar, ulike kjøttpålegg, fiskeprodukter og smøreoster får du i deg ulike vitaminer og mineraler - mye av dette er også gode kilder til proteiner.

## Hva med brød?

Jeg får stadig vekk spørsmål om brød virkelig er den store synderen. Mange har rett og slett blitt redde for brød, er det grunn til det? Svaret mitt er både ja og nei. For det første kan jeg si at hvis du skal spise brød - bak ditt eget! Industrielle brød er fulle av gluten, inneholder gjerne mindre næring enn det du baker selv og har som regel konserveringsmidler. Hvis man spiser mye brødmat bør man i alle fall variere de typene man spiser. Brød bakt på havre, rug eller hvete inneholder ikke de samme mikronæringsstoffene, så ved å velge ulike typer så sikrer man inntak av et bredere spekter vitaminer/mineraler. At man skal velge en grov typer tror jeg de fleste er klar over. Og velger du grovt brød er det faktisk en veldig god kilde til både jern, B-vitaminer, magnesium, sink, kalium, natrium og selen.

Jeg synes imidlertid at det holder med ett brødmåltid om dagen. Den enkle grunn til det er at det er vanskelig å spise variert nok om man spiser 2-3 brødmåltider om dagen. Erstatt brødlunsjen med en omelett, salatblanding eller middagsrester. Ett brødmåltid kan gjerne erstattes med hjemmelagde frøknekkebrød - frø er en utrolig god kilde til mange vitaminer og mineraler, i tillegg er frø rike på proteiner og sunt fett, samt kostfiber. En annen fin erstatning til brødmåltidet er cottage cheese med yoghurt og musli/frø/nøtter.

Er du veldig glad i brødmat - ikke slutt å spis brød. Men prøv å hold deg til ett brødmåltid om dagen, bak ditt eget og varier hvilke ingredienser du bruker.

## Frukt og grønnsaker

Alle vet hvor viktig det er, men mange sliter med å få i seg nok. Agurk på leverpostei er dessverre ikke det klokeste valget om målet er å få i seg litt. Uansett om du spiser mye eller lite så er det absolutt viktig å variere mellom ulike typer. Ikke kjøp eple, banan og appelsin hver gang. Hva med å prøve en kiwi eller pære? Noen blåbær og jordbær i musliblandingen gjør godt for både smak og helse. Også når det kommer til grønnsaker vil jeg anbefale på det sterkeste å prøve noen nye typer. Gå inn på [bama.no](http://www.bama.no) f.eks, der finner du en veldig god oversikt over ulike typer frukt og grønnsaker, bruksområde og tilberedning. Der kan du hente mange tips og inspirasjon.

Det finnes mange måter å spise mer frukt og grønnsaker på. Kutt opp litt paprika, tomat og agurk, så ha du det klart til å ha på brødskiven/knekkebrødet sammen med pålegg. Lager du omelett så spis det sammen med en salat. Mitt beste tips er å skjære opp masse salat og ha en i bolle i kjøleskapet, da er det mye lettere tilgjengelig og du kommer garantert til å spise mer. Gjør det til en vane å spise grønnsaker til middag. Frosne grønnsaker er utrolig kjapt å lage, enten de dampes eller kokes.

## Snacks og godteri

Fakta er, at desto mindre godteri og snacks du har i deg i løpet av en uke, desto bedre er det. Sukker er noe man bør være spesielt oppmerksom på. Dette tror jeg de fleste vet. For mange hører det til livsgleden å kunne kose seg med noe godt i helgene, og da er det utrolig viktig at en tilfredsstiller dette behovet, og ikke lar fornuften ta over - for det eneste man sitter igjen med da er dårligere livskvalitet. Jeg tror ikke jeg trenger å si så mye angående dette med snacks og godteri. Jeg tror de fleste er rimelig klar over at dette er noe som bør begrenses til 1-2 dager i uken (helg), og at man skal tenke litt over hvilke mengder man har i seg. Men det er uansett bedre å spise en større mengde én gang i uka, enn å fordele det utover hele uken - det har hverken tennene eller blodsukkeret ditt godt av. Gjør det til en vane at godteri, kaker, kjeks, is og potetgull kun er tillatt i begrensede mengder 1-2 ganger i løpet av en helg, da kommer du langt.

## Ferdigmat vs. hjemmelaget

Det er et uendelig utvalg av ferdigprodukter i butikkene (gryteretter, potetmos, pizzafyll, supper, pølser ect.), og mange tyr til disse i en travel hverdag. Da skal du vite at det går like raskt å lage maten selv. I et fornuftig kosthold så bør man prøve å unngå å bruke for mye ferdigprodukter, hovedsakelig fordi de inneholder mye salt, vegetabilsk fett (transfett?), sukker, smaksforsterkere og andre stoffer man ikke vet 100% hvor godt vi har av. Jeg mener at ferdigprodukter til middag bør begrenses til 1-2-3 dager i uka. Resten av dagene bruker du rent kjøtt/fisk, grønnsaker, ris/potet/pasta og lager dressinger/sauser/tilbehør selv. Mager kesam eller lettrømme egner seg ved siden av mye, pastasaus/pizzafyll kan du enkelt lage av hermetiske tomater, du kan lage guacamole selv, en enkel fløtesaus vha fløte, kremost og krydder f.eks. Ingenting av dette tar spesielt lang tid, det gjelder bare å planlegge slik at du har ingrediensene du trenger. Ønsker du en sunnere livsstil vil jeg absolutt anbefale deg å redusere mengden ferdigmat.

## Hvor ofte og hvor mye?

Spis når du er sulten! Er du sulten, betyr det i de aller fleste tilfeller at kroppen trenger påfyll av energi. Om dette er to eller fem ganger om dagen, avhenger helt av hvor store måltid du spiser, hva måltidene består av, og hvordan du fungerer best. Her er det ingen fasit i mine øyne.

Velg det måltidsmønsteret som passer deg, og lytt til kroppens signaler. Spis når du er sulten og stopp når du er mett, høres det ikke enkelt ut? Vel, det vet vi det ikke er. Men de fleste vet hvordan man fungerer best, og da er det ingen grunn til å forandre på det med mindre det faktisk ikke fungerer. For de fleste vil frokost, lunsj, middag og kvelds + 1-2 mellommåltid være en grei fordelingen av dagens måltider.

## Konklusjon

-   Sørg for å få i deg nok proteiner i løpet av en dag ved å velge proteinrike pålegg, spise egg/kjøtt/fisk hver dag. Har du ikke prøvd deg på cottage cheese eller kesam er det å anbefale.
-   Ikke overdriv inntaket av karbohydrater med mindre du trener hardt, kroppen har like godt av sunt fett og proteiner.
-   Hold deg til ett brødmåltid om dagen - og bak ditt eget!
-   Spis omelett, salat eller middagsrester til lunsj.
-   Spis variert hver dag, ikke la hvilke matvarer du velger bli en rutine, men utforsk matvarefronten.
-   Sørg for å få i deg nok grønnsaker, frukt og bær. Prøv nye typer og ha det lett tilgjengelig i kjøleskapet.
-   Lag maten selv, ikke kjøp ferdigprodukter til middag hver dag.
-   Ha et normalt forhold til godteri/snacks, la dette være forbeholdt til helgen, og ikke overdriv mengdene.
-   Spis når du er sulten, og stopp når du er mett.

Hørtes dette greit ut? Eller er det fortsatt noe som er uklart?

Sjekk ut Stine sin [nye nettside](http://www.mat-helse.no) som åpnet i dag!
