---
title: "Frelse gjennom helse – når riktig blir for viktig"
author: "Asle Bøe"
date: 2014.03.06
---

Mange har et emosjonelt forhold til mat, og et økende fokus på at den skal være sunn, riktig, ren, økologisk og helsebringende gjør at mange deler inn maten i sunn/usunn, ja/neimat. Dette kan være en rettesnor for en enkel forståelse av hva det er fornuftig å spise, men mengdebegrepet er vel så viktig.

Et kosthold til en ung og aktiv person hvor 80-90% utgjøres av frukt, grønnsaker, grove kornprodukter, fornuftige proteinkilder og fettsyrer tåler helt fint en andel kosekalorier på 10-20% uten at det går negativt ut over helsen dersom energibehovet ikke overskrides vesentlig. 50 g sjokolade blir dermed ikke usunt, selv om personen som spiser den kan få dårlig samvittighet for at de spiste en “usunn” matvare.

## Sunt?

Mengdebegrepet, hvor mye, hvor ofte og hvor mye energi matvarene bidrar med sammen med energibehovet er enda viktigere enn at maten er på riktig side av den ofte tilfeldige sunnhetslinjen.

“Sunn” spiller løst på helse og helsebringende, men selve helsebegrepet er nokså løst definerbart.  [WHO](http://www.who.int/about/definition/en/print.html) definerte det i 1948 som:

> Health is a state of complete physical, mental and social well-being and not merely the absence of disease or infirmity.

Relatert til enkeltmatvarer blir det litt søkt å snakke om at den skal være sunn og helsebringende, og spesielt feil blir det når en snakker om supermat. Dersom en tillegger enkeltmatvarer disse egenskapene blir det motsatte tilsvarende skaminduserende og skadelig, noe som er langt fra virkeligheten.

Dersom vi aksepterer helse som ikke bare et fravær av sykdom men et mer generelt psykososialt og fysisk velvære blir det tydelig at et for diskriminerende kostholdsfokus kan, selv om det ikke er skadelig fysisk, føre til redusert velvære på andre felt. Dersom en blir stresset av feil mat i sosiale sammenhenger eller isolerer seg fra dem fordi maten som serveres er feil kan det bli et vesentlig stressmoment.

## Hensiktsmessig

Hensiktsmessig er et ord jeg blir mer og mer glad i. Det respekterer konteksten et utsagn gis i uten å være generaliserbart til alle hele tiden. Dersom du har et behov for å redusere energiinntaket, sukkerinntaket, fettinntaket eller sukkerinntaket kan det være hensiktsmessig å velge alternativer som har mindre av de nevnte. Det gjør ikke maten som inneholder disse tingene usunn eller helseskadelig, og det gjør ikke maten som inneholder mindre av dem mer helsefremmende helt tatt ut av sammenheng fra hvem som spiser det, hvorfor og ikke minst hvor mye en spiser.

Endel maten som defineres som sunn kan også være energitett, og det er lett å overskride kaloribudsjettet. Selv om maten i hensiktsmessige mengder kan bidra til god helse vil for mye kunne bidra til overernæring. Mørk sjokolade, nøtter, oljer og smør er noen av de mest energirike matvarene, men de har også positive egenskaper. Kontrolleres mengdene er de uproblematiske bestanddeler av kostholdet, men inntas de ukritisk får en fort for mye energi fra dem.

Dersom du har et behov for å øke energiinntaket kan det være hensiktsmessig å velge matvarer med mer energi som har et lavere volum enn matvarer som gjør det vanskelig å dekke energibehovet.

## Ortoreksi?

Ortoreksi kommer av gresk, og betyr direkte oversatt “korrekt apetitt”. Siden vi foretrekker salte, søte og fete matvarer fra naturens side er det i utgangspunktet et problematisk ønske å skulle konsekvent unngå disse matvarene. Ortoreksi kan begynne som et uskyldig ønske om å spise bedre, som så blir altoppslukende og ødeleggende.

Tanken er at dersom en spiser maten som oppfattes som riktig vil en få det bra – og problemene oppstår når det ikke blir slik. Må du bare være enda mer restriktiv, enda flinkere? Mangler du viljestyrke? Hva gjør en når en blir dårlig av tanken på at en har spist noe feil som en hadde veldig lyst på?

Å tilskrive matvarer sunne eller usunne egenskaper, å tillegge dem evnen til å enten støtte eller ødelegge for god helse er en betegnende karakteristikk for [ortoreksi](http://www.ntfe.no/utgaver/14-nr-1-2013/55-ortoreksi). Ortoreksi er ikke en etablert klinisk diagnose, og er et relativt nytt begrep. Inntas “feil mat” blir det et stressmoment, og hele matvaregrupper kan utelukkes på tynt grunnlag.

I ekstreme tilfeller kan ortoreksi føre til et så begrenset matvareutvalg at grunnleggende behov ikke dekkes, en får feilernæring og i enkelte tilfeller død. Således har ortoreksi potensiale til å få like dramatiske konsekvenser som de tradisjonelle spiseforstyrrelsene. Dersom all maten skal være riktig og sunn, og [mengdebegrepet forsvinner](http://journals.cambridge.org/download.php?file=%2FPNS%2FPNS71_OCE2%2FS0029665112001000a.pdf&code=cf8e0a32773bde281339879b90c07d0c) får en en tilnærming til kosthold som hverken er fornuftig eller hensiktsmessig nesten uansett hva som er hensikten.

Å definere mat slik, god og dårlig, ren og søppelmat nærer under en emosjonell heller enn kunnskapsbasert tilnærming til mat.

## Porsjonskontroll!

Settes den i sin rette sammenheng ser du at det er helt uproblematisk å lage mat med “vanlige” ingredienser om porsjonene er av passe størrelse og du vet noenlunde hva du får i deg. Dersom du velger den “usunne” maten har du ikke gjort noe galt, feil eller bør skamme deg – det er bare lurt å være bevisst på mengdebegrepet og porsjonsstørrelsene.

Tanken om at noe er sunt kan gjøre oss ukritisk til det, og markedsføring brukes bevisst for å få oss til å velge disse alternativene selv om de nødvendigvis ikke inneholder mindre energi. Dersom vi tenker at sunn=bra og blir ukritisk til mengde og kontekst er det lett for at maten vi tenker er sunn inntas[ i større mengder enn nødvendig.](http://www.ncbi.nlm.nih.gov/pubmed/23428941)

Et levelig, fornuftig og hensiktsmessig kosthold har både plass til energirik mat som utelukkende er der for smakens skyld og mat en bevisst velger fordi den inneholder fiber, proteiner, vitaminer og mineraler og kan bidra til god metthetsfølelse. Det er ingenting galt i å være bevisst på at det går an å velge mindre kaloririke alternativer, å for eksempel lage hjemmelaget pizza med mindre fett, taco med mer grønnsaker og hjemmelaget krydderblanding eller lignende men utfordringen ligger i den kunstige inndelingen av mat som “ja” og “nei”.

Jeg vil påstå det er nyttigere å forstå i hvor store mengder en kan spise de forskjellige matvarene, og skjønne hvilke sammenhenger det kan være lurt å velge alternativer. Mange har behov for å redusere energiinntaket, og det kan absolutt gjøres gjennom å være mer bevisst på ingrediensene i matlagingen.

Bare ikke gi matvarene egenskaper som kun finnes i ditt hode, og gå mot å utvikle et ja/nei-syn på mat. Mesteparten av tiden i hensiktsmessige mengder og noe av tiden i hensiktsmessige mengder er en tilnærming som bevisstgjør, uten at en behøver å tillegge matvarene effekt som fjernet fra sammenhengen og mengden de inntas i ikke gir mening.

Den følgende listen kan det være artig å gå gjennom for å se hvordan du scorer. [Orto-15](http://www.orthorexia.com/wp-content/uploads/2010/06/Donini-Orthorexia-Questionaire.pdf) er en liste utarbeidet for å kunne vise en indikasjon på et [sunnhetsfiksert forhold til mat.](http://www.orthorexia.com/wp-content/uploads/2010/06/Donini-Orthorexia-Questionaire.pdf) Listen er [oversatt til norsk fra engelsk](http://www.ntfe.no/utgaver/14-nr-1-2013/55-ortoreksi), som igjen er oversatt fra italiensk og er således ikke validert for engelske/norske forhold eller for korrekt oversettelse, men jeg tar den med likevel siden den kan være et godt utgangspunkt for refleksjon. Listen er hentet fra [en artikkel](http://www.ntfe.no/utgaver/14-nr-1-2013/55-ortoreksi) skrevet av Kari Anne Vrabel, psykologspesialist/PhD, Avdeling for spiseforstyrrelser og Forskningsinstituttet, Modum Bad og Hilde Mollestad Tveit Reistad, klinisk ernæringsfysiolog, Avdeling for spiseforstyrrelser, Modum Bad.

## ORTO-15

> 1.  Er du bevisst på kaloriene i maten du spiser?
> 2.  Føler du deg forvirret når du er på en matbutikk?
> 3.  Har tanken på mat bekymret deg i løpet av de siste 3 månedene?
> 4.  Er matvalgene du tar betinget av din bekymring for egen helse?
> 5.  Er smaken på maten mer avgjørende enn kvaliteten på maten du spiser?
> 6.  Er du villig til å bruke mer penger på sunnere mat?
> 7.  Bekymrer tanken på mat deg mer enn 3 timer om dagen?
> 8.  Tillater du deg selv matutskeielser?
> 9.  Tror du at humøret ditt påvirker spisemønsteret ditt?
> 10. Føler du at et sunt kosthold bidrar til å øke selvfølelsen?
> 11. Tenker du at et sunt kosthold er med på å forandre livsstilen din? (Hvor ofte du spiser ute, eller med venner).
> 12. Tenker du at et sunt kosthold bidrar til å forbedre utseende ditt?
> 13. Har du skyldfølelse når du spiser noe “forbudt”/noe du ikke burde ha inntatt?
> 14. Tenker du at det også finnes usunn økologisk mat?
> 15. Inntar du måltidene dine alene på nåværende tidspunkt?

Spørsmålene besvares med alternativene: alltid, ofte, av og til, eller aldri.

-   På spørsmål 2, 5, 8 og 9 gir alltid 4 poeng, ofte 3, av og til 2, og aldri 1.
-   På spørsmål 3, 4, 6, 7, 10, 11, 12, 14 og 15 gir alltid 1 poeng, ofte 2, av og til 3, og aldri 4.
-   På spørsmål 1 og 13 gir alltid 2 poeng, ofte 4, av og til 3, og aldri 1. Cut-off verdien for ortoreksi er satt til 40 poeng.

## Take-home message

Å forstå at de fleste matvarer kan bidra til god helse i passelige mengder, enten gjennom å bidra med god næring eller gode smaksopplevelser. En påfølgende kontrollert frihet i kostholdet kan være vesentlig mye mer helsefremmende enn et kvelende fokus på å hele tiden velge riktig med strenge regler for hva som er lov eller ei.

Ikke la riktig bli for viktig. Bon apetitt!
