---
title: "Funksjonsfremmende trening - del 1"
date: "2012.04.26"
author: "Kristian Fagerland"
---

Vi er alle blitt oppmerksomme på begreper som funksjonell trening, skadeforebyggende trening og idrettsspesifikk trening. Forskjellige treningsmiljøer promoterer seg gjerne med å bruke et eller flere av disse begrepene for dermed å appellere til forskjellige kundemasser.

Her skal vi se litt på begrepet funksjonell trening og hva man bør legge i det!

Hos noen er funksjonell trening ensbetydende med trening som imiterer dagliglivets aktiviteter, eller trening med fokus på «stabiliserende» muskulatur. Her ligger fokuset ofte på isolerende øvelser for små muskelgrupper, og det kan nesten virke som en unnskyldning for ikke å trene tungt eller for å unngå tyngre øvelser.

Hos andre treningsmiljøer som f.eks. Crossfit, er treningsfilosofien blant annet å utføre "funksjonelle bevegelser" i treningsøkten på kortest mulig tid. Disse treningene blir derfor utført med høy intensitet og utøveren yter maksimalt under hele den 2-30 minutter lange økten. Her er øvelsene ofte kompliserte flerleddsøvelser og involverer da ofte større og flere muskelgrupper. Det er vanskelig å trekke paralleller fra slik trening til noen av dagliglivets aktiviteter. Dette er altså to ganske forskjellige treningsmetoder som begge defineres som "funksjonell trening". Så hva er egentlig funksjonell trening? Og er det virkelig nødvendig å definere noen treningsformer som funksjonelle? Hvis vi da setter ting på spissen, vil trening som ikke gjennomføres på denne måten være ufunksjonell? Det samme kan man jo spørre om andre begreper som skadeforebyggende trening; vil da annen type trening være skade*fremmende*?

## Funksjonell trening

Den klassiske definisjonen på funksjonell trening er *trening som skal forbedre individets evne til å utføre hverdagslige gjøremål*, altså **trening som har høy overføringsverdi til dagliglivet**. Et begrep som blir brukt mye i rehabilitering er ADL-trening (activities of daily living). I en rehabiliteringsprosess må slik trening tilpasses pasientens funksjonsnivå (han kan være sprek, syk, ha andre diagnoser etc.), de miljømessige krav pasienten møter i hverdagen (har han trapp hjemme, lang vei til butikken etc.) og individets egne mål (hvor motivert er han for trening, hva ønsker han selv å kunne utføre etc.).

For en pasient på 80 år som nylig er operert for lårhalsbrudd vil mulige målsettinger for eksempel være å klare seg selvstendig hjemme, ha energi til å være med barnebarna eller kunne gå til butikken og hjem igjen hvis det ikke er glatt føre. ADL-trening vil for ham være gåtrening med/uten hjelpemidler, trappetrening og diverse øvelser for å styrke glutealmuskulaturen (som ofte er svekket etter lårhalsbrudd). For akkurat denne pasienten vil slik trening være *funksjonell*. For en frisk atlet i 20-årene vil slik trening være meningsløs da han ikke har den samme funksjonsnedsettelsen.

**Funksjonell trening bør derfor ikke defineres ut ifra hva eller hvordan man trener, men heller etter det man oppnår med treningen.** Treningen skal stimulere og føre til positive adapsjoner i kroppslig funksjon*.* Videre er det viktig å forstå at funksjon er avhengig av oppgavens krav. En person som sitter i rullestol er nødvendigvis ikke hemmet av sin funksjonsnedsettelse hvis han skal bruke en PC. Styrkeløftere som løfter 300 kg i knebøy stiller helt andre krav til kroppen sin enn Petter Northug gjør til sin. Derfor er det ikke presist nok å kalle en spesifikk type trening for funksjonell, uten å vite hvilke funksjonsnedsettelser (i forhold til oppgavens krav) og målsettinger utøveren har.

## Funksjons*fremmende* trening

For at treningen skal være funksjonell må den altså være *funksjonsfremmende*. Dette er avhengig av hvilke verktøy man bruker, noe som vil variere fra individ til individ. Visse retningslinjer kan de fleste likevel følge grunnet vanlige problemstillinger forårsaket av typiske over-/feilbelastninger, skadeutsatte kroppsområder eller "weak links". For den friske populasjonen som enten trener aktivt eller har et bevisst forhold til helse, er det derfor kanskje bedre å snakke om *funksjonsfremmende* *trening*. Uten å lage et nytt treningsbegrep, vil fokus på funksjonsfremmende trening være rettet mot å forbedre utøverens kapasitet og funksjon, uansett funksjonsnivå. Enten målet er å ta 310 kg i knebøy, vinne 5-mila i Kollen eller forebygge belastningsskader i jobbsammenheng.

Funksjonsfremmende trening skal forbedre, eller forhindre en forverring av kroppslige funksjoner. Kort fortalt betyr det at den personen som forlater gymmet etter en treningsøkt skal være en forbedring av den personen som gikk inn (når denne personen har fått restituert seg vel å merke). Dette kan selvsagt oppnås på et mangfold av forskjellige måter, men de viktigste og mest effektive elementene i treningen bør være:

-    **Øke det *smertefrie* bevegelsesutslaget til et optimalt nivå i forhold til de krav utøveren møter i sin hverdag/sport.**

    -   Her er det også viktig å se på tilstøtende ledd, da nedsatt bevegelighet i disse kan påvirke bevegeligheten i andre områder. Optimal bevegelighet er essensielt for å motvirke kompensatoriske bevegelser eller feilbelastninger i andre deler av kroppen. Hvis et ledd ikke beveger seg som det skal, fordi en muskel ikke jobber som den skal, vil det skje en kompensasjon en annen plass i kroppen. Hva som regnes som optimal bevegelighet vil variere fra kravene som stilles til utøveren. Likevel er det visse "minstekrav" man bør streve for å oppnå, mer om dette i del 2 i denne serien.

-   S**tyrke muskulatur gjennom hele bevegelsesbanen for å kunne opprettholde stabiliteten i leddet under belastning.**

    -   Å få inn symmetri blant antagonistisk muskulatur er en viktig del av dette elementet. En muskelubalanse vil enten føre til nedsatt stabilitet i leddet eller feilbelastning, som igjen fører til nedsatt funksjon og ytelse hos utøveren. Store flerleddsøvelser som knebøy, markløft og skulderpress vil være med på å bygge en sterk kropp. Et generelt treningsprogram som involverer slike øvelser vil derfor være et godt utgangspunkt for de aller fleste, så lenge utøveren hele tiden tilstreber å perfeksjonere teknikk gjennom optimalisering av egen kroppsfunksjon (se punkt 1). En muskelubalanse kan dog kreve andre tilnærmingsmåter, og i noen tilfeller vil det kreve et trent øye for å finne årsaken bak en muskelubalanse og løsningen på problemet.

-   **Trene målrettet på stadig mer komplekse og spesifikke bevegelsesmønster som man møter i sin sport/hverdag.**

    -   Nervesystemet er plastisk og styrer alle funksjoner i kroppen. Systematisk trening fører til forandringer i nervesystemet. Målrettet trening kan gi forbedret nevromuskulær kontroll, aktivering og rekruttering av muskelfibre. Dette fører til økt prestasjonsevne gjennom en effektivisering av kroppens egne ressurser. En slik prosess tar tid, og er resultatet av langvarig trening med stadig mer komplekse bevegelesmønster som utfordrer kroppen i situasjoner med høy overføringsverdi til den respektive sporten.

Jeg vil poengtere at om man har en skade, funksjonsnedsettelse eller høyere ambisjoner for egen utvikling kan det være hensiktsmessig å oppsøke profesjonelle fagutøvere eller helsepersonell. Disse kan gjennom undersøkelse og testing finne ut hva som vil være den beste framgangsmåten for deg i å nå ditt mål. Vi kan likevel lage retningslinjer som du kan følge, jamfør listen over. I de neste artiklene i denne serien vil vi komme med konkrete forslag til øvelser og teknikker du kan benytte for å trene funksjonsfremmende.

## Før du begynner…

Før du begynner på et nytt treningsprogram eller en ny treningsperiode vil jeg at du skal starte en annen tankeprosess. Tenk igjennom hva du ønsker å oppnå med treningen. Det er viktig med en klar målsetting med (forholdsvis) spesifikke mål. Det er selvsagt ikke alle som har de største ambisjoner eller ønsker om store forbedringer innenfor treningen de holder på med, men alle har innimellom godt av å tenke igjennom og revurdere veien de følger, enten det er i en treningssammenheng eller i forhold til andre ting i livet.

Det er lett å bli låst i faste rutiner. Livet er i bunn og grunn bygd opp av rutiner, og derfor er det viktig å kunne stoppe helt opp og analysere hva man har gjort og hva disse handlingene har ført til. Har man oppnådd det man har ønsket? Hvis ikke er det kanskje på tide å gjøre forandringer. Tenk derfor igjennom hva du ønsker å ha oppnådd i forhold til treningen om 1 år, 6 måneder, 3 måneder og i løpet av den neste måneden. Gjør gjerne dette med andre aspekter i livet ditt også. Jo mer spesifikt jo bedre. Å "bli sterkere" eller "gå ned i vekt" er mål for mange, men de er altfor vage til å være hensiktsmessig for treningen.

Det er også vanskelig å måle og definere en slik framgang. Bedre mål hadde vært å "ta dobbel kroppsvekt i markløft" og "gå ned 1 kg i måneden", eller til og med "få synlig six-pack". Mer abstrakte mål som det siste kan være greit for "hobbyløftere" eller de som trener utenfor konkurranse-idretter. Spesifikke mål er nødvendig når man ønsker et spesifikt resultat, dette for å gjøre det lettere å måle utviklingen underveis og kunne følge en jevn progresjon. Tenk gjennom mål som både er realistiske og som du gjerne må jobbe ekstra hardt mot for å oppnå.

Når dette er gjort er det neste steg å analysere hva som står i veien for at du kan oppnå disse målene. Dette kan være sosiale (jobb, familie), psykiske (mangel på motivasjon) eller fysiske (nedsatt styrke, mobilitet eller utholdenhet) faktorer. Ofte kan det være kombinasjoner. Hos noen kan det være nødvendig å få vurdert sine fysiske egenskaper av en erfaren fagperson, evt. prøve å analysere problemet selv. Når man så vet hvor utfordringene ligger kan man dermed mer effektivt prøve å finne løsninger.

## Når du begynner…

Når du har en klar målsetting for det du vil oppnå og vet hvor de fleste utfordringene ligger, kan du jobbe spesifikt mot disse. Dette betyr dog ikke at treningen kun bør være fokusert på problemområdene; snarere tvert imot. En person som tar 150 kg i markløft vil sannsynligvis ha bedre funksjon enn en annen som tar 100 kg i markløft, gitt de samme forutsetningene. Derfor er det viktig å se på den helhetlige framgangen, samtidig som man tilstreber en bedring i de områdene som hindrer videre framgang.

Treningen bør ha en jevn progresjon, f.eks. enten i form av økt volum eller mer krevende øvelser. Underveis kan det dukke opp nye problemer eller man kan oppdage nye «weak links». Disse kan kreve andre tilnærmingsmåter. Dette er en konstant dynamisk prosess som gjør at man med jevne mellomrom må tilpasse treningen. Kravene man stiller til seg selv varerier alt etter hva man ønsker. En snekker som ønsker å forebygge eller minske skulderproblemer kan bruke helt andre tilnærmingsmåter enn turneren som trenger stabile og sterke skuldre for å kunne utføre en «iron-cross». Motivasjonen, kunnskapen og volumet av treningen vil også være ganske så forskjellig mellom disse. Fokuset er dog det samme for begge; *å* *fremme funksjon*.

## Konklusjon

Poenget med denne artikkelen er å vise at det ikke er nødvendig (eller korrekt) å skille mellom forskjellig definerte treningsmetoder. Øvelser med fokus på økt styrke, optimalisering av bevegelsesutslag og nevromuskulær kontroll bør sammen utgjøre grunnlaget i all trening for de som ønsker redusert smerte, bedre funksjon, økt ytelse og bedre livskvalitet. I neste artikkel i denne serien vil jeg komme med konkrete råd og øvelser for å diagnostisere, behandle og forbedre funksjon.

I mellomtiden; tren for å bli bedre på det som er viktig for deg, tren for å bedre kunne møte hverdagens belastninger, tren for å nå dine mål, tren funksjonsfremmende; tren for å holde deg *frisk & funksjonell.*
