---
title: "Fysisk aktivitet for et lengre liv"
author: "Asle Bøe"
date: 2014.03.20
---

Fysisk aktivtet er grunnleggende for å oppnå god helse og å redusere risikoen for livsstilsykdommer. Tidligere har fysiskt aktivitet vært nødvendig for å skaffe mat og husly. Når huslyet er permanent og byttedyrene ligger ferdig oppdelt i butikken vi ruller til på fossilt brennstoff er behovet for å bevege seg for bevegelsens skyld en relativt ny situasjon vi befinner oss i. Aktivitet har således fått verdi i seg selv – bevegelse for å opprettholde god funksjon og god helse.

## Anbefalinger

I store deler av verden faller aktivitetsnivået i befolkningen dramatisk. [WHO](http://whqlibdoc.who.int/publications/2010/9789241599979_eng.pdf?ua=1)  (World Health Organization) anbefaler minst 150 minutter med moderat til anstrengende fysisk aktivitet i uken i aldersgruppen 18-64 år. [Helsedirektoratet ](http://helsedirektoratet.no/folkehelse/fysisk-aktivitet/Sider/default.aspx)anbefaler minimum 30 minutter hver dag, eller 180 minutter i uken for voksne og det dobbelte for barn. Er målet å vedlikeholde eller fremme vektnedgang er anbefalingen for voksne også 60 minutter om dagen, mens WHOs anbefalinger går opp til 300 minutter i uken, der det kan fordeles mellom anstrengende og moderat aktivitet. Det er altså relativt stor enighet om disse anbefalingene.

Både [Helsedirektoratet](http://www.helsedirektoratet.no/folkehelse/fysisk-aktivitet/aktivitetshandboken/generelle-kapitler/Documents/helseaspekter-ved-styrketrening-kapittel-10.pdf) og WHO anbefaler muskelstyrkende aktivitet to ganger i uken for en voksen befolkning. Ifølge [Mayo Clinic Proceedings](http://www.nlm.nih.gov/medlineplus/news/fullstory_144719.html) utfører menn med fedme helt ned i 3.6 timer anstrengende fysisk aktivitet i året, mens kvinner kun har en time i snitt.

## Hva bidrar trening med?

Fysisk aktivitet bidrar til å bedre metabolsk og kardiovaskulær helse, opprettholde funksjon og en kan se endringer i genuttrykket ved fysisk aktivitet som assosieres med redusert sykdomsrisiko og bedret helse. I en [stor studie som samler data fra seks kohortstudier](http://www.plosmedicine.org/article/info%3Adoi%2F10.1371%2Fjournal.pmed.1001335) som samlet hadde  654.287 deltagere fra 21 til 90 år ville forskerne se hvor mye forventet levealder økte med økende grad av fysisk aktivitet sammenlignet med null fysisk aktivitet.

Ifølge studien gir fysisk aktivitet tilsvarende raskt gange opptil 75 minutter, eller halvparten av WHO-anbefalingene, en forventet økning i forventet levealder på 1.8 år etter fylte 40 år. Nivåer over anbefalte WHO-verdier ga forventet økning på 3.4-4.5 år.  På det høyeste aktivitetsnivået, 450 + minutter i uken eller rett over en time om dagen ser en økning på 7.2 år etter fylte 40 år. sammenlignet med total inaktivitet .

Fysisk aktivitet ga god effekt hos både normalvektige, overvektige og de med fedme. Sammenlignet med å ha fedme grad 2 (BMI på over 35) og å være normalvektig og aktiv var forventet levealder 7.2 år lengre. Å være inaktiv og normalvektig ga 3.1 år lavere forventet levealder enn å ha fedme ( BMI 30- 34.9) og å være aktiv.

En åpenbar begrensning er at datene er selvrapporterte, og således ikke validert. En kan også regne med at mer aktivitet vil være en indikator på god helse og en helsefremmende livsstil i utgangspunktet. Likevel tyder resultatene på at fysisk aktivitet er en god investering som kan gi avkastning livet ut.

Videre har noen gjort matematiske krumspring og foreslått at hvert minutt med fysisk aktivitet kan øke [livslengden med 7 minutter](http://commonhealth.wbur.org/2013/03/minutes-exercise-longer-life), men med så usikre data er det mer en artig tabloid vinkling enn noe du realistisk sett kan forvente. Det er imidlertid liten tvil om at tid investert i fysisk aktivitet i befolkningen kan gi store utslag, og er vel verdt det.

## Livskvalitet og gjennomføring

Livskvalitet er vel så viktig som livslengde, så å finne fysisk aktivitet en trives med er viktig både for å gidde å gjennomføre den og for at den skal bidra så positivt som mulig til opplevelsen av livskvalitet. For noen er turer med hunden å foretrekke foran mer strukturert trening, noe som er helt flott.

Både fysisk aktivitet og å ikke bli overvektig eller utvikle fedme er positivt for helsen og forventet levealder, men å være inaktiv og normalvektig kan være mer uheldig enn å være overvektig og aktiv. Fysisk aktivitet kan bidra positivt til vektnedgang, men gir også god effekt selv om vektnedgangen uteblir.
