---
title: "Påskeferien, hvor usunn er den?"
date: 2014.04.14
---

Det nærmer seg påske, og det er på tide å børste støv av påskeegget. Butikkene har priskrig på smågodt, og sjokolade har aldri vært billigere. Men hvilken innvirkning har egentlig denne høytiden på helsen vår? Er det lov å kose seg litt ekstra?

## Påskeferien og samvittighet

Det er ikke hva du isolert sett gjør i en kort periode som avgjør hvordan helsen din blir. Helsen er nemlig et resultat av alt du gjør og ikke gjør over lengre tid. Påskeferien utgjør en liten del av året, men de samme spørsmålene har en tendens til å dukke opp hvert år. Hvor mye vil det ha å si om man skulle finne på å kose seg litt ekstra i ferien, og hvor dårlig samvittighet skal man ha? Kanskje har det ikke så stor betydning som man skulle tro, og her følger mine tanker om hvordan man kan få i både pose og sekk.

## Fysisk aktivitet og restitusjon

I en travel hverdag med jobb, skole og andre forpliktelser kan det bli knapt med tid til fysisk aktivitet og avslapning. Hvorfor ikke utnytte muligheten i ferien til nettopp dette? Mange reiser på fjellet i påsken, som gjerne innebærer både skiturer, aking og annen aktivitet. Men du trenger selvfølgelig ikke å reise til fjells for å være fysisk aktiv! Nesten uansett hvor du bor vil du finne en egnet turløype i nærheten. Eventuelt er det mange muligheter på nærmeste fotballbane eller lekeplass.

Vi har tidligere skrevet noen saker om [hvorfor nok søvn er viktig](sovn-viktigere-enn-du-tror.qmd). I en hektisk hverdag kan det å sove nok være en utfordring. I ferien blir imidlertid dette mye enklere, da det plutselig åpner seg muligheter for å ligge en time ekstra om morningen.

## Gode valg

Selv om det absolutt må være lov å kose seg og fylle påskeegget med det man måtte ha lyst på, er det mange muligheter for å gjøre gode valg som ikke trenger å gå utover kosen. Man trenger for eksempel ikke å ha påskeegget stående fremme hele uken, da det kan gjøre det lettere å småspise. Da er det kanskje en bedre ide å la påskeegget bo i skuffen for så å ta det frem innimellom.

Et annet forslag er å kjøpe inn frukt og lage til et stort fruktfat. Hvorfor ikke prøve noen nye frukter? Nøtter gjør seg også godt som snacks, og inneholder både proteiner og sunt fett. Visste du at det å spise nøtter er satt i sammenheng med [lavere fremtidig vektøkning](overvekt-forebygging.qmd)?

Brus og saft kan være kilder til en del sukker. Å velge sukkerfrie varianter kan være en svært effektiv måte å redusere sukkerinntaket på. Dette gjelder for øvrig i like stor grad resten av året, da [karbohydrater i flytende form](flytende-karbohydrater.qmd) ser ut til å være spesielt lite gunstig.

**Da gjenstår det bare å ønske alle sammen en riktig god påske, enten den feires i byen eller på fjellet!**
