---
title: "Oppskriften på en god kostdebatt?"
date: "2012.02.10
---

Kostdebatten som har rast i media det siste året har ikke vært spesielt ryddig. Ofte skulle man tro at fokuset ligger et helt annet sted enn på å komme til en enighet om hva som er det beste kostholdet. Prestisje og det å "ha rett" ser ut til å være viktigere enn å komme fram til en god løsning. Hva må til for at vi skal få til en fruktbar debatt, som folkehelsen på sikt kan dra nytte av?

**Forhåpentligvis har alle parter i debatten det samme overordnede målet, nemlig en forbedret folkehelse.** Hvorfor er vi ikke da mer interesserte i å komme sammen og diskutere de ulike synspunktene, og i samråd med nyere studier og forskningsresultater komme fram til en felles løsning. Så lenge alle insisterer på å stå på sitt, kommer vi hvertfall ingen vei. **I det minste burde vi være mer åpne om at vi per i dag ikke kan si så veldig mye sikkert når det kommer til kosthold, og at det er svært vanskelig å gjøre studier som isolerer effekten av enkelte næringsstoffer eller matvarer.** I tillegg er folk forskjellige, og de samme kostrådene kan ikke være optimale for alle, slik at en individuell tilnærming vil være helt nødvendig.

## Vi må bli enige om hva vi diskuterer

Hvis du ser på kostdebatten slik den er i dag, så er det tydelig at de ulike partene diskuterer på ulikt grunnlag. Det første som må skje for at debatten i mine øyne skal komme på rett kjøl igjen, er at man holder seg til det man diskuterer. **Hvis målet med debatten er å finne ut hvilket kosthold som er det beste for helsen, så må ting som bærekraft og solidaritet med fattige land holdes utenfor.** Da må man rett og slett fokusere på hvilken effekt kostholdet har på helsen, uavhengig av andre faktorer. Disse andre tingene har helt klart sin plass i utarbeidelsen av kostråd for en større populasjon, men i forhold til helsespørsmålet for enkeltindividet blir det en annen diskusjon.

Når man skal lage anbefalinger for større grupper, må man selvfølgelig ta hensyn til at det skal være nok mat til alle og at alle skal ha mulighet til å følge anbefalingene. Dette er helsepolitiske spørsmål som helt klart spiller inn på hvordan kostrådene blir seende ut, men man burde da også være åpne om at dette er tilfelle, og at helse ikke er det eneste hensynet som prioriteres.

## Vi må bli enige om hvem vi diskuterer

Når vi diskuterer kosthold, er det viktig å ha for seg at folk er ulike og har ulike behov. Derfor er det viktig å gjøre det helt klart hvem sitt kosthold man diskuterer. Er det snakk om en frisk befolkning, eller diskuterer vi kanskje kosthold for diabetikere? Hva med hjertepasienter, epileptikere eller folk med ulike funksjonshemninger? **Alle vil ha ulike behov for diverse næringsstoffer, og når vi blander alle disse gruppene sammen i samme diskusjon, blir det bare surr.**

I tillegg til at folk er ulike, så må vi også ha klart for oss om vi diskuterer kostholdsanbefalinger til enkeltpersoner eller til større grupper. Når det gjelder kostråd på individnivå, kan kostholdet tilpasses dette individets situasjon og utgangspunkt. Dette faller litt bort når man skal gi anbefalinger til større grupper, og disse rådene blir nødvendigvis mer generelle. **Målet med kostholdsråd til større grupper må være at dersom hele gruppen følger disse rådene, vil det bli en gjennomsnittlig forbedring i helsen til folk**. Det vil ikke dermed si at disse rådene er optimale for hver enkelt, for som nevnt i forrige avsnitt vil folk med ulikt utgangspunkt har ulike behov.

## Vi må bli enige om definisjonene på det vi diskuterer

På dette punktet er det naturlig å ta opp debatten om lavkarbo. Her er det helt klart behov for å bli enige om hva man legger i det begrepet før det i det hele tatt et vits i å diskutere det. **Om man diskuterer lavkarbo og opererer med to helt ulike meninger om hva lavkarbo er, er det uunngåelig at man ender opp med å snakke forbi hverandre.** En løsning kommer man hvertfall ikke fram til, og det vanlige er at man ender opp med å stå å kritisere hverandre i stedet for å fokusere på det man er enige og uenige om.

På samme måte må vi være enige om hva som er alternativet til lavkarbo. Er dette et kosthold i tråd med de offentlige anbefalingene, eller er det et typisk norsk kosthold med et stort innslag av ferdigmat og enkle løsninger?

Et veldig godt eksempel på dette er saken fra dagbladet nylig, der [Sunt Hjem](http://www.sunthjem.no) hadde hjulpet en familie å legge om kostholdet til en form for lavkarbokosthold. I artikkelen ble også en ernæringsfysiolog intervjuet, og et av spørsmålene var:

*"Kan barn spise lavkarbo?"*

Svaret ernæringsfysiologen gav på dette spørsmålet var:

*"Nei, barn skal ikke gå på ekstrem lavkarbodiett".*

Problemet med denne uttalelsen er at det aldri var snakk om noen ekstrem lavkarbodiett. Fokuset i den artikkelen var på å kutte ut inntaket av ferdigmat og halvfabrikata, og begynne å lage maten fra bunnen av med rene råvarer. Når man på denne måten legger andre meninger i munnen på de man diskuterer med, og deretter argumenterer mot disse (stråmannsargumentasjon), kommer man ingen vei!

Dette var bare et av mange eksempler på at man snakker forbi hverandre, nettopp fordi man opererer med ulike definisjoner av det som diskuteres. **Dette er veldig ødeleggende, og hindrer det jeg ville sett på som en god debatt.** Om man er enige om hva man diskuterer, kan fokuset legges på de tingene man er enige om, for det er faktisk en del ting alle er enige om!

## Baser debatten på fakta, ikke følelser

Det er klart at når man har jobbet med noe i mange år, så blir meningene våre farget av nettopp det. Ingen liker at andre forteller at du tar feil, spesielt ikke når dette er noe du jobber med til daglig. Men, som nevnt innledningsvis, så håper jeg at alle parter i kostdebatten har det samme overordnede målet, nemlig en forbedring av folkehelsen. Da er det på tide å innse at om vi skal komme noen vei, så må vi være åpne for å høre på hva motparten har å si. Når det kommer relevante forskningsresultater, må vi være i stand til å se objektivt på disse, og være villige til å endre meningene våre dersom dokumentasjonen for noe annet er sterk nok. **Om man ikke er villig til å høre på ting som strider mot egne meninger, er det et klart tegn på at det viktigste er å "ha rett", og ikke å finne svaret på spørsmålet.**

Så lenge forskningen ikke er entydig og gir oss noen klare svar, må et minstekrav være at man i det minste er åpen om at vi ikke kan trekke noen klare konklusjoner, og at vi inntil videre i stor grad baserer oss på hypoteser og konsensus, ikke klare beviser. Nå må det understrekes at forskningen nok aldri kommer til å gi oss noen klare svar når det kommer til kosthold, men jo mer informasjon som blir tilgjengelig, jo bedre grunnlag har vi for å gi anbefalinger.

##### Hva mener du? Hva må til for å få til en god debatt?
