---
title: "God Jul!"
date: 2013.12.23
---

Jula er her, med alt den bringer med seg. Familiebesøk, julemiddag, julegaver og ikke minst masse julekaker, godteri, brus og for oss voksne også alkohol. Et realt gilde med andre ord! Dette er tiden for å kose seg med sine nærmeste og få hverdagen litt på avstand. Men mange bekymrer seg kanskje for hva jula gjør med kroppsvekten. Den bekymringen er ofte uten grunn.

## Juleflesk

Det er helt normalt å legge på seg litt i løpet av jula. Energibalansen er nådeløs, og flere dager på rad med store middager og påfølgende dessert og kakebord gir et godt bidrag til inntakssiden. Men husk også at ikke hele kroppsvekten utgjøres av energiholdig kroppsvev, så en vektøkning trenger ikke å være ensbetydende med juleflesk. Høyt inntak av salt og sukker bidrar for eksempel med at vi holder på mer væske, noe som selvfølgelig vil gi utslag på badevekten.

For å sette litt tall på det: Det å legge på seg en 1 kg fettvev krever et ganske stort energioverskudd, da dette tross alt representerer innlagring av ca 7500 kcal. Dersom du ligger 1000 kcal i overskudd hver eneste dag mellom jul og nyttår vil du med andre ord maksimalt legge på deg rett i underkant av 1 kg kroppsfett. Det er ingen krise, og tar heller ikke lang tid å bli kvitt igjen.

## Fysisk aktivitet

Det er ingen grunn til å være inaktiv i jula. Jula er en ypperlig anledning til å presse inn noen solide treningsøkter. Den ekstra maten kan fort gi et ekstra gir på trening. Kanskje er juleferien tiden for å sette en ny rekord?

Jula er som nevnt i innledningen tid for familie. Det er ikke dermed sagt at man må være inaktiv. Hva med å legge inn noen formiddagsturer? Er det snø kan kanskje skiene få seg en runde, eller man kan teste ut akebakken. Om ikke annet kan dette gi en ekstra god følelse når man senere på dagen setter seg rundt bordet for å nyte en bedre middag.

## Kos deg

Det jeg først og fremst ønsker å formidle i dette innlegget er at julen er tid for å kose seg. Jula utgjør en liten del av året, så ikke la eksempelvis frykten for julekiloene gjøre at du holder tilbake. Det har du hele resten av året til å gjøre. Det er ikke det du gjør mellom jul og nyttår som er av betydning, det er hva du gjør mellom nyttår og jul!

Ønsker du å begrense eller hindre vektoppgang i jula, ikke la dette gå utover familiekosen. Det går for eksempel an å spise litt mindre tidligere på dagen de dagene du planlegger stor middag, og dermed ha mer å gå på. Å legge inn ekstra fysisk aktivitet er et annet tiltak. Men uansett, ikke se deg blind på badevekta. Husk at mesteparten av den eventuelle vektøkningen i jula vil bestå av ekstra væske, og denne forsvinner like fort som den kommer på.

**Helt til slutt vil jeg ønske dere alle en riktig god jul!**