---
title: "God påske!"
date: 2013.03.28
---

Påsken er her, og for mange betyr dette familiekos med alt det fører med seg. For noen vil slike anledninger etterfølges av dårlig samvittighet - ikke la dette gjelde deg!

## Det er bare påske en gang i året

Som flere ganger tidligere vil jeg understreke at det er det du gjør mesteparten av tiden som ligger til grunn for mesteparten av resultatene du oppnår. Spiser du sunt til daglig, så vil ikke noen dagers utskeielser være forskjellen på suksess og fiasko. Det vil rett og slett kunne inngå i det som kan regnes som variasjon over tid.

Mat er mer enn det vi putter i munnen for å overleve. Det er kultur, det er smaksopplevelser og ikke minst er det sosiale aspekter som kan være minst like viktige som de fysiologiske. Det er fornuftig å i størst mulig grad velge mat ut fra hva som fungerer best med tanke på metthet, energinivå osv, men dersom dette innebærer å nekte seg selv noe man egentlig har lyst på så kan det også være fornuftig å slippe opp litt innimellom.

Jeg oppfordrer for all del ikke til å gå berserk i godteskålen, poenget er at du ikke trenger å gå rundt med dårlig samvittighet om du skulle slå deg litt løs noen kvelder i påsken! Og ikke tenk at du må kompensere for dette etter påsken, unn deg heller noen dagers ferie fra nettopp hverdagen!

## En aktiv påske?

Selv om påsken på alle mulige måter er en anledning for å kose seg med god samvittighet, så er det ikke dermed sagt at du trenger å søke sofaen med smågodtposen og sitter der hele tiden. Fri fra jobb og skole frigir masse tid som også kan brukes til å være fysisk aktiv. Husk at det ikke bare er de knallharde øktene på treningsstudio som gir utbytte. Den daglige aktiviteten er om mulig langt viktigere enn disse øktene for det totale helseutbyttet.

Er du på fjellet så er valget enkelt, ski er en ypperlig påskeaktivitet. Har du ikke snø under beina, så er det ikke noe i veien for å gå tur uten ski. Kanskje er det en passende anledning til å ta med barna på lekeplassen eller fotballbanen? Med litt kreativitet kan man lett kombinere det å være fysisk aktiv og det å kose seg, og mulighetene er så mange at det i praksis bare er fantasien som setter grenser!

Får du tatt deg en treningsøkt eller to, så kan du også oppleve at det ekstra matinntaket kanskje kan gi et ekstra gir på trening, kanskje er det tid for å sette noen nye rekorder? Får du ikke trent, ikke fortvil, det kommer dager etter påske også. Noen dager treningsfri er aldri krise, gjør det som passer deg best, og ha god samvittighet for valget ditt!

## Kos deg i påsken

Det jeg ønsker å formidle kan oppsummeres i følgende tre punkter:

-   Det er bare påske en gang i året, kos deg!
-   Ikke få dårlig samvittighet dersom du avviker mye fra det du gjør i hverdagen
-   Ikke kompenser med å spise mindre/trene mer i perioden etter påske

På vegne av meg selv og resten av skribentene på Frisk og Funksjonell, ønsker jeg alle sammen en fantastisk påske!
