---
title: "Våre råd for bedre helse"
author: 
  - "Vegard Lysne" 
  - "Torbjørn Lysne"
date: "2011.11.06"
categories:
  - helse
---

Helsedirektoratet gir ut sine [råd for kosthold og fysisk aktivitet](http://www.helsedirektoratet.no/ernaering/kostholdsrad/), og ved å følge disse rådene vil de aller fleste merke forbedring i sin helse. Vi kan likevel ikke si oss helt enig i alle rådene, og vi har også et par råd vi vil legge til i listen. Det må understrekes at dette er våre råd til gjennomsnittsbefolkningen. For spesielle grupper, som f.eks. toppidrettsutøvere eller folk med ulike sykdommer, kan ytterligere tiltak være nødvendig. For de fleste vil disse rådene likevel være mer enn tilstrekkelig for å oppnå god helse!

## **1. Sørg for å få i deg nok [protein](naeringsstoffer/protein/) fra gode kilder**

Protein er kroppens byggestener, og normal kroppsfunksjon er avhengig av tilstrekkelig inntak. Protein har vist seg å gi en bedre metthetsfølelse enn de andre næringsstoffene, så om du skal ned i vekt kan det være en fordel å øke inntaket noe. Restitusjon etter trening er også avhengig av at kroppen har aminosyrer tilgjengelig, slik at proteinsyntesen i musklene kan starte. Hvis du trener mye så har du et høyere proteinbehov enn om du har en passiv livsstil. Offentlige anbefalinger er 1,2-2g protein/kg kroppsvekt, noe som er tilstrekkelig for de aller fleste.

[Kvaliteten på proteinkilden](proteinkvalitet.qmd) avhenger mest av aminosyresammensetningen. Alle aminosyrene er nødvendige for at proteinsyntesen skal kunne fungere, og da trenger vi spesielt tilførsel av de essensielle aminosyrene, som kroppen ikke kan lage selv. Fullverdig protein inneholder alle de essensielle aminosyrene i tilstrekkelige mengder. Kilder til fullverdig protein er kjøtt, fisk, egg, meieriprodukter og soya, og disse matvaregruppene bør derfor være representert i ditt daglige kosthold!

## 2. Reduser inntaket av raffinert**e [karbohydrater](naeringsstoffer/karbohydrater/)**

Med raffinerte karbohydrater tenker vi på sukker og fint mel. Disse matvarene utgjør en skremmende stor del av energiinntaket i et vestlig kosthold, noe som med stor sannsynlighet er en del av årsaken til fedmeepidemien vi er vitne til i dag.

Disse karbohydratene har en sterk påvirkning på blodsukkeret, noe også fører til en kraftig insulinrespons. Insulin er det hormonet kroppen skiller ut for å senke blodsukkeret. Det er derfor et livsviktig hormon, siden høyt blodsukker er farlig for oss. Problemet med insulin oppstår først når nivået er konstant forhøyet. Insulin er et innlagringshormon, og fungerer ved å åpne cellene (hovedsakelig muskel- og fettceller) slik at energien kan lagres. Dersom kostholdet inneholder mye karbohydrater, spesielt av den raffinerte typen, vil dette medføre at insulinproduksjonen også økes, noe som gir et økt stress på bukspyttkjertelen (der insulinet produseres), men også på cellene. Etter hvert kan man utvikle insulinresistens, noe som ytterligere vil øke insulinproduksjonen, og da er vi på vei mot diabetes.

Sukker er et eksempel på det vi kan kalle tomme kalorier, siden det ikke inneholder noen mikronæringsstoffer og bare bidrar med energi. Nedbrytningen av glukose forbruker av kroppens vitaminlagre, og det er en helt klar sammenheng mellom høyt sukkerinntak og mangel på vitaminer og mineraler.

## **3. Øk inntaket av frukt og grønnsaker**

"*5 om dagen*" sier Helsedirektoratet, og dette mener vi bør være et absolutt minimum!

Alle er enige om at forbruket av grønnsaker er for lavt, og at de aller fleste vil ha en god helseeffekt av å øke inntaket av denne matvaregruppen. Grønnsaker inneholder lite energi, og vi kan derfor spise masse av dem uten å tenke på at det vil være negativt for vekten. I tillegg er grønnsaker svært næringstette, noe som betyr at de inneholder mye vitaminer og mineraler.

Frukt inneholder en del sukker, og dersom du sliter med å holde vekten bør du ikke ukritisk øke inntaket av frukt, selv om det fint kan inngå i kostholdet ditt. Jo mer fysisk aktiv du er, jo mer frukt kan du unne deg. Er du derimot inaktiv, bør du i større grad satse på grønnsaker.

Både frukt og grønnsaker inneholder en del fytokjemikalier, som har vist seg å kunne beskytte mot en del krefttyper. Frukt og grønnsaker er også de eneste basedannende matvarene, og er nødvendig for å motvirke all den andre syredannende maten. Et syreoverskudd vil føre til økt utskillelse av blant annet [kalsium](naeringsstoffer/kalsium.qmd), noe som kan være en av de sentrale årsakene til utviklingen av beinskjørhet.

Alt i alt er det all grunn til å anbefale å øke inntaket av både frukt og grønnsaker, men hovedsakelig grønnsaker.

## **4. Vær forsiktig med flytende energi**

Det er grunn til å hevde at flytende energi i form av brus, juice, saft og lignende gir en svært dårlig metthetsfølelse. Sliter du med å holde vekten, er dette det første du bør [kutte ut av det daglige kostholdet ditt](flytende-karbohydrater.qmd). Mens inntak av raske karbohydrater fra fast føde ofte fører til en kompensasjon i form av redusert energiinntak resten av dagen, viser studier at det motsatte skjer dersom denne energien kommer i flytende form. Energiinntaket resten av dagen forblir like høyt, og i mange tilfeller øker det!

I Helsedirektoratets anbefalinger regnes et glass juice som en av) vil ødelegges, og innholdet blir derfor lavere enn i den opprinnelige frukten. Syreinnholdet vil også være negativt for tannhelsen, og setter et økt krav til munnhygiene! Velg derfor frukt i stedet for fruktjuice.

## **5. Velg vann!**

Her er vi helt på bølgelengde med de nasjonale anbefalingene. Vann har alltid vært, og kommer alltid til å være, det beste valget av tørstedrikk. Vann er livsviktig for oss, og vi hadde ikke overlevd lenge uten tilførsel. Velger du vann som tørstedrikk fremfor saft, juice, brus og liknende, gjør du deg selv en stor tjeneste!

## **6. Øk [aktivitetsnivået](aktivitet-helse.qmd)**

Stillesitting øker dødeligheten uavhengig av treningsmengde. Samtidig kan vi ikke ukritisk øke mengden hardtrening uten at dette vil føre til økt stress på kroppen. Da blir løsningen å komme seg opp av stolen og øke det daglige aktivitetsnivået.

Rolig aktivitet har flere gode effekter, som at fettforbrenningen blir mer effektiv, det kapillære nettverket utvikles, skjelett og bindevev styrkes og økt blodgjennomstrømming fører til bedre restitusjon mellom de hardere øktene.

Tiltak du kan gjøre for å øke den daglige aktiviteten, er å gå til jobb/skole, velge trapper foran heisen, ta deg en kveldstur i stedet for å sitte på sofaen og generelt benytte alle muligheter til å reise deg fra stolen i løpet av dagen.

## **7. Øk kvaliteten på treningen**

Som nevnt under forrige punkt, kan vi ikke ukritisk øke mengden med hardtrening. Da må vi heller gjøre noe med kvaliteten på det vi gjør når vi først trener.

Hovedmålet med treningen bør ikke være å trene mest mulig, men å få mest mulig utbytte av den tiden du bruker på det! Målet bør derfor være å forbedre fysiske kvaliteter som styrke, hurtighet, spenst og kondisjon, og da gjelder det å velge metoder som gir deg mest igjen for innsatsen.

Styrketrening bør være sentralt i ethvert opplegg, nesten uavhengig av målsetning. Frie vekter gir i de fleste tilfeller langt mer effektiv trening enn trening i apparater, siden øvelser med frie vekter stiller større krav til stabilisering og balanse. Dette vil igjen bidra til at denne treningen også i større grad virker skadeforebyggende. Vi anbefaler å finne et program som trener hele kroppen, og fokuserer på store øvelser med frie vekter. For å [bli sterkere](treningsprogram-stor-sterk.qmd).

En sterk kjernemuskulatur er veldig viktig for å holde kroppen skadefri, og er også sentral når det gjelder idrettsprestasjoner. Vi anbefaler å inkludere øvelser som trener kjernemusklene på den måten de er ment å fungere, nemlig til å motvirke bevegelse. Øvelser som øker denne egenskapen er f.eks. forskjellige plankevarianter. Les mer om basistrening [her](basistrening.qmd).

Når det gjelder [kondisjonstrening](utholdenhet.qmd), velger veldig mange å jogge, noe som ikke nødvendigvis er det beste valget. En intervalløkt vil gi en mye større effekt på oksygenopptaket, som er den viktigste faktoren for kondisjonen. En slik økt vil også ta mye kortere tid, og vil enklere kunne inkluderes i en travel hverdag. Lengre joggeturer har også sin plass i et helhetlig opplegg, men husk at dette er en treningsform som sliter mye på kroppen. Spesielt knær og ankler er utsatt, så det kan være en god idé å variere med f.eks. svømming eller sykling.

## **8. Bruk litt tid på tøying**

De aller fleste sliter med ubalanser mellom musklene, noe som påvirker holdningen og lett kan føre til kroniske smerter og plager. Slike smerter er i dag en av de vanligste årsakene til at folk sykemelder seg.

Typiske muskler som er forkortet er hofteleddsbøyerne, baksiden av lårene og brystmusklene. Jevnlig tøying av disse kan gjøre mye for holdningen din, noe som vil være forebyggende med tanke på nevnte plager.

Hvis du ønsker å gjøre ytterligere tiltak, kan vi anbefale deg å skaffe en massasjerulle (foam roller). Ved å rulle fram og tilbake over stramme muskler vil du jobbe med bindevevet som ligger rundt musklene, muskelfascien. Dette vil blant annet øke muskelens fleksibilitet, forbedre lokal sirkulasjon og redusere muskelspenninger.  Sekundære fordeler med dette vil være forbedret restitusjon etter trening. Egenmassasje av overnevnt muskulatur samt sete (m. Gluteus maximus og medius/minimus) og bindevevsdraget på utsiden av låret (tractus iliotibialis) er å anbefale hvis du vil ha mest mulig ut av treningen din.

## **9. Lytt til kroppen**

Kroppen reagerer på alt du gjør, og gir beskjed dersom noe er galt. Vi vil anbefale å alltid lytte til kroppen og ta alle signaler på alvor. Ved å gjøre dette kan du forhindre utvikling av sykdom og utbrenthet. Det er bedre å stå over én trening enn å gå glipp av flere på grunn av dårlige valg. Det er også bedre å droppe det siste settet enn å risikere å skade deg, dersom du merker at noe ikke er som det skal. Å presse seg er selvfølgelig sentralt for å oppnå fremgang, og det er viktig å skille mellom signaler på at du er sliten og signaler på at det er noe galt.

## **10. Slapp av**

De færreste klarer å være perfekt hele tiden. Selv om du lager en plan og ønsker å følge denne hele tiden så dukker det hele tiden opp fristelser, og før eller siden så vil de fleste gi etter. Dette trenger ikke å være negativt, og det kan i mange tilfeller være værre å hele tiden nekte seg noe man egentlig har lyst til. Det å hele tiden fokusere på hva man ikke "har lov til", kan være ganske stressende, og slikt stress er ikke bra!

Husk på at det er det du gjør mesteparten av tiden som avgjør hvordan resultatene dine blir, og enkelte utskeielser har i den store sammenhengen svært lite å si. Prinsippet med lørdagsgodt passer veldig godt inn i dette punktet, da det kommuniserer at det er lov å kose seg, men samtidig er det en god idé å begrense dette.

Om du over lengre tid klarer å følge planen over 80% av tiden, så skal du være fornøyd med dette. Dette er et realistisk mål for alle! Du bør selvfølgelig så langt det lar seg gjøre prøve å strekke deg mot 100%, og da har du også mer rom for uforutsette utskeielser som plutselig dukker opp, siden du vet at dette ikke vil utgjøre en stor del av totalen!

Budskapet er: Slapp av og nyt livet!
