---
title: "Tenk på helsa til bestemor!"
author: "Stine Malvik"
date: 2013.05.09
---

Vi er stadig mer opptatt av hva vi putter i oss, noe som er bra. Foreldre passer på at barna får i seg næringsrik mat både i barnehage og skole, det kan vi se blant annet gjennom forbud mot bursdagskaker i barnehager og skolemelk/-fruktordning rundt omkring i landet. Vi passer på oss selv, og vi passer på barna våre – men hva med de gamle? Kanskje har du en gammel bestemor på sykehjem, eller en bestefar som nylig har blitt enkemann. Har du tenkt noe særlig over hva de får i seg av næring?

## Underernæring, et stort problem!

På sykehus er underernæring et mye større problem enn overvekt. Svært mange pasienter kommer inn på sykehus og får i seg alt for lite mat under oppholdet. Dette kan skyldes dårlig matlyst som følge av sykdom, munn/tann/svelgproblemer, at de ikke liker maten eller at de rett og slett er for syke til å få i seg ordentlig mat. Mange er inne på sykehus over lengre tid, eller går inn og ut over en lengre periode. Er man undervektig fra før er det ekstra skummelt å få i seg for lite mat, men også overvektige personer som får for lite mat over lengre tid kan få mangelsykdommer eller være ekstra utsatt for sykdom. Det er svært uheldig for syke å være under-/feilernært, dette kan forverre sykdomsbildet, øke tiden de er innlagt eller føre til flere sykdommer. På sykehus prøver man derfor å fokusere ekstra mye på å kartlegge ernæringssituasjonen til nye pasienter.

Mange har enten foreldre eller besteforeldre på sykehjem, eller kanskje en gammel tante? Svært mange gamle går ned i vekt som følge av økt alder. Det kan skyldes de samme årsakene som nevnt ovenfor, spesielt tap av appetitt og problemer med munn/tenner/svelg. På sykehjem får man servert all mat, og alle pleierne er ikke like oppmerksomme på nøyaktig hvor mye mat og drikke hver enkelt får i seg. Det er f.eks. ikke usannsynlig at en på sykehjem får i seg noe sånt som dette i løpet av en dag:

> Frokost: 2 halve skiver med smør og syltetøy + 1 glass lettmelk og 1 kopp kaffe
> Formiddagskaffe: 1 kopp kaffe og 1 glass saft
> Middag: 1 potet, 1 kjøttkake, 1 gulrot og litt brun saus
> Ettermiddagskaffe: 1 stk sjokoladekake + 1 kopp kaffe
> Kvelds: 2 halve skiver med smør og syltetøy + 1 glass lettmelk

Dette dagsinntaket tilsvarer 1008 kcal og 27,5 g protein. Ei lite aktiv dame på 80 år har behov for 1697 kcal og 63 g protein hver dag for ikke å miste vekt. Med dette energiinntaket vil hun kunne gå ned rundt et halvt kg i uka, og mye av dette er muskelmasse. Jeg har selv jobbet på sykehjem i mange år, og vet at flere spiser så lite som dette.

## Hva kan gjøres?

Selv om enkelte har dårlig matlyst, så er det også mange som spiser sakte, og kanskje er maten ryddet bort når de er ferdige. Høflige som mange eldre er, så spør de ikke om mer mat. Da er det viktig at pleiepersonalet er oppmerksom på hvor mye hver enkelt får i seg, og enten venter med å rydde bort maten til alle er ferdige med å spise, eller smører noen skiver som de kan tilby etterpå. Hvis enkelte ikke ønsker å spise store mengder, så må man heller tenke på hva man faktisk får i seg de få måltidene man spiser. Det er mange måter å øke energitettheten på maten man spiser, f.eks gjennom oljer, smør, majones, mer pålegg, feite sauser, helmelk i stedet for lettmelk ect.

Poenget mitt er at du skal ikke forvente at de som jobber på sykehjem sørger for at moren eller bestefaren din får i seg nok mat – både på grunn av dårlig prioritering av tid, lite kunnskap og enkelte ganger likegyldighet. Jeg skriver ikke dette for å kritisere de som jobber på sykehjem, det er svært mange dyktige pleiere der ute som tar dette på alvor, og i mange tilfeller handler det også om for lite ressurser. Men hvordan situasjonen er på det sykehjemmet du har din kjære må du finne ut selv. Derfor er det viktig at man som pårørende eller familiemedlem følger med på kroppsvekta, snakker med vedkommende om hvordan de selv synes matsituasjonen er, og tar det opp med personalet om det er noe som ikke er bra. Mister man mye vekt på sykehjem, spesielt muskelmasse, så er det mye større risiko for å pådra seg sykdom, og kroppen har dårligere evne til å helbrede. Kanskje blir det en ond sirkel man aldri kommer ut av, og pasienten ender opp med forverret helsetilstand som følge av dårlig ernæring. Dette kan resultere i infeksjoner, dårligere hukommelse og mye mer.

En annen situasjon man skal være spesielt oppmerksom på for eldre som bor hjemme er hvis ektefellen dør. Tap av ektefelle fører ofte til mye sorg, ensomhet, depresjoner og redusert matlyst. Det er ikke uvanlig å gå ned i vekt etter en slik hendelse, og på samme måte som på et sykehjem, kan man havne inn i en ond sirkel. Spesielt menn er i faresonen her. Kanskje er det kona som ha stått for all matlaging, spesielt middagsmat. Mange eldre menn kan ikke å koke poteter en gang, og da kan man skjønne at det blir problematisk hvis kona dør. Middagen blir ofte erstattet med brødskiver, eller rett og slett ingenting. Dette er ting som familien må plukke opp. Det er ikke nødvendigvis sånn at man må sette i gang med store matlagingskurs. Ferdigmiddager kan være vel så bra, eller man kan sjekke opp om man kan benytte seg av «middag på døren» i regi av storkjøkken og hjemmehjelptjenester.

Som gammel skal man ha noen kg ekstra på kroppen, det er bare sunt! Blir man syk en dag så er kroppen mye bedre rustet for å takle sykdom om man veier et par kg for mye enn et par for lite. Selv om alle bør ha et kosthold med mye frukt, grønnsaker og fiber, så er det ikke alltid sånn at det er det man skal fokusere mest på hos de aller eldste, spesielt ikke hvis de er syke og/eller har lav vekt fra før. Da kan sjokoladekaka til ettermiddagskaffen være svært verdifull, og det å bytte ut lettrømme med sæterrømme kan være et viktig steg for å øke det totale energiinntaket i løpet av en dag. Sånt må man vurdere individuelt avhengig av hvilken situasjon den eldre er i, med tanke på sykdom, nåværende vekt, trivsel og fremtidsutsikter.

## Hva er viktigst?

Mitt budskap til deg er altså at man skal tenke gjennom og undersøke hvordan kostholdet og ernæringssituasjonen er hos dine gamle familiemedlemmer, og sette i gang tiltak dersom det er noe som ikke virker bra. Sett deg ned og slå av en prat, hør hva de selv har å si om appetitt og matinntak. Hjelp de å skjønne at det er sunt å ha litt fett på kroppen, og at det er viktig å både få i seg nok mat og å kose seg med maten. Ta en titt i kjøleskapet for å se hvordan situasjonen er der; er det mye gammel mat som har gått ut på dato? Går det i brødskiver med syltetøy? Hva med drikke? Har du en enslig besteforelder, foreslå at dere lager middag sammen en dag! Er han/hun plassert på sykehjem, så prat med personalet om hvor mye de spiser, og si fra hvis du vet om et favorittpålegg eller de har gitt uttrykk for at det er noe de ikke er helt fornøyd med. Man betaler en god del penger for å være på sykehjem, så riktig kosthold er det minste man skal forlange.

Vi lever stadig lengre, og det er viktig å huske at selv om man bikker 80 år, så trenger kroppen fortsatt mat og pleie for å holde oss gående. Ei dame på 80 kan fint leve 10 år til, men da trenger hun nok og riktig mat. Det er ikke alltid så lett å passe på sånt selv når man blir gammel, spesielt hvis man kommer i stressende situasjoner, som sykdom eller tap av ektefelle. Det er da vi som barn og barnebarn har ansvar for å følge opp, og da er mitt spørsmål til deg; gjør du det?

Sjekk også ut [Stine sin blogg](http://mat-helse.no/)!
