---
title: "Helse, et individuelt eller sosialt ansvar?"
author: "Ole Anders Brøndbo"
date: 2013.02.07
---

Maten vi spiser spiller i stor grad inn på helsen vår. Men hvem skal bestemme hva maten som ligger i butikken skal inneholde? Er det du og jeg? Er det produsentene? Eller skal staten og helsedirektoratet bidra på denne fronten, med reguleringer og andre strukturelle vedtak? I denne artikkelen vil jeg drøfte et par synspunkter angående dette.

I hvilken grad staten skal beskytte befolkningen? Allerede i dag eksisterer det en rekke lover som er til for å beskytte befolkningen på bekostning av vår frihet som enkeltindivider. Disse lovene tas i dag som selvfølgelige, men ikke alle ble oppfattet slik da de ble innført. Eksempler er våpenloven, alkoholloven og i denne sammenheng den relativt ferske røykeloven. Er det ønskelig at staten og helsedirektoratet styrer hva maten vi har tilgang til inneholder? Et argument for slike tiltak er at man når ut til hele befolkningen, noe som kan være effektivt dersom det er stor sannsynlighet for at det aktuelle tiltaket vil være gunstig for folkehelsen. Argumentene mot vil hovedsakelig omhandle de eventuelle innvirkningene tiltaketvil ha på vår frihet. Hvilke tiltak er aktuelle og hvor mye frihet er vi villige til å ofre? Er styrende tiltak eller forbud veien å gå?

## Transfett

Steen Stender snakket nylig om statlig styring av matvaretilgang under [LHL sin kostholdskonferanse](ldl-konferanse-2013.qmd). Under sin presentasjon la han frem hvordan en signifikant andel av den Danske befolkningen i 1994 fikk i seg over 5g transfett daglig. Allerede på denne tiden var det kjent at transfett var en stor bidragsyter til risikoen for å utvikle hjertesykdom. Etter press fra det danske helsedirektoratet, gikk matvareprodusentene over til andre fettyper. Endringen ga ønsket effekt, men det var fortsatt en subgruppe av den danske befolkningen som fremdeles fikk i seg ganske mye av dette fettet. Danske helsemyndigheter innførte i 2004 en lov om innholdet av transfett i mat. Salg av produkter hvor mer en 2% av fettinnholdet var transfett ble nå forbudt, og resultatet av dette er at det nå omtrent ikke finnes transfett i maten man får kjøpt i Danmark.

I Norge har vi per i dag ikke et slikt forbud, men produsentene er lovpålagt å informere om et produkt inneholder transfett. En av grunnene til at vi ikke har innført et forbud, er at inntaket av transfett i den norske befolkningen jevnt over er veldig lavt. Stender tok en liten runde i Oslo dagen før han holdt foredraget sitt. Med unntak av flere typer kjeks i innvandrerbutikker på Grønland i Oslo, fant han veldig lite. Disse kjeksproduktene var importert, og innholdt transfett i doser langt over de 2% av fettinnholdet som er satt som grensen i Danmark.

Grunnet det lave inntaket av transfett i befolkningen, vil mange argumentere for at transfett derfor ikke er et problem her i landet. Men husk at akkurat det samme var tilfelle i Danmark når man så på hele befolkningen under ett! Finnes det subgrupper i den norske befolkningen som fremdeles inntar større mengder transfett? Skal norske myndigheter følge Danmarks eksempel og ”redde” de som får i seg for mye transfett? Stender svarte langt på vei ja på dette spørsmålet!

Helsegevinsten må veies opp mot påvirkningen lovforslaget har for befolkningens frihet, selvstendighet og egenansvar. Det å forby salg av trans fett i Norge kan ses på som en bagatell med tanke på den begrensede tilgangen på produkter som inneholder transfett. På den andre siden kan det argumenteres for at en lov ikke vil påvirke befolkningen. I Danmark viste det seg at å gå fra trans fett til andre fettyper ikke hadde noen innvirkning på smak eller pris. Så hva har vi egentlig noe å tape ved å innføre en slik lov?  I paneldebatten som avsluttet konferansen sa hele panelet seg enig i at dette burde gjennomføres.

## Hvilke andre områder burde diskuteres?

Transfett er helt klart et helseproblem dersom vi får i oss for mye, men er det også andre områder myndighetene bør ta ansvar og gå inn og regulere? Som nevnt over så må en eventuell helsegevinst veies opp mot hvordan reguleringene påvirker befolkningen. Det er viktig å ivareta befolkningens autonomi og råderett over eget liv, samtidig som man har et ansvar for den samlede folkehelsen. Vi har alt å vinne på forbedring av folkehelsen, både økonomisk og ikke minst når det gjelder livskvaliteten til den enkelte. Her er et par punkter som kanskje burde være oppe for diskusjon.

### Sukker

Inntak av tomme kalorier er ofte sett på som en medvirkende årsak til fedme og overvekt. Nå er også sukker satt i forbindelse med risiko for å utvikle hjertesykdom og er regnet som verstingen av alle kostholdsfaktorene. En del matvarebutikker har forsøkt å påvirke forbrukerne ved å fjerne produkter med høyt sukkerinnhold fra kasseområdet, men er dette tiltak som burde styres ovenfra og dermed gjelde alle? Skal helsedirektoratet gå enda lenger for å begrense folks sukkerinntak? Avgiftsøkning er sannsynligvis ikke veien å gå, siden sukker er veldig rimelig og fortsatt vil være dette på tross av dette. Kan en regulering av salgsvolumene av sukkerholdig drikke være en ide? Eller forbud mot å selge godteri med leker inni rettet mot barn? Hva med å påvirke befolkningen til å i større grad velge produkter med [kunstig søtning](sotstoffer.qmd)?

### Endring av næringsinnhold i matvarer

Anna Haug la på LHLs kostholdskonferanse frem data på det at ved å endre innholdet i kraftforet som gis til kylling, kan du blant annet endre fettsammensetningen i kjøttet. Om soyaoljen i fôret byttes ut med raps- og linfrøolje, vil ikke kjøttet bare inneholde omega-6, men også en betydelig andel omega-3-fettsyrer! Når vi så spiser denne maten, så påvirker fettsyresammensetningen i kjøttet fettsyresammensetningen i vår egen kropp, så dette er også et tiltak som vil treffe store deler av befolkningen. Vi vet at [forholdet mellom omega-3 og omega-6](http://www.friskogfunksjonell.no/omega-3-og-omega-6-i-kostholdet/ "Omega-3 og Omega-6 i kostholdet") kan ha mye å si for helsen.

### Standardiserte innholdsfortegnelser

I USA har de en lov som gjør at alle matvareprodusenter må opplyse om varens innhold gjennom en standardisert innholdsfortegnelse, hvor det også stilles krav til skriftstørrelse. På denne måten skal det alltid være tydelig hva maten vi kjøper inneholder. Dette krever imidlertid opplysning og bevisstgjøring i befolkningen angående hva man skal se etter og hva man skal velge. Stender gjorde et poeng av at innholdsfortegnelsene ofte var skrevet med en ekstremt liten skrift, spesielt når innholdet i matvaren var så som så. Vil et slikt tiltak påvirke produsentene til å forbedre innholdet i matvarene?

## Konklusjon

Er vi villige til å sette begrensninger og endre på matvarene dersom helsedirektoratet kan påvise at endringen vil ha en helsemessig gevinst i befolkningen? Som ved innføringen av røykeloven kan dette i stor grad hvile på om befolkningen er overbevist om at endringen har en positiv helseeffekt.

**Hva mener dere: Er helse utelukkende et individuelt ansvar, eller kan det forsvares dersom myndighetene innfører tiltak som nevnt i artikkelen? Legg igjen din mening i kommentarfeltet!**
