---
title: "Hjernens Evolusjon"
author: "Kristian Fagerland"
date: 2013.02.25
---

Hvordan har det seg at mennesket har utviklet den største og mest komplekse hjernen av alle dyr på jorden? I denne artikkelen vil jeg prøve å gi deg en liten oversikt over hvordan denne utviklingen har skjedd.

Menneskehjernen har egentlig utviklet seg i tre steg, men først la oss gå tilbake til da livet startet på jorden.

## Steg 1

Livet på jorden startet for mange år siden i havet. De første levende strukturer vi kjenner til var encellede alger og bakterier som sirkulerte rundt i havets strømmer. Disse var først kun avhengig av sollys, men etter hvert som mat ble tilgjengelig la dette til rette for utvikling av multicellede organismer. Det ble nå gunstig å kunne forflytte seg fra et sted til et annet for å finne matkilder. Derfor mener vi at de multicellede organismene utviklet et enkelt nervesystem for nå å kunne bevege seg.

Dette var vårt første steg! Nemlig et enkelt nervesystem som styrte et enkelt bevegelsesapparat. De første organismene med et nervesystem var bittesmå larver med mulighet til å bevege seg. Nå med bedre evne til å bevege seg og flere matmuligheter, utviklet naturen komplekse og strukturerte organismer som maneter, fisk, osv.

## Steg 2

En del år senere på evolusjonsstigen ble det etter hvert mer attraktivt å bevege seg fra havet og opp på land. Her var det nå mer mat, og enda viktigere; mer oksygen. På land var det for øvrig en stor utfordring for oss. Her var det nemlig større tyngdekraft. For å kunne bevege seg i denne tyngdekraften måtte vi derfor utvikle et enda større nervesystem og bevegelsesapparat. De første dyrene som kunne bevege seg på land var reptiler.

## Steg 3

På land med masse oksygen og mat, satte nervesystemets utvikling fart. Mange nye arter utviklet seg. Mennesket stammer fra aperiket. Menneskets DNA er 99% likt sjimpansenes DNA. Da apene begynte å reise seg opp på to bein ble det enda mer påvirkning fra tyngdekraften, og nervesystemet måtte igjen utvikle seg. Dette er det 3. steget i menneskehjernens utvikling. Vi kvittet oss etter hvert med pelsen og fikk lengre armer og bein, noe som er ekstremt viktig for hjernens temperaturregulering. Nå med en hjerne som krevde mer energi, utviklet vi bedre kommunikasjon og håndkontroll for å lage redskaper og dermed var vi rustet til å få tak i den maten vi behøvde.

## Hjernens oppbygning

Menneskehjernen har utviklet seg lagvis. Den veier ca. 1.5 kg (2% av total kroppsmasse) og består av drøye 100 milliarder hjerneceller. De eldste senterne sitter i midten og utgjør hovedsakelig hjernestamme og lillehjerne. Disse er så å si like i alle dyr, og har forandret seg lite i et evolsjonsmessig perspektiv. Hovedforskjellen på vår hjerne og andre dyrs hjerner er de ytterste og evolusjonsmessig nyere delene. Disse har lagvis utviklet seg utover fra hjernestammen, og utgjør den såkalte storehjernen eller neocortex, som betyr den nye hjernen. Mennesket har den mektigste neocortexén i dyreriket. Den er avhengig av glukose og oksygen for å overleve, og i en voksen person forbruker den opp til 40% av kroppens energi (60% hos barn i utvikling). Dvs. ca. 40% av all næring vi inntar og luft vi puster skal opp til hjernen. Derfor er det også viktig med frisk luft og et stabilt blodsukker.

Av de ”nyere” delene i menneskehjernen er det de pre-frontale og de frontale lappene som hovedsakelig gir oss atferd. Disse gjør at vi kan ha målrettet atferd, ha tålmodighet, impulskontroll, kommunikasjon, med mer. Innen atferdsproblematikken, som jeg er spesielt interessert i, ser vi at det er disse som ofte svikter funksjonelt.

## Hvor er vi nå?

Det som er utrolig spennende med hjernens evolusjon er at bevegelse er hovedgrunnen til at vi i dag har en hjerne. Hadde vi ikke trengt å bevege oss, hadde vi aldri fått den hjernen vi i dag har. Dette er et viktig element i all nevrologisk rehabilitering, atferdsproblemer inkludert.

Vi vet at inaktive barn og voksne får et dårlig nervesystem, og en uønsket atferd. Forskning anbefaler derfor både voksne og barn å være i fysisk aktivitet minst 1-2 timer hver dag. Mange av oss klarer dessverre ikke å oppnå dette. Derfor spekuleres det i mange fagmiljøer om vi utvikler oss i feil retning. Aldri tidligere har vi sett mer livsstilsykdommer enn det vi gjør nå. De yngste generasjonene klarer ikke lenger å overleve sine foreldres generasjoner.

Kanskje noe av forklaringen er at vi stresser mer, beveger oss mindre og spiser dårligere mat enn vi tidligere gjorde? Det er på tide med en global helse-reform!
