---
title: "Hvorfor er vi så feite?"
date: 2013.06.03
---

For å legge på seg, altså å øke kroppens energilagre, må man være i [energioverskudd](energibalansen.qmd "Energibalansen – hva sier den egentlig?"). Dette er et kriterie for å kunne gå opp i vekt, og er grunnlaget for forklaringen om at en overvektig på et eller annet tidspunkt har spist mer energi enn han/hun har forbrukt, noe som har lagt forholdene til rette for at kroppsvekten kunne øke. Ettersom energi ikke kan oppstå av seg selv, så er det rett og slett ikke mulig å legge på seg dersom dette kriteriet ikke er oppfylt. Løsningen som presenteres blir derfor å gjøre det motsatte, altså spise mindre og trene mer. Men hvor nyttig er denne strategien? I denne bloggposten vil jeg dele noen tanker rundt disse temaene.

## Forklarer energioverskuddet overvekten?

Dersom du har gått opp i vekt, så har du nødvendigvis spist mer enn du trengte. Dette er en beskrivelse av hva som fysiologisk ligger til grunn for at akkumulering av fett skal være mulig. Så på mange måter er dette en direkte, kausal forklaring på hva som har skjedd. Men til tross for at dette beskriver en direkte årsakssammenheng mellom energibalansen og vektutviklingen, sier det ingenting om hvilke faktorer som ligger til grunn.

Den vanlige løsningen om å bevege seg mer og spise mindre spiller på at det er folks latskap og grådighet som ligger til grunn for overvekten. Selv om dette vil stemme i flere tilfeller, der det å ta seg sammen faktisk vil være tilstrekkelig, så er det også mange tilfeller der dette ikke er spesielt nyttig, verken som forklaringsmodell eller løsning på problemet. Andrea har nylig skrevet [en flott artikkel](livsstil-latskap.qmd) der hun tar for seg psykologien bak det å gjøre livsstilsendringer, og forklarer der hvorfor dette ikke nødvendigvis er så enkelt.

## Hvorfor spiser vi for mye?

Det første spørmålet man bør stille seg er hva som er årsaken til at man har spist for mye. Her vil løsningen ligge hos veldig mange. Å vite at man har spist for mye har begrenset nytteverdi, mens det å finne ut hvorfor man har spist for mye kan være kjempeviktig. Her er det mange muligheter, og det å finne ut hva som ligger til grunn hos den enkelte vil være essensielt for å kunne finne den beste løsningen. Å tilpasse løsningen til individet vil i alle tilfeller være bedre enn å tilpasse individet til en forhåndsbestemt løsning!

Mange vil argumentere for at det er det at vi spiser feil mat som gjør at vi legger på oss. Dette kan på mange måter stemme, ettersom ulik mat utvilsomt har ulik effekt på hvor mette vi blir. Dette kan handle om egenskaper ved maten som smak, eller fysiologiske responser som eksempelvis blodsukkerstigning med påfølgende fall. Jeg har tidligere [skrevet om en studie](spise-saktere.qmd) som fant en økt risiko for å utvikle diabetes type 2 hos de som spiste raskest, som antas å henge sammen med at det å spise fort er forbundet med å spise mer. Kanskje kan noen matvarer gjøre det enklere å spise mye energi på kort tid, noe som bidrar til å øke energiinntaket. For eksempel så vil det gå mye raskere å spise 1000 kalorier fra en hamburgermeny fra McDonalds enn å få i seg den samme energimengden fra biff, poteter og brokkoli. Det samme gjelder [energi i flytende form](flytende-karbohydrater.qmd), og da spesielt sukkerholdige drikker, som kan bidra med mye energi på kort tid uten å mette noe særlig.

En annen konsekvens av å spise mye dårlig og næringsfattig mat er at dette ikke nødvendigvis gir den største følelsen av overskudd. Dette kan bidra til redusert aktivitetsnivå i form av at sofaen og godstolen blir ekstra fristende. Aller helst skulle vi alle sittet minst mulig, men er man trøtt, sliten og generelt mangler overskudd så er det ikke alltid like lett. I stedet så sitter vi i bilen, sitter på jobben og sitter enda litt til når vi kommer hjem. Kanskje burde vi alle benyttet oss av [underholdningsslavens redning](underholdningsslavens-redning.qmd)?

## Hva er så feil mat?

Dersom det er slik at vi spiser for mye fordi vi velger feil mat, så gjenstår et svært viktig spørsmål: Hva er riktig og hva er feil mat? Her vil du få ulikt svar alt etter hvem du spør. Hos en person vil du få høre at mat med mye fett er energirik og selvfølgelig er hovedgrunnen til økt energiinntak. Hos en annen vil du høre at karbohydrater stimulerer insulin, og at det er dette som gjør oss overvektige. En tredje person vil fortelle deg at verken karbohydrater eller fett er så galt i seg selv, men at kombinasjonen av disse i samme måltid er grunnen til at vi legger på oss.

I utgangspunktet er det derfor vanskelig å klassifisere mat som feil eller riktig, [sunn eller usunn](sunn-usunn-kontekst.qmd), på bakgrunn av hvilke næringsstoffer den inneholder. Kanskje er det først og fremst andre egenskaper med maten som som avgjør hva som er lurt å spise mer og mindre av. Sunn fornuft vil diktere at det å spise fastfood mange ganger i uken ikke er en spesielt bærekraftig plan, og at brus ikke er det beste helsemessige valget som tørstedrikk. Det er tross alt det du spiser mesteparten av tiden som avgjør mesteparten av resultatet, så det er her fokuset burde ligge!

Selvfølgelig er det ikke likegyldig hva vi spiser, men bildet er kanskje litt mer nyansert enn det de fleste ønsker å innse. Det er enkelte tiltak som har en tendens til å fungere, og som kan anbefales nesten uavhengig av hvordan kostholdet ser ut i utgangspunktet. Å øke inntaket av grønnsaker, velge proteinrik mat og å kutte ned på inntaket av sukker, potetgull, godteri og annet snacks er råd som sjelden slår feil. Er målet å begrense inntaket av kalorier så har jeg skrevet [en sak](lite-nok-mat.qmd) om hvordan du med enkle grep kan få til dette, forankret i de nevnte rådene. Vi kommer ikke bort fra at [lavkarbo](lavkarbo-livsstil.qmd) for mange er en svært effektiv måte å gå ned i vekt på, men det betyr ikke at dette er den beste løsningen for alle. Vi er forskjellige, har ulike preferanser og vil trenge ulike verktøy for å finne noe som fungerer. I alle tilfeller er det gode grunner for å [spise variert](spise-variert,qmd), ettersom dette er den beste måten å sikre at man dekker alle behovene for næringsstoffer.

## Stikker problemet enda dypere?

Overvekt kommer som nevnt som en direkte konsekvens av at man har vært i positiv energibalanse. Jeg har fortalt om noen mulige ting som kan ligge til grunn for hvorfor man ender opp med å spise for mye, og en plausibel forklaring er at vi gjør dårlige valg i matveien. Dette burde teoretisk sett være en smal sak å gjøre noe med, men som Andrea skrev om i sin sak så er det ikke alltid så lett å gjøre endringer i livsstilen. Vi har en tendens til å gå på autopilot når vi tar valg i hverdagen, og vaner er vonde å vende.

Jeg skrev innledningsvis at det å finne ut hva som var årsaken til at man har spist for mye er sentralt for å kunne gjøre noe med det. Å tvinge seg selv til å spise mindre vil ikke nødvendigvis gjøre noe med disse. Men hvis vi da kommer frem til at en person spiser for mye fordi han/hun gjør dårlige valg i matveien, da burde det jo være en smal sak å gjøre noe med dette? I teorien så burde det hvertfall være det, men vi vet av erfaring at det å slanke voksne mennesker på tradisjonelt vis er fryktelig vanskelig, hvertfall i gjennomsnitt. Det å informere om hva som er fornuftige valg og hva som skal til for å gå ned i vekt har en viss effekt, men i lengden er suksessraten svært begrenset.

Det neste naturlige steget er da å stille seg spørsmålet om hvorfor denne personen gjør dårlige valg i matveien. Først da vil man ha godt grunnlag for å tilpasse en god løsning til denne personen. Kanskje handler det ikke i det hele tatt om mangel på kunnskaper om hva som er en sunn livsstil. I mange tilfeller ligger det nok noe helt annet til grunn for hvorfor vi tar valgene vi tar. Vi vet at mennesket har en tendens til å foretrekke umiddelbar belønning fremfor belønning som ligger lenger fremme i tid, og dette kan nok i stor grad relateres til mange som sliter med overvekt. Dersom man for eksempel er deprimert, så er det sannsynlig at trøsten i å velge feil mat i dag veier tyngre enn belønningen av å velge rett mat på sikt. Depresjon er selvfølgelig bare et eksempel av fryktelig mange underliggende problemer som den enkelte kan ha, det kunne like gjerne vært noe annet.

I dette eksempelet kan vi si at depresjonen er et større problem enn overvekten, og at det å ta tak i vektproblemene kan være uoverkommelig så lenge depresjonen er der. De fleste overvektige ønsker jo ikke å være så store som de er, men det kan altså være mye annet enn latskap og mangel på viljestyrke som gjør at de ikke klarer å gjøre noe med det. Av denne grunn er det veldig viktig å kartlegge slike ting, og kanskje burde vi i større grad enn i dag vendt oss mot psykologene i behandlingen av sykelig overvekt og fedme?

## Så, hvorfor er vi så feite?

Det jeg ønsket å understreke med dette blogginnlegget var at selv om vi vet hva som forårsaker overvekt rent fysiologisk, så forklarer det ikke hva som er de underliggende årsakene til at en person blir overvektig. Hos veldig mange handler det om prioriteringer og vaner, og tiltakene som skal til trenger ikke å være omfattende i det hele tatt. Hos andre kan overvekten komme som en konsekvens av underliggende problematikk, som det vil være viktig å ta hånd om før man kan ha håp om å få til å gjøre de endringene som trengs.

Når det gjelder livsstil så er det meste fryktelig individuelt, og individrettede tiltak er derfor ytterst nødvendig. Disse må forankres i hva som er problemene til den enkelte, og kartlegging av dette er kanskje det aller viktigste i en slik prosess. En ting er sikkert, det er ikke sånn at alle overvektige er late og mangler viljestyrke!
