---
title: "Ikke-cøliakisk glutenintoleranse"
date: 2014.05.22
---

Kan også personer uten cøliaki reagere på gluten? De siste dagene har fenomenet ikke-cøliakisk glutenintoleranse blitt viet en del oppmerksomhet i media. Forskergruppen som først fant ut at også mennesker uten cøliaki kunne få negative reaksjoner på gluten har nemlig i en påfølgende studie funnet indikasjoner på at konklusjonene de trakk i første omgang kanskje ikke kunne rettferdiggjøres likevel. 

## Ikke-cøliakisk glutenintoleranse

Gluten er kort fortalt et protein vi finner i kornslag som hvete, rug og bygg og i mat som er laget på disse. At gluten skaper problemer for de som har [cøliaki](coliaki.qmd "Cøliaki")er godt kjent, men det har vært spekulert i om gluten også kan være problematisk for personer uten cøliaki. [Glutenfri diett](kosthold-institusjoner/glutenfritt.qmd "Glutenfri kost") har derfor i mange tilfeller blitt anbefalt til folk med diverse symptomer relatert til mage/tarm, uten at det har forelagt noe evidens for at dette skulle ha noe for seg. Hvorvidt gluten i seg selv kunne være en årsak til disse symptomene var det ingen som visste.

Dette var bakgrunnen for en studie gjennomført i 2011 av Peter Gibson og medarbeidere ved Monash University i Australia (1). Dette var en dobbeltblindet, placebokontrollert studie, og studiedeltakerne hadde [irritabel tarm](irritabel-tarm-behandling.qmd "Irritabel tarm – hvordan behandles det?"), men ikke cøliaki. På forhånd hadde alle deltakerne sine symptomer under kontroll på en glutenfri diett, og studien skulle undersøke hvorvidt reintroduksjon av gluten ville gjøre at symptomene kom tilbake.

Totalt var det 34 deltakere, hovedsakelig kvinner, som startet forsøket. Alle disse fulgte en glutenfri basisdiett i 6 uker, i tillegg til to brødskiver og en muffins daglig, med eller uten gluten. 19 deltakere fikk gluten, mens 15 fikk glutenfritt. I glutengruppen var det 13 deltakere (68%) som opplevde symptomer, mens 6 deltakere (40%) i placebogruppen rapporterte om det samme. Det var en statistisk signifikant høyere forekomst av symptomer blant dem som fikk gluten, og dermed konkluderte forfatterne med at ikke-cøliakisk glutenintoleranse kunne være et ekte fenomen, selv om denne studien i seg selv ikke var nok til å bekrefte dette.

## Ikke ikke-cøliakisk glutenintoleranse likevel?

Den siste tiden har det vært en del overskrifter i media som indikerer at ikke-cøliakisk glutenintoleranse kanskje ikke finnes likevel. Dette er basert på en oppfølgingsstudie av samme forfattere, publisert i august i fjor. Som gode forskere var nemlig ikke Gibson og kompani overbevist om at resultatene fra den første studien stod for seg selv, så de igangsatte et nytt eksperiment (2). Denne gangen inkluderte de 40 deltakere som alle hadde irritabel tarm og selvrapportert ikke-cøliakisk glutenintoleranse, og ville undersøke hvorvidt gluten virkelig gav symptomer hos disse personene.

Etter å ha fulgt sitt vanlige kosthold i en uke ble deltakerne randomisert i tre grupper som alle først fikk en [FODMAP-redusert](irritabel-tarm.qmd "Irritabel tarm og hva du kan gjøre med det!") og glutenfri diett i 2 uker for å oppnå symptomfrihet. Deretter fortsatte deltakerne på denne dietten, men fikk i tillegg ulik mengde gluten i en uke. Høyglutengruppen fikk 16g gluten, lavglutengruppen fikk 2g gluten og 14g melkeprotein mens placebogruppen fikk 16g melkeprotein. Etter at deltakerne hadde vært gjennom en intervensjon, ventet de to uker før de prøvde neste. Alle hovedmåltider ble laget på studiestedet og levert til hver enkelt deltaker.

Av de 40 deltakerne var det 3 som ikke klarte å få symptomene under kontroll under de første to ukene, og derfor droppet ut. De 37 resterende deltakerne gjennomførte alle diettene. Det var imidlertid to tilfeller der deltakere avsluttet en av studiediettene tidlig grunnet sterke symptomer, en i løpet av placebodietten og en under høyglutendietten.

Sammenlignet med deltakernes vanlige kosthold, ble det observert en forbedring i symptomene i de to ukene de fulgte en FODMAP-redusert diett. Når de så analyserte effekten av de tre intervensjonsdiettene, begynte symptomene å komme tilbake. Det var imidlertid ingen klar sammenheng med inntak av gluten. Bare 6 av de 37 deltakerne opplevde symptomer under høyglutendietten, men halvparten av disse opplevde symptomer også av placebodietten. Det var altså bare 3 av de 37 deltakerne som hadde symptomer eksklusivt til høygluten. 11 av deltakerne opplevde symptomer etter placebodietten.

Etter hovedforsøket ble deltakerne invitert til å delta på en ny runde, men denne gangen skulle hver diett bare testes i tre dager, og bakgrunnsdiettene var mye strengere med tanke på andre ting som kunne gi symptomer (de var blant annet fri for melk og en rekke tilsetningsstoffer som det er mulig å reagere på). De tre intervensjonene var nå 16g gluten, 16g melkeprotein eller ingenting. 22 av deltakerne takket ja til dette, deriblant 2 av de som utelukkende reagerte på gluten i det første forsøket. I dette forsøket var det 2 som utelukkende rapporterte om symptomer etter høyglutendietten, men det var ikke de samme som rapporterte dette etter det første forsøket.

## Hvor står vi nå?

Dersom gluten forårsaket symptomene hos disse personene så ville man forvente at det å spise glutenfritt ville gjøre dem symptomfrie, og at introduksjon av gluten ville gjøre at symptomene kom tilbake. Det første poenget forfatterne tar frem i diskusjonen er at selv om ikke alle deltakerne var symptomfrie til tross for at de fulgte en glutenfri diett i utgangspunktet, viste alle en markant forbedring ved å redusere inntaket av FODMAPs. Når man i tillegg ikke klarte å dokumentere noen sammenheng mellom glutenprovokasjon og symptomer, fant forfatterne ikke noen gode holdepunkter for at gluten hadde noe med symptomene å gjøre.

Denne studien taler forfatternes første studie tvert imot, og flere mulige årsaker blir tatt opp. For det første var den nye studien bedre kontrollert med tanke på FODMAP. Den første studien var heller ikke en kryssoverstudie der deltakerne prøvde alle de ulike diettene, noe som er en styrke med sistnevnte. Det faktum at det ble observert symptomer etter alle intervensjonsdiettene tyder på en såkalt noceboeffekt, som betyr at man opplever symptomer fordi man forventet at man kom til å gjøre det.

Det er selvfølgelig ikke mulig å utifra denne studien slå fast at ikke-cøliakisk glutenintoleranse ikke eksisterer, men resultatene peker mot at dette i hvert fall er svært uvanlig. En stor styrke med denne studien er kryssoverdesignet og at det ble gjennomført et oppfølgingseksperiment. Hvis gluten hadde vært en årsak til symptomene blant disse pasientene så ville man forvente å finne mer entydige resultater, men det gjorde de altså ikke. Dette var en liten studie, og selv om deltakerne var høyst selektert på forhånd så er det selvfølgelig mulig at en ny studie med andre deltakere ville gitt et annet resultat.

Per dags dato er dokumentasjonen for ikke-cøliakisk glutenintoleranse svak, og ut fra dataene som foreligger er det mest sannsynlig andre ting enn gluten som forårsaker symptomene hos de fleste som mener de reagerer på gluten. Likevel, opplever man å bli symptomfri på en glutenfri diett, så er det jo fremdeles dette som er det viktigste. Likevel er det viktig å finne ut hva som skaper plagene i utgangspunktet, slik at dette kan behandles på en stadig bedre måte!

Referanser:

1.  Biesiekierski JR, Newnham ED, Irving PM, Barrett JS, Haines M, Doecke JD, Shepherd SJ, Muir JG, Gibson PR: **Gluten causes gastrointestinal symptoms in subjects without celiac disease: a double-blind randomized placebo-controlled trial**. *The American journal of gastroenterology* 2011, **106**(3):508-514; quiz 515.

2.  Biesiekierski JR, Peters SL, Newnham ED, Rosella O, Muir JG, Gibson PR: **No effects of gluten in patients with self-reported non-celiac gluten sensitivity after dietary reduction of fermentable, poorly absorbed, short-chain carbohydrates**. *Gastroenterology* 2013, **145**(2):320-328 e321-323.
