---
title: "Intervju i VOF"
date: 2012.11.28
---

I årets siste nummer av magasinet [Vitenskap og Fornuft](http://www.vof.no) ble jeg intervjuet i deres intevjuserie om myndighetenes kosthold. Her vil jeg gjengi intervjuet i sin helhet, slik at dere lesere kan se hva jeg svarte. Tar forbehold om at enkelte formuleringer kan være forskjellig fra det som ble publisert i bladet

#### 1. Hva er din oppfatning av de statlige kostrådene, som anbefaler en karbohydratandel på opp mot 60 % av energien og et fettinntak på omkring 30 %?

I utgangspunktet ser jeg ikke så store problemer med de offentlige rådene sånn som de er i dag, og er overbevist om at dersom hele befolkningen faktisk fulgte disse rådene så ville det gitt et solid løft for folkehelsen. Når det er sagt, så mener jeg også at det å se på de offentlige rådene som individuelle retningslinjer ikke blir helt riktig, og det er viktig å skille mellom kostråd til enkeltindivider og kostråd til større grupper.

Kosthold er individuelt, og må tilpasses individet og dets livsstil og målsetning. Spesielt gjelder dette kanskje karbohydratinntaket, som bør tilpasses aktivitetsnivået. For en inaktiv person vil et karbohydratbasert kosthold være lite gunstig, mens en høyaktiv person har bedre forutsetninger for å tåle dette på en god måte.

#### 2. Når begynte du å engasjere deg i ernæringsdebatten, og i hvilken grad har du endret standpunkt?

Jeg har vært interessert i ernæring og helse lenge, men mitt engasjement i ernæringsdebatten startet i løpet av mitt første studieår. En medisinstudent som studerte parallelt med meg testet ut et ketogent kosthold over en periode, noe som gjorde at jeg ble nysgjerrig i å utforske den andre siden av debatten. Etter jeg startet opp Frisk og Funksjonell høsten 2011 har engasjementet mitt økt betydelig. Jeg har i utgangspunktet ikke endret standpunkt, annet enn at jeg har blitt mer og mer klar på at kostholdet må tilpasses til hver enkelt, og at det ikke er en oppskrift som passer for alle.

#### 3. På hvilket grunnlag har du dannet deg en oppfatning om hva folk flest bør spise? Kliniske erfaringer med pasienter, egen forskning, studier og/eller egenerfaringer?

Som student er det begrenset hva jeg har hatt mulighet til å gjøre meg av kliniske erfaringer. Min oppfatning av hva folk flest bør spise baseres hovedsakelig på egenerfaringer, det jeg vil kalle sunn fornuft og kunnskaper om menneskets fysiologi. I tillegg har jeg også prøvd ut ulike måter å spise på, og konkludert med at det er mange veier til Rom, og at trivsel er et enormt viktig aspekt ved kostholdet.

#### 4. Hvilken faglig vurdering har du når det gjelder betydningen av mettet fett og kolesterol i kosten?

Kolesterol i kosten har en svært liten betydning for kolesterol i blodet, så her ser jeg ingen god grunn til å frykte et normalt inntak. Når det gjelder mettet fett så er forskningen motstridende, men gjennomgangsmelodien for de siste store kunnskapsoppsummeringene konkluderer hvertfall med at det ikke er noe mål å begrense dette for mye, og hovedfokuset bør etter min mening heller ikke ligge her.

Det er holdepunkter for at det å bytte ut mettet fett med flerumettet gir en redusert sykdomsrisiko, men samtidig er det også grenser for hvor mye umettet fett vi bør spise. Ut ifra det jeg vet og tror i dag vil jeg påstå at frykten for mettet fett er overdrevet, men samtidig er jeg veldig åpen for videre forskning. Et poeng jeg vil dra frem er at forskningen på mettet fett er gjort innenfor rammen av et alminnelig, vestlig kosthold med mye karbohydrater. Vil mettet fett ha andre effekter i kontekst av et høyfettkosthold?

[Les Hanne Storhaug sin vurdering av rådene om mettet fett.](brokenlink/de-offentlige-anbefalingene-for-fett-godt-begrunnet/ "De offentlige anbefalingene for fett, godt begrunnet?")

#### 5. Hvis du skulle gi generelle kostholdsråd til befolkningen, hvordan ville du formulert deg?

Kostholdet bør være variert og baseres på lite bearbeidet mat. Velg rene råvarer fremfor hel- og halvfabrikata, så har du kommet langt. La grønnsaker, kjøtt, fisk, egg, meieriprodukter og frukt/bær være basisen i kostholdet ditt. Velg fullkorn og reduser inntaket av tilsatt sukker og fint mel så mye som praktisk mulig. Fokuser på det du spiser mesteparten av tiden og ikke vær redd for å skeie ut innimellom.

#### 6. Enkelte mener at vi står overfor et paradigmeskifte innen ernæring. Hva tror du skal til før de offisielle anbefalingene endres, og når kommer dette til å skje?

Paradigmeskifte er et sterkt ord! Jeg tror helt klart at det kommer endringer, men samtidig tror jeg ikke at de blir så drastiske. Mer nyanserte og mindre skråsikre utspill fra begge sider av debatten må til for å få til en endring. Det er tross alt en del ting de aller fleste er enige om, så et økt fokus på disse tingene i første omgang vil være et steg i riktig retning. Jeg syns også det er et poeng at kostråd til befolkningen bør være matvarebaserte, så det å styre debatten litt bort fra karbohydrater vs. fett vil også være nyttig i det lange løp.

Et økt fokus på kontekst tror jeg også kommer til å prege fremtidens kostråd, der man gir råd ut ifra den enkeltes livssituasjon fremfor å gi samme råd til alle. Det er også mye spennende forskning på gennivå, så kanskje vi i fremtiden til og med kan gi personlige kostråd basert på genene våre?

#### 7. Tilhører du dem som mener at vi fortsatt trenger mye mer forskning før vi kan konkludere at folk flest er bedre tilpasset et kosthold med et lavt til moderat innhold av karbohydrater enn et kosthold med opptil 60 energiprosent? Begrunn kort.

Selv om vi vet mye om kosthold, så finnes det på ingen måte en fasit! Kostholdsforskning er svært vanskelig, og siden det er så mange variabler involvert så er det problematisk å få til gode studier i realistiske situasjoner. Opp gjennom vår evolusjon har mennesket tilpasset seg et bredt spekter av kosthold, og det er liten tvil om at vi i mesteparten av denne perioden har spist langt mindre karbohydrater enn i dag. I mine øyne bør karbohydratinntaket tilpasses aktivitetsnivået, og når vi vet at folk flest ikke er spesielt aktive så er det nærliggende å tro at de fleste vil oppleve en positiv helseeffekt ved å redusere inntaket av karbohydrater noe sammenlignet med dagens inntak. Hvilket kosthold som gir optimal helse vil til syvende og sist være individuelt.

**Har du innspill, kommentarer eller ønsker å diskutere noen av spørsmålene, så tar jeg gjerne diskusjoner i kommentarfeltet!**
