---
title: "Irritabel tarm og matintoleranse - en pasienthistorie"
author: "Martin Darre Longva"
date: 2013.02.28
---

Jeg ønsker å dele litt av min historie fordi jeg vet at den kan angå så mange som 30-40% av befolkningen. Selv om jeg i dag er  symptomfri, kunne mitt møte med helsevesenet spart meg for mange bekymringer, hvis norske leger hadde vært bedre informert (og interessert?) i internasjonal forskning på området. Sist, men ikke minst, ønsker jeg å bidra til at ”tabuet” rundt folkesykdommen irritabel tarmsyndrom/matintoleranse brytes ned. Dette er noe svært mange har, men svært få vil snakke om. Resultatet er ofte nedsatt livskvalitet og psykiske problemer.

[Les mer om irritabel tarm her](irritabel-tarm-behandling.qmd "Irritabel tarm – hvordan behandles det?")

## Min historie

Da fastlegen ikke umiddelbart fant noe galt med meg, ble jeg sendt videre til en spesialist, som henviste meg videre til Haukeland sykehus i Bergen. Disse tok nye prøver og sendte meg tilbake til fastlegen igjen. Hele denne runddansen tok godt og vel et par år. Ingen steder følte jeg meg virkelig tatt på alvor. I det store og hele virket legene til å ha lite å bidra med. Det virket rett og slett som om flere av dem var uinteresserte, og trodde at dette var noe jeg innbilte meg.

I mellomtiden hadde situasjonen begynt å tære både på humøret og tålmodigheten. Jeg begynte rett og slett å lure på om dette virkelig var noe jeg innbilte meg. Det gikk så langt som at jeg i tre måneder gikk på antidepressive piller for å sjekke om dette var hjernen min som spilte meg et puss. I denne perioden følte jeg meg riktignok mer likegyldig til situasjonen, men symptomene var og ble de samme. Det virket i midlertidig hele tiden som om symptomene mine ble utløst av visse typer mat/drikke. Dette hadde jeg også tatt opp med legene, men da alle ”vanlige” allergitester var negative, fikk jeg beskjed om at ”det ikke var grunnlag for å gjøre noen kostholdsgrep”. Likevel forsøkte jeg meg fram, gjennom å kutte ut diverse matvarer som melk, hvete, gjær osv. Dette bedret situasjonen noe, men ikke helt. Symptomene kom og gikk, uten at det tilsynelatende fantes noe mønster.

## FODMAP?

Gjennombruddet for min del da jeg ved en tilfeldighet snublet over teorien om FODMAP på nettet. For første gang kunne jeg se en sammenheng mellom symptomene, og inntak av visse typer mat. Dette hjalp meg mye, ikke minst mentalt. Endelig kunne jeg slå meg til ro med at mageproblemene hadde en fysisk årsak, og at jeg tross alt ikke var alvorlig syk.

Likevel ble ikke FODMAP-redusert diett en endelig løsning for min del. Selv om situasjonen bedret seg ganske mye, opplevde jeg tidvis likevel symptomer. Slik jeg opplever det, må irritabel tarmsyndrom derfor også sees i sammenheng med tilstander som fruktosemalabsorbsjon, og matintoleranse som en forsinket immunrespons. Det er også nyere forskning som tyder på at dette er tilfelle. For eksempel tåler jeg personlig ikke laktosefri melk, selv om dette skal være greit ifølge Fodmap-dietten. Symptomene trenger da heller ikke nødvendigvis å komme bare fra magen, men gjerne også fra huden (eksem), eller hodet (svimmelhet/tretthet).

[Les mer om FODMAP her](irritabel-tarm.qmd "Irritabel tarm og hva du kan gjøre med det!")

**Mye tyder på at maten vi spiser, har langt mer å si for helsa vår enn vi tidligere var klar over!**

Hvis du har spørsmål, eller ønsker å vite mer om min historie, ta gjerne kontakt på [www.mage.no](http://www.mage.no).

Med vennlig hilsen Martin Darre Longva
