---
title: "Juleferie og juleflesk"
date: 2012.12.14
---

Nå er vi der igjen. Desember, måneden de fleste av oss forlater litt tyngre enn vi var da den startet. Hva er det som gjør at man lett legger på seg i julen, og er det noe vi kan gjøre for å motvirke dette? Er dette i det hele tatt noe vi burde fokusere på? Dette er temaene som diskuteres i denne artikkelen.

Julen er tiden for familie og kos. Vi løper fra familiebesøk til julebord, og hvor enn vi kommer er det god mat, og mye av den. Når gradestokken viser blå temperatur er det ekstra godt å sitte inne under teppet og kose seg med en kopp kakao, selvfølgelig med krem! Når kalenderen viser januar, så har det gjerne skjedd ett og annet, og badevekten stopper ikke lenger der du husker at den pleide å gjøre. De berømte julekiloene har kommet, og det er på tide med full panikk! Eller?

## Hvorfor kommer julekiloene?

Som jeg har skrevet om tidligere, i artikkelen om [energibalansen](energibalansen.qmd), så er kroppsvekten et uttrykk for alt kroppen vår består av. Mye av vekten utgjøres av vann, og ved å endre på vannbalansen kan dette gi ganske store utslag på vekten over korte tidsrom. Vi består også av muskler og fett, og endringer i disse kommer som følge av ubalanser mellom inntak og forbruk av energi.

Det er begrenset hvor mye fett du klarer å legge på deg på såpass kort tid som en juleferie, så i første omgang kan du trøste deg med at mesteparten av julekiloene består av gode, gamle H2O. Dette kan skyldes at julemat generelt inneholder en del salt, noe som gjør at du på kort sikt vil holde på mer vann. Dette vil forsvinne tilsvarende fort når du kommer tilbake i gamle vaner.

## 6 enkle tips for å unngå å legge på seg unødvendig fett

Som nevnt over så vil det å legge på seg fett komme som et resultat av at inntaket overskrider forbruket. Med store julemiddager med påfølgende dessert, etterfulgt av kaffe, kake og kos på kveldene blir energiinntaket raskt ganske høyt. Å øke aktivitetsnivået nok til å kompensere for det økte inntaket er en løsning, men for de fleste er dette urealistisk i en hektisk juletid. Resultatet blir at den overflødige energien lagres på kroppen som fett.

Det er imidlertid et par triks du kan benytte deg av for å redusere oppsamlingen av juleflesk, og her kommer noen av dem:

### Periodisk faste

Dersom du planlegger et større matinntak på ettermiddagen, f.eks. i et familiebesøk, så kan du redusere inntaket tidligere på dagen. På denne måten sparer du inn en del av dagens kalorier på en tid av dagen, og kan spise mer på kvelden uten at totalen øker så mye. I fjor skrev jeg en sak om nettopp å bruke [periodisk faste](brokenlink/periodisk-faste-til-jul/) som verktøy på denne måten.

### Finn alternativer til sukker

Søt mat og sukker hører julen til, men her er det muligheter for å gjøre bedre valg. Vanlig brus kan uten problemer byttes ut med en lettvariant, og i bakst går det an å bytte ut (noe av) sukkeret med erstatningsprodukter som sukrin.

Les mer om [søtstoffer](sotstoffer.qmd).

### Gode snacksalternativer

All kveldskosen trenger ikke å være sentrert rundt kake og godteri, det finnes alternativer. Frukt, bær, nøtter og mørk sjokolade er generelt sett bedre alternativer. Klementiner og appelsiner er klassisk julesnop, og det samme er tørket frukt som fiken og dadler. Som nevnt i punket over så går det også an å lage kaker med mindre sukker.

### Forsyn deg godt med proteinkilden til middag

Julemiddager inneholder tradisjonelt sett en god proteinkilde, som f.eks. kan være svineribbe, pinnekjøtt eller fisk. Dette metter bedre enn tilbehøret, så ved å velge mer av dette og heller redusere litt på tilbehøret så kan du oppnå større metthet, som også kan bidra til at du reduserer inntaket av søtsaker senere på kvelden!

### Finn måter å øke hverdagsaktiviteten

Selv om det er juleferie så trenger du ikke å sitte i ro hele dagen. Familiebesøket er gjerne på kveldstid, så det er ingenting i veien for å legge inn litt aktivitet på formiddagen. For de som er heldig og har snø kan en skitur, eller kanskje noen timer i akebakken, være en hyggelig måte å svi av litt kalorier. Ellers så vil jo også julehandel og andre forberedelser gi muligheter til å slite ut noen trappetrinn og skosåler.

### Ikke dropp treningen fordi det er ferie

Økt matinntak kan gjøre underverker for resultatene på trening. De som driver med styrketrening har gjerne erfart at ekstra mat gir ekstra trykk i kroppen, og dette er noe du bør utnytte. Kanskje er juleferien tiden for å sette en ny rekord?

## Det er jo jul bare en gang i året

Dette er et veldig viktig poeng oppi det hele. Du trenger ikke å la slankingen eller måteholdet få hovedfokus akkurat i juleuken. Dette har du 51 andre uker å bruke på! Julen er tiden for familie og kos, og **du trenger ikke å ha dårlig samvittighet** for å bruke den til nettopp dette!

Alkohol er også noe som hører med for de fleste av oss. Det er ingen hemmelighet at alkohol bidrar med en del kalorier, og på den måten kan bidra til julekiloene, men samtidig skal jeg ikke overbevise deg om å droppe juleølen. Det har jeg hvertfall ikke tenkt å gjøre selv, da den for min del hører med til julemiddagen og kveldskosen!

Syns du kakene er best med ekte sukker så bruker du selvfølgelig dette. Denne artikkelen er på ingen måte ment for å redusere trivselen med juleferien, men heller gi deg som ønsker det noen tips og triks for å unngå det verste juleflesket, det har jo tross alt med trivsel å gjøre det også!

La årets julemotto være:

> Det er ikke det du gjør mellom jul og nyttår som avgjør, det er det du gjør mellom nyttår og jul!\
> -ukjent

## God Jul!
