---
title: "Belastningsskader: Jumper's knee"
author: "Torbjørn Lysne"
---

Jumper’s knee – eller hopperkne – er en skade som er svært vanlig i idrett som inkluderer mye hopping og støt. Utøvere innefor volleyball, basketball, fotball og hoppøvelser i friidrett er spesielt i faresonen for å utvikle jumper’s knee i løpet av karrieren. For eksempel i volleyball er forekomsten av jumper’s knee opptil 40 %. I denne artikkelen ser jeg litt på hva jumpers knee er for noe, og hvordan det behandles.

Jumper’s knee skyldes en overbelastning av senen til den store knestrekkermuskelen på fremsidenav låret (musculus quadriceps femoris). Denne muskelen er festet til kneskålen (patella) gjennom en sterk sene som fortsetter fra nedre del av kneskålen til et ben høyt på fremsiden av leggbenet. Kneskålen kan med andre ord sees på som en del av senen til quadricepsmuskulaturen.

På fagspråket kalles jumper’s knee for patellar tendinopati ettersom det er en overbelastning i senen til quadriceps. Gjentatte hopp med høy belastning kan til slutt gå ut over senens tåleevne. Både under hopp og i landinger med bøyde knær blir knestrekkersenen utsatt for belastninger som kan tilsvare flere ganger din egen kroppsvekt. Hvis belastningen overstiger senens tåleevne vil kroppen svare med å gi beskjed om at noe er galt, og det utvikles en betennelse/inflammasjon i senen. Betennelse kan betegnes som kroppens forsvarsreaksjon mot skade i vev eller organer. Kort fortalt sørger den for at blodtilførselen til det skadede stedet øker, en hevelse oppstår som følge av at det siver blodplasma ut i vevet, og du får smerter på grunn av hevelsen.

Les også: [Runners knee](runners-knee.qmd)

## Symptomer

Som oftest beskriver personen smertedebut etter en bestemt aktivitet, mens andre kan kjenne at smerten har kommet gradvis og at den har utviklet seg over tid. Likheten er at smertene er aktivitetsavhengige, og vanlig hverdagsaktivitet går som regel uten store smerter. I de fleste tilfellene er smertene lokalisert ved quadricepssenens utspring fra nedre del av kneskålen og nedover mot leggbeinet, men et fåtall kan også kjenne smerter langs senens feste på øvre del av kneskålen. Smertedebut er som regel i et lite, avgrenset område, men tiltar mer og mer desto lengre man går uten å gjøre noen tiltak for å stoppe utviklingen.

Ut fra symptomer kan vi dele jumper’s knee inn i fire stadier:

1.  Smerte etter trening, ingen funksjonsnedsettelse
2.  Smerte under og etter aktivitet, kan fungere på samme nivå som tidligere
3.  Forlenget smerte under og etter aktivitet – Vansker med å prestere i idretten
4.  Total avrivning av senen – kirurgisk behandling nødvendig.

## Behandling og forebygging

Hovedmålet med behandlingen av jumper’s knee er som ved alle andre belastningsskader; å komme tilbake til ønsket aktivitetsnivå raskest mulig. Det er lett for å komme inn i et mønster der du både kompenserer med andre muskelgrupper og endrer bevegelsesmønster for å unngå smertene som har oppstått. Den typiske belastningsskaden endrer både bevegelsesutslaget, teknikken og koordinasjonen til utøveren. Dette er viktig å prøve å unngå for å ikke utvikle nye skader.

Ved jumper’s knee består behandlingen i akuttfasen å dempe betennelsen, samt redusere smerter. Hvile, lette uttøyninger og nedkjølinger er det viktig å komme i gang med raskt om du ønsker å kommer fortest mulig tilbake til fullt aktivitetsnivå. I noen tilfeller kan betennelsesdempende medikamenter være nødvendig for å redusere smertene i en akuttfase (ca. én uke).

Når tiden er inne begynner en lengre rehabiliteringsfase der målet er å gjenvinne tapt funksjon. Her gjelder det å ta tiden til hjelp og ikke overstige vevets tåleevne for å unngå tilbakefall. Betennelsen er betydelig redusert og hevelsen er på vei ned. Dette medfører også at smerter under aktivitet vil være noe minsket, men en må regne med å kjenne litt smerter i området også under opptreningen. Det er hovedsakelig to ting jeg vil be deg gjøre i en rehabiliteringsfase av skaden; **Eksentrisk styrketrening** og **uttøying** på fremside/bakside lår.

## Eksentrisk styrketrening

Driver du med noe som inkluderer mye hopping, blir du utsatt for ekstreme eksentriske krefter hver gang du hopper, både i begynnelsen av satsfasen og ved landing. Ved jumper’s knee har senen til mm. Quadriceps fått en overbelastning på grunn av at den ikke har tålt disse eksentriske kreftene. Å bli sterk i eksentrisk arbeid er dermed en forutsetning for å tåle all hoppingen.

Eksentrisk styrketrening er trening der muskelen forlenges mens den utvikler kraft. Ved jumper’s knee betyr dette at mm. Quadriceps må utsettes for arbeid mens den forlenges, altså når kneet bøyes. Eksentrisk trening er anbefalt å gjennomføres rolig og kontrollert for best mulig effekt. Man kan for eksempel stå på ett bein og sakte gjøre en knebøy. På veien opp, i den konsentriske fasen av knebøyen, hjelper du til med det andre beinet. [Her er en video av øvelsen](http://www.youtube.com/watch?v=LbVIGDqWaU8).

Et annet alternativ er å gjøre det samme i et benpressapparat. Skyv opp med begge bein og hold igjen med affisert bein på veien ned. Fordelen med å gjøre det i et apparat er at du lettere kan justere den ytre motstanden i den eksentriske fasen. I starten legges det vekt på å gjøre mange repetisjoner (20-30) med en motstand som gjør at øvelsen kan gjennomføres innenfor smertegrensen. Tre serier minimum 4 ganger i uken anbefales for å komme raskere tilbake til vanlig trening, men øvelsen kan gjerne gjøres daglig. Når du kjenner at kneet tåler mer kan du øke belastningen og redusere antall repetisjoner. Det er viktig å ikke overstige vevets tåleevne (les smerter) under opptreningen, det kan medføre en forverring av skaden og avbrekket fra din normale treningshverdag vil øke.

## Uttøying

Tøying av mm. Quadriceps er også en viktig del av behandlingen av jumper’s knee. Dette bør gjøres for å få en smidigere og lengre muskulatur på fremsiden av låret. Fordelene med det er at bevegelsesforholdene bedres og faren for å pådra seg tilbakefall og/eller andre skader kan reduseres. Tøy gjerne på annen lår- og leggmuskulatur også.

Utenom den eksentriske styrketreningen og tøyingene er det å anbefale å holde seg unna annen aktivitet som fremprovoserer smerter.

## Prognoser

De aller fleste innenfor stadiene 1-3 opplever å bli bra etter et lengre opptreningsprogram med eksentrisk styrketrening og uttøyinger. Et slikt treningsprogram bør vare i 2-3mnd, men dette er svært individuelt med tanke på hvilket stadie en er på når behandlingen tiltar. Jeg vil uansett anbefale å ta tiden til hjelp og når det gjelder belastningsskader som jumper’s knee.

Dersom senen er helt avrevet (stadie 4) kreves kirurgisk behandling. Det kan også bli aktuelt dersom konservativ behandling ikke fungerer hos noen som ikke har avrevet sene.

