---
title: "Ketose uten ketogen diett?"
date: 2012.11.29
---

I dagens VG er det en sak om en ny mirakeldrikk som skal kunne hjelpe deg ned i vekt. Forskningen på denne drikken er i oppstartsfasen, men resultatene av denne forskningen kan etterhvert bli veldig spennende! 

Kieran Clarke er professor ved Oxford University i England, og står bak dette forskningsprosjektet. Hun har laget en drikk som inneholder ketonlegemer, som er molekyler som dannes ved ufullstendig forbrenning av fettsyrer. Når vi spiser lite karbohydrater, såkalte ketogene dietter, så øker produksjonen av disse ketonlegemene, som har egenskaper som gjør at de kan overta som energikilde der vi ellers måtte være avhengig av glukose.

Ketogene dietter har vist seg å være effektive for å oppnå vekttap, siden de av ikke kartlagte mekanismer ser ut til å redusere apetitten. Også ved epilepsi har man brukt ketogene dietter hos de som ikke responderer på medisinene, hovedsakelig hos barn, og hos mange har dette redusert mengden anfall ganske drastisk. Dette gjør at forskning på effekter av selve ketonlegemene kan være veldig spennende. Ulempen med ketogene dietter er at de kan være veldig vanskelig å følge over tid, siden de setter ganske store restriksjoner i kostholdet.

## Superdrikken

> **Du trenger ikke proppe deg med smør og bacon eller droppe frukt og grønnsaker, slik som en del ketosedietter foreskriver**

Clarke har altså laget en drikk som inneholder ketonlegemer, noe som vil øke nivåene av disse molekylene uten at man trenger å gå på en streng diett. Målet med forskningen er å finne ut om dette kan ha lignende effekter på appetitten som ketogene dietter har vist seg å ha, noe som kan være positivt med tanke på behandling av overvekt.

I artikkelen står det at fordelene med denne drikken er at man kan opprettholde en alminnelig, sunn middelhavsdiett, og slipper å droppe frukt eller stappe i seg smør og bacon. Ulempen er at drikken ifølge Clarke smaker grusomt.

## Hva sier ekspertene?

Fedon Lindberg er en av ekspertene som kommer med innspill i artikkelen. Han sier at ketonene i denne sammenhengen vil ha en effekt på appetitten, oppmerksomhet, humør og mer. Lindberg nevner også at denne forskningen er viktig, spesielt siden den er veldig "out of the box" med tanke på hvordan mange fagpersoner ser på ketogene dietter.

At ketonlegemene virker oppkvikkende forklarer Lindberg med evolusjonen. Ketose kan nemlig oppnås på flere måter, enten ved å spise lite karbohydrater, kostindusert ketose, eller ved å spise lite energi, også kjent som sultindusert ketose. Når dyr ikke får tak i mat så blir de ikke sløve, da dette ytterligere ville minsket mulighetene for å få tak i mat. Dette underbygges også av mange anekdotiske bevis fra mennesker som mener de blir mer oppmerksomme og tenker klarere når de gjennomfører kortere perioder uten mat.

Clarke håper trolig med sin forskning å kunne oppnå lignende effekter uten å måtte gå på strenge dietter, altså ved å tilføre ketonlegemene utenfra.

Kjetil Retterstøl er førsteamanuensis ved UiO og overlege på Lipidklinikken. Han stiller seg tvilende til at denne drikken vil kunne etterligne effektene av et ketogent kosthold, da han påpeker at ketonlegemene bare er en brikke i et større metabolsk puslespill. Han avviser ikke at det kan være en effekt, men understreker at det må mer forskning til før det er mulig å si noe mer om dette. Jøran Hjelmesæth, leder for Senter for sykelig overvekt, deler Retterstøls syn og sier at forskningen er på et alt for tidlig stadium til å kommenteres.

## Veien fremover

Først og fremst så må studien gjennomføres, slik at man kan finne ut om drikken gir de effektene man håper at den gjør, altså at den øker nivåene av ketonlegemer selv om man spiser normalt. I neste rekke gjelder det å finne et bruksområde og undersøke om den gir ønskede effekter. Vil f.eks. denne drikken være et effektivt hjelpemiddel som gjør vektnedgang enklere? Hva med kognitive effekter, kan et økt nivå av ketoner gjøre oss mer årvåkne og gi oss et bedre humør?

Alt dette gjenstår å se, men foreløpig er det viktig å tenke over det Retterstøl og Hjelmesæth påpeker, at forskningen foreløpig er på et så tidlig stadie at det vil være umulig å konkludere i noen retning!
