---
title: "En kiropraktors vidunderteip?"
author: "Andreas Wahl Blomkvist"
date: 2015.11.26
---

Har du noen gang sett idrettsutøvere som [Lance Armstrong](http://www.athletictapeinfo.com/tag/lance-armstrong-kinesio-tape/) eller [Thor Hushovd](https://www.oslosportslager.no/magasinet/kinesiologi-teip--en-revolusjon-innen-sportsteiping-1087.aspx) med fargerik teip diverse steder på kroppen? Da har du sannsynligvis sett Kinesioteip eller Kinesiologi teip (KT) – utviklet av den japanske kiropraktoren Kenzo Kase for en rekke [antatte fordeler](http://www.kinesiotaping.com/about/kinesio-taping-method) på 70-tallet. Tanken er, om vi skal tro leverandøren i Norge, [AlfaCare](http://www.kinesiotaping.no/omoss/om_tapen), at KT letter lymfedrenasje ved å løfte huden. Dette skal gi en rekke effekter som påvirker kroppens «[egne tilhelingsprosesser](http://www.kinesiotaping.no/omoss/om_metoden)», og dermed et unikt terapeutisk verktøy innen rehabilitering og idrettsmedisin. Teipen skal – for å oppnå effekt – plasseres på en bestemt måte, og det tilbys, ikke overraskende, [kursing](http://www.kinesiotaping.no/kurs) i nettopp dette. 

## En kiropraktors vindunderteip?

Populariteten til KT [skøyt i været](http://www.abqjournal.com/120131/news/taping-americas-athletes.html) etter at produktselskapet donerte KT til utøvere under Sommer-OL i Beijing 2008. Dette førte også til en bølge av vitenskapelige studier i årene som fulgte. Med utgangspunkt i de nyere oversiktsstudiene vil jeg se nærmere på effekten av kiropraktorens vidunderteip. Men først ser vi på dette med lymfedrenasje.

## Lymfedrenasje

Med økt lymfedrenasje håper man å behandle hevelser forårsaket av væskeopphopning, kjent som ødem. De [første](http://www.ncbi.nlm.nih.gov/pubmed/?term=19199105) [studiene](http://www.ncbi.nlm.nih.gov.zorac.aub.aau.dk/pubmed/?term=19240683) gav grunn til optimisme, om enn ikke KT var særlig bedre enn vanlig bandasjering. Senere studier har derimot forsøkt å sammenligne KT med placeboteip (oftest KT plassert feil eller teip uten de samme elastiske egenskapene). Disse har [ikke](http://www.journalofphysiotherapy.com/article/S1836-9553(14)00148-9/fulltext) funnet en [forskjell](http://www.archives-pmr.org/article/S0003-9993(13)00426-7/fulltext) mellom KT og placebo.

Det er dog flere årsaker til ødem, og de få studiene som foreligger utelukker ikke en effekt. Men, mosjonister og idrettsutøvere er mer interessert i hvorvidt noe hindrer skade eller bedrer funksjon, ikke hvorvidt det er noen millimeter forskjell i hevelse to uker etter en overtråkk.

## Muskelsmerter og nedsatt funksjon

Flere oversiktsstudier har de siste årene sett nærmere på effekten av KT på [muskelsmerter ](http://www.ncbi.nlm.nih.gov/pubmed/25595290)og [-funksjon](http://www.ncbi.nlm.nih.gov/pubmed/?term=24875972). KT gir ikke bedre resultater enn andre teknikker på muskelsmerter eller funksjonsnedsettelse, men er muligvis gavnverdig på smerter når vi sammenligner KT med ingen behandling eller placeboteiping. Det sistnevnte funnet er usikkert da resultatene spriker mye og inkluderer også studier som ikke er placebokontrollert. En annen oversiktsstudie så nærmere på de studiene som var placebokontrollert og konkluderer at KT [ikke er bedre enn placebo](http://www.ncbi.nlm.nih.gov/pubmed/24856938).

Samlet sett er effekten såpass liten at man kan trekke den praktiske nytteverdien i tvil. Likevel, det er et billig alternativ som sammen med andre metoder kanskje kan hjelpe utøveren sine smerter. Det er – tross alt – ikke mange fungerende behandlingsmetoder for muskel- og skjelettsmerter. Og, om noe *samlet sett* har liten virkning, er ikke dette ensbetydende med at *individet* ikke merker en forskjell, uansett hva forklaringen er.

## Forebygge skade

Igjennom økt blodgjennomstrømning og bedre «kontroll» på muskler og ledd skal KT kunne forebygge skader. Forskere i New Zealand forsøkte å se [om det fantes dokumentasjon](http://www.ncbi.nlm.nih.gov/pubmed/22124445) for å hevde en slik forebyggende effekt. Dessverre er det gjort få relevante studier på forebygging, og basert på det som foreligger er det lite som gir belegg for en slik påstand.

## Muskelstyrke

En metaanalyse publisert i 2014, basert på en sammenfatning av 19 publiserte studier og 530 forsøkspersoner, så på hvorvidt KT hadde en [gunstig effekt ](http://www.ncbi.nlm.nih.gov/pubmed/25027771)på muskelstyrke. Forskerne fant ingen eller neglisjerbar effekt på muskelstyrke. Studiene som viste effekt var oftere av dårligere kvalitet enn studiene som ikke viste effekt. En slik trend er typisk for metoder som ikke virker: vi forventer ikke at en reell effekt blir borte med bedre metodikk.

## Konklusjon

KT lever ikke opp til de mange antatte fordelene. På noen områder, som skadeforebygging og lymfedrenasje, er det kun gjort få studier. På andre områder, som muskelsmerter og muskelstyrke, er det gjort flere studier som samlet sett gir lite grunn til optimisme. KT faller derfor i rekken til de mange produktene som markedsføres mot mosjonister uten dokumentasjon for sine påstander. Likevel, KT skader ikke, og er et billig alternativ (hvert fall sammenlignet med [kompresjonsklær](http://www.aftenposten.no/meninger/debatt/Dyre-kompresjonstights-som-2XU-markedsfores-som-a-ha-store-fordeler-Er-du-blitt-lurt-8139208.html)) for de som sliter med muskelplager som ikke har latt seg løse med konvensjonelle metoder.
