---
title: "Hvorfor du bør ta dype knebøy"
author: "Mari Kalland Knapstad"
date: 2014.05.12
---

Like mye som knebøy som øvelse er populær er den også omdiskutert og myteomspunnet, men så lenge jeg har drevet med styrketrening har knebøy vert kongen av alle øvelser. I en hver diskusjon om knebøy får jeg i yrket mitt som både fysioterapeut og personlig trener spørsmål som

-   Er ikke dype knebøy farlig for knærne?
-   Man trenger vel ikke å gå så dypt?
-   Er ustabile underlag noe å vurdere?
-   Er knebøy funksjonelt?

For å ta det siste først, knebøy er ikke bare en overlegen øvelse når det gjelder styrkeutvikling, men jo, den er også funksjonell. Sistnevnte er et ord som slenges mye rundt, og knebøy er kanskje ikke den første øvelsen man forbinder med det uttrykket. Men la det være sagt, at en øvelse som involverer store muskelgrupper, ligner dagligdagse bevegelser og gjør deg sterk, helt fint kan karakteriseres som funksjonell.

I denne artikkelen skal jeg drive litt myteknusing og svare i klartekst på de nevnte spørsmålene fra et vitenskapelig perspektiv:

## Hva er knebøy?

Knebøy er en flerleddsøvelse i lukket-kjede. Det vil si at det ikke er noe åpent rom mellom bena og underlaget, som det ville vært om man eksempelvis satt i et knestrekkapparat. Selve bevegelsen består blant annet av en fleksjon i kneleddet, det vil si at femur (lårbeinet) ruller bakover på tibia (leggbein) og sklir noe fremover. Av muskelgrupper involverer øvelsen quadriceps femoris(fremside lår), gluteus maximus (den store setemuskelen) samt medius og mimimus. I tillegg involveres hamstrings(bakside lår), addcutorer(innside lår), legger og rygg/bukmuskulatur. Med andre ord er dette en øvelse som involverer det meste at muskulatur som er viktig for både styrkeutvikling og funksjon.

## Er dype knebøy skadelig for knærne?

Dette er noe man hører veldig ofte, og myten spant trolig ut fra studier gjort av Klein (1961) som mente at ligamentene i kneet bleløsere ved dype knebøy, noe som ikke er spesielt bra for knestabiliteten. Denne teorien har nå blitt gjort til skamme av senere forskning, og får man spørsmålet kan man svare helt og klar tydelig at; nei, dype knebøy er ikke farlig for knærne.

En review-artikkel av Hartmann og medarbeidere (2013) tok for seg studier som undersøkte om halve knebøy var tryggere for knær enn dype. De fant at de retropatellare kreftene (altså kreftene mellom kneskål og femur) var størst ved 90 grader fleksjon, og ble redusert (!) jo dypere man gikk. Store krefter i ledd blir ofte sett i sammenheng med belastning og slitasjeskader i kneet og er altså noe man bør prøve å unngå. For øvrig konkluderte forfatterne videre med at dype knebøy ikke var skadelig for passive strukturer i kneet.

Videre har andre studier vist at stresset på fremre korsbånd er størst ved 30 grader fleksjon (knesvikt), mens når det gjelder det bakerste er det størst ved rundt 90 grader fleksjon (kvartbøy). Gikk man videre ned i 150 grader fleksjon (knebøy) var stresset på begge korsbånd vesentlig lavere (Li et al. 2004). Det vil si at stresset, eller draget om du vil, på leddbåndene er minst i dyp knebøyposisjon. Alt dette er altså er noe man bør ha i bakhodet neste gang man laster vektstangen full med vekter for å gjøre knesvikt/kvartbøy.

## Muskelaktivering ved dype knebøy

Det er spesielt to store muskelgrupper i bena som er aktiv ved knebøy, nemlig quadriceps og gluteus maximus.

Caterisano og medarbeidere (2002) gjorde EMG-målinger på hoftemuskulatur ved ulike dybder knebøy. Denne studien viste at aktiviteten i deler av quadriceps (vastus medialis og lateralis) var konstant uavhengig av dybde. Med andre ord kan du altså skaffe deg sterke quadriceps ved å trene kvartbøy, men ha i bakhodet det som tidligere ble nevnt om 90 graders fleksjon og leddkrefter. Ja, man kan lesse på mer vekter om man kun flekterer 90 grader, men det er også her leddkreftene er størst. Denne kraften vil potensieres av de ekstra kiloene du lesser på stangen, og du risikerer dermed å bli mer utsatt for skader.

Videre er inntrykket mitt er at man ofte er interessert i å få tak i en helt annen muskel som gjerne er inaktiv og underutviklet hos mange, nemlig gluteus maximus. Caterisano viste at gluteus maximus aktiveres i større grad jo dypere man går. Så om man vil ha en sterkere bak, blant annet for å forebygge fremtidige ryggplager, vil jeg på det aller sterkeste anbefale dype knebøy!

## Er ustabile underlag noe å i det hele tatt vurdere?

Blir knebøy mer funksjonelt dersom man legger inn ustabilt underlag? Funksjonelt med tanke på hva i så fall? Å bli sterk? NEI. Hvor mye av dagen tilbringer du på en bosuball sammenlignet med et gulv? Skal man bli sterk må man løfte tungt trenger man stabilitet i underlaget. Med tanke på å trene opp nevromuskulær kontroll og stabilitet etter skade? Tja, da kan knebøy på ustabilt underlag være fornuftig, men det har ingenting med styrketrening å gjøre.

### Referanser

1.  Caterisano A, Moss RF, Pellinger TK, Woodruff K, Lewis VC, Booth W, and Khadra T. The effect of back squat depth on the EMG activity of 4 superficial hip and thigh muscles. Journal of Strength and Conditioning Research . 16(3):428 – 432. 2002

2.  Hartmann H,  Wirth K, Klusemann M Analysis of the Load on the Knee Joint and Vertebral Column with Changes in Squatting Depth and Weight Load. Sports Med (2013) 43:993–1008

3.  Klein K. The deep squat exercise as utilized in weight training for athletes and its effects on the ligaments of the knee. JAPMR . 15(1):6 – 11 1961.

4.  Li G, Zayontz S, Most E, DeFrate LE, Suggs JF, and Rubash HE. In situ forces of the anterior and posterior cruciate ligaments in high kneeflexion: an in vitro investigation. Journal of Orthopaedic Research . 22(2):293 – 297. 2004.
