---
title: "Heldigvis bestemmer vi selv hva vi skal spise"
author: "Hanne Storhaug"
date: "2012.07.02"
---

Man kan bli både bekymret og forvirret av å følge med på ekspertuttalelser om kosthold. Dessverre er det mange som gir inntrykk av at vi i dag vet hva som er best, men som de fleste medisinske sannheter har dessverre ernæringsforskningens velbegrunnede råd også en lei tendens til å gå ut på dato.

Det mest beklagelige er at nye forskningsresultater blir tolket av fagfolk som er forutinntatte, og de fleste kostråd bærer preg av dette. Dersom en helt objektivt undersøker den vitenskapelige litteraturen som omhandler sammenhengen mellom enkeltbestanddeler i kosten og sykdom eller død, er det svært få matvarer som har en godt dokumentert sammenheng med helseutfall. De næringsstoffene det er sterkest evidens for at har negativ effekt har ofte en kjemisk struktur som ikke finnes igjen i naturen. Det store paradokset er at noen av disse ble laget nettopp for å erstatte de antatt helseskadelige næringsstoffene i naturlig mat.

## Advarsler mot mat kan virke negativt

Ved frokostbordet i dag fortalte mormor om da forskere begynte å advare mot å spise egg. På den tiden brukte mine oldeforeldre alltid å koke seg hvert sitt egg til frokost. Mormor husket ikke om de sluttet med det eller om de bare ble ekstra bekymret. Uansett var virkningene negative. I dag vet vi som har undersøkt dette, at evidensen for å anbefale droppe frokostegget ikke var god nok.  Helsemyndighetene i de fleste land har da også gått bort fra å advare mot egg.

Kokekaffe er et annet godt eksempel på noe som var antatt helseskadelig i lang tid, men rådene var basert på forskning på såkalte myke endepunkter, og ikke på den direkte sammenhengen med sykdom eller død. Dessverre anbefalte jeg mormor å kutte ut presskannekaffen etter mitt andre år på ernæring, men har rettet opp dette tankeløse rådet nå. Helsedirektoratet har også rettet det opp i den nyeste kostrapporten, men har ikke investert mye i å informere befolkningen om det.

## Positive opplevelser og glede er vel så viktig for god helse

God helse er mer enn fravær av sykdom, og mat er mer enn næringsstoffer og deres eventuelle virkninger hver for seg. Per Fugelli, professor i sosialmedisin, sier dette om kaffedrikking:

> All folkelig erfaring tilsier at menneskene opplever selv at de har godt av kaffe, det er et lyspunkt for dem i tilværelsen. Da er det eneste gyldige svaret: Kos deg da med kaffe og ikke bry deg. Ikke tenk på om det påvirker det ene eller det andre organet i den ene eller andre retning. Glem det!

## Du er ekspert på din egen kropp

Det er synd at ernæringsforskere kan trekke konklusjoner og gi kostråd på bakgrunn av svært dårlig dokumentasjon uten at dette får konsekvenser eller blir undersøkt av utenforstående. Heldigvis bestemmer du selv hva du skal spise, og de fleste har nok mer enn en formening om hvilken mat som får en til å føle seg bra og hvilken mat som ikke har så gode virkninger på kroppen. Mat som føles bra på kort og lang sikt kan neppe være noe annet enn bra for deg.

Mitt beste råd er: lytt til egen kropp – du er den som vet best hva som er riktig for deg.
