---
title: "Enkle prinsipper for kosthold og styrkeøkning"
author: "Thomas Olsen"
date: 2012.09.19
---

Det finnes nok av artikler på utallige blogger om hvordan man skal trene for de beste resultatene. Som nybegynnere er det vanskelig å vite hvor man skal begynne når tilgangen på informasjon, god og dårlig, er bortimot ubegrenset.

Denne artikkelen var egentlig myntet på personer som er ny innenfor styrkeidretter og da spesielt styrkeløft. Dette er en revidert versjon som kan være nyttig for alle som ønsker å bli sterkere. Denne artikkelen var også opprinnelig delt inn i tre serier som involverer **Ukontrollert/kontrollert vektoppgang og styrkeøkning, vedlikehold og styrkeøkning samt vektnedgang og vedlikehold av styrke.**

Dette er første del av artikkelserien, og den er ment å gi enkle pekepinner på hva man skal være opptatt av og tenke på når man er i en oppstartsfase og relativt ny innenfor styrketrening.

## Del 1 - Glem vekten å spis deg sterk

La meg innlede med litt personlig erfaring;

Tidligst i min relativt kortfattede (aktive) karriere innenfor styrkeløft, kom jeg traskende inn på trening med min knapt 69 kg tunge, kvisebefengte kropp. Jeg begynte å trene, og etter mine obligatoriske nybegynner-gains sa det stopp. Etter hvert fikk jeg beskjed om at nøkkelen til styrkeøkning også kom an på hva jeg spiste til daglig, og at om jeg spiste mer ville jeg sannsynligvis også bli sterkere. Dette resulterte dermed i fantastisk mye drittmat, ettersom jeg på det tidspunktet ikke hadde noen kunnskaper om kosthold. Jeg ble sterkere, jeg ble motivert for å bli enda sterkere, samtidig som jeg ikke tenkte på vektklasser. Men er det egentlig så lurt som det høres ut som?

#### Positiv energibalanse

Som de fleste nå vet, er det sentralt for muskelvekst og dermed styrkeøkning med positiv [energibalanse](energibalansen.qmd). Positiv energibalanse er et mål, best mulig resultater skal oppnås for å bli sterkest mulig og bli størst i klassen. For å bygge opp muskelvev etter en benhard ben-økt (sorry) holder det ikke bare med en ussel proteinshake rett etter trening. Helheten spiller inn, og jo mer opp i vekt man går, jo flere strenger vil man etter hvert ha å spille på da man vil opparbeide seg energireserver i form av glykogen og fett i form av at økt tilgang på energi er proteinbesparende.

For en veldig forenklet fremstilling av energibalansen, les [historien om et badekar](brokenlink/energibalansen-historien-om-et-badekar/)!

#### Hva mener jeg med proteinbesparende?

Musklene er kort fortalt bygget opp av proteiner som igjen består av ulike aminosyrer. Ved **energiunderskudd** og **mangel på energireserver**, kan kroppen bryte ned proteiner til aminosyrer og bruke dette som energi.

Derimot, ved tilstrekkelig energiinntak, syntese og inntak av proteiner vil musklene restitueres, styrkes og dermed vokse fortere og gjøre deg sterkere (1). Reserver bestående av karbohydrater og fett vil også hjelpe deg under treningen alt ettersom hvor intens den er. Energioverskuddet som oppnås vil også føre til forhøyede verdier av anabole hormoner som testosteron, insulin og IGF-1, mens katabole hormoner som kortisol vil holdes på et lavere nivå, dette stimulerer muskelvekst og styrkeøkning (2,3).

#### Sammensetning av måltidet

Ved ukritisk matinntak i denne fasen er dette kanskje ikke noe å tenke på. Men dersom man vil oppnå best mulig resultater er det viktig å tenke på hva kostholdet er sammensatt av.

Det første man gjerne tenker på, og som jeg har nevnt flere ganger i løpet av artikkelen, er proteiner. Det pågår en evig diskusjon mellom forskere, bodybuildere og fitnessutøvere om hva som er optimalt. De steroide-befengte oksene på treningssenteret mener kanskje at 3-4 g/kg kroppsvekt er optimalt, mens forskerne mener at, for den som trener mye holder det med et inntak mellom 1,5-2 g/kg kroppsvekt. Personlig lener jeg meg fort mot 2 g/kg kroppesvekt om dagen som tilstrekkelig. I en oppstartsfase kan muligens et høyere inntak forsvares da musklene gjerne bygges raskere i denne perioden.

Ved å spise proteiner av [god kvalitet](brokenlink/proteinkvalitet/) vil du trenge mindre protein totalt for å dekke behovene.

Det er også viktig å huske på at styrketrening er intensivt fysisk arbeid, og i disse lavkarbo-dager drister jeg meg fremdeles til å påstå at glykogen er essensielt for å fullføre en ordentlig styrkeøkt. Insulin hemmer utskillelsen av veksthormon, men i en review av G. Gregory Haff et al som ser på karbohydrattilskudd og styrketrening, spekulerer man i at hypoglykemi **forårsaket av** forhøyede insulinnivåer kan oppregulere syntesen av veksthormoner. Effektene er usikre, men dette kan dermed indirekte påvirke muskelvekst (5). Haff påpeker også at utøvere bør vurdere inntak av karbohydrater før, under og etter trening for å hemme tapet av muskelglykogen og bedre restitusjonen. Dette er prinsipper som er åpne for diskusjon da dette avhenger av intensitet, varighet, hyppighet og hvilke type trening man faktisk gjennomfører, men jeg kommer ikke til å gå videre inn på det her.

#### Måltidsfrekvens

Olympiatoppen gjennomførte et forsøk hvor de fulgte to grupper gjennom en tolv uker lang styrketreningsperiode med forskjellig måltidsfrekvens (3 måltider vs. 6 måltider/dag). De fant en signifikant større økning i styrke og volum hos gruppen som spiste 3 store måltider om dagen kontra dem som spiste 6 måltider om dagen (4). Med andre ord kan du oppnå bedre resultater ved å spise tre store måltider daglig i stedet for seks mindre som er blitt en gjenganger i forskjellige anbefalinger.

Det er ikke dermed sagt at du bør gå over til å spise sjeldnere dersom du trives med 6 måltider om dagen, men du trenger ikke å frykte dårligere fremgang dersom du gir det et forsøk. Finn et måltidsmønster du trives med, og som tillater deg å få i deg nok mat i løpet av dagen.

## Nøkkel: Tålmodighet

Mine veiledere hadde kanskje rett i at et godt kosthold er nøkkelen til styrkeøkning, men et annet viktig element er tålmodighet. Gjennom en **gradvis** omlegging av kostholdet som gir en **positiv energibalanse** med fokus på **proteiner** i første rekke og karbohydrater og fett sekundært vil man begynne å se resultater i tillegg til at vekta vil øke stabilt.Det betyr at man kanskje har større mulighet for å stabilisere seg innenfor en vektklasse hvor man føler seg komfortabel med både kropp og styrke.

## Konklusjon

Det er flere bakdeler med å følge denne metoden ukritisk med mindre man er nybegynner og **vet hva man gjør.** Dette er en metode som kanskje kan hjelpe nybegynnere eller utøvere som har slitt med skader. Har du nylig begynt med styrkeidrett og ønsker å konkurrere kan det være greit å la kroppsvekten gå litt i glemmeboken en stund, spesielt om du sliter med å legge på deg muskelmasse. Spis rikelig og tren mye med god veiledning. Dette kan bidra til å øke motivasjonen, men på en annen side vil du sannsynligvis komme til et punkt der økningen i styrke slutter å følge vektutviklingen din, og du ender opp med en vekt hvor du ikke føler deg komfortabel i det hele tatt. Det er med andre ord viktig å ikke glemme vekten bort fullstendig.

La meg også legge til at kosttilskudd som proteinpulver vil være tilstrekkelig i starten for å dekke protein- og energibehov. Det vil sannsynligvis ta litt tid før man stagnerer og får intense kreatin-cravings. Enda lenger tid vil det ta før man er i en periode der man vil finpusse formen og evt. skulle ha bruk for andre kosttilskudd som BCAA o.l.

###### Nok og riktig mat er nøkkelen i første omgang!

*Kilder*

1.  Andersen LL et al, **The effect of resistance training combined with timed ingestion of protein on muscle fiber size and muscle strength**, *Met Clin Exp,* 2005

2.  Houston ME, **Gaining weight: the scientific basis of increasing skeletal muscle mass**, *Can J Appl Physiol,* 1999

3.  Lambert CP et al, **Macronutrient considerations for the sport of bodybuilding**, *Sports Med,* 2004

4.  Raastad T et al, **Styrketrening - i teori og praksis**, *Gyldendal Undervisning,* 2010

5.  Haff GG et al, **Carbohydrate supplementation and resistance training**, *J Str Cond Res,* 2003
