---
title: "Enkle tiltak som kan forbedre kostholdet ditt - del 3"
date: "2012.04.10"
---

Her komme tre nye forslag til endringer du kan gjøre i kostholdet ditt. Som jeg har skrevet i de to første artiklene er det ikke nødvendig å gjøre så store omveltninger, og enhver liten forbedring vil gjøre at det totale kostholdet ditt blir bedre, noe som på sikt vil være positivt for helsen din.

## Frukt og bær er naturens godteri

Mennesket er fra naturens side utstyrt med et sug etter det som smaker søtt. Dette stammer fra den tiden da vi var avhengige av å finne maten vår ute i naturen. Siden det ikke er noen naturlige gifter som smaker søtt, betydde søtsmak vanligvis at det var trygt å spise. Søtsuget fungerte en gang som en overlevelsesmekanisme, men i dag virker det heller mot sin hensikt, da vi ikke akkurat har mangel på søte alternativer.

Likevel er ikke løpet helt kjørt, det finnes både gode og mindre gode alternativer her også. Det mindre gode alternativet er å stupe nedi nærmeste smågodtskål neste gang suget melder seg, eller å ty til søte drikker. Som jeg var inne på i [del 1](brokenlink/3-enkle-tiltak/ "3 enkle tiltak som kan forbedre kostholdet ditt") bør vi prøve å begrense inntaket av tilsatt sukker, og i [del 2](brokenlink/3-tiltak-del-2/ "3 tiltak som kan forbedre kostholdet ditt – del 2") snakket jeg om helseeffektene av å velge vann som tørstedrikk.

**De beste søte alternativene for helsen din er frukt og bær.** Disse er ikke spesielt energitette, og i motsetning til en del andre søte alternativer, så inneholder de en del vitaminer, mineraler og andre gunstige stoffer. Frukt og bær er også basedannende, noe som kan være med å balansere syren som produseres når vi spiser annen mat.

Velg frukt eller bær som dessert, så får du tilfredsstilt søtsuget med god samvittighet!

## Finn fram i oljejungelen

Fett er et viktig næringsstoff, både som en viktig energikilde, byggesten i cellemembranene våre og for å absorbere fettløselige vitaminer. I butikkhyllene finner du mange ulike matoljer, og det er ikke alltid like lett å vite hva du bør se etter. De fleste har hørt at oliven- eller rapsolje er gode alternativer, og det er de, men også her finnes det ulike varianter.

Mange matoljer inneholder veldig mye omega-6, noe som vi fra før får i oss for mye av sammenlignet med omega-3. Verstingene her er soyaolje, maisolje og solsikkeolje, så disse bør du styre unna. Velg derfor mer nøytrale oljer som oliven- eller raps. Kokosolje inneholder nesten utelukkende mettet fett, så denne er helt nøytral når det gjelder omega-3 og omega-6, og fungerer veldig godt til å steke med.

Les mer om [omega-3 og omega-6](brokenlink/omega-3-og-omega-6-i-kostholdet/ "Omega-3 og Omega-6 i kostholdet").

En viktig forskjell på de ulike oljene handler om hvordan de er laget. Kaldpresset olje (extra virgin) er minst behandlet, og fettsyrene er  derfor i sin naturlige form. Dette er et kvalitetstegn, og noe du bør se etter når du skal velge olje! **Kaldpresset olje tåler mindre varme enn varmpresset, så disse bør ikke brukes til å steke i, men heller helles over maten etter tilberedning.**

Oljer som inneholder umettet fett (dvs. alle utenom kokosolje) vil være utsatt for harskning, altså oksidering av fettsyrene. Denne prosessen går raskere når oljen blir utsatt for lys og oksygen. **Av denne grunn bør du kjøpe olje som kommer på en mørk flaske, og oppbevare denne mørkt, gjerne i kjøleskap.**

For å oppsummere bør du altså velge en kaldpresset oliven- eller rapsolje på mørk flaske, og oppbevare denne mørkt. Til steking bør du bruke fett som er mest mulig mettet, altså kokosfett eller meierismør.

## Finn en måltidsrytme som passer deg og din hverdag

Glem alt du har hørt om at frokosten er viktig for å sette igang og at små, hyppige måltider er viktig for å opprettholde forbrenningen. Sannheten er at du har mye større frihet til å tilpasse måltidsmønsteret etter hva som passer deg, og det eneste som kan sies å være viktig er at du får i deg nok mat og at du prøver å spise noenlunde likt fra dag til dag. Det er ikke til å komme utenom at gode rutiner gjør det enklere å unngå de store utskeielsene, siden kroppen tilpasser seg det måltidsmønsteret du velger. Så lenge du spiser den samme totalmengden, spiller det med tanke på forbrenningen ingen rolle hvor mange måltider du fordeler denne på

For mange passer det utmerket å spise lite og ofte, og det er selvfølgelig ingenting i veien for å fortsette med dette. Men, er du blant dem som ikke er sulten om morningen og helst foretrekker å vente til lunsj, så er ikke dette noe å ha dårlig samvittighet for. Mange føler at de fungerer bedre på denne måten, og så lenge det ikke resulterer i at du stikker innom nærmeste bensinstasjon og kjøper boller, men klarer å spise fornuftig og strukturert, så er det ingenting som tilsier at du trenger å gjøre noe annet!

**Alle er forskjellige, og der noen trives best med å spise litt med jevne mellomrom er det andre som liker best å spise færre måltider og heller spise seg god og mett hver gang. Trivsel er nøkkelordet, og bare du vet hva du trives best med!**

Les mer om [periodisk faste](brokenlink/periodisk-faste-til-jul/ "Periodisk faste til jul?").
