---
title: "Enkle tiltak som kan forbedre kostholdet ditt - del 2"
date: "2012.03.17"
---

I [forrige del](kosthold-tiltak-1.qmd "3 enkle tiltak som kan forbedre kostholdet ditt") så jeg på tre av de tingene så godt som alle er enige om når det kommer til kosthold, nemlig det å spise mer grønnsaker, mer fisk og mindre sukker. I dag ser jeg på tre ytterlige tiltak du kan innføre for å løfte kostholdet ditt til et nytt nivå.

Som jeg nevnte sist vil enhver endring til det bedre føre til en forbedring av kostholdet sett som en helhet, så om du bare innfører et av punktene under, så vil dette være langt bedre enn ingenting.  At du får til å gjøre en endring vil også øke motivasjonen for å gjøre ytterligere endringer senere, hvertfall om du får en merkbar effekt. Så her er det bare å starte i en ende!

## Vann er den beste tørstedrikk

Drikkevarer som jus, brus og saft inneholder mye sukker, og i flytende form vil for det første opptaket gå raskere, og påvirkningen på blodsukkeret blir større. I tillegg vet vi at karbohydrater i denne formen [metter mindre enn karbohydrater i fast form](brokenlink/bor-du-begrense-inntaket-av-flytende-karbohydrater/ "Bør du begrense inntaket av flytende karbohydrater?"), noe som gjør det lettere å spise for mye. **Med tanke på at overvekt er et stadig voksende problem, vil dette være et viktig ledd i forebyggingen av både dette og sykdommene som ofte følger med overvekten.**

Å velge lettvarianter, der sukkeret er erstattet med andre søtningsmidler vil være fornuftig, men det vil samtidig være lurt å begrense mengdene. De fleste tåler disse søtningsstoffene i de mengdene de normalt inntas, men om du er storforbruker av f.eks. lettbrus kan det være en god ide å redusere forbruket, da vi ikke kan vite sikkert om høy eksponering av kunstig søtning kan gi problemer på lang sikt.

En fordel med kunstig søtning, f.eks. Aspartam, er at de er mye søtere enn sukker. Dette betyr at mengdene som brukes er veldig mye mindre, og **mattilsynet opererer med så høye sikkerhetsmarginer at det absolutt kan anses som trygt med et normalt inntak (ikke litervis hver dag).** Personer med Føllings sykdom (fenylketonuria) bør imidlertid styre helt unna aspartam, da det er en kilde til aminosyren fenylalanin. Andre som opplever symptomer som hodepine eller lignende etter inntak av kunstig søtning kan være ekstra sensitive for disse, og kan også med fordel styre unna. **Små barn bør heller ikke serveres kunstige søtningsstoffer, siden de har en mye lavere tålegrense pga lavere kroppsvekt!**

Selv om lettvarianter av saft og brus er et bedre valg enn variantene med sukker, vil det helt klart beste valget av tørstedrikk være gode gamle H2O. Vann vil være et gunstig valg, både for helsen din og for lommeboken. **Å erstatte saft/brus/jus med vann til daglig, vil være et kjempetiltak for helsen din!**

## Velg gode proteinkilder

**Protein er det makronæringsstoffet som metter best, og et økt inntak av protein vil derfor gjøre det lettere å begrense energiinntaket.** Dette vil blant annet bidra til å forebygge overvekt. Kvaliteten på proteinkildene er viktig, og her kan man gjøre både gode og mindre gode valg!

Det er fem matvaregrupper som er regnet som [fullverdige proteinkilder](brokenlink/protein/ "Protein"), noe som betyr at de inneholder tilstrekkelig av de essensielle aminosyrene til å holde proteinsyntesen i gang. **Jeg anbefaler at man tilstreber å spise mat fra hvertfall en av disse gruppene hver dag, slik at man sikrer et tilfredsstillende inntak av essensielle aminosyrer.** De fem matvaregruppene er\
kjøtt, fisk, egg, meieriprodukter og soya. Meieriprodukter er uaktuelt for mange på grunn av allergier og intoleranser, og soya er heller ikke en basismatvare hos de fleste. Derfor vil jeg legge fokus på de tre første.

Egg er en ypperlig proteinkilde, og inneholder også de aller fleste [mikronæringsstoffene](brokenlink/naeringsstoffene/ "Artikkelserie om Næringsstoffene"). **Av denne grunn kan man med fordel inkludere egg i kostholdet flere ganger i uken!** Tidligere ble det advart mot et høyt inntak av egg fordi eggeplommen inneholder en del kolesterol, men etterhvert som man fant ut at kolesterolmengden i maten har en minimal innvirkning på kolesterolnivået i blodet ble imidlertid egg friskmeldt.

Kjøtt og fisk er for mange ensbetydende med blandingsprodukter som kjøttkaker, kjøttdeig, fiskeboller og fiskepinner. Innholdet av kjøtt og fisk i disse er ofte veldig lavt (det skal oppgis på innholdsfortegnelsen), og det tilsettes blant annet en del stivelse og tilsetningsstoffer i stedet. Proteininnholdet i rene produkter fra kjøtt og fisk ligger rundt 18-25g/100g, men i blandingsproduktene er innholdet langt lavere.

Ved å fortrinnsvis velge rene produkter som fiskefilet, reker/scampi, biff, koteletter og lignende vil du for det første få i deg mer protein av høy kvalitet. I samme slengen får du i deg mindre tilsetningsstoffer, og en høyere andel protein vil bidra til å redusere mengden som skal til for at du skal bli mett. Om du ønsker å ta det et hakk videre, så velger du villfisk og økologisk kjøtt fra dyr som har beitet ute. Disse har en bedre fettsyresammensetning, med blant annet en høyere andel omega-3.

**Å velge økologisk vil ofte medføre at maten blir dyrere, og for de som ikke tar seg råd til dette så vil man likevel få en veldig god effekt av å velge rene fremfor bearbeidede produkter av kjøtt og fisk.**

## Tilskudd av omega-3

[Et riktig forhold mellom omega-3 og omega-6](brokenlink/omega-3-og-omega-6-i-kostholdet/ "Omega-3 og Omega-6 i kostholdet") er essensielt for å opprettholde en god helse. **I et vestlig kosthold får vi i oss veldig mye omega-6, så her er det for mange et stort forbedringspotensiale.**

En ting man kan gjøre er å redusere inntaket av omega-6. Dette vil innebære et redusert inntak av planteoljer rike på disse fettsyrene, som soyaolje, solsikkeolje og maisolje.Det å redusere kornforbruket bidrar også positivt på dette forholdet, da korn er en av hovedkildene til omega-6.

Forholdet mellom omega-3 og omega-6 kan også forbedres ved å øke inntaket av omega-3. **Et økt forbruk av fisk, fortrinnsvis fet fisk, vil være fornuftig.** Samtidig vet vi at folk flest ikke spiser så mye fisk som de gjerne burde gjort, så da kan det være på sin plass å vurdere et kosttilskudd.

Helsemyndighetene har i lang tid anbefalt at man tar en spiseskje tran daglig, noe som absolutt vil være lurt. Det finnes også andre alternativer som selolje, lakseolje og krillolje, som har et lavere innhold av blant annet A-vitamin. **Ved høyt forbruk av omega-3-tilskudd kan det derfor være en fordel å velge en av disse fremfor tran.** I alle tilfeller vil det være lurt å velge et tilskudd i flytende form, siden det da vil være enklere å oppdage om oljen er harsk enn dersom den er inni en kapsel.
