---
title: "Enkle tiltak som kan forbedre kostholdet ditt - del 1"
date: "2012.03.02"
---

Kosthold fremstilles ofte som en stor suppe med mange bestanddeler, hvor alle er like viktige. Ofte kan det virke som om en forbedring av kostholdet er et "alt eller ingenting"-prosjekt, og mange velger derfor å heller droppe å gjøre endringer. Dette er ikke bra, og det er viktig å bli bevisste på at alle endringer til det bedre vil være gunstig, og man trenger heller ikke å snu opp-ned på hverdagen for å få det til! 

## Massestrategien

Et av hovedprinsippene i forebyggende helsearbeid er det som heter massestrategien eller befolkningsstrategien. Denne fungerer slik at **dersom en hel befolkning gjør et tiltak som senker risikoen litt, så vil dette totalt spare befolkningen for mange sykdomstilfeller.** Dette gjelder i høyeste grad kosthold, og en liten forbedring hos hver enkelt kan være veldig effektivt for å redusere forekomsten av livsstilssykdommer og problemer tilknyttet dette.

Den andre hovedstrategien i forebyggende helsearbeid heter høyrisikostrategien, og tar sikte på å redusere risikoen hos de som allerede er i høy risiko for å utvikle sykdom. Denne krever mye arbeid, blant annet med å identifisere hvem som er i denne gruppen, samtidig som tiltakene nødvendigvis blir større. **Massestrategien trenger ikke å ta hensyn til individuelle forskjeller, da uansett ønsker å påvirke hele befolkningen.** Et godt eksempel på denne typen påvirkning er kostrådene, som har som mål å påvirke folk til å spise sunnere. Virkemidlene er blant annet opplysningsarbeid som). Et enda nyere virkemiddel er faget Mat og Helse i grunnskolen, som tar sikte på å lære skolebarn om hva som er fornuftig kosthold.

## 3 enkle tiltak som alle er enige om

De fleste som leser her har fått med seg at det er en del uenighet om hva som er et sunt kosthold. I denne situasjonen er det viktig å holde tungen beint i munnen, slik at man ikke ender opp med å plukke litt her og litt der, da dette kan føre veldig galt av sted. F**oreløpig finnes det ingen fasit på hva vi bør spise, og sannsynligvis er det individuelle forskjeller på gennivå som påvirker hvilken mat som gir enkeltindividet god helse**. Vi har også veldig forskjellig livsstil, noe som gjør at vi har veldig ulike behov for de forskjellige [næringsstoffene](../naeringsstoffer.qmd).

For å få til et vellykket forebyggende arbeid i form av kostholdsråd, må vi rett og slett fokusere på de små endringene som alle er enige om. **Det er en del ting som utvilsomt vil gi en positiv effekt på helsen, spesielt når vi ser på det i et befolkningsperspektiv, og det er her fokuset må ligge.** Her kommer tre enkle tiltak som alle både kan og bør prøve å innføre så langt det lar seg gjøre.

### Spis mer grønnsaker 

Vi nordmenn er ekstremt dårlige til å spise grønnsaker, og en økning her vil være positivt på flere områder. **Grønnsaker er veldig næringstette og samtidig energifattige matvarer.** Å spise mer grønnsaker er et godt tiltak for å holde vekten i sjakk eller for å bekjempe den overvekten man allerede har. I tillegg er grønnsaker basedannende, noe som kan bidra til at man blant annet sparer kalsium fra beinvev, noe som på sikt kan være med å forebygge flere tilfeller av beinskjørhet. Jeg tror ikke det er tilfeldig at vi ligger på verdenstoppen i forekomsten av beinskjørhet samtidig som vi ligger langt nede på listen over grønnsaksinntak!

Det trenger ikke å være vanskelig å øke inntaket av grønnsaker, og heller ikke dyrt. Frosne grønnsaker er like næringsrike som ferske, og de er både billige og raske å tilberede. **Grønnsaker kan kokes, stekes, wokes, dampes, ovnsbakes eller spises rå, så variasjonsmulighetene er mange!**

### Spis mindre sukker

At sukker er negativt for helsen vår er ingen hemmelighet. På landsbasis får vi i gjennomsnitt i oss 13% av energien vår fra tilsatt sukker alene. **De offentlige anbefalingene sier at tilsatt sukker bør utgjøre under 10% av energiinntaket, men jeg vil gå enda lenger og si at dette er noe vi med fordel kan redusere til et minimumsnivå!**

Sukker og raffinerte karbohydrater er sterkt koblet til livsstilssykdommer i form av metabolsk syndrom (diabetes, overvekt, høyt blodtrykk og dårlig sammensetning av fettstoffene i blodet). **En reduksjon av sukkerinntaket vil være et viktig grep i å begrense omfanget av disse problemene!** Spesielt sukker i [flytende form](flytende-karbohydrater.qmd) ser ut til å ha en negativ effekt på helsen vår, så disse er det veldig lurt å styre unna. En halv liter brus inneholder hele 50g sukker, og ingen næringsstoffer!

En del sukker kommer i form av såkalt "skjult sukker", som finnes i mange typer ferdigmat og halvfabrikata. En God-Morgen-yoghurt inneholder f.eks. 10% tilsatt sukker, noe som tilsvarer 20g. **Ved å i større grad basere kostholdet på rene råvarer som du tilbereder selv kan du unngå veldig mye unødvendig sukker, og i samme slengen vil du også redusere saltinntaket ditt ganske mye, da disse ferdigvarene er vår største kilde til salt!**

### Spis mer fisk

**Fisk er en ypperlig proteinkilde, og fett fra fisk er rikt på omega-3-fettsyrene, som vi i gjennomsnitt [får i oss for lite av](omega-3-6.qmd).** Myndighetene vil gjerne at vi spiser mer fisk på bekostning av kjøtt, med de argumentene at det vil gjøre fettinntaket vårt mer i tråd med det de anbefaler. Jeg deler ikke denne oppfatningen, men er likevel enig i at fisk er noe vi kan og bør spise mer av!

En grunn til at mange spiser lite fisk er mangelen på kunnskap om hvordan man kan tilberede den. På samme måte som for kjøtt, finnes det mange muligheter til å variere også her. Fisk kan kokes (trekkes), stekes, wokes, ovnsbakes, dampes og røykes, så man trenger ikke å spise kokt torsk hver gang! Med ulike krydderkombinasjoner kan man ytterligere variere smaken!

**Velg så langt det går ren fisk og ikke fiskeprodukter**. Fiskeproduktene er som oftest tilsatt veldig mye rart, og andelen fisk er ofte lav (dette står på pakken). Både fersk og frossen fisk er bra mat, og det trenger heller ikke å koste skjorten. **I frysedisken kan du finne billige fileter av både sei, laks og torsk, og om du ikke har noe imot litt ekstra arbeid er det enda billigere å kjøpe hel fisk som du renser selv!**

## Hva skal du ta med deg fra dette innlegget?

Å spise sunnere trenger ikke å innebære at man gjør store omveltninger i kostholdet. Alle endringer til det bedre vil være gunstig i den store sammenhengen, og det kan være lurt å begynne i det små (f.eks. ved å innføre de tre tiltakene nevnt her). En ting som er verdt å ofre en tanke er at positive endringer i livsstilen vil motivere til å gjøre ytterligere endringer, og plutselig befinner du deg milevis fra det du startet med. Jo flere som gjør slike små tiltak jo bedre vil det være for den samlede folkehelsen!

**Alle reiser starter med det første skrittet, og kosthold/livsstil er ikke noe unntak!**
