---
title: "En introduksjon til kreftgåten"
author: "Andreas Wahl Blomkvist"
date: 2014.02.27
---

Kreft er noe mange kjenner til, både fra allmennkunnskap og personlig erfaringer. Nylig sirkulerte det en debatt som tok for seg sammenhengen mellom kost og kreft. Blant annet resulterte det til en [artikkel her på frisk og funksjonell](kalorirestriksjon-kreft-debatt) av Vegard Lysne. Jeg skal ikke antenne denne diskusjonen på nytt, selv om Warburg effekten, som gir grunnlaget for de metabolske forandringene vi ser i kreft (og dermed indirekte debatten om kost), er spennende og interessant – til og med [interessant nok til å vinne en Nobelpris](http://en.wikipedia.org/wiki/Otto_Heinrich_Warburg). Jeg ønsker i stedet å svare på noen tilsynelatende enkle spørsmål: Hva er kreft? Hvordan oppstår kreft? Hvorfor har vi ikke løst “kreftgåten” ennå? Det er sannsynligvis mange misforståelser blant folket om kreft, og kanskje du kan bidra til å bringe fram en bedre forståelse av kreft etter å ha lest denne artikkelen?

## Hva er kreft?

Kreft er en *gruppe* genetiske (men ikke nødvendigvis *arvelig)* sykdommer *(1).* Det er et resultat av skader på våre gener som gir opphav til unormale egenskaper hos celler, sånn som å dele seg uregulert og uavhengig. Tenk på kreft som en populasjon som har byttet politisk styreform til anarki. De responderer ikke på normal fysiologisk veksthemming og vokser på bekostning av nærliggende vev og kroppen generelt. Det er med andre ord en ukontrollert vekst av celler med ganske så forskjellige egenskaper sammenlignet med normale celler.

Det er kanskje ikke så vanskelig å forestille seg at kreft ofte oppstår i vev som normalt vokser og deler seg hyppig, slik som epitelvev. Epitelvev utgjør deler våre slimhinner, kjertler og hud, og de vanligste kreftformene blant voksne menn og kvinner oppstår i epitelvev. Disse er lungekreft, brystkreft (for kvinner), prostatakreft og endetarmkreft.

For å låne tittelen til Harald Eia sin bok, er du *født* sånn eller *blitt* sånn? Med andre ord, er det en arvelig sykdom eller en miljømessig sykdom? Dette er ikke så lett å svare på fordi kreft *ikke* er en enkelt sykdom. Hvis vi forsøker å svare på spørsmålet ved å se på kreft som en helhet, hevder i hvert fall en stor studie at omtrent 65% av *risikoen* for kreft er forårsaket av miljø og mellom 25-42% er arvelig disposisjon. Derfor er kreft hovedsakelig en miljømessig sykdom, men det er viktig unntak til denne generaliseringen som for eksempel retinoblastoma og familiær adenomatøs polyppose. Disse kreftformene, riktignok sjeldne, har gitt viktig innsikt i vårt neste spørsmål, hvordan oppstår kreft?

## Etiologien til kreft som en miljømessig genetisk sykdom

Kreft er en genetisk sykdom og det er derfor nødvendig å forstå noe om DNA og vårt genetiske materiale for å begripe hvordan kreft oppstår. Det er fire fundamentale prinsipper som gjelder alle kreftformer:

*1. Ikke dødelig genetisk skade er nødvendig for kreftutvikling*. Det kan først virke motstridene at skadene skal være “ikke dødelig”, men enhver dødelig celleskade vil slette de potensielle kreftcellene. Kreftcellenes genetiske materiale, og dermed funksjoner, blir modifisert av skader på DNA-nivå. Disse skadene kan være eksogen (komme utenfra) eller endogen (komme innenfra) og er “kreftfremkallende” eller karsinogene som det heter. Noen eksempler er diverse kjemikalier (f.eks. benzopyrene fra røyk), stråling (f.eks. UV stråler fra sola), virus (f.eks. human papilloma virus), arvelige mutasjoner, tilfeldige feil i replikasjon av DNA og frie radikaler fra metabolismen eller inflammasjon.

*2. Fire klasser av gener er hovedmålene for genetisk skade.* Gener som stimulerer vekst, kalt *proto-oncogener*, gener som hemmer vekst, *tumor suppressor gener*, gener som regulerer programmert celledød (apoptose) og gener involvert i reparasjon av DNA. Det er, så langt jeg vet, omtrent 30 veldokumenterte oncogener og 20 tumor suppressor genes.

Den første klassen gener inneholder den genetiske koden til å produsere diverse proteiner som *stimulerer vekst*. Vi kaller et skadet proto-oncogen bare oncogen, og produktet oncoprotein. På grunn av de genetiske forandringene har cellen begynt å produsere produkter som stimulerer til uregulert vekst. Det er viktig å huske på at disse oncoproteinene ikke nødvendigvis er vekstfaktorer, men kan være reseptorer til vekstfaktorene, signalproteiner i cytoplasma eller for eksempel transkripsjonfaktorer. Et velkjent eksempel er *RAS* genet, det hyppigste abnormale proto-oncogenet i kreft hos mennesker. Dette er sett i omtrent 15-20% av alle kreftyper. RAS er et G protein som fungerer ved å signalisere til vekst når en vekstfaktor har bundet seg til en G protein-reseptor. Noen mutasjoner (det finnes mange) i RAS genet fører til at RAS proteinet sender signaler *uavhengig* av signaler fra G protein-reseptoren.

Den andre klassen, *tumor suppressor gener* (TSG), fungerer på en motsatt måte. Fysiologisk hemmer denne klassen vekst, og hvis genetisk skade gjør disse produktene ikke-funksjonelle klarer ikke cellen lenger å bremse vekst (vekststimulerende effekt). I motsetning til oncogener, må stort sett begge allelene (genvariantene) være skadet for at en vekststimulerende effekt skal oppstå. Et eksempel er *RB* genet som får sitt navn fra sin oppdagelse i retinoblastoma nevnt i begynnelsen av artikkelen. Normalt hemmer RB proteinet vekst ved å binde E2F familien med proteiner. Disse proteinene stimulerer til vekst ved å transkribere syklin E som er nødvendig for at en celle skal fortsette igjennom sin cellesyklus. Hvis RB proteinet er skadet slik at E2F familien uhemmet kan stimulere produksjon av sykliner, vil dette bidra til at cellen kan vokse og dele seg uregulert. Et interessant funn blant alle disse faktorene er human papilloma virus (HPV) sin relasjon til kreft og RB proteinet. Det viser seg at HPV type 16 produserer et protein kalt HPV E7, som binder seg til RB proteinet på samme sted om E2F vanligvis gjør og dermed virker kreftfremkallende. HPV er kjent for sin assosiasjon med livmorshalskreft hos kvinner, og om en 10 års tid kan vi se epidemiologiske resultater av HPV vaksinen mot nye tilfeller av denne krefttypen i vårt naboland, Finland.

*3. Kreft oppstår fra en celle*. Etter hvert som flere genetiske skader akkumuleres vil en celle få egenskapene som behøves for å dele seg uregulert og selvstendig. Alle andre kreftceller kommer fra denne ene forgjengeren, og vi sier derfor at kreft er *monoklonal*.

*4. Kreft er en sykdom som krever flere trinn for å utvikle seg*. Det er ikke nok at cellene greier å dele seg uregulert, men de må etter hvert invadere nærliggende vev, skaffe seg næring ved å stimulere til vekst av blodårer (angiogenese), bryte seg løs fra ekstracellulær matriks og unngå immunforsvarets kreftbeskyttende funksjon. Dessverre har mange nye krefttilfeller ervevet disse funksjonene før kreften oppdages, og på dette tidspunktet er også kreftcellene svært forskjellige fra hverandre (de er heterogene), til tross for at de stammer fra en enkelt celle.

Jeg skal ikke gå i flere detaljer om etiologien av kreft, men det bør være tydelig at det er en flertrinnsprosess som foregår over en lengre periode der både endogene og eksogene faktorer spiller en rolle. Dette er sannsynligvis årsaken til at de fleste krefttyper oppstår etter fylte 55 år. En annen grunn kan være det svekkede immunforsvaret i høyere alder.

## **Hvorfor har vi ikke løst kreftgåten?**

Dette spørsmålet kan det hende leseren har svaret på allerede: kreftgåten er ikke løsbar fordi det ikke er en gåte – det er *mange* gåter. Kreft er en heterogen genetisk sykdom som så klart har fellestrekk, men årsaken og mekanismene som leder til kreft er svært forskjellig fra en kreft til en annen. For eksempel kan vi i dag kurere Hodgkins lymfom, mens bukspyttkjertelkreft fremdeles er svært dødelig. Noen krefttyper utvikler seg diskret og ubemerket før den har kommet langt i sitt ødeleggende livsløp.

En revolusjonerede terapi mot noen krefttyper kom med legemiddelet *Imatinib*. Imatinib hemmer tyrosine kinase proteiner som ofte kan være involvert i stimulering av vekst. Imatinib er mest effektiv i mot en form for kronisk myelogen leukemi. Slik målrettet terapi er under utvikling og flere mekanismer utforskes for å “løse andre gåter”. Uspesifikt brukes strålingsterapi og cellegift mot kreft. Grunnen til at disse metodene kan brukes på et bredt spekter av kreftformer er fordi de målretter seg mot celler som deler seg raskt. Dette gjør også at denne typen behandling er assosiert med mange bivirkninger. Ironisk nok virker mange cellegifter ved å påføre *enda mer* genetisk skade på kreftcellene og, enda mer paradoksalt, er *mindre* effektiv mot kreft som vokser sakte. Til slutt er kirugi, ofte brukt sammen med stråling og/eller cellegift, et viktig verktøy som utvilsomt har berget mange liv.

## Sammendrag

Kreft er en kompleks heterogen genetisk sykdom med mange faktorer som spiller inn. Kreft oppstår når ikke-dødelige genetiske skader akkumuleres til en celle får egenskapene til å danne en selvstendig populasjon som deler seg uregulert og på bekostning av kroppens friske vev. Kreftgåten har aldri vært *en* *gåte*, og det har sakte men sikkert oppstått terapeutiske metoder som virker mer spesifikt og skånsomt enn den tradisjonelle behandlingen med cellegift, stråling og kirurgi. Vår kunnskap om kreft bygges sakte opp fra flere vitenskapelige disipliner og vil fortsette å være en stor helseutfordring for mennesker verden over.

*Referanser*

1.  Robbins et al. *Pathologic Basis of Disease8th edition*. Saunders elsevier 2009. Kap. 8
