---
title: "Lavkarbo eller lavfett, er dette riktig fokus?"
author: "Vegard Lysne"
date: "2011.10.31"
categories:
  - kosthold
---

Stadig flere velger å legge om kostholdet til en eller annen form for lavkarbo. Etter massevis av suksesshistorier i media og rundt omkring på internett, er det ikke rart at man blir interessert og ønsker å teste selv. Å legge om til et lavkarbokosthold innebærer for de aller fleste en kraftig reduksjon i inntaket av karbohydrater, kombinert med en økning i inntaket av fett og protein.

Men er det sånn at så lenge sammensetningen av hovednæringsstoffene ([fett](http://www.friskogfunksjonell.no/fett/), [protein](http://www.friskogfunksjonell.no/protein/) og [karbohydrat](http://www.friskogfunksjonell.no/karbohydrater/)) passer din kostholdsretning, så er dette det eneste som teller? Hvis vi skal tro på alt vi leser i media, så kan det virke som om mange er av denne oppfatningen. Det er ikke jeg!

Et moment som ofte forsvinner i kostholdsdebatten er matkvalitet. Folk henger seg opp i hvor mange gram karbohydrater eller fett en matvare inneholder, og fokuserer mindre på hvor denne matvaren kommer fra og hvordan den havnet i hyllen på butikken.

Fra lavfettleiren anbefales det ofte å redusere inntaket av kjøtt og meieriprodukter, fordi dette inneholder mye mettet fett, mens fra lavkarboleiren er det mange som er redde for å spise frukt på grunn av høyt innhold av karbohydrater. Dette er etter min mening feil vinkel å angripe problemet fra. Både fettrike og karbohydratrike matvarer kan inngå i et sunt kosthold, og alt handler om matkvaliteten!

## Hva mener jeg med matkvalitet?

Mat som er mest mulig slik vi finner den i naturen, har den beste kvaliteten. Dette er mat som mennesket alltid har spist, og derfor er genetisk best tilpasset å spise. Med en gang vi begynner å bearbeide matvarene, vil kvaliteten synke.

Noen eksempler:

-   Hel frukt er bedre enn produkter som tørket frukt og fruktjuice.

-   Poteter er bedre enn potetprodukter som chips og pommes frites.

-   Rent kjøtt (med det naturlige fettet) er bedre enn kjøttprodukter, som ofte er tilsatt masse forskjellig for å få riktig konsistens og smak, samt lengre holdbarhet.

-   Ren fisk er bedre enn produkter som fiskekaker av samme grunn som over.

-   Meierismør er bedre enn plantemargariner

Setter du sammen kostholdet ditt av gode matvarer som er minst mulig bearbeidede, så er fordelingen mellom de ulike [næringsstoffene](http://www.friskogfunksjonell.no/naeringsstoffene/ "Artikkelserie om Næringsstoffene") i min bok underordnet, og ikke noe du nødvendigvis trenger å tenke så mye på.

## Skal vi bare glemme næringsstoffsammensetningen?

Jeg mener for all del ikke at fordelingen mellom karbohydrater, protein og fett er uvesentlig, men dette vil ordne seg mye av seg selv når utvalget av matvarer er bra. Dersom du registrerer hva du spiser i løpet av en dag, vil du merke at det er svært vanskelig å få i seg en stor andel energi fra karbohydrater når du kutter ut ferdigprodukter og halvfabrikata. Energiandelen fra fett vil være naturlig høy så lenge du spiser variert, spesielt om du spiser en del proteinrik mat som kjøtt, fisk, egg og nøtter/frø, samt inkluderer gode oljer som kaldpresset olivenolje og kokosolje.

Ved å velge matvarer av god kvalitet vil du også dekke behovet for alle mikronæringsstoffene. Dette forutsetter selvfølgelig at energiinntaket ditt er tilstrekkelig. Eneste unntak er [D-vitamin](http://www.friskogfunksjonell.no/d-vitamin/ "D-vitamin"), siden dette er et vitamin vi hovedsakelig produserer selv når vi eksponeres for sollys. Det kan være en fordel å ta tilskudd av dette vitaminet i vinterhalvåret.

Ved å redusere kornforbruket og velge fett av høy kvalitet (ikke varmebehandlede oljer som soya-, solsikke- og maisolje), vil du også oppnå en bedre [balanse mellom omega-3 og omega-6](http://www.friskogfunksjonell.no/omega-3-og-omega-6-i-kostholdet/ "Omega-3 og Omega-6 i kostholdet"), noe som er sentralt når det gjelder å opprettholde en god helse!

## Tomme kalorier

Vi hører ofte snakk om tomme kalorier, men vet egentlig alle hva dette er? Tomme kalorier er et uttrykk som brukes for å beskrive mat som bidrar med mye energi, men lite næringsstoffer i form av vitaminer og mineraler. To gode eksempler på dette er sukker og hvitt mel, og matvarer med høyt innhold av disse bør du så godt det lar seg gjøre styre unna. Spesielt gjelder dette sukker vi får i oss gjennom drikke, som brus, saft og jus. Denne energien vil tas opp ekstra raskt, og dermed gi en kraftigere virkning på blodsukkeret enn tilsvarende mengder sukker fra mat. I tillegg metter den vesentlig dårligere. Flytende kilder til sukker bør derfor begrenses så langt det lar seg gjøre. Velg frukt foran fruktjus og saft!

## Man skal jo også kose seg litt!

En felle mange går i når de endrer kosthold er å fullstendig nekte seg mat de er glad i. Dette kan f.eks. være brødmat eller potet, som er kjære innslag i kosten til veldig mange nordmenn. Husk at en suksessfull livsstilsendring innebærer at du klarer å følge ditt nye kosthold resten av livet, og da kommer man ikke langt med å være ekstrem.

Etterhvert finner du kanskje ut at disse matvarene ikke er like viktige for deg som de en gang var. Ved å eksperimentere med ulike matvarer finner du fort flere ting som kan erstatte brødskiven til frokost eller poteten til middagen, og at du ikke har behov for å spise disse hver dag. Plutselig har du mange ulike måltider å variere med, og variasjon i kostholdet er bra!

Det sier seg selv at en sunn livsstil ikke gir rom for kaker og brus hver dag, men det er ikke noe i veien for at man også kan spise dette i spesielle anledninger. Så lenge basisen i kostholdet er av bra kvalitet, og man klarer å holde seg til dette mesteparten av tiden, trenger ikke slike utskeielser å ha noen spesielt negativ innvirkning!

## Hvordan skal vi da på best mulig måte legge opp kostholdet?

Det er viktig å være klar over at mennesker er ulike, og lever ulike liv. Vi trenger ikke det samme til enhver tid og det finnes ingen «one size fits all» innen kosthold. Det vi alle er enige om, er at forbruket av grønnsaker bør økes vesentlig. Utover dette blir det mest opp til individet å velge et kosthold som man kan beholde livet ut. Jeg anbefaler å holde fokuset på matkvaliteten, og ikke tenke så mye på antall gram av ditt og datt. Kosthold trenger ikke å være så komplisert!

Velg et måltidsmønster som passer deg og din hverdag. Lukk ørene for de som forfekter gamle myter som at du må spise frokost for å sette igang forbrenningen eller spise lite og ofte for å holde den i gang. Studier viser ingen forskjeller i forbrenningen ved ulike måltidsmønstre, så her er kan du velge helt selv. Passer det deg best å spise to store måltider om dagen kan du fint gjøre dette, på samme måte som du kan velge å spise seks ganger om dagen om du syns dette er mest behagelig. Følg din egen sultfølelse!
