---
title: "Norum vs Fedon, er lavkarbo uanstendig?"
date: "2012.02.03"
categories:
  - lavkarbo
  - kosthold
---

Kaare Norum skrev nylig en [kronikk i aftenposten](http://www.aftenposten.no/meninger/kronikker/Lavkarbo-er-uanstendig-6753310.html#.TyvOkFzj7-M) der han hevder at lavkarbo er uanstendig. Argumentene i kronikken går hovedsakelig ut på bærekraft og hensynet til menneskene i land med dårlig tilgang til mat. Alle kan ikke spise lavkarbo, sier Norum, noe han langt på vei har rett i. I dagens nettutgave av aftenposten dukket det opp et [svar fra indremedisiner og lavkarboforkjemper Fedon Lindberg](http://www.aftenposten.no/meninger/debatt/Hoykarbo-er-uanstendig-6754851.html#xtor=RSS-3), som ikke er enig i Norums argumenter. Har begge et poeng, eller diskuterer de rett og slett ulike ting? Vi ser på argumentene!

## Overvekt og fedme

Det er ingen hemmelighet at forekomsten av overvekt og fedme øker over hele verden, det vet alle som har sett mennesker. Norum skriver i sin kronikk at dette problemet er størst i de delene av verden som spiser veldig søt og fet mat, eksemplifisert med USA og midtøsten.

Han sier så at overvekt disponerer for en rekke følgesykdommer som diabetes, hjerte/kar-sykdom og en rekke krefttyper, noe man ikke kan argumentere mot, selv om det kan diskuteres om ikke de samme tingene som fører til fedme også fører til en del av disse problemene.

Ifølge Norum er det tre hovedårsaker til at vi velger matvarer som bidrar til overvekt:

> **1. Pris.** Usunne matvarer er som regel billige.
>
> **2. Tilgjengelighet.** Usunne varer finnes overalt og når som helst.
>
> **3. Markedsføring.** Reklame og annen markedsføring når oss hele tiden gjennom aviser, TV, gjennom sosial medier og på skoler og idrettsstevner. Nesten all matreklame er for det vi burde spise mindre av.

Han mener at staten burde gå mer aktivt inn og regulere forbruket ved å legge avgifter på usunn mat, subsidiere sunn mat og legge føringer på hvor tilgjengelig denne maten skal være. Blant annet skriver han at kiosker og lignende burde forbys på kino og forsamlingslokaler.

Staten burde sørge for å tilrettelegge forholdene for fysisk aktivitet, samt bedre utdannelsen innen helse og kosthold helt fra barneskolen av. I tillegg ønsker Norum å gjeninnføre årlig veiing av alle barn i skolealder.

**Her er det etter min mening flere ankepunkter:**

-   Myndighetene gjør allerede en innsats for å påvirke forbrukernes valg av matvarer, nemlig gjennom [nøkkelhullsordningen](http://www.friskogfunksjonell.no/nokkelhull-bare-tull/ "Nøkkelhull, bare tull?"). Denne ordningen er langt fra perfekt, noe som i stor grad skyldes at det fremdeles er stor uenighet om hva som er sunn mat. Dette må det bli en enighet om før en slik ordning vil fungere som ønsket.

-   En økt styring fra staten vil gå utover den grunnleggende friheten vi har til å velge selv.

-   Å forby kiosker på kino er helt feil ende å angripe problemet. Det er ikke det du spiser/drikker når du en gang i mellom er på kino som gjør et utslag, det er det du spiser til daglig.

-   Å tvangsveie alle skolebarn kan hjelpe oss med å oppdage overvektsproblematikk tidligere, men samtidig fører dette nødvendigvis til et økt fokus på vekt blant disse barna. Dette kan igjen gi grunnlag for mer mobbing, og et etterfølgende økt fokus på vekt og kropp.

## Hva med lavkarbo?

**Lavkarbo viser seg i mange nye studier å være mer effektiv enn andre metoder når det gjelder vektnedgang**. Dette skyldes med stor sannsynlighet kostholdets påvirkning på sult og metthet, noe som gjør det lettere å innta mindre energi, noe som fører til vektnedgang uten sult. I tillegg viser flere studier at også etablerte risikofaktorer for sykdom blir bedre når andelen karbohydrater i kosten reduseres til fordel for mer fett og protein.

Norum sammenligner i sin kronikk lavkarbo med andre slankekurer som eggekurer, banankurer og ananaskurer. Dette sier meg at Norum ikke har brukt særlig mye energi på å sette seg inn i hva lavkarbo handler om, og anser det som en slags quick-fix. Han påpeker helt korrekt at lavkarbo fungerer fordi man spiser mindre enn man forbrenner, og dermed går ned i vekt, **men når lavkarbo i større studier viser seg mer effektiv enn tradisjonelle lavfettdietter, så burde det være interesse for å finne ut hvorfor, i stedet for et behov for å tviholde på det man har tenkt i alle år.**

Ifølge Norum er lavkarbo for en befolkning økologisk galt, dyrt og skadelig på sikt, og argumentene hans for dette er følgende:

-   Lavkarbokosthold er ikke bærekraftig, og karbohydrater er den viktigste energikilden i verden.

-   Lavkarbokosthold er økologisk galt, siden det krever mer ressurser å produsere en kg kjøtt enn en kg korn, og lavkarbo vil dermed føre til mer sult i verden.

-   Karbohydratrik mat som korn og poteter er billig, mens kjøtt, fløte, ost og smør er dyrt.

-   Lavkarbokosthold skader klimaet. Utslippene fra en kg kjøtt er større enn utslippene fra en kg korn.

-   Mye mettet fett i lavkarbomat øker risikoen for hjerte/kar-sykdommer, ved at det øker kolesterolnivåene som igjen øker åreforkalkning. Det er også en sammenheng mellom rødt kjøtt og tarmkreft.

**Fedon Lindberg svarer på disse kommentarene i sitt debattinnlegg, og her er noen av tingene han skriver:**

-   Lavkarbo er ikke ensbetydende med å spise mer kjøtt. Selv om en del ekstreme varianter anbefaler dette, så gjelder det ikke alle. Man kan fint ha et variert og plantebasert kosthold med redusert karbohydratmengde. En stor studie fra Harvard viste nettopp at et slikt kosthold vil øke livslengden.

-   Utviklingen av livsstilssykdommer har eksplodert i Norge, noe som fører til enorme utgifter. Skal vi i rike land bevisst spise høykarbomat i solidaritet med de landene som sliter med underernæring, når dette kan bidra til nevnte problem?

-   Nyere systematiske gjennomganger av litteraturen som omhandler kosthold og hjerte/kar-sykdommer støtter synet om at et middelhavskosthold med mye nøtter, grønnsaker, olivenolje, fisk og omega 3-tilskudd reduserer risikoen for sykdom. Industrielt fremstilt transfett og raske karbohydrater øker på sin side risikoen. Total fettmengde, uansett type, ser ikke ut til å ha hverken en positiv eller negativ effekt.

Når det kommer til solidaritet med de landene som sliter med underernæring, har Lindberg en del punkter han mener vi bør satse på i stedet for å fokusere på å spise det han anser som dårligere mat:

> -   La oss i Norge og andre rike land spise og leve sunnere og dermed redusere de enorme helseutgiftene.
>
> <!-- -->
>
> -   La oss redusere vårt overforbruk av meningsløse ting, som dyre biler, mer klær, mobiltelefoni og dyre reiser før vi prøver å vise solidaritet ved å spise "billigere" mat som kan gjøre oss sykere.
>
> -   La oss få sukker og hvitt mel bort fra kosten, eller i det minste redusere dette vesentlig.
>
> -   La oss øke vårt inntak av grønnsaker, helst fra fattige land som ikke bruker oljefyring for å holde drivhusene sine varme. La oss sørge for at fattige land får slippe til uten høye tollmurer.
>
> -   La oss anvende produksjonsmetoder som reduserer CO~2~-utslipp fra kjøttproduksjon (bruk av linfrø i stedet for korn i fôret til storfe fører til nesten 20 prosent reduksjon).
>
> -   La oss ikke kaste så mye mat hver dag.

## Kommentarer til debatten

Norum skriver at problemet med overvekt er størst i de landene der det spises mest søt og fet mat. **Her blir det for enkelt å trekke paraleller til lavkarbo eller et hvilket som helst annet fornuftig kosthold**. Mat som er forbundet med disse karakteristikkene er fastfood, som typisk inneholder masse av både karbohydrater og fett, begge av dårlig kvalitet. Denne kombinasjonen er kjent for å trigge oss til å spise mye, noe som helt klart har bidratt til et økt energiinntak, uten at det kan skyldes på verken karbohydrater eller fett i seg selv, men heller på kvaliteten.

**Når man skal diskutere lavkarbo, så er det helt essensielt å være enig om hva man legger i begrepet.** Her er det tydelig at Norum har bestemt seg for at lavkarbo er lik masse kjøtt og fete meieriprodukter, noe som ikke trenger å være tilfelle. Hadde man vært enige om hva man snakket om i utgangspunktet, hadde vi sluppet slike debatter som dette, der man bare ender med å snakke forbi hverandre.

**På spørsmålet om hvorvidt lavkarbo er uanstendig, så vil jeg si at det først og fremst avhenger av hvilke matvarer man velger å spise.** Om du velger å basere kostholdet sitt hovedsakelig på kjøtt, så er det klart at dette ikke er positivt verken for miljøet eller for den globale matforsyningen. Om du derimot velger å følge f.eks. Lindberg sin tilnærming, med et stort innslag av plantebasert mat som frukt og grønnsaker, samt varierte proteinkilder med det naturlig tilhørende fettet, så er saken en helt annen. Jeg syns også Lindberg har mange gode forslag til ting som bør prioriteres før vi velger å spise mat av lavere kvalitet.

**Les mer om min [tilnærming til lavkarbo](http://www.friskogfunksjonell.no/en-enkel-innforing-i-lavkarbokosthold/ "En kort innføring i lavkarbokosthold og tilpasning til din livsstil").**

Angående Norums uttalelser om mettet fett, kolesterol og hjertesykdom, så er bevisgrunnlaget for disse påstandene veldig svake, og nyere studier finner ingen sammenheng her. Når så mye taler imot at dette er riktig, hvorfor har vi da behov for å tviholde på slike meninger. Alle har jo forhåpentligvis folkehelse som et overordnet mål, og da kommer vi ingen vei dersom vi ikke tar hensyn til hva vitenskapen forteller oss. Hanne Storhaug har tidligere gått gjennom [bevisgrunnlaget for fettanbefalingene](http://www.friskogfunksjonell.no/de-offentlige-anbefalingene-for-fett-godt-begrunnet/ "De offentlige anbefalingene for fett, godt begrunnet?"), i en artikkel jeg virkelig kan anbefale!

## Hvordan skal vi så spise?

Kaare Norum har sin oppfatning av hva som er et sunt kosthold, og han oppsummerer dette i slutten av kronikken sin:

> Her er det for meg klart at Som lege og ernæringsforsker har jeg alltid ment, og mener fortsatt at grovt brød til frokost, lunsj og kvelds og kokte poteter og gulrøtter til middag er både sunt og riktig å spise

Fedon Lindberg på sin side sverger til et middelhavskosthold med lavglykemiske karbohydrater. Han skriver at:

> Etter min mening er målet hverken lavkarbo eller høykarbo, men smart-karbo og likeså smart-fett, ikke høyfett eller lavfett. Kvalitet betyr mer enn bare mengde. Så må den enkelte finne ut hva som gir en best helse, sunnere vekt og ikke minst større matglede.

Jeg har tidligere skrevet et blogginnlegg for [Sunt Hjem ](http://www.sunthjem.no)der jeg tok opp om [fordelingen av makronæringsstoffene](http://www.friskogfunksjonell.no/lavkarbo-eller-lavfett-er-dette-riktig-fokus/ "Lavkarbo eller lavfett, er dette riktig fokus?") er det riktige fokuset i jakten på et sunt kosthold.

Jeg vil påstå at valg av matvarer, og hvordan disse er bearbeidet er viktigere enn hvordan fordelingen av næringsstoffene er. **Om du baserer kostholdet ditt på grønnsaker, frukt, nøtter og bær, varierte proteinkilder som kjøtt, fisk, egg og meieriprodukter og fett fra naturlige kilder som kaldpressede oljer og fete meieriprodukter, så har du i mine øyne et veldig sunt kosthold som dekker alle behovene for næringsstoffer.** Om du velger å spise andre ting innimellom, så vil ikke dette være noe problem så lenge du spiser bra mesteparten av tiden.
