---
title: "En kort innføring i lavkarbokosthold og tilpasning til din livsstil"
author: "Vegard Lysne"
date: "2011.11.22"
categories:
  - kosthold
  - lavkarbo
---

Det blir stadig mer populært å legge om til såkalt lavkarbokosthold, og annenhver dag trykkes en ny oppskrift i media, den ene mer ekstrem enn den andre. Er det virkelig så komplisert som det fremstilles som, eller bidrar avisene mest til forvirring? Dersom du ønsker å legge om kostholdet mer i retning av lavkarbo, men ikke vet helt hvordan du skal gå fram, er dette innlegget midt i blinken for deg! Jeg vil også se litt på hvordan dette kan tilpasses enkeltindividet utifra aktivitetsnivå og målsetninger.

Dersom du ønsker å legge om til lavkarbokosthold, trenger ikke forandringene være så drastiske. Vi står for en naturlig tilnærming til lavkarbo, som verken skal være ekstrem eller vanskelig å gjennomføre i hverdagen. Hvis du først og fremst ønsker å optimalisere helsen din, for å holde deg frisk og funksjonell, har vi tidligere publisert [våre råd for bedre helse](http://www.friskogfunksjonell.no/vare-rad-for-bedre-helse/ "Våre råd for bedre helse"). Her er noen enkle tiltak som vil føre kostholdet ditt i retning lavkarbo, og til slutt kommer noen ord om hvordan dette kan tilpasses henholdsvis stillesittende og idrettsutøvere.

### 1. Velg så ren mat som mulig

Dette er etter min mening det viktigste punktet i kostomleggingen. Fokuset må flyttes vekk fra ferdigmat og over på rene råvarer. Maten skal være mest mulig slik du finner den i naturen. I praksis betyr dette at du spiser mat som kjøtt, fisk, egg, frukt, grønnsaker, bær, nøtter, frø og meieriprodukter. Det du først og fremst reduserer inntaket av er ferdigmat og halvfabrikata.

Sukker bør være det første man reduserer i ethvert kosthold, og alle anbefaler å redusere forbruket av tilsatt sukker. Et godt alternativ er sukrin, som består av den naturlige sukkeralkoholen erythritol, og nå har også stevia, en søt plante som blant annet har vært det vanligste søtningsmiddelet i Japan, nylig blitt tillatt i Norge. Les mer om Stevia i [saken om søtstoffer](http://www.friskogfunksjonell.no/sotstoffer/ "Søtstoffer"). Kunstig søtning vil generelt også være et bedre valg enn sukker.

### 2. Reduser inntaket av korn

Korn er den største kilden til karbohydrater i et vestlig kosthold, og ved å redusere inntaket av dette tar du et langt steg i retning et lavkarbokosthold. Mye tyder på at en del korntyper har en del negative effekter på helsen, og Pål Jåbekk skriver en del om akkurat det i [denne](http://www.paljabekk.blogspot.com/2011/10/veien-til-god-helse-korn.html) bloggposten.

Det er mange måter å redusere inntaket av brød, og du trenger ikke nødvendigvis å kutte det helt ut. Du kan f.eks. skjære tynnere skiver, og øke mengden pålegg. Dette er en fin måte å gjøre det på dersom du ønsker å redusere inntaket gradvis. Om du fra før har flere brødmåltider om dagen, kan du begynne å bytte ut ett og ett måltid med alternativer. Det er mange gode alternativer, f.eks. egg i alle mulige varianter, meieriprodukter med frukt/bær oppi eller man kan bake egne brød/knekkebrød basert på nøtter og frø.

### 3. Øk inntaket av frukt, grønnsaker og bær

Jada, frukt og grønnsaker er karbohydrater, men det er ingen som har snakket om å kutte ut alle karbohydrater fra kostholdet! Disse matvaregruppene er næringsrike og inneholder ikke mye energi. Dette betyr at du i de fleste tilfeller kan spise ganske store mengder av disse, uten at du får i deg så veldig mye karbohydrater. Grønnsaker kan du i alle tilfeller spise ubegrenset av. Hvor mye frukt og bær du vil spise blir mest opp til deg selv, og avhenger litt av hvor streng du vil være. Som tommelfingerregel kan du spise mer frukt jo mer aktiv du er.

### 4. Reduser de klassiske karbohydratkildene i middagen: pasta, ris og potet.

Tradisjonelt sett inneholder middagsmåltidet en solid porsjon pasta, ris eller potet. Her er det lett å redusere mengden og erstatte det med ekstra grønnsaker, og du trenger kanskje ikke disse matvarene til middag hver dag. Pasta er et kornprodukt, så dette bør du uansett redusere jmf. punkt 2. Når det kommer til potet er saken en litt annen, siden potet per definisjon er en rotfrukt/grønnsak. Potet inneholder ganske mye karbohydrat i form av stivelse, som er lange kjeder av glukosemolekyler. Her blir tankegangen litt som med frukt: Jo mer aktiv du er, jo mer potet kan (og bør) du spise, da glukosen først og fremst vil gå til å fylle opp glykogenlagrene dine. Mer om dette kommer lenger nede!

### 5. Velg de feteste meieriproduktene

Meieriprodukter er en stor del av det norske kostholdet, men anbefalingene fra myndighetenes side er å velge de magreste typene. Dette begrunnes med at melkefett i stor grad er mettet, og at man lenge har trodd at det er en sammenheng mellom mettet fett og hjertesykdom. [Bevisgrunnlaget for denne påstanden er faktisk utrolig svakt](http://www.friskogfunksjonell.no/de-offentlige-anbefalingene-for-fett-godt-begrunnet/ "De offentlige anbefalingene for fett, godt begrunnet?"), og utifra det vi vet i dag er det ingen grunn til å være redd for naturlig fett. Når du reduserer inntaket av karbohydrater, bør du øke inntaket av fett noe for å dekke energibehovene i løpet av dagen. Meieriprodukter er en god kilde til fett og energi, men dette betinger at du velger de feteste typene. Du vil merke at disse metter bedre enn de magre produktene, og at du ikke vil ha behov for å spise/drikke like mye for å bli mett, og i tillegg smaker maten mye bedre når man bruker ekte fløte og smør!

## Hvilke tilpasninger bør en stillesittende eller mosjonerende person gjøre?

Dersom du er stillesittende, kan du med fordel redusere karbohydratinntaket ganske mye. Karbohydrater er en hurtig energikilde, og først og fremst nødvendig ved høye intensiteter. Ved inaktivitet og trening på lave intensiteter kan fett fint være den primære energikilden, og mye tilsier at den også bør være det.

Det er mange myter om at man må innta masse karbohydrater etter trening for å få utbytte av økten, fylle på glykogenlagrene før neste økt osv, men dette er i de fleste tilfeller sterkt overdrevet. **Med mindre du skal trene igjen samme dag, har du mer enn god nok tid til å fylle på glykogenlagrene før neste økt.** Etter en periode på lavkarbokosthold, vil fettforbrenningen utgjøre en større del av den totale forbrenningen, også ved høyere intensiteter, noe som også reduserer behovet for karbohydrater. Om du trener for helsen sin del, og ikke har idrettsprestasjoner som mål, vil du heller ikke ha det store behovet for å fylle på glykogenlagrene, siden dette først og fremst er viktig med tanke på prestasjon på høye intensiteter.

Rent praktisk betyr dette at du er litt mer restriktiv i karbohydratinntaket, først og fremst med tanke på brødmat, potet, pasta og ris. Frukt er også noe du mer fordel kan begrense inntaket av til fordel for grønnsaker og bær, men jeg vil likevel ikke anbefale noen å kutte frukt helt ut av kostholdet, da det fint kan inngå som dessert eller til kos.

Det må også nevnes at vi ikke på noen måte anbefaler inaktivitet, noe jeg har skrevet mer om [her](http://www.friskogfunksjonell.no/aktivitetsniva-helse/ "Aktivitetsnivå og helse").

## Hvilke tilpasninger bør en idrettsutøver gjøre?

Er du idrettsutøver, eller [trener du som en idrettsutøver](http://www.friskogfunksjonell.no/tren-som-en-idrettsutover/ "Tren som en idrettsutøver – se ut som en!"), så har du litt andre behov enn dersom du er inaktiv eller trener på mosjonsnistnivå. Det er en strategi du kan benytte deg av for å få det beste fra begge verdener, og dette er det såkalte "train-low, race-high"-prinsippet. **Dette er såklart noe som bør testes ut i en treningssituasjon før du gjør det i konkurranse, men det kan gi deg et fortrinn.**

Som idrettsutøver har du maksimale prestasjoner som mål, og trener mye for å oppnå dette. Da har du først og fremst et økt energibehov sammenlignet med mosjonisten, og må sørge for å få i deg nok mat. Det er også viktig å holde seg mest mulig frisk, slik at man ikke må droppe treningsøkter og bruke masse energi på å restituere seg etter sykdom. Da er det sentralt at maten er av god kvalitet, og dekker behovet for alle [næringsstoffene](http://www.friskogfunksjonell.no/naeringsstoffene/ "Artikkelserie om Næringsstoffene"). **Disse behovene dekker du ved å ha et variert kosthold der du spiser nok!** Behovet for kosttilskudd må vurderes i hvert enkelt tilfelle, og avhenger av hvordan kostholdet ser ut, men de aller fleste vil ha fordel av å benytte tilskudd av omega-3.

**"Train-low, race-high" handler hovedsakelig om å skille mellom det man gjør i treningsperioder og hva man gjør under konkurranse.** Det er ingen tvil om at glykogenlagrene er sentrale når det gjelder prestasjonen, og man bør sikte på å fylle disse før konkurranse. Samtidig er det en fordel at kroppen er godt tilpasset å bruke fett som energikilde ved så høye intensiteter som mulig, siden vi tross alt har mye mer energi lagret i fettvevet enn i glykogenlagrene. Samtidig vil dette bidra med å spare muskelglykogenet, slik at dette reserveres til de hardeste anstrengelsene.

## Hvordan kan dette gjennomføres i praksis?

**I treningsperioden legger du grunnlaget for prestasjonen i konkurranse.** Ved å redusere inntaket av karbohydrater vil du på en effektiv måte lære kroppen å forbrenne fett, da dette blir den mest tilgjengelige energikilden når karbohydratinntaket er lavt. Dette vil gjøre at cellene tilpasser seg for å forbrenne fett mest mulig effektivt, noe som over tid vil gjøre at du i større grad kan bruke fett som energikilde på høyere intensiteter enn du klarte før. Et høyt inntak av fett vil føre til utvikling av fettlagrene i musklene, såkalte intramuskulære triglyserider, som er veldig tilgjengelige som energikilde. Frukt og grønnsaker er basedannende matvarer, og vil bidra til å nøytralisere den sure tilstanden kroppen kommer i etter hard trening blant annet pga. melkesyre. Av denne grunn er det lurt å ha et stort inntak av disse matvaregruppene, spesielt etter trening.

Du vil fremdeles ha behov for karbohydrater under trening, siden du også ønsker å trene på de høyeste intensitetene, og her kommer timing inn i bildet. Når du spiser karbohydrater vil blodsukkeret øke, og bukspyttkjertelen produserer og skiller ut insulin. **Ved siden av å senke blodsukkeret, vil insulin også hemme et enzym som heter hormonsensitiv lipase, som er det enzymet som sørger for frigjøring av fettsyrer fra fettvevet.** Så lenge insulinnivået er høyt, vil dermed mulighetene for fettforbrenning være begrenset. I tillegg vil insulin hemme glykogennedbrytningen. Derfor anbefaler vi ikke å innta noe særlig med karbohydrater de siste 2-3 timene før trening. På denne måten får insulinnivået tid til å synke, noe som er bra siden du ikke ønsker å starte treningsøkten med høyt insulinnivå. Etter trening derimot, vil insulinsensitiviteten være på sitt høyeste, og det er nå på tide å innta mesteparten av dagens karbohydrater. Dette vil bidra til restitusjonen, slik at du raskere blir klar til neste økt.

**Når det kommer til konkurranse, er det på tide å fylle opp glykogenlagrene, slik at du er best mulig rustet til å prestere optimalt.** Hvor lang oppkarbing man trenger vil variere fra person til person, men som utgangspunkt kan du begynne to dager før konkurranse. Gode karbohydratkilder til dette formålet er rotfrukter som potet og søtpotet, havregryn og frukt. Husk også å drikke mye vann i denne perioden, da økte glykogenlagre også betyr at kroppen vil holde på mer vann. Hvis vekten viser litt mer enn vanlig så er dette grunnen!

På selve konkurransedagen gjelder det samme som for trening, at du vil starte konkurransen med lavt insulinnivå. Under aktivitet vil kroppen kunne ta opp karbohydrater uten særlig utskillelse av insulin, og dette er noe du kan benytte til din fordel. **Mot slutten av oppvarmingen kan du få i deg litt lettopptakelige karbohydrater, f.eks. i form av sportsdrikk, tørket frukt eller lignende.** Dette kan gi deg et ekstra gir å gå på, uten at det går så mye utover fettforbrenningen. Denne strategien bør du teste ut i treningssammenheng, slik at du finner en karbohydratkilde og mengde som fungerer for deg.

## **Avslutning**

Målet med denne artikkelen var å fjerne en del av forvirringen rundt dette med å spise lavkarbo, og få fram at det å spise etter disse prinsippene ikke er verken komplisert eller skummelt. Egentlig er jeg ikke så glad i begrepet lavkarbo, siden folk flest forbinder dette med hysteri og ekstremdiett, og vil heller flytte fokuset over på matkvaliteten.

Jeg ønsker ikke å komme med noen retningslinjer på hvor store mengder karbohydrater man bør innta i løpet av en dag, da dette vil være individuelt og alle må finne den mengden som fungerer for seg selv. Det viktigste er å velge matvarer av høy kvalitet, som er minst mulig behandlet og raffinert. Da vil fordelingen av næringsstoffene stort sett falle på plass av seg selv!
