---
title: "10 livsstilstips som virker"
date: 2013.04.15
---

Sommeren nærmer seg, og slankepresset øker for hver dag som går. De fleste av oss går rundt med planer om å passe minst like godt inn i bikinien som i fjor, og etter en vinter og vår der ting har sklidd litt ut så er det på tide å ta seg selv i skinnet. I denne prosessen kommer ofte helseaspektet litt i bakgrunnen, men slik trenger det ikke å være!

Selvfølgelig gjør det det! Jeg har ved flere tidligere anledninger vært inne på viktigheten av å gjøre varige endringer for å oppnå varige resultater, og for de av dere som har fulgt siden en stund så vil det meste her være kjent stoff. Likevel føler jeg at dette er såpass viktig at det fortjener mer spalteplass. Det å innføre gode vaner og gjøre det til en livsstil er det beste du kan gjøre for helsen din, og vil i tillegg til å gi overskudd og god samvittighet også bidra til å forebygge livsstilssykdommer.

Som vanlig er det ikke alle tipsene som vil være like aktuelle for alle. Vi er alle forskjellige og gjør ulike valg fra før. Kanskje følger du allerede mange av rådene? Det beste er å se på de ulike rådene som verktøy, så er det opp til hver enkelt å plukke ut hva man ønsker å gjennomføre ut ifra hva som passer med det du allerede gjør i dag! Husk at flere små endringer til sammen kan utgjøre en stor forskjell!

#### 1. Stump røyken

Det viktigste enkelttiltaket du kan gjøre for helsen din, uten sidestykke, er å [stumpe røyken](stump-royken.qmd). Selv om noen kan røyke hele livet og likevel unngå sykdom, så gjelder dette et mindretall. Røyk er en viktig risikofaktor for en lang rekke sykdommer, der lungekreft, KOLS og hjerte- og karsykdom er de mest alvorlige. I tillegg spiller det inn på andre aspekter som utholdenheten og ikke minst økonomien!

#### 2. Hverdagsaktivitet

Det er mye snakk om trening, men ikke like mye snakk om aktiviteten som skjer resten av dagen. Fra et helseperspektiv er denne minst like viktig, om ikke langt viktigere! Vi er ikke laget for å sitte stille, og hver gang du reiser deg fra stolen så gjør du deg selv en tjeneste. Det å reise seg fra kontorstolen og gå litt i pausene (kanskje ikke bruke den nærmeste kaffemaskinen eller det nærmeste toalettet?), velge trappene i stedet for heisen, gå av bussen to stopp for tidlig eller på andre måter legge inn litt aktivitet der det er mulig kan over tid utgjøre en enorm forskjell! Alle små grep bidrar til totalen, og jo mindre tid på rumpen jo bedre!

**Les også: [Aktivitetsnivå og helse](aktivitet-helse.qmd)**

#### 3. Søvn

Søvn er viktig! Etter en lang dag er det viktig å lade batteriene. Ikke bare vil dette føre til at du blir generelt mer opplagt, men det ser også ut til å påvirke både hvor aktiv du er og hvor mye du spiser. Det å innarbeide gode søvnrutiner kan være veldig vanskelig, men avkastningen av å få det til kan være vel verdt innsatsen som legges ned.

**Les også: [Kan søvnmangel bidra til overvekt?](sovn-overvekt.qmd)**

#### 4. Grønnsaker

Grønnsaker bør inngå i det daglige kostholdet. Ikke bare bidrar det med masse vikige mikronæringsstoffer, det gir også variasjon i måltidet og metter godt på lite energi. Vil du ned i vekt bør grønnsaker utgjøre en stor del av tallerkenen, mens det heller kan begrenses litt dersom du sliter med å gå opp i vekt.

#### 5. Mindre sukker

Å redusere sukkerinntaket er noe de fleste kan tjene mye på rent helsemessig. Tilsatt sukker er det vi kaller tomme kalorier, som betyr at det bare bidrar med energi og ikke med næringsstoffer. Spesielt [sukker i flytende form](brokenlink/bor-du-begrense-inntaket-av-flytende-karbohydrater/) er det lett å få i seg mye av, siden dette metter dårligere enn sukker i fast form. Å bytte ut brus med lettbrus gjør et godt innhugg i sukkerinntaket, og kan være en veldig effektiv måte å begrense seg på.

#### 6. Frukt og bær

Frukt og bær kan være en viktig del av et sunt og variert kosthold. Disse gir god metthet per energimengde, og er et veldig godt alternativ til annen snacks. Frukt og bær bidrar med en rekke mikronæringsstoffer og er en god kilde til løselig fiber. I tillegg finner vi mange andre stoffer, såkalte fytokjemikalier, som har mange egenskaper, både kjente og ukjente. Et kosthold med mye grønnsaker, frukt og bær er assosiert med beskyttelse mot en rekke kreftformer og andre livsstilssykdommer.

#### 7. Spis mindre prosessert mat

Det å i større grad lage maten selv fremfor å velge hel- og halvfabrikata vil i de fleste tilfeller heve kvaliteten på kostholdet ditt. Spesielt når det gjelder diverse kjøtt- og fiskeprodukter som strengt tatt ikke inneholder så mye kjøtt eller fisk, så kommer du bedre ut av det ved heller å velge renere og mindre behandlede produkter. Ettersom ferdigmaten er vår desidert største kilde til salt så vil dette også bidra til å begrense saltinntaket betraktelig, samtidig som hjemmelaget mat også smaker bedre!

Kombinert med å [spise variert](spise-variert.qmd) så sikrer du inntaket av alle næringsstoffene.

#### 8. Slapp av

Stress fører ikke noe godt med seg, så det er viktig å slappe av også. Husk at det er det du gjør mesteparten av tiden som bestemmer mesteparten av resultatene dine, så ikke føl at du må gi alt hele tiden. Det er lov å avvike fra planen av og til, både når det gjelder trening og kosthold. Kanskje kan det å slippe opp litt innimellom være det som gjør at du klarer å få til varige endringer og hindrer at du går på en smell?

#### 9. Drikk vann

Kroppen vår består av 50-60 % vann, og vi trenger påfyll av væske hver dag. Som en tommelfingerregel er væskebehovet 30ml/kg/dag. Å venne seg til å drikke vann i stedet for saft, jus og brus vil for mange kunne bidra til å redusere søtsuget/energiinntaket. I forbindelse med måltider er vann med på å fylle opp magesekken og dermed bidra til at du blir fortere mett.

#### 10. Trening

Trening hører hjemme i en sunn livsstil, men det er ikke ensbetydende med at du må pumpe vekter på gymmet. Det viktigste når det kommer til trening er i mine øyne å finne en aktivitet man trives med, slik at man orker å drive med det regelmessig. Liker du ikke aktiviteten er heller ikke sjansen for at du fortsetter særlig stor.

## Avsluttende ord

Som nevnt i innledningen, så er det ikke meningen at hver og en skal følge alle disse tipsene. Dette er bare forslag til verktøy du kan ta i bruk alt etter hva som passer best i din spesifikke situasjon. Å gjøre store og plutselige omveltninger kan fungere for mange, men samtidig blir slike endringer ofte kortvarige. Mindre endringer er ofte både enklere å gjennomføre og enklere å vedlikeholde.
