---
title: "Målsetninger og artikkelønsker"
date: "2012.01.02"
---

I løpet av 2012 ønsker jeg å utvide Frisk og Funksjonell til å bli en av de ledende helsebloggene i landet. I den forbindelse kommer det etterhvert til å dukke opp flere artikkelforfattere, slik at bredden og kunnskapsnivået økes. Samtidig vil jeg at dere lesere skal være med å sette preg på siden, da det tross alt er dere som leser det vi skriver!

Et av våre mål for 2012 er å vokse oss større, og da ønsker vi å få et nærmere forhold til våre lesere, slik at Frisk og Funksjonell kan utvikle seg i en retning som interesserer flest mulig. Vi vil selvfølgelig gjøre vårt ytterste for å fortsatt fremstå som en troverdig og saklig kilde til informasjon, samtidig som vi vil skrive om ting som opptar folk. Vi setter derfor også stor pris på om dere deler artiklene våre med venner og kjente, slik at flere kan være med å ta del i dette nettstedet!

## Hva vil du lese mer om i 2012?

Vi kommer til å fortsette å utvide kunnskapsbasen med flere faktaartikler om kroppen, forhåpentligvis forklart på en enkel måte så alle kan få noe ut av det. Målet er at denne siden etterhvert skal kunne fungere som et oppslagsverk når det gjelder kroppens funksjoner.

En viktig del i utviklingen av nettsiden er å skrive om ting som opptar folk, og hva er vel bedre enn at dere selv kan sende inn artikkelønsker? Er det noe du vil lese mer om, om det er egne temaer du mener vi bør skrive om, eller om du vil ha kommentarer på avisartikler osv, gi oss beskjed i kommentarfeltet!

## Andre tiltak

Har du tips til andre tiltak vi kan gjøre for å løfte Frisk og Funksjonell opp på et nytt nivå? Gi oss en lyd i kommentarfeltet, alle forslag blir mottatt med stor takknemlighet!
