---
title: "Startposisjon og utførelse av markløft"
date: "2012.03.09"
---

Markløft er en kjempebra øvelse, som virkelig har overføringsverdi til hverdagen og ikke minst til idrettsprestasjoner. Å løfte noe opp fra bakken er en grunnleggende bevegelse for mennesket, og å gjøre dette regelmessig vil gi deg mange fordeler. Her skal vi se på noen av fordelene med markløft, litt ulike varianter av øvelsen, og det som for mange vil være en ny tilnærming til startposisjonen!

Veldig mange som trener styrke benytter seg av en eller annen variant av markløft, og utført riktig er dette helt klart en av de beste øvelsene du kan gjøre for å utvikle en funksjonell fysikk. Kreativ (les:dårlig) utførelse er imidlertid ikke spesielt uvanlig, og da kan dette være en skummel øvelse for ryggen. **Skal du trene markløft, så sørg derfor for at du utfører øvelsen på en god og trygg måte!**

## Fordeler med markløft

**Markløft setter store krav til styrken på hele baksiden av kroppen, hovedsakelig hoftemuskulaturen, som er de sterkeste musklene i kroppen.** **Også kjernemuskulaturen, som jobber for å stabilisere overkroppen under løftet, får kjørt seg godt.** For en idrettsutøver er det hoftemusklene som genererer kraft til å både løpe fort og å hoppe høyt/langt, og i kombinasjon med kjernemusklene brukes også denne kraften både i slag, spark og kast, så å være sterk her vil være en fordel i så godt som alle idretter.

For den generelle helsen vil markløft også være et godt verktøy, da øvelsen forbereder deg på å løfte ting opp fra bakken, som f.eks. et barn eller tunge bæreposer. Regelmessig trening av markløft vil også belaste skjelettet, slik at det vil bidra til å forebygge beinskjørhet.

## Utførelse av markløft

Det er flere varianter av markløft, og man må rett og slett prøve seg fram og se hvilken som føles best for den enkelte. De to hovedvariantene er "vanlig", der man står relativt smalt med beina, og "sumo", der man står bredt. Sumovarianten vil i større grad bruke musklene i beina, mens den vanlige bruker mer rygg. Her vil jeg ta utgangspunkt i den vanlige varianten.

**For å finne riktig bredde på beinstillingen, er det en god tilnærming å stille deg slik du ville gjort om du skulle hoppet så høyt du klarte, og deretter trekke beina litt nærmere hverandre.** Still deg deretter slik at stangen ligger rett over midtpunktet på foten din (mellom hælen og tærne). For å få tyngdepunktet på riktig sted kan det være lurt å ta av skoene, eller løfte med helt flate sko.

Fra denne posisjonen bøyer du deg ned med strake bein og strak rygg (video lenger nede), og tar tak i stangen rett utenfor beina. Press så hoften bakover mens du holder spennet i ryggen. Knærne vil nå bevege seg fremover til leggene dine treffer stangen, og lenger fram enn dette skal ikke knærne! Du kan justere dybden med hofteleddet, men ikke la knærne vandre lenger frem, da de vil komme i veien for stangen på vei opp. Press brystet fram og skuldrene bak. **Dette er startposisjonen din, sørg for at den er lik for hvert løft!**

**Før du løfter stangen, trekker du pusten helt ned i magen og strammer magemusklene for å stive av området rundt korsryggen.** Du er nå klar til å løfte! Dra stangen opp fra gulvet uten å krumme ryggen, når stangen passerer knærne dine, skyter du frem hoften og strammer rumpen for å fullføre løftet. På vei ned gjør du det motsatte, press hoften bakover helt til stangen passerer knærne, og bøy derette i knærne for å sette stangen ned igjen på gulvet. **Stangen skal bevege seg i en rett linje opp og ned, slik som på bildet!**

Jeg vil anbefale at man bruker nøytralt grep, altså overhåndsgrep med begge hendene så langt det går. Når vektene begynner å bli tunge kan det bli nødvendig å snu grepet på den ene siden, noe som gjør det lettere å holde stangen. Da vil jeg anbefale at man bytter litt på hvilken vei man holder!

Kelly Starret fra [mobilitywod](http://www.mobilitywod.com) har en video der han forklarer hvordan man bør komme inn i startposisjonen. Videoen anbefales!\
\[youtube=http://www.youtube.com/watch?v=a-DJu0bEVPw\]

[Her er en litt eldre video av meg som trener markløft](http://www.youtube.com/watch?v=z4pzmYXaqTg). Den er ikke helt optimal, men kan hvertfall gi en liten pekepinn på hvordan det kan se ut!

## Vanlige feil

Du trenger bare å ta turen til nærmeste treningssenter for å finne noen som gjør markløft på direkte skadelige måter. Her er noen av de vanligste feilene:

-   **Krumming av ryggen**. Dette ser ikke spesielt behagelig ut, og det er heller ikke spesielt fornuftig. Om du krummer ryggen, får du en ekstra stor belastning på ryggsøylen, og risikerer å skade deg. I tillegg er det ikke en spesielt effektiv måte å løfte på, og du vil klare å løfte tyngre om du lærer deg å stabilisere ryggsøylen skikkelig.

-   **Tyngdepunktet for langt fremme**. Tyngdepunktet når du løfter skal være midt under foten, eller bakover mot hælen. Det er ikke uvanlig å se folk som har tyngdepunktet frempå tærene, og til og med de som løfter hælen fra bakken i bunnposisjon.

-   **Å ikke gå helt ned.** Mange senker ikke stangen helt ned til gulvet, men stopper litt før og løfter opp igjen. For ryggen sin del er ikke dette spesielt gunstig, siden du da påfører den ekstra belastning i form av å bremse opp og snu hele bevegelsen mens stangen henger på ryggsøylen din.Dette punktet er omdiskutert, og mange vil si at dette ikke er noe problem. Jeg vil likevel anbefale deg å behandle hver repetisjon som et eget løft, og setter stangen ned på gulvet mellom hver gang. Det er en god grunn til at øvelsen heter deadlift på engelsk, og det er at stangen skal ligge "død" på bakken!

-   **Å se overdrevet oppover.** Det er ikke uvanlig å se folk trene markløft mens de ser opp i taket. Tanken bak dette er at det skal gjøre det lettere å holde ryggen strak, men neste gang du ser dette, se hva som skjer med nakken. Prøv å heller feste blikket rett fram, noe som gjør at nakken får en mer naturlig posisjon i forhold til ryggsøylen.

-   **Overekstensjon på toppen.** Løftet er ferdig når du står oppreist med hoften presset fram. Det er ingen grunn til å lene seg så lang man klarer bakover, sånn som mange ser ut til å tro.

**Ved å følge framgangsmåten i avsnittet over vil du unngå alle disse feilene, og utførelsen din blir mye tryggere!**

## Avslutning

Jeg håper at jeg ved dette innlegget har påvirket noen til å teste ut markløft, og at de som gjør en eller flere av de vanligste feilene klarer å rette på dette. Skal du bare trene en øvelse for styrke, så er markløft et godt valg!\
