---
title: "Husk å mate bakteriene dine"
author: "Oddrun Anita Gudbrandsen"
date: 2015.01.12
---

Et voksent menneske består av omtrent 40 000 000 000 000 menneskeceller som skal ha næring og energi for å kunne vokse, dele seg og ta seg av enormt mange ulike og viktige funksjoner i kroppen. Men menneskeceller er ikke nok til å få en menneskekropp til å fungere, så i tillegg har vi rundt ti ganger så mange bakterier og andre mikroorganismer rundt omkring på og i kroppen. Vi har flest bakterier i tykktarmen, der de blant annet bryter ned karbohydrater som menneskeceller ikke kan fordøye, produserer vitaminer, avgifter fremmedstoffer og beskytter kroppen mot fremmede bakterier.

Dette innlegget er først publisert host [BT innsikt](http://innsikt.bt.no/husk-a-mate-bakteriene-dine/), hvor Oddrun er fast bidragsyter.

Vi mennesker har bakterier nesten over alt, som på huden, slimhinnene og i luftveiene, men de aller fleste bakteriene våre lever i magetarmkanalen. Det er en del bakterier i øvre del av tarmen (tynntarmen), men den største mengden finner vi i tykktarmen. Det er flere grunner til det, blant annet at tarminnholdet beveger seg roligere gjennom denne siste delen av tarmen slik at bakteriene får god tid til å ta seg av det som kommer forbi. Mens det vanligvis tar rundt 2-4 timer for tarminnholdet å passere gjennom den 6-7 meter lange tynntarmen, så er passasjetiden normalt 30-70 timer gjennom tykktarmens 1,5 meter. Det er ikke så mange stasjonære bakterier i tynntarmen, men en del bakterier som transporteres gjennom tynntarmen på vei til tykktarmen for å enten gjøre en jobb der eller for å prøve å skape problemer på et sted der de normalt ikke hører hjemme.

Det kan på mange måter virke rart at vi skal ha bakterier i tarmen. Mens antall menneskeceller er strengt regulert, så vil bakterier vokse og dele seg etter hvor mye energi og næring som er tilgjengelig, og dette kan komme ut av kontroll. Ved fødselen får den nyfødte babyen tilført bakterier fra mor allerede i fødselskanalen, og like etter fra mors og andres hud og luftveier, og fra miljøet rundt. Disse pionér-bakteriene etablerer seg babyens tykktarm, slimhinner og hud, og etablerer miljøer der de selv trives og der andre typer bakterier kan få problemer med å få fotfeste. Tarmbakteriene har blitt overført fra generasjon til generasjon, og har utviklet seg sammen med oss over årtusener. I tykktarmen har bakteriene skaffet seg et beskyttet og næringsrikt hjem, og til gjengjeld utfører de flere oppgaver som er til nytte for oss ved å blant annet ha en barriærefunksjonen som beskytter oss mot skadelige bakterier som ikke klarer å etablere seg i et velregulert miljø. I vår moderne medisinske verden kan bruk av antibiotika endre balansen mellom bakterier i tarmen og gjøre det lettere for oppblomstring/overvekst av skadelige bakterier.

Tarmbakteriene er helt avhengige av tilførsel av energi og næring via kostholdet vårt for å kunne leve, vokse og dele seg. I riktig gamle dager, da tilgangen på energi og næring ikke var så god som i dag, var bakteriene i tykktarmen helt nødvendige for å utnytte plantemat. Hvis vi fjerner alle tarmbakterier fra rotter så må de må spise 30% mer for å opprettholde kroppsvekten sin sammenlignet med rotter med normal bakterieflora, og det sier noe om hvor viktig tarmbakteriene kan ha vært for mennesker i tidligere tider men også for mennesker i vår tid som ikke har tilgang på tilstrekkelig næringsrik mat. Bakteriene i tykktarmen spiser plantefibre som våre celler ikke kan fordøye fordi vi mangler de nødvendige enzymene. Dette kalles fermentering, og bakteriene skaffer seg det de trenger samtidig som de produserer en del avfallsstoffer som de ikke har bruk for, blant annet de kortkjedete fettsyrene acetat, propionat og butyrat som er verdifulle for våre celler. Disse kortkjedete fettsyrene er den viktigste energikilden for tarmceller i tykktarmen, og de tas opp fra tykktarm og går over i blodet for transport til lever, muskler og andre vevstyper der de også brukes som energi.

Helsefordelene med å spise fiberrik mat er mange og veldokumenterte. Dette inkluderer bedre kontroll av kroppsvekt, appetitt, blodsukkerregulering og insulinfølsomhet og kolesterolnivået. Det er godt mulig at mange av de gode helseeffektene av å spise fiber skyldes økt produksjon av kortkjedete fettsyrer i tykktarmen, siden disse kan øke fettsyreforbrenningen, hindre produksjon av kolesterol i lever og øke nivåene av metthetshormoner.

Bakteriene i tykktarmen påvirker også fremmede stoffer som medisiner og miljøgifter, stoffer fra kosmetikk og tilsetninger i mat som kommer ned i tykktarmen ved å påvirke aktiviteten, tilgjengeligheten og giftigheten av disse stoffene. Disse fremmedstoffene kan være harmløse eller giftige, men uansett behandles de av tarmbakteriene som fremmede. Hittil er ikke så mye kjent om hvilke tarmbakterier som bryter ned fremmedstoffer, eller hvilke produkter som dannes, men det er kjent at tarmbakterier kan inaktivere noen medisintyper og danne giftige produkter av andre.

Tykktarmen har også en egen produksjon av flere vitaminer, blant annet vitamin [B1](naeringsstoffer/thiamin.qmd "Thiamin, vitamin B1"), [B2](naeringsstoffer/riboflavin.qmd "Riboflavin, vitamin B2"), [B3](naeringsstoffer/niacin.qmd "Niacin, vitamin B3"), [B5](naeringsstoffer/pantotensyre.qmd "Pantotensyre, vitamin B5"), [B6](naeringsstoffer/pyridoksin.qmd "Pyridoksin, vitamin B6"), [B7](naeringsstoffer/biotin.qmd "Biotin, vitamin B7"), [B12](naeringsstoffer/kobalamin.qmd "Kobalamin, vitamin B12") og [K2](naeringsstoffer/kvitamin.qmd "K-vitamin"). Mens Vitamin B12 antagelig ikke tas opp fra tykktarmen til blodet, så kan det se ut til at bakterieprodusert vitamin K2 kan tas opp og spille en rolle i prosesser i menneskekroppen. Sannsynligvis bidrar ikke bakterieproduksjon av vitamin B1, B2, B3, B5, B6 og B7 i særlig grad til ernæringsstatusen til våre celler, men det er mulig at de kan spille en rolle lokalt i tykktarmen blant annet ved å ha antioksiderende og betennelsesdempende effekter.

Siden tarmbakteriene er helt avhengige av hva vi spiser og drikker, så vil sammensetningen av bakteriefloraen i tykktarmen påvirkes av kostholdet. Det er ikke bare fiber og fremmedstoffer som blir tatt hånd om av disse bakteriene, men også proteiner fra kosten brytes ned til kortkjedete fettsyrer i tarmen. I tillegg omdannes de forgrenete aminosyrene leusin, isoleusin og valin i proteiner til forgrenete fettsyrer som kan ha helseeffekter.

#### Vi vet foreløpig ikke så mye om hvordan ulike proteintyper påvirker tarmbakteriene, og derfor setter vi snart i gang en studie for å se om proteiner fra fisk og kjøtt har ulike effekter på tarmbakteriene våre.

#### Hvis du kan tenke deg å donere avføring til et spennende prosjekt så ta kontakt med oss på protein\@k2.uib.no.
