---
title: "Medieskapt kroppsideal som årsak til negativt selvbilde og forstyrret spiseatferd"
author: "Asle Bøe"
date: 2014.02.24
---

I vårt samfunn har medieeksponering for kroppsideal blitt en selvfølge. Det antas at skjønnhetsidealer fører til at vi prøver å etterstrebe disse , spesielt gjennom motebransjen, reklame og populærkultur.

Visse kroppstyper og ideal blir fremhevet enten bevisst eller ubevisst. Disse er ofte kulturelt betinget – å være slank er ikke et tidløst ideal som kan fristilles fra samfunnet det oppstår i, men det spiller på viktige evolusjonære mekanismer.

Indikatorer på evolusjonær fitness eller attråverd er signaler om at en klarer seg godt i et gitt miljø, enten på tross av eller på grunn av egenskaper. For mennesker er egenskaper som ungdom, helse og intelligens høyt verdsatt, det samme er sosial status. Vi må ikke bare vise vi har god helse, men også at vi er istand til å tilpasse oss sameksistens. Mennesker er sosiale flokkdyr, og avhengig av å kunne fungere sammen med andre mennesker. Sosial status gir makt, tilgang på ressurser og bedret evne til å finne en make eller flere.

Når mediebildet da blir en del av samfunnet og bevisst fremviser enkelte ideal og tillegger det sosial status og attråverd kan vi komme i den situasjonen at vi skaper et virkelighetsfjernt ideal som fører til vesentlig stress for de som prøver å etterleve det.

Det er velkjent at ungdom som eksponeres for blader der visse ideal er fremtredende, [som tynne modeller er mer tilbøyelig](http://demoiselle2femme.org/wp-content/uploads/Body-Image-and-Self-Esteem-Among-Girls.pdf) til å være misfornøyd med sin egen kropp. Bedre blir det ikke av at bildene manipuleres, slik at personen på bildet ikke engang ser ut som seg selv når bladet kommer på trykk eller billboardet rager i bybildet. Her er det åpenbart overlappende effekter: Eksponeringen kan både komme som følge av og forsterke allerede eksisterende usikkerhet.

## En studie fra Fiji

Hva skjer når en befolkning som tidligere ikke har vært eksponert for de medieskapte idealene plutselig blir det? En [spennende studie av dette ble gjort blant unge jente-fijier](http://bjp.rcpsych.org/content/180/6/509.full), som ble studert før og etter intensiv eksponering for helt vanlige TV-serier. Etter eksponeringen ble det rapportert om økt forekomst av spiseforstyrrelser, slanking og forsøk på å etterleve idealene som ble indirekte fremvist gjennom mediet. En slik deskriptiv studie som benytter seg av ikke-klinisk rapportering av forstyrret spiseatferd har åpenbare svakheter, men gir også spennende informasjon om subjektiv opplevelse.

Jentene i studien rapporterte økt selvbevissthet, og var veldig klar over hvordan de skilte seg fra personene i TV-seriene de fulgte med på. Denne effekten kan ha blitt forsterket av at fijiene i utgangspunktet ikke ligner på de kaukasiske personene som dominerte serien, men det fører til en rekke interessante spørsmål.

TV begynte for alvor å bli vanlig i 1995, og etter tre års eksponering ble en gruppe jenter som nå hadde vokst opp med TV blitt intervjuet. Tradisjonelle fiji-idealer hevdes å være mer i retning av en robust og hardfør kroppstype, noe som står i sterk kontrast til de slanke skikkelsene som dominerer det vestlige mediebildet.

Siden flere ble bevisst kroppen sin og hvordan de spiste, skulle en ikke da tro de ble mer motivert til å gjøre noe med det? [Data fra 1993 og utover](http://www.ijbnpa.org/content/pdf/1479-5868-10-45.pdf) peker på en tredobling av overvekt blant unge fijier – en dramatisk utvikling , med en tydelig utvikling mot et mer vestlig kosthold.

De tidligere kulturelle faktorene som begrenset slankeatferd, bulimi og spiseforstyrrelser ble nesten umiddelbart overstyrt da TV ble allemannseie. At medier som fremviser smale kroppsideal utøver sterk påvirkningskraft på unge jenter har vært kjent lenge, men dette er den eneste studien som meg bekjent tar for seg hva som skjer i en befolkning som tidligere ikke er eksponert for disse idealene.

Sitater fra intervjuene i studien er nokså interessante:

> … most of the time when I watch TV… when I look at \[the actresses\] they… look… thin, and they do most of the things I can’t do, so I just want to lose my weight again. (s-44)
>
> I want to be like \[Cindy Crawford\]… I want to be like that, very tall, \[I\] want to be taller and thinner… \[TV\] always affects me that… I always say how thin I want to become… I wanted to become that thin, but I always tried to become that thin. (s-48)
>
> … the actresses and all those girls, especially those European girls, I just like, I just admire them and I want to be like them. I want their body, I want their size. I want myself to be \[in\] the same position as they are…. Because Fijians are, most of us Fijians are, many of us, most, I can say most, we are brought up with those heavy foods, and our bodies are, we are getting fat. And now, we are feeling, we feel that it is bad to have this huge body. We have to have those thin, slim bodies \[on TV\].’ (s-64)
>
> \[TV\] teaches me what I should do, and what I should not do.’ (s-26)
>
> Culture in Fiji normally accepts women here as big, heavy. In the TV, the women are thin… (s-58)
>
> My mom wants me to look like her, like growing fat like that, but I don’t want that.’ (s-50)

## Så, hvor står vi i dag?

Selv om kroppsidealet blant unge jenter har endret seg markant, og de ikke lengre bruker mødrene og medsøstrene sine som referanser øker overvekten i befolkningen raskt. Det er et komplekst årsaksbilde, men jeg tror neppe at uoppnåelige ideal og sosial sammenligning med fiktive personer bidrar med noe positivt i så måte.

Jeg tenker umiddelbart på alle bildene og filmene av veltrente kropper ervervet med og uten bruk av prestasjonsfremmende, og måten de profileres på som en motvekt til den økende overvekten i samfunnet for øvrig. Er det virkelig motiverende, eller er det bare en del av fiksjonen som gjør oss mer ulykkelige samtidig som vi ikke gjør noe med de grunnleggende årsakene?
