---
title: "Midlertidige løsninger - midlertidige resultater"
date: "2012.03.23"
---

Jojo-slanking virker å være veldig populært. Hvor mange finnes det som har slanket seg gang på gang, med stadig nye metoder, uten å oppnå varige resultater? Jeg vet ikke, men svaret er mange! Veldig mange! Er det sånn at når man først har blitt overvektig så er det ingen vei tilbake? Slik er det selvfølgelig ikke, men hva er hemmeligheten til alle de som har oppnådd varige forbedringer av helsen sin?

## Den store hemmeligheten

Sannheten er at det å gå ned i vekt er et spørsmål om energibalanse. Om man over tid tilfører kroppen mindre energi enn den forbruker, så vil dette gå utover energilagrene våre (les: fettvevet), og man går ned i vekt. Dette kalles å være i energiunderskudd. På samme måte vil et energioverskudd føre til at vi lagrer energi, og kroppsvekten går opp. Om vekten holder seg stabil, er man i det som heter energibalanse, altså at inntak og forbruk over tid er i balanse.

Det du kan få ut av avsnittet over er at dersom kroppsvekten din har økt over tid, har du vært i energioverskudd, uansett hvor mye du har spist eller trent. Om vekten har gått nedover, har du vært i energiunderskudd, også uavhengig av hvor mye du har spist eller trent. **Det motsatte er nemlig ikke mulig, uansett hvor mye enkelte prøver å argumentere for det!**

Dette betyr likevel ikke at det bare er å spise mindre og trene mer, for denne tilnærmingen har ikke akkurat vist seg å være særlig effektiv i kampen mot de ekstra kiloene, hvertfall om vi ser på store grupper. **Dette handler om at inntak og forbruk ikke er uavhengige faktorer.** Dette betyr enkelt forklart at dersom du spiser mer, så forbrenner du også mer, og spiser du mindre så forbrenner du mindre. Dette er kroppen sin måte å motvirke store endringer i kroppsvekt, og er et ledd i det som heter homeostase, eller på godt norsk; likevekt.

Det er selvfølgelig mange tilpasninger som skjer i kroppen for å motvirke endringer i energiinntaket, men hovedfaktoren er det som kalles spontan aktivitet. Dette er den aktiviteten du ikke tenker så mye over, men som likevel øker det generelle aktivitetsnivået. For å skjønne hvordan energiinntaket påvirker denne faktoren, så kan du tenke deg at når du spiser lite så blir du slapp, og det frister mest å sitte i sofaen. Om du derimot har spist mye, kan du oppleve at det kribler i beina, og at det å sitte i ro blir utenkelig. Dette er selvfølgelig en grov overforenkling, men poenget er at kroppen gjør tilpasninger for å tilstrebe å opprettholde en stabil vekt. Dette gjør at det ofte kan være vanskelig å gå ned i vekt. **Når du føler at kroppen motarbeider deg, så er det faktisk akkurat det som skjer!**

## Andre faktorer, sult og metthet

En annen tilpasning som skjer i kroppen når kroppsvekten forandrer seg, er at det blir en endring i signalene som stimulerer sult og metthet. Hvis du spiser mindre, så vil sultfølelsen stimuleres. Dette er hovedårsaken til at typiske lavkaloridietter ikke gir varige resultater for en stor del av de som har prøvd. **Etterhvert som man går sulten, øker risikoen for å øke matinntaket igjen, og før eller siden sprekker de fleste.** Jo mindre man spiser, jo større er sjansen for at man sprekker, så slike slankeopplegg fører sjelden til varige resultater. Som Andreas Eenfeldt skriver i boken sin, Matrevolusjonen: **Bak skrivebordet kan man se bort i fra sultfølelsen, men i virkeligheten må vi forholde oss til den.** Dette betyr i praksis at det ikke er noe problem å sette opp en kostholdsplan med lite mat, men å følge den over tid kan by på store problemer.

Alle reagerer ulikt på forskjellige typer mat. Der noen blir stappmett av karbohydratrik mat, vil denne maten føre til en økt sultfølelse hos andre. Det samme er tilfellet med fettrike matvarer, som for mange metter både godt og langvarig, mens andre har lett for å overspise på denne maten. Hvordan du reagerer på de ulike matvarene handler blant annet om insulinsensitiviteten, og jo dårligere denne er jo dårligere vil du tåle karbohydrater. Typisk vil insulinsensitiviteten blir dårligere etterhvert som vi legger på oss, så det første jeg personlig ville redusert på er de største karbohydratkildene, og da hovedsakelig de raffinerte karbohydratene som sukker og hvitt mel. Trening vil bidra til å forbedre insulinsensitiviteten, så hvis du trener mye vil du også tåle karbohydrater bedre enn om du er inaktiv. **Dette er bare en liten del av det store bildet, men det viser hvorfor det er viktig å tilpasse kostholdet til individet!**

Det som er felles for de fleste, er at protein er det makronæringsstoffet som metter best per energimengde, så om du vil ned i vekt kan det være en god ide å øke inntaket av proteinrike matvarer som kjøtt, fisk, egg og meieriprodukter. Dette er noe jeg vil anbefale til alle som ønsker å gå ned i vekt og bli der!

## Viktigheten av å endre livsstil

Som du sikkert skjønner nå, så er varige endringer den store hemmeligheten bak å oppnå varige resultater. Grunnen til at de fleste slankekurer mislykkes i lengden, er at man slutter å følge dem. Som tittelen påpeker, midlertidige løsninger vil bare gi midlertidige resultater! Her er det viktig å skifte fokus! **Du er nødt til å finne et kosthold du kan leve med over tid, som samtidig gjør at du klarer å moderere inntaket.**

For å få dette til er det flere ting å ta hensyn til:

-   Du bør basere kostholdet på mat du liker.

-   Du bør tilpasse måltidsrytmen slik at det passer med din hverdag.

-   Du bør være fleksibel nok til at du takler uplanlagte utskeielser.

-   Endringene må ikke gå ut over livskvaliteten din

Gode resultater forutsetter selvfølgelig at du gjør gode valg i matveien. Alle skjønner at det ikke er et sjakktrekk å spise chips og brus til hvert måltid, men hva bør du egentlig spise? Her på siden finner du flere artikler som tar for seg dette med kosthold, og flere vil komme i fremtiden:

-   [Våre råd for bedre helse](helserad.qmd)

-   [Diett eller livsstilsendring?](diett-livsstilsendring.qmd)

-   [Innføring i lavkarbo på en fornuftig måte](lavkarbo-livsstil.qmd)

-   3 tiltak for et bedre kosthold, [del 1](kosthold-tiltak-1.qmd)

-   [Hva er periodisk faste?](periodisk-faste-jul)

I denne artikkelen har jeg fokusert på kostholdet, men den fysiske aktiviteten er selvfølgelig også sentral, og her gjelder det samme som ved kosthold, nemlig at du må gjøre varige endringer. Å trene mye i en periode for så å slutte vil ikke gi deg særlig gode resultater i lengden. **Da er det bedre å gradvis gjøre endringer som er lette å opprettholde, slik at fysisk aktivitet etterhvert blir en naturlig del av livet ditt!**

Det ligger flere artikler her på siden som kan hjelpe deg i gang med treningen:

-   [Aktivitetsnivå og helse](aktivitet-helse.qmd)

-   [Tren som en idrettsutøver](tren-som-en-idrettsutover.qmd)

-   [Nybegynnerkurs i utholdenhetstrening](utholdenhet.qmd)

-   Bli sterkere med mengdetrening, [del 1](mengdetrening-1.qmd)

En ting er sikkert, om du gjør midlertidige endringer i livsstilen din, så vil resultatene garantert også bli midlertidige. Går du tilbake til det du gjorde før, så vil kroppen din også i de fleste tilfeller gå tilbake til slik den så ut før. Jeg håper at du etter å ha lest denne artikkelen er motivert til å gjøre endringer i din egen livsstil, og at du skjønner at midlertidige løsninger ikke er veien å gå!

**Husk at enhver endring til det bedre vil være positivt for helsen din som helhet, så du trenger ikke å endre alt på en gang. Begynn i det små, så kan du øke på etterhvert!**
