---
title: "Morgenfugl eller nattugle - når bør du trene?"
author: "Asle Bøe"
date: 2023.05.20
---

Noen elsker å starte dagen med en treningsøkt, mens andre ikke engang orker tanken. Hvilken av disse personene er du, og har du noen gang tenkt på hvorvidt det du gjør er det mest fornuftige? Kraftutviklingspotensialet forandrer seg nemlig utover dagen. For å si det litt enkelt - dersom du snubler ut av sengen og inn i et knebøystativ, ligger ikke forholdene akkurat til rette for et nytt maksløft!

Men hvorfor er det sånn?

Artikkelen er originalt publisert hos [Myrevolution](http://myrevolution.no/s/morgenfugl-eller-nattugle-nar-bor-du-trene/).

Kroppstemperaturen er lavere om morningen, både sentralt og i muskulaturen. Mellomvirvelskivene i ryggraden har absorbert væske iløpet av natten, og i løpet av dagen komprimeres ryggraden og væsken siver ut. Det kan derfor være lurt å vente noen timer før en går løs på de tyngste vektene, selv om det er få som tenker på maksimal styrketrening rett etter de har våknet.  Så mange runder som mulig på snooze-knappen er som regel nok.

## Morgenfugler og nattugler

Mens noen våkner av seg selv, strekker seg og går og slår av vekkerklokken fem minutter før den ringer, velter en god del av oss ut sengen med tannkosten i ene hånden mens den andre febrilsk prøver å få på klærne som ligger slengt på gulvet.**\
**\
Morgenfuglene, eller a-menneskene, våkner tidlig og sovner tidlig. Nattuglene sitter og ser på morsomme bilder sent og står opp sent og motvillig. Selv har jeg prøvd å trene om morgenen – for å være helt ærlig så har jeg prøvd bare å fungere om morgenen. Hele mitt voksne liv, og spesielt i ungdomsårene, har det ikke slått feil. I morgentimene er det vanskelig å se forskjell på meg og en av zombiene i Walking Dead, men utover kvelden føler jeg meg bedre og bedre.

Treningene er bedre, vektene lettere og kreativiteten flyter over... Litt upraktisk om en må være oppe om et par timer. Internett blir også markant gøyere i de små timene over midnatt.

## Variasjoner i prestasjon gjennom dagen

Tamm og kolleger ville se på hvordan kronotype, eller det vi i dagligtale omtaler som A og B-mennesker, påvirker evnen til kraftutvikling gjennom dagen (1). Eksperimentene foregikk ved at deltagerne, 18 mennesker, ble delt i to grupper basert på hva de svarte på et spørreskjema. 9 morgenmennesker og 9 kveldsmennesker ble utsatt for tester klokken 9, 13, 17 og 21 på en enkelt dag.

De benyttet seg av hjernebarkstimulering, elektrisk stimulering av tibialisnerven og elektromyografiske (EMG) målinger av muskelaktivitet og isometriske kraftutviklingsmålinger. De skulle  evaluere hjernens eksitabilitetsgrad , spinaleksitabilitet og kraftutviklingspotensialet til triceps surae, eller leggen på godt norsk.

Idet du bestemmer deg for å utføre et muskulært arbeid, sendes det nerveimpulser fra motoriske sentre gjennom ryggraden, ut i det perifere nervesystemet og til motoriske enheter i muskelen eller musklene som skal utføre arbeidet.

Morgenmenneskene hadde størst kortikal eksitabilitet klokken 9, spinal eksitabilitet var høyest kl 21 og det var ingen betydelige forskjeller i EMG eller kraftutvikling gjennom dagen. I kontrast til dette viste kveldsmenneskene parallelle økninger i kortikal og spinal eksitabilitet gjennom dagen, som ble assosiert med økninger i EMG-aktivitet og kraftutviklingspotensiale hos nattuglene.

Forskerne foreslår at den parallelle økningen i kortikal og spinal eksitabilitet hos kveldsmenneskene øker kraftutviklingspotensialet gjennom en dag. Videre påpeker de at disse funnene har implikasjoner for å maksimere menneskelig ytelse og setter fokus på betydningen av kronotype på individers døgnrytme.

Dersom du er en morgenfugl som  er oppe før du fiser, og trives med morgentreninger - flott! For oss andre kan det imidlertid være fornuftig å legge styrketreningen til ettermiddagen dersom målet er effektiv styrketrening. En vil fremdeles kunne få gode resultater med trening tidlig på dagen – det er bare ikke nødvendigvis optimalt.

## Fungerer oppvarming?

En gruppe forskere ledet av Edwards og kolleger publiserte nettopp resultatene fra en studie som så på det samme som Tamm og kolleger fra 2009, men med flere tester (2). De illustrerer godt hvordan den vitenskapelige prosessen fungerer – hver studie skaper flere spørsmål og hypoteser enn svar, og dette forskes det videre på.

Det er kjent at muskelkraft og kraftutviklingspotensiale er lavere om morgenen og at dette kan henge sammen med motivasjon, perifere og sentrale nevrale faktorer. Som nevnt er også kjerne- og muskeltemperaturen høyere om kvelden enn om morgenen. Forskerne ville derfor se om en kunne reversere tapet av styrke gjennom å isteden for en kjapp oppvarming på 5 min varme opp passivt og aktivt til kjernetemperaturen nådde kveldsnivå. Studien ble gjennomført på 10 unge, aktive menn. Forskjellen på morgen- og kveldstemperatur var 0.56°C og o.74°C.

Samme tendens som i det første forsøket ble observert: Redusert kraft om morgenen kontra kvelden. Hverken aktiv eller passiv oppvarming gjorde at morgenprestasjonen var like god som kveldsprestasjonen. Dette kan antyde at kroppstemperatur ikke medvirker til reduksjonen i kraftutvikling, men at grunnen ligger mer sentralt og er nevral av natur.

Jeg skulle likt å sett et forsøk med en litt mer progressiv dynamisk oppvarming og egenmassasje. Flere og flere får øynene opp for bruksområdene til massasjeruller som Rumble Roller og strikk til aktiveringsøvelser før trening og [ellers](underholdningsslavens-redning.qmd).

## Kan sentralstimulerende tilskudd ha effekt?

Salget av energidrikker som inneholder koffein tar helt av, og koffein er hyppig brukt i både ren form og fra ekstrakter av te , kaffe og guarana i fettforbrenningsprodukter. Det er mange grunner til at kaffe, te , energidrikker og koffeintilskudd er så populært. En av grunnene er at folk *føler* de blir mer våkne og energiske – men gjør dette at de trener bedre?

I en studie av Rodriguez og kolleger fra 2012 ble effekten av koffein på døgnvariasjonene i prestasjon undersøkt (3). Forsøkspersonene, som var “trente” unge menn fikk 3 mg/kg koffein – 240 mg for en mann på 80 kg.  Inntak av koffein fikk dynamisk styrke og kraftutvikling om morgenen til å øke betraktelig.

Dette er en liten enkeltstudie, og det finnes langt mer forskning på emnet enn det som presenteres her.

## Praktiske implikasjoner

-   Dersom du har valget mellom å trene om morgenen eller kvelden vil det kunne være fornuftig å trene om kvelden dersom målet er muskelvekst og styrke.
-   Dersom du fungerer godt om morgenen og trives med å trene da vil du ha fremgang likevel – og vil kanskje til og med tilpasse deg morgenøkter slik at du ikke har redusert kraft om morgenen i forhold til om kvelden. Kun spekulasjon.
-   Dersom du skal ha to økter om dagen, la morgenøkten være en lett teknikkøkt og la de tunge løftene være til kveldstreningen.
-   Dersom målet med treningen kun er å trives med aktivitet og å faktisk trene – tren når du kan og vil.
-   Dersom du skal trene om morgenen kan en kopp kaffe eller to være fornuftig. Alternativt noe annet som inneholder koffein.
-   Vær lydhør til hvordan kroppen din trives med det du gjør og hvilke resultater du oppnår – det er individuelle hensyn å ta som gjør at ikke alt passer alle. Vi er nemlig ikke like!
