---
title: "Nøkkelhull, bare tull?"
date: "2012.01.20"
---

I et forsøk på å gjøre det enklere å velge sunn mat, lanserte myndighetene i 2009 nøkkelhullsmerket. Dette er en ordning som har eksistert i Sverige siden 1989, og har som mål å få oss til å velge matvarer som utifra noen enkle kriterier regnes som sunnere enn andre matvarer i samme kategori. Helsemagasinet VOF publiserte i utgave nr.3 2011 en artikkel som het "Nøkkelhull - bare tull?", der de kommer med ganske krass kritikk mot denne måten å merke matvarer på.

Også de store matvarekjedene har satt sitt spor i denne saken, først og fremst Kiwi, som kuttet momsen på alle nøkkelhullsprodukter og de andre kjedene fulgte etter. Er nøkkelhullsmerket mat nødvendigvis sunn mat, og hvordan bør man eventuelt tolke denne merkeordningen?

## Hva er nøkkelhullsmerket?

Nøkkelhullsmerket er et merke som produsenter av matvarer kan sette på produktene sine dersom de oppfyller visse krav. Kravene for å kunne få nøkkelhull varierer litt for de ulike matvaregruppene, men hovedtrekkene er at produktet skal ha et maksimumsinnhold av fett, sukker og salt, samt ha et minsteinnhold av kostfiber. For en mer nøyaktig oversikt over de ulike kravene, besøk [hjemmesiden til nøkkelhullsmerket](http://www.nokkelhullsmerket.no/nokkelhull/Matvarer/article234.ece).

**En matvare som er merket med nøkkelhull er, utifra kravene for merking, regnet som et sunnere valg enn tilsvarende produkter i samme matvaregruppe.** Her er det mange som misforstår, og setter likhetstegn mellom nøkkelhull og sunt.

Nøkkelhullsordningen er frivillig, noe som betyr at produsenten selv velger om de vil merke produktene sine med nøkkelhull. Etter at Kiwi i 2011 gjorde en innsats for å redusere prisen på nøkkelhullsvarene, har flere produsenter valgt å ikke lenger merke sine produkter, da de tjener mindre penger på å selge dem med nøkkelhullsmerket.

## Fordeler med nøkkelhullet

På [NFE og NSE sitt høstseminar](http://www.friskogfunksjonell.no/hostseminar/ "Rapport fra høstseminar i Oslo: Karbohydrater og helse") 2011 snakket Linn Anne Brunborg om nøkkelhullsmerkingen. Hun nevnte at forbruksdata viser at vi i større grad velger nøkkelhullsmerkede produkter når vi handler, noe som tyder på at dette er en effektiv måte å påvirke forbrukerne på.

Vi kommer ikke bort fra at folk flest har veldig liten kunnskap om hva de putter i munnen, **og en slik merkeordning er absolutt på sin plass for å gjøre det enklere å velge rett.** Gjennomført på en god måte kan en slik ordning gjøre veldig mye for folkehelsen, noe som er viktig å ta i betraktning når vi skal diskutere den!

**Formidlingen av kunnskap til befolkningen må gjøres på en måte som alle forstår, og noe så enkelt og banalt som å se etter nøkkelhullet krever ikke mer enn at vi er klar over hva nøkkelhullet er.**

## Ulemper med nøkkelhullet

Det største problemet med nøkkelhullet i dag er at det forutsetter at de kravene som benyttes er satt på riktige premisser. Per i dag er man veldig uenige om hva som er sunt, noe kostdebatten er et veldig tydelig tegn på. Er det nødvendigvis riktig at et produkt som inneholder mindre fett er et bedre valg enn et som inneholder mer? Ernæringsstudent Hanne Storhaug har gått gjennom [kunnskapsgrunnlaget bak fettanbefalingene](http://www.friskogfunksjonell.no/de-offentlige-anbefalingene-for-fett-godt-begrunnet/ "De offentlige anbefalingene for fett, godt begrunnet?"), og hennes konklusjon samsvarer ikke helt med kostrådene.

Når det kommer til de kravene som er satt, så må det nevnes at det kan være uheldig å ha et sånt fokus på enkelte næringsstoffer. **Vi spiser tross alt mat, ikke næringsstoffer, og om en matvare inneholder noe som sees på som uheldig, kan matvaren likevel totalt sett være sunn.** Kravene om fettinhold tar f.eks. ikke hensyn til fettsammensetningen i matvaren, bare totalinnholdet, noe som ikke gir et godt bilde av hvor gunstig denne matvaren er. Jeg har tidligere skrevet om viktigheten av å ha [balanse mellom omega-6 og omega-3](http://www.friskogfunksjonell.no/omega-3-og-omega-6-i-kostholdet/ "Omega-3 og Omega-6 i kostholdet"). Likevel ser vi at matoljer og plantemargariner med skyhøyt omega-6-innhold får nøkkelhullsmerket, mens mer nøytrale fettkilder som smør og bremykt ikke får det. Grove kornprodukter kan fint få nøkkelhull utelukkende pga sitt høye fiberinnhold, uten at det tas hensyn til at det kan være [flere problemer forbundet med korn enn vi liker å tro](http://fitnessbloggen.no/god-helse-korn/).

I tillegg har vi det problemet jeg nevnte lenger oppe, at **folk setter likhetstegn mellom nøkkelhull og sunn mat**, noe som ikke er riktig. For eksempel har Grandiosa fått nøkkelhull, noe som bare betyr at den, utifra kravene, er hakket bedre enn annen frossenpizza, [selv om forskjellene i realiteten er minimale](http://fitnessbloggen.no/nokkelhullsmerket-grandiosa/). Dette handler i stor grad om hvordan nøkkelhullet blir oppfattet blant folk, og bedre informasjon kan gjøre noe med dette problemet, men i mine øyne burde hurtigmat vært utelukket fra hele ordningen! Dag Viljen Poleszynski skriver i sin artikkel for VOF at nøkkelhullet "*hovedsakelig deles ut til sterkt bearbeidede produkter*", og selv om dette ikke nødvendigvis er helt presist, så er jeg enig i at dette kan være et problem.

## Konklusjon

Nøkkelhullsordningen, slik den er i dag, fungerer i mine øyne dårlig. Dette handler ikke om ordningen i seg selv, men først og fremst hvordan folk oppfatter den. I tillegg blir det vanskelig å få til en god merkeordning så lenge det er så stor uenighet om hva som faktisk er et sunt kosthold. Om en slik merkeordning skal være vellykket, burde fokuset vært lagt på de tingene alle er enige om:

-   Øke forbruket av grønnsaker, bær og frukt

-   Redusere inntaket av sukker og raffinerte karbohydrater

-   Øke inntaket av fisk og sjømat

Utifra disse kriteriene vil all frukt og grønt og all sjømat få merket, og det meste av ferdigmat med høyt innhold av sukker, fint mel og prosessert fett vil ikke få merket. Så lenge det er uenighet og uklarhet i effektene av mettet fett, burde ikke myndighetene gå aktivt inn for å styre forbruket vekk fra disse fettsyrene. Etter min mening blir det feil å anbefale å redusere på mettet fett, men det blir også feil å oppfordre til et ukritisk inntak. Det burde også vært innført et anti-nøkkelhull som merket varer som alle er enige om er usunne, altså matvarer med høyt innhold av sukker. **Det trykkes store helseadvarsler på røykpakkene, så hvorfor ikke merke brus og godteri på en tilsvarende måte?**

Med disse tankene i bakhodet ville merkeordningen fått en annen funksjon, nemlig å vise hvilke matvarer man trygt kan spise masse av, og også vise hva man burde spise minst mulig av. For å påvirke forbrukerne til å kjøpe merkede matvarer, burde prispolitiske vedtak (momskutt) kommet fra myndighetenes side, slik at disse matvarene ble mer tilgjengelige. Da hadde ikke produsentene av disse varene tapt penger på å merke varene sine sånn som de faktisk gjør i dag. Dette kunne vært oppveid gjennom en momsøkning på de matvarene som ble merket som usunne. Dette er tiltak som hadde vært veldig positivt for folkehelsen, da det effektivt hadde vridd forbruket i en gunstig retning.

Jeg mener med andre ord at en merkeordning er helt på sin plass, men den må nødvendigvis utformes på en annen måte om den skal ha ønskede effekter på folkehelsen! I mellomtiden vil jeg henvise til [våre råd for bedre helse](http://www.friskogfunksjonell.no/vare-rad-for-bedre-helse/ "Våre råd for bedre helse"), som gir deg gode retningslinjer for hvilken mat du bør velge!

Hva mener du, fungerer dagens ordning eller burde den endres?
