---
title: "Rapport fra høstseminar i Oslo: Karbohydrater og helse"
author: "Vegard Lysne"
date: "2011.11.07"
categories: 
  - konferanse
  - kosthold
---

Fredag 4. november arrangerte [Nasjonalt Selskap for Ernæring](http://nse-info.no/) (NSE) i samarbeid med [Norsk Forening for Ernæringsfysiologer](http://nfe.no/) (NFE) årets høstseminar. Temaet denne gangen var karbohydrater og helse, noe som kan regnes som et høyaktuelt tema sett i lys av den pågående kostdebatten.

På programmet stod foreleserene Torunn Nordbø, Anja Olsen, Espen Rostrup, Andreas Eenfeldt og Linn Anne Brunborg, og temaene strakte seg fra helseaspekter ved den nordiske dietten, via ulike sider ved lavkarbokosthold og over på industriens utfordringer med tanke på å utvikle sunne produkter. Alt lå til rette for en spennende dag!

Førstemann på talerstolen var leder for NSE, Pernille Baarseth. Hun fortalte oss litt om NSE sin historie, fra stiftelsen i 1981, og hva de har jobbet med fram til i dag. For noen år siden så NSE seg nødt til å slå seg sammen med NFE for å arrangere disse seminarene, da de innså at de kjempet om det samme publikumet, en kamp begge ville tape på i det lange løp. Siden den gang har det blitt arrangert et årlig høstseminar, og interessen er økende.

Her sammendrag fra de ulike foredragene vi ble servert denne fredagen!

### **Hvordan fokuset på brød og korn i forhold til ernæring har endret seg i løpet av de siste 30 år**

v/Torunn Nordbø, [Opplysningskontoret for Brød og Korn](http://www.brodogkorn.no/)

Med tanke på at Nordbø representerer opplysningskontoret for brød og korn, kom det ikke som en overraskelse at hun i foredraget stilte seg svært positiv til nettopp disse komponentene av kostholdet. Hun kunne fortelle at opplysningskontoret for brød og korn stod for "sunn matglede med brød og korn til alle måltider", og gikk langt i å anbefale alle å etterkomme dette.

Mesteparten av foredraget bestod av ulike statistikker, som skulle beskrive nordmenns holdninger til korn og fullkorn. Personlig synes jeg dette ble veldig uoversiktlig, og man skulle følge godt med for å ikke gå i surr i alle prosentene. Noen tall jeg likevel registrerte var at 25% av energien i et gjennomsnittlig norsk kosthold kommer fra korn, og hele 75% av matmelet vårt kommer fra norskprodusert korn.

Mange er likevel interessert i å redusere forbruket av kornprodukter, og 5% av de spurte oppgav at de ikke spiste brød i det hele tatt. De primære årsakene folk oppgir til at de ønsker å redusere kornforbruket er helse og sunnhet, etterfulgt av at «brød er kjedelig».

Det ble også snakket en del om kostfiber. ***"Alle er enige om at kostfiber er sunt"***, sa Nordbø, og begrunnet dette med helseeffekter som forebygging av kreft, utifra data fra [WCRF](http://wcrf.org/).

Deretter uttalte hun at ***"siden korn er vår største kilde til fiber er det god grunn til å anbefale at vi spiser mer korn"***, noe jeg mener blir en alvorlig logisk feilslutning. At vi i dagens kosthold får i oss mye fiber fra kornprodukter er ikke en gyldig begrunnelse for å øke inntaket.

### Helseaspekter av den nordiske diett

v/Anja Olsen, [Danish Cancer Society](http://www.cancer.dk/om+os/The+Danish+Cancer+Society.htm)

Anja Olsen har vært med på å utføre en studie der de har sett på [aspekter med det nordiske kostholdet,](http://www.ncbi.nlm.nih.gov/pubmed/21346102) og fortalte om denne. Det ble fastslått at vi i Norden har et høyere inntak av fullkorn sammenlignet med andre vestlige land, men forfatterne av studien har undersøkt om det også er andre komponenter med spesielle positive helseeffekter.

Først var det nødvendig å definere hva en typisk nordisk diett har bestått av. Det ble trukket fram at vi tradisjonelt sett har spist mye kjøtt, fullfete meieriprodukter og mer smør enn vi spiser i dag, og frokosten har typisk bestått av havregrøt. Selv om flere av disse matvarene ble omtalt som usunne, ble det understreket at den nordiske dietten tradisjonelt sett har vært sunn når vi ser på helheten.

Anja fortalte så om studien de hadde utført, der de så på effekten av enkeltkomponenter i kostholdet. Inklusjonskriteriene for å bli tatt med i studien var at matvaren måtte være å finne i nordisk natur, ha en kvantitativ betydning i kostholdet og ha dokumenterte helseeffekter. De endte opp med 6 matvarer, som utgjorde Healthy Nordic Food Index: Fisk, rotfrukter, rugbrød, havregryn, epler/pærer og kål.

Denne indeksen fungerer slik at for hver matvare der inntaket er lik gjennomsnittsinntaket eller høyere, får man ett poeng, altså maksimalt seks poeng. Når man så på sammenhengen mellom inntaket av disse matvarene og dødeligheten, fant man at for hvert poeng sank dødeligheten med 4%. Forfatterne så også på forekomsten av tykktarmskreft, og her ble det ikke funnet noen selvstendig effekt for noen av matvarene. Siden dette er en observasjonsstudie, kan ikke resultatene si noe om årsakssammenheng, slik at studien ikke på noen måte kan regnes som sikkert bevis for noe.

Til slutt viste Olsen noen bilder av sin datter som med stor innsats spiste noen av de nevnte matvarene, og brukte dette som et argument for at den nordiske dietten er velsmakende!

### Balansert lavkarbodiett

v/[Espen Rostrup](http://espenrostrup.com), Haukeland Universitetssykehus.

Espen startet sitt foredrag med å vise to forsider fra VG, der lavkarbo var det sunneste av det sunne på den ene, og vår største fiende på den andre. Dette beskriver på mange måter hvordan lavkarbodebatten har utviklet seg i media. Han etterspør en debatt som i større grad bygger på vitenskap og fakta, og i mindre grad på synsing og følelser. Espen tok så for seg ulike aspekter ved lavkarbokosthold, og viste til forskning som underbygget det han sa. Han påpekte også at lavkarbo nå er inne i varmen både hos helsemyndighetene og hos ADA og Diabetes UK, som vektreduksjonsdietter.

De første temaene som ble tatt opp var kolesterol og aterosklerose. Ny forskning viser at det ikke er så enkelt som vi tidligere har trodd. Totalkolesterolet er ingen god prediktor, og heller ikke HDL/LDL forteller hele sannheten. Det viser seg nå at LDL kommer i ulike størrelser, og det er først og fremst de minste partiklene som er forbundet med høy risiko for hjertesykdom. Dette forklarte Espen med at de minste partiklene i større grad er utsatt for oksidasjon, og de små oksiderte LDL-partiklene kan passere gjennom åreveggene og fanges. Disse er i større grad er knyttet til årsaken til aterosklerosen. Et lavkarbokosthold er assosiert med større LDL-partikler, mens et fettfattig kosthold i større grad er assosiert med en økt mengde små, tette LDL-partikler.

Når det gjelder kostholdsfett, tok Espen for seg noen av de studiene nasjonalt råd for ernæring har brukt som referanser for sine anbefalinger, og påpekte en del svakheter ved kunnskapsgrunnlaget. For det første er det stadig flere studier som viser at det ikke er noen sammenheng mellom mettet fett og hjertesykdom. Når det gjelder studier på lavfettkosthold, finnes det bare to randomiserte prospektive studier, og ingen av disse viser noen effekt når det kommer til dødeligheten. En del studier viser positive effekter av å erstatte noe mettet fett med flerumettet fett, men dersom mettet fett erstattes med karbohydrater ser vi motsatt effekt. Disse studiene viser likevel ikke noen effekt på dødeligheten, men en marginal nedgang i forekomsten. Espen påpekte at for å få signifikante resultater måtte de ta med Oslostudien i metaanalysen, og denne studien var en multiintervensjonsstudie der blant annet røykeslutt var sentralt. Forfatterne ***"måtte ha med en røykesluttstudie for at resultatene skal bli signifikante"***, kommenterte han!

Evidensen for et magert kosthold er i stor grad basert på små, kortvarige studier. Disse har i tillegg ikke sett på dødeligheten, men såkalte myke endepunkt, som kan være endring i risikofaktorene (f.eks. kolesterol, som vi åpenbart ikke vet så mye om likevel).

Det er gjort en del studier som sammenligner lavkarbokosthold med lavfettkosthold, og Espen tok opp et par punkter angående disse:

-   Lavkarbogruppen får ofte spise ad libitum (dvs til de er mette), mens lavfettgruppen som oftest har begrensninger i energiinntaket.

-   De fleste studiene viser lik effekt, eller går i favør lavkarbo, selv om resultatene ikke alltid er signifikante.

-   Metabolske risikoparametre forbedres som oftest best i lavkarbogruppen.

Randomiserte kostholdsstudier viser ikke virkeligheten, siden motivasjonen for å følge opplegget ikke alltid er like høy når du blir tildelt en diett som du ikke nødvendigvis har så stor tro på eller har lyst til å følge. Espen påpekte at dette kan ha en stor del av ansvaret for at resultatene mellom gruppene ofte jevner seg ut over tid. Han etterlyste en studie der man velger motiverte deltakere til de ulike gruppene, slik at vi i større grad kan se effekten av å faktisk følge de ulike oppleggene.

Avsluttningsvis sa Espen at helsemyndighetene i større grad burde ta i bruk lavkarbo som et alternativ, og at de ikke måtte **"*skremme folk bort fra et verktøy som kan være veldig nyttig for veldig mange"*!**

### Lavkarbodiett ved fedme og diabetes, hva sier forskningen?

v/[Andreas Eenfeldt](http://www.kostdoktorn.se), lege og spesialist i allmennmedisin, Sverige

Utgangspunktet for Andreas sitt foredrag er den voldsomme økningen i overvekt og fedme vi har vært vitne til de siste 30 årene, etter at de offentlige kostholdsanbefalingene virkelig begynte å påvirke hva folk spiste! På bare en generasjon, har forekomsten av fedme blitt tredoblet, noe som ikke kan forklares genetisk. Det må med andre ord være noe som er forandret i miljøet vi lever i, og Andreas mener tydelig at den mest kritiske endringen har skjedd i  kostholdet vårt!

I 1984 publiserte magasinet Time en artikkel om kolesterol, og den sammenhengen vi trodde det var mellom kolesterolnivået og hjertesykdom. Ifølge Eenfeldt var evidensen bortimot ubetydelig, men vi trodde sterkt på denne teorien, og den ble derfor sentral i de kostrådene som fulgte.

Andreas må sies å være en tilhenger av insulinhypotesen, som grovt sett sier at et økt inntak av karbohydrater fører til en økt insulinproduksjon, noe som fører til mer fettlagring og økt forekomst av overvekt og fedme. Når vi fant ut at kolesterol var negativt, førte dette til en fettfrykt, og vi skulle nå redusere inntaket av fett. For at en slik reduksjon skulle være mulig, måtte naturligvis inntaket av noe annet økes tilsvarende, og dette annet ble da karbohydrater.

Eenfeldt påpeker at det finnes flere eksempler på befolkninger som har et høyt inntak av karbohydrater, som likevel ikke har problemer med verken overvekt eller andre metabolske forstyrrelser. Felles for disse befolkningene er at store deler av karbohydratene kommer fra frukt og rotfrukter, og ikke fra sukker og andre høyglykemiske matvarer, slik som ofte er tilfelle i den vestlige verden. Det er ikke frukt og rotfrukter som har erstattet fettet i vårt kosthold, men heller dårlige karbohydrater fra mat som pommes frites, brus, is og store mengder brødmat.

Mange kaller lavkarbo for en motediett, men Eenfeldt snur på dette og stiller spørsmålet om ikke fettfattig kosthold kan kalles en motediett. Vi har tross alt ikke spist denne nye maten så veldig lenge, og det finnes sterke indikasjoner på at mennesket opp gjennom tiden har spist mer i tråd med lavkarboprinsipper. ***"Frykten for fett har ført til de kostrådene vi har i dag*****"**, påpeker han.

Det siste temaet for dette foredraget var kosthold for diabetikere. I dag får diabetikere råd om å spise etter de offentlige anbefalingene, og det understrekes at mat som øker blodsukkeret langsomt er bra, eksemplifisert ved brød, pasta, ris, potet og frukt. Andreas sammenligner dette med [anbefalingene diabetikerne fikk tidligere](http://www.archive.org/stream/diabeticcookeryr00oppeiala#page/12/mode/2up), før vi hadde blodsukkermedikamenter. Alle de anbefalte matvarene var da omtalt som mat som var strengt forbudt, pga sin blodsukkerøkende effekt, og diabetikerne ble bedt om å heller spise mat som kjøtt, fisk, egg og smør.

Lavkarbokosthold gir, som Espen påpekte i sitt foredrag, best resultat når det gjelder forbedring av metabolske risikofaktorer, sier Andreas, og avslutter med at ***"det er på tide å forlate 80-tallet*****"**!

### Hvilken utfordring har industrien til å utvikle sunnere produkter og måltider?

v/Linn Anne Brunborg, PhD i human ernæring, [Norgesmøllene](http://www.mollerens.no/Norgesmollene/).

Linn Anne startet sitt foredrag med å fortelle at hun stillte seg svært positiv til lavkarbokosthold rettet mot de med insulinresistens og overvekt. Hun var likevel veldig skeptisk til om dette var et kosthold som passet for alle, og trakk fram et [avisoppslag](http://sprek.bt.no/henvisninger_sprek/--Vondt--trene-med-lavkarbo-11687.html) om Andrine Flemmen som hadde testet streng lavkarbo i en måned, og ikke fikk til å trene som normalt. Det kan selvfølgelig diskuteres hvorvidt en måned er lang nok varighet til å konkludere med noe, men vi kan likevel med stor sikkerhet slå fast at folk vil reagere ulikt på et kosthold, og at individuelle tilpasninger vil være nødvendig.

Når det gjelder industriens utfordringer, fokuserte Brunborg naturligvis på kornindustrien, siden hun tross alt representerer denne. Hun kunne blant annet fortelle at ***"industrien har hørt på kostrådene og økt utmalingsgraden på melet*****"**, noe som betyr at andelen fullkorn er økt. Mens de foregående foredragene fortalte om lavkarbokostholdets effekter på blodsukkeret, påpekte Brunborg at man ***"kan få et like stabilt blodsukker på et karbohydratrikt kosthold*****".**

Korn består av flere komponenter; kli, kim og kjerne. Fullkorn inneholder alle tre delene, mens raffinert korn hovedsakelig består av kjernen. Det er vanskelig å skille effektene av de ulike delene fra hverandre, men foreløpig har man konkludert med at fullkorn er det vi bør spise mer av. Gjennomsnittlig inntak av fullkorn i dag er 50g, mens anbefalingene er på 70-90g. Vi har med andre ord en del å gå på her.

Nøkkelhullsmerkingen av matvarer har blitt sterkt kritisert, og mange mener at en slik merkeordning ikke er bra. Brunborg fortalte at denne merkingen har vært svært effektiv for å få folk til å velge de merkede matvarene, og understrekte at vi i stedet for å diskutere selve merkeordningen burde diskutere kriteriene for den. Selve prinsippet med å merke sunne matvarer mente hun at vi burde holde på, siden dette åpenbart er en effektiv måte å kommunisere med forbrukerne på.

Til slutt i sitt foredrag ville Brunborg rette lyset mot noen globale trender som hun så på som positive:

-   Folk flest ser ut til å endre holdninger til å gå på diett, og fokuserer i større grad på å endre livsstil.

-   Det er et økende fokus på naturlig mat.

-   Vi ser en forbedring i kvaliteten på ferdig tilberedte måltider, men dette setter fremdeles store krav til industrien når det gjelder å ytterligere forbedre disse produktene.

Som avslutning hadde Linn Anne en oppfordring om at vi må ***"lære den oppvoksende generasjonen å lage mat fra bunnen av*****"**, og om kostdebatten i media hadde hun bare en ting å si: ***"Lite smak og lite glede!"***

### Diskusjon

Den siste halvtimen var viet spørsmål til deltakerne, og ikke overraskende var det Rostrup og Eenfeldt som fikk de fleste spørsmålene rettet mot seg. Mitt totalinntrykk etter spørrerunden, er at veldig mange viser stor interesse for å forstå hva lavkarbo handler om, og sånn sett var dette et veldig positivt seminar når vi tenker på den polariserte debatten vi er vitne til i media. Mange virket fornøyd med at lavkarbo først og fremst ble rettet mot folk med insulinresistens og overvekt, selv om det også kom fram at det ikke burde være noe i veien for å velge et slikt kosthold om du er frisk og normalvektig heller.

Alt i alt vil jeg si at dette var et svært vellykket seminar der folk fra begge sider av debatten fikk uttale seg, og mange gikk nok derfra en del klokere enn de var når de kom!
