---
title: "5 overkommelige nyttårsforsetter"
date: 2014.01.02
---

Røyken etter nyttårsrakettene har lagt seg og det er på tide med nyttårsforsetter! Her vil jeg presentere 5 forslag til overkommelige nyttårsforsetter som alle vil bidra positivt for helsen din. 

## 1. Spis grønnsaker hver dag

Grønnsaker er naturens egen supermat, som bidrar med drøssevis av næringsstoffer, masse fiber og lite energi. Dette er en matvaregruppe du kan spise nærmest ubegrenset av. Det er anbefalt å spise minst fem porsjoner frukt og grønnsaker hver dag, og det er ingen grunn til å ikke la grønnsaker utgjøre brorparten av dette. Det kan i tillegg bidra til å øke metthetsfølelsen og dermed bidra til å redusere energiinntaket.

Om du fra før ikke spiser grønnsaker daglig, vil det å sikte mot å inkludere grønnsaker hver dag være en forbedring av kostholdet ditt. Spiser du allerede grønnsaker hver dag, kan det være et greit mål å øke inntaket.

## 2. Spis mer frukt

Frukt inneholder mindre vitaminer og mineraler og mer energi enn grønnsaker, men også frukten har en plass i et sunt kosthold. Frukten fyller en annen funksjon enn grønnsaker, og kan bidra som både desserter og mellommåltider. Selv om frukten er mer energitett enn grønnsaker, er det fremdeles jevnt over en lite energitett matvaregruppe sammenlignet med det meste annet vi spiser.

Ved å øke inntaket av frukt, spesielt om det erstatter andre alternativer, vil du redusere energitettheten i kostholdet ditt. Dette er gunstig for å begrense energiinntaket, som kan være en vesentlig faktor for å ta vare på helsen. Det er blant annet holdepunkter for at å begrense ennergiinntaket er gunstig med tanke på å forebygge kreft, og et kosthold rikt på frukt er også assosiert med god helse.

## 3. Øk hverdagsaktiviteten, sitt mindre

Vi sitter mye. Mange av oss har stillesittende jobber, og mange av oss kommer oss til og fra jobb sittende i en bil eller på en buss. På ettermiddagen har de fleste av oss en sofa, og den trenger også kjærlig omsorg etter å ha stått alene hele dagen.

Vi er ikke laget for å sitte i ro, og faktisk er stillesitting i seg selv satt i sammenheng med økt sykelighet. Alle tiltak som får oss opp fra stolen burde være hjertelig velkomne, så hvorfor ikke benytte seg av de mulighetene man har, og her er det mye å velge mellom. For det første er det mulig å gå av bussen et eller to stopp før du er fremme og spasere de siste minuttene. Når du først er på jobb eller skole er det ingenting i veien for å benytte seg av toalett, hente kaffe eller gjennomføre andre nødvendige gjøremål i etasjen over, og når vi først var inne på det, trappen er et bedre valg enn heisen - alltid.

Husk at mange små tiltak tilsammen kan utgjøre en betydelig forskjell, så her er det bare å bruke fantasien og finne muligheter.

## 4. Bytt ut sukkerdrikke med vann eller kunstig søtet drikke

[Kunstige søtstoffer](brokenlink/sotstoffer/ "Søtstoffer"), og da spesielt aspartam, har vært hyppig oppe til diskusjon i 2013, og kommer nok også til å være det i året som kommer. Samtidig er den mest omfattende rapporten vedrørende aspartam nylig publisert, og nok en gang konkluderes det med at det ikke er grunn til bekymring med et realistisk inntak.

Vann er den beste tørstedrikk, det er det ingen tvil om, og det beste er å i størst mulig grad holde seg til dette. Likevel, dersom du fra før drikker mye sukkerholdig brus eller saft vil det å bytte dette ut mot kunstig søtet drikke bidra til å redusere inntaket av sukker og energi.

## 5. Prioriter søvn

Det å sove nok er [veldig viktig for helsen](brokenlink/sovn-viktigere-enn-du-tror/ "Søvn – viktigere enn du tror!"). Når vi sover får kroppen restituert seg, og ikke minst er søvnen viktig for den hormonelle regulerinegn. Det er også holdepunkter for at søvnmangel kan være en [bidra til utvikling av overvekt](brokenlink/sovn-og-overvekt-2/ "Søvn og overvekt – Større sammenheng enn vi tror?") gjennom å stimulere til overspising.

Hva som er nok søvn er individuelt, men våkner du stadig opp trøtt og sliten er det kanskje en god idé å prioritere søvn et hakk eller to høyere.

I denne underholdende [videoen](http://www.youtube.com/watch?v=rqbAsr6wN_I) forteller Mike Evans litt om dette med nyttårsforsetter.

## 
