---
title: "En pekefinger i flere retninger"
author: "Thomas Olsen"
date: 2013.01.07
---

I løpet av året som har gått har fokuset på kosthold, trening og en bedre folkehelse for alvor manifestert seg i det norske samfunnet. Hva man spiser nå, hva man spiste før, hvordan man skal trene, og hvordan man ikke minst skal leve for å best mulig øke livskvaliteten blir heftig debattert både på blogger, i aviser og på statlig TV. Lavkarbo eller høykarbo? Steinalder eller kornbasert kosthold? Styrketrening eller kondisjonstrening? Diskusjonene florerer, og rådene spriker som aldri før.

På toppen av det hele krangler fagfolk på hver sin side av spekteret om hva som er optimale anbefalinger for mannen i gata og gjør forvirringen komplett. De stakkars tilskuerne som er ment å opplyses, som ønsker informasjon om hvordan de kan leve optimalt basert på sin situasjon, blir stående midt i skuddlinjen. De ender opp med å kunne enda mindre enn tidligere. I tillegg har vi mektige medieredaksjoner som blåser opp og sensasjonaliserer resultater som egentlig er av relativt ubetydelig verdi. Kaoset er komplett!

## Hvorfor er det egentlig blitt slik?

Når det kommer til kosthold og ernæring etterstreber man en fasit. Noe som fungerer for alle, og som skal redde helsen vår. Denne fasiten skal senke den samfunnsøkonomiske belastningen knyttet til livsstilssykdommer og heve livskvaliteten vår ytterligere.  Konservative fagfolk, gjerne professorer, er av den gamle skolen, og proklamerer det vi alle har hørt før; mettet fett er farlig og gjør deg syk. På andre siden har vi nærmest revolusjonære knopper som fremmer blomstrende høy-fett kosthold som løsningen. Korn er roten til alt vondt, og man blir syk av karbohydrater, og gjerne også av pasteurisert og homogenisert melk. Felles for dem begge? Begge fremmer sine synspunkt som løsningen på de store folkehelseproblemene både i Norge og den industrialiserte verden og gjerne enda me,r ved hjelp av generalisering. Men hva er det man glemmer når man generaliserer? Når man bastant proklamerer det som fungerer for èn selv og for en gruppering i en observasjonsstudie eller populasjoner ellers? Midt i det hele blir individet glemt.

Å trekke slutninger innenfor ernæring og kosthold er farlig, hadde vi hatt en fasit hadde vi ikke hatt livsstilssykdommer den dag i dag. Utallige coacher, kliniske ernæringsfysiologer, bloggere, personlige trenere og andre som jobber innenfor folkehelsen har sin egen oppfatning av hva som fungerer for seg selv, og de har gjerne en skokk med tilhengere hvor det samme har fungert for dem. Det er vel og bra det, men, en tendens jeg ser hos svært mange er at man overser enkeltpersonen. Å tilnærme seg en pasient/klient som ernæringsfysiolog eller som kostholdsveileder handler på mange måter om å samarbeide med pasient/klient mot et felles mål. Da skulle man tro at det første som slår rot i hjernebarken er å jobbe utfra pasientens/klientens forutsetninger,  ikke slenge ut standardiserte matplaner og menyer som tar utgangspunkt i hva som har fungert for deg og andre eller hva du har troen på, og din egen personlige overbevisning.

Skal man legge om et kosthold og endre livsstil må man ta hensyn til individualitet.  Å legge om vaner man har opparbeidet seg gjennom 20-50 år tar tid, og gjøres ikke over natten. Kontekst er viktig, og uten å vite mer om en persons preferanser og målsetninger er det umulig å gi noe som ligner på en fasit på hva denne personen bør spise. Hvem, hva, hvorfor, hvor mye og hva annet er blant spørsmålene som er viktig å utforske først!

## Individualisering i praksis

La oss ta utgangspunkt i korn. Hvorfor skal en som ikke reagerer på korn, men er svært glad i havregrynet sitt til frokost, fordi det fungerer og det holder ham mett,  kutte dette helt ut av kostholdet sitt? Hva om problemet sitter andre steder, som micro-pizzaen+ cola til lunsj, og helgekos fra fredag til søndag? Denne hypotetiske personen kan helt fint ha et kosthold som passer dens livsstil, og som føles optimalt for han/henne, som innebærer havregryn til frokost. Kanskje er dette noe personen ikke ønsker å endre. Skal man da likevel gjøre inngrep? **I mitt hode?** Nei. En person kan helt fint ha et kosthold som er optimalt for han/henne selv om det inneholder korn, og en tilnærming i retning rådgivning som gis av myndigheter vil virke fornuftig, **samtidig som man tar hensyn til resten av bildet.**

La oss ta det motsatte tilfelle. Bør en person som ikke er spesielt glad i korn eller poteter, men liker grønnsaker og frukt godt, inkludere korn og poteter i kostholdet sitt, når han vil klare seg helt fint uten og samtidig dekke næringsbehovet sitt? Svaret er følgelig nei basert på de samme prinsippene som over. Frukt og grønnsaker er helt klart er mer næringstett enn brød og poteter. Her er kanskje en lavkarbo tilnærming noe å vurdere i veiledning og rådgivning, **samtidig som man tar hensyn til resten av bildet**.

Man skal gjøre endringer der personen ønsker å gjøre endringer, og der personen selv mener han/hun er i stand til å gjøre endringer. Som veiledere kan vi styre i riktig retning, men valg og endringer kan gjerne komme som forslag fra kunden selv, og man kan komme frem til forslag sammen.

Selvfølgelig skal vi også trekke inn helse som et særdeles viktig parameter også, men dette inngår som en del av konteksten og perspektivet og det vi tar hensyn til når vi veileder. Poenget med denne artikkelen er hva som i stor grad skal tas hensyn til, men hva som glemmes, av paleovennene og lavkarbo-forkjemperne, av professorer og helsedirektoratet. Nemlig prinsippet om individualitet, og en personlig tilnærming basert på ønsker, behov og målsetninger. Det viktigste er å stake ut en sti som fungerer for deg, og som man selv kan leve med, som samtidig hjelper deg å nå målene dine. For noen er det mye fett og proteiner som skal til for å holde seg mett, for andre er dette et kosthold basert på grovt brød og melk.

## Dagens debatt

Dessverre er det blitt slik at fanebærere fra hver sin side, spesielt med tanke på kosthold, er blitt ekstremt unyanserte i sitt syn på hva som fungerer. I stedet for å være objektiv og vurdere studier og litteratur med nøytrale øyne, leser man det man vil lese, tolker det på sin egen måte, og presenterer resultater av egen interesse som det som fungerer for alle. Kosthold og ernæring handler i svært stor grad om preferanser, ønsker, kultur, vaner og behov, hvorav alle faktorer er svært personlige og i aller høyeste grad individuelle. Noen har ikke mentalitet eller viljestyrke til å forandre alle sidene ved kostholdet sitt, men de kan gjennomføre noen som unektelig kan gi resultater, og det er her man skal begynne, og det er dette man skal ta utgangspunkt i.

Skulle man ta utgangspunkt i alt man kan lese på internett, så vil veien fremover kanskje se mest ut som dette...

Ernæring og kosthold er et levende felt, og på samme måte som at professorer bør og skal ta ny forskning i mot med åpne armer, bør og skal man heller ikke dra konklusjoner basert på et tynnere grunnlag til tross for at det er voksende evidens for den ene siden av saken. En vanskelig kunst å mestre, men som er helt fullstendig vesentlig, og dessverre også tilsynelatende glemt.

Unyanserte uttalelser fra begge sider har ikke skapt annet enn konflikt og forvirring i 2012, la oss håpe de åpner øynene i 2013.
