---
title: "Periodisk faste til jul?"
author: "Vegard Lysne"
date: "2011.11.28"
categories: 
  - kosthold
  - faste
---

Julen er tradisjonelt sett en tid på året der vekten går opp, før nyttårsforsettene setter inn og de ekstra kiloene skal bekjempes med nebb og klør. Det ville gjerne vært mer praktisk å holde en mer stabil kroppsvekt året gjennom, men av flere grunner er det mer vanlig at vekten varierer. De gjeldende rådene handler om å spise regelmessig og at dette er veien til suksess. I denne artikkelen skal jeg fortelle litt om en alternativ måte å spise på, som har gitt gode resultater for mange, nemlig periodisk faste.

## Hva er periodisk faste?

Periodisk faste er en måte å spise på som har økt i popularitet de siste årene. En av de fremste forkjemperne for dette kostholdsmønsteret er Martin Berkhan, som driver siden [Leangains](http://www.leangains.com/). I prinsippet er periodisk faste et veldig enkelt konsept. Du faster 14-16 timer i døgnet, for så å spise hele dagens energiinntak i det gjenværende spisevinduet på 8-10 timer. Det er både fordeler og ulemper med å spise på denne måten, og hvilke av disse som virker sterkest på deg vil avgjøre hvorvidt du vil trives med å spise slik eller ikke. Det er også noen vanlige myter som står i sterk kontrast til dette. La oss se på noen av disse tingene:

#### Fordeler:

-   Du kan spise store måltider, og dermed spise deg skikkelig mett.

-   Etterhvert som du tilpasser kroppen dette måltidsmønsteret vil du ikke ha en sultfølelse som hopper opp og ned som en sprettball, og i større grad kunne fokusere på andre ting enn mat.

#### Ulemper:

-   Omstillingsfasen kan være preget av en kraftig sultfølelse, siden kroppen er vant til å få tilførsel av energ med jevnere mellomrom. Dette vil imidlertid raskt tilpasse seg hos de aller fleste.

-   Hvis du pleier å trene tidlig på morningen kan det være negativt dersom det går veldig lang tid før kroppen får mat. Jeg skriver kan, siden det finnes strategier for å unngå dette problemet, og mange gjør også dette og får gode resultater.

#### Myter:

-   **Man må spise frokost for å sette i gang forbrenningen.** Dette er noe som har blitt gjentatt så mange ganger at det til slutt har blitt sant. Det finnes imidlertid ingen beviser for at dette skulle være tilfelle, og det er mange empiriske bevis på det motsatte. Alt handler om hva kroppen er vant til!

-   **Ved å spise sjeldent senker man forbrenningen (å spise ofte øker forbrenningen)**. Dette er også et eksempel på hvordan noe blir sant bare det gjentas ofte nok. Måltidsfrekvensen har ingen påvirkning på totalforbrenningen, og isokaloriske (likt totalinntak) studier som sammenligner ulike måltidsmønstre, finner ingen forskjell når det gjelder den totale forbrenningen \[1-3\]. Så lenge energiinntaket er likt, spiller det altså ingen rolle for forbrenningen hvor mange måltider du fordeler dette på!

-   **Å spise sjelden fører til et ustabilt blodsukker.** En artikkel som ble publisert i fjor \[4\] viste at blodsukkeret over en 12-timers periode var høyere ved 6 måltider enn ved 3, selv om den totale insulinresponsen var lik. Det kan altså synes som om en lavere måltidsfrekvens gir bedre kontroll på blodsukkeret.

-   **Du kan bare ta opp X mengde protein per måltid.** Dette brukes ofte som et argument for at man bør fordele næringsinntaket over flere små måltider. Det finnes imidlertid ingen beviser for at dette skulle være sant. I realiteten vil så godt som alt du spiser absorberes i tarmen, uavhengig av hvor store måltider du spiser. Dette vil reguleres ved at maten tømmes ut av magesekken med en lavere hastighet.

## Hvordan gjennomføre periodisk faste?

Den enkle oppskriften på periodisk faste er å fastsette et spisevindu, f.eks. på 8 timer. Utenom dette spisevinduet inntar du bare vann, og evt kaffe/usøtet te. I denne perioden tvinger du kroppen til å hente energi fra egne lagre. Insulinnivået vil være lavt, og fettreservene vil derfor være lett tilgjengelige.

Hvor mange måltider du velger å spise i spisevinduet er individuelt, men 2-3 måltider er vanlig. Dette kommer an på hvor store energibehov du har, og dersom behovet er stort kan det være nødvendig med et ekstra måltid.

Når det gjelder sammensetningen av næringsstoffene, blir dette opp til den enkelte. Noen trives best med lite [karbohydrater](http://www.friskogfunksjonell.no/karbohydrater/ "Karbohydrater") og mye [fett](http://www.friskogfunksjonellno//fett/ "Fetthttp://friskogfunksjonell.wordpress.com/2011/10/17/fett/"), mens andre ikke takler fett så godt og heller velger karbohydrater. Som i artikkelen om [lavkarbokosthold](http://www.friskogfunksjonell.no/en-enkel-innforing-i-lavkarbokosthold/ "En kort innføring i lavkarbokosthold og tilpasning til din livsstil"), anbefaler jeg å legge fokuset på kvaliteten på matvarene fremfor fordelingen av næringsstoffer. Så lenge du spiser variert mat av god kvalitet, ordner sammensetningen av næringsstoffer seg selv.

#### Periodisk faste er for deg som:

-   Liker å spise deg skikkelig mett på store måltider

-   Liker å sove litt ekstra om morningen i stedet for å bruke tid på å lage og spise frokost

-   Heller vil lage 2-3 gode måltider om dagen fremfor å spise kjedelig brødmat og andre raske alternativer

-   Liker å ha ekstra god kontroll på kostholdet og derfor fører regnskap med det du spiser. Dette blir enklere jo færre måltid du spiser.

#### Periodisk faste er ikke for deg som:

-   **Har inflammatorisk tarmsykdom (Crohns eller ulcerøs kolitt) eller er plaget med irritabel tarm.** Ved disse tilstandene vil store måltider ikke være veien å gå, siden næringsopptaket i tarmen vil være lavere enn vanlig, og store måltider kan føre til ubesvær som diaré.

-   **Er idrettsutøver med store treningsmengder.** Som idrettsutøver har du et økt energibehov, og det kan være vanskelig å få i seg all denne maten på et kort spisevindu. Ofte har du som idrettsutøver treningstider på ulike tider av døgnet, noe som gjør at det vil være vanskelig å tilpasse spisevinduet slik at det optimaliseres med tanke på treningen. Det er ikke dermed sagt at periodisk faste er uegnet mot idrett, og for enkeltpersoner kan det nok fungere vel så bra som et mer normalt måltidsmønster.

## Avslutning

Dersom du ønsker å prøve om periodisk faste er noe for deg, så er juletiden en perfekt anledning til å prøve! Denne tiden innebærer for de aller fleste ganske store middager, etterfulgt av kaker og kveldskos. For å unngå at vekten beveger seg for mye oppover i ferien, kan det være lurt å redusere energiinntaket tidlig på dagen for å kompensere.

Du vil nok merke at det er vanskelig å gjennomføre opplegget i begynnelsen, men om du gir det litt tid, så vil du merke at kroppen fort venner seg til det nye spisemønsteret. Dette er enda en grunn til at juleferien er den perfekte tiden å begynne, siden du har fri fra jobb og skole, som derfor ikke vil påvirkes av at du er i en omleggingsfase.

Det er ingenting magisk med periodisk faste fremfor andre spisemønstre, og valg av spisemønster handler hovedsakelig om trivsel og tilpasning til hverdagen. **Det du skal ta med deg fra denne artikkelen er at du står veldig fritt til å velge det spisemønsteret du selv trives best med!**

**Referanser:**

1.  La Bounty PM, Campbell BI, Wilson J, Galvan E, Berardi J, Kleiner SM, Kreider RB, Stout JR, Ziegenfuss T, Spano M et al: **International Society of Sports Nutrition position stand: meal frequency**. J Int Soc Sports Nutr 2011, 8:4.

2.  Cameron JD, Cyr MJ, Doucet E: **Increased meal frequency does not promote greater weight loss in subjects who were prescribed an 8-week equi-energetic energy-restricted diet**. Br J Nutr 2010, 103(8):1098-1101.

3.  Bellisle F, McDevitt R, Prentice AM: **Meal frequency and energy balance.** Br J Nutr 1997, 77 Suppl 1:S57-70.

4.  Holmstrup ME, Owens CM, Fairchild TJ, Kanaley JA: **Effect of meal frequency on glucose and insulin excursions over the course of a day**. Volume 5. e-SPEN; 2010.
