---
title: "Planlegg treningen din"
author: "Torbjørn Lysne"
date: "2012.05.29"
---

Alle som trener har et mål med treningen sin, enten det er å bli sterkere, raskere, spenstigere, mer utholden eller å få et mer atletisk utseende. For å oppnå sitt eget mål er det viktig å vite hva som må til for å klare dette. Jeg vil her fortelle hva som er viktig å tenke på for å oppnå de målene du setter deg!

## Arbeidskravanalyse

Det første som er viktig å vite angående målsettingen er kravene som stilles for å oppnå disse. Uansett hva du ønsker å oppnå er det som oftest flere faktorer som spiller inn. Det kan være lurt å skrive ned en liste over hvilke arbeidskrav som stilles for å kunne oppnå målet. En slik liste kan inneholde fysiske målsettinger som styrke, spenst, hurtighet, utholdenhet og bevegelighet, men også andre egenskaper som teknikk, koordinasjon og lignende spiller en rolle i en slik arbeidskravsanalyse.

For å ta et eksempel: Har du som mål å klare 100kg i rykk er det ikke nødvendigvis styrken som er begrensende for hva du klarer. Det kan være på grunn av en dårlig teknikk, dårlig koordinasjon, nedsatt bevegelighet i skuldre som gjør at man ikke kommer i en god posisjon under løftet osv. Poenget med eksempelet er at det er flere faktorer som er avgjørende for at en målsetting skal være oppnåelig.

## Kapasitetsanalyse

Når du vet hvilke krav som stilles for å oppnå målet sitt, er det neste steget å finne ut hvordan din kapasitet er sammenlignet med arbeidskravene som stilles. Du må vite hvilke faktorer du må forbedre og hva som skal til for å forbedre disse. Sagt på en annen måte; finn ut hva du allerede er god på, og hva som trenger en forbedring.

## Treningsplan

Det er først når du vet arbeidskrav og egen kapasitet du kan sette opp en fullverdig målsetting. Sammen skal disse tre (arbeidskrav, kapasitet og målsetting) danne grunnlaget for treningsplanen din. Treningsplanen må inneholde alle faktorene du har skrevet ned i arbeidskravsanalysen og kapasitetsanalysen. Når du vet hva du trenger for å oppnå målet er det lettere å faktisk få med seg alle faktorene i treningen din! Bildet nedenfor oppsummerer raskt hvordan det hele fungerer.
