---
title: "Myter og sannheter om prolaps"
author: "Torbjørn Lysne"
date: 2014.06.19---
---

I løpet av livet opplever 4 av 5 ryggsmerter i en større eller mindre grad. Noen får akutte smerter som går over etter kort tid, mens andre kan slite med kroniske smerter som varer over lengre tid, gjerne også periodevis. Man vet generelt lite om slike uspesifikke smerter som oppstår, men i denne saken vil jeg fortelle litt om en av de mest kjente synderne til smerter, prolaps – på folkemunne også kalt skiveutglidning.

## Anatomi

For å kunne forstå hva prolaps i ryggen er må du har en forståelse for hvordan ryggsøylen fungerer. De viktigste oppgavene til ryggsøylen er å beskytte ryggmargen og sikre stabilitet i overkroppen.

Ryggsøylen (columna) består av 33 ryggvirvler:

-   7 i nakken (Cervical)
-   12 i brystryggen (Thoracal)
-   5 i korsryggen (Lumbal)
-   5 sammenvokste korsbenvirvler (Sacral)
-   4 sammenvokste halebensvirvler (Os coccygus)

Mellom ryggvirvlene har du mellomvirvelskiver som består av en ringformet fiberbrusk med en bløt kjerne. De fungerer som trykkavlastende støtputer og gir også gode forbindelser mellom hver enkelt ryggvirvel slik at ryggsøylen kan bevege seg mer enn den ellers kunne gjort.

## Hva er prolaps?

En prolaps kan kort forklares med at en sprekk i en mellomvirvelskive, vanligst i Cervicalcolumna og Lumbalcolumna. Denne åpningen fører til at deler av den bløte kjernen presses ut og danner en utposning på utsiden av mellomvirvelskiven. Prolaps skyldes som regel langvarig slitasje på mellomvirvelskivene, men kan også oppstå akutt etter et betydelig traume. Selv om mange kan gjengi akkurat hva som skjedde i det prolapset oppstod, er det ikke nødvendigvis dette i seg selv som var avgjørende for prolaps eller ikke – det er ofte bare en uheldig utløsende årsak.

Ryggsøylen blir utsatt for svært mye belastning gjennom livet, og det er helt naturlig at det oppstår slitasjeforandringer i ryggsøylen. Tunge løft, dårlig sittestilling, muskulære svakheter, lite aktivitet, dårlig holdning og kosthold er eksempler på ting som sammen danner helheten i hva ryggen gjennomgår i løpet av livet. Mye feil (og riktig) belastning kan til slutt føre til at mellomvirvelskivene får nok og et prolaps kan lettere oppstå. Den beste måten å redusere slitasje i ryggsøylen er å holde seg i bevegelse og være obs på de overnevnte punktene.

Gjennom en dag endrer vi stilling veldig ofte. Alle endringene fører til at trykket inni mellomvirvelskivene forandrer seg. Når trykket overstiger skivens tåleevne kan den bløte kjernen presse seg ut og danne en utposning utenfor mellomvirvelskiven. En rygg som har blitt påført mye uheldig belastning over lang tid vil ha større slitasje enn en «frisk» rygg, og dermed øker risikoen for prolaps.

## Prolaps og smerter

I seg selv vil ikke et prolaps nødvendigvis ha en direkte sammenheng med smerter. Veldig mange har faktisk ett eller flere prolaps som de ikke selv vet om fordi de ikke har noen symptomer. Du vil derimot oppleve smerter dersom prolapset trykker mot en nerverot eller ryggmargen. Prolaps i cervicalcolumna vil gi utstrålende smerter ut i armene, mens det i lumbalcolumna gir utstråling til beina. Hvor utstrålingen skjer skyldes hvilke nervefibre som blir påvirket. Smertene kan bli kraftige og være både lokalt og perifert utover langs nervebanene. Plagene avhenger av hvor på nerveroten det er mest trykk.

Over halvparten av den voksne befolkningen har symptomfrie prolapser. Dette skyldes at trykket mot nervefibrene ikke er stort nok til at du opplever det som smerter. Anatomiske forskjeller hos mennesket er med på å avgjøre om prolapset gir smerter eller ikke. En frisk nerve tåler også en god del trykk uten at det gir smertesymptomer. Prolapser med smertesymptomer er vanligst i før fylte 50år. Etter dette vil som regel mellomvirvelskivene ha tørket inn slik at risikoen for nye prolapser er liten.

## Er prolaps farlig?

Som nevnt er prolaps vel så vanlig som det er uvanlig hos det voksne mennesket. Er du en av de som har prolaps uten symptomer vil du nok ikke gjøre noe med det som følge av at du sannsynligvis aldri vil finne ut at du har prolaps.

Hvis du derimot har fått prolaps med smertesymptomer er det viktig å ta dette på alvor. Selve prolapset forsvinner ikke uten et kirurgisk inngrep, men det er absolutt mulig å bli kvitt smertesymptomene med god trening og behandling. Du må gjerne bruke god tid for å bli helt bra igjen, men det er å foretrekke å unngå operasjon fordi det medfører en tynnere og mindre støtdempende mellomvirvelskive samt redusert bevegelighet i det gitte området. Disse faktorene fører ofte til at opererte prolapspasienter etter en tid får større ryggplager enn de som klarer å bli kvitt symptomene uten kirurgi.

## Behandling av prolaps

Smertegivende prolapser behandles som oftest konservativt, og bare en liten prosentandel må opereres. I begynnelsen av akutt periode er det vanlig å avvente situasjonen og se hvordan tilstanden utvikler seg. Man blir anbefalt å være i litt aktivitet og prøve å unngå å bli sengeliggende. Mange starter med smertestillende medikamenter i denne perioden.

Etter den akutte perioden vil smertene normalt avta. Her er det viktig å holde seg i bevegelse og starte opp igjen med fysisk aktivitet. I denne perioden må du unngå belastninger som forverrer smertene samt unngå å stivne i ryggen/nakken. Det har også vist seg at styrketrening av mage-/ og ryggmuskulatur er med på å gjøre tilstanden bedre. Prolapset forsvinner ikke, men økt styrke i området rundt skadet virvel gjør at du vil tåle større belastninger enn ellers. Det vil være lurt å gå til egnet helsepersonell for å sørge for at du trener de riktige øvelsene og treffer riktig muskulatur.

Blir ikke tilstanden bedre i løpet av noen uker kan det være aktuelt å undersøke om skaden bør opereres. De vanligste årsakene til operasjon er vedvarende sterke smerter og/eller økende lammelser i armer/bein. Er du riktig uheldig kan et prolaps føre til at du mister kontroll over vannlating/avføring. Operasjon er da uunngåelig.

## Oppsummering

Å leve med en prolaps er noe halvparten av den voksne befolkningen gjør uten helt uten symptomer. Det er altså fullt mulig å leve som normalt med en eller flere prolapser. Får du en prolaps med smertesymptomer og/eller utstråling/lammelser ut i armer/bein vil du i de fleste tilfeller behandles konservativt, herunder bruk av smertestillende medikamenter og så snart som mulig vende tilbake til all aktivitet som ikke forverrer tilstanden. Videre vil veiledet trening av muskulatur rundt prolapset være til hjelp for å tåle større belastninger i fremtiden. Selve prolapset vil aldri forsvinne, men etter en tid med riktig behandling og trening vil de fleste ikke lenger være plaget av symptomer.
