---
title: "Guide til å mestre pullups"
author: "Martin Norum"
date: 2012.09.13
---

Viktigheten av å benytte baseøvelser i treningsprogrammer kan ikke understrekes nok. I en perfekt verden der skader ikke er noe problem og tekniske ferdigheter er på plass vil effekten av markløft alltid være større enn rygghev, og knebøy vil alltid være bedre enn benpress. Alle øvelser har sin plass og kan benyttes for variasjon, men du henger sikkert med på poenget. Pullups kan ses på som overkroppens knebøy. I denne artikkel skal jeg se på hvordan du kan jobbe progressivt mot pullup-suksess! Guiden fungerer også like bra for chins(supinert grep)

Det mest vanlige alternativet til pullups er nedtrekk. Den finnes i maskin, med kabel og med benstøtte som dytter deg oppover. Med alle de nye fancy apparatene som finnes idag er det nesten ingen som gjør de gode gamle(og mest effektive) øvelsene lenger. At apparatene ser flotte ut gjør dem ikke effektive og nyttige når resultater skal fremdrives så fort som mulig. Jeg er ikke motstander av vanlige nedtrekk, det er bare at de gir deg mindre tilbake for strevet du legger ned i trening (så fremt du klarer å utføre pullups), på samme måte som triceps-press med kabel gir deg mindre tilbake sammenlignet med benkpress med smalt grep eller dips. Velg pullups fremfor nedtrekk av følgende årsaker.

1.  Effekten av øvelsen er langt større – å løfte sin egen vekt opp over stanga gir bedre stimulering av muskelfibrene enn å løfte den samme vekten ned mot kroppen.

2.  Øvelsen er mentalt tøffere – Bruk alle anledninger til å gjøre treningen så tøff som mulig så lenge teknikken tillater det. Mental tøffhet må ikke undervurderes

3.  Øvelsen er utfordrende og morsommere å gjennomføre enn nedtrekk

Før vi ser på effektive progresjoner mot pullups – ikke glem at du må gjøre andre øvelser enn bare pullups (som utføres i det vertikale planet) for å bli virkelig sterk. Med andre ord er det viktig å ha med støtteøvelser som kan underbygge progresjon der du ønsker fremgang. For ryggen er følgende øvelser smart å ha i programmet mot ditt mål om bedre pullup-styrke.

-   Markløft - se mer om urførelse i [denne artikkelen](markloft.qmd "Startposisjon og utførelse av markløft").
-   Foroverlent roing med stang
-   En-arms roing over benk
-   Baseøvelser for biceps

## Det er på tide å lære pullups!

La oss starte med å avklare en ting. Pullups = overhåndsgep. Chins = underhåndsgrep. Vær klar over at øvelsene er vidt forskjellige og stiller ulike krav til muskelaktivitet og tekniske punkter. Progresjonene vist under kan brukes for begge øvelser.

**1. Retraksjon av scapula(skulderbladet) fra heng.\
**Det første vi må gjøre er å styrke musklene som trekker skulderbladene sammen. Heng med strak kropp fra stangen og trekk skulderbladene mot hverandre før du slipper tilbake. Når du får til 3 set X 10 rep er du klar til steg to. En del personer sliter med denne bevegelsen grunnet dårlig kontroll av hvordan skulderbladene beveger seg. [Video](http://www.youtube.com/watch?v=ndrEJSdScyY)\

**2. Pullups med strikk.**\
Ved hjelp av en strikk klarer de fleste å få til noen repetisjoner. Strikket hjelper mest i bunnposisjonen fordi den strammer seg, men gir etter på vei opp. Etter mitt syn er bruk av strikk et bedre alternativ enn pullup-maskinen som gir benstøtte. Med strikk kontrollerer du bevegelsen selv og får følelsen av hvordan en ordentlig pullup skal kjennes på kroppen. Ved vanlige pullups og chins må du faktisk rotere kroppen rundt stangen, og dette krever mye mer innsats og bruk av flere muskler. Med benstøtte er bevegelsesbanen låst og effekten er dårligere. I tilfeller der stor overvekt er et problem, og strikker ikke er tilstrekkelig hjelp kan likevel pullups med benstøtte være et fint alternativ.

Gjør slik: bygg deg opp til å klare ca 8 repetisjoner med en fast strikk du bruker hver gang du trener øvelsen. Når du klarer 8 stykker legger du på vekt. Mange synes det er rart å legge på ekstra vekt i et belte når man bruker strikker for å gjøre øvelsen lettere. Det kan kanskje se rart ut, men for å bli bedre må belastningen økes. Start med 2,5 kg ektra vekt i beltet og økt 2-5 kg hver gang avhengig av hvor tungt det er. Jobb progressivt fremover til du har 10-15 kg hengende i beltet og klarer 1-3 repetisjoner. Når du får til dette er du klar for neste punkt. [Video](http://www.youtube.com/watch?v=v4f5T8cPbHA)

**3. Isometriske hold**

Når du mestrer tunge repetisjoner med strikk er det på tide å gå løs på øvelsen uten ekstra utstyr. Neste progresjon går ut på å holde en statisk/isometrisk posisjon i et gitt antall sekunder.

Det er tre forskjellige punkter du bør holde fokus på:

-   Toppen av øvelsen(haken over stangen)
-   Midten av øvelsen(ca 90 graders vinkel i albueleddet)
-   Nederste del av øvelsen(ikke strekk fullstendig ut, men hold en liten knekk i albuen)

Klem skulderbladene hardt sammen og hold kroppen helt stødig og kontrollert i 5-8 sekunder i hver posisjon. [Video](http://www.youtube.com/watch?v=DDs1OVfD8CM)

**4. Eksentrisk trening**

For å øke pullups-styrken bør belastningstiden følges bevisst. Etter de forrige progresjonene er fortsatt noen ikke sterke nok til å trekke sin egen kroppsvekt opp med haken over stangen. Har du imidlertid klart progresjonene så langt, er du garantert sterk nok til å trene på den eksentriske fasen. Fasen på vei ned. Du er sterkere på vei ned enn på vei opp, noe som betyr at dette er veien å gå når styrken skal utvikles raskt.

Gjør slik: start med haken over stangen og hold igjen ALT du makter og har. På sikt bør du klare å holde igjen i 20 sekunder på vei ned. Det er samme tempo som i klippet under. Sikt på 3 serier med 2 repetisjoner. [Video](http://www.youtube.com/watch?v=xFe5bNZg-u4)

## Din første pullup!

\[youtube=http://www.youtube.com/watch?v=Cp4Wdq8EQ78\]\
Hvis du ikke allerede har klart en pullup vil du være i stand til det nå. Når du først har fått til en er veien videre temmelig enkel. For å fortsette å øke er det mange ting som kan gjøres, men en enkel måte å få til 2,3, 4 og fler er å trene mye på øvelsen. Øk volumet og prøv å få til f.eks 10 stykker i samme treningsøkt. Gjør øvelsen når som helst – mellom serier med andre øvelser eller som enkeltøvelse. Når du begynner å få til fler repetisjoner etter hverandre kan du begynne å trene et høyt antall serier(4-8) med få repetisjoner(2-4). Legg gjerne på ekstra vektbelastning i et vektbelte mellom bena slik videoen under illustrerer. Øk alltid belastningen fra økt til økt – enten i form av tyngre vekter eller flere repetisjoner.

\[youtube=http://www.youtube.com/watch?v=tjydy5HD-eE\]

Tunge singler er en effektiv måte å komme videre på. Forvent gode resultater når det gjelder styrke og muskelmasse i hele overkroppen.
