---
title: "Refluks og funksjonell dyspepsi"
author: "Ingvild Thun"
date: 2013.02.11
---

Refluks og funksjonell dyspepsi er tilstander som rammer de øvre delene av fordøyelsessystemet. Disse kan være svært plagsomme, men heldigvis er det en del ting man kan gjøre for å lindre plagene. I denne artikkelen vil jeg forklare hva som forårsaker disse tingene, og gi deg noen tips til hva du kan gjøre dersom dette skulle ramme deg!

## Refluks

Det er sent en lørdagskveld; du sitter i sofaen med den øverste bukseknappen oppkneppet og tenker "knallgod middag, men det ble minst en porsjon for mye..". Du kjenner et ubehagelig trykk øverst i magen, omtrent som at maten er på tur opp igjen og du opplever sure oppstøt, brystbrann og gulping i tiden etter det store måltidet.

**Refluks** er noe de fleste opplever en gang i blant, spesielt hvis man har konsumert store mengder mat eller drikke. Omtrent 10-15 % av voksne har symptomer som brystbrann og oppstøt daglig, men fåtallet oppsøker lege. Noen velger rett og slett å leve med det, mens andre bare er plaget en gang i blant, i tillegg finnes det syrenøytraliserende medisiner på apotek. Refluks, eller **gastroøsofageal refluks** **(GØR),** forekommer spesielt hyppig hos spedbarn og gravide, noe som oftest har en naturlig forklaring og vil gå over. Refluks forekommer hyppigere jo eldre man blir, og en typisk karakteristikk er en overvektig mann i førtiårene med en sedat livsstil.

Refluks betegnes som «ufrivillig tilbakestrømming av ventrikkelinnhold til øsofagus», altså surt mageinnhold som strømmer feil vei, derav navnet «surt oppstøt». Refluks er egentlig ikke en diagnose, men kan forårsakes av ulike typer sykdom. Det er altså mest av alt et symptom.

GØR må ikke forveksles med **gastroøsofageal reflukssykdom (GØRD)**, som er en mer alvorlig form for GØR. Refluks hos små barn er som nevnt vanlig og vil ofte gå over innen første leveår, men vedvarer refluksen kan det være GØRD. Er man mye plaget med reflukssymptomer over lengre tid, bør man oppsøke lege for å utelukke organisk sykdom og sjekke om man har GØRD.

### Årsaker

Mellom spiserøret og magesekken har vi en muskel som kalles **nedre lukkemuskel**. Den åpner seg for å tillate mat å komme ned i magesekken og den lukker seg for å forhindre at mat og magesyre flyter tilbake og opp i spiserøret igjen. **Høyt trykk** i magesekken, som ved graviditet eller store måltider, samt en **dårlig fungerende** lukkemuskel, ofte hos barn, vil ofte føre til surt mageinnhold i spiserøret og forårsake symptomer på reflukssykdom. Når det sure mageinnholdet kommer opp i spiserøret blir det møtt av bikarbonat, som er basisk, og noe av magesyren blir dermed **nøytralisert**. Det er ikke uvanlig at noe mageinnhold strømmer tilbake, men normalt sett er det tilstrekkelig bikarbonat til å nøytralisere dette. Problemet oppstår dersom mengden refluks blir så stor at det overgår bikarbonatets evne til nøytralisering. Det er ikke bare syren som skaper problemer, men også fordøyelsesenzymet pepsin som hjelper å spalte proteiner til aminosyrer. Pepsin vil trenge inn i slimhinnene, og når det treffer nerveendene vil vi oppleve en **brennende følelse** i halsen.

### Behandling

For å diagnostisere GØRD foretas det **pH-måling i spiserøret**, som regnes som gullstandard da de fleste har normal gastroskopi. Man får utdelt et apparat som måler pH-en i spiserøret gjennom ett døgn, i tillegg til at personen trykker på en knapp hver gang han kjenner symptomer. Dette kan så i ettertid avleses, og ofte ser man en synkende pH og signal om at personen har trykket etter et måltid. Det finnes ingen kur mot refluks, men det finnes ulike metoder man kan prøve. For personer med GØR kan **kost- og livsstilsråd** som vekttap, måltidsrytme og matvaretips være tilstrekkelig. For personer med GØRD er det ofte nødvendig med nøytraliserende midler, antisekretoriske midler (protonpumpehemmere) eller kirurgi hos de tyngst rammede, i tillegg til livsstilsintervensjon.

Enkelte matvarer kan **forsinke tømming fra magesekken**, og dermed gjøre at maten blir liggende lenge i magesekken og skape ubehag og symptomer. Mat som forsinker tømming fra magesekken og ned i tarmene er ofte store og/eller fettholdige måltider. Dette kan også **senke trykket i den nedre lukkemuskelen**, noe som gjør at denne muskelen lettere åpner seg og tillater mat å komme opp i spiserøret. Andre matvarer som lettere tillater dette er blant annet løk, tomat- og tomatprodukter, sjokolade og peppermynte. Er man sår i spiserøret etter hyppig refluks kan naturlig nok syrlig mat og drikke som juice, samt sterkt krydret og røkt mat forverre dette og irritere slimhinnene. Mat kan også stimulere til økt syreproduksjonen i magesekken, dette sees blant annet med proteinrik mat, samt sterke krydder som chili og pepper.

### Generelle kostråd

-   Unngå store måltider – små og hyppige måltider kan være bedre
-   Unngå veldig fettrike måltider
-   Unngå for sene måltider – la det gå ca.to timer før du legger deg (mageinnholdet strømmer lettere tilbake i liggende posisjon)
-   Vær forsiktig med (store mengder) brus, juice, hvitvin, sjokolade, løk, tomat, sterke kryddere samt peppermynte i flytende form
-   Ved sårt spiserør tolereres oftest mild, myk og fuktig mat best
-   Kald mat tåles ofte bedre, for eksempel brødmat
-   Melk kan dempe plagene hos enkelte
-   Unngå liggende stilling etter et måltid
-   Unngå høy aktivitet etter måltider
-   Er du overvektig, kan det hjelpe å redusere vekten og dermed trykket på magesekk/spiserør

## Funksjonell dyspepsi

Det er sent en lørdagskveld; du sitter i sofaen med den øverste bukseknappen oppkneppet og tenker "Jeg skulle gjerne spist mye mer av dette, men det er stappfullt..". Du kjenner et ubehagelig trykk øverst i magen, er oppblåst, stinn og litt kvalm, selv om du ikke spiste spesielt mye. Dette kan ha oppstått i perioder eller hyppigere, ofte tilknyttet måltider. Hva i all verden er dette?

Det finnes over 20 identifiserte funksjonelle magetarmlidelser, og de kan oppstå overalt i fordøyelseskanalen, fra munn til endetarm. Tidligere er det blitt skrevet en artikkel om [**irritabel tarm**](irritabel-tarm.qmd), en tilstand som karakteriseres av mageknip, oppblåsthet og forstyrrelse i avføringen uten at man helt finner årsaken til problemene. Irritabel tarm kjennetegnes ved smerte **under navlen**/øverst i buken, og er tilknyttet tynn- og tykktarmen. Har man **smerter fra navlen og oppover** uten åpenbare årsaker er det snakk om øvre del av fordøyelseskanalen (magesekk, spiserør og muligens tolvfingertarmen). Dette kalles **funksjonell dyspepsi**.

Veldig ofte ser man overlapp mellom funksjonelle mage- og tarmlidelser. Ordet *funksjonell* kommer av at man opplever symptomer, men ikke finner noe anatomisk feil. *Dyspepsi* er gresk for «forstyrret fordøyelse», men dette er ikke tilfellet. Slike funksjonelle diagnoser blir stilt først når man har fullstendig utelukket alvorlig, organisk sykdom!

### Årsaker

Over **20 % av voksne** har opplevd dyspepsi, og det står for **2-3 % av konsultasjoner** hos fastlege. Som antydet tidligere, vet man ikke årsaken til disse smertefulle symptomene, siden man ikke kan finne noe unormalt ved gastroskopisk undersøkelse av magesekken.  Man spekulerer i om plagene skyldes kan skyldes motilitetsforstyrrelser, sensitivitetsforstyrrelser og/eller hjerne-tarm-dysfunksjon:

1.  Motilitetsforstyrrelse betyr en forstyrrelse i den muskulære aktivteten til fordøyelseskanalen. Unormale spasmer, for mye eller for lite kontraksjoner kan føre til smerter og ubehag

2.  Med sensitivitetsforstyrrelser mener man unormalt høy følsomhet i nervene i fordøyelsekanalen som responderer på stimuli (feks etter måltid)

3.  Forstyrrelser i signaloverføringen i «gut-brain-axis», altså kommunikasjonen mellom mage/tarmkanalen og hjernen

Før trodde man funksjonelle magetarmlidelser hadde psykiske årsaker, og at symptomene kom i kjølevannet av angst, depresjon og stress. I dag vet man at dette ikke er tilfellet, men heller at magetarmlidelsen har innvirkning på livskvalitet og dermed på den psykiske helsen.

### Diagnose

Funksjonell dyspepsi innebærer at ett eller flere kriterier må være oppfylt **over en dag per uke**:

-   Plagsom oppfylthet etter måltid
-   Tidlig metthet
-   Epigastriesmerter – smerter øverst i magen i vinkelen mellom ribbensbuene
-   Følelse av «brenning» i epigastriet

For å diagnostisere funksjonell dyspepsi må man begynne i den andre enden; nemlig **utelukke organisk sykdom**, det vil si anatomiske feil som et resultat av alvorlig sykdom. Vanligvis innebærer dette en rekke undersøkelser fra ultralyd, gastroskopi, CT, røntgen etc, men da uten særlig funn.

### Behandling

Behandlingsfronten er preget av at man ikke vet årsaken, og dermed blir det, som ved IBS, kun snakk om symptomlindring. Man kan ha ulike typer, hyppighet og smertegrad av symptomer, og det er dette man må utnytte ved symptomlindring. Ulike medikamenter og kostråd kan være verdt et forsøk. Av medikamenter kan man blant annet prøve midler mot kvalme hvis man er kvalm, mot refluks hvis man plages med det, eller midler for å bedre magesekktømmingen.

### Generelle kostråd

-   Små, hyppige måltider – 5-7 om dagen
-   Forsiktig reduksjon av fett – ikke spis *mindre* enn du tåler da dette er en viktig energikilde hvis man har problemer med å få i seg nok energi!
-   Unngå mat man tidligere har erfart skaper problemer

Vi er alle ulike, og noen tåler enkelte matvarer bedre enn andre, og omvendt. Hvis du av erfaring vet at en matvare gir deg symptomer, kan denne utelates, men ikke eliminer matvarer i så stor grad at det går ut over energiinntak: erstatt det du tar vekk. **Prøv deg fram!** Opplever du mage- eller refluksplager som vedvarer over tid, gå alltid til legen for undersøkelse for å utelukke sykdom.

**Har du erfaringer med denne typen plager? Del dine erfaringer og hva som har fungert for deg i kommentarfeltet!**

Referanser:

-   Thomas B, Bishop J: **Manual of Dietetic Practice**: Blackwell Publishing; 2007.
-   Forelesninger
