---
title: "Dette gjør du riktig på gymmet!"
author: "Asle Bøe"
date: 2013.05.13
---

I trening og kostholdsverden er det lett for å bli elitistisk og sær. Alle skal ville bli råsterk i baseløftene og se ut som guder og gudinner. Rumper og andre kroppsdeler skal nå gulvet i knebøy, ellers kan en like gjerne gå hjem. For de som vil trene og har konkrete mål med treningen sin er det fornuftig å etterstrebe så effektiv og trygg trening som mulig. Likevel blir det fort eksluderende – for de som står på utsiden og ser inn i jungelen av treningsinformasjon og har vært et par ganger på gymmet er det ikke lett å orientere seg.

Du har gjerne hodet fullt av ting det går an å gjøre feil -men fatt mot! Bare at du er der er noe. Har du i det hele tatt kommet deg på trening gjør du noe riktig!

Artikkelen er originalt publisert hos [MyRevolution](http://myrevolution.no/s/dette-gjor-du-riktig-pa-gymmet/)

## Du er der!

Istedenfor å sitte hjemme og vegetere foran tven eller pcen står du forhåpentligvis på dine to ben og gjør noe den tiden du er der. Sitting er en tilpasning vi har gjort for å spare energi. Det er en stilling som har blitt en hybrid mellom aktivitet og hvile. Vi sitter og spiser, sitter og ser på TV, sitter foran PCen, sitter og jobber, sitter på skolen, sitter i bilen og kjører til butikken eller gymmet.

All tid av stumpen er gull verdt for bena og helsen for oss som sitter for mye. Hverdagsaktivitet er sterkt undervurdert i forhold til trening, men har du først kommet deg på gymmet er sjansene store for at du ihvertfall gjør noe som innebærer muskulært arbeid over det å like og dele bilder av katter på facebook.

## Du er fysisk aktiv

I vårt behagelige, moderne samfunn kan vi omtrent unngå muskulært arbeid og holde energiforbruket svært lavt.

Omgivelsene ligger til rette for å bevege seg så lite som mulig og energi i form av mat er lett tilgjengelig hele tiden. Derfor har mange av oss kommer i den artige situasjonen at vi må bevisst gå inn for å øke aktiviteten. Dersom trening er et ork og du ikke liker det du driver med – slutt! All aktivitet monner. Gå en tur med venner istedenfor, klarne tankene i lunchen på jobb ved å ta ti minutter ute men velg konsekvent noe du liker eller kan komme til å like. Stillesitting og inaktivitet har vært kalt den nye folkesykdommen, og heldigvis er medisinen enkel: Bevegelse!

I alt snakket om det optimale er det lett å glemme hva som er godt nok , og alt er bedre enn ingenting. Det er først når en har konkrete mål en kan sammenligne den ene treningsformen mot den andre og veie for og mot hva som vil føre en til målet på en mest hensiktsmessig måte og gi best resultater.

## Du gjør noe du liker

Om det er crossfit, zumba, ren styrketrening, 3-splitt, 5-splitt, du kun trener kondisjon – finn den aktivitetsformen som passer best til dine mål og som du trives best med.

Vær åpen for at det finnes andre metoder som er vel så gode som dine eller de du har lest om, og at andre trener av helt andre grunner enn det du gjør. Fokuser på å gjøre noe du liker og synes er motiverende når du trener.

**Les også: [Underholdningsslavens Redning](underholdningsslavens-redning.qmd "Underholdningsslavens redning")**

Har du kommet deg på trening eller tatt steget opp fra stolen eller sofaen? Flott! Du er på vei til å gjøre noe som er bra for helsen, humøret og formen. Du behøver på ingen måte ta turen til gymmet heller – gjør det du kan der du er. En runde med egenmassasje, litt kroppsvektøvelser, en tur i lunchen. Bevegelsesapparatet er der, mulighetene er der – bruk det og bruk dem!

##### Senker du listen er det lett for du hopper flere ganger!
