---
title: "Seminar om irritabel tarm"
author: "Norene Grytten Kjøsnes"
date: 2014.12.15
---

Den 11.oktober arrangerte [Landsforeningen mot fordøyelsessykdommer ](http://www.lmfnorge.no/)(LMF)det første [nasjonale seminaret om Irritabel tarm syndrom (IBS)](http://www.lmfnorge.no/component/k2/item/392-hvaeribs).Per i dag betegnes IBS som en funksjonell tarmlidelse, det vil si at man finner ingen organisk årsak bak symptomene. Vanlige symptomer ved IBS er smerter/ubehag, oppblåsthet, luft i magen, diare og forstoppelse. Viktige problemstillinger stod på agendaen. Skyldes IBS psykiske problemer? Forverres IBS av vanlige matvarer?

Første foredrag handlet om diagnostikk ved IBS, mens foredrag nummer to handlet om behandling. Begge disse ble holdt av professor emeritus Arnold Berstad som har jobbet med og forsket på mage og tarm i over 30 år. Det siste foredraget var om FODMAP og kost for IBS pasienter. Dette ble holdt av klinisk ernæringsfysiolog Gry Skodje som for tiden i hovedsak jobber med ulike gastro-relaterte diagnoser. Denne artikkelen er en oppsummering av innholdet på seminaret. Seminaret ble også filmet, og er tilgjengelig på hjemmesiden til LMF.

Generalsekretær for LMF, Arne Schatten, ønsket velkommen. Schatten påpekte at IBS er en vanlig tilstand som rammer rundt 10% av befolkningen, men at mage-og tarmproblematikk ofte er et tabubelagt tema. IBS er et stort problem både for de mange enkeltpersoner som rammes, men også samfunnet i sin helhet.

## Diagnostikk ved IBS

[Opptak](https://www.youtube.com/watch?v=NBpRsB7VY2c)

Berstad åpnet med å gratulere med at man har fått til et IBS seminar. Han sier at IBS er et kjempestort helse-problem som myndighetene ikke skjønner omfanget av. Berstad tror at opp mot 1 million nordmenn kan lide av IBS, og at 20-30 prosent av den norske befolkningen er gluten-sensitive. Flere ganger nevner han at behovet for en pasientforening er stort.

Berstad synes at Roma III-kriteriene som brukes ved diagnostisering av IBS er vanskelige å bruke. Videre erfarer han at ufullstendig tømming er noe som ofte ikke blir nevnt. Dermed kan dette viktige symptomet falle utenfor når det dannes et bilde av IBS-pasientens symptomer.

Berstad har over en tid systematisk registrert symptomer hos 84 av sine IBS-pasienter. Funnene har han publisert i artikkelen ´Functional bowel symptoms, fibromyalgia and fatigue: a food induced triad?´. Noen observerte karakteristikker hos IBS-pasienter er at de fleste er kvinner, gjennomsnittsalderen er 37 år, kroppsmasseindeksen grenser til høy, leddsmerter er vanlig, og IBS pasienter har ofte ME.

Berstad beskriver det slik at IBS pasienter har en lammelse i tarmen. Han viser til egen forskning som viser at IBS pasienter som gis laktulose vil ha en mye større akkumulasjon av væske i tynntarmen sammenlignet med friske kontroller. Les mer om studien [her](http://forskning.no/mat-og-helse-menneskekroppen-sykdommer/2014/10/forste-synlige-bevis-irritabel-tarm).

Årsaken til denne lammelsen vet man ikke, sier Berstad. Her må det forskes mer. Foreløpig er det kun Berstad med sin forskningsgruppe som har sett på disse sammenhengene. Berstad la frem egen forskning som foreslår serotonin-mangel som årsak til mange av problemene man ser hos IBS-pasienter. Normalt sett finnes 95 % av serotoninet i kroppen i tarmen der det er viktig for tarm-peristaltikken, mens 5 % finnes i hjernen og er viktig for minne/konsentrasjonsevne og sinnsstemning. Det ble presentert mye komplisert biokjemi rundt sammenhengen mellom tryptofan, serotonin og IBS-problematikken; tryptofan er en essensiell aminosyre som er nødvendig for å lage serotonin, og ifølge Berstad har IBS- pasienter en økt nedbrytning av tryptofan. Derfor har IBS-pasienter en trolig serotonin-mangel. Resultatet av kraftig nedbrytning av tryptofan har mange ulike konsekvenser. Man kan kjenne seg overfølsom, tåkete, glemsk, opplever dårlig søvn og man kan få søt-hunger. Oksidativt stress bidrar til fibromyalgi. Auto-immunitet bidrar til ME . Videre får man en svekket motorikk i tarmen, med andre ord en lammelse. Dette kan man lese mer om i artikkelen ´Tryptophan: ´essential´for the pathogenesis of irritable bowel syndrome?´.

Mange IBS pasienter har opplevd at IBS klassifiserer som en psykosomatisk tilstand, og mange diagnostiseres med irrasjonell angst, depresjon og nevrotisisme. Berstad mener at dette er sekundære problemer, som vil forsvinne når man bare får bukt med mageplagene. Han nevner at før man fant at helikobacter-bakterier forårsaket magesår, så var også magesår klassifisert som en psykosmatisk tilstand.

Til nå har man sett at IBS helt klart kan forårsakes av gastroenteritt, noe som ble klart etter Giardia-utbruddet i Bergen i 2004. Berstad nevner også at for mange IBS-pasienter begynner problemene etter en antibiotika-behandling. Berstad tror at IBS er et mikro-økologisk problem, der den naturlige bakteriefloraen er forstyrret. Han tror det primære bak IBS er bakterier, muligens stafylokokker.

## Behandling av IBS

[Opptak](https://www.youtube.com/watch?v=ISHc6O4e5cs)

Berstad erfarer at det er utfordrende å tilby IBS-pasienter tilstrekkelig service. Dette skyldes i stor grad at årsaken(e) bak plagene ved IBS ennå ikke er anerkjent, og dette gjelder også teoriene til Berstad. Mange etterlyser medisiner, men man har foreløpig ikke mye å tilby. Berstad tror at IBS kan kobles til den ”moderne livstil”.

Berstad setter spørsmålstegn ved om at frukt er sunt. Han mener at fruktose gir plager ettersom det ender opp langt ned i tarmen og blir mat til bakterier. Han poengterer at kliniske ernæringsfysiologer har vondt for å gå bort fra ´5 om dagen´.

Berstad mener at gluten er et problem fordi det er et protein som ikke kan absorberes, og derfor blir mat for bakterier. Følgelig er det uheldig at gluten-innholdet i hvetemel økes for å få luftigere brød. Det understrekes at IBS pasienter ikke er allergiske mot gluten eller fruktose. For eksempel vil vanlig havregryn være greit å spise. Man tåler opp til en viss mengde gluten og fruktose, da dette er dose-avhengig. Berstad uttrykker at moderne bearbeiding av mat er ugunstig, og mener at tradisjonelt kosthold/´gammaldags mat´ er gunstig for IBS-pasienter. Berstad påpeker at han erfarer at de fleste IBS pasienter for eksempel kan spise spekeskinke.

Berstad mener at fett-holdige matvarer gir minst problemer for IBS-pasienter fordi fett og protein blir absorbert relativt raskt, og ender derfor ikke opp i tykktarmen ufordøyd, slik som fruktose og gluten gjør. Videre observerer Berstad at mange IBS-pasienter ekskluderer melkeprodukter. Han nevnte at kasein kan ha uheldige effekter, mens glutamin kan ha både gunstig og ugunstige effekter. Lactoalbumin (myse) inneholder mye tryptofan, noe Berstad mener er positivt. Lactoferrin er også trolig gunstig fordi det binder jern som er essensielt for bakterier sin funksjon. Melke-produkter har altså veldig mange positive effekter. Derfor synes Berstad at det er uheldig å utelukke melk fra kostholdet.

Berstad snakket videre om ulike uheldige, men vanlige, behandlinger ved uforklart matoverfølsomhet. Han sier at melkesyrebakterier produserer store mengder syre noe som er essensielt for tarmfloraen. Han mener derfor at det er uheldig at mange skyr ´sur kost´. Han mener at syredempende medisiner har en uheldig effekt på tarmfloraen.

Videre påpeker Berstad at man bør være mer restriktive ved bruk av antibiotika. Dette fordi man kan utvikle resistens som kan få langvarige konsekvenser. Han mener også at bruk av probiotika er ugunstig fordi probiotika produserer bakteriosiner som forstyrrer den naturlige symbiosen av bakterier i tarmen. Når man slutter å ta probiotika står man gjerne dårligere stilt enn før, mener Berstad. Når det gjelder bruk av anti-depressiva, så erfarer Berstad at IBS-pasienter tåler dette dårlig.

IBS-pasienter gjennomgår ofte veldig mange og ulike undersøkelser, og Berstad sier at dette ofte ikke er nødvendig. Han understreker at det kan gå dager fra man har spist til man får en reaksjon, og at dette gjør detektiv-arbeidet veldig komplisert og ofte misvisende. Videre sier han at statistisk sett har IBS pasienter mindre sjanse for å for eksempel utvikle tarm-kreft sammenlignet med normalbefolkningen.

Berstad sin behandling av IBS har i essens vært å sette pasientene på karbohydrat-fattig kost, i tillegg til å unngå gluten og bearbeidet mat. Nå har vi kunnskaper om FODMAP dietten, og den er å foretrekke. Berstad råder pasientene til å innhente mest mulig informasjon om dietten, og helst den informasjonen som kommer fra Monash Universitet i Australia.

## **FODMAP og kost ved IBS**

[Opptak](https://www.youtube.com/watch?v=NDzN3YH41iA)

**FODM**A**P** står for **F**ermenterbare **O**ligosakkarider **D**isakkarider **M**onosakkarider og (And) **P**olyoler. Oligosakkaridene er de kort-kjedete karbohydratene som består av 2-3 sukkermolekyler i kjeder. Disakkaridene er de 2-kjedete sukker-molekylene. Monosakkaridene er de enkle sukkerartene. Polyolene er sukker-alkoholer som har flere enn 10 sukkermolekyler. Det at FODMAPs er fermenterbare betyr at de brytes ned anaerobt i tarmen.

[Les mer om lav-FODMAP-dietten her](irritabel-tarm.qmd "Irritabel tarm og hva du kan gjøre med det!")

Skodje startet med å fortelle om historien til FODMAP. Man så tidlig sammenhenger mellom mat og livskvalitet, og man begynte å mistenkte ulike matvarer. For eksempel observerte man på 80-tallet at eplejuice kunne være årsak til diare. Man så også at ved funksjonelle tarmlidelser så kunne inntak av fruktose, sorbitol og fruktose bli problematisk. Nå vet vi mer om hvorfor man observerte dette, og man har klassifisert de ulike FODMAPer.

FODMAP-konseptet startet i Australia. Sue Shepard er klinisk ernæringsfysiolog tilknyttet Monash Universitetet i Melbourne. Sue begynte å se sammenhenger mellom grupper matvarer og ulike problemer hos pasienter med funksjonelle tarmlidelser. Dermed ble det iverksatt systematisk forskning tidlig på 2000-tallet. Etter hvert identifiserte/kategoriserte de ulike matvaregrupper som nå kalles FODMAP.

Sue har siden jobbe systematisk videre med FODMAP-konseptet. Hun har blant annet gitt ut oppskriftsbøker. Monash Universitet jobber produktivt med å spre informasjon fortløpende. Heftet ”The Monash University low fodmap diet” kan bestilles. De har også utviklet ”The Monash University low fodmap diet ap”. Foreløpig er det bare i Australia de analyserer matvarer for de ulike FODMAPer, så det er deres database vi bruker. Derfor er matvare-listene ikke komplette på noe vis, men det analyseres jevnlig nye matvarer. De tar også imot matvarer fra andre land for analyse. Så etter hvert vil appen inneholde et filter slik at man kan velge matvare utfra landet man er i.

Skodje påpekte at det nå foreligger mye god litteratur i vitenskapelige medisinske tidsskrifter om FODMAP. Det har kommet mye publikasjoner fra den australske gruppen, blant annet står de bak en av de få studiene som tydelig viser at symptombelastningen hos IBS-pasienter blir signifikant redusert ved FODMAP diett sammenlignet med standard diett. Denne studien kan man lese om i publikasjonen ”[A diet low in FODMAPs reduces symptomps of irritable bowel syndrome](http://www.gastrojournal.org/article/S0016-5085%2813%2901407-8/abstract)”.

I en annen studie fra Australia ønsket man å observere gass-produksjon hos IBS-pasienter og friske kontroller etter FODMAP-belastning. De fant via pusteprøver at friske kontroller hadde lavere produksjon av metan og hydrogen sammenlignet med IBS-pasientene. Så her så man en tydelig forskjell på hvordan IBS-pasienter og friske kontroller responderer på FODMAP. Dette kan man lese om i publikasjonen ”[Manipulation of dietary short chain cho alters the pattern of gas production and genesis of symptoms in irritable bowel syndrome](http://www.ncbi.nlm.nih.gov/pubmed/20659225)”.

Det blir også publisert bekreftende studier blant annet fra Kings College i London. De står blant annet bak en studie der man sammenlignet effekten av FODMAP-dietten versus de vanlig standard NICE retningslinjene. Totalt sett så fant de at FODMAP-rådgivning var mest effektivt på IBS-symptomer. Les mer om dette i publikasjonen ”[Comparison of symptom response following advice for a diet low in fermentable carbohudrates versus standard dietary advice in patients with irritable bowel syndrome](http://www.ncbi.nlm.nih.gov/pubmed/21615553)”.

Skodje forklarer videre hvorfor FODMAPer kan være problematiske. FODMAP er små osmotisk aktive molekyler som trekker væske inn i tarmlumen, og som dermed kan endre motiliteten i tarmen. Man kan få både raskere og saktere tarmpassasje. FODMAP er tungt fordøyelige i tynntarmen, og derfor passerer de delvis ufordøyd til tykktarmen hvor de fermenteres av bakterier. Denne fermenteringsprosessen produserer gasser som kan føre til en utvidelse av tarmlumen.

Det er viktig å merke seg at FODMAP også er tungt fordøyelige for personer uten IBS. Malabsorpsjon er med andre ord dels fysiologisk naturlig. Den individuelle toleransegrensen for totalmengden med FODMAP er veldig variabel. IBS-pasienter regnes som mer sensitive sammenlignet med normalbefolkningen.

Skodje snakket om de ulike fodmap-gruppene. Hun snakket oss igjennom lister over matvarer med høyt innhold av FODMAP og lavt innhold av FODMAP. Monosakkaridene er i hovedsak fruktose, som er naturlig forekommende i frukt. Oligosakkaridene er i hovedsak fruktaner og galakto-oligosakkarider og disse finner vi i ulike kornsorter, nøtter, belgnøtter og linser. Disakkaridene er laktose, som vi finner i melkeprodukt. Polyolene relateres først og fremst til kunstig søtning, men de finnes også naturlig i frukt.

Skodje gikk mer spesifikt inn på hvorfor fruktose, fruktaner, galaktaner, polyoler og laktose kan være problematiske. Fruktose har lav transportkapasitet over tarmveggen. Derfor vil høye doser fruktose skape problemer selv om man ikke har IBS. Fruktose blir ikke nødvendigvis et problem hvis man ikke har en malabsorpsjon. Glukose og fruktose konkurrerer om samme opptaks-mekanisme, og derfor vil fruktose bli et problem hvis det er mye fruktose i forhold til glukose. I disse tilfellene vil fruktose-transporten være dårlig og man får et overskudd i tarmen, og den blir mal-absorbert. Da kan man få problemer. For å redusere sjansen for problemer, bør man velge de fruktene som har minst 50% innhold av andre sukkertyper enn fruktose. De fruktene som har rundt regnet lik balanse mellom fruktose og for eksempel glukose, tolereres ofte bedre. Det finnes lister over sukkertype-fordelingen i ulike frukter. Fruktanene er det ingen av oss som klarer å absorbere, dette fordi vi mangler hydrolase-enzymene i tarmen. Det samme gjelder galaktanene.

Når det gjelder polyolene så er de molekyler som er for store for å enkelt passere over tarmen ved passiv diffusjon, det vil si at vi mangler transportsystemer for disse molekylene. Her er det veldig individuelt hvor store doser man tolererer. En pakke med Dent pastiller på styrten vil gi problemer hos de fleste, altså selv om man ikke har IBS.

Laktose defineres som en FODMAP bare hvis man har en laktose-intoleranse. Ved laktose-intoleranse har man for lite laktase-enzymer for å bryte ned melkesukkeret.

Matvarer som inneholder flere typer FODMAP-grupper vil generelt gi enda større problemer, fordi da øker den totale mengden FODMAP. Eplejuice er et klassisk eksempel. Her finner man både fruktose og sorbitol. I tillegg er fruktose-mengden ikke balansert i forhold til innholdet av glukose, sukrose og sorbitol. Når man da tenker på at eplejuice er veldig konsentrert form for eple, så skjønner man at eple kan bli problematisk for mange.

Skodje nevner at ukritisk eliminering av matvarer er vanlig hos IBS-pasienter. Det er ikke uvanlig at høy-FODMAP lister ender som nei-lister. Skodje poengterer flere ganger at det ikke er meningen at man skal stå på lav FODMAP-diett permanent. Det er ikke meningen at man permanent skal kutte ut store matvaregrupper fra kostholdet.

Skodje forteller at på Rikshospitalet så begrenser de eliminasjons-perioden til 6-8 uker maksimum. Etter disse 6-8 ukene starter man gradvis å re-introdusere matvarene for å kartlegge toleranse-grensen for de ulike FODMAPer. Dette er et krevende systematisk arbeid mellom behandler og pasient. På denne måten finner man ut hvilke nivåer man skal holde seg innenfor for å ha et så balansert kosthold som mulig. Man skal tilstrebe en liberalisering så langt man kan innenfor det man tolererer av symptomer og man skal kompansere for matvarer man ekskluderer. Og så må man huske på at toleranse-grensen er doseavhengig. For eksempel kan man kartlegge under reintroduksjon at 0.5 eple daglig kan gå greit, mens 1 eple blir for mye. Vi må altså ta hensyn til den akkumulerende effekten. Det vil si at for eksempel kan 0.5 eple kan bli problematisk hvis det spises 3 dager på rad. Den første dagen kan gå fint, mens på den 3 dagen reagerer man.

Skodje poengterer at man omfavner ikke FODMAP-dietten ukritisk, siden 10 år med forskning er kort tid i denne sammenheng. FODMAPer har mange positive effekter for helsen. Man vet ennå ikke nok om langtidseffektene av et lavt FODMAP kosthold. For eksempel vet man ikke hvordan en lav FODMAP-diett over lang tid vil påvirke mikrofloraen i tykktarmen. Man vet heller ikke langtidseffekten på ernæringsstatus, da store endringer og særlig restriksjoner i kostholdet kan medføre at man ikke får dekket næringsstoff-behovene.

Dietten brukt mest i en-til-en konsultasjoner, men kan også benyttes i grupper. Man skal være obs på at bruk av skriftlige FODMAP-råd uten annen veiledning ikke er å anbefale, fordi det blir vanskelig for pasienten å utføre kostholdet riktig og strukturert. Konsekvensene kan være at FODMAP-dietten få en manglende effekt, og kan muligens påføre unødvendige restriksjoner i kostholdet. Men så lenge man får kyndig veiledning er FODMAP-dietten etter hvert blitt akseptert og anbefalt som den mest effektive kostbehandlingen ved IBS.

## Avslutning og spørsmål fra publikum

Avslutningsvis ble det oppfordret til spørsmål fra salen. Det ble spurt om hvor lett det er for en IBS-pasient å få tilgang til en trenet klinisk ernæringsfysiolog. Skodje svarte at hun skulle ønske hun kunne si at det er lettere enn man tror. Men på Rikshospitalet er de nå i en veldig lovende situasjon fordi de er i etableringsfasen av en ny ernæringspoliklinikk, og her vil det være lettere å få tilgang som poliklinisk pasient. Driften vil ikke være i gang før på nyåret, da de driver å ansetter nå. Dette er hun veldig glad for å kunne si, siden hun vet at mange opplever at det er vanskelig å få tilgang til klinisk ernæringsfysiolog.

Arne Schatten takket for oppmøtet og summerte opp saker som LMF skal jobbe med fremover. LMF skal se på mulighetene for grunnstønad til de med IBS. LMF må sørge for at helse-direktoratet sin informasjon om IBS er riktig, og øke kompetansen hos fastleger. De vil også rette søkelys på barn og IBS. LMF ønsker å stimulere til mer forskning og LMF ønsker også å jobbe for bedret tilgang til klinisk ernæringsfysiolog.
