---
title: "10 ting du bør vite dersom du jobber skift eller natt"
author: "Andrea Rørvik Marti"
date: 2015.05.16
---

Nattarbeid er en nødvendig bestanddel i vårt moderne samfunn, men helsemessig er ikke det å jobbe om natten det lureste du gjør. Jobber du natt er det en del ting du bør være klar over, og i denne artikkelen får du presentert ti viktige punkter.

## 1. Du er utsatt for betydelig helserisiko

Tallene er klare: Natt- og skiftarbeid har betydelige negative konsekvenser for helsen. Denne typen arbeid er blant annet assosiert med psykiske lidelser, som depresjon og angst \[1\], søvnforstyrrelser \[2\], metabolsk syndrom \[3, 4\], forstyrret glukosetoleranse og svekket insulinfølsomhet \[5\], hormonforstyrrelser \[6\], døgnrytmeforstyrrelser \[7\], og problemer med fordøyelsen \[8\]. I tillegg har skiftarbeid blitt klassifisert som “sannsynligvis kreftfremkallende” av verdens helseorganisasjon, og assosiert med en lang rekke kreftformer \[9, 10\].

## 2. Mennesker er ikke tilpasset et liv om natten

Du husker kanskje fra biologitimen at forskjellige arter er tilpasset ulike "nisjer" i miljøet. Noen arter er tilpasset et liv under bakken, andre i tretoppene, og noen i luften. Så lenge liv har eksistert har jorden rotert rundt din egen akse, hvilket har den naturlige konskevens at hver enkelt dag er delt inn i en lys og en mørk fase, som vi gjerne kaller natt og dag. Alle arter har derfor vært nødt til å tilpasse seg denne daglige rytmen, og noen har funnet sin plass i natten (nattaktive arter) mens andre er aktive om dagen \[11\]. Til og med sopp og alger har en døgnrytme som følger lys/mørke-perioden. Vi mennesker har tilpasset oss dagen, og alle våre biologiske systemer og organer er bygget opp rundt dette \[12\].

## 3. Du får påvirket "klokkene" i kroppen din når du jobber skift

Alle vev i kroppen har klokker; gener som endrer sitt uttrykk med 24-timers intervaller og forteller organene hvilken tid på døgnet det er \[13\]. Disse styres av "hovedklokken" som ligger i hypothalamus. Denne sender signaler til klokkene i resten av kroppen, som også sender feedback tilbake til hypothalamus og i seg selv påvirkes av andre typer stimuli som for eksempel tilførsel av næring og aktivitet \[13\]. Avhengig av tid på døgnet utfører organene ulike oppgaver. Om dagen brytes celler ned, og energi frigjøres slik at du kan være våken, aktiv og fungere normalt. Om natten repareres cellene, og celledeling finner sted. Når du jobber natt kommer disse systemene ut av rytme \[14, 15\].

## 4. Du får lys på feil tid av døgnet

Lys er den viktigste faktoren som påvirker  klokkene i hjernen \[16\]. Når du får lys inn til øyet om natten undertrykkes melatoninutskillelsen, og en rekke viktige prosesser som skulle funnet sted blir avbrutt \[17\]. Dette påvirker også metabolismen og fremmer sultfølelse \[18, 19\]. Spesielt lys tidlig om morgenen, ved slutten av skiftet, kan gjøre det vanskelig å sovne, og fremmer søvnproblemer \[20\].

## 5. Du får mat på feil tid av døgnet

Klokkene i leveren er spesielt påvirket av måltidsrytme \[21\]. Når du spiser mat om natten blir klokkegenene påvirket, og disse har igjen en effekt på andre gener som forteller leveren hva den skal gjøre med maten som kommer. Studier tyder på at matinntak om natten aktiverer gener involvert i fettlagring \[22\]. En studie viste at rotter som "jobbet nattarbeid", og spiste mat i løpet av nattskiftet, viste mer vektøkning og økt mengde magefett. Disse negative metabolske konsekvensene ble ikke sett blant dyrene som jobbet nattskift uten tilgang på mat \[23\].

## 6. Du tilpasser deg ikke arbeidstiden

Selv ved permanent nattarbeid er det vanskelig å tilpasse seg. Du har fridager der du må forholde deg til mennesker rundt deg som ikke jobber natt, du må på butikken, osv. Svært få nattarbeidere snur døgnet fullstendig. Selv hvis du fjerner alle disse tingene er det vanskelig å unngå dagslys i løpet av dagen. Forskning peker mot at under 3% av nattarbeidere klarer å tilpasse døgnrytmen sin til nattarbeid \[24\].

## 7. Kroppen din er ute av balanse

Etter en endt nattarbeidsperiode er vevene i kroppen din ute av synk, på grunn av at du har blitt utsatt for endrede lys-, aktivitets- og måltidsmønstre \[25\]. Det tar tid å hente seg inn igjen, men ulike systemer bruker forskjellig tid på å komme seg tilbake til den opprinnelige rytmen \[7, 14, 26\]. I denne perioden vil ulike vev operere på ulike «tidssoner», hvilket trolig er med på å fremme sykdommer som for eksempel kreft \[27\].

## 8. Det finnes ting du kan gjøre

Vi vet lite om hvordan nattarbeid fører til negative konsekvenser, men vi vet at endring av ytre stimuli, som lys og matinntak, har en negativ påvirkning. Dersom du klarer det, kan det være lurt å prøve å unngå å spise store mengder mat i løpet av nattskiftet. Den tidligere nevnte studien tyder på at dette kan motvirke noen av de negative metabolske konsekvensene \[23\].

En annen ting som kan være effektivt er å unngå lys, spesielt sollys. Sollys er langt sterkere enn innendørs belysning, og spesielt de 20-30 minuttene med dagslys i bilen på vei hjem fra nattskiftet kan ha en stor påvirkning på søvnen din i etterkant av nattskiftet. Bruk mørke solbriller, og denne effekten kan reduseres noe \[20\].

## 9. Du kan ikke motvirke de negative konsekvensene av natt- og skiftarbeid helt.

Derfor anbefales det gjerne nattarbeid ikke for gravide, eldre, tidligere kreftpasienter, og andre utsatte grupper \[28-30\]. Som natt- eller skiftarbeider er det derimot greit å være klar over at man utsetter seg selv for en viss risiko. Det er allikevel ikke gitt at alle som jobber skift eller natt blir syke. Noen har bedre toleranse for skiftarbeid enn andre \[31\].

## 10. Nattarbeid er (dessverre) helt nødvendig i et moderne samfunn

Samfunnet kan ikke fungere uten nattarbeidere. Vi trenger sykepleiere, leger, politi, brannmenn, nattevakter, transportarbeidere osv døgnet rundt. Derfor er mye av fokuset innen forskningen i dag rettet mot å finne ut hvordan nattarbeid påvirker oss og hvordan dette kan minimeres med ulike tiltak. Eksempler på framtidige tiltak er nærmere kontroll av hvor mange og hvor lange skift nattarbeidere jobber, beskyttelse mot lys under og etter nattskiftet, samt anbefalinger for matinntak under nattskiftet.

**Litteraturliste**

1.  Oyane, N.M., et al., *Associations between night work and anxiety, depression, insomnia, sleepiness and fatigue in a sample of Norwegian nurses.* PLoS One, 2013. **8**(8): p. e70228.

2.  Akerstedt, T., et al., *Sleep and sleepiness: impact of entering or leaving shiftwork--a prospective study.* Chronobiol Int, 2010. **27**(5): p. 987-96.

3.  Karlsson, B., A. Knutsson, and B. Lindahl, *Is there an association between shift work and having a metabolic syndrome? results from a population based study of 27 485 people.* Occup Environ Med, 2001. **58**: p. 747-752.

4.  Tucker, P., et al., *Shiftwork and metabolic dysfunction.* Chronobiol Int, 2012. **29**(5): p. 549-55.

5.  Simon, C., L. Weibel, and G. Brandenberger, *Twenty-four-hour rhythms of plasma glucose and insulin secretion rate in regular night workers.* Am J Physiol Endocrinol Metab, 2000. **278**(3): p. E413-20.

6.  Weibel, L. and G. Brandenberger, *Disturbances in hormonal profiles of night workers during their usual sleep and work times.* J Biol Rhythms, 1998. **13**(3): p. 202-8.

7.  Lac, G. and A. Chamoux, *Biological and psychological responses to two rapid shiftwork schedules.* Ergonomics, 2004. **47**(12): p. 1339-49.

8.  Vener, K.J., S. Szabo, and J.G. Moore, *The effect of shift work on gastrointestinal (GI) function: a review.* Chronobiologia, 1989. **16**(4): p. 421-39.

9.  Matheson, A., L. O'Brien, and J.A. Reid, *The impact of shiftwork on health: a literature review.* J Clin Nurs, 2014. **23**(23-24): p. 3309-20.

10. International Agency for Research on Cancer, *IARC Monographs Programme Finds Cancer Hazards Associated with Shiftwork, Panting and Firefighting.*, W.H. Organization, Editor. 2007: Lyon.

11. Bechtold, D.A. and A.S.I. Loudon, *Hypothalamic clocks and rhythms in feeding behaviour.* Trends in Neurosciences, 2013. **36**(2): p. 74-82.

12. Czeisler, C.A., et al., *Stability, precision, and near-24-hour period of the human circadian pacemaker.* Science, 1999. **284**(5423): p. 2177-81.

13. Buijs, R.M. and A. Kalsbeek, *Hypothalamic integration of central and peripheral clocks.* Nat Rev Neurosci, 2001. **2**(7): p. 521-6.

14. Gupta, S. and A.K. Pati, *Desynchronization of circadian rhythms in a group of shift working nurses: Effects of patterns of shift rotation.* Journal of Human Ergology, 1994. **23**(2): p. 121-131.

15. Salgado-Delgado, R., et al., *Internal desynchronization in a model of night-work by forced activity in rats.* Neuroscience, 2008. **154**(3): p. 922-31.

16. Arellanes-Licea, E., et al., *The circadian timing system: a recent addition in the physiological mechanisms underlying pathological and aging processes.* Aging Dis, 2014. **5**(6): p. 406-18.

17. Dumont, M., et al., *Melatonin production and light exposure of rotating night workers.* Chronobiol Int, 2012. **29**(2): p. 203-10.

18. Fonken, L.K., et al., *Light at night increases body mass by shifting the time of food intake.* Proc Natl Acad Sci U S A, 2010. **107**(43): p. 18664-9.

19. Gangwisch, J.E., *Invited commentary: nighttime light exposure as a risk factor for obesity through disruption of circadian and circannual rhythms.* Am J Epidemiol, 2014. **180**(3): p. 251-3.

20. Rahman, S.A., et al., *Effects of filtering visual short wavelengths during nocturnal shiftwork on sleep and performance.* Chronobiol Int, 2013. **30**(8): p. 951-62.

21. Buijs, R., et al., *Peripheral circadian oscillators: time and food.* Prog Mol Biol Transl Sci, 2013. **119**: p. 83-103.

22. Salgado-Delgado, R.C., et al., *Shift work or food intake during the rest phase promotes metabolic disruption and desynchrony of liver genes in male rats.* PLoS One, 2013. **8**(4): p. e60052.

23. Salgado-Delgado, R., et al., *Food intake during the normal activity phase prevents obesity and circadian desynchrony in a rat model of night work.* Endocrinology, 2010. **151**(3): p. 1019-29.

24. Folkard, S., *Do permanent night workers show circadian adjustment? A review based on the endogenous melatonin rhythm.* Chronobiol Int, 2008. **25**(2): p. 215-24.

25. Ferreira, L.R.C., et al., *Circadian rhythm of wrist temperature and night shift-work.* Biological Rhythm Research, 2013. **44**(5): p. 737-744.

26. Weinert, D. and J. Waterhouse, *The circadian rhythm of core temperature: effects of physical activity and aging.* Physiol Behav, 2007. **90**(2-3): p. 246-56.

27. Fritschi, L., et al., *Hypotheses for mechanisms linking shiftwork and cancer.* Med Hypotheses, 2011. **77**(3): p. 430-6.

28. Davis, S., D.K. Mirick, and R.G. Stevens, *Night shift work, light at night, and risk of breast cancer.* J Natl Cancer Inst, 2001. **93**(20): p. 1557-62.

29. Knutsson, A., *Health disorders of shift workers.* Occup Med (Lond), 2003. **53**(2): p. 103-8.

30. Tucker, P., et al., *The effects of age and shiftwork on perceived sleep problems: results from the VISAT combined longitudinal and cross-sectional study.* J Occup Environ Med, 2011. **53**(7): p. 794-8.

31. Vidacek, S., et al., *Individual differences in circadian rhythm parameters and short-term tolerance to shiftwork: a follow-up study.* Ergonomics, 1993. **36**(1-3): p. 117-23.
