---
title: "Skribentpanel - Hva er dine topp 3 kostholdstips?"
date: 2013.01.24
author:
  - Vegard Lysne
  - Thomas Olsen
  - Asle Bøe
  - Ingvild Thun
  - Hanne Storhaug
categories:
  - skribentpanel
  - kosthold
---

Kosthold er noe som angår oss alle, og mange er også ivrige med å gi ut velmente råd, både på diskusjonsforum, i blogger og muntlig. Men hva er de tre beste tipsene du gir om noen spør? I denne første skribentpanelsaken bad jeg fire av skribentene om å dele sine tre beste kosttips til den generelle befolkningen, og her kommer svarene!

## Ingvild Thun

Ingvild (22) er masterstudent i klinisk ernæring ved UiB, og har følgende råd å komme med:

### 1. Øk inntaket av frukt og grønnsaker

Disse matvarene er stort sett energifattige, noe som betyr at du kan spise ganske store mengder uten at det går mye ut over energiinntaket ditt. De metter også godt med tanke på energien du får i deg, så et økt inntak av frukt og grønt kan også gjøre det lettere å begrense totalinntaket. Frukt og grønnsaker er også gode kilder til mange vitaminer og mineraler, og de fleste virker også basedannende i kroppen vår.

### 2. Øk inntaket av melkeprodukter og andre gode proteinkilder

Protein er et viktig næringsstoff. Først og fremst har det sin funksjon som byggesteiner i kroppen, men også enzymer og en rekke hormoner er bygget opp av aminosyrene som vi får fra nedbrytningen av protein. En annen stor fordel med proteinrike matvarer er at de jevnt over gir en høyere metthetsfølelse enn annen mat, noe som bidrar til å begrense energiinntaket.

Ved å la ren fisk, kylling og annet kjøtt være en naturlig del av det daglige kostholdet ditt, så gjør du helsen din en tjeneste. I tillegg til å bidra med protein av høy kvalitet er disse matvarene også rike på andre næringsstoffer.

### 3. Spis når du er sulten og til du er passe mett

Vi er forskjellige! Noen er sultne om morgenen og liker å spise en stor frokost, mens andre spiser kanskje sen middag/stor kvelds eller er naturlig mindre sulten om morgenen. For friske mennesker er det ingen fornuftig grunn til å spise et ekstra måltid hvis man ikke er sulten og får dekket alle behov for næringsstoffer til andre måltider. Det er alltid lurt å ha sunn mat tilgjengelig hvis man blir plutselig sulten. Gjør det du føler er best tilpasset din livsstil.

## Hanne Storhaug

Hanne (26) er utdannet ernæringsfysiolog ved Helsehøyskolen, og er nå medisinstudent ved UiO. Hun gir deg følgende tips:

###  1.La basiskosten være et variert utvalg av naturlig mat

Basiskosten er et fint ord for det du spiser mesteparten av tiden. Jeg vil anbefale at du i størst mulig grad baserer kostholdet ditt på lite prosesserte matvarer samtidig som du spiser variert. Eksempler på matvarer som passer inn i denne beskrivelsen er fisk, kjøtt, egg, grønnsaker, melkeprodukter, usaltede nøtter og lignende. Denne maten ligner mest på det du finner ute i naturen, og det er sannsynligvis denne typen mat som er gunstigst for helsen vår. Husk at den maten det er sterkest dokumentasjon for at kan være helseskadelig er menneskeskapt, f.eks. industrielt transfett.

Ved å spise variert av matvarer beskrevet over vil du uten problemer dekke behovene for mikronæringsstoffer og essensielle fettsyrer.

### 2. Kutt ned på karbohydratene hvis du sliter med oppblåst mage

Oppblåst mage eller andre symptomer på irritabel tarm blir mer og mer vanlig. Mange har god effekt av å bytte ut brød og frukt med mer protein- og fettrike matvarer.

### 3. Varier energiinntaket etter aktivitetsnivå

Vi trenger ikke like store porsjoner når vi sitter mye stille. Selv om vi trener en time hver eneste dag utgjør det ikke alltid så veldig mye dersom vi er i ro de 23 resterende. Vekten er den beste indikatoreren på om du spiser ok, men de fleste vil kjenne at de trenger mindre mat når de sitter mer stille. Da gjelder det å lytte til kroppen.

## Asle Bøe

Asle (26) er utdannet sykepleier og jobber for tiden i [MyRevolution](http://myrevolution.no/s/artikler/) og som personlig trener på Elixia Kokstad i Bergen. Hans råd er som følger:

### 1. Moderasjon før restriksjon

Når man har kommet til det punktet at man innser at man trenger å endre på det man har gjort til nå for å forbedre helsen eller få en mer tiltalende kroppsfasong, kan man fort overdrive. Karbohydratrestriksjon og begrensing av sukker blir til totalt avhold, fokus på gode proteinkilder og grønnsaker blir til utelukkende magre proteinkilder og grønnsaker og så videre.

Gjør endringene i små steg av gangen, og se på hva du kan begrense og hva du kan legge til. Positive endringer kan skje over et stort spekter, og det er ikke nødvendigvis slik at resultatene blir bedre jo nærmere man kommer ytterpunktene.

Kunsten ligger i å få erfaring med, og kunnskap om, hva som er for mye, hva som er passe og hva som er unødvendig restriktivt.

### 2. Praktiske ferdigheter og hensyn

En ting er å vite hva en bør, skal og vil gjøre, en annen å gjennomføre det i praksis.

De vanene du har og bakgrunnen for de valgene du tar har det tatt årevis å forme. Å skape en livsstil, summen av valgene du tar som påvirker livskvalitet og helse, tar tid. Å legge til rette for å kunne ta de riktige valgene er en kunst, men det kan være en rimelig enkel en:

-   Planlegg handling slik at det du vil ha mer av er mer tilgjengelig enn det du vil ha mindre av.
-   Gjør det enklere å ta flere riktige valg - om du vet det blir pizza hver dag når du kommer hjem fra jobb og er skrubbsulten, forbered noe som er mer fornuftig og lett å lage dagen før.
-   Chipsen som ikke ligger i skapet blir ikke spist - ikke ha ting stående du vet ryker til når du kjeder deg litt.
-   Kultiver gode vaner ved måltider: Spis når du spiser. Facebook er der  om et kvarter også!
-   Vær bevisst på hvorfor du spiser- er det av vane, ved behov, ved kjedsomhet eller for å dekke andre behov?

### 3. Ei kunnskapen din, og vær åpen for ny kunnskap.

Et litt diffust punkt, men et jeg føler er enormt viktig. Du skal vite hvorfor du gjør som du gjør.  Ikke baser kostholdet ditt på overskrifter i tabloide medier og klipp og lim fra ting du har hørt og lest her og der. Et godt og fornuftig kosthold legger grunnlaget for god livskvalitet og helse, men likevel er det stor mangel på kunnskap og gjennomføring av helt grunnleggende aspekter ved det å spise hensiktsmessig.

Kosthold blir nærmest religion for mange. Det handler om å spise god mat en liker og som gjør at en kan ha det bra. Ikke bare her og nå men også i et lengre løp! Det handler om å bli et forbilde for sine barn og venner - ikke en som sitter og skuler på yoghurten til kollegaene mens en spiser en salat. Du spiser for å ha det bra og å fungere med alt det fordrer av energi og velvære. Aldri glem dette!

Søk kunnskap fra solide kilder - at du leser Frisk og Funksjonell kan være en god start!

## Thomas Olsen

Thomas (23) er masterstudent i Human Ernæring ved UiB, og jobber som ernæringsfysiolog ved siden av studiene. Hans råd er:

### 1. Mindre tilsatt sukker og prosessert mat

Til tross for at rene sukkervarer som farin og sirup har sunket betydelig de siste tiårene, har forbruk av varer som sjokolade og brus vært stabile det siste året, kostdebatter og økt kroppsfokus til tross. En fornuftig tilnærming til karbohydratreduksjon innebærer først og fremst å kutte ut kilder til tilsatt sukker som er nettopp overnevnte matvarer, samt en drøss av milkshaker, boller, loff og godterier generelt. Et annet fokus har jeg lyst å rette mot poteten hvorav både produksjon og forbruk av vanlig potet har sunket, mens produkter som chips og pommes frites har skutt i været. Dersom man ønsker en moderat tilnærming til inntak av karbohydrater er poteten en veldig fin ting å støtte seg på om man ikke skulle være glad i/tåle grove kornvarer eller ikke ønsker karbohydratreduksjon av de mer ekstreme variantene.

### 2. Mer frukt og grønnsaker

Forbruket av frukt og grønt i befolkningen har økt jevnt de siste årene med unntak av en liten dupp i 2009. Derfor havner dette som nummer 2 på listen min over viktige kostholdstips. Samtidig er også dette noe de fleste eksperter er samstemte om når det kommer til grep man kan gjøre for å sikre bedre helse. Frukt og grønnsaker bidrar ikke bare med mikronæringsstoffer i form av livsviktige vitaminer og mineraler, men også fytokjemikalier som er med på å forebygge kreft, reduserer oksidativt stress og øker detoksifiseringsreaksjoner i lever (som for øvrig utfører langt bedre detoksifisering enn diverse kosttilskudd som stort sett bare er eselpiss). En enkel måte å gjøre dette på er å alltid ha en kilde til frukt eller grønt til hvert måltid. Et eple ved siden av frokost og halve tallerkenen bestående av salat eller grønnsaker til middag er gode eksempler.

### 3. Sikre proteininntak fra gode kilder

Jeg vil gjerne nevne at et protein ikke er et protein. Vi mennesker er pattedyr, og aminosyreprofilen i animalske kilder (og soya) er av langt høyere kvalitet enn det vi finner i vegetabilske kilder som hvete, frukt og grønnsaker. Det tradisjonelle norske kostholdet bidrar kanskje kvantitativt med nok proteiner, mens inntak av essensielle aminosyrer gjerne er begrenset. To måltider basert på proteinkilder som fugl, fisk, egg eller meieriprodukter vil i de fleste tilfeller sikre de fleste.

Samtidig vil jeg påpeke at å dekke proteinbehovet vårt er enklere enn vi tror. Selv om flere liker å anbefale 2g/kg kroppsvekt til absolutt alle, skal det langt mindre til å dekke behovet til en normalt aktiv person, og det er slett ikke sikkert proteinpulveret du kjører i deg 4 ganger om dagen bidrar med annet enn energi eller substrat for helt andre metabolske veier enn muskelsyntese.

## Oppsummering

Som dere sikkert la merke til, så er det noen råd som går igjen. Selv om de fire skribentene har et ulikt utgangspunkt, så er de enige om en del ting. Kanskje er dette punkter du bør bite deg ekstra godt merke i?

