---
title: "Skribentpanel: Lavkarbo, gull eller tull?"
date: 2013.04.08
author:
  - Torbjørn Lysne
  - Vegard Lysne
  - Thomas Olsen
  - Ingvild Thun
categories:
  - skribentpanel
  - kosthold
---

Kostråd er i vinden som aldri før, og i løpet av det siste tiåret har lavkarbokostholdet fått en sentral rolle i den eviggående kostholdsdebatten. Ekspertene kommer med stadig nye meninger hva angår lavkarbokosthold. Noen er lavkarbofans, noen er antilavkarbo, mens noen er åpen for at lavkarbo kan være det riktige valget for enkelte. I den senere tid har debatten også tatt veien inn i trenings- og idrettsverdenen, og stadig flere kombinerer nå trening med dette kostholdet. Kan dette ha noe for seg? Jeg har spurt tre av våre skribenter om deres meninger om lavkarbo!

Spørsmålene jeg har stilt er følgende, og under kommer skribentenes svar!

1\. Har lavkarbo noe for seg, og i såfall for hvem?

2\. Hva er dine beste tips til en som har lyst å teste ut lavkarbo?

3\. Hva savner du i lavkarbodebatten i media?

## Vegard Lysne

Masterstudent i klinisk ernæring Vegard Lysne (25) har følgende svar:

### 1. Har lavkarbo noe for seg, og i såfall for hvem?

Ja, det har det absolutt. For vektnedgang eller blodsukkerkontroll har lavkarbo god dokumentasjon bak seg for å være en effektiv strategi. Det er også gode indikasjoner på at karbohydratrestriksjon gir positive endringer i blodlipidene hos noen. Dette betyr ikke at alle skal legge om til lavkarbo, for det er mange ting som påvirker våre matvalg, og alle har ikke med helsen å gjøre. Man kan oppnå de samme helseeffektene på andre kosthold, så det viktigste i mine øyne er at vi har flere kostholdsverktøy å velge blant, og at det ikke er en oppskrift som passer for alle. De jeg kunne tenke meg å foreslå karbohydratrestriksjon for er først og fremst overvektige, [diabetikere (type 2)](diabetes-kosthold.qmd) eller de som har spesiell preferanse for «lavkarbomat», hva nå enn dette er.

Når vi snakker om folk med sykdom eller av ulike grunner er i risikogruppen for å utvikle sykdom så bør kostomlegging skje i samråd med lege eller ernæringsfysiolog. Friske har stort sett veldig stort spillerom i valg av hva de vil spise, og til syvende og sist er det også hver enkelt som bestemmer hva man ønsker å spise. Det er blant annet flere idrettsutøvere som mener de presterer bedre med mindre karbohydrater i kostholdet, og da er det selvfølgelig ingenting i veien for å gjøre det slik.

### 2. Hva er dine beste tips til en som har lyst å teste ut lavkarbo?

Hvis man har bestemt seg for å prøve å redusere på karbohydratene, uansett hva som er grunnen til dette, så er det et par tips jeg alltid vil komme med. For det første så bør man etterstrebe å [spise variert](spise-variert.qmd). Lavkarbo er ikke smør og bacon, det er kjøtt, fisk, fugl, egg, grønnsaker, bær, nøtter, bønner, linser, frø, meieriprodukter osv. Kanskje til og med frukt, litt potet/ris og en brødskive om man ikke har tenkt seg på den strengeste varianten. Det trenger ikke å handle om å kutte ut ting, det kan like gjerne handle om å regulere mengden og omstrukturere middagstallerkenen litt, og det siste er i mine øyne helt klart den fornuftige måten å gjøre det på. I alle tilfeller bør sukker, spesielt i flytende form, være det første du kutter ned på.

Jeg vil også anbefale å ikke bruke alle erstatningsproduktene man finner i butikken. Nå er det mulig å kjøpe lavkarboditt og lavkarbodatt, men om du føler behov for å bruke masse av disse produktene så er kanskje ikke lavkarbo noe for deg i utgangspunktet. Å basere seg på helt vanlige råvarer er det svært vanskelig å kritisere, og hvis noen prøver å fortelle deg at du er usunn fordi du velger mer brokkoli/blomkål og mindre potet, så kan du med god samvittighet lukke ørene.

Det aller viktigste tipset mitt vil være å ikke velge lavkarbo bare fordi du har hørt at det er så bra. Velg det dersom dette er mat du liker og trives med å spise, og ikke minst føler deg bra og opplagt med! Det er ingen oppskrift som passer for alle, heller ikke lavkarbo.

### 3. Hva savner du i lavkarbodebatten i media?

Først og fremst savner jeg en skikkelig definisjon av hva man legger i begrepet lavkarbo. Som jeg var litt inne på i forrige punkt så er det enormt rom for variasjon, og det å sette en merkelapp på kostholdet er etter min mening nærmest meningsløst. Det viktige er hva man totalt sett ender opp med å spise, ikke hva man kaller maten.

Debatten er veldig polarisert, der vi på den ene siden har de som mener at lavkarbo er løsningen på alle verdensproblemer og på andre siden får høre at det mer eller mindre er en snarvei til dødssengen. De store uenighetene og den høye temperaturen skyldes både det at debattantene med stor sannsynlighet snakker om vidt forskjellige kosthold, og når man blander dette med mangel på nyanser og kontekst så har vi en eksplosiv kombinasjon.

Jeg skulle gjerne sett en større vilje til å møtes, se på hva man er enige om (det er egentlig ganske mange ting), og heller diskutere grunnlaget for de tingene man er uenige om. Mer ydmykhet og mindre prestisje fra alle sider av debatten hadde gitt en langt mer ryddig debatt, og forhåpentligvis ville også budskapet som når ut til forbrukeren vært enklere å forholde seg til!

## Ingvild Thun

Masterstudent i klinisk ernæring Ingvil Thun (22) har følgende svar:

### 1. Har lavkarbo noe for seg, og i såfall for hvem?

Ja, det kan ha noe for seg – for de personene et slikt kosthold passer for. «Lavkarbo» et vidt begrep og kan innebære alt fra middelhavsdiett med moderat mengde karbohydrater og mer umettet fett, til lchf der man ofte spiser minimalt med karbohydrater og erstatter dette med fett (ofte mest mettet). Konseptet bak lavkarbo i forhold til vekttap, er at for mange vil mer fett og proteiner føre til økt metthet, noe som igjen fører til kaloriunderskudd og vekttap.

I tillegg vil lavkarbo ofte bety redusert inntak av raske karbohydrater som sukker og hvitt mel, samt bearbeidet mat og ferdigprodukter. Man blir flinkere til å lage mat fra bunnen av, bruke mye grønnsaker, gode proteinkilder og rene råvarer (noe som ikke innebærer fråtsing av bacon). Når dette er sagt, vil ikke et kosthold bestående av lite karbohydrater og veldig mye fett passe alle, men som sagt er ikke lavkarbo ensbetydende med et strengt regime.

De fleste vil si at det er en livsstil, og det finnes mange varianter – men hadde hele Norges befolkning kuttet ut sukker, hvitt mel og ferdigprodukter tror jeg de fleste ville kommet under betegnelsen «moderat lavkarbo». Kornprodukter er en stor del av hverdagen til de fleste nordmenn, og er man tilfreds med kostholdet sitt, er sunn og har en frisk kropp, er det flott.

Det finnes mange oppskrifter her i verden, og ikke alt passer alle like bra.

### 2. Hva er dine beste tips til en som har lyst til å teste ut lavkarbo?

Vi bestemmer heldigvis selv hva vi spiser, det gjelder også hvis man har bestemt seg for å teste ut lavkarbo. Vil man satse på moderat lavkarbo, ekstrem lavkarbo osv, er smak og behag. Jeg vil uansett anbefale å starte med å kutte ut raske karbohydrater som ikke bidrar\
med annet enn rene kalorier og lite næringsstoffer, slik som sukker og hvitt mel, samt alle produkter med mye av dette som ingrediens. Vær obs på kaloriene du drikker, som brus, juice osv og kutt disse. Videre ville jeg kuttet ut begynt å lage all mat fra bunnen av og kuttet ut alt av ferdigprodukter. Mye grønnsaker, melkeprodukter hvis man tåler det, gode proteinkilder som kjøtt, fisk, egg og fugl samt bær, nøtter og frø tilfører mange viktige næringsstoffer og gir god metthet. Hvor mye fett du skal spise avhenger av hvor mye du reduserer på karbohydratene, det viktigste er at du er klar over dette og ikke ender opp med å redusere for mye uten å erstatte.

### 3. Hva savner du i lavkarbodebatten i media?

Mye! God dokumentasjon og korrekt fremlegging av forskningsresultater fremfor alt. Alle har et ønske om å være frisk og føle seg bra, men når aviser har forsidestoff for/mot lavkarbo annenhver dag, blir dette veldig svarthvitt og lite seriøst. Hvis EN studie har funnet noe som kan være bra eller dårlig for helsen vår, blir dette fort forsidestoff. Problemet er at denne dokumentasjonen ikke er god nok: en studie er langt fra nok til å kunne komme med antydninger, og i alle fall ikke konklusjoner. I tillegg er ofte studiene svake i design og\
utførelse, noe som fort kan gjøre dem ubrukelige. Det er blitt skapt to fronter når det kommer til helse; en mot og en for lavkarbo, og disse er ikke i stand til å samarbeide til tross for felles mål. Lavkarbo er en av flere veier til vekttap, vi er ulike på omtrent alle områder og det finnes ingen fasit for alle.

## Thomas Olsen

Masterstudent i human ernæring Thomas Olsen (23) har følgende svar:

### 1. Har Lavkarbo noe for seg, og i så fall for hvem?

For å si det helt enkelt og greit, et kosthold bestående av frukt, grønnsaker, nøtter, fisk og fjærfe, sunne oljer og kjøtt, tror jeg det er svært få fagpersoner som kunne frarådet, enten man er frisk eller ikke. Et balansert og variert kosthold basert på disse matvarene kan helt fint la seg gjøre i menigmannens måltidshverdag, og er naturlig lavt på karbohydrater alt ettersom. Men andre ord kan lavkarbo som kosthold være helt greit enten man er frisk eller syk.

Når det er sagt synes jeg at bagatelliseringen av mettet fett og LDL i lavkarbo-leiren er en smule overdrevet. Det er greit at mettet fett i seg selv ikke er lik hjertesykdom, men hos mennesker med eksempelvis høyt blodtrykk og andre tilstander som gjør risikoen for karskader høy, syns jeg at man skal være forsiktig med å anbefale store mengder mettet fett, mens et utgangspunkt i matvarene nevnt over kan være greit. LDL-partikler spiller en rolle i aterosklerotiske prosesser, og en nyere oppdatering av en gjennomgang publisert av Cochrane Library ([Lee Hooper et al.](http://www.ncbi.nlm.nih.gov/pubmed/22592684)) viser at å bytte ut mettet fett med umettet fett til en viss grad ser ut til å gi moderat gevinst, mens å bytte ut mettet fett med stivelsesrik mat ikke gav noen klare helsegevinster. **Jeg mener dog at man skal være forsiktig med å ekstrapolere denne kunnskapen over til friske individer, og at så lenge man er frisk og rask, kan man fint kose seg med helfete meieriprodukter, ost og en entrecôte.**

Så med andre ord, ja, lavkarbo kan definitivt ha noe for seg. Er man glad i god og fet mat, om man vil ned i vekt, eller om man rett og slett blir litt småuggen av brød og pasta, kan man gjerne ha en tilnærming hvor man ikke spiser spesielt mye karbohydrater. Er man syk og aspirerende hjerte- og karpasient skal man kanskje velge fettkildene sine med omhu så lenge evidensen er slik den er i dag. 

### 2. Hva er dine beste tips til en som har lyst å teste ut lavkarbo?

Først og fremst ville jeg funnet ut hvor det er aktuelt å kutte. Frukten og bærene til mellommåltidet eller poteten til middag kan man gjerne beholde til å begynne med, og heller fokusere på å kutte ned på brødmåltider som etter alt og dømme sannsynligvis dominerer. Dersom du spiser 2-3 brødmåltider om dagen kan du kanskje kutte ned til ett, og ha middagsrester til lunsj i stedet. Drikker du mye sukkerholdig væske, eller er i overkant glad i sjokolade? Da kan du kanskje vurdere sukkerfrie alternativer til drikken og en liten neve mandler i stedet. Vips så har du faktisk kuttet ut en god del karbohydrater fra kosten, det trenger ikke være vanskeligere enn det, og er helt legitime, sunne, enkle, gode valg. Et utgangspunkt i frukt, grønt, fjærfe, fisk, kjøtt, nøtter og et melkeglass eller to er kjempefint!

### 3. Hva savner du med lavkarbodebatten i media?

Helt ærlig savner jeg saklighet og sidesyn. Et lite lys i tunellen.

Jeg kan ikke dy meg, og om du leste innlegget mitt på nyåret som går ut på å [sette individet i fokus](pekefinger.qmd), så vet du kanskje hvor jeg vil med dette. Debatten og debattantene på begge sider av kjøledisken er fremdeles i full fyr selv om den kanskje har avtatt litt i media. Det mest hjernedøde man hører fra lavkarbo og paleoleiren er gjerne at karbohydrater i seg selv gir deg kreft, mens man på den andre siden mener at mettet fett i kosten øker sjangsen for både det ene og det andre uten å ta hensyn til at en fettsyre ikke er en fettsyre og at observasjonsdata kun er **observasjons**data.

Det er på tide og møtes, se seg selv i speilet og innrømme ovenfor hverandre at ernæringsepidemiologi og forskning generelt er rimelig tynn suppe, og konklusjoner skal dermed forsiktig trekkes. Mat er mye mer enn biokjemi, metabolisme og statlige anbefalinger. Preferanser, behov og trivsel spiller en vel så viktig rolle, men dine preferanser er ikke automatisk andres preferanser, og det som føles bra for deg kan være et lite helvete for andre.

## Oppsummering

Det ser ut til å være enighet om at lavkarbo som kosthold, selv om begrepet i seg selv kanskje trenger en nærmere beskrivelse, kan være et alternativ som passer for noen, men ikke alle. Skribentene fokuserte på ulike områder når det gjelder selve gjennomføringen, men samtidig nevnte de mange av de samme tingene, som å tenke over hva man velger å kutte ned på først. Alle nevner også noe om det å ha variasjon i kostholdet. Når det gjelder den offentlige kostdebatten var det ulike synspunkter, men felles for alle skribentene var at de ikke virker fornøyd med hvordan denne har utartet seg.

##### Har du synspunkter på det som er skrevet, eller kanskje du ønsker å dele dine svar på de tre spørsmålene? Gjør det i kommentarfeltet!
