---
title: "Skribentpanel - Hvordan komme i gang med trening?"
date: 2013.02.21
authors: 
  - Vegard Lysne
  - Martin Norum
  - André Midtby
  - Torbjørn Lysne
  - Eivind Eliasson
---

Sist gang vi kjørte skribentpanel var temaet [kostholdstips](skribentpanel-kostholdstips). Denne gangen er temaet trening, nærmere bestemt hvordan man best mulig kommer i gang med trening. Jeg har spurt fire skribenter om hva som er deres tre beste tips for å komme i gang med treningen, og her er svarene de har kommet med!

## Martin Norum

Martin (22) er personlig trener og fagansvarlig ved akademiet for personlig trening. Han har følgende råd:

### 1. Bestem deg og ta deg sammen

Det er ikke så lenge siden vi gikk inn i et nytt år. Et nytt år som skal være fullt av trening, masse sunn mat og ingen unnasluntring, ikke sant? Om dette er nyttårforsettet ditt bør du allerede nå gjøre en liten revurdering. Du har nemlig gjort noe mange gjør, å sette seg litt overambisiøse målsetninger. Det er ingenting galt med å trene 5 ganger i uken og spise sunt om du trives med det, men litt rom for tilvenning til en ny livsstil og det å ikke være perfekt hele tiden bør det også være plass til. Jeg mener at det for mange som ikke er vant med store mengder trening er smartere å starte med tre treningsøkter i uken. I motsetning til hva mange tror kan tre økter i uken gi veldig gode resultater. Det er ikke slik at mer alltid er bedre.

Samtidig må du gå litt skikkelig inn i deg selv å tenke etter hvorfor du egentlig gjør dette. Hvorfor skal du egentlig sette av tid til å trene og leve sunnere enn i 2012? Gjør du det for å gjøre kroppen din en tjeneste? Gjør du det for å se litt mer sexy ut naken? Hva enn grunnen din er, ha den i bakhodet! En ting som kan være fornuftig er å visualisere hvordan du vil føle deg når du når målene dine. Hva vil følelsen av å ha oppnådd det du ønsker gi deg? Hva vil den gi de menneskene som er rundt deg? Har du barn og en partner? Kanskje vil de også nyte godt av din egen livsstilsendring? Dette gir straks en litt større driv til å trå til!

### 2. Finn en treningsform du liker

Dette er viktig. Hater du å jogge? Ikke jogg. Det høres kanskje for åpenbart ut til å være nødvendig å skrive, men faktum er at svært mange presser seg på trening på noe de ikke liker å gjøre. Da er det heller ikke så enkelt å holde motivasjonen oppe. Samtidig er dette et tveegget sverd; ofte bør man nemlig gjøre en del ting som man ikke synes er så kult. Hvis du for eksempel ikke synes styrketrening er noe særlig fordi du ikke får høy puls og blir sliten er det fristende å ta beina fatt og bare løpe i stedet. Ulempen er at du med bare løping sannsynligvis ikke vil ende med den kroppskomposisjonen du opprinnelig var ute etter. Kanskje kan du gjøre et kompromiss med deg selv ved å bruke styrketrening i form av sirkeltrening for å få litt av begge verdener?

### 3. Få deg en treningspartner eller PT

Trener du alltid alene? Prøv å få med en kompis eller venninne på øktene dine. Helst da en kompis eller venninne som er omtrent på samme nivå som deg selv, og som du vet også er ute etter å bli flinkere med treningen. Om dere bestemmer dere for å trene sammen har jeg et lite tips: snakk om hvordan dere skal hjelpe hverandre. Går dere inn på et treningsstudio uten å ha tenkt noe over dette, kan det fort ende med å bli mer skravling enn trening, og da mister du litt av poenget. Det er helt fint å være sosiale i pausene, men da skal ikke pausene og øktene blir lenger pga dette. You're on a mission, ikke glem det! Det vil også være svært hensiktsmessig å få hjelp av en PT som kan se dine behov og sy sammen et opplegg du kan følge, enten med PTen, med kompisen eller alene. En dyktig PT kan sine saker om trening og kan se ting i et helt annet perspektiv enn du selv kan. Snakk med andre du kjenner som har brukt en PT og hør om de har noen anbefalinger.

Avslutningsvis vil jeg si; skynd deg sakte. Selv om du har dårlig tid og egentlig helst skulle hatt resultater i går - vent. Innse at trening og et sunt kosthold ikke er et korttidsprosjekt, men noe du skal trives med gjennom et langt liv. Lykke til på veien!

## Eivind Eliasson

Eivind (29) er utdannet fysioterapeut og tidligere aktiv innen styrkeløft. Hans råd er følgende:

### 1. Finn aktiviteter du liker

Om du over tid skal ha motivasjon til å fortsette å være fysisk aktiv, er det viktig at du liker det du holder på med! Om det er golf (for all del ikke kjør rundt i golfbil!) eller crossfit er ikke så nøye, det viktigste er at du liker det og at du får brukt kroppen din!

### 2. Ha et mål å jobbe mot

Har du planlagt å trene tre ganger i uken, men av ulike grunner bare får gjennomført en, så har du likevel beveget deg i retningen av det overordnede målet ditt. Mange kan miste motivasjonen dersom de ikke klarer å trene så mye som de i utgangspunktet hadde tenkt, men denne tankegangen er det lett å vri på. Dersom alternativet var å droppe treningen, så kom du mye lenger mot målet med denne ene økten du faktisk rakk å gjennomføre! En ukentlig løpetur eller kanskje en intervalløkt i motbakke vil for eksempel hjelpe deg på veien mot bedre kondisjon!

### 3. Ikke sammenlign deg med andre.

Om du til stadighet tar deg selv i å ønske deg formen til kompisen din som trener mye, så husk på at du har din kropp og han har sin. Dere har ulikt utgangspunkt, og kan ikke sammenlignes direkte. Trening er noe du gjør for din egen del, så prøv heller å oppnå dine egne mål i stedet for å sammenligne deg med andre!

## André Midtby

André (21) er landslagsutøver i styrkeløft, og blir å se på EM og VM dette året. Han holder også kurs i baseløft rundt om i landet. Dette er hva André mener er viktig:

### 1. Sett deg realistiske mål og følg dem

Når man har bestemt seg for å ta tak i treningen, enten det er for å bli sterkere, ta av noen kilo eller bare “stramme opp” litt, er det viktig å sette seg realistisk og konkrete mål. La oss legge fokuset på det jentene kaller å “stramme opp”. Okei, for det første: Hva skal du stramme opp? Hvis svaret er “alt”, så har du bommet. **Finn konkrete mål!** Det å ta bilder av seg selv kan være veldig motiverende, siden du da lettere kan se tilbake og se forbedring! “-Oppfordrer han meg til å ta nakenbilder??“ Ja, ettersom vi ser vår egen kropp hver eneste dag kan det være vanskelig å se både positiv og negativ utvikling. Det er ikke snakk om at du skal eksponere bildene på facebook, men at du har noe for deg selv du kan se tilbake på, og en bedre trent kropp er som oftest en motivasjonsfaktor til at mange trener.

Sørg også for å ha delmål på veien. Dette er mye av grunnen til at jeg liker styrketrening og styrkeløft, det er så målbart. Veldig mange har de siste årene endelig fått med seg at dette er treningen som virkelig gjør nytten fra seg, også blant jentene som tidligere ikke besøkte styrkeavdelingen. La det at du ønsker å løfte x kg i knebøy være et delmål, eller at du skal gå ned x antall centimeter rundt midjen – Det å ha noe å strekke seg mot er motiverende!

### 2. Tren på en måte du trives med

Som nevnt er styrketrening en veldig god måte å trene på, da det former kroppen og fungerer effektivt i forhold til fettforbrenning. Ha fokus på baseløft som eksempelvis knebøy og markløft.

“Men hva om jeg hater styrketrening?” Vel, da lar du være, enkelt og greit! Trening i en eller annen grad er kommet for å bli. Du skal ha den kroppen du nå har i mange år fremover, og skal du få den slik du ønsker, men sliter med å komme igang med treningen, er det viktig å gjøre noe du liker! Likte du å spille basketball, gå på ski eller være ute i naturen når du var yngre? Finn tilbake til dine yngre dager og se etter hva du trivdes med for deretter å kunne legge inn dette som trening. Gjør treningen til noe du synes er morsomt/interessant. Synes du swing og dans er gøy? Vel, da sørger du for å være i aktivitet gjennom det, sving løs!

### 3. Les deg opp på trening, eller oppsøk noen som kan hjelpe deg

Styrketreningen slår til igjen, jeg har ikke gitt meg helt enda! For noen er frivektområde en mørk hule med skumle personligheter og tredemølla en sikker vinner. Men de fleste som har kastet seg ut i styrketreningen, angrer på at de løp på mølla til tunga lå limt under skosåla...og litt til! Dette siste punktet handler om kunnskap, og hvordan du kan tilegne deg denne.

Viktigheten av å trene riktig er stor. Eksempelvis er knebøy en øvelse sikkert 80-90% på treningssenter gjør feil i en eller annen grad, uten å være for pirkete. Er du usikker på noe, ikke trekk deg tilbake eller dropp det – angrip usikkerheten ved å spørre andre på treningssenteret (slapp av, de er ikke skumle!), bestill en time hos personlig trener (vær kritisk til hvem du velger) og/eller les deg litt opp på trening. Det ligger enorme ressurser rundt deg, bruk de!

Avslutningsvis ønsker jeg å nevne  i korte trekk: Finn din motivasjon, finn treningspartner(e) og støtt hverandre, sett av tid til trening og ta i litt når du er på trening! Lykke til – you can do it!

## Torbjørn Lysne

Torbjørn (23) er utdannet fysioterapeut, og for tiden i turnus. Han driver aktivt med friidrett, og tok i 2012 to sølv i NM, på 100m og 200m sprint. Hans råd er:

### 1. Sett konkrete og realistiske mål

Har du tidligere prøvd å komme i gang med trening og mislyktes? Et enkelt tips for å bryte denne trenden kan være å skrive ned målene og henge de opp synlig en plass i hjemmet. Du vil da ofte bli minnet på målene, og motivasjonen til å klare de vil øke. Å skrive ned målene ser jeg på som det viktigste tipset for å komme i gang med mer regelmessig trening. Gå i deg selv og finn ut hva nettopp du ønsker å oppnå. Er det å få bedre kondis, styrke, hurtighet eller spenst? Se bedre ut? Skriv ned konkrete mål; «Trene X ganger i uken», «Løpe 5km på X minutter», «Ta X kg i knebøy», «Gå ned X kg» osv. Det kan også være lurt å skrive ned delmål på veien mot hovedmålet, og ikke minst når du skal nå disse.

Et urealistisk mål vil for de fleste ødelegge for motivasjonen, mens et realistisk mål vil være ditt første steg på veien til å komme i gang med trening!

### 2. Tren lystbetont

Dette er et velkjent tips, men desto viktigere å følge! Å trene på ting en ikke synes er gøy er kanskje den største motivasjonsknekkeren av de alle. Trening skal være gøy og lystbetont, og det er spesielt viktig for de som sliter med å komme i gang. Noen ganger kan du kanskje være nødt til å trene noe du ikke synes er gøy for å oppnå målet, men det kan du vente med til du har kommet litt i gang med det du synes er gøyere. Du bør komme inn i en god rutine før du begynner å eksperimentere med treningsøkter du i utgangspunktet ikke liker. Trening som ikke er gøy kan slå ut både positivt og negativt på motivasjonen. Går det greit kan du fortsette, hvis ikke bør du slutte og gå tilbake til lystbetonte økter.

### 3. Ta tiden til hjelp

Vær også obs på at ingen mennesker er like. Personer med samme utgangspunkt trenger ofte ulike mengder trening for å oppnå det samme. Ikke forhast deg dersom du ikke opplever den fremgangen du ønsker. Bruk den tiden du trenger og hold motivasjonen oppe. Et solid treningsarbeid over tid vil alltid gi resultater til slutt!

Begynn forsiktig og øk heller antall økter/intensitet når du har trent en stund. Da vil faren for belastningsskader og motivasjonssvikt reduseres betraktelig.

## Oppsummering

Det som går igjen i svarene fra de fire intervjuobjektene er dette med å sette seg mål, finne aktiviteter man liker og å søke kunnskap om korrekt og effektiv trening. Med dette som utgangspunkt burde du være godt rustet til å ta fatt på treningen og forvente resultater!
