---
title: "10 nyttige ting du bør vite om smerte"
author: "Martin Hole Hanstvedt"
date: 2013.09.23
---

De aller fleste opplever smerter fra tid til annen og det er mye man vet og ikke vet når det gjelder smerter.  Forekomsten av rapportert smerte i Norge er høyere enn i mange andre europeiske land, og man anslår at [30 prosent av de voksne har kroniske smerter i Norge i dag](http://www.dagensmedisin.no/nyheter/tar-tak-i-kroniske-smerter/). Den vanligste årsaken er muskel- og skjelettplager, men en rekke andre lidelser kan også føre til kronisk smerte.

Smerte er uten tvil noe av det mest interessante som finnes når det gjelder helse og hvordan vi mennesker har det i hverdagen. Det kan også være nyttig å vite hva smerte faktisk er, da det har vist seg at man lettere kan håndtere smertene dersom man har noe kunnskap om hva det er og hva det kommer av. Forskningen har gjort store fremskritt, men har ennå mye å ta for seg når det gjelder smerte. I denne artikkelen vil jeg gjennomgå en del ting som kan være nyttig å vite om smerte, enten for din egen del eller dersom smertebehandling er noe du arbeider med.

Før vi går gjennom de 10 punktene kan det være nyttig å få med seg denne videoen der Lorimer Moseley, en australsk fysioterapeut, snakker om hvorfor ting gjør vondt. Vel verdt en titt!

\[youtube=http://www.youtube.com/watch?v=gwd-wLdIHjs\]

## 10 ting som er verdt å vite om smerte

### 1. Smerte blir definert som

> en ubehagelig sensorisk og emosjonell opplevelse assosiert med faktisk eller potensiell vevsskade, eller beskrevet i forhold til slik skade (International Association for the Study of Pain)

Det er en biopsykososial opplevelse og alle elementene vil være til stede når man opplever smerter.

### 2. Smerte kan være nyttig.

Når du opplever smerte betyr dette at hjernen din tolker det som at kroppen er i fare for å bli skadet. Det perifere nervesystemet og sentralnervesystemet er ansvarlig for å formidle informasjon til hjernen som igjen tolker hva dette er. Smerteopplevelsen har til hensikt å motivere deg til å foreta deg noe, vanligvis beskytte kroppsdelen som hjernen tror (rett eller galt) er skadet eller i ferd med å bli skadet. På denne måten er smerte en overlevelsesmekanisme som kan være svært viktig for at du skal bli klar over at noe er skadelig kan være i ferd med å skje, og smerte vil på denne måten kunne være svært nyttig da det får oss til å gjøre noe.

### 3. Smerte er ikke alltid en presis indikator for vevsskade.

Noen kroppsdeler og noen skader kan oppleves å være smertefulle selv om skaden er liten, og man kan ha fått store skader uten at man opplever en tilsvarende smerte. Når en kroppsdel blir skadet vil nerveender sende signaler til hjernen som inneholder informasjon om skadens omfang og lokasjon. Smerte blir likevel ikke opplevd før hjernen har tolket denne informasjonen og bestemt seg for at smerte er det rette for å få deg til å beskytte kroppsdelen slik at smerten skal forsvinne. Smerte er derfor ikke alltid en presis måling på hvor stor vevsskade som har skjedd eller er i ferd med å skje. Det er mange faktorer som spiller inn og det fins også store individuelle forskjeller relatert til hvor mye smerte man opplever ved samme skade avhengig av alle disse faktorene.

Smerte er altså et svært komplekst område som kan ha mange mulige årsaker og løsninger.

### 4. Kartlegging

Når man hanskes med smertefulle tilstander er det essensielt å få kartlagt en rekke mulige faktorer som kan være med å påvirke smerteopplevelsen. Det er også viktig å huske at hjernen tar hensyn til svært mange faktorer samtidig og mange deler av hjernen er delaktig i å tolke de ulike signal som hele tiden blir mottatt. Områder i hjernen som omfatter minner, følelser og framtidige intensjoner er blant annet medvirkende i å tolke signalene som blir mottatt. Det er da viktig å huske at selv om du opplever langvarige smerter, betyr ikke det at det alltid er en stor vevsskade eller degenerasjon i kroppen din.

### 5. Effekten av å forstå smerte

Forskningen rundt smerte har vært omfattende og har også vist at det å ha kunnskap om smertefysiologi er assosiert med [økt mestring av smerte ](http://www.ncbi.nlm.nih.gov/sites/pubmed/15322439)og bedring av funksjon (Moseley,2002; Moseley et al., 2004). Man har også vist at smertefysiologi kan læres av mannen i gata (Moseley, 2003). Det å forstå smerte kan være en stor fordel ved å endre betydningen av smerte, slik at vedkommende får en annen forståelse for hvordan smerte kan oppstå og vedvare.

### 6. Smerten forsvinner ikke alltid selv om skaden leges

En av årsakene til at smerten ikke alltid forsvinner selv om vevsskaden er leget, er at hjernen kan endre oppfattelsen av smerte, også kalt sentral sensitisering. Det er en slags smertehukommelse  der hjernen overreagerer for å beskytte deg mot fare ved at du opplever smerte og dermed muligens unngår aktiviteter som tidligere har vært smertefulle (Giummarra et al, 2011). En vevsskade kan muligens øke graden av sensitisering slik at hjernen lettere kan beskytte området som er blitt skadet. Mange faktorer kan påvirke opplevelsen av smerte positivt eller negativt: stress, utmattelse, følelsmessig tilstand, forventninger, oppmerksomhet, endringer i fysisk aktivitet (ny aktivitet eller mer intensitet).

### 7. Dårlig holdning trenger ikke å gi kroniske smerter

Det er ikke nødvendigvis noen sammenheng mellom assymetri, “dårlig holdning”, “skjevheter” og langvarig opplevelse av smerte (kronisk). ”Dårlig” holdning trenger altså ikke bety at du får eller har smerter. Lederman E. (2011) skrev en interessant artikkel som diskuterer nettopp dette. Den er noe bombastisk etter min mening og konkluderer til tider med ting som kan varierere dersom man går inn på individnivå, men artikkelen er absolutt verdt å lese.

### 8. Placebo og nocebo er to kraftige virkemidler

Placebo: Forventningene om at et tiltak skal lindre smertene er nok til å redusere smerteopplevelsen. Man tror det hjelper og derfor hjelper det.

Nocebo Hvis forventningene er negative så vil det redusere effekten av smertebehandling. Forventninger om bivirkninger kan fremkalle sykdomstegn. Man tror ikke på at det skal hjelpe, og dermed reduseres effekten/negativ effekt. Les mer om placebo i en [fagkronikk i bladet “Fysioterapeuten”](http://fysioterapeuten.no/Fag-og-vitenskap/Fagartikler/Placebo-mer-enn-kvakksalveri-og-innbilt-virkning). Takk til Manuellterapeut Sigurd Mikkelsen sin side som stadig tipser om interessant fagstoff.

### 9. Språkbruk og informasjon

Språkbruk og informasjon er viktig når smerte er involvert (Bedell et al.,2004). Dessverre er det slik at feil språkbruk og informasjon kan være med å forandre en pasient sin oppfattelse av egen smerte og årsaken til denne, og igjen være med å påvirke bevegelsesmåten på en negativ måte. Dette skjer ofte uten at pasienten selv er klar over det. Fear avoidance ved [ryggsmerter](http://martinhanstvedt.com/2012/03/01/ryggsmerter-start-her/) - frykten for å bevege seg – er et eksempel på dette. Man blir redd for å få smerter ved bevegelse og slutter derfor å bevege seg sånn som man burde og kunne gjort dersom man hadde hatt tro på at det går greit. 

### 10. Du kan alltid gjøre noe

Når man opplever smerter er det viktig å huske at man nesten alltid kan gjøre noe for å holde resten av kroppen i gang. Generelt sett er det bedre for personer med smerter å [holde seg aktiv](http://www.ncbi.nlm.nih.gov/pubmed/20556780) (Dahm, 2010). Man må ikke på treningssenter eller løpetur for å trene eller være i aktivitet. Det vil nesten alltid være noe man kan gjøre selv om man har smerter som kan bidra til å bedre plagene på sikt. Ved å starte på riktig nivå og med god veiledning vil det være mulig å kunne mestre nye bevegelser og skape sunne bevegelsesmønster. Dette bør naturligvis unngås dersom man nettopp har skadet seg ordentlig, som ved for eksempel et benbrudd.

Smerte er altså et svært omfattende tema og det er fortsatt svært mye å lære om hva smerte er og hvordan det kan behandles.

Dersom du opplever langvarige smerter vil det uansett være fornuftig å oppsøke noen som kan hjelpe deg dersom du ikke finner en løsning på problemene selv. Les [denne](http://martinhanstvedt.com/2012/03/01/velge-behandling-eller-behandler/) for å finne den rette personen til dette.

Les også [Er en MR-undersøkelse svaret på dine smerter?](http://martinhanstvedt.com/2012/08/07/er-mr-undersokelse-svaret-pa-dine-smerter/)

Jeg kan også anbefale fysioterapeut [Tony Ingram sin side](http://www.bboyscience.com/pain/) der han skriver mye interessant om smerter og andre ting:

Referanser:

-   Bedell SE, Graboys TB, Bedell E, Lown B.Words that harm, words that heal. Arch Intern Med. 2004 Jul 12;164(13):1365-8.
-   Dahm KT, Brurberg KG, Jamtvedt G, Hagen KB. Advice to rest in bed versus advice to stay active for acute low-back pain and sciatica. Cochrane Database Syst Rev. 2010 Jun 16;(6):CD007612. doi: 10.1002/14651858.CD007612.pub2.
-   Giummarra MJ, Georgiou-Karistianis N, Nicholls ME, Gibson SJ, Chou M, Bradshaw JL.Maladaptive plasticity: imprinting of past experiences onto phantom limb schemata.Clin J Pain. 2011 Oct;27(8):691-8. doi: 10.1097/AJP.0b013e318216906f.
-   Lederman E. The fall of the postural-structural-biomechanical model in manual and physical therapies: exemplified by lower back pain. J Bodyw Mov Ther. 2011 Apr;15(2):131-8. PubMed PMID: 21419349.
-   Moseley L. Combined physiotherapy and education is efficacious for chronic low back pain. Aust J Physiother 2002;48:297-302.
-   Moseley GL, Nicholas MK, Hodges PW. A randomized controlled trial of intensive neurophysiology education in chronic low back pain. Clin J Pain. 2004 Sep-Oct;20(5):324-30.
-   Moseley G.L., Unraveling the barriers to reconceptualization of the problem in chronic pain: the actual and perceived ability of patients and health professionals to understand the neurophysiology. J Pain 2003
