---
title: "Hvorfor bør du spise variert?"
date: 2012.12.10
---

Skal vi tro alle reklamene for kosttilskudd som ruller over tv-skjermen? Skulle nesten tro at helt vanlig mat ikke lenger virker, og at kosttilskudd er veien å gå for å oppnå god helse. Er det sånn at vi har gjort oss avhengige av kosttilskudd for å holde oss sunn og frisk, eller kan vi få alt vi trenger fra maten vi spiser? Og hvordan skal vi sikre at vi får til dette?

## Behov

For at kroppen skal fungere optimalt er vi helt avhengig av å dekke behovene for alle næringsstoffene. Alle sammen spiller sentrale roller i vår fysiologi, og når noe mangler så er det noe som ikke fungerer som det skal. Hvor mye vi trenger av hvert næringsstoff varierer en del. For vitaminer og mineraler sier helsedirektoratet "[ikke for lite, ikke for mye](http://www.matportalen.no/kosthold_og_helse/tema/naringsstoffer/vitaminer_og_mineraler__ikke_for_lite_ikke_for_mye)", noe som forteller oss at vi trenger en viss mengde, men at det også kan bli for mye og skape problemer på denne måten. Det siste er ikke noe du trenger å tenke på om du bare spiser vanlig mat.

Husk at retningslinjene er basert på en vurdering av den tilgjengelige forskningen, og er et uttrykk for gjennomsnittet av en befolkning. Ditt spesifikke behov vil du ikke kunne beregne nøyaktig, fordi forhold som størrelse, aktivitetsnivå og alder vil være med å påvirke dine personlige behov. De offentlige anbefalingene vil likevel være tilstrekkelig for de aller, aller fleste.

De energigivende næringsstoffene (karbohydrat, fett og protein) er viktige for å tilføre den energien vi trenger for å overleve og fungere, og fett og protein fungerer i tillegg som byggesteiner. De ulike vitaminene og mineralene har viktige funksjoner overalt i kroppen, blant annet for å kunne utnytte oss av energien i maten vi spiser. Mer inngående informasjon om dette finner du i vår [artikkelserie om næringsstoffer](brokenlink/naeringsstoffene/ "Artikkelserie om Næringsstoffene").

For å dekke behovene for de energigivende næringsstoffene gjelder det å spise nok mat. Spiser vi mer enn vi trenger vil den overflødige energien lagres som fettvev og vi legger på oss. Spiser vi derimot mindre enn vi bruker må vi hente ut lagret energi fra fettvevet, og vi blir slankere. Mer om dette kan du lese i artikkelen om [energibalansen](brokenlink/energibalansen/ "Energibalansen – hva sier den egentlig?"). Behovene for vitaminer og mineraler dekkes vanligvis i et normalt kosthold, men spiser du veldig ensidig eller lite kan du risikere å utvikle mangeltilstander.

## Spis variert

For det første vil jeg si at det ikke er spesielt vanskelig å dekke alle behovene gjennom kostholdet alene. Litt kunnskap og planlegging av hvilken mat du velger å spise er alt som skal til. Myndighetene har i alle år rådet oss til å spise variert, og om du skal ta med deg bare en ting fra dette innlegget, så er det nettopp dette!

Ulike matvarer bidrar med forskjellige næringsstoffer, noe som er grunnen til at et ensidig kosthold kan føre til mangeltilstander. Spiser du lite, f.eks. fordi du slanker deg, er det desto viktigere å velge smart fordi redusert matinntak også gir mindre næringsstoffer. De som spiser mye vil dermed ha større friheter i kostholdet sitt, men det er en naturlig følge av at det totale inntaket av næringsstoffer er høyere.

For å dekke alle behovene kan det være praktisk å tenke på de ulike matvaregruppene, og sørge for at du over tid er innom flere av disse. Her følger en rask oversikt over ulike matvaregrupper og hva de bidrar med i kostholdet ditt.

### Grønnsaker

Generelt sett er grønnsaker energifattige, men inneholder mye vitaminer og mineraler. Dette gjør grønnsaker til svært næringstette matvarer som du kan spise mye av uten at det går noe særlig utover energibudsjettet ditt. Grønnsaker er også en fin kilde til fiber, som er positivt for tarmfunksjon og blodsukkerregulering. De er også basedannende i kroppen, og bidrar til å balansere effektene av de fleste andre matvarer som er syredannende.

### Frukt og bær

Frukt og bær egner seg ypperlig som dessert eller mellommåltid. Sammenlignet med andre alternativer inneholder disse en del vitaminer og mineraler og mindre energi. C-vitamin finner vi bare i frukt, bær og grønnsaker. Som grønnsakene er også disse matvarene basedannende.

### Kjøtt

Kjøtt er en fantastisk proteinkilde, og inneholder en rekke viktige mineraler. Spesielt er kjøtt en god kilde til jern, og dette jernet tas mye lettere opp enn jern fra planteriket. Også B-vitaminer finner vi mye av i kjøtt.

### Fisk og sjømat

Som kjøtt er også fisk en god kilde til protein og en rekke vitaminer og mineraler. Jod er et mineral vi i stor grad får fra fisk og sjømat. Fisk, spesielt fet fisk, er en god kilde til de viktige omega-3-fettsyrene som er essensielle for oss. Fet fisk er også en av de få matvarene som inneholder D-vitamin.

### Egg

Egg er en supermatvare som inneholder så godt som alt vi trenger. Proteinet er av topp kvalitet, og med unntak av C-vitamin inneholder egget også alle vitaminene og mineralene. Spesielt eggeplommen er rik på næringsstoffer, mens hviten hovedsakelig består av vann og protein.

### Meieriprodukter

Melk er også en supermatvare, og der egget inneholder alt som skal til for å lage en kylling, inneholder melken alt som skal til for å fø en kalv. Alle pattedyr, mennesket inkludert, drikker morsmelk den første tiden. Melk inneholder protein av høy kvalitet, og mange vitaminer og mineraler. Spesielt viktig er melken som kilde til kalsium og riboflavin.

### Nøtter

Nøtter er en veldig fin energikilde, og spesielt rik på mineraler. Nøtter er også en fin kilde til E-vitamin. Paranøtter er en eksepsjonelt god kilde til selen! Spis gjerne nøtter daglig, men tenk litt over mengdene da det fort blir mye energi av det!

### Fullkorn

Skal du spise kornprodukter så bør du av mange grunner velge fullkornsvariantene. Disse inneholder mer fiber enn de fine variantene, noe som blant annet påvirker blodsukkerresponsen etter et måltid. Innholdet av vitaminer og mineraler er høyere, men samtidig er biotilgjengeligheten lavere på grunn av mer antinæringsstoffer som fytat. Så selv om du ikke nødvendigvis tar opp så mye mer vitaminer og mineraler ved å velge fullkorn, så er de likevel et bedre valg på grunn av høyere fiberinnhold og at de metter bedre.

## Konklusjon

Målet med dette innlegget er å gjøre deg bevisst på hvorfor det anbefales å spise variert. I tillegg til at dette sikrer inntaket av alle næringsstoffene, så gir det deg større friheter og muligheter i forhold til kostholdet. Strenge dietter har absolutt sin plass i gitte situasjoner, men for de fleste vil mer frihet være hensiktsmessig. Det øker i det minste sjansen for at de eventuelle tiltakene du velger å gjøre i kostholdet ditt blir varige.

Jeg sier ikke at du skal eller bør inkludere alle matvaregruppene i kostholdet ditt, hvertfall ikke daglig. Jeg er for en individuell tilnærming til kostholdet, der hver enkelt tilpasser maten til egne preferanser og målsetninger. Det er imidlertid veldig gunstig å være innom en del av de ulike matvaregruppene, hvertfall over tid, for å sørge for at du får i deg alt du trenger. Gjør du dette trenger du ikke å bekymre deg for om du trenger kosttilskudd eller noe annet fancy, da holder det lenge med den vanlige maten!
