---
title: "Stump Røyken"
date: "2012.02.18"
---

Det er liten tvil om at å stumpe røyken er ett av de viktigste grepene du kan gjøre for helsen din, om ikke det aller viktigste. Hvorfor er dette da så vanskelig for mange, mens andre kan slutte på dagen uten videre problemer? I dette innlegget kommer jeg inn på noen av de negative helseeffektene av røyk, og forteller deg hvorfor du bør slutte!

## Risikofaktor for sykdom

Røyking er som kjent en viktig risikofaktor for å utvikle sykdommer. Hovedsakelig tenker man da på lungekreft, men røyk gir også økt risiko for andre krefttyper og hjertesykdom! **Det kan blant annet nevnes at dersom du har hatt et hjerteinfarkt, kan du ved å kutte ut røyken halvere risikoen for å utvikle en ny hjerterelatert hendelse**.

Røyken påvirker flere ting i blodårene våre på en negativ måte. For det første gir røyk en mer ugunstig fordeling av [blodlipidene](http://www.friskogfunksjonell.no/minikurs-i-lipoproteiner/ "Minikurs i lipoproteiner") våre. Dette er som kjent en risiko for sykdommer relatert til hjertet. I tillegg gjør røyken blodplatene mer klebrige, slik at det lettere dannes blodpropper. Av effekter på selve åreveggen så øker røyken det oksidative stresset, slik at det lettere dannes skader der det kan avleires fettstoffer. Dette gir en trangere passasje, slik at blodtilførselen til vevet nedenfor avleiringene blir dårligere. **Spesielt under fysisk aktivitet når blodtrykket øker kan dette gi problemer.** Det hjelper ikke på situasjonen at blodets oksygenbærende kapasitet reduseres, siden hemoglobinmolekylene blir opptatt med å frakte karbonmonoksid, CO, fra røyken i stedet.

Nå må det selvfølgelig også nevnes at røyk ikke nødvendigvis er en risikofaktor for enkeltindividet. Det er mange eksempler på folk som har røykt masse og likevel blitt svært gamle, så med stor sannsynlighet er det en genetisk predisponering for hvordan man reagerer på røykingen. Altså, røyk er ikke sunt for noen, men det gir heller ikke den samme risikoen for alle.

**Det som likevel er helt klart er at hvis en større gruppe slutter å røyke, vil den gjennomsnittlige sykdomsrisikoen synke betraktelig!**

## Avhengighet og det å slutte

Det er nikotinen i røyken som gir avhengighet. Nikotinen binder til nikotinreseptorer i hjernen, som gir en positiv opplevelse for den som røyker. Når man røyker over tid, utvikles det flere av disse reseptorene, slik at de positive opplevelsene med røyken økes. **Disse reseptorene forsvinner ikke når man slutter å røyke**, noe som gjør at det er veldig lett å havne utpå igjen om man f.eks. tar seg en røyk på fest. Derfor er det helt klart best å kutte ut alt for godt om man først bestemmer seg for å slutte!

Det tilsettes flere stoffer i røyken for at produsentene skal selge mer og dermed øke fortjenesten. Blant annet gjelder dette stoffer som øker nikotinopptaket til hjernen, og stoffer som får sigaretten til å brenne raskere. Dette fører til at avhengigheten blir sterkere og siden hver røyk tar kortere tid, er det stor sjanse for at antallet sigaretter økes.

**Den fysiske avhengigheten av røyk forsvinner på 2-4 uker, men den psykiske avhengigheten kan vare mye lenger.** Derfor er det lurt å gjøre noe med vanene rundt det å røyke i tillegg til selve røykeslutten. Dette kan f.eks. være at dersom man alltid starter dagen med en røyk og kaffe, kan det være lurt å også droppe denne kaffekoppen i en periode. I andre situasjoner der det er naturlig å ta en røyk, kan det også være nyttig å endre på det man pleier å gjøre, noe som kan gjøre det enklere å droppe røyken.

Den fysiske avhengigheten (pga nikotinreseptorene) kan oppleves svært ulikt fra person til person. **For de som opplever store abstinenser, finnes det tilbud som nikotinplaster eller medikamenter.** Et vanlig medikament heter champix, og fungerer ved å blokkere nikotinreseptorene. Da vil man ikke lenger merke de positive opplevelsene ved røyken, og det blir enklere å droppe den. [Røyketelefonen](http://www.slutta.no/) er også et tilbud for de som ønsker oppfølging og gode råd underveis.

Om man ønsker å fortelle andre om røykesluttplanene eller ikke er veldig individuelt. For mange kan det være positivt å fortelle det til andre, siden man da kan få støtte og hjelp til å slutte. For andre kan det oppfattes som et økt press, og nederlaget ved å mislykkes kan oppleves enda sterkere om mange vet om det. Her må man rett og slett velge selv hva man setter høyest.

**Hvor vanskelig det er å slutte med røyk er veldig individuelt**. For noen er det ikke noe problem i det hele tatt, mens andre opplever store problemer. Her spiller nok forventninger i stor grad inn, som en slags selvoppfyllende profeti. Om an forventer at det kommer til å bli veldig vanskelig å slutte, så blir det gjerne det, men om man bestemmer seg for at dette ikke skal være noe problem kan det være det blir mye enklere. For å sitere kong Harald: *"Det var skuffende enkelt å slutte å røyke".* **Husk også at de fleste som har sluttet å røyke har hatt flere enn to forsøk bak seg, så om du mislykkes første gang er det bare å prøve igjen.** Da har du også fordelen av at du kan lære av dine egne feil fra forrige forsøk!

**Det er også dyrt å røyke, og en bevisstgjøring av hvor mye penger som går med på røyk kan gi en god motivasjon til å stumpe røyken for godt.** Her er en tabell som viser hvor mye du sparer på å kutte røyken, utifra hvor mye du røyker per dag.

|                    |       |       |       |        |        |
|--------------------|-------|-------|-------|--------|--------|
| Sigaretter per dag | 1 mnd | 3 mnd | 1 år  | 5 år   | 10 år  |
| **10**             | 1240  | 3720  | 14600 | 73000  | 146000 |
| **15**             | 1860  | 5580  | 21900 | 109500 | 219000 |
| **20**             | 2480  | 7440  | 29200 | 146000 | 292000 |
| **25**             | 3100  | 9300  | 36500 | 182500 | 365000 |
| **30**             | 3720  | 11160 | 43800 | 219000 | 438000 |
| **35**             | 4340  | 13020 | 51100 | 255500 | 521000 |
| **40**             | 4960  | 14880 | 58400 | 292000 | 584000 |

## Visste du at

Etter røykeslutt tar det

-   20 min før blodtrykk og puls er tilbake til normalen

-   24 timer før risikoen for akutt hjerteinfarkt er redusert

-   48 timer før lukt- og smaksevnen er forbedret

-   72 timer før lungekapasiteten øker, og etter 2-3 mnd er kapasiteten økt inntil 30%

-   1 år før risikoen for akutt hjerteinfarkt er halvert

## Avslutning

Jeg håper at dette blogginnlegget har gitt deg en ekstra motivasjon til å stumpe røyken for godt. Som nevnt i innledningen er røykeslutt det viktigste enkelttiltaket du kan gjøre for helsen din, og kombinert med andre tiltak som forbedringer i kostholdet og en økning i aktivitetsnivået er du på god vei til en optimal helse! Våre [råd for en bedre helse](http://www.friskogfunksjonell.no/vare-rad-for-bedre-helse/ "Våre råd for bedre helse") er et godt utgangspunkt!
