---
title: "Nei, du er ikke avhengig av sukker"
author: "Andrea Rørvik Marti"
date: 2013.10.17
---

Avhengighet er en betegnelse som slenges rundt om mye forskjellig, men mange av disse tilstandene er ikke de samme. I denne artikkelen vil jeg forklare hvorfor problemer med å kontrollere inntak av sukker ikke bør refereres til som en avhengighet. Hvis vi legger til grunn den typen avhengighet vi ser hos mennesker og dyr som ikke klarer å kontrollere sine impulser til å ta eksempelvis kokain eller amfetamin, vil vi se at de prosessene som underligger denne formen for avhengighet ikke underligger sukker«avhengighet». Det oppleves kanskje som vanskelig å kutte ned på sukkeret iblant, og for noen er dette kanskje tilnærmet umulig. Det skal man ikke nekte for, men denne adferden har lite eller ingenting med rusavhengighet å gjøre. 

Artikkelen bygger først og fremst på to reviewartikler (1,2).

## Hva mener vi med "avhengig"?

Aller først bør vi skille mellom det som man på engelsk refererer til som "addiction" og "dependence". Selv om jeg ikke liker uttykkene "fysisk" og "psykisk" avhengig, kan jeg bruke de her for å illustrere. Hvis fysisk avhengighet er det samme som dependence, kan man si at dette skjer som et resultat av at kroppen utvikler et fysisk behov for tilførsel av substansen, og man opplever fysiske abstinenser som for eksempel svette, hodepine og oppkast hvis man ikke får tilført stoffet. Denne typen avhengighet er et resultat av helt andre mekanismer enn "psykisk" avhengighet, og vil ikke være i fokus her. Uttrykket "psykisk" avhengighet er noe misvisende, siden dette også er et resultat av fysiske endringer som resultat av kronisk inntak av en substans. Vi kan se på denne formen for avhengighet som det man på engelsk referer til som "addiction". Denne typen avhengighet kan løst defineres som et intenst ønske om å innta en substans samt manglende evne til å kontrollere denne impulsen, til tross for alvorlige negative konsekvenser. Fra nå av, når jeg refererer til "avhengighet", er det dette jeg mener.

Hos lekfolk blir "psykisk" avhengighet ofte sett på som mildere og mindre alvorlig enn "fysisk" avhengighet. Man har tenkt på psykisk avhengighet som et resultat av dårlige valg, som skal kunne kureres ved hjelp av viljestyrke, coaching eller andre former for terapi. Nyere forskning tyder derimot på at denne typen avhengighet er like fullt fysisk manifestert som den mer lettgjenkjennelige "fysiske" avhengigheten. Hos avhengige individer ser man tydelige biologiske endringer i strukturer i hjernen som knyttes til motivasjon, belønning og impulskontroll. I begynnelsen er det sannsynlig at inntak av avhengighetsskapende substanser er viljestyrt, men hos de individene som blir avhengige blir evnen til å kontrollere inntaket avbrutt. Vi kan derfor se på denne formen for avhengighet som en hjernesykdom med en årsak som er like fysisk som for eksempel en hjertesykdom. Unormal adferd knyttet til avhengighet er altså et resultat av dysfunksjoner i hjernen

## Hvilke endringer skjer i hjernen hos avhengige?

For å utvikle avhengighet er det nødvendig med vedvarende eksponering for den aktuelle substansen. Det er derimot ingen direkte sammenheng mellom inntak av en substans og utvikling av avhengighet. Her spiller både biologiske og miljøfaktorer inn. Vi vet ikke nøyaktig hvorfor noen mennesker utvikler avhengighet og andre ikke, men dette er sannsynligvis en følge av genetiske predisposisjoner, biologiske prosesser, sosiale og andre miljøfaktorer. Det vi derimot ser i hjernen til mennesker og gnagere som er avhengige, er omfattende endringer i viktige kretsløp av aktivitet. Til tross for at studiet av dette har pågått i over to tiår er vi enda ikke i mål med å kartlegge alle endingene som skjer. Jeg vil derimot ta for meg visse veletablerte endringer som man kan observere i hjernen til individer som er avhengige.

På cellenivå kan man hos gnagere som er avhengige av kokain eller amfetamin observere forgrening på dendrittene til cellene i Nucleus Accumbens (Nac) og Prefrontal cortex (PFC). Dendrittene er tråder som står ut av cellekroppen og kopler sammen hjerneceller i store nettverk. Når dendrittene utvikler forgreninger (se figur under) øker dette overflatearealet og tettheten til cellene. Dette fører trolig til økt sensitivitet i disse hjerneområdene, som er relatert til motivasjonen for å innta en substans. Her skiller vi mellom det å ha lyst på noe og det å like noe. Forgreningen av dendrittene i denne delen av hjernen fører trolig til økt lyst på substansen individet er avhengig av, uten å påvirke hvor mye vedkommende liker substansen. Rapporter fra avhengige individer tyder på at de ofte opplever en kompulsiv lyst på stoffet til tross for at de ikke opplever nytelse av å innta det.

På nevrotransmitternivå kjenner de fleste til at avhengighet er knyttet til endringer i dopaminsensitivitet og -utskillelse. Dette er derimot bare en liten del av historien. Hos avhengige ser man endringer i en lang rekke nevrotransmittersystemer, deriblandt de som involverer GABA, opiater, serotonin og flere ulike nevropeptider. Når sensitivitet og utskillelse av disse nevrotansmitterne endres fører dette til betydelige dysfunksjoner i sammenhengende kretser i hjernen. Den mesokortikale (mesocortical) kretsen er en av de som er mest studert og tilsynelatende mest endret ved avhengighet; igjen kan dette relateres til motivasjon og ønske om å innta en substans uten økning i hvor mye nytelse man opplever av substansen. Den mesolimbiske (mesolimbic) kretsen ser også ut til å være sentralt involvert, noe som kan tyde på at emosjoner spiller en rolle i utviklingen og opprettholdelsen av avhengighet.

## Hva med mat eller sukker?

De fleste studier av avhengighet er gjort hos mennesker og rotter, og hovedsakelig på avhengighet av kokain og amfetamin. Grunnen til dette er fordi det er stoffer som er relativt enkle å administrere, og siden disse som oftest fører til en økning i fysisk aktivitet kan man studere hvor mye rotter er villige til å jobbe for å få tilgang på stoffet (for eksempel hvor mange ganger de er villige til å trykke på en pedal). Med for eksempel heroin eller andre stoffer som virker sløvende, kan dette være problematisk da rottene etter hvert vill jobbe saktere og saktere ettersom stoffet setter inn. Stoffene som brukes i forskning på avhengighet (og læring mer generelt) kalles ofte for forsterkere. En kjapp innføring i hva en forsterker er og hvilke ulike typer som finnes må tas med her

## Naturlige og kunstige forsterkere

Når en rotte er villig til å trykke på en pedal for å få tilgang på en gjenstand eller en substans, kan man kalle denne gjenstanden/substansen for en "forsterker", fordi den forsterker utførelsen av aktiviteten. Enhver substans som fører til utskillelse av dopamin kan kalles for en forsterker. Normalt skiller man mellom naturlig og kunstige forsterkere. Naturlige forsterkere er forsterkere som har en funksjon for overlevelse; det at man er villig til å jobbe for å oppnå disse er normalt sett en positiv ting. Naturlig forsterkere kan være for eksempel mat, sex eller sosialt samvær. Alle disse fører til utskillelse av dopamin, og en påfølgende positiv følelse. Dette er en svært viktig overlevelsesfunksjon, og helt nødvendig for at vi skal kunne fungere normalt. Når man leser i tabloidene at "sukker har samme effekt i hjernen som heroin" er det dette man mener; det fører til dopaminutskillelse. De glemmer derimot å nevne alle de betydelige forskjellene som oppstår i hjernen ved kronisk bruk av heroin kontra sukker.

Kunstige forsterkere er forsterkere som ikke har en overlevelsesfunksjon i seg selv, men som derimot kan ha negative konsekvenser for oss. Her finner vi blant annet rusmidler. Vi kan også skille mellom primære og sekundære forsterkere. En primær forsterker fører direkte til utskillelse av dopamin; dette kan for eksempel være kokain eller nikotin. En sekundær forsterker er en forsterker som assosieres med den primære forsterkeren og som fører til en mindre utskillelse av dopamin, samt en påfølgende motivasjon til å innta den primære forsterkeren; dette kan for eksempel være brukerutstyr for heroin, en lighter, et sted knyttet til inntak av substansen eller lignende. Slike primær- og sekundær-assosiasjoner skjer også mellom naturlige forsterkere og assosierte gjenstander, og kan føre til påminnelser om den naturlige motivasjonen vi alle har mot å innta disse substansene.

## Sukkeravhengighet da?

Så hvis mat og sukker fører til økt utskillelse av dopamin, som i sin tur fører til økt ønske om å innta dem, hvorfor kan man da ikke si at man er avhengig av sukker?

For det første fører ikke kronisk inntak av sukker til dysfunksjoner i hjernen; derimot er hjernens primære energikilde nettopp sukker i form av glukose. Både mennesker og rotter opplever et sug etter sukker nettopp fordi det er nødvendig for å opprettholde optimal hjernefunksjon, og fordi det i vår evolusjonære historie har vært viktig for oss å innta søte matvarer som for eksempel frukt for å få i oss nok energi. I tillegg kan det nevnes at søt mat opp gjennom evolusjonen også har representert trygg mat, da giftige forbindelser i naturen sjelden smaker søtt, noe som også kan forklare hvorfor vi trekkes mot det søte. Selv om raffinert sukker, eller karbohydrater generelt for den saks skyld, kanskje ikke er livsnødvendig for vår funksjon slik vi lever i dag, ville det vært helt totalt bakvendt og destruktivt hvis en av våre viktigste energikilder gjennom historien skulle ført til betydelige dysfunksjoner i hjernen som i sin tur førte til alvorlige negative konsekvenser for adferd og sjanser for overlevelse.

Likevel, det at visse mennesker opplever en sterkere trang til å innta sukker enn andre er det liten tvil om. Det at visse mennesker inntar mer mat enn de behøver er det heller ingen tvil om. Og det at dette i sin tur kan føre med seg alvorlige negative konsekvenser er det heller ingen tvil om. Hvorfor kan man ikke da si at mennesker som har disse erfaringene er avhengige? Grunnen er så enkel som at i ren vitenskapelig forstand er det tilnærmet umulig at de samme prosessene som bidrar til kokain- eller heroin-avhengighet skal kunne føre til sukkeravhengighet. Ingen foreløpige studier tyder på abnormaliteter i nevrotansmitterkretser eller forgrening av dendritter for å nevne noen få eksempler.

Hvis vi grovt sett sier at avhengighet handler om en økt lyst på en substans som følger av dysfunksjoner i områder av hjernen som har med motivasjon å gjøre, så er det lite som tyder på at problemer med sukkerinntak har de samme underliggende mekanismene. Det som derimot er mer sannsynlig er at vi alle har en basal, naturlig, medfødt lyst på sukker, men av noen av oss har en svekket evne til å kontrollere denne lysten. [Manglende impulskontroll](livsstil-latskap.qmd) har jeg så vidt vært inne på tidligere, og også her vil jeg presisere at det ikke er meningen å si at de som sliter med å kontrollere sitt inntak av sukker «bare» skal ta seg sammen. Dette handler ikke om å bagatellisere, men å skille begreper fra hverandre. Når man snakker om avhengighet snakker man enten om et behov som fører til abstinens ved manglende inntak, eller om en motivasjon til å innta en substans til tross for alvorlige negative konsekvenser. Det er altså ikke klinisk mulig å bli avhengig av en naturlig forsterker på samme måte som man kan bli avhengig av en kunstig forsterker. Det er derimot mulig å ha varierende evne til å kontrollere egne impulser, eller rett og slett være preget av dårlige vaner. Dette er ingenting å kimse av, men problemet løses heller ikke ved å diagnostisere en selv med en lidelse en ikke har. Ikke bare kan dette føre til forvirring både blant rusmisbrukere, stoffavhengighet, helsepersonell eller hos mennesker som sliter med matinntak, men det fører til en propagering av terminologi brukt på feil måte i feil situasjon. Selvfølgelig kan det føles godt å kunne si at man er «avhengig», men når det ikke er det som er det faktiske problemet løser man ingen verdens ting.

En av de viktigste grunnene til at man må skille psykiske lidelser ut ifra hvilke underliggende hjernedysfunksjoner som forårsaker dem er at dette er viktig i utviklingen av behandlinger. Om 10 år vil vi kanskje ha utviklet psykofarmaka som kan brukes i behandling av de underliggende årsakene til avhengighet, men ikke til impulskontroll. I slike tilfeller er det viktig å vite hva som feiler en for å kunne foreskrive rett behandling. Man vil aldri kunne behandle de som sliter med overforbruk av sukker og de som sliter med avhengighet av kokain med samme medisin; nettopp fordi disse to tilstandene ikke er de samme.

Så, neste gang du har lyst til å bruke uttrykket «avhengighet» om alt som er vanskelig å motstå, tenk om igjen. Uansett hvor vanskelig det er å motstå den sjokoladen: Du er ikke avhengig av sukker!

Referanser:

1.  Benton, D. (2010). The plausibility of sugar addiction and its role in obesity and eating disorders. *Clinical Nutrition*, 29, 288-303.

2.  Volkow, N. D., & Li, T. K. (2004). Drug addiction: the neurobiology of behaivour gone awry. *Nature Reviews Neuroscience*, 5, 936-970.
