---
title: "Sunt eller usunt - betydningen av kontekst"
date: "2012.06.15"
---

Kan den entrecoten du spiste til middag regnes som sunn eller usunn? Og hva med potetene du spiste ved siden av? Av og til kan det virke som om en matvare kan klassifiseres som enten sunn eller usunn, men er det egentlig så enkelt? Hva avgjør om en matvare er sunn eller ikke, og kan den være begge deler?

## Sunnhet og helse

Det er mange betydninger av begrepene sunnhet og helse, og du vil få ulike svar alt etter hvem du spør. Det kan være snakk om konkrete ting som fravær av sykdom, eller mer komplekse forhold som psykisk velvære og trivsel. Alle de ulike aspektene gjelder også når det er snakk om kosthold, noe som kan være med å komplisere synet på om en matvare er sunn eller usunn. Et kosthold som er sunt for deg trenger ikke nødvendigvis å være like sunt for en annen. Alle har ulike behov, så å kategorisk definere en bestemt matvare som sunn eller usunn blir rett og slett en grov overforenkling.

## Betydningen av kontekst

Det er selvfølgelig mulig å lage generelle retningslinjer for hva som er sunn og usunn mat, men overgangen vil være langt mer glidende enn som så. Problemet med å sette for klare grenser her er at det ikke tas hensyn til individuelle forskjeller i både kosthold og livsstil. For å kunne si noe om en matvare er sunn eller usunn for akkurat deg, må vi se på kostholdet og livsstilen din som en helhet.

Viktige spørsmål å stille seg kan være:

-   Hva ønsker du å oppnå?

-   Hvor mye er du i fysisk aktivitet, og hvordan er intensiteten?

-   Hva har du spist/skal du spise resten av dagen?

-   Er dette unntaket eller regelen?

Alle disse tingene spiller inn når du skal avgjøre om noe vil være greit å spise eller om det vil være mer hensiktsmessig å la være. Hvis du har spesifikke målsetninger som f.eks. å gå ned i vekt, setter det begrensninger for hva som er lurt å spise, men først og fremst vil det være mengdene som påvirkes. Er du mye i fysisk aktivitet vil du slippe unna med større frihet i kostholdet enn dersom du sitter i ro hele dagen. Et kakestykke eller to som et daglig innslag i kostholdet vil være en dårlig idé for den gjennomsnittlige sofapoteten, mens en deltaker i Tour de France gjerne er helt avhengig av å ty til slike løsninger for å dekke det enorme energibehovet sitt.

Hva du spiser til hvert enkelt måltid er underordnet det totale matinntaket over tid. Vi vet at måltidsfrekvensen spiller liten rolle så lenge totalinntaket er det samme, og dette bør tas med i vurderingen av måltidsstørrelsen. Hvis du spiser få måltid om dagen, er det greit at disse er store. Hvis du derimot trives best med å spise ofte, vil det kanskje virke mot sin hensikt om måltidene samtidig er store og energirike, spesielt om målet er vektnedgang. Vil du opp i vekt kan det være vanskelig å få i seg nok mat på få måltider, og det kan være lurt å spise oftere.

Det du gjør mesteparten av tiden vil også avgjøre mesteparten av resultatene du får. Om kake og brus er et daglig innslag i kostholdet ditt er det nok ikke det lureste du gjør, men om du en sjelden gang velger å kose deg med dette vil det ha minimalt å si i lengden. Det kan til og med slå positivt ut på f.eks. psykiske aspekter ved helsen din. Igjen gjelder det å ta hensyn til de langsiktige målsetningene dine og velge derifra.

For å oppsummere er det viktig å ta hensyn til helheten. Om en matvare er sunn eller ikke vil avhenge av hvilken kontekst vi snakker om, og det er mange faktorer å ta hensyn til. **Hvem, hva og hvorfor er sentrale spørsmål å ta utgangspunkt i.** For å gjøre generelle forbedringer i kostholdet ditt kan du ta utgangspunkt i de følgende artiklene.

[Enkle tiltak som kan forbedre kostholdet ditt del 1](kosthold-tiltak-1.qmd "Enkle tiltak som kan forbedre kostholdet ditt – del 1")

[Enkle tiltak som kan forbedre kostholdet ditt del 2](kosthold-tiltak-2.qmd "Enkle tiltak som kan forbedre kostholdet ditt – del 2")

[Enkle tiltak som kan forbedre kostholdet ditt del 3](kosthold-tiltak-3.qmd "Enkle tiltak som kan forbedre kostholdet ditt – del 3")

##### Hva legger du i begrepene sunn og usunn?
