---
title: "Sunnere livsstil? Prøv en ny strategi!"
author: "Stine Malvik"
date: 2014.09.04
---

Å endre livsstil er ikke lett. De fleste vet hva som er sine største «synder», og har en formening om hva man burde gjøre for å få et sunnere liv. Har du noen gang tenkt på at det kan være enklere å tilføre noe sunt, enn å fjerne noe usunt? Det har jeg tenkt å sette fokus på i denne artikkelen.

Mitt inntrykk er at når folk flest skal endre på noe i kostholdet sitt, så er det gjennom å fjerne noe som de mener ikke burde være der, i hvert fall ikke så ofte. Folk flest får nok dårligere samvittighet av å spise for mye av enkelte ting, enn å spise for lite av andre. Kutte ned på sjokolade, godteri, snacks, brus og kaker – det er ofte tanker som står i hodet på folk som plages med dårlig samvittighet over kostholdet sitt. Er du en av de som har prøvd utallige ganger å kutte ned på enkelte matvarer? Matvarer du mener ikke er bra for helsen (eller vekten) din? Hvordan har det fungert?

Enkelte er sånn at når de bestemmer seg for noe, og virkelig går inn for det, så gjennomfører de med stil og uten å klage for mye over det. Mitt inntrykk er at dette oftere gjelder gutter enn jenter, men det har jeg ikke noe vitenskapelig belegg for å påstå. Jeg synes i alle fall at det virker som at enkelte gutter bare kan bestemme seg for å slutte å spise godteri, og det er det. Mens for jenter er sprekken kommet allerede etter noen dager, eller kanskje på neste jentekveld hvor «presset» blir for stort. Jeg har flere ganger tenkt at fra mandag av, så blir det en strammere linje, og den må jeg holde i noen uker. Men når helga kommer, og fredagskvelden med Idol og stearinlys står foran meg, så kommer suget etter «noe godt», og jeg klarer ikke å stå imot. Nok en skuffelse og dårlig samvittighet!

Det er nok heller ikke sånn at de som har et problem med å spise for mye sjokolade eller noe annet usunt, ellers har et feilfritt kosthold som vil gi dem optimal helse. De fleste har et par tanker om at de enten spiser for lite fisk, for lite grønnsaker, frukt eller burde være flinkere til å drikke mer vann. Allikevel er det oftest endring i forhold til de usunne matvarene som står i fokus – gjerne fordi det er forbundet med vekt. Har du prøvd utallige ganger å få en bedre livsstil ved å kutte ned på ting du spiser for mye av, kanskje det er på tide å prøve motsatt strategi; spise mer av mat som er positiv for helsen din. Det er mye enklere å innføre noe, enn å fjerne, tror jeg.

For en liten stund, legg bort alle tanker om for mye sjokolade og pizza. Hva er det du kunne tenkt deg å endre på i kostholdet ditt som vil gi deg bedre helse, ved at du tilfører noe? Spise mer laks? Spise brokkoli oftere? Øke fra 1 til 2 frukt om dagen? Her gjelder det å sette seg et lite mål i første omgang. Valnøtter er sunt, spiser du noe av det? Kunne det vært et mål å begynne å spise 5 valnøtter daglig? Annen hver dag? 4 dager i uken? Dette er et forholdsvis enkelt mål, og noe som allikevel kan være veldig positivt for helsa di. Avokado er sunt, spiser du noe av det? Hva om du begynner å ha avokado som pålegg på brødskiva 2 dager i uken? Det er veldig godt sammen med salt og pepper. Gulrøtter har alle godt av å spise, kjøper du en pose gulrøtter en gang i uka, kan du gjøre det til en vane å alltid ha med gulrot sammen med lunsjen.

Tenk gjennom hva det er du har lyst til å tilføre av sunne matvarer i kostholdet ditt, og velg en av disse. Her gjelder det å ikke sette seg for store mål, samtidig som det bør være helt konkret for at du skal klare å gjennomføre det. Hvis du bare bestemmer deg for at du skal spise en gulrot daglig, og ikke når på dagen du skal spise den, så kommer du garantert til å glemme den gulroten, eller kanskje komme på det i løpet av dagen men tenke «tar det senere». Hvis du imidlertid bestemmer deg for at gulrot skal være fast innslag i lunsjmatpakken, da er det mye større sannsynlighet for at dette vil skje. Du bør også tenke gjennom hva det er du må gjøre for å klare å gjennomføre denne nye vanen. Hva må du handle på butikken? Hvor skal du ha det tilgjenlig hjemme? Må du ha huskelapp de første dagene? Alarm på telefonen? Legg til rette for at du skal klare å gjennomføre!

Når man har klart å gjort en endring, og synes det har blitt til en god vane, kan man begynne med en ny. Hva er så det neste du har lyst til å tilføre? Og sånn fortsetter man, kanskje kan man klare å innføre to endringer samtidig, det må man ta stilling til selv, basert på hvilke erfaringer man har med livsstilsendringer.

Kostholdet mitt er langt fra perfekt, og jeg skal love deg at det dukker ofte opp tanker om hva jeg burde spise mer eller mindre av, men å omsette teori til praksis er ikke alltid så enkelt. Nå skal jeg derfor sette meg mitt eget mål som jeg skal følge fremover. Jeg skal ikke fjerne noe fra kostholdet mitt, men jeg skal tilføre. Mitt mål blir å starte og avslutte dagen med et stort glass vann. Og grunnen til at jeg velger akkurat det, er rett og slett fordi jeg har drukket litt for lite væske den siste tiden, og ved å sette meg et slik konkret mål, så vet jeg at det er mye større sannsynlighet for at jeg klarer det. Og du, jeg starter ikke på mandag, jeg starter i dag!
