---
title: "Sunt kosthold på studentbudsjett"
date: 2012.11.06
---

Det hevdes ofte at det er dyrt å spise sunt. Selv om vi vet at nordmenn er blant de menneskene i verden som bruker desidert minst andel av inntekten vår på mat, så er det spesielt en gruppe som kan møte litt utfordringer, nemlig studentene. En stor andel av studielånet går med til å betale husleien, og jobber du ikke ved siden av studiene, så har du valget mellom å klare deg på et svært begrenset budsjett eller spise av sparepengene.

Det er ingen tvil om at et sunt kosthold er en av grunnstøttene for å utvikle god helse og holde sykdommer på avstand. Men hvordan skal du klare å spise sunt når de økonomiske midlene er begrenset, sunt mat er jo dyrt? Her kommer noen tips!

## Prioriteringer

Det første punktet på denne listen gir seg selv. Det hele handler om prioriteringer. Prioriterer du å bruke pengene dine på andre ting, og heller sparer inn på matbudsjettet, så må du også belage deg på at dette går ut over kvaliteten på maten du spiser. Hvor mye penger svir du av på byturer i helgene? La oss si det går 7-800 kroner på byen annenhver helg, det blir fort 1400-1600 kroner i måneden. Ta ut 4-500 kroner på forhånd, la bankkortet ligge igjen hjemme (ta for all del med deg annen ID), og vips så har du 600 kroner ekstra å bruke på mat den måneden.

En annen ting som spiser godt av budsjettet er ting som sjokolade, chips, godteri og lignende. Om du har et begrenset matbudsjett så er dette, ved siden av alkoholen, de første postene som bør reduseres. Det er også lett å tygge opp en del penger i form av tyggis om du bruker mye av dette.

## Økonomiske kostråd

Det å investere i egen helse er svært gunstig på lang sikt, og selv om det ikke på noen måte sikrer deg mot å utvikle helseplager, så reduserer det risikoen betydelig. Likevel betyr ikke dette at det er nødvendig å tømme hele bankkontoen for å spise sunt, og her følger noen konkrete råd som burde gjøre det mulig å få til et sunt kosthold på studentbudsjettet:

### Drikk vann

Brus, saft, jus og energidrikker kan bli en solid utgift om det blir et innslag i det daglige kostholdet. Her i Norge er vi velsignet med springvann av svært høy kvalitet, så her er det ingen unnskyldninger for å ikke spare litt penger. For helsen sin del er det også et poeng å [redusere inntaket av flytende karbohydrater](http://www.friskogfunksjonell.no/bor-du-begrense-inntaket-av-flytende-karbohydrater/ "Bør du begrense inntaket av flytende karbohydrater?"), så vann kommer godt ut også her!

### Frossengrønnsaker

Grønnsaker bør ha en stor plass i kostholdet ditt, og generelt sett spiser vi alt for lite av denne matvaregruppen. En enkel og billig måte å øke grønnsaksinntaket på er å benytte seg av frossengrønnsaker. I motsetning til det enkelte tror så inneholder ikke frossengrønnsakene mindre næring enn ferske. Faktisk inneholder de ofte mer! En annen fordel med frossengrønnsaker er at du ikke trenger å bruke mye tid på tilberedning. Kok opp vann og la grønnsakene varmes godt opp, eller stikk noen huller i posen og sleng den i mikrobølgeovnen, så er det ferdig på noen minutter.

Ferske grønnsaker kan også være billige, hovedsakelig de som er i sesong. Hermetiske varianter er heller ikke det som ruinerer deg.

### De etter tilbud og frys ned

Det dukker stadig opp forskjellige tilbud i de ulike butikkene, og her er det penger å spare. De fleste har tilgang på en fryseboks, og ved å kjøpe inn større kvanta og heller fryse ned kan du komme godt ut. Mange butikkjeder har også egne merkevarer som er en del billigere enn de kjente merkene, uten at kvaliteten trenger å være noe dårligere av den grunn. I ferskdisken kan du også fra tid til annen finne reduserte priser, og det samme gjelder hos slakterforretninger.

### Kjøp inn større partier

Stort sett vil kiloprisen reduseres jo større pakker du kjøper. Ved å se på kiloprisen i stedet for stykkprisen kan du få deg noen oppvekkere, og potensielt spare en del penger. Kombinert med tipset om å fryse ned er det mye å hente her.

### Planlegg innkjøpene!

Ved å planlegge hva du skal lage til de ulike måltidene kan du spare en del penger på butikken. God planlegging kan gjøre at du kaster mindre mat, siden du i større grad kan bruke råvarene over flere dager i stedet for at det blir liggende og blir dårlig.

Det å planlegge matinntaket litt frem i tid reduserer også sjansene for å gå på en smell med unødvendige impulskjøp som potensielt kan være ganske negative for økonomien. Kjøp inn det du vet du trenger i løpet av uken, og sett deg gjerne ned søndags kveld, sett opp et matbudsjett og en meny. Bor du i kollektiv kan det være en god plan å lage middag sammen.

### Ikke kast matrester

Vurderer du å kaste den ene laksefilèten og salatrestene som er igjen etter middagen? Skjerpings! Dette kan bidra til en luksuriøs skolelunsj dagen etter som, om ikke annet, vil få deg til å se rikere og mer fornuftig ut enn du egentlig er! Tilberedt mat holder seg helt fint over natta og garantert brukes dagen etter. Mange har også tilgang på mikrobølgeovn i kantinen på studiestedet, noe som er enda et argument for å velge denne metoden! Dette med middagsrester til lunsj inngår også i forrige punkt om planlegging.

### Rimelige kilder til de ulike næringsstoffene

Energien i kostholdet vårt får vi fra karbohydrater, fett og protein. Alle disse har en plass i kostholdet, og ekstremdietter den ene eller andre veien er sjelden en god løsning for majoriteten av befolkningen. Fokuset bør, som jeg har nevnt tidligere, ligge på [kvaliteten på matvarene](http://www.friskogfunksjonell.no/lavkarbo-eller-lavfett-er-dette-riktig-fokus/ "Lavkarbo eller lavfett, er dette riktig fokus?"). Her kommer eksempler på gode kilder til de ulike næringsstoffene til rimelige priser.

### Proteinkilder

Protein av [god kvalitet](http://www.friskogfunksjonell.no/proteinkvalitet/ "Alt du trenger å vite om proteinkvalitet") finner vi hovedsakelig i animalske matvarer som kjøtt, fisk, egg og meieriprodukter. Dette er matvarer som kan legge beslag på store deler av ditt matbudsjett, og det kan være gunstig å se an kiloprisen for å finne det mest økonomiske valget.

Frosne kyllingfileter i store pakker er billig. Det samme er sei, torsk og annen frossen/fersk fisk. Tunfisk på boks og makrell-i-tomat fra billigmerkene er et rimelig og fint tilskudd til lunsjen. Svinekjøtt, enten i form av koteletter eller strimlet, koster ikke all verden, og av farseprodukter er kyllingkjøttdeig, svinekjøttdeig og karbonadedeig rimelige alternativer. Egg er en svært anvendelig matvare, og bør alltid være tilgjengelig i kjøleskapet. De største pakkene er de billigste.

### Fettkilder

Fett er et viktig næringsstoff som inngår i alle kroppens celler og er en viktig energikilde. De fleste gode proteinkildene inneholder også en del fett, slik at behovet for mye fett utover dette er minimalt. Et viktig poeng med fettinntaket rent helsemessig er å sikte mot en god fordeling av [omega-3 og omega-6](http://www.friskogfunksjonell.no/omega-3-og-omega-6-i-kostholdet/ "Omega-3 og Omega-6 i kostholdet"), siden disse gir opphav til signalstoffer som er med å regulere mange kroppslige prosesser.

Smør, kokosolje, olivenolje, rapsolje og valnøttolje er gode fettkilder. Husk at du ikke bruker så mye av disse om gangen, slik at de vil vare en god stund. Derfor vil jeg anbefale å prioritere kvalitet foran pris akkurat på disse matvarene. Hvordan du finner matoljer av god kvalitet har jeg skrevet mer om [her](http://www.friskogfunksjonell.no/3-tiltak-del-3/ "Enkle tiltak som kan forbedre kostholdet ditt – del 3"), men som et kjapt sammendrag bør du se etter kaldpressede oljer på mørke flasker.

### Gode karbohydratkilder

Karbohydrater er den energikilden som er enklest å benytte for kroppen, og myndighetene anbefaler at mesteparten av energien vår bør komme fra nettopp karbohydrater. Likevel er det etterhvert mange holdepunkter for å anbefale en reduksjon av karbohydratinntaket, spesielt for de som er mindre aktive. Her vil egne preferanser være det som veier tyngst, så velg ut ifra hvilken mat du trives best med å spise. For lommeboken sin del er karbohydrater et godt valg, så på et begrenset budsjett kan det være greit å ikke styre helt unna.

Potet og ris er svært billige matvarer, og bidrar med lett tilgjengelig energi i form av stivelse. Når det gjelder korn så er det noen som reagerer når de spiser større mengder, men om du ikke opplever slike plager er også pasta et billig alternativ. Havregryn er svært anvendelig, og kan brukes både alene og i bakst.

Frukt er også en god kilde til karbohydrater og mange mikronæringsstoffer. Ved å se deg litt om i fruktavdelingen finner du fort ut at prisene varierer mye i løpet av året, og den frukten som er i sesong er den billigste. Frukt er ypperlig som dessert, som del av et sammensatt måltid eller som kosemat. Mange vil hevde at frukt er dyrt, men om du sammenligner kiloprisen med godteri og sjokolade så kommer frukten soleklart best ut!

Enkle tips til å forbedre kostholdet finner du i følgende artikler:

-   [3 tiltak som kan forbedre kostholdet ditt - del 1](kosthold-tiltak-1.qmd "Enkle tiltak som kan forbedre kostholdet ditt – del 1")

-   [3 tiltak som kan forbedre kostholdet ditt - del 2](kosthold-tiltak-2.qmd "Enkle tiltak som kan forbedre kostholdet ditt – del 2")

-   [3 tiltak som kan forbedre kostholdet ditt - del 3](kosthold-tiltak-3.qmd "Enkle tiltak som kan forbedre kostholdet ditt – del 3")

Takk til Thomas Olsen og Ingvild Thun for innspill og diskusjon!
