---
title: "Tallerkenmodellen som pedagogisk verktøy"
date: "2012.05.09"
---

Det er mange ulike måter å kommunisere kostråd på. Kostsirkelen og matvarepyramiden er to av de mest kjente symbolene på hvordan et kosthold i myndighetenes øyne bør se ut. For å enkelt veilede i hvordan man bør legge opp hvert måltid er tallerkenmodellen kanskje den mest kjente. Hva er fordelen med tallerkenmodellen, og hvordan kan og bør den brukes?

## Hva sier tallerkenmodellen?

Kort fortalt sier tallerkenmodellen til myndighetene at du bør legge opp hvert måltid slik at proteinkilden (kjøtt, fisk, egg) dekker 1/3 av tallerkenen, potet/pasta/ris dekker 1/3 og den siste 1/3 utgjøres av salat eller grønnsaker. Ved vektnedgang anbefales det at salat/grønnsaker utgjør halve tallerkenen, mens protein og karbohydrater da får 1/4 hver.

For den jevne befolkning er dette et helt greit holdepunkt, og om alle hadde fulgt dette ville vi helt klart vært en friskere befolkning. Problemet med en slik tilnærming er at den ikke tar hensyn til individuelle forskjeller og preferanser. Skal f.eks. en diabetiker legge opp måltidene sine på denne måten, eller finnes det [bedre alternativer](brokenlink/hvordan-bor-en-diabetiker-spise/ "Hvordan bør en diabetiker spise?")?

## Fordeler med tallerkenmodellen

Tallerkenmodellen og lignende verktøy byr på flere fordeler. For det første er den veldig enkel å forstå seg på, da den gir et oversiktlig bilde over hva du bør legge på tallerkenen. Snakker du til en som ikke har satt seg inn i kosthold, vil det i de fleste tilfeller være mye mer effektivt med et slikt bilde enn å snakke om karbohydrater, proteiner og fett.

En annen fordel, og etter min mening den aller største fordelen, er at det er enkelt å tilpasse denne modellen til den enkeltes behov. Her kan man ta hensyn til alt fra allergier og intoleranser, til personlige preferanser angående hvilken mat man liker å spise. Denne allsidigheten gjør tallerkenmodellen til et kjempeverktøy innen kostveiledning.

## Bruksområde

Innen kostveiledning ser jeg absolutt på tallerkenmodellen som et veldig nyttig verktøy, nettopp på grunn av at den er så enkel og fleksibel. Brukt på store grupper har denne modellen sine begrensninger, men så lenge man klarer å kommunisere at den bare representerer et utgangspunkt ser jeg ikke noe stort problem med det. For å kommunisere individuelle kostråd til personer uten forhåndskunnskaper om kosthold er denne modellen derimot helt suveren!

Du som leser her på siden har etterhert plukket opp en god del gode tips om hvordan et sunt kosthold bør være. Neste gang du skal hjelpe noen andre med kostholdet, hvorfor ikke bruke tallerkenmodellen?
