---
title: "Tren som en idrettsutøver - se ut som en!"
author: 
  - "Vegard Lysne"
  - "Torbjørn Lysne"
date: "2011.11.12"
categories: 
  - trening
---

Det er ingen hemmelighet at veldig mange først og fremst trener for å se bedre ut. Det er ingenting galt i dette, og alle må få lov til å hente motivasjon der de finner den! Men hvordan ender folk flest opp med å legge opp treningen sin utifra de målene de har satt seg?

Det er ikke uvanlig at folk søker opp første og beste kroppsbyggersplitt og setter igang. Rygg og biceps på dag en, bryst og triceps dag to, og bein og skuldre den tredje dagen. Hver muskelgruppe må ikke trenes mer enn en gang i uken, for det er viktig med syv dager hvile mellom hver gang muskelen belastes. Kondisjonstrening begrenses til rolige gåturer, for intensiv kondisjonstrening vil selvfølgelig føre til tap av muskelmasse, og det er det viktig å begrense. Kostholdet er også viktig, så

man kjøper inn både proteinpulver, kreatin og weightgainer. Nå er alt tilrettelagt, og drømmekroppen er rett rundt hjørnet!

Er dette den mest hensiktsmessige måten å legge opp treningen på? Vi synes ikke det, og hvorfor skal vi forklare her. Når vi diskuterer hvem som har en bra fysikk, så kommer vi raskt til toppidrettsutøvere. Har disse utviklet fysikken sin ved å trene etter kroppsbyggerprogrammer, eller har de som hovedfokus å se bra ut? I noen tilfeller er svaret sikkert ja, men i de fleste tilfellene ligger nok fokuset et helt annet sted.

## Hva fokuserer en idrettsutøver på?

En toppidrettsutøver trener hovedsakelig for å bli bedre i idretten sin. Dette innebærer selvfølgelig mange timer med spesifikk trening på akkurat denne idretten, men også mye fysisk trening utover dette. Det er den fysiske treningen som gir grunnlaget for å tåle de store treningsmengdene som skal til for å nå toppen, og det er også denne som har mye av æren for hvorfor en toppidrettsutøver ser ut som han/hun gjør.

Når det gjelder den fysiske treningen, er ikke målet å se bra ut, men å øke den fysiske kapasiteten. I styrkerommet handler dette først og fremst om å bli sterkere og mer eksplosiv, noe som gir grunnlag for å kunne løpe raskere og hoppe høyere. Når det gjelder utholdenhetstreningen, vil hovedmålet være å øke det maksimale oksygenopptaket. Med mindre du driver med langdistanseidrett, vil rolige langturer ha en veldig begrenset rolle i det totale treningsopplegget.

## Hvor vil vi med dette?

Dersom du trener fordi du ønsker å se bedre ut, er det kanskje på tide å flytte fokuset vekk fra dette, og over på økte prestasjoner. Dersom du over tid klarer å løfte tyngre, løpe raskere, hoppe høyere eller forbedre et annet mål på fysisk kapasitet, så har du sannsynligvis i samme periode også fått en bedre fysikk.

Når det gjelder vårt syn på treningsfrekvens, hvor ofte du trener, så kan dette oppsummeres i følgende uttrykk: «Det du ønsker å bli bedre på, må du gjøre ofte». For en idrettsutøver vil dette innebære at man trener på den aktuelle idretten flere ganger i uken. For deg bør det innebære det samme. Det er ingen grunn til å vente en hel uke før du igjen belaster en muskel du har trent. Musklene er klare for ny økt 24-72 timer etter forrige økt, alt etter hvor hardt du har trent, og faktisk så viser flere studier at muskelveksten og styrkeøkningene er bedre om du belaster en muskel 2-3 ganger i uken sammenlignet med en gang.

## Hva så med kostholdet?

Kostholdet har selvfølgelig veldig mye å si for resultatet. Det å forbedre kroppen sin innebærer for mange å gå ned litt i vekt, slik at musklene kommer bedre fram. Når det gjelder å redusere mengden kroppsfett, vil kostholdet være langt viktigere enn selve treningen. Som Kenn Hallstensen pleier å si: "Kosthold er kilo, trening er gram", et uttrykk som langt på vei beskriver virkeligheten. Et godt sammensatt kosthold gir også et mye bedre utgangspunkt for resitusjonen, slik at du raskere er klar for neste treningsøkt!

Hvordan du best mulig kan legge opp kostholdet for å nå dine mål avhenger av mange faktorer som hvilken mat du liker, hvilket måltidsmønster som passer din hverdag, og ikke minst hva målene dine er. Dette blir tema en annen gang!
