---
title: "Ulike kosthold – samme mål?"
author: "Daniel Bieniek"
date: 2015.01.21
---

Den 15.01.2015 ble den årlige fagdagen for samfunnsernæring ved høyskolen i Oslo og Akershus arrangert. Tema for dagen var de ulike tilnærmingene som er aktuelle i ernæringsdebatten i Norge.  Dette er et kort sammendrag av de respektive foredragsholdernes presentasjoner. Det var totalt fem foredragsholdere, og en oppsummering til slutt. 

## Paleo – hva er det og hva det ikke er

Førstemann ut var Pål Jåbekk som har mastergrad i idrettsvitenskap og leder fagrådet i foreningen Kostreform for bedre helse. Jåbekk ønsket å diskutere steinalderkost fra et vitenskapelig ståsted. Det ble presisert at dette kostholdet er et logisk rammeverk for moderne mennesker og ikke et forsøk på en historisk gjenskaping av å leve som en steinaldermann. Han fremhevet mest mulig «naturlig mat i alle ledd». Kuer skal spise gress og vi bør ekskludere korn, belgfrukter, sukker, frøbaserte planteoljer og melkeprodukter, som ikke kan regnes som menneskemat. Han mener at dagens livsstilsykdommer i stor grad skyldes moderne kosthold.

Med et sitat om at det som er naturlig ikke er usunt dro han paralleller til korn. Jåbekk mener mennesket ikke er designet for å spise dette. Han fremhevet videre jeger og samlerkost, der hovedprinsippene er å spise lokal, sesongbasert mat samt innmat.

Jåbekk avsluttet med at bevisbyrden ligger hos dem som fremmer myndighetenes kostråd, og han mener at dagens retningslinjer ikke er vist å være sunnere enn steinalderkost. Videre mener han at aspekter som bærekraftighet og miljø må komme i andre rekke etter matvarene han mener er sunnest.

## Råkost og høykarbo for reversering av livsstilsykdommer

Asgeir Brevik er førsteamanuensis, studieleder for samfunnsernæring HiOA og råkost-tilhenger. Han åpnet opp med med sterke referanser til dyreverden, «alle dyr spiser maten rå».

Sykdom i egen familie var hovedinspirasjonen for å starte med et slikt kosthold, som i praksis har vært utfordrende, blant annet med tanke på kalorier, kostnader og sosialt. Å dekke proteininntaket var imidlertid uproblematisk og viste til egen kostdagbok.

Påståtte helsefordeler av råkost var fraværet av stekemutagener, transfett, hydrolyserte oljer, L-karnitin, TMAO (trimetylaminoksid), og AGE (avanserte glykosylerte endeprodukter). Det ble fremhevet at råkost inneholder mye fiber, lite animalsk protein og er alkaliserende, gir bedre syn relatert til inntak av karotenoider, mindre hudproblemer, et dramatisk forbedret immunsystem og reversering av livsstilsykdommer.

Sammenhengen mellom kalorirestriksjon og et langt og friskt liv ble viet mye oppmerksomhet. Det ble vist til forsøksdyr hvor et slikt kosthold forlenget livet med 30-40 %. Han påpekte at denne gunstige effekten forsvinner om dyrene spiser animalsk protein trolig grunnet assosiasjonene med kreftutvikling.

Brevik rettet videre kritikk mot steinalderkosthold. Han nevnte blant annet at mye tyder på at mennesker har spist korn lenger enn antatt. Han mener jordbruksrevolusjonen var nødvendig for den menneskelige utviklingen, og at vi uten denne ikke hadde hatt muligheten til å brødfø befolkningen.

Han avsluttet med at retningslinjene i USA nå tar utgangspunkt i et plantebasert kosthold og ønsker et paradigmeskifte i retning rawfood i løpet av hans levetid.

## Hemmeligheten til god helse

Gry Hammer er forfatter, foredragsholder og blogger, og mener hemmeligheten til god helse ligger gjemt hos våre forfedre, med fokus på tradisjonsmat. Hun viste til en graf som viste hennes tidligere feilslåtte forsøk på å følge ulike dietter og inkluderte vegetarkost, blodtypediett, middelhavsdiett, supermat, rawfood og fleksitarianer.

Hammer nevnte at forskning på dyr som får naturlig mat til fordel for eksempelvis soya, som hun mener er unaturlig, viser at fettsyresammensetningen er mer gunstig som i tur kan være av betydning for helsen vår. Eksempelvis kan fjærkre ha et høyere innhold av omega-3-fettsyrer gitt en mer gunstig fôrsammensetning. Hun kritiserte videre kraftfôr på et generelt grunnlag i debatten om økologisk og konvensjonelt landbruk.

Subjektivt «flyttet det fjell» å benytte seg av tradisjonsmat for å unngå potensielle livsstilsykdommer. Tradisjonsmat baserer seg på naturlig mat og hun trakk frem upasteuriserte meieriprodukter, viltkjøtt, økologisk dyrket frukt & grønt samt uraffinert salt som eksempel til fordel for problematiske matvarer som melkemat, raffinerte planteoljer, korn, soya og raffinert salt.

Avslutningsvis ble det hevdet at kjøttkraft bygger immunforsvaret, styrker hjertefunksjonen og «avgifter» kroppen. Hammer viste til det hun mente var solid evidens, og understreket at dette ikke var hennes egne ord. Som en oppsummering burde tradisjon og erfaring derfor ha mer å si fremfor en mer vitenskapsbasert tilnærming til hva vi burde spise.

## Ernæringsepidemilogi og offiselle kostråd – fra grøtstrid til smørkrise.

Erik Arnesen har en mastergrad i samfunnsernæring og jobber som helsefaglig rådgiver i landsforeningen for hjerte- og lungesyke. Han skriver jevnlig om kosthold og kritisk tenking på sin egen blogg «Sunn Skepsis», er redaksjonsmedlem i Norsk Tidsskrift for Ernæring og ble nylig valgt inn i Nasjonalt råd for ernæring.

Arnesen åpnet opp med den tilsynelatende evige debatten om hva befolkningen skal spise. l året 1865 pågikk det en «grøtstrid» som kulminerte i Norges trolig første vitenskapelige kostholdsstudie (av Frans Faye, 1866). Trolig hadde to av tre nordmenn den gang grøt som en stor del av kostholdet og spiste dette flere ganger daglig. De første offisielle anbefalingene på befolkningsbasis kom i 1939 fra «Statens kostholdsnemnd», og hensikten var å sikre et sunt kosthold, men moderne hygieniske krav ble vektlagt mer enn hva som trolig var optimalt. I etterkrigstiden endret dette seg og fokuset ble rettet mot landbruksproduksjon og selvforsyning. Parallelt økte insidensen relatert til hjerte-kar sykdommer, og dødeligheten for menn økte med over 90 % i løpet av 1950-årene. Det ble etter hvert foreslått mulige sammenheng mellom kosten og hjertesykdom.

I 1960 foreslo Nicolaysen-komiteen å redusere fett til under 30E%. Selv om evidensgrunnlaget var tynt ble det argumentert at risikoen for å ikke handle var større. Dette baserte seg på lav dødelighet av iskemisk hjertesykdom i land hvor fettinntaket var \<30E%. I 1963 foreslo den samme komiteen at 10 % av fettet i kosten skulle være flerumettet, dette er også dagens anbefalinger. Forslaget møtte motstand, hovedsakelig fra matindustrien grunnet salget av matvarer som helmelk og fløte, som til da hadde vært sett på som «sikringskost». Nicolaysen-komiteens anbefalinger førte ikke til betydelige ernæringsmessige endringer i befolkningens kosthold.

Hjerteproblematikken fortsatte, og i 1975 framla Landbruksdepartementet forslag til norsk ernæring og matforsyningspolitikk. Målet var å fremme et helsemessig kosthold og å bruke landets ressurser best mulig. Det ble nødvendig med økt subsidiering for landbruket og derfor trengte man en ernæringspolitikk som kunne fremme et slik tiltak. Det politiske målet om et fettinntak hos befolkingen \<35E% ble nådd før 1990.

Deretter endret tematikken seg mot dagens kostråd og evidensgrunnlaget bak disse. Dagens kostråd har nå fokus på matvarevalg, og makronæringsstoffene kommer i andre rekke. Kostrådene bygger på  helheten av ernæringslitteraturen, . Her er det ikke rom for personlige meninger, og man bygger i hovedsak på metaanalyser og systematiske oversikter (oppsummeringer av forskning).

Arnesen avsluttet med å understreke at man ikke kan gi offentlige råd basert på en individuell studie, uavhengig av hvor god denne måtte være. Selv om nye enkeltstudier kan bringe mye på bordet, vil likevel totalen av forskningen som er gjort fremdeles veie tyngst. Dette inkluderer også eldre studier.

## Nutrigenomics – ny metodologi for fremtidens kostråd.

Stine Marie Ulven er førsteamanuensis og ansatt ved Samfunnsernæring. Hun er forskningsgruppeleder for gruppen Humane kostforsøk og helseeffekter, som fokuserer på fettsyrer og hjerte- og karsykdom. Stine har en doktorgrad i ernæringsbiologi fra Universitetet i Oslo

Nutrigenomics omhandler hvordan kostholdet interagerer med genvarianter. En rask introduksjon av DNA-molekylet forteller at én celle består av rundt 3 milliarder basepar og koder for ca. 30 000 gener. Selv om 99,9% er likt internt mellom mennesker, kan den siste promillen være av stor betydning. Tilfeldige feil i koding av aminosyrene fører til mutasjoner som kan gi stor variasjon.

Målsetningen er å kunne bruke denne informasjonen til å gi personlige kostråd basert på den individuelle genotypen. Ved å få en genetisk profil så kan man se hva man er disponert for og ikke, og dette kan gi informasjon om hvilket kosthold man bør ha. Ny teknologi, der vi i dag kan ta for oss hele genomet på en gang, gir oss muligheten til å studere hvordan maten påvirker hele systemet, og da kan vi også klare å identifisere biomarkører som kan resultere i individrettede kostråd. Men før vi kommer dit må man dokumentere helseeffekter, noe som per dags dato ligger et stykke frem i tid.

For å bedre kunne avdekke sammenhenger mellom miljøfaktorer og sykdom, må fremtidige studier inkludere bedre metoder for blant annet å samle inn kostdata. Avdelingen Samfunnsernæring kan ha mye å bidra med i fremtiden: «Det er ønskelig å integrere samfunnsernæring og molekylærernæring for å forbedre metoder for å registrere matinntak, finne objektive og gode metoder ved matinntak. Og få mer kunnskap fra ernæringsepidemiologiske studier og nasjonale kostholdsundersøkelser»

## Oppsummering

Førsteamanuensis Kjell Sverre Pettersen oppsummerte dagen, og delte sine tanker. Han startet med å takke forsamlingen og rettet en generell kritikk mot det å fokusere på «det naturlige». Han minnet om at naturlig og evolusjonsmessig ikke er synonymt med optimalt. Samtidig presiserte han at et kosthold som man finner i mest mulig naturlig tilstand, neppe er galt. I Asia er ris et helt naturlig kosthold, uten at dette må være noe negativt. Han påpekte at svært få av den norske befolkning har tid til å dra ut i Nordmarka for å jakte, eller ut i Oslofjorden for å fiske. Det er rett og slett for mange mennesker i  samfunnet til at et paleokosthold vil la seg gjennomføre for alle. Helt til slutt oppfordret han oss til å huske på viktigheten av å ha en vitenskapelig holdning til ernæring!
