---
title: "Underholdningsslavens redning"
author: "Asle Bøe"
date: 2012.11.13
---

Inaktivitet er din herre, og du har blitt en slave av lysende skjermer og underholdning. Iløpet av en dag bruker du flere timer liggende eller sittende i forhold til antall timer du bruker på dine ben og på bevegelse. Flott tenker du, men jeg trener jo. Trening er bra, men hva med de resterende 23 timene?

Det finnes mange tips for å øke hverdagsaktiviteten, men felles for dem alle er det at du egentlig ikke vil gjøre det du har godt av for enkelhetens og behagelighetens skyld.

-   Gå av bussen to stopp før? Komme hjem 10 min senere!

-   Gå og handle istedenfor å kjøre? Gå glipp av favorittserien!

En får ikke raske resultater av å gjøre disse endringene, og da tar mange til den enkleste løsningen. Tiltakene er enormt enkle, men gjennomførelsen viser seg problematisk for mange. Hvem hadde ikke klart å gå en time hver dag om målet er vektnedgang og bedre helse? Hvor idiotiske unnskyldninger aksepterer vi fra oss selv og andre?

## Utfordringen

Selv har jeg store problemer med dette - internett er stort og kjekt, og jeg bruker enormt med tid på å lese og lete etter informasjon jeg håper vil gjøre meg bedre.

Jeg kommer likevel ikke unna at mens jeg leser om ting som kan hjelpe meg og andre å øke livskvaliteten sin og treningsresultatene gjør jeg noe som det er fint lite vits i - sitter på en stol. Selv om jeg korrigerer hyppig merker jeg at jeg hele veien går inn i ugunstige arbeidsstillinger.

Her kommer noen enkle forslag til hvordan en kan, som Ole Brum så fint sier det, si :'Ja takk, begge deler!'

En av grunnene til at vi blir mer og mer stillesittende er nok at underholdning er så lett tilgjengelig på en skjerm. Gjennomsnittspersonen bruker gjerne 6 timer på medier iløpet av en dag, men mange av oss bruker mye, mye mer.

Hvorfor sitte og lese? Hvorfor sitte og se en film?

Jeg vil foreslå at du legger en plan. Si du skal se en episode av favorittserien din. Velg deg noe du kan jobbe med ved siden av som gjør at du er i bevegelse.

-   En halvtimes [egenmassasje](http://myrevolution.no/s/enkel-og-effektiv-egenmassasje/) med massasjerulle? Flott.

-   Yoga? Kjempegreier.

Ta med nettbrettet til treningsstudioet og gå en time på møllen mens du leser en artikkel eller ser foredraget om knebøyteknikk før økten med [André og Erle](http://myrevolution.no/blogger/kneboy-benkpress-og-markloftworkshop-med-erle-engmark-og-andre-midtby/)? God ide!

Jobbe med aktiverings og mobiliseringsøvelser med strikk? Øve inn en ny runde med dynamisk oppvarming før neste trening?

## Underhold meg!

Behovet for underholdning er der, men det behøver ikke bety at den skal inntas sittende eller lett henslengt på sofaen. Dersom du gjør dette en gang pr dag vil du kunne merke svært gode resultater.

Tenk hvor mye det er mulig å få til om du plutselig øker [aktivitetsnivået](brokenlink/aktivitetsniva-helse/) med 3.5 til 7 timer i uken! Tenk på effekten på bevegelighet, vonde og stive rygger, nakker og knær - tenk på muligheten for å hver dag kunne gjøre noe som føles bra samtidig som du blir underholdt og har det kjekt.

Plutselig er det ikke et ork å gjøre disse tingene lengre, det må ikke prioriteres . Du gjør det automatisk når du slår på TVen eller nettbrettet.

Da jeg studerte var den eneste måten jeg klarte å lese på om jeg gikk samtidig - plutselig fikk jeg både studert 2 timer hver dag jeg ellers ikke hadde giddet, samtidig som jeg fikk beveget meg.

Å være kreativ slik er ikke bare tidsbesparende, men veldig artig når en kommer inn i det.

Har du sett en hund gå og svinse med halen og snuse med nesen når den går tur? Hjernen tar helt fyr, og hunden tenker ikke ' jaja, 25 min igjen nå \@ 65% av makspuls så har jeg forbrent den [tacoen](brokenlink/er-taco-farlig/) fra igår.' Den blir styrt av instinktene sine og konstant stimulering. Vi er mer visuelle av oss, så vår hjerne elsker å få mat gjennom øynene i form av visuell underholdning.

En av grunnene til at vi er i det uføret vi er kan sies å være kreativiteten vår og evnen til å forandre omgivelsene. Det er vår største styrke og svakhet - hva det skal være for deg kan du bestemme selv.

En av de største utfordringene, også for oss som trener er hverdagsaktiviteten og hva de ugunstige kroppsstillingene gjør med oss over tid. Å tilbringe mer tid i bevegelse og mindre tid sittende er en god start. En merker raskt effekt, og det motiverer til å gjøre mer.

## Mange små steg blir fort en lang tur

Summen av små endringer som dette over tid blir for mange en sterkere, mer funksjonell kropp som øker livskvaliteten og prestasjonene på trening og i hverdagen.

Sånn, nå har du sittet lenge nok! Gå og sett på en serie eller to mens du får fyr i stumpen og rullet ut kranglete kroppsdeler.

Originalartikkel hentet fra: [Asles innlegg på MyRevolution.](http://myrevolution.no/s/underholdningsslavens-redning/)
